### PR TITLE
Suppress verbose build output

### PR DESCRIPTION
**Pull request by bmson**
Issue: #1872

## What I did
 This is bit of a stab in the dark to address the output noice in Storybook.
Added `--quiet` to the CLI command list, so we can conditionally load the `webpack.ProgressPlugin`.

## How to test
`yarn test --cli`

### CODE REVIEW

**Comment by bmson** [comment]
The circleci errors seem unrelated to this PR »`Bad credentials`

**Comment by Hypnosphi** [comment]
I've changed the PR base to `master` because we need to apply this change to mithril app as well. But it’s probably easier to open a new one than to resolve the conflicts

Please also document this option
https://github.com/storybooks/storybook/blob/master/docs/src/pages/configurations/cli-options/index.md

**Comment by Hypnosphi** [comment]
Please update config for app/mithril

**Review by Hypnosphi — APPROVED** [review]

**Comment by benniemosher** [comment]
Was this only applied to the `start-storybook` command? The docs don't have the `--quiet` option for `build-storybook` and the CLI is not accepting it. How hard would it be to get it done there too?

**Comment by ndelangen** [comment]
It should work for both in V5 I think! Can you help us test?

**Pull request merged**
