### PR TITLE
Update Webpack Title

### PR DESCRIPTION
**Pull request by MichaelArestad**
Issue: #17709 

## What I did

I updated the title to be "Storybook loading…". I think it might be better to actually say the name of the Storybook. @kylegach is that something that can be easily done?

## How to test

TBD

### CODE REVIEW

**Comment by IanVS** [comment]
I'm all for this!  It always feels strange to see "Webpack app" in my vite project storybook.  😂

**Review by kylegach — APPROVED** [review]
Nice one!

As far as using the `brandTitle`, that's a great idea, but I've heard talk of moving the non-color-related theme stuff into `main.js` in `7.0` after which it'll be a _lot_ easier to do that.

_Sorry. Just realized this is a draft PR. Feel free to ping me for a re-review, if warranted!_

**Comment by MichaelArestad** [comment]
@kylegach In that case, I think we should get this one in and then follow up post 7.0 to change it to the `brandTitle`.

**Review by ndelangen — APPROVED** [review]

**Comment by artrasoft** [comment]
> I'm all for this! It always feels strange to see "Webpack app" in my vite project storybook. 😂

"Webpack app" even though Webpack isn't involved. Strange

**Pull request merged**
