### PR TITLE
Typescript: Export IStory in `@storybook/angular`

### PR DESCRIPTION
**Pull request by atanasster**
Issue: #9041

## What I did

added export of IStory for compatibility

## How to test

in angular 
`import { IStory } from '@storybook/angular';`

### CODE REVIEW

**Comment by shilman** [comment]
Should we do this for all frameworks?
Isn't this a breaking change?

cc @kroeder @gaetanmaisse

**Comment by atanasster** [comment]
@shilman  seems this is angular specific PR, there was a breaking change that renamed IStory to StoryFnAngularReturnType

https://github.com/storybookjs/storybook/commit/997ce2773dc4d78c3097a02bfb5b33158456c3d5#diff-24186810dba01fce38b56c8e599a9ed5

My change is not breaking, I am only naming as IStory for the export from `client/index.ts`

**Comment by shilman** [comment]
Sorry my bad. You're adding an export, not modifying an existing export. 👍

**Review by shilman — APPROVED** [review]
LGTM

**Comment by shilman** [comment]
@atanasster @kroeder @gaetanmaisse do we want to do this for all frameworks, not just angular?

**Review by shilman — CHANGES_REQUESTED** [review]
Do we want `IStory` to be `StoryFn<StoryFnAngularReturnType>`?

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@shilman YES we do

**Comment by atanasster** [comment]
> Do we want `IStory` to be `StoryFn<StoryFnAngularReturnType>`?

In the breaking change IStory was just renamed to StoryFnAngularReturnType, so I am not sure:
```
 - export interface IStory {
 + export interface StoryFnAngularReturnType {
```

**Review by shilman — APPROVED** [review]
I see. Thanks for the clarification @atanasster

**Pull request merged**
