### PR TITLE
Changed import of react-syntax-highlighter from esm to cjs

### LINKED ISSUE #9279: Syntax Highlighter should import react-syntax-highlighter from CommonJS dist instead of ESModules
**Is your feature request related to a problem? Please describe.**
I have a problem when using Storyshots (It may be a jest misconfiguration, since I'm not really proficient in that, but I've tried everything to fix it), that syntaxhighlighter imports react-syntax-highlighter from it's esm distribution which creates an error for me
```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import jsx from "refractor/lang/jsx.js";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

**Describe the solution you'd like**
I would like to import react-syntax-highlighter from their cjs dist, since syntaxhighlighter component itself is written in commonjs. **This fixed my issue locally.**

Current imports:
```
var _jsx = _interopRequireDefault(require("react-syntax-highlighter/dist/esm/languages/prism/jsx"));

var _bash = _interopRequireDefault(require("react-syntax-highlighter/dist/esm/languages/prism/bash"));

var _css = _interopRequireDefault(require("react-syntax-highlighter/dist/esm/languages/prism/css"));

var _markup = _interopRequireDefault(require("react-syntax-highlighter/dist/esm/languages/prism/markup"));

var _tsx = _interopRequireDefault(require("react-syntax-highlighter/dist/esm/languages/prism/tsx"));

var _typescript = _interopRequireDefault(require("react-syntax-highlighter/dist/esm/languages/prism/typescript"));
```

fixed imports:
```
var _jsx = _interopRequireDefault(require("react-syntax-highlighter/dist/cjs/languages/prism/jsx"));

var _bash = _interopRequireDefault(require("react-syntax-highlighter/dist/cjs/languages/prism/bash"));

var _css = _interopRequireDefault(require("react-syntax-highlighter/dist/cjs/languages/prism/css"));

var _markup = _interopRequireDefault(require("react-syntax-highlighter/dist/cjs/languages/prism/markup"));

var _tsx = _interopRequireDefault(require("react-syntax-highlighter/dist/cjs/languages/prism/tsx"));

var _typescript = _interopRequireDefault(require("react-syntax-highlighter/dist/cjs/languages/prism/typescript"));
```

**Describe alternatives you've considered**
I've been trying to fix the jest config for 2 days now, if you can suggest me how to fix this without the need to change these imports, please do.

**Are you able to assist bring the feature to reality?**
yes, I can create a PR right away

### PR DESCRIPTION
**Pull request by Rikpat**
Issue: #9279 

## What I did

Changed imports from ESModules to CommonJS modules for react-syntax-highlighter.
I had to change import to require because CommonJS modules don't have typescript definitions and would fail tests.

I noticed PR #9287 and also included that change, but with CommonJS import and manual type definition. In case this PR gets merged, that PR becomes obsolete.
I had to import props for ReactSyntaxHighlighter so I removed the line that got them directly from the component and used the imported props instead.

## How to test

Nothing really changed except for imports and typescript declaration, so I don't think any changes in testing or documentation are necessary

Closes #9279, overrides #9287, and also addresses #9282

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@Rikpat https://github.com/storybookjs/storybook/issues/9279#issuecomment-570083047
> there's a problem with import statement, not CommonJS related, but the package doesn't have type definitions for CommonJS modules, so build and tests fail on no type definition.
I had to import it as require to work around this
>
> Otherwise we would need to create a declaration for all of the imported modules

The existing [definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-syntax-highlighter/index.d.ts#L930) for `esm` just type everything as `any`, so I think you can just all the used imports as `declare module` to `lib/components/src/typings.d.ts`

**Review by shilman — CHANGES_REQUESTED** [review]
@Rikpat Thanks for the fix!!! It looks like it caused some regressions, however. Can you please take a look at the 3 updated Chromatic snapshots and see if you can figure out what's going on? Thanks!

**Comment by Rikpat** [comment]
> @LarsDenBakker #9287 I think they're all from syntax highlighting. I think we need to support HTML/CSS/JS/TS/MD highlighting out of the box.

I tried adding JS and MD into the highligter but it still has the same problem
It seems the generated ASTs are different for some reason, the css seems to be missing number highlighting and JS something to do with modules, and console object isn't highlighted.

I created a codesandbox to find out why does it do that.
It has a Direct component that imports everything directly from cjs dist, DirectHighlight that uses hljs instead of prism (for comparison only) and FromModule that imports from the module.
Just uncommenting the FromModule import in HighlighterTest fixes the css colors when using the direct component, so it's related to some import in there.

[Edit react-syntax-highlighter](https://codesandbox.io/s/react-syntax-highlighter-bvoiw?fontsize=14&hidenavigation=1&theme=dark)

**Comment by LarsDenBakker** [comment]
@Rikpat thanks for digging into this. The strange thing is that your PR has even more differences than my PR to the syntax highlighting. There is definitely something strange going on, perhaps there is a race condition somewhere?

**Comment by Rikpat** [comment]
@LarsDenBakker I was trying to fix it by importing and registering jsExtras and cssExtras directly from refractor, it fixed js highlighting, but cssExtras do break css highlighting for some reason. It works in isolated environment, but it doesn't work in storybook.
But it's a fix for both yours and mine PR. react-syntax-highlighter imports refractor in full package, but refractor/core in the light package. That includes js and css by default, but it doesn't include jsExtras and cssExtras like the full refractor. And react-syntax-highlighter doesn't include that in their languages.
I just can't figure out why does it break the css.

**Comment by ndelangen** [comment]
I'm wondering wether changing to https://github.com/rexxars/react-refractor would help.

**Comment by ndelangen** [comment]
adding css-extra seems to break highlighting for css for some reason. Do we absolutely need it?

**Comment by Rikpat** [comment]
> adding css-extra seems to break highlighting for css for some reason. Do we absolutely need it?

It doesn't highlight numbers, so it creates a different output without cssExtras



> I'm wondering wether changing to https://github.com/rexxars/react-refractor would help.

There would need to be some changes, but it would also fix the issue with cjs/esm imports. And we could probably just use refractor directly without wrapping component, since SyntaxHighlighter is the wrapping component. And react-refractor doesn't have a typescript declaration.

I've tried both react-refractor and refractor and both failed on the addon-docs story with 
```Unknown language: `plaintext` is not registered.``` 
There should be a check that it skips plaintext highlighting

**Comment by ndelangen** [comment]
I tried adding css-extra, but that actually makes css un-highlighted 😕

**Comment by shilman** [comment]
I'm ok with these changes as long as we understand what's going on and the scope of the change. I certainly don't understand that yet.

It's going into 6.0, so breaking changes OK.

**Comment by LarsDenBakker** [comment]
It's quite a big chain of dependencies, most likely that within that chain there are side effects which change the behavior of syntax highlighting. When trimming down the amount of packages that are loaded, and only loading what's needed, some of these implicit dependencies are gone.

We could perhaps merge this now, and look into using the syntax highlighting libraries directly later on since not all the abstractions are necessary here.

**Comment by mAAdhaTTah** [comment]
@shilman I'm running into this issue, wondering why this is slated for v6 instead of the next minor?

**Comment by Rikpat** [comment]
I've looked into the dependencies, and [css-extras](https://github.com/wooorm/refractor/blob/master/lang/css-extras.js) in refractor is basically just copied [prism code](https://github.com/PrismJS/prism/blob/master/components/prism-css-extras.js) wrapped in a module. 
The prism code was since updated, and refractor wasn't I'm not sure whether that causes the issue or not, but I don't really have time to look into it further because of university exams.

**Comment by shilman** [comment]
@mAAdhaTTah Well, it's a breaking change isn't it? I'm totally open for making it a patch if we're all in agreement that the changes are acceptable. Nobody's really convinced me that they understand why the diffs are occurring though. One option is that we can merge it into next, release it on 6.0-alpha, see how it affects people, and then patch it into 5.3.x once we've verified that the new behavior is good.

**Comment by mAAdhaTTah** [comment]
@shilman My thought was switching ESM -> CJS wouldn't be breaking. I just noticed the addition of `refractor`, which could be breaking. If those were split up, maybe this could go into a minor, but if that's not possible, your plan sounds good.

**Comment by ndelangen** [comment]
If we split them up, there are still the regressions in the syntax highlighting..
@mAAdhaTTah those are regression we'd rather not ship to 5.3.x

**Comment by mAAdhaTTah** [comment]
@ndelangen Oh I missed that. To clarify, switching from esm -> cjs is causing CSS regressions?

I'm a maintainer of Prism–I don't suppose I can help with anything here?

**Comment by ndelangen** [comment]
Yes @mAAdhaTTah. I think what might have been going on in the past is we loaded both syntax-highlighters and they are both using the single (global) instance of Prism, injecting and overriding languages.

If we could find a way to make css-extra work here, we'd be done, and I think the change is OK to go in a patch release.

Do you think you could help us with that?

**Comment by Rikpat** [comment]
@mAAdhaTTah Well the esm->cjs isn't causing it, I just included a change from another PR that was to reduce the size and was importing another esm module, so I added it with cjs insted of esm so it wont have to be changed in the future, but it turned out it was causing regression issues.
If we were only to change the imports and keep the full react-syntax-highlighter, the regressions would not happen and the PR could be closed.

**Comment by mAAdhaTTah** [comment]
If that's the case, then yeah, back to my original suggestion of just changing the esm -> cjs imports in this PR. Then I can look at the regressions introduced by those changes separately.

**Comment by shilman** [comment]
@mAAdhaTTah Are you proposing I merge this and release on an alpha, and then you will follow up from there? (I'm fine with that plan, just want to confirm)

**Comment by mAAdhaTTah** [comment]
@shilman I'm proposing the PR be updated so it's back to just changing esm -> cjs, if I understood this correctly:

> If we were only to change the imports and keep the full react-syntax-highlighter, the regressions would not happen and the PR could be closed.

Then the regression issue (which sounds like is caused by deep-importing that package) could be looked at separately.

**Comment by ndelangen** [comment]
Yes it sounds like separating these 2 things out into 2 separate PRs is a good plan.

Perhaps best is to leave this one, and open another with just the ESM => CJS change and if everything checks out release that into a 5.3.x patch

**Comment by shilman** [comment]
@mAAdhaTTah gotcha. glad i checked. sometimes when you're ready 100+ notifications per day, the words just start running together... 🙈

**Comment by mAAdhaTTah** [comment]
No worries, it happens. I'll poke at #9287 to see what I can do about the deep imports regression.

**Comment by mAAdhaTTah** [comment]
Not stale.

**Comment by shilman** [comment]
@mAAdhaTTah you've seen #9780 and #9795 right? both went out in 6.0-alpha

**Comment by mAAdhaTTah** [comment]
@shilman No, thanks for pointing that out. Unfortunately, I haven't had the time to look into this, but I'm not sure I'm going to in the near future, so if it's in 6.0, maybe that's fine. Sorry I couldn't be more helpful.

**Comment by shilman** [comment]
@mAAdhaTTah no worries. just wanted to let you and anybody else on this PR know about that incremental change. pretty sure there's more to do here, but it's all a little over my head.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
This turned into some cleanup & I added 2 new languages: yml & markdown

**Comment by Dashue** [comment]
Will this land on 5x or should I try to adopt 6x to have this sorted?
I'm hitting the issue when trying to use material-ui.

Happy to jump to 6x if it's in a good state? Are there any migration docs?

**Comment by shilman** [comment]
@Dashue 6.x and there are migration instructions in MIGRATION.md. I usually write them up in a post as well before the release goes out.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-53x-to-60x

**Pull request merged**
