### PR TITLE
Upgrade react-select dependency to version 3 for addon-knobs

### PR DESCRIPTION
**Pull request by indigolain**
## What I did
Upgraded react-select to version 3, to keep up with emotion's new typing.
[react-select version 3 upgrade guide here](https://github.com/JedWatson/react-select/issues/3585)

Projects using addon-knobs and emotion 10, with the new css props, might encounter the issue below and needs to upgrade the react-select dependency for addon-knobs.
https://github.com/emotion-js/emotion/issues/1084

### CODE REVIEW

**Comment by ndelangen** [comment]
Thanks @indigolain seems there are issues with the way you import `ValueType`:

```
/Users/dev/Projects/GitHub/storybook/core/addons/knobs/src/components/types/Options.tsx
  4:27  error  Unable to resolve path to module 'react-select/lib/types'  import/no-unresolved
  4:27  error  Missing file extension for "react-select/lib/types"        import/extensions
```

**Comment by indigolain** [comment]
@ndelangen 
Thank you for the review! I think I've managed to fix the import issue for react-select.
Could you take a look at it?

**Comment by ndelangen** [comment]
Thank you for the contribution ♥️

**Comment by indigolain** [comment]
@ndelangen 
I’m glad to help 👍

**Comment by ndelangen** [comment]
I invited you to the github organisation, hope to see more PRs like this 👍

**Comment by indigolain** [comment]
Thank you for the invitation ❤️

**Comment by SimenB** [comment]
Hah, I was just about to open a PR for this. Perfect timing 😀

**Pull request merged**
