### PR TITLE
UI: Reset layout properties when switching stories

### PR DESCRIPTION
**Pull request by yannbf**
Issue: #10641 

## What I did
Because there is a merge operation with styles when switching stories, when changing from centered to padded, for instance, the properties from the layout centered that were not present in padded (such as justify-content) would still be there, therefore making the next element be centered by mistake. The fix is to reset those properties. 

Kapture 2020-05-04 at 22 18 10

## How to test
1 - Checkout this branch
2 - Run storybook official example
3 - Filter for layout stories and check there

### CODE REVIEW

**Comment by tmeasday** [comment]
@ghengeveld did you write this original layout code (it changed files). Can you reveiw?

**Review by ghengeveld — APPROVED** [review]

**Comment by ghengeveld** [comment]
LGTM.

**Comment by ghengeveld** [comment]
Actually, shouldn't we be using `initial` instead of `inherit`? I think that's the safer option here.

**Comment by yannbf** [comment]
> Actually, shouldn't we be using `initial` instead of `inherit`? I think that's the safer option here, in case someone overrides any of these styles on the `html` element (which would lead this to inherit that).

Agreed! While I was changing that I noticed a bug in the stories example, also fixed! 👍

**Review by shilman — APPROVED** [review]
Awesome work @yannbf! You're on 🔥

**Review by shilman — CHANGES_REQUESTED** [review]
Awesome work @yannbf! You're on 🔥 

@ghengeveld @yannbf can one of you check out the chromatic diffs? seems like this is a pretty disruptive change? it doesn't really matter because layout is a 6.0 feature, but i just want to verify that the new behavior is the correct one and we didn't regress somehow. thanks! 🙏

**Comment by yannbf** [comment]
> Awesome work @yannbf! You're on 🔥
> 
> @ghengeveld @yannbf can one of you check out the chromatic diffs? seems like this is a pretty disruptive change? it doesn't really matter because layout is a 6.0 feature, but i just want to verify that the new behavior is the correct one and we didn't regress somehow. thanks! 🙏

Thanks <3 

I really need help with the chromatic diff, I don't understand why there are so many diffs.
About the E2E failure, I don't know why a timeout is happening while loading preview, and it works fine locally. I will try to figure it out!

**Comment by shilman** [comment]
@yannbf ignore the e2e failure, it's working on circle CI

**Comment by yannbf** [comment]
Chromatic is awesome. After using `initial` that was resetting the display of the root element to `inline` for a few of the layouts, and because of that vertical padding was not being applied!

**Comment by yannbf** [comment]
Ok, 5 changes in chromatic is much better 😂 Can someone else review them?

Also, after merging the latest for `next`, there are two changes which have nothing to do with my PR: [this](https://www.chromatic.com/snapshot?appId=5a375b97f4b14f0020b0cda3&id=5eba58a712567a00221b35b8) and [this](https://www.chromatic.com/snapshot?appId=5a375b97f4b14f0020b0cda3&id=5eba58a712567a00221b35bc). Maybe result of a bad merge into next?

**Review by shilman — APPROVED** [review]
LGTM! Thanks @yannbf!!!

**Pull request merged**
