### PR TITLE
Build: Fix sandbox running multiple versions of react

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

Template stories were running multiple versions of react in react projects when referenced by relative path. 

@tmeasday @IanVS any idea why this breaks in vite?

## What I did

- [x] Fixed this by sym-linking the stories into the project
- [x] Light refactor of `sandbox` script
- [x] Added react hooks stories to test this case

## How to test

- [ ] CI passes

### CODE REVIEW

**Comment by shilman** [comment]
@tmeasday Another problem that I'm seeing with this scheme is that the file watching for the story index server breaks. changes to the linked stories don't trigger an index update.

**Comment by IanVS** [comment]
@shilman do you have an example of a failure that was happening with multiple react versions?

**Comment by shilman** [comment]
@IanVS If you copy the React hooks story from this PR into `next` and run a sandbox you'll see the problem when you navigate to that story. Symlinking the stories into the sandbox solves that problem, but introduces two others.

**Comment by tmeasday** [comment]
@shilman do we need to install `@storybook/jest` as a dependency of our sandboxes?

**Comment by tmeasday** [comment]
> @tmeasday @IanVS any idea why this breaks in vite?

@shilman in what way is it breaking in vite (but not CRA)?

**Comment by tmeasday** [comment]
> Another problem that I'm seeing with this scheme is that the file watching for the story index server breaks. changes to the linked stories don't trigger an index update.

Hmm, we definitely need to investigate this, that would be very annoying.

**Comment by shilman** [comment]
@tmeasday See the CI failure

**Comment by tmeasday** [comment]
@shilman `build-sandboxes`? It is failing in all frameworks, not just Vite, for the `@storybook/jest` reason mentioned above:

**Comment by shilman** [comment]
@tmeasday I'm not at my computer but I think there's also a dev failure that's only in vite. I'll report back later.

**Comment by shilman** [comment]
@tmeasday @IanVS my bad, i misread the CI output. it was just the missing dependency & i fixed by adding it back. LMK if there's a cleaner way to do this.

**Comment by shilman** [comment]
@tmeasday holding off on this until we figure out the story index issue for linked stories

**Comment by tmeasday** [comment]
@shilman

> @tmeasday holding off on this until we figure out the story index issue for linked stories

I took a look at this. As far as I can tell reading the source, watchpack [doesn't resolve internal symlinks](https://github.com/webpack/watchpack/issues/190) when watching a directory. 

A solution is just to add each symlinked dir as a stories glob:

image

This appears to work, although we'll have to go back to a more complex `stories` field unfortunately.

**Comment by shilman** [comment]
NOTE: We should replace `../**/*.stories.*` with `../(!template-stories)**/*.stories.*` to avoid duplicate matches when there is no `src` dir in the sandbox.

**Pull request merged**
