### PR TITLE
Core: Wrap manager entries to handle exports using a cache directory

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: managerEntries can break when they contains exports

## What I did

see: https://github.com/storybookjs/storybook/pull/20308

This would also allow us to provide cleaner locations without special characters in the paths for managerEntries.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM! Still not 100% confident, but let's see what users say

**Comment by ndelangen** [comment]
tests run on my local machine 🎉

**Comment by VidunderGunder** [comment]
I make this mistake all the time myself, but it's a bit risky to use types from before a breaking change.

```json
{
  "@types/find-cache-dir": "^3.2.1",
  "find-cache-dir": "^4.0.0",
}
```

Maybe a test to check for mismatching types could be a smart thing to implement?

Anyways, this may be a pointer to how the issues this lead to can be fixed:

> ## v4.0.0
>
> ### Breaking
> Require Node.js 14 https://github.com/sindresorhus/find-cache-dir/commit/c5e8e5c8eb8603867545ba4d42748a8fa4cc546f
> This package is now pure ESM. Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

**Comment by ndelangen** [comment]
Thanks for spotting that @VidunderGunder ❤️ 

I've opened a PR downgrading for now.

**Pull request merged**
