### PR TITLE
Fix height adjustment in ZoomElement in Safari

### PR DESCRIPTION
**Pull request by jrencz**
## What I did

I replaced a mutation observer with the hook `useResizeObserver` inside ZoomElement in order to make stories using custom elements resize properly in Safari

Problem is visualized in https://github.com/storybookjs/storybook/pull/21138#discussion_r1111985790

<details>

Problem, as described in [this thread](https://github.com/storybookjs/storybook/pull/21138#pullrequestreview-1305837273) affects stories rendered with custom elements using Shadow DOM. Such stories are affected if at the moment ZoomElement measures the height, component did not yet render its contents. Then, when component in a story renders content, it doesn't trigger MutationObserver (mutation callback is not called when Shadow DOM is altered).

ResizeObserver replaces the existing MutationObserver (orignally added via #15472).

Problem, as described in the original thread was mitigated by @JReinhold with #21163, but even after that fix Safari is excluded from using native `zoom` and needs the fallback behavior.

</details>

## How to test

See https://github.com/jrencz/storybook-lity-story-height-repro

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by JReinhold — CHANGES_REQUESTED** [review]
Thanks for this! How do I test this? Do I just need a setup using web components that changes size over time?

I think we should replace the mutation observer completely with the resize observer because:

1. [Can I Use shows a great support table for it](https://caniuse.com/resizeobserver), and works for all the browsers and versions we support in 7.0.
2. It was already introduced in another part of the UI recently as part of https://github.com/storybookjs/storybook/pull/20783, so we've sort of already made it a requirement.

**Comment by jrencz** [comment]
Good point. I will try to provide some reproduction example, but until I find time to get it right
- try using `@storybook/web-components-vite`
- create component and story for it (i use Lit, maybe it matters, maybe not)
- maybe it matters that I globally use style `:not(:defined) { display: none}`

**Comment by jrencz** [comment]
@JReinhold I added a repository that reproduces the problem on `beta.53` and allows to notice that `ResizeObserver` resolves it

> I think we should replace the mutation observer completely 

Let's clarify: do you want me to replace `MutationObserver` with `ResizeObserver` it in this PR instead of just adding `ResizeObserver`?

**Comment by JReinhold** [comment]
> Before	After
> Screenshot 2023-02-21 at 22 33 58	Screenshot 2023-02-21 at 22 35 10

Great!

> If there's a way to integrate that in this repo instead of having a distinct one, please guide me how can I do it the right way.

I don't think that'll be necessary in this case.

> Let's clarify: do you want me to replace `MutationObserver` with `ResizeObserver` it in this PR instead of just adding `ResizeObserver`?

yup!

**Comment by jrencz** [comment]
It should be all right now. I extended the demo and found and fixed a problem, which I initially didn't notice (see commit message of https://github.com/storybookjs/storybook/pull/21174/commits/c8509fbcfc21fe3b46ae55aac58dd3343b468be1)

**Review by JReinhold — APPROVED** [review]
Looks good! Thanks for your contribution!

**Pull request merged**
