### PR TITLE
Add URL query param feature

### PR DESCRIPTION
**Pull request by leoyli**
Issue: #6602 

## What I did
- [feature] query param feature.
- [type] types to match with its typed function name.
- [doc] quickly document the new feature in README.md.
- [test] add tests to cover the newly added `serializers`.
- [chore] clean up: rename file structure.

#### Story running under default contexts
- Manager mode: https://monorepo-2kjlxsp90.now.sh/examples/official-storybook/?path=/story/addons-contexts--languages
- Iframe mode: https://monorepo-2kjlxsp90.now.sh/examples/official-storybook/iframe.html?id=addons-contexts--languages

#### Story running under preselected contexts set by URL query params
- Manager mode: https://monorepo-2kjlxsp90.now.sh/examples/official-storybook/?path=/story/addons-contexts--languages&contexts=CSS%20Themes=Desert,Languages=Chinese
- Iframe mode: https://monorepo-2kjlxsp90.now.sh/examples/official-storybook/iframe.html?id=addons-contexts--languages&contexts=CSS%20Themes=Desert,Languages=Chinese

## Known bugs
- The iframe URL is not get updated unless you switch from tabs (i.e. the iframe opening url is out of sync), which is the same problem as in the `addon-knob`.
- Perform `api.setQueryParams({ contexts: null })`: nothing happened, but based on the doc this query param should be removed.

Will file issues later to track it.

### CODE REVIEW

**Comment by shilman** [comment]
Possibly related to the known bugs https://github.com/storybooks/storybook/issues/6075

@tmeasday is looking into that issue

**Comment by leoyli** [comment]
Sorry for some drastic files movement, but I think this can make the source code easier to follow...  And I quickly add 2 tests to cover the new pure functions.  I think the feature is good to go.  Let me see if we can push this addon to Angular community as the next. 💪

**Review by shilman — APPROVED** [review]
Looking great @leoyli 👏 

I wonder if there are some types & patterns of this that would be useful for other addons as well (e.g. the `createAddonDecorator`) @ndelangen @tmeasday

**Comment by leoyli** [comment]
@shilman, I believe there are some pattern that potential can be further extracted to make cross framework addon development a breeze.  I would be happy to share or draft a post to discuss on it.  So far it seems each addon came up its unique way (and I came up with my own... but hope people think this could be easy to understand and follow).

**Comment by leoyli** [comment]
I guess many people starts to get `no-cycle` linter errors due to `eslint-plugin-import` v1.7.2.  The feature was added last year but get finally fixed and running out-of-box. It's a nice linting though.  Here is the error when I run it on my local machine:

```js

/Volumes/Data/GitHub/storybook/addons/info/src/components/types/ArrayOf.js
  1:1  error  Unused eslint-disable directive (no problems were reported from 'import/no-cycle')

/Volumes/Data/GitHub/storybook/addons/info/src/components/types/ObjectOf.js
  1:1  error  Unused eslint-disable directive (no problems were reported from 'import/no-cycle')

/Volumes/Data/GitHub/storybook/addons/info/src/components/types/OneOfType.js
  1:1  error  Unused eslint-disable directive (no problems were reported from 'import/no-cycle')

/Volumes/Data/GitHub/storybook/addons/info/src/components/types/PrettyPropType.js
  1:1  error  Unused eslint-disable directive (no problems were reported from 'import/no-cycle')

/Volumes/Data/GitHub/storybook/addons/info/src/components/types/Shape.js
  1:1  error  Unused eslint-disable directive (no problems were reported from 'import/no-cycle')
```

**Comment by shilman** [comment]
@leoyli I just pushed a fix for the linting error. Hopefully it passes CI. 🙏

**Comment by shilman** [comment]
@leoyli BTW can you create an issue in the storybook repo and reference that instead using the `Issue: #xxx` format? that way the issue will be closed & commented on when i release this improvement

**Comment by leoyli** [comment]
@shilman, do you mean open an issue for the linting error or copy the original issue into this repo?!

**Comment by shilman** [comment]
@leoyli copy the original issue into this repo

**Comment by leoyli** [comment]
I have rebased the branch, and patch d66aa30 for fixing the potential bugs due to exposing the state via URL query param. This avoid any inconsistency (as far as I can catch).

**Comment by leoyli** [comment]
I have rebased the branch, and patch d66aa30, b178d68 for fixing the potential bugs due to exposing the state via URL query param. This avoid any inconsistency (as far as I can catch).

**Comment by shilman** [comment]
@leoyli build failed in `addons/contexts`:

```
$ node ../../scripts/prepare.js
src/shared/serializers.ts(21,3): error TS2322: Type 'string[]' is not assignable to type 'SelectionState'.
  Index signature is missing in type 'string[]'.
```

**Comment by leoyli** [comment]
@shilman, learned a lesson on `.reduce` type inference... sometimes it failed in infer the type, especially when its initial value is `null` or `undefined`; then I have to manually specify it 👀.

**Comment by leoyli** [comment]
Going to merge it since CD/CI are happy and all my paranoid checks and bug hunting have been done! 💪

**Comment by leoyli** [comment]
Related to #6602.

**Pull request merged**
