### PR TITLE
Next.js: Support getImageProps API

### LINKED ISSUE #24675: [Bug]: getImgProps from next/image not supported
### Describe the bug

If i use the new function unstable_getImgProps from 'next/image' the component doesn't work.
I know this function is unstable, but i would be nice to be able to use it even in storybook

(0 , next_image__WEBPACK_IMPORTED_MODULE_3__.unstable_getImgProps) is not a function

### To Reproduce

Just use unstable_getImgProps in any nextjs environment.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 3.5.1 - ~/.nvm/versions/node/v18.18.0/bin/yarn <----- active
    npm: 10.1.0 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.4
  npmPackages:
    @storybook/addon-designs: ^7.0.5 => 7.0.5 
    @storybook/addon-essentials: ^7.5.2 => 7.5.2 
    @storybook/addon-interactions: ^7.5.2 => 7.5.2 
    @storybook/addon-links: ^7.5.2 => 7.5.2 
    @storybook/blocks: ^7.5.2 => 7.5.2 
    @storybook/manager-api: ^7.5.2 => 7.5.2 
    @storybook/nextjs: ^7.5.2 => 7.5.2 
    @storybook/react: ^7.5.2 => 7.5.2 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    @storybook/theming: ^7.5.2 => 7.5.2 
    storybook: 7.5.2 => 7.5.2 
    storybook-dark-mode: ^3.0.1 => 3.0.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by piratetaco**
Closes https://github.com/storybookjs/storybook/discussions/23588
Closes https://github.com/storybookjs/storybook/issues/24675

## What I did

in this [pull request](https://github.com/vercel/next.js/commit/4b50313fd946eed9191ce3d38de21407db730446#diff-b638b8968b6105ab5ed992cc238af90f7a6a0f430e8185d136c85d7096b864f1), Next made getImageProps a stable member of the Image api. <del>This is the minimum required work to forward that through the Next format mock in a future-facing manner in case Next were to expose any additional members at this path.</del> This adds a getImageProps mock just like the mock NextImage that leverages the preset `defaultLoader` so that images all properly load when using this.

Open to changes if desired!

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

Screenshot of issue:
Screenshot 2024-01-24 at 10 48 52 AM

screenshot after change:
Screenshot 2024-01-24 at 10 59 17 AM

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
Thank you so much for your contribution!

Could you add a story? Then we can cover and automatically test the behaviour. The best place to add one is to create a new story here: https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs/template/stories_nextjs-default-ts. These stories are automatically picked up by Chromatic, which is set up for the Next.js sandboxes.

**Comment by piratetaco** [comment]
added! Hopefully it's formatted right and whatnot. Trying to follow what appears like convention but using the browser for this acc. Let me know if there's anything beyond this that you want added/changed!

**Comment by piratetaco** [comment]
@valentinpalkovic The next version in storybook seems to be a bit too low to write the story. I accounted for this in the import and later destructuring in the fix, but right now I don't think the story will work without also bumping storybooks next version a bit. Which I guess explains why only the legacy image has a story today. What would you like me to do?

**Comment by valentinpalkovic** [comment]
In principle only for 8 unless it is a critical bugfix and there are enough upvotes to patch it back.

**Review by valentinpalkovic — APPROVED** [review]

**Comment by brycefranzen** [comment]
I could really use this on one of my projects. What's the hold-up? How can I help?

**Pull request merged**
