### PR TITLE
Addon-controls: Improve color picker UI and migrate to react-colorful

### PR DESCRIPTION
**Pull request by EvHaus**
Issue: N/A

## What I did

Migrates `addon-knobs` and `addon-controls` from [`react-color`](https://casesandberg.github.io/react-color/) to [`react-colorful`](https://github.com/omgovich/react-colorful).

Also added a "color" control to `official-storybook` examples so that it's easier to review and test this change.

The UI is slightly different

**Before:**

Screen Shot 2021-03-16 at 11 36 56 AM

**After:**

Screen Shot 2021-03-16 at 11 03 59 AM

### Why?

`react-color` is a giant library (143kb) largely caused by the fact that it depends on `@icons/material` which brings in an SVG file for every supported icon in Google's Material Design. This is overkill for what Storybook needs, and the `react-colorful` library is designed to deliberately be lightweight and fast.

For us at [ZenHub](https://www.zenhub.com), we've noticed that the `react-color` attributed **greatly** to the initial installation performance of Storybook and it impacts every single one of our CI builds. In fact, `react-color` adds so many extra files to `node_modules` that our CI runners often run into file handle limit restrictions when installing, building and deploying Storybook.

Given that Storybook 6.2 has an emphasis on performance, I thought this change would be a nice small win. It's a small trade-off between UI elegance/flexibility and performance (specifically bundle size).

## Impact

Size of `node_modules` before this change: 140,107,104 bytes (236 MB on disk) for 34,882 items
Size of `node_modules` after this change: 132,129,715 bytes (212.3 MB on disk) for 29,389 items

26% fewer files used. 10% smaller install size.

It's a bit harder to measure, but I imagine the start up time for Storybook's webpack server should be faster too as Webpack has much fewer files to load into memory.

## How to test

- Run the `official-storybook` preview (`cd examples/official-storybook && yarn storybook`)
- Navigate to http://localhost:9011/?path=/story/addons-controls--basic and confirm that the Color control in the Controls tab works
- Navigate to http://localhost:9011/?path=/story/addons-knobs-withknobs--tweaks-static-values-organized-in-groups, go into the Knobs tab, go into the Display tab and ensure the Color control works
    - **NOTE:** The current `next` builds seem to have broken knobs. They don't have values. So you can't test that the change works, but you can test that the component renders properly

### CODE REVIEW

**Comment by shilman** [comment]
@EvHaus thanks for this! `react-colorful` has been on the radar for awhile, so it's great to see it in action.

It looks like a big win on a fresh install in CRA in dev mode, shaving off a couple seconds in both start & build times, as well as the dependency reductions that you already mentioned above:

Storybook_Benchmark_›_Explorer__Install__Start__Build_

In production mode it didn't make much difference:

Storybook_Benchmark_›_Explorer__Browse_

So we should definitely merge this. Will consult with @ghengeveld to see whether we can squeeze this into 6.2 (which is already in RC) or whether we need to wait until 6.3.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
What a great first contribution @EvHaus 🎊

**Review by gaetanmaisse — APPROVED** [review]

**Comment by EvHaus** [comment]
Thanks all. Is there anything else I need to do on my end to move this forward? I see some failed checks on the PR but I don't have access the review the reasons.

**Comment by shilman** [comment]
@EvHaus nope. @ghengeveld is going to make some UI tweaks and we'll either try to sneak it into 6.2 or get it out right after in 6.3-alpha. thanks so much for putting this together!!!

**Comment by ghengeveld** [comment]
This is great. I'm making some changes to make up for the functionality lost from react-color. I also wanted to make it dead simple to copy/paste values, and convert between color spaces.

https://user-images.githubusercontent.com/321738/111670636-574a1e80-8818-11eb-9f67-96a6dc54e8f2.mov

**Comment by EvHaus** [comment]
Nice! I noticed Storybook currently always assumes `rgba`, so adding support for other formats is a nice improvement.

**Comment by ghengeveld** [comment]
More progress 🎨

https://user-images.githubusercontent.com/321738/111710108-49f95800-8849-11eb-9284-03521e1b415c.mov

**Comment by ghengeveld** [comment]
Swatches 🌈 

Screenshot 2021-03-19 at 10 18 22

**Comment by shilman** [comment]
Looks like some of the e2e tests are failing on this branch, on `next` and also on #14264. Working with @gaetanmaisse to try to get to the bottom of this, but may end up merging & releasing, just to get 6.2 out the door

**Review by shilman — APPROVED** [review]
Tremendous work @EvHaus for raising this and @ghengeveld for making it amazing. You guys rock! 💯

**Comment by omgovich** [comment]
Hi guys! I'm so happy you chose react-colorful! ❤️
Making the Storybook lighter and faster was one of the library's initial goals!

Let me know if you'll face any issues. I'm always glad to help.

**Comment by EvHaus** [comment]
Thank you all for jumping on this and shipping it in 6.2.0! This is going to help us a bunch.

**Comment by yannbf** [comment]
Hey peeps this contribution is super awesome! I wanted to show something I noticed while testing controls on docs page.
[Here's the link to the story](https://next--storybookjs.netlify.app/angular-cli/?path=/docs/basics-component-with-ng-content-button-with-different-contents--always-define-template-or-component)

I hope you don't mind the QA:

1 - the input is not as responsive as it could be, and text is not correctly aligned
2 - when playing with the picker, there's a flicker
3 - the color swatch feature is registering invalid colors as you type them (and says "black" for some reason)

Here's a gif showing these points:
2021-03-24 at 16 33 24 - Lime Giraffe


cc @ghengeveld @EvHaus

**Pull request merged**
