### PR TITLE
feat(repo): upgrade to latest version of Nx

### PR DESCRIPTION
**Pull request by mandarini**
NOTE: Maybe use this updated PR instead: https://github.com/storybookjs/storybook/pull/22694

## What I did

Updated repo to latest Nx.

## How to test

I upgraded and then ran `yarn task` and compiled all projects, all projects compiled successfully.

### Note:

We can remove `migrations.json`, I left it there for now, for you to see what scripts it ran! :)

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by chakAs3** [comment]
hi @mandarini thanks for your work.
I'm testing it now, indeed the build passes, However, i'm trying to run some scripts,  to create and run the sandboxes.
```

⚙️ Initializing Storybook
> node /Users/chakir/devs/storybook/code/lib/cli/bin/index.js init --yes
```
 it is stuck  here never finished.

**Comment by mandarini** [comment]
@chakAs3 can you tell me what command you are running exactly, and in which directory?

**Comment by chakAs3** [comment]
> @chakAs3 can you tell me what command you are running exactly, and in which directory?
root directory
`yarn task --task dev --template react-vite/default-ts --start-from=install`

it is stuck in prompts asking some plugin install, the promise is not returned 

if i bypass the prompts it passes .

**Comment by mandarini** [comment]
@chakAs3 yes ok I just verified. Weird, I wonder what it can be. I'm looking into it

**Comment by mandarini** [comment]
@chakAs3 same thing happens to me in latest `next`, in the existing version of Nx, before migrating. So I guess that's not an issue with the migration... It just hangs there forever.


Screenshot 2023-05-18 at 11 58 49 AM

**Comment by shilman** [comment]
@chakAs3 This was a CLI change that was introduced last week. I believe @yannbf and @ndelangen  will have a fix today

**Comment by chakAs3** [comment]
> @chakAs3 This was a CLI change that was introduced last week. I believe @yannbf and @ndelangen will have a fix today

yes it was the prompts, it was fixed with a workaround to unblock the contributors.

**Review by chakAs3 — APPROVED** [review]
I revert back to nx@16.2.1  as the beta creating some issue for with type checking

**Comment by chakAs3** [comment]
Hi @mandarini  i hope we are having a good week's start.

Unfortunately i could not merge your PR, I'm getting plenty of type checking errors, so CI tests won't pass 
to test run `yarn ci-tests`  or  `yarn task --task check --no-link`

**Comment by mandarini** [comment]
Hi @chakAs3 ! I will rebase my PR, squash the commits and push again if that's ok with you. I re-applied the latest upgrade, just to see the effects after rebasing with latest next. You can ping me on slack/discord if you want to briefly pair on this today. [The tests are passing on my end](https://app.warp.dev/block/zRHxFk2Oe7WqqNQholQ8tg), but I understand that "works on my machine" does not say much, hehe! :)

**Comment by mandarini** [comment]
@chakAs3 @shilman I created a new PR from scratch, and it seems to work for me, but let's test again! https://github.com/storybookjs/storybook/pull/22694

**Comment by ndelangen** [comment]
I suppose the new PR replaces this one?

**Pull request closed without merging**
