### PR TITLE
Fix polyfills loading order

### PR DESCRIPTION
**Pull request by Hypnosphi**
Issue: `addons.js` is loaded before polyfills in `manager` entry, which leads to [issues](https://github.com/storybooks/storybook/pull/1733#issuecomment-332009183) in IE.

## What I did
I put `addons.js` right after the polyfills

## How to test
Open React and Vue kitchen sink apps in IE11

### CODE REVIEW

**Comment by ndelangen** [comment]
Looks good, but will this help with the issue we're having in [3.3](https://github.com/storybooks/storybook/pull/1733#issuecomment-332009183)?

**Review by ndelangen — APPROVED** [review]
I'm making a mental note to revisit this code later, because this code looks super fishy to me.

I would prefer to not have to inject entry points like this.

**Comment by ndelangen** [comment]
If you've tested this @Hypnosphi go ahead and merge!

**Comment by Hypnosphi** [comment]
One possible alternative is to `unshift` polyfill into both entries right before passing the config to webpack

**Pull request merged**
