### PR TITLE
Update Emotion-related deps

### LINKED ISSUE #18656: Console error about server-side rendering on a Docs page
**Describe the bug**

When opening any Docs page in Storybook following console warning appear in a browser console:

```
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
```

Similar bug was fixed in #18103 but the fix didn't fix this bug.

**To Reproduce**
To reproduce run locally (production build is not affected):

```
npx sb repro --template react_typescript
cd react_typescript
yarn storybook
```

Open “Button” component and then “Docs” tab:

Screen Shot 2022-06-23 at 15 17 32

Alternatively clone this repository https://github.com/hudochenkov/storybook-console-error-18103 (difference from steps above: I used React 17 and npm). But error is the same in both cases.

**System**
```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 102.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-docs: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Additional context**
Console.error was introduced in 6.5, and doesn't exist in 6.4.22.

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/storybookjs/storybook/issues/18656

I've finally fixed the issue with ignoring some of those ignore flags in Emotion - so upgrading to the new version of Emotion should fix your problems 🤞 

With this, changes from https://github.com/storybookjs/storybook/pull/18361/files could be reverted if you want
This PR also closes https://github.com/storybookjs/storybook/pull/18657

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Review by ndelangen — APPROVED** [review]

**Comment by tmeasday** [comment]
I'm getting these errors when I run a sandbox:

image

```
yarn sandbox --template cra/default-ts
```

@ndelangen it looks like a manager bundling issue?

**Comment by tmeasday** [comment]
PS when I run the sandbox on `next` (where it works fine), I don't see the [original issue](https://github.com/storybookjs/storybook/issues/18656): 

image

Any idea on why that might be @Andarist @ndelangen ?

**Comment by tmeasday** [comment]
I also created this branch https://github.com/storybookjs/storybook/tree/revert-disable-emotion-unsafe-ssr-warnings where I reverted #18361 as you suggested @Andarist and I am not seeing the warnings in a sandbox either.

Which version of emotion resolved the issue? It looks like monorepo is currently bundling version `11.9.x`, perhaps the fix is already in there?

**Comment by tmeasday** [comment]
Confirmed I don't see the warning in docs mode in the latest 7.0 alphas.

**Comment by Andarist** [comment]
This was fixed by [@emotion/cache@11.10.2](https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Fcache%4011.10.2) (had to fix a regression in a follow-up release though: [@emotion/cache@11.10.3](https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Fcache%4011.10.3)). This depends on the rendered components - since the warning only gets printed when such "unsafe" styles are being rendered. Maybe you have not entered a screen that would trigger this?

I've confirmed now that the issue can be reproduced using [this repro](https://github.com/hudochenkov/storybook-console-error-18103) (on Storybook 6.5.x) after entering the Docs tab in Button stories.

This PR is worth merging anyway as it should be a safe upgrade. If you want to confirm that it actually fixed the problem then I would appreciate it if you could create a repro with the current 7 alpha that I could take a look at.

**Comment by tmeasday** [comment]
@Andarist I tried in a vanilla SB7 project and I don't see the same warnings. I'm not sure what would have fixed it though, if as you say the upstream problem wasn't fixed until `11.10.x`. I agree we may as well merge this once CI is passing though.

I suspect @ndelangen is most likely to have the answers on both fronts.

**Comment by Andarist** [comment]
This got superseded by https://github.com/storybookjs/storybook/pull/19029

**Pull request closed without merging**
