### PR TITLE
updating lib/csf-tools to use ts-up

### PR DESCRIPTION
**Pull request by josh-the-dev**
Issue:

## What I did

Migrated csf-tools to use the ts-up bundler.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by josh-the-dev** [comment]
Not sure why my  tests are failing? If anycone can  shed any light that'd be appreciated!

**Comment by ndelangen** [comment]
I tried looking into this, why the tests are failing.. something is doing something funny with csf-tools that makes it not accept the bundled code. Perhaps it's some ESM detection thing. It seems like the test are detecting an actual regression though.

**Comment by josh-the-dev** [comment]
> I tried looking into this, why the tests are failing.. something is doing something funny with csf-tools that makes it not accept the bundled code. Perhaps it's some ESM detection thing. It seems like the test are detecting an actual regression though.

Not sure how I've managed to cause a regression through this though if you look at my changes? 😢 I've applied the changes as per other PRs and as the suggestion in the original issue post 👍  .
 I'm more than welcome to feedback if I have broken something as a side effect though!

**Comment by ndelangen** [comment]
Looks like we got a duplicate PR here:
https://github.com/storybookjs/storybook/pull/19141

In which I found that minification actually breaks to code 😱

**Comment by IanVS** [comment]
Oh sorry, I didn't notice this PR when I made mine, it wasn't linked back to https://github.com/storybookjs/storybook/issues/18732 I guess.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
