### PR TITLE
feature: noStoriesOf loader option support for custome story

### PR DESCRIPTION
**Pull request by 466023746**
Issue:#3993

### CODE REVIEW

**Comment by igor-dv** [comment]
> if publish, hopes notify me here, thanks

You mean you don't want to continue this PR?

**Comment by 466023746** [comment]
ehhh..., i have thought you will change it, sorry, understand mistake.
i will continue this pr

**Review by igor-dv — COMMENTED** [review]
Now I like it 🥇

**Comment by igor-dv** [comment]
Please merge from master, it should solve CI issues.

**Review by igor-dv — APPROVED** [review]

**Pull request merged**
