### PR TITLE
CLI: suggest possible matches on invalid command

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Assume if the user makes a typo:- `sb ini`

Updated warning message:-
```
Invalid command: ini.
 See --help for a list of available commands.

 Did you mean init?
```

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@shilman @ndelangen Thoughts :thinking:

**Comment by ndelangen** [comment]
@jamesgeorge007 you should add dependencies using yarn, this will update the yarn.lock file.

**Comment by shilman** [comment]
@jamesgeorge007 Love it ❤️

**Review by shilman — APPROVED** [review]
LGTM. Fix the yarn.lock and I'll merge!

**Comment by jamesgeorge007** [comment]
The `yarn.lock` file is actually present in the project root, while the dependency being installed was specific to the `cli` workspace. Installing `didyoumean` (respective package) within the specific workspace is not likely to update `yarn.lock` right :thinking:

**Comment by jamesgeorge007** [comment]
The `yarn.lock` file is actually present in the project root, while the dependency being installed was specific to the `cli` workspace. Installing `didyoumean` (respective package) within the specific workspace is not likely to update `yarn.lock` right :thinking:

**Comment by jamesgeorge007** [comment]
@shilman @ndelangen Correct me if I'm wrong :clap:

**Review by wuweiweiwu — COMMENTED** [review]
we're in a monorepo so any dependency changes in any of the workspaces should update the toplevel lock file

**Comment by jamesgeorge007** [comment]
cc @shilman @ndelangen

**Comment by shilman** [comment]
@jamesgeorge007 linting errors:

```
/tmp/storybook/lib/cli/bin/generate.js
  75:61  error    'cmd' is already declared in the upper scope  no-shadow
  75:68  error    Unexpected dangling '_' in '_name'            no-underscore-dangle
  77:5   warning  Replace `↹` with `··`                         prettier/prettier
```

**Comment by jamesgeorge007** [comment]
cc @shilman

**Review by shilman — APPROVED** [review]
LGTM!

**Pull request merged**
