### PR TITLE
Build: Bundle lib/preview-web with ts-up

### PR DESCRIPTION
**Pull request by javier-arango**
Issue: [#18732](https://github.com/storybookjs/storybook/issues/18732)

## What I did
Migrated `lib/preview-web` to use the `ts-up` bundler.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by IanVS** [comment]
@javier-arango I pulled your branch and ran `yarn bootstrap --build`, and saw that preview-web was failing, with a message of:

```
src/PreviewWeb.tsx(65,3): error TS2612: Property 'previewEntryError' will overwrite the base property in 'Preview<TFramework>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
```

So, I removed the duplicate `previewEntryError`, and was able to build successfully.  Let's see what happens in CI 🤞.

**Comment by javier-arango** [comment]
> 

@IanVS Thank you for the help. Now I don't know why the `lint` check is failing. I am getting this error `/tmp/storybook/code/lib/core-client/src/preview/start.test.ts
  10:8  error  Unexpected use of file extension "mockdata" for "@storybook/preview-web/dist/cjs/PreviewWeb.mockdata"  import/extensions`. Also, the `unit-test` is failing with this error `Cannot find module '@storybook/preview-web/dist/cjs/WebView' from 'lib/core-client/src/preview/start.test.ts'`. When I try to edit the import to `@storybook/preview-web/dist/WebView` and I try to commit it I get the same `lint` error. I don't know how to fix it.

**Comment by ndelangen** [comment]
Both the linting error and the unit-test failures are correct.

in `lib/core-client` direct references are made to files deep in the `dist` folder of `lib/preview-web`. Moving the bundling breaks this.

We either have to expose multiple entrypoints, or update the usage in `lib/core-client` in some form.

**Comment by javier-arango** [comment]
@IanVS I saw that you were helping with this issue too. Saw your changes, but we still failing the `unit-test`. I was trying to figure it out how to fix it, but I couldn't find a way to do it. In the mean time, I am going to try to help with a different package. Let me know if I should do something to help with this issue.

**Comment by ndelangen** [comment]
@javier-arango I finally was able to get to this, but to not have to deal with merge conflicts I created a new branch off `next` branch. https://github.com/storybookjs/storybook/pull/19319

I'm sorry that I was not able to merge in your work, I really really appreciate the time, energy and skill you put into making this PR.

**Pull request closed without merging**
