### PR TITLE
Addon-backgrounds: set background on iframe instead of adding a wrapper in preview

### PR DESCRIPTION
**Pull request by Hypnosphi**
It fixes second part of #2655

---
This change is [Reviewable](https://reviewable.io/reviews/storybooks/storybook/2807)

### CODE REVIEW

**Comment by ndelangen** [comment]
@Hypnosphi We can actually improve this addon a lot.

We can set the iframe background to be transparent, and set the background in the manager.

What do you think?

**Comment by Hypnosphi** [comment]
@ndelangen Sorry, missed your comment.

Yeah, that sounds like a good idea, will try.

**Comment by Hypnosphi** [comment]
@ndelangen wouls your idea mean an API change? Currently the addon is used as decorator, which implies that it adds something to preview not manager

**Comment by Hypnosphi** [comment]
Another problem is, addons can't currently add things anywhere in manager outside of the addons panel. Should we allow them?

**Comment by ndelangen** [comment]
@Hypnosphi the viewport addon seems to be able to just fine?

**Review by igor-dv — COMMENTED** [review]
LGTM, but I wonder if these changes are considered backward compatible. For example for people that use both, storyshots and background addons.

**Comment by Hypnosphi** [comment]
Do you mean that people will need to update their snapshots? To me personally it seems OK. Plus we're actually removing noise from storyshots: https://github.com/storybooks/storybook/pull/2807/files#diff-261e00eb9848ef08cfb37eb5e7e0b012

**Comment by igor-dv** [comment]
Yeah, that what I meant. Maybe it worth adding some note about it, Just to reduce confusion... I don't know where though

**Review by igor-dv — APPROVED** [review]

**Comment by Hypnosphi** [comment]
I'm pretty sure we're introducing changes that can affect existing snapshots all the time

**Pull request merged**
