### PR TITLE
Core: add workaround to make storybook work for headless static build

### LINKED ISSUE #26080: [Bug]: storybook7 fails in headless mode
### Describe the bug

I have storybook7 to generate static html files, and use playwright to do the visual regression tests. It works fine in headmode. But when I enable the headless mode, it failed with error:
image

And it works fine in storybook6.
After debug, there is a fetch method in the [Preview.tsx](https://github.com/storybookjs/storybook/blob/981c2bdcef785f324faf08578d1281b36b391b1d/code/lib/preview-api/src/modules/preview-web/Preview.tsx#L168)

Is there any solution to fix this issue? Or can we remove the fetch method here? Many thanks for your help!

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RongqiZ**
Closes https://github.com/storybookjs/storybook/issues/26080

## What I did
We are using storybook7 and playwright headless mode to do the visual regression test. But after upgrading the storybook6 to storybook7, we failed to run the tests, due to "failed to fetch".

After some checking, it will fail on the **fetch** method in headless mode, since the method does not support **file://** type.

So I added a workaround for this situation, when it needs the file:// type, use the XMLHttpRequest to get the json file content instead. If you have any other suggestions, feel free to leave coments.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by tmeasday** [comment]
Hi @RongqiZ, thanks for the PR - are you pointing playwright at the files of the build storybook directly with the `file://` protocol?

We recommend starting a local http server to serve the built storybook (for instance you can run `npx http-server storybook-static`). I'm not sure but I think there are a variety of other issues you might run into when browsing to the files directly, my suspicion is that similar to this issue, things are not designed to be used that way.

@ndelangen does that square with your understanding?

**Comment by RongqiZ** [comment]
> Hi @RongqiZ, thanks for the PR - are you pointing playwright at the files of the build storybook directly with the `file://` protocol?
> 
> We recommend starting a local http server to serve the built storybook (for instance you can run `npx http-server storybook-static`) and connecting via `http://`. I'm not sure but I think there are a variety of other issues you might run into when browsing to the files directly, my suspicion is that, similar to this issue, things are not designed to be used that way.
> 
> @ndelangen does that square with your understanding?

Yes! We need to use playwright to load the storybook static build result.
This is our use case: 
Our product is very complex, so we want to build the UI test on the pipeline without the affect of the test environment, test account, network, database/..
So we decided to run the UI test based on the storybook build static files. And it will need more resources if we start the the storybook server, and run the test on top of it. We have a lot of projects in one repo, and there will be a lot of testing pipelines runing at the same time. 
Run playwright test on the storybook static build is really needed for us to integrate the UI test in the pipeline.

**Comment by ndelangen** [comment]
Yes @tmeasday that's correct.

@RongqiZ I also recommend ensuring storybook runs on a http protocol.
The file protocol is not well supported.

I don't want add a fallback layer to `fetch` just for this use-case.

**Comment by tmeasday** [comment]
> Run playwright test on the storybook static build is really needed for us to integrate the UI test in the pipeline.

Running a simple http server like `npx http-server` mentioned above is very simple and isn't going to use significantly more resources than browsing to `file://` directly.

**Pull request closed without merging**
