### PR TITLE
Build: Bundle addons/storysource with ts-up

### PR DESCRIPTION
**Pull request by bryanjtc**
Related: #18732

## What I did

Followed the instructions in the above issue

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by bryanjtc** [comment]
Should I include preset.js in the exports and field and in the bundle?

**Comment by IanVS** [comment]
I'm not sure, to be honest.  Here was a previous attempt at this conversion, FWIW: https://github.com/storybookjs/storybook/pull/19284

I think @ndelangen can provide better guidance here.

**Comment by bryanjtc** [comment]
It seems javascript files are not allowed by the typescript config of the bundle script. I will convert the js file to ts.

**Comment by bryanjtc** [comment]
@IanVS Converting preset.js to typescript and including that file in the bundle seems to have worked.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
