### PR TITLE
Document stories not showing up on storybook UI until device connects

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Document wonky RN storybook behavior for first time users

## How to test

N/A

### CODE REVIEW

**Comment by orta** [comment]
This makes sense 👍

**Comment by slorber** [comment]
@shilman what would be very great is to have a big green/red icon in the welcome page of http://localhost:7007/, just under the instructions, to tell the user weither or not the storybook has received an incoming connexion from device

**Comment by shilman** [comment]
@slorber that's a great idea. PR's welcome!!

**Review by tmeasday — APPROVED** [review]
LGTM

**Pull request merged**
