### PR TITLE
Interactions: Fix show length of object value on MethodCall

### PR DESCRIPTION
**Pull request by lonyele**
Issue: #17400

## What I did
show 2 fields of the object at most instead of 1 field

case 1, 3 were working as intended. This PR fixes the case 2 that previously neither `toHaveBeenCalledWith({ foo: 'bar', yo: 123 })`  or  `toHaveBeenCalledWith((2) { foo: 'bar', ... })` weren't shown that causes confusion to the user. Code itself was intended to show 2 fields so I made the change accordingly.

```ts
1) await expect(args.onSubmit).toHaveBeenCalledWith({ foo: 'bar' });
2) await expect(args.onSubmit).toHaveBeenCalledWith({ foo: 'bar', yo: 123});
3) await expect(args.onSubmit).toHaveBeenCalledWith({ foo: 'bar', yo: 123, help: 'asdf'});
```

스크린샷 2022-03-08 오전 1 03 02
스크린샷 2022-03-08 오전 1 04 00
스크린샷 2022-03-08 오전 1 04 21

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @lonyele thanks for your contribution! The linear label helps us keep track of issues. We use a tool called linear!

I'll try my best to check this contribution in detail this week and get back to you!

**Comment by lonyele** [comment]
FYI, meaning of `Code itself was intended to show 2 fields so I made the change accordingly.` is because this code already tried to make a distinction between less and more than 3 fields.
https://github.com/storybookjs/storybook/blob/13f4c66500b2dec1554ace2e37a206c17668c68d/addons/interactions/src/components/MethodCall.tsx#L218-L226

**Comment by lonyele** [comment]
Oh, this one looks good! @yannbf  if we are going to this route, what about setting 'expandLevel={1 or 2}' so that it can be few clicks more convenient for users. There are some case where users have multiple very big object that it can make worse for them for its visibility, it is good for general use cases(there still is a chance that some heavy user like the idea of default expansion of 1 or 2)  if this sounds ok, then i could make a change

**Comment by yannbf** [comment]
> Oh, this one looks good! @yannbf if we are going to this route, what about setting `expandLevel={1 or 2}` so that it can be few clicks more convenient for users. There are some case where users have multiple very big object that it can make worse for them for its visibility, it is good for general use cases(there still is a chance that some heavy user like the idea of default expansion of 1 or 2) if this sounds ok, then i could make a change

@MichaelArestad WDYT? I set the object not to be expanded so that there's no chance to blow up, but one level might be interesting

**Review by shilman — APPROVED** [review]
LGTM! Great job @lonyele @yannbf 👏

**Pull request merged**
