### PR TITLE
Core: Don't persist theme to localStorage

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/6798

## What I did
The FOUC doesn't happen anymore because of the tri-config api change
I removed the code to prevent the FOUC which was causing other issues.

### CODE REVIEW

**Comment by shilman** [comment]
AWESOME. Super excited about this!!!

What happens to users who haven't migrated to the new code?

**Comment by ndelangen** [comment]
They get the FOUC, seems like a god trade-off to me.

It will nudge them to migrate to the new api I guess.

**Comment by shilman** [comment]
Yeah I think that's a fair tradeoff and a great reason to upgrade.

Is there a deprecation warning for the old API, or some other clear path for them to follow when they get the FOUC?

**Comment by ndelangen** [comment]
@shilman if this is going to be in a major release, is it important enough to get a deprecation warning in?

I looked, and it's not the healthiest code already with multiple layers of deprecated stuff. I'd rather clean it up some more instead.

all this code is already for deprecation warnings:
https://github.com/storybookjs/storybook/blob/0de8e9d471b1c947af9f30fbc457f0fef314176d/lib/api/src/modules/layout.ts#L86-L131

**Comment by ndelangen** [comment]
Can I remove all that code for 6.0.0?

**Comment by shilman** [comment]
@ndelangen Yeah I think we can get rid of that old deprecation warning. If we do, we should mention it in `MIGRATION.md` for 6.0 and refer back to the original 5.0 notice. cc @tmeasday @Hypnosphi

**Review by shilman — APPROVED** [review]
LGTM! Safe to merge?

**Pull request merged**
