### PR TITLE
simplify babel config and make polyfills lazyloaded

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/11126

## What I did
See what happens to storybook if we remove the global polyfills

### CODE REVIEW

**Comment by ndelangen** [comment]
I've modified it so the polyfill CAN load, but they load async, and only when needed, thanks to @adamdoyle really

**Comment by ndelangen** [comment]
I can likely turn this into a NON_BREAKING state 😮

**Comment by ndelangen** [comment]
this makes the `configure` call async, unless an environment variable is set. (used by storyshots)

**Comment by ndelangen** [comment]
@shilman I think this is mostly a backwards compatible change now. There are risks in the changes stated above.
And obviously this changes a load of babel config...

**Comment by gaetanmaisse** [comment]
Will review it in the next few days but I will certainly have some question @ndelangen ;)

**Comment by tmeasday** [comment]
> this makes the configure call async

This is a little scary for Chromatic which relies on stories being rendered within the page load even in certain cases. Do we need to worry @ndelangen?

**Comment by ndelangen** [comment]
@tmeasday chromatic waits for the configure event, so it's already async

**Review by gaetanmaisse — COMMENTED** [review]
It does look ok, however I'm really not a Babel expert and there are a lot of changes on that side

**Comment by ndelangen** [comment]
understandable @gaetanmaisse, we have the e2e tests for a reason..

@shilman I'd love to know the perf impact of this.

**Comment by shilman** [comment]
Looks like dev impact is negligible:

Storybook_Benchmark_›_Explorer__Install__Start__Build_

But production impact is good, about a 12% reduction in bundle size:

Storybook_Benchmark_›_Explorer__Browse_

**Comment by ndelangen** [comment]
I'm closing this because:
- `--modern` implements this already
- There are too many merge conflicts to salvage this PR

**Pull request closed without merging**
