### PR TITLE
Upgrade bootstrap in docs

### PR DESCRIPTION
**Pull request by igor-dv**
Issue:
image

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Looks like some migration is needed: https://deploy-preview-4183--storybooks.netlify.com

**Comment by igor-dv** [comment]
💩 .. I've checked it in a dev mode, and it looked ok... Maybe we need to add chromatic on this? (@tmeasday 😉)

**Comment by igor-dv** [comment]
Fixed few things, but it still looks a bit different due to breaking changes. 
Also, I don't know yet how to fix search box

**Comment by Hypnosphi** [comment]
So they fixed the vulnerability only in v4? There's no patch for v3?

**Comment by igor-dv** [comment]
As far as I checked in the releases, they don't... We have the latest v3

**Comment by tmeasday** [comment]
What are you thinking @igor-dv? ;) Do the docs have a storybook?

**Comment by igor-dv** [comment]
Ah yeah. Docs have a setup but it doesn't work. Can we configure chromatic to snapshot only the homepage screen and one of the inner screens? Just to check that layout is not broken.

**Comment by tmeasday** [comment]
We can probably do a similar iframe back that we do with the built example
apps?

Sent from Astro <https://www.astro.ai> for iOS


On 17 Sep 2018 at 5:29 pm, Igor <notifications@github.com> wrote:


Ah yeah. Docs have a setup but it doesn't work. Can we configure chromatic
to snapshot only the homepage screen and one of the inner screens? Just to
check that layout is not broken.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/storybooks/storybook/pull/4183#issuecomment-421914056>,
or mute the thread

**Comment by igor-dv** [comment]
It's possible, but docs are not bootstrapped with the examples, AFAIK.

**Comment by igor-dv** [comment]
I've patched the search box to use classes from v3. I am not so happy with this, so if anyone familiar with bootstrap better would like to take this, that'd be great.

**Comment by ndelangen** [comment]
https://5b9faf1a3813f05aeb0eb2a2--storybooks.netlify.com/

**Comment by ndelangen** [comment]
Looks fine to me

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
