### PR TITLE
add a feature flag for enabling crossOriginIsolated

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

I added a feature flag to enabling the header to get SharedArrayBuffer to work.
We need to make this opt-in because it broke some storybooks

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
LGTM but I wonder if it should be a core option?

**Comment by ndelangen** [comment]
what's the rationale behind `features` vs `core`? It feels a little bit arbitrary.

**Comment by ndelangen** [comment]
what's the rationale behind `features` vs `core`? It feels a little bit arbitrary.

**Comment by shilman** [comment]
@ndelangen @tmeasday 

My thinking is that feature flags are a _temporary_ mechanism by which we turn code on and off to:
- to make breaking changes available in minor releases
- temporarily support legacy options that we plan to remove
- piloting experimental features

Code to configure other aspects of storybook should be located elsewhere. I think this one should go in `core`.

**Comment by ndelangen** [comment]
I changed it to be in core

**Comment by tmeasday** [comment]
That's what I suspected. Thanks for clarifying @shilman

**Pull request merged**
