### PR TITLE
Merge CRA2 webpack plugins

### PR DESCRIPTION
**Pull request by mucsi96**
Issue: #5005 

## What I did
- Increased the test coverage for `app/react/src/server/cra-config.js`
- Merge webpack plugins in case of `react-scripts` > `2.1.0`

@igor-dv Please review

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
LGTM what do you say @igor-dv ?

**Comment by mucsi96** [comment]
@ndelangen @Hypnosphi Do you have any idea why the Danger build fails?

**Comment by Hypnosphi** [comment]
@mucsi96 this https://github.com/storybooks/storybook/pull/5126#issuecomment-450646552

**Comment by mucsi96** [comment]
@Hypnosphi Can you remove one of the labels `bug` or `maintenance`. Now it's failing because of both them 🤣 

```
Please choose only one of these labels: ["bug","maintenance"]
```

**Comment by Hypnosphi** [comment]
LOL

**Comment by mucsi96** [comment]
@Hypnosphi Can we merge this?

**Comment by igor-dv** [comment]
2 weeks late, but Yey 🔥

**Pull request merged**
