### PR TITLE
Docs: Add `useSWC` documentation as alternative to Babel

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pull request, the documentation was updated to feature the experimental flag `useSwc` as an alternative to Babel.

Follows up on #22075 and addresses #22678

What was done:
- Updated the documentation to feature in the feature flag and reference it as a fallback for issues with Babel
- Created the required snippets

Leaving out the patch label to avoid issues with the documentation being published, as it seems that this flag is only available for 7.1.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by jonniebigodes** [comment]
Thanks for taking the time to review this @ndelangen. Appreciate it 🙏 . Merging

**Comment by benedfit** [comment]
Am I right in assuming there is currently no way to provide additional config to `swc-loader` in the same way as is possible with `babel-loader`? I'm currently using a non-standard `swc.config.js` file, rather than `.swcrc`, (due to the needs of a plugin), so I don't have a means of passing this config to Storybook

**Comment by ndelangen** [comment]
AFAICS plugins can be used in `.swcrc`: https://swc.rs/docs/configuration/compilation#jscexperimentalplugins

We could add a way to explicitly configure the `swc-loader` via `main.ts` for sure, though if not needed, I'd rather not.
I can't find a config option in their docs to set the configFile to a custom path for the swc-loader: https://swc.rs/docs/usage/swc-loader

**Comment by benedfit** [comment]
[@swc/plugin-relay](https://github.com/swc-project/plugins/tree/main/packages/relay#swcplugin-relay) currently needs `rootDir: __dirname` and as a result, can't be in the usual JSON format. So everywhere I'm using `swc-loader` I'm explicitly passing in the contents of my config file. e.g.

```
const swcConfig = require("./.swcrc.js")

// ...

{
  include: path.resolve("./src"),
  test: /\.ts$/,
  use: [
    {
      loader: "swc-loader",
      options: swcConfig,
    },
  ],
}
```

**Pull request merged**
