### PR TITLE
Add support for create-react-app@3.0.0

### PR DESCRIPTION
**Pull request by mrmckeb**
Issue: https://github.com/facebook/create-react-app/pull/6656

## What I did
`create-react-app@3` is likely to be released next week, and adds support for `baseUrl` in `tsconfig.json` and `jsconfig.json` files. Users will be told that `NODE_PATH` is deprecated, although it'll still work for now. 

We want to make sure that users that do remove `NODE_PATH` don't find that their Storybook no longer works as expected. 

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

This can be tested by installing alongside the latest `next` release with the `--typescript` flag.
https://www.npmjs.com/package/create-react-app/v/3.0.0-next.68

After installation, add the property `baseUrl` with the value `src` to the project's `tsconfig.json`.

### CODE REVIEW

**Comment by ndelangen** [comment]
Wow amazing @mrmckeb

**Comment by mrmckeb** [comment]
This is ready for review @ndelangen, I'd just like to hold off merging until I can test with the final release.

**Review by shilman — APPROVED** [review]
LGTM, thanks for taking care of this 🎖

**Comment by pavinthan** [comment]
but this changes is not working for latest CRA app:
This is my `jsconfig.json`

```
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```


This is my component
```
...
import { name } from "config/env";
...
```


I got this error when I start storybook
```
ERROR in ./src/components/DocumentHead/index.js
Module not found: Error: Can't resolve 'config/env' in '/Users/pavinthan/code/projects/deliver-daily/kpi-client/src/components/DocumentHead'
```

**Comment by mrmckeb** [comment]
@pavinthan, can you share a reproduction of this issue? I can take a look for you :)

**Comment by Hypnosphi** [comment]
@pavinthan it should be fixed with https://github.com/storybookjs/storybook/pull/9324

**Comment by pavinthan** [comment]
@mrmckeb I'm really very sorry becase I did not check this, I just skiped and thanks for your actions guys 🙏 🙏 🙏

// cc @Hypnosphi

**Comment by mrmckeb** [comment]
No problem, thanks for the feedback!

**Pull request merged**
