### PR TITLE
Svelte: use `SvelteComponent` instead of deprecated `SvelteComponentTyped`

### PR DESCRIPTION
**Pull request by mrazauskas**
## What I did

Replaced deprecated `SvelteComponentTyped` with the `SvelteComponent` type. `SvelteComponentTyped` is deprecated since Svelte 4 (see the [migration guide](https://svelte.dev/docs/v4-migration-guide#sveltecomponenttyped-is-deprecated)) and it is recommended to use the `SvelteComponent` type instead.

The `@storybook/svelte` package marks Svelte 4 as lowest supported version, so it feels reasonable to migrate. Reference:
https://github.com/storybookjs/storybook/blob/a606619e6cc628c083ff1fe5c11d34e3a518ce0f/code/renderers/svelte/package.json#L71-L73

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [x] integration tests
- [ ] end-to-end tests

#### Manual testing

The change is in type test file. If I got it right, `svelte-check` is used to type check the file. Running `svelte-check` does not report errors.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by lucalves — APPROVED** [review]

**Review by kasperpeulen — APPROVED** [review]
LGTM

**Review by JReinhold — APPROVED** [review]

**Review by JReinhold — CHANGES_REQUESTED** [review]
I see quite a lot of more instances of `SvelteComponentTyped`, I don't think this change makes sense without changing all of it - especially because right now it's only changed in tests.

image

**Comment by mrazauskas** [comment]
Right. I missed that. All instances are changed now.

**Comment by mrazauskas** [comment]
Hm.. Is this a breaking now? Definitely the change is larger than I thought initially.

**Comment by kasperpeulen** [comment]
Shall we look at this together @JReinhold ?

**Comment by mrazauskas** [comment]
Never mind (;

**Comment by kasperpeulen** [comment]
Thanks for your PR! 

Sorry for not merging it sooner, we made a new PR here:
https://github.com/storybookjs/storybook/pull/26113

**Pull request closed without merging**
