### PR TITLE
CLI: Update fixtures used for CLI tests

### PR DESCRIPTION
**Pull request by gaetanmaisse**
## What I did

 - ♻️ Remove SB config and stories from CLI test fixtures:
These fixtures are used to check that `sb init` is properly initializing SB in the fixture context so SB config (and stories) shouldn't be already in the fixture.
Moreover, fixtures were using outdated `config.js` file and a new `main.js` config file is added during initialization causing SB build to fail with:`ERR! Error: You have both a "main" and a "config". Please remove the "config" file from your configDir`

 - 🗑 Remove `react_babel_6` refs in CLI tests:
There is no more fixture related to `react_babel_6` so I removed all refs to that in scripts used to run CLI tests

## How to test

- CLI tests / CLI Fixtures should be 🟢 again

### CODE REVIEW

**Comment by gaetanmaisse** [comment]
Failing CI checks are related to IE11 and are also failing on `next` for now.

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by KtaVC11** [comment]
> ## What I did
> * ♻️ Remove SB config and stories from CLI test fixtures:
>   These fixtures are used to check that `sb init` is properly initializing SB in the fixture context so SB config (and stories) shouldn't be already in the fixture.
>   Moreover, fixtures were using outdated `config.js` file and a new `main.js` config file is added during initialization causing SB build to fail with:`ERR! Error: You have both a "main" and a "config". Please remove the "config" file from your configDir`
> * 🗑 Remove `react_babel_6` refs in CLI tests:
>   There is no more fixture related to `react_babel_6` so I removed all refs to that in scripts used to run CLI tests
> 
> ## How to test
> * CLI tests / CLI Fixtures should be 🟢 again

Hello, I have this error, but I did not understand how you fixed it, can you explain like in steps with the path and name of the files, please!

**Comment by gaetanmaisse** [comment]
The error occurred because the project was using Storybook 5.3+ but had 5.2- config files. 
The 5.2 -> 5.3 migration guide hadn't be followed, it's maybe the same for you? Details about that are available here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x

**Comment by KtaVC11** [comment]
> The error occurred because the project was using Storybook 5.3+ but had 5.2- config files.
> The 5.2 -> 5.3 migration guide hadn't be followed, it's maybe the same for you? Details about that are available here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x

I resolved this with one of the steps there, tahnk you very much!!.

**Pull request merged**
