### PR TITLE
Core: Change react deps to normal deps

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/11492

This is a proposal for a fix for the above mentioned issue..

Users get warningson missing

## What I did

- MOVE all react peer-dep to regular dep, since we use webpack alias to ensure singletons, see:
https://github.com/storybookjs/storybook/blob/03b5540101f180349795923eb71ea4355e81388b/lib/core/src/server/preview/iframe-webpack.config.js#L182-L187
and
https://github.com/storybookjs/storybook/blob/298ad9e6dbfcfc426112b45ab4d866ca2c7a2e8e/lib/core/src/server/manager/manager-webpack.config.js#L142-L146

This should remove the warnings for users not using react / react-dom

### CODE REVIEW

**Comment by gaetanmaisse** [comment]
`react` and `react-dom` were listed in `package.json` of apps too (as transitive peer deps) so if we move them to regular deps in core packages we can remove them from apps (and that should fix a lot of Yarn/NPM warnings)

**Comment by shilman** [comment]
This looks good to me, but it also looks like a huge destabilizing change and I'm worried about making it in the RC.

We can:
- Roll it out & see what happens & potentially roll it back
- Wait for 6.1 to make the change

**Comment by gaetanmaisse** [comment]
As it, I'm not sure it will remove all warnings and I think there is not much benefit merging this in RC as everything is working fine for now 🤷 I mean it can wait for 6.1 and be part of a bigger work on deps. But I'm not strongly opinionated, both options look ok 😄 🙈

**Comment by ndelangen** [comment]
> react and react-dom are listed in package.json of apps too (as transitive peer deps) so if we move them to regular deps in core packages we can remove them from apps (and that should fix a lot of Yarn/NPM warnings)

I'll see if I can do that today

**Comment by mrmckeb** [comment]
This should be fine with CRA too, because React is a project dependency - so it shouldn't log warnings in the pre-flight checks.

I agree with @shilman that maybe this is tight.

As an alternative, as all of Storybook is written with React, why not expose the dependencies once - from core?  You could re-export React from core, and then import from `@storybook/core/react`. We do that within CRA sometimes.

**Review by jimmyandrade — APPROVED** [review]
LGTM

**Comment by ndelangen** [comment]
Do we want to push this forwards as-is for 6.1 @shilman ?

**Comment by shilman** [comment]
@ndelangen I think so, after 6.0 stabilizes more we can merge and release in 6.1-alpha?

**Review by gaetanmaisse — APPROVED** [review]

**Comment by gaetanmaisse** [comment]
Reviewed ✅  I updated the PR with `next` and added 2 commits to sync ts and ts-node

**Review by jimmyandrade — APPROVED** [review]
LGTM

**Review by jimmyandrade — APPROVED** [review]
LGTM

**Comment by ndelangen** [comment]
Merge when green @shilman

**Pull request merged**
