### PR TITLE
Upgrade to telejson 6

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

Upgrade to telejson v6

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
@ndelangen Change seem to be working but `e2e-core` tests are failing pretty hard (on this branch only AFAICT). Can you please take a look?

**Comment by shilman** [comment]
@ndelangen now it's chromatic that's failing on IE11 support

https://www.chromatic.com/build?appId=5def62c97bd45f0020ef370e&number=11798

**Comment by ndelangen** [comment]
Wow, I'm stuck on this... I tried all sorts of things, and angular doesn't like any of it. also seems there's still something broken in IE11...

I ran `npx -p @storybook/cli sb repro ../storybook-e2e-testing/angular13 --framework angular --template angular13 --e2e` locally, and verified it's using the latest version of telejson, and locally it seemed to work just fine...

**Comment by ndelangen** [comment]
@shilman can you assist in reproducing this? I can't figure out what the problem is..

**Comment by ndelangen** [comment]
@shilman final straw it seems is the cra_bench failure, can you assist?

**Pull request merged**
