### PR TITLE
Addon Outline: Fix additional outline border in docs mode

### LINKED ISSUE #21328: [Bug]: An additional outline border is displayed in docs mode
### Describe the bug

Reported by @kbrandwijk (Thank you!)

When seeing a story in canvas, the Outline addon functionality is correct:
image

But when seeing in a docs entry, it outlines more elements that it should not, such as the "show code" button and the story wrapper:
image

The addon should only highlight the child elements of the story wrapper (e.g. `<div id="story--components-category--default--primary-inner" data-name="Default">`) in docs mode.

### To Reproduce

- Run Storybook 7 with addon-essentials
- Open a story in docs mode
- Enable outline (press O on keyboard)

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by g-cappai**
Closes #21328 

## What I did

I changed the selector used to target elements to be outlined.
Now every descendant of the direct child of the ZoomElement component is outlined according to its type.

## How to test

See issue -> to reproduce.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by yannbf — CHANGES_REQUESTED** [review]
Hey @g-cappai thanks a lot for your contribution! I think we should make some slight changes to make this more reliable.

What about we add a `data-story-block="true"` to the [Story block](https://github.com/storybookjs/storybook/blob/next/code/ui/blocks/src/components/Story.tsx#L129), and then we target that selector instead?

**Comment by g-cappai** [comment]
Hi @yannbf , I totally agree. Now looks definitely better.

**Review by yannbf — APPROVED** [review]
This looks great, thank you so much for working through the feedback!

cc @JReinhold  in case you want to take a look at this

**Comment by JReinhold** [comment]
@yannbf I'm sorry I'm late to the party here, but given that the story block already has a unique class `"sb-story"`, couldn't we have used that as a selector? Looks like it would effectively do the same thing as what we do with the data attribute.

**Comment by yannbf** [comment]
> @yannbf I'm sorry I'm late to the party here, but given that the story block already has a unique class `"sb-story"`, couldn't we have used that as a selector? Looks like it would effectively do the same thing as what we do with the data attribute.

In my perspective the data attribute is safer because the classname could be changed in the future and the person might not realize its connection to the addon outline, that's why I suggested it! Also feels more descriptive than a `sb-story` class

**Pull request merged**
