### PR TITLE
Improve Alphabetical order on Stories and Storykinds

### PR DESCRIPTION
**Pull request by filipposarzana**
Issue: Storykinds were not sorted alphabetically

## What I did
Using two functions to sort a `Map` and the array of `stories`

## How to test

Is this testable with jest or storyshots? Yes, it could be, but it's just a sorting matter

Does this need a new example in the kitchen sink apps? Nope

Does this need an update to the documentation? No I dont't think so

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Good idea! I changed your PR base to be `release/3.3` (the active development happens there). Please resolve the conflict and address the linting errors.

**Comment by filipposarzana** [comment]
Cool, I'll do it ASAP :smile: thanks

**Comment by igor-dv** [comment]
What about the `sortStoriesByKind` option?

**Comment by filipposarzana** [comment]
Ops i did not see it.
Honestly i needed to search through whole codebase to find something about it.

Probably addons options should be more written also in general README

**Comment by filipposarzana** [comment]
Probably I could make a PR about README.md to update some infos I think everyone should know about.
What about keeping the `sortStoriesByKind` true by default?

**Comment by igor-dv** [comment]
@filipposarzana 
I think changing the defaults is kinda breaking change... Even though IMO everyone wants it ordered. But improving the documentation is always a good idea 👍

**Comment by filipposarzana** [comment]
Probably could be a good idea sorting by default even though would be breaking.
If document is well-written i bet it won't be hard for everyone to adjust it.

I'll do in the next few days if you agree :smile: 

Anyway, storybook it's a wonderful package! :+1:

**Comment by danielduan** [comment]
Is this still an applicable PR with the addon option?

I think sort by kind on by default makes sense, but sometimes someone would want a welcome page at the top as well. I'd be open to it for a 3.3 change to default that to true and have docs on it.

**Comment by danielduan** [comment]
I'm gonna close this PR since there hasn't been much activity here. If you'd like to reopen it, just leave a comment.

**Pull request closed without merging**
