### PR TITLE
Add catalog metadata to the addons

### PR DESCRIPTION
**Pull request by winkerVSbecks**
## What I did

Added catalog metadata for the addons

### CODE REVIEW

**Review by phated — APPROVED** [review]
@shilman anything else you'd want done before merging this?

**Review by shilman — CHANGES_REQUESTED** [review]
@winkerVSbecks sorry for the slow reply -- totally missed this PR the first time around. can you run yarn install in the storybook repo and then re-save the files? i'm pretty sure you're running an old version of prettier, which is causing the `typesVersions` to move around: an unnecessary change that will just get reversed the next time somebody else edits the files. The rest of the curation looks great. Thanks!

**Comment by winkerVSbecks** [comment]
@shilman updated

**Review by shilman — APPROVED** [review]
Thanks @winkerVSbecks 🙏

**Pull request merged**
