### PR TITLE
UI: Styling updates

### PR DESCRIPTION
**Pull request by domyen**
Issue: #14737 and other UI improvements

## What I did
- ArgsTable when in controls panel: Fix ugly black border in Safari
- Boolean control: Switch position of `True | False` to `False | True` per #14737
- Sidebar: Buttons for root heading and expand/collapse now only get the outline-y focus state if they're keyboarded to
- Toolbar icons: Update copy icon to a link (which is what it does) and share icon to the alternative share icon
- Icons: Update icon set to have parity with the design system
- a11y addon: minor layout alignment fixes

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes. Go to the PR check.
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? no

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Looks great @domyen! :100:

**Comment by shilman** [comment]
@domyen I think this PR introduces a slight regression. In the case where there's a boolean arg with an `undefined` value, in the old version the control would display `false`. After this PR the control displays `true`. While neither option is technically correct, the old behavior is more correct than the new one. I think we are dealing with this in the "undefined values" work, so I'm not sure if it's critical to fix, but I wanted to get it on your radar.

**Comment by domyen** [comment]
@shilman That's strange, this was a styling change it doesn't affect whether the boolean was `checked`. When I go to the Storybook itself I see that it still displays "false" [here](https://5a375b97f4b14f0020b0cda3-gbgvhyavvb.chromatic.com/?path=/story/controls-boolean--undefined).

image

**Comment by ndelangen** [comment]
🤔

**Comment by shilman** [comment]
@domyen I'll keep an eye out for it after the undefined values changes come in and provide a repro if it's still broken then

**Comment by domyen** [comment]
Thanks! I handed the undefined state project back to @tmeasday yesterday so he'll probably know if anything is wrong.

**Comment by shilman** [comment]
Ok @tmeasday @domyen you can see the changes in every new PR that has unaccepted changes related to this bug. I'm not sure why it didn't show up in the original PR.

**Comment by shilman** [comment]
False alarm. It was introduced here: #14408, reverting

**Pull request merged**
