### PR TITLE
Addon-docs: Fix typo in default config

### PR DESCRIPTION
**Pull request by shilman**
Issue: #6706 

## What I did

Fixed a typo

### CODE REVIEW

**Comment by shilman** [comment]
Self-merging cc @Aaron-Pool

**Comment by Aaron-Pool** [comment]
@shilman you have this as a typo, but it looks like it was an incorrect type. Is there a type that would have been appropriate there?

**Comment by shilman** [comment]
@Aaron-Pool it's a JS file!

**Comment by Aaron-Pool** [comment]
Doh. Whoopsie 😐

**Pull request merged**
