### PR TITLE
Fix svg loading

### PR DESCRIPTION
**Pull request by shilman**
Issue: #5708 

## What I did

- Restore CRA SVG example
- Create full-control example

## What I tried

Lots of different permutations to get this working without deleting the `SVG` rule out of the base webpack, plus various SVG loaders. This is the first combo that I got working.

## How to test

```
cd examples/official-storybook
yarn storybook
```

Unfortunately, storyshots is broken 😦 and I'm not sure what to do about it.

### CODE REVIEW

**Comment by shilman** [comment]
@igor-dv Mind taking a look at this to see why storyshots is broken? I'm also not sure whether this is an acceptable solution to the bug it's trying to address. But at least it's something...

cc @ndelangen @tmeasday

**Comment by yingzuo** [comment]
I am getting a different error with this config. Before it was looking for the file under static/media, now it's using the file content as the tag name.
```
Failed to execute 'createElement' on 'Document': The tag name provided ('data:image/svg+xml;base64,bW9kdWxlLmV4cG9ydHMgPSBfX4dl5nBhY2tfcH54ibEljX3BhdGhfXyArICJzdGF0aWMvzdmciOw==') is not a valid name.
```

**Comment by tmeasday** [comment]
@yingzuo from memory that kind of issue comes from file loader handling the import. Perhaps you need to change the order of the loaders or ignore svgs in file loader (which is part of the default config)?

@shilman you'll need to get an "SVG loader" working in Jest too. What we do in chromatic:

```
// in jest.config.js
moduleNameMapper: {
    '\\.(svg)$': '<rootDir>/__mocks__/fileMock.js',
  },

// fileMock.js
module.exports = 'test-file-stub';
```

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
@tmeasday Tried various permutations of that with no luck. Landed on the `transform` solution used by CRA, which succeeds if I do `yarn jest --testPathPattern storyshots.test.js` but fails if I do `yarn test --core` and I'm not sure why.

**Comment by yingzuo** [comment]
Thanks @tmeasday.

**Comment by Pixelatex** [comment]
Any updates on this? 😄  Without the svg's working, I can't upgrade my storybook.

**Comment by shilman** [comment]
@Pixelatex this is just an update to the official storybook that shows how to load SVG's--basically a workaround. I haven't gotten to the bottom of the change or made a proper fix to Storybook yet. @igor-dv explained the problem in this week's maintainer's meeting, but we haven't had a chance to go over how we might update the codebase.

**Comment by berdyshev** [comment]
@shilman the proposed rule doesn't work for me.
```
{
  test: /\.svg$/,
  use: ['@svgr/webpack'],
}
```
Maybe because storybook is separate package in my lerna-driven monorepo, and the SVGs cannot be loaded this way, I don't know.

I managed it for v.4.x with such a rule:

```
  {
      test: /\.svg$/,
      use: [
        'babel-loader',
        {
          loader: 'react-svg-loader',
          options: {
            svgo: {
              plugins: [
                { removeDimensions: true, removeUselessStrokeAndFill: true }
              ]
            }
          }
        }
      ]
    }
```

**Comment by shilman** [comment]
@Pixelatex and anybody else who's watching. 5.0.2 fixed a regression in webpack extend-mode customization: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#from-version-501-to-502

This means that everybody migrating from a 4.x project using extend-mode should be unbroken using 5.0.2+. I also deprecated extend-mode. I also added a `--debug-wepack` CLI flag so you can see the exact webpack config you're passing to the preview's webpack.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@shilman can we move this PR forward, or can we close it?

**Comment by shilman** [comment]
Gonna close this. There was a bug in webpack extend mode that was fixed in https://github.com/storybooks/storybook/pull/6104

The contents of this PR are still useful for documenting how to get inline SVGs. But the main pain was fixed in the other PR and I've got my hands full with higher priority issues than sorting this out.

Happy to merge if anybody wants to resurrect this in a new PR.

**Pull request closed without merging**
