### PR TITLE
remove the defaultValue feature for argTypes

### PR DESCRIPTION
**Pull request by ndelangen**
remove the deprecated defaultValue property api for argTypes

### CODE REVIEW

**Comment by ndelangen** [comment]
@shilman I'd like your review on this.. I commented out the test code, because I didn't know if I should remove it or modify it, please advice what you'd like me to do about that.

I also suspect that there might be stories (in our own codebase) out there somewhere that use this deprecated feature?

**Review by tmeasday — APPROVED** [review]
Yes, I think I discovered in the angular work that it is still setting default values from compodoc (which is often very annoying, TBH). Still it might make it a disruptive changes for angular users.

Probably we need to pull the bandaid though.

**Comment by ndelangen** [comment]
This is one of the few remaining ones @tmeasday @shilman

**Comment by tmeasday** [comment]
@ndelangen I think you should play around with some of the angular stories with and without this change. For example this line of code:

https://github.com/storybookjs/storybook/blob/53c490cd1a64f69e1b259e2c6bf9c697891c4e86/code/frameworks/angular/template/stories/argTypes/doc-button/doc-button.component.ts#L52

I'm pretty sure it leads to an `argType.defaultValue` being set for the story automatically to `{ theDefaultValue: 'Default value in component' }`. I'm also pretty sure we changed the react docgen->argTypes implementation so that wouldn't happen (in the equivalent situation.

**Comment by ndelangen** [comment]
@shilman Do you think it's possible for us to resolve this together on Monday? and get this merged?

**Comment by shilman** [comment]
@ndelangen Sure! Let's do it

**Comment by tmeasday** [comment]
@ndelangen sorry for the delay here, I got to the bottom of it: https://github.com/storybookjs/storybook/pull/19935

**Pull request merged**
