### PR TITLE
adding /storybook.json endpoint

### PR DESCRIPTION
**Pull request by benzaita**
Allows enumeration of the stories and integration with tools such as BackstopJS, Gemini.

### CODE REVIEW

**Comment by mnmtanish** [comment]
Hi @benzaita 
It's a cool idea but I think we can do this using an addon.
We recently added custom middleware support with https://github.com/storybooks/react-storybook/pull/435

**Comment by benzaita** [comment]
Thanks. I'll look into the custom middleware approach

**Comment by mnmtanish** [comment]
Awesome! let me know if you need any help :)

**Comment by benzaita** [comment]
Hi @mnmtanish ,

I am afraid the `compiler` instance is not passed to the custom middleware - which is needed to be able to serve the up-to-date storybook object in the endpoint.

Am I missing something?

**Comment by mnmtanish** [comment]
I'll see if there's anything I can do on storybook side? or if there's some other way

**Comment by ndelangen** [comment]
@benzaita I'm interested in expanding the integration-abilities, so what would you need passed to you in the middleware? which `compiler`?

**Comment by benzaita** [comment]
@ndelangen that would be the `compiler` instance created by Webpack

**Comment by ndelangen** [comment]
Ah! I see, I'll think about the consequences in passing that around.

**Comment by ndelangen** [comment]
@benzaita I'm really sorry for keeping this PR open for so long without any progress on our part.

I would be OK with merging this is if were rebased on master, would that be something you're willing to do?

**Comment by benzaita** [comment]
Sure @ndelangen! Will do.

**Comment by ndelangen** [comment]
Fantastic!

**Pull request closed without merging**
