### PR TITLE
release/3.3

### PR DESCRIPTION
**Pull request by ndelangen**
Merge this when ready for 3.3 release

### CODE REVIEW

**Comment by shilman** [comment]
2017-August-31

#### Features

-   Deprecate confusing option names [#1692](https://github.com/storybooks/storybook/pull/1692)
-   1699 Have Stories on each level of hierarchy [#1763](https://github.com/storybooks/storybook/pull/1763)
-   887 Generate snapshot per story file [#1584](https://github.com/storybooks/storybook/pull/1584)
-   Search box: make found options selectable with click [#1697](https://github.com/storybooks/storybook/pull/1697)

#### Bug Fixes

-   Height aligned the 2 button [#1769](https://github.com/storybooks/storybook/pull/1769)
-   Fix Docgen in static builds for Info [#1725](https://github.com/storybooks/storybook/pull/1725)

#### Documentation

-   Add carbon to examples page [#1764](https://github.com/storybooks/storybook/pull/1764)
-   Minor grammar fixes and clarification to Vue documentation [#1756](https://github.com/storybooks/storybook/pull/1756)
-   Make dependencies more deterministic [#1703](https://github.com/storybooks/storybook/pull/1703)
-   Fix incorrect yarn command in docs [#1758](https://github.com/storybooks/storybook/pull/1758)

#### Maintenance

-   A CLI for running specific tests suites, like bootstrap CLI [#1752](https://github.com/storybooks/storybook/pull/1752)
-   Remove check for sender on channel. [#1407](https://github.com/storybooks/storybook/pull/1407)
-   Add config for dependencies.io [#1770](https://github.com/storybooks/storybook/pull/1770)
-   Fixed Jest warnings [#1744](https://github.com/storybooks/storybook/pull/1744)
-   [Examples] Added addon-knobs to crna and vanilla react native. [#1636](https://github.com/storybooks/storybook/pull/1636)

#### Dependency Upgrades

-   Update lerna to the latest version 🚀 [#1768](https://github.com/storybooks/storybook/pull/1768)
-   Update lerna to the latest version 🚀 [#1760](https://github.com/storybooks/storybook/pull/1760)

**Comment by Hypnosphi** [comment]
@ndelangen please resolve the conflicts =)

**Comment by Hypnosphi** [comment]
Ok, now it's my turn

**Review by Hypnosphi — DISMISSED** [review]

**Comment by ndelangen** [comment]
@Hypnosphi Do you want to deal with these conflicts? I think you're the last person to change those files?

**Comment by Hypnosphi** [comment]
Sure

**Comment by ndelangen** [comment]
I think we're ready to merge this one

**Review by Hypnosphi — APPROVED** [review]

**Pull request merged**
