### PR TITLE
Added kitchen sink to sample app

### PR DESCRIPTION
**Pull request by shilman**
Issue: #1220 

## What I did

Added `notes`, `info`, `knobs`, `options` to the `test-cra` and `cra-storybook` examples.

- `test-cra` tries to simulate what a user would see installing these packages but based on file links
- `cra-storybook` is uses `lerna bootstrap` to install the dependencies and is easier to develop on

## What I found

~~`info` and `knobs` are apparently broken.~~
- ~~`info` shows an error in the preview window. this also causes our test suite to fail (yay?!)~~
- ~~`knobs` shows up but editing is broken (URL is not updated properly)~~

**Update:**
- `info` works on all platforms?
- `knobs` is fixed based on @ndelangen 's fix below

## What I need

- any feedback on existing scenarios
- contributions for `events`, `graphql` addons
- are the bugs i'm seeing actually bugs?

## How to test

```
npm run bootstrap
cd examples cra-storybook
npm run storybook
```

```
cd ../test-cra
npm install
npm run storybook
```

### CODE REVIEW

**Review by danielduan — COMMENTED** [review]
looks good, thanks!

**Comment by alexandrebodin** [comment]
#1238 Some cleaning I did on the propTypes :)

**Comment by shilman** [comment]
@tmeasday @ndelangen 

Proposal based on what I've seen from both of you:
 
1. rename `cra-storybook` => `cra-kitchen-sink` (to line up with react-native-vanilla, `crna-vanilla`)
2. remove `test-cra` and port any interesting diffs over to `cra-kitchen-sink`
3. create a `cra-vanilla` that's the equivalent to running `getstorybook` in a `CRA` app
4. use `bootstrap`-style dependencies across the board rather than `file:` deps which are problematic

Happy to do all of this if you're good with it, except for (2) which I'd ask for help from @tmeasday

**Comment by tmeasday** [comment]
Per https://github.com/storybooks/storybook/pull/1238#discussion_r121230860 I suppose we should remove `test-cra`, which would simplify this PR a bit?

**Comment by tmeasday** [comment]
I'm happy with this and happy to help. I'm not sure what the best naming is. I chose `react-native-vanilla` in the sense of "not CRNA" but I guess you took it to mean "simplest possible storybook usage".

I think long term we want a RN kitchen sink too, and there's no reason not to use the same app for that. So maybe we should rename that app `react-native-vanilla-kitchen-sink` or just `react-native-kitchen-sink` if it's clear that it isn't CRNA.

**Comment by shilman** [comment]
Ok, I understand `vanilla` better now.

How about:
- `x-getstorybook`
- `x-kitchen-sink`
- `x-whatever-we-want-to-demonstrate`

**Comment by alexandrebodin** [comment]
Sounds good

**Pull request closed without merging**
