### PR TITLE
Core: Add `prefix` customization for navigation items

### PR DESCRIPTION
**Pull request by tooppaaa**
Issue: Lack of capability to add elements to
- sidebar subheadings (most important one in my opinion)
- sidebar items 
   - folder
   - component
   - story

This PR aims as a proposal for this and basis of discussions

image

- Should we keep double icons when prefix is set ?
- Should it be called prefix ?

### CODE REVIEW

**Comment by shilman** [comment]
cc @domyen @ghengeveld

**Review by shilman — COMMENTED** [review]
Looks great & code is pretty simple. Great stuff @tooppaaa 💯 

We're doing some work on the sidebar as part of the search stuff and I want to make sure this is compatible with that work before we merge it. My spider sense is tingling that we'll want to address this in a different way, but don't have a concrete suggestion yet.

**Comment by tooppaaa** [comment]
Happy to wait / change implementation ! 
As I mentioned, this is simple "suggestion PR" where we can see whether we want this or not :)

**Comment by ghengeveld** [comment]
I'm working on a revamp of the sidebar right now. Allowing customization is on the radar and the current proposal is to allow this by seeing data attributes on relevant nodes for various things. That allows these elements to be targeted with CSS and read the data values from JS.

@tooppaaa would this work for you? Do you have other suggestions?

**Comment by ghengeveld** [comment]
@tooppaaa I can share the redesign strawman with me you if you'd like. Just send me your Google account address on which to invite you. I think you follow me on Twitter. Or drop a note in the chat bubble at https://www.chromatic.com/docs

**Comment by tooppaaa** [comment]
@ghengeveld Should we drop that PR ?

**Comment by ndelangen** [comment]
I think the idea on this PR is great, @tooppaaa I think it's worth continuing in concept, but perhaps it'd be easier to start anew rather then try and fix the merge-conflicts?

**Comment by tooppaaa** [comment]
Reworked as https://github.com/storybookjs/storybook/pull/13121

**Pull request closed without merging**
