### PR TITLE
feat: Add 'component' option to @addons/info

### LINKED ISSUE #2893: withInfo does not understanding decorators
When I pass decorated component, for example `Button` to `withInfo` it parses component as is, like `JSS(withRouter(Button))`

- @storybook/react 16.2
- @storybook/addon-info 3.3.11

My proposal is to provide option for `addon-info` to set map function component. 
```js
withInfo({
      component: () => MyUndecoratedComponent,
    })(() =>
      <Component>Click the "?" mark at top-right to view the info.</Component>
    )
```
or
```js
withInfo({
      component: Component => Component.Wrapper.Inner,
    })(() =>
      <Component>Click the "?" mark at top-right to view the info.</Component>
    )
```

### PR DESCRIPTION
**Pull request by wuweiweiwu**
Issue:
fixes #2893 
## What I did
added a `component` option that allows users to specify what component is analyzed

Usage:

```js
storiesOf('Addons|Info.Options.component', module).add(
  'Specify another component to be analyzed',
  withInfo({
    component: () => <BaseButton label="specified button" />,
  })(() => myHOC(BaseButton))
);
```

## How to test

Is this testable with Jest or Chromatic screenshots? n/a
Does this need a new example in the kitchen sink apps? y
Does this need an update to the documentation? y

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Isn't this usecase covered by `propTables` option?

https://storybooks-official.netlify.com/?selectedKind=Addons%7CInfo.Options.propTables&selectedStory=Shows%20additional%20component%20prop%20tables&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by wuweiweiwu** [comment]
I would say partially, since the `propTables` option appends other components. 

What if the `propTables` option completely overrides the story component instead? 

I mainly just have decorated components in mind for this use case, on second thought, I don't this this is actually needed, since in #2893 you can just pass in the undecorated component into the story unless the decorator adds some extra functionality, but propTables can be used to document the undecorated component instead

**Comment by Hypnosphi** [comment]
> What if the `propTables` option completely overrides the story component instead?

You can achieve this by combining it with `propTablesExclude`

**Comment by wuweiweiwu** [comment]
I see! Thanks for clarifying

**Pull request closed without merging**
