### PR TITLE
React: Upgrade to @storybook/react-docgen-typescript-plugin

### PR DESCRIPTION
**Pull request by shilman**
Issue: #14118 

## What I did

- [x] Published @bebraw 's PR to `@storybook/react-docgen-typescript-plugin` 
- [x] Upgraded to the new package

## How to test

```
yarn bootstrap --core
cd examples/react-ts
yarn storybook
```

### CODE REVIEW

**Comment by bebraw** [comment]
I followed your instructions with a small addition (`yarn` in the beginning) against a fresh checkout:

```
yarn
yarn bootstrap --core
cd examples/react-ts
yarn storybook
```

The problem is that I don't get the same error as you do and the Storybook seems to run just fine and it's parsing the types as you would expect.

I wonder what's the difference. Can anyone else confirm the issue?

**Review by ndelangen — APPROVED** [review]

**Comment by bebraw** [comment]
Note that I pushed two more fixes to the webpack plugin to address issues discovered during further testing in practice. There will be another canary by Michael I think.

**Comment by yannbf** [comment]
Hey @bebraw I was having issues in my project and I went through multiple versions of Storybook to figure out where the problem was originated from. I ended up finding that the issue was introduced in version alpha-35, and I think it's related to this PR. 

The issue is: 
Storybook initializes correctly and works fine, then you make a change in a component used in the story, and if you refresh Storybook, it gives the error below

image

Have you seen anything like this in another project? I heard from another colleague that this happens to his Storybook occasionally

**Comment by bebraw** [comment]
@yannbf It's not possible to debug the issue based on that information alone. Can you open a separate issue with a standalone repository to check?

**Comment by yannbf** [comment]
> @yannbf It's not possible to debug the issue based on that information alone. Can you open a separate issue with a standalone repository to check?

Consider it done! 👌

**Pull request merged**
