### PR TITLE
Update Docs class name escape hatches

### PR DESCRIPTION
**Pull request by kevinSuttle**
## What I did 

Minor update to the docs class names

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Thanks @kevinSuttle!!

**Comment by kevinSuttle** [comment]
I just noticed that these are different if the docs are MDX or CSF. 

e.g. CSF `.sbdocs-title`. MDX: `.sbdocs-h1`
CSF `.sbdocs-subtitle`. MDX: `.sbdocs-h2`

**Comment by kevinSuttle** [comment]
Also, I should point out that I've never been able to get a single one of these to work.  :/

**Comment by shilman** [comment]
@kevinSuttle `.sbdocs-title` is the page title in DocsPage. `.sbdocs-h1` is what's generated by `# some h1` in MDX.

Why doesn't overriding work? I think providing the extra class selector, e.g. `.sbdocs.sbdocs-title` should give it the specificity it needs to override. Those "inline" styles are not really inline -- just generating a class selector in emotion AFAIK...

**Pull request merged**
