### PR TITLE
Add TypeScript support for react-scripts

### PR DESCRIPTION
**Pull request by mrmckeb**
Issue: #4587

## What I did
Added support for TypeScript when using `react-scripts@>=2.1.0`.

## How to test
Create a new Create React App project and pass in the `--typescript` flag.
```sh
npx create-react-app my-app --typescript
```
Install storybook (this build) and run `storybook`. You should not see any errors.

### CODE REVIEW

**Review by igor-dv — COMMENTED** [review]
Very cool! Thanks for taking it.
Do you want to add CLI tests for this in a separate PR?

**Comment by mrmckeb** [comment]
@igor-dv Definitely, I can take a look at that over the weekend.

I've squashed and pushed those changes, thanks for the review.

**Review by igor-dv — APPROVED** [review]

**Comment by Vinnl** [comment]
Thanks for this work! Do I understand it correctly that now, using Storybook 4.1, we can:

- Use Storybook for React components written in TypeScript (this PR).
- Write Storybook configuration in TypeScript (#4902).
- NOT write stories themselves in TypeScript.

And follow-up in case the latter is false: is there anything that needs to be done to enable writing stories in TypeScript, other than renaming them from `.jsx` to `.tsx`?

**Comment by mrmckeb** [comment]
Yes, all of my team's stories are `.tsx` and it works great.

**Comment by Vinnl** [comment]
@mrmckeb Hmm, and you've removed your custom webpack.config.js and don't have a TypeScript loader in your own dependencies?

I'm asking because I'm running into

> Module parse failed: Unexpected token (17:22) You may need an appropriate loader to handle this file type.

So it appears that for some reason, without my own Webpack config, Storybook's config does not look for TypeScript files.

**Comment by mrmckeb** [comment]
Hi @Vinnl, can you let me know what version of `react-scripts` and `@storybook/react` you're using? Thanks!

**Comment by mrmckeb** [comment]
Hmm, where are you stories located? In component directories?

Perhaps you could push up a quick test repo that I could play with? Something very rough.

**Comment by Vinnl** [comment]
@mrmckeb The stories are in `/stories`, next to the components which are in `/src`. The project is open source, so it can be seen [here](https://gitlab.com/Flockademic/plaudit/tree/57-use-svg-component-and-native-typescript-in-storybook/client). (Note that this work is done in the branch `57-use-svg-component-and-native-typescript-in-storybook`, and that there are several projects in this repo - the relevant one is in `/client`.)

**Comment by mrmckeb** [comment]
Would it be OK if I look over the weekend @Vinnl? Sorry for the delay.

**Comment by mrmckeb** [comment]
I just confirmed with the latest packages, and it is still working for me locally @Vinnl.

image

```
    "react-scripts": "2.1.1",
```

```
    "@storybook/addon-a11y": "^4.1.1",
    "@storybook/addon-actions": "^4.1.1",
    "@storybook/addon-knobs": "^4.1.1",
    "@storybook/addon-links": "^4.1.1",
    "@storybook/addons": "^4.1.1",
    "@storybook/react": "^4.1.1",
    "@types/storybook__addon-actions": "^3.4.1",
    "@types/storybook__addon-knobs": "^3.4.1",
    "@types/storybook__addon-links": "^3.3.3",
    "@types/storybook__react": "^4.0.0",
```

**Comment by Vinnl** [comment]
Thanks for working on this at all @mrmckeb - you don't owe me anything :)

But you were entirely correct! Moving the stories into the `src/` folder solved the issue, and the stories get compiled just like my regular components now. Thanks a bunch!

**Comment by igor-dv** [comment]
@mrmckeb we probably need to add `stories` dir into the `include` as well 🤦‍♂️  SB cli creates this dir when you execute `sb init`...

**Comment by mrmckeb** [comment]
I actually feel that this is not a good default. I much prefer stories to be alongside components - perhaps that should be the default? This results in less jumping between folders, and a smaller chance that people will forget to update stories after changing components (which I've seen a lot).

Regardless, this is a very easy fix if we want to add it ;)

**Comment by igor-dv** [comment]
Yeah, that is how most of the people work with stories, IMO. Though I am not sure it's easy to do this with the cli at least now...

**Pull request merged**
