### PR TITLE
Height aligned 2 buttons in manager's header

### PR DESCRIPTION
**Pull request by usagi-f**
This PR is nitspick.

The height of the 2 buttons are not aligned **in Chrome**.
I am a designer, this feel sick to me...

#### ScreenShot in Chrome
image

#### ScreenShot in Safari
image

## What I did

Using flexbox

#### ScreenShot in Chrome
image

#### ScreenShot in Safari
image

## How to test

>Is this testable with jest or storyshots?

Yes, maybe by storyshots.

>Does this need a new example in the kitchen sink apps?

No.

>Does this need an update to the documentation?

No.

---

I'm contributing to this repository for the first time.

Sorry, I did not fully understand if there are other files that need to be changed.

### CODE REVIEW

**Comment by ndelangen** [comment]
@marchdoe Would you like to review this one?

**Comment by ndelangen** [comment]
Thank you @usagi-f, awesome PR, very clear what it does and I'm sure we can get this merged real soon and end this atrocity to your eyes. 👨‍🎨 

I want to give some new members on the team the opportunity to review and merge for the first time.

**Comment by marchdoe** [comment]
@usagi-f - I am trying to recreate the issue and am not able to. 

I am on Chrome Version 60.0.3112.113 (Official Build) (64-bit) (MacOS)

screen shot 2017-08-30 at 9 39 56 am

Great work on this! Everything looks great in the PR. The only thing I noticed that I was more curious about than anything was the nesting of Flex. Is it possible to achieve the same display without nesting?

**Comment by ndelangen** [comment]
Maybe the issue only appears when zooming?

**Comment by usagi-f** [comment]
@marchdoe 
Thank you review for this PR.

I also reviewed it in the same environment. (60.0.3112.113 / 64-bit / MacOS)
But, display was same.

- cra-kitchen-sink
image

- Install for `"@storybook/react": "^3.2.8"` in the new directory
image

---

And, Thank you for review on CSS too.

But, I think the nested flexbox is not a bad thing.

By doing this, eliminate the Magic-Number of padding, and The height becomes flexible.

How about you think this...?

**Comment by marchdoe** [comment]
@usagi-f - awesome, sounds good to me, lets get this into master!

cc @ndelangen

**Review by marchdoe — APPROVED** [review]

**Review by Hypnosphi — APPROVED** [review]
Looks awesome to me

**Comment by ndelangen** [comment]
@marchdoe you can press 'Update branch' and then wait for the CI to finish and then press 'Merge' 😄👍

**Comment by ndelangen** [comment]
Congrats on your first merge as maintainer 👍

**Comment by usagi-f** [comment]
Thanks to everyone of the maintainers! 😆

I hope the storybook will be a valuable product!

**Pull request merged**
