### PR TITLE
MIGRATE to wrap emotion into a @storybook/theming package

### PR DESCRIPTION
**Pull request by ndelangen**
- This ensures a single version
- This adds a good place to add themes
- Addons can take a dependency on something storybook
- We could migrate to another styling lib without asking all users to migrate with us

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
LGTM. Should we include this in 5.0? Probably just about in time to scrape in before RC / feature freeze

**Comment by ndelangen** [comment]
Yes, should be in 5.0.0

I also plan on moving the router into it's own package too.

**Review by shilman — COMMENTED** [review]
@ndelangen Why did all the storyshots change?

Do you have anything else in mind before we feature freeze 5.0 and restrict PRs to bugfixes only (aside from the RN core refactor, which I know is going to take a little time cc @Gongreg @igor-dv)?

**Comment by ndelangen** [comment]
@shilman the storyshots change because the emotion jest snapshot thing no longer functions.

I personally think this is not a HUGE deal, though I'd like to fix it in the future. For the sake of debuggability.

**Pull request merged**
