### PR TITLE
Vite: Fix plugin types

### PR DESCRIPTION
**Pull request by IanVS**
Issue:

Fixes type errors that were originally ignored in https://github.com/storybookjs/storybook/commit/d1418038d32d7d8416df165ff6786a6e34f1b69d

## What I did

Used the proper type for plugins (PluginOption).

## How to test

- Green CI

### CODE REVIEW

**Comment by IanVS** [comment]
We're ending up with two different versions of vite installed, one beta version and one older one, due to dependencies.  I'll wait until vite 3.1.0 is released, then revisit this.

**Comment by shilman** [comment]
@IanVS any idea what's going on with CI?

**Comment by IanVS** [comment]
I fixed CI by adding the same `vite@3.1.0` to devDependencies of the vite framworks, to ensure we have the right minimum matching version between the builder and the frameworks.

**Review by shilman — APPROVED** [review]
LGTM! 👍

**Pull request merged**
