### PR TITLE
Move typings for @storybook/react to @types package

### PR DESCRIPTION
**Pull request by joscha**
Issue: #1166 

* [x] Hold off merging until https://www.npmjs.com/package/@types/storybook__react is available.
* [x] Update docs

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
@joscha this is awesome!! mind updating the docs as well and including that in the PR?

**Comment by ndelangen** [comment]
Thanks @joscha !

**Comment by joscha** [comment]
Docs updated in 5013dda - let's see how we go with this change and then we can update all the other packages.

**Comment by shilman** [comment]
Thanks so much @joscha . Going to test it out and then merge. Super excited about this!

**Review by shilman — APPROVED** [review]

**Comment by shilman** [comment]
@joscha worked like a charm. fabulous! 🌈 🦄 🌟

**Comment by joscha** [comment]
> @joscha worked like a charm. fabulous! 🌈 🦄 🌟

awesome, I'll be doing the other packages then as follow-ups.

**Comment by shilman** [comment]
@joscha @ndelangen @tmeasday I'd like to revert this change for now. It's a breaking change, so technically it would bump this release to 4.0.0 under semver, and I think we want to batch up breaking changes so that we aren't doing major releases all the time.

1) does this make sense to you guys?
2) (OR do you want to ditch semver and just release this is as 3.0.2, which is what it feels like?)
2) @joscha if we backed out this change, is it still possible for users to force typescript to use your `DefinitelyTyped` typings instead of these?

Thanks and sorry for the confusion!

**Comment by joscha** [comment]
> does this make sense to you guys?

makes sense, yes.

> (OR do you want to ditch semver and just release this is as 3.0.2, which is what it feels like?)

hmm, not sure how annoyed I would be if I had to run one little `yarn add @types/node @types/storybook__react` after upgrading, I personally would probably be okay with it, but it is not a no-brainer update as a patch should be, so maybe 4.0 sounds right?

> @joscha if we backed out this change, is it still possible for users to force typescript to use your DefinitelyTyped typings instead of these?

I don't think so, the `typings` definition in `package.json` takes precedence iirc, so it would shadow anything from `@types/...`. We'd need to keep the typings in definitelytyped updated alongside the ones in this repo for the time being and then remove the typings from this repo with the 4.0.0 release. Quite tedious and potentially confusing, but an easier upgrade path for users I suppose.

I haven't tried, but what if `@types/storybook__react` is made a dependency of `@storybook/react` for now and we reference the `./node_modules/@types/storybook__react/index.d.ts` from the `typings` key in `package.json` - does that work? Because then that would be a seamless upgrade until in 4.0.0 we can remove the absolute dependency as a breaking change. The only penalty to pay in the meantime is the weight of the additional package for users that don't use TS, but they currently pay a similar penalty with the additional type definition anyway.

**Comment by shilman** [comment]
Sorry for the confusion @joscha . See my updated comment above. 😵

**Pull request merged**
