### PR TITLE
FIX scrollbars in flexbar

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/11283 https://github.com/storybookjs/storybook/issues/11071

## What I did
I fixed the missing custom scrollbar on the FlexBar component

### CODE REVIEW

**Comment by domyen** [comment]
Nice work @ndelangen! 

The last thing is that the handle is missing when I hover over the bar. That makes it impossible for me to pan horizontally if I don't activate the scrolling first. Video below.

https://www.loom.com/share/4ddc5f68d9614a75b37bc645fad07f7c

**Comment by ndelangen** [comment]
Does any other place we use the custom scrollbars exhibit that described behavior?

**Comment by ndelangen** [comment]
K, I found the option in the overlayscrollbars library we use

**Comment by domyen** [comment]
nice lgtm

**Pull request merged**
