### PR TITLE
fix: set default theme according to preferred color scheme

### PR DESCRIPTION
**Pull request by fabioatcorreia**
Issue:
Currently, the theming documentation is not completely correct because "Unless you've set your preferred color scheme as dark" is not working.  
ref #6088

## What I did
Updated the `theme` under the `defaultState` to reuse the `create` function, which, when called without arguments, already returns the `ThemeVars` according to the preferred color scheme.

## How to test

Open up a browser which supports the preferred color scheme preference, with any Storybook without a custom theme and, check that its theme is according to your preference.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Hey @fabioatcorreia that's really sweet! Thank you for the contribution!!

**Comment by ndelangen** [comment]
@shilman perhaps though not technically a BREAKING change, it might be perceived as disruptive one for users...
After upgrading their storybook might be dark all of a sudden, when they did not expect this.

WDYT, do we release this in a minor, or wait for a major?

**Comment by ndelangen** [comment]
We currently support this:
```
addons.setConfig({
  theme: themes.dark,
});
```

It would be great if users could configure:
```
addons.setConfig({
  theme: 'auto',
});
```

**Comment by fabioatcorreia** [comment]
Sorry, but I couldn't understand if that last comment was meant for me or @shilman. @ndelangen?

**Comment by ndelangen** [comment]
@fabioatcorreia I was expressing concern that users of storybook might find the change disruptive (storybook could turn to dark-mode by default) for a minor version bump.

And I was mentioning that users could already opt-in to the behaviour this PR sets.
I'm not sure how to proceed. I agree this PR should be merged, I just don't know when.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
