### PR TITLE
add lerna badge in README

### PR DESCRIPTION
**Pull request by armujahid**
## What I did
added lerna badge in README
## How to test

- Is this testable with Jest or Chromatic screenshots? no need
- Does this need a new example in the kitchen sink apps? no need
- Does this need an update to the documentation? no need

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
As much as I appreciate how Lerna helps us maintain Storybook (it's truly awesome!), I don't think this badge is informative at the top of our README. I'd be open to creating some kind of acknowledgments section elsewhere in the documentation if we can find a good place for it.

**Comment by armujahid** [comment]
@shilman something like this https://github.com/gatsbyjs/gatsby#a-note-on-how-this-repository-is-organized?

**Comment by shilman** [comment]
@armujahid Maybe add a sentence to the beginning of the [Development scripts](https://github.com/storybooks/storybook#development-scripts) section?

```
Storybook is organized as a monorepo using [Lerna](https://lernajs.io). Useful scripts include:
```

**Comment by armujahid** [comment]
@shilman done

**Review by shilman — APPROVED** [review]
Thanks! 🙏

**Pull request merged**
