### PR TITLE
dependencies(vue): Update vue-loader to 15.x.x

### LINKED ISSUE #3509: vue-loader versions available: 15.0.0
There are new versions of vue-loader available from npm.

## 15.0.0

_No content found._

### PR DESCRIPTION
**Pull request by pksunkara**
Fixes #3509, #3492

### CODE REVIEW

**Review by igor-dv — COMMENTED** [review]
Thanks!

Looks a reasonable change, since we are preparing a breaking version of Storybook.

Any reason why the visual tests could fail, though?

image

**Comment by pksunkara** [comment]
I don't have any idea on why that is. I didn't dig deep because it was just a `<h1>` style change. Maybe the browser in chromatic changed. Do you want me to find out why this is happening?

**Comment by pksunkara** [comment]
Actually, found out why this is happening. You can see `h1` having `font-weight: normal` at https://github.com/storybooks/storybook/blob/83d55c23fa124fa87cd061bdb5b5ce9453b393c1/examples/vue-kitchen-sink/src/App.vue#L43-L45. But before this PR, this wasn't being used by the App. The `font-weight: bold` from the `user-agent` was being used.

So, I guess, this PR kinda fixes the behaviour now.

**Comment by igor-dv** [comment]
I don't understand how changing the `vue-loader` version fixes this

**Comment by pksunkara** [comment]
https://vue-loader.vuejs.org/migrating.html#style-injection
https://github.com/vuejs/vue-loader/commit/234d48b

**Comment by igor-dv** [comment]
Ah, thanks, got it.

**Review by igor-dv — APPROVED** [review]
@storybooks/team, speak now or forever hold your peace

**Comment by ndelangen** [comment]
Absolutely perfect!

**Pull request merged**
