### PR TITLE
src/middleware: open router handler for developers.

### PR DESCRIPTION
**Pull request by bshy522**
This commit allows the developers to customize the middleware.

### CODE REVIEW

**Comment by arunoda** [comment]
I wanna know why you need this.
Normally Storybook is a dev time tool and we normally don't need this or should not customize the server side.

**Comment by mnmtanish** [comment]
I think there are many valid use cases for this and users and addon developers can do many awesome things using this feature.

**But this feature comes with a huge cost**. At the moment, storybooks can be built as static webpages. This enables users to deploy them to GIthub pages, etc. (I have a few more features planned which also depend on being able to deploy as static web apps).

But let's keep this issue open so we can discuss it more and get more opinion

**Comment by arunoda** [comment]
I don't like to allow to configure Storybook in the server side. This will open to a lot of issues we never want to address.

**Comment by bshy522** [comment]
First, i'm so sorry. My engilish is very bad.

I am developing an in-house development tool based on storybook. 

I want to be able to dynamically generate some files in the server, through the HTTP to the client. For example, dynamically compiled a sass file.

So, open middleware to me is the most rapid solution. Doesn't seem to cause too much of a problem.

**Comment by erykpiast** [comment]
Another use case (my own) is proxy for API calls. Storybook is just as good tool that you can never find all ways to use it! And I use it to test parts of my app talking with not-really-cors-friendly API so I need a proxy. I'd not like to continue working on .bin/storybook changed by hand and not synchronized with this repository :)q

**Comment by mnmtanish** [comment]
> Currently addons have access to the 'Manager App' and the 'Preview Area'.
> 
> Adding an ability to inject custom (express) middleware would open up even more opportunities for creative addon-creators.
> 
> These custom middlewares can provide storybook with new features by enabling additional data retrieval for addons.
> 
> Some data examples of data:
> - unit tests
> - package / dependencies version & updates
> - package dependency graph
> - git & other system integrations
> 
> I don't think it's all that hard to implement via `config.js`.
>
> @ndelangen 
> https://github.com/storybooks/react-storybook/issues/638#issue-193380755

**Comment by mnmtanish** [comment]
Hi @bshy522 @erykpiast @ndelangen
This feature is available from `v2.34.0`

Here's an example `middleware.js` file

```js
module.exports = function (router) {
  router.get('/hello', (req, res) => {
    res.send('Hello World!');
    res.end();
  });
}
```

With this feature, we can also bring back the local-db:
https://github.com/kadirahq/storybook-database-local

**Comment by interactivellama** [comment]
It took me a few hours to find this and know that I needed to call the file `middleware.js` and put in the config folder. This would be nice to surface in the docs in an advanced section.

Thank you for making it so flexible though. It's now that I understand how to manipulate Express/Storybook.

**Comment by UsulPro** [comment]
hey, @interactivellama!
Could you share your experience? maybe short example? 😊

**Comment by interactivellama** [comment]
I just needed a url alias to align with our internal react project with the Salesforce Lightning Design System. The following simple middleware worked for me.

```
const expressMiddleWare = (router) => {
	router.use('/assets/icons',
		express.static(
			path.join(__dirname,
			'../node_modules/@salesforce-ux/icons/dist/salesforce-lightning-design-system-icons/')
		)
	);
};
```

My primary issue was that until I found this issue I knew how to do it in express, but not how to connect it to Storybook. I looked through the source code for a while and knew it could be done. So my request was just to say, "hey if you want Express middleware, then put it in a file called middleware.js in the config folder."

**Comment by ndelangen** [comment]
This feature needs proper documentation 😄

**Comment by vzaidman** [comment]
add the following "middleware.js" file to your .storybook folder:
```
const express = require('express')

const expressMiddleWare = router => {
  router.use('/static', express.static('./src/static'))
}

module.exports = expressMiddleWare
```
obviously you can config it as you like.

**Comment by ndelangen** [comment]
It's not been documented yet. 😞 

This won't work when you build a static version of storybook btw.

**Comment by Jigsaw-Jams** [comment]
Gotcha 😭 and thanks! It shouldn't be an issue since we only need it for local development. Our master Storybook has a Flask backend where we already have the proxy in place.

**Comment by theKashey** [comment]
Just a regular notice that this feature has to be documented 😉

**Comment by jamieowen** [comment]
Also it would be great to have typescript support for middleware 👍

**Comment by amaury-hanser** [comment]
For people having trouble using `middleware.js`, it seems that it doesn't like empty lines.

**Comment by alexandrzavalii** [comment]
would anyone know if its possible to use `middleware.js` to create a websocket?

**Comment by rnarcos** [comment]
Would it be possible for us to access the environment variables at this point (within the middleware definition)?

**Comment by Ananya-96** [comment]
@thani-sh  solution worked for me with storybook v6.3.8, angular v12 in development mode using start-storybook. But when I build the storybook using build-storybook, middleware is not getting included in the static build folder. Can someone help me with this?

**Comment by theKashey** [comment]
middleware __cannot be__ included in the static build due to the _static_(HTML, CSS, js) nature of the latter.

**Comment by AngelosTzetzias** [comment]
@theKashey or @Ananya-96 are you aware of a work around?
i want to be able to deploy my storybook on my website and i have apis for some stories that i mock / hard code through the middleware.js ....  I have managed to deploy but the apis are not mocked like they are when i run locally with middleware (setup of original project is angular 14 with nx) ... 

P.S. I ve also tried msw-storybook-addon but i dont seem to be able to make it work (not sure if its from my implementation or it just doesnt work with angular and nx). Any help / direction  would be appreciated thanks a lot

**Pull request merged**
