### PR TITLE
UI: Prebundle `@storybook/components`

### PR DESCRIPTION
**Pull request by ndelangen**
This uses https://github.com/storybookjs/storybook/pull/17000 to prebundle `lib/components`

### CODE REVIEW

**Comment by ndelangen** [comment]
hmmm.. 
```
export 'mdx' was not found in '@mdx-js/react'
```

**Comment by ndelangen** [comment]
@shilman any idea on the above?

**Comment by shilman** [comment]
@ndelangen looks like it's referenced here:

https://github.com/storybookjs/storybook/blob/next/addons/docs/jest-transform-mdx.js#L15

And looks like it's defined in the package:

```
exports.mdx = createElement;
```

So I'm not sure why it's failing 🤷‍♂️

**Comment by shilman** [comment]
@ndelangen aha here's why it's failing: https://github.com/mdx-js/mdx/releases/tag/2.0.0

something is installing 2.0 which was released 2h ago, and we're compatible with 1.x only.

**Comment by ndelangen** [comment]
ahh maybe this is is?
https://github.com/storybookjs/storybook/blob/ee1e8ec6a49a47fc0b394c6132660cb8c40e7bfe/lib/cli/src/generators/baseGenerator.ts#L89-L90

**Comment by ndelangen** [comment]
getting the same problem here:
https://github.com/storybookjs/storybook/pull/17375

**Comment by ndelangen** [comment]
@shilman This might be a pretty big deal!!

**Comment by ndelangen** [comment]
I had to add `@types/react` to angular to get it to compile... @gaetanmaisse WDYT about this?

**Comment by ndelangen** [comment]
Hmm, so that didn't work?

```
ERR! => Failed to build the preview
ERR! node_modules/@storybook/router/dist/ts3.9/_modules/react-router-dom-index.d.ts:57:20 - error TS2694: Namespace 'React' has no exported member 'HTMLAttributeAnchorTarget'.
ERR! 
ERR! 57     target?: React.HTMLAttributeAnchorTarget;
ERR!                       ~~~~~~~~~~~~~~~~~~~~~~~~~
ERR!
```

**Comment by ndelangen** [comment]
If I added `@types/react` to the packages (`router`, `theming`) wouldn't that potentially cause issues for Vue?

**Review by shilman — APPROVED** [review]
Great job @ndelangen 🎖️

**Pull request merged**
