### PR TITLE
Build: Fix DLL generation race condition

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/9707

## What I did
FIX it with some very funk setTimeout

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Ugly, but I'll take it if it works. I take it you've already tried smaller timeouts (0, 1) and that wasn't enough?

**Comment by ndelangen** [comment]
No I didn't try smaller ones, this was the first one I tried, and it worked.

Shall I lower this timeout?

**Comment by shilman** [comment]
Were you able to repro the problem in the first place? Like I said, I'll take it if it works.

But generally speaking the less funky stuff we have in our codebase the better. `setTimeout(0)` is very clear what it's doing. `setTimeout(1)` less clear. `setTimeout(5000)` seems pretty arbitrary. I'm not making a fuss, since this is a build script, but wanted to raise it. Guessing you already know all this, but it never hurts to overcommunicate. 😄

**Comment by ndelangen** [comment]
Yes I was able to reproduce.

I tested this twice on my local machine.

A 5 second delay was arbitrary, testing takes minutes, so after finding that the 5 second timeout worked, I was happy.

**Pull request merged**
