### PR TITLE
Fix bug in addons/graphql in reIndentQuery

### PR DESCRIPTION
**Pull request by jamsea**
Issue:
Creating a multi line graphiql query causes storybook to error out in version 3. This is because it tries to run `join` on a string rather than an array.

## What I did
Move the bracket so `join` is always appended to an array rather than a string.

## How to test
Try creating a story with a multi-line graphiql query and loading it.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Thank you @jamsea ! I don't know a lot of users of this addon, if you're using it please let us know how, and what you'd like to see improved?

**Comment by jamsea** [comment]
@ndelangen thanks for merging. We're using GraphQL for our new projects at the NFL and we're using this add on for internal documentation. We're already using story book as internal documentation for all of our react components so being able to integrate GraphQL examples in the same system was a life saver.

The only thing I wasn't able to figure out was adding an example GraphQL variable. Is there a way to do that currently or is that a new feature that would need to be developed?

**Comment by ndelangen** [comment]
Well I know it's using https://github.com/graphql/graphiql and supports it, but maybe it needs an update?

**Comment by shilman** [comment]
@jamsea do you happen to have any public storybooks from NFL you can share? i'm documenting examples here (placeholder, will be redesigned): https://storybook.js.org/examples/

**Pull request merged**
