### PR TITLE
chore(rax): supplement rax

### PR DESCRIPTION
**Pull request by SoloJiang**
1. Examples: use `@alib/build-scripts` instead `rax-scripts`
2. Addon: add rax contexts addon
3. Docs: add rax to README, and we need an online example `https://storybooks-rax.netlify.com/`

### CODE REVIEW

**Comment by shilman** [comment]
Awesome @SoloJiang !!! Thanks~

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Hey @SoloJiang amazing work!

We have visual regression:
https://www.chromaticqa.com/snapshot?appId=5def6514ca0cac00201af360&id=5e00bd0dc2ab7000205d1c92

Can you either approve or fix them?

**Comment by SoloJiang** [comment]
@ndelangen Okay, I will resolve it later~

**Comment by SoloJiang** [comment]
@ndelangen Okay, I will resolve it later~

**Comment by ndelangen** [comment]
Thanks!

**Comment by SoloJiang** [comment]
@ndelangen Can you help me resolve the conflict ?

**Comment by ndelangen** [comment]
I merged in the bae branch and resolved conflicts

**Comment by SoloJiang** [comment]
> I merged in the bae branch and resolved conflicts
When can you merge this branch ?

**Pull request merged**
