### PR TITLE
add clarification

### PR DESCRIPTION
**Pull request by stevendavisfoto**
this was confusing to me since there is also a config directory.

Issue:

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ndelangen** [comment]
This should target the next branch (the default branch) not master

**Review by ndelangen — CHANGES_REQUESTED** [review]
Could you perhaps rebase your commit unto the next branch?

**Comment by shilman** [comment]
@ndelangen FYI documentation fixes to `master` are fine. I patch them both ways.

**Comment by ndelangen** [comment]
Ow really? I didn't know

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
