### PR TITLE
Fix centered addon for IE11

### PR DESCRIPTION
**Pull request by sam-at-work**
Issue:
https://github.com/storybooks/storybook/issues/2525

## What I did
Fix the style rules for centered add on so that it works correctly in IE11

## How to test

Look at centered add on in IE 11. Components will now be correctly centered

### CODE REVIEW

**Comment by sam-at-work** [comment]
@brianespinosa you might be interested in checking this?

**Comment by danielduan** [comment]
Looks good but I think this breaks some snapshots so those will need to be updated.

**Review by Hypnosphi — APPROVED** [review]

**Comment by sam-at-work** [comment]
@danielduan I've updated the snapshots.
Got an error running `yarn test` then update:
```
$ yarn test
yarn run v1.7.0
$ node ./scripts/test.js
? Select which tests to run Update all snapshots (update)
● Validation Error:

  Module <rootDir>/node_modules/react-native/jest/assetFileTransformer.js in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
but running `node node_modules/jest/bin/jest.js -u` worked.

**Review by danielduan — APPROVED** [review]

**Comment by danielduan** [comment]
@Hypnosphi I'm not sure why the Danger CI is failing, but this looks good to go.

**Pull request merged**
