### PR TITLE
Added addon-knobs to crna and vanilla react native.

### PR DESCRIPTION
**Pull request by Gongreg**
## What I did

Added example taken from cra example.

## How to test
Try it out.

### CODE REVIEW

**Comment by tmeasday** [comment]
I don't reckon the duplication is an issue!

Can you update the snapshot? Should be a matter of running `npm test -- -u` and checking in the snapshot changes.

**Comment by Gongreg** [comment]
@tmeasday, alright, I'll do it tomorrow. :)

**Review by danielduan — APPROVED** [review]
These look good to me. The duplication errors are there to help us find redundant code, but this should probably be duplicated.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I fixed a merge-conflict in the package.json

**Comment by ndelangen** [comment]
TESTED

**Pull request merged**
