### PR TITLE
Custom scrollbars #5421

### PR DESCRIPTION
**Pull request by domyen**
Issue: #5421 

## What I did
- Styled scrollbars using [SimpleBar](https://github.com/Grsmto/simplebar) for nicer scrollbar UX, hoverable, customizable, cross-browser, etc. This is the same lib that codepen.io uses.

Note: I initially tried implementing this with CSS-only but was unable to achieve the desired styling and interaction.

## How to test
Custom scrollbars are present in 4 places.  Resize your window or drag to expand the Sidebar to see the overflow behavior. Omission from the preview iframe is intentional.

**Sidebar** 
image

**Canvas Toolbar**
image

**Addon bar**
image

**Addon panel**
image

### CODE REVIEW

**Comment by domyen** [comment]
@ndelangen Made the changes you requested. I need help with an issue with Toolbar scrolling. Can you take a look?

**Issue:**
Scrolling the `Bar` component works as expected for Addons
image


But Canvas Toolbar shows a vertical scrollbar:
image

**Hypothesis**
I suspect this happens because we add items to the Toolbar _after_ the scrolling lib instantiates. One thing to try is [recalculating the scrollbar](https://github.com/Grsmto/simplebar#notifying-the-plugin-of-content-changes) when the Toolbar completes loading addons.

**Comment by shilman** [comment]
@domyen Is this still `do not merge`?

**Comment by domyen** [comment]
Yea, don’t know why I removed that. Norbert is working through this one
with me.

**Comment by domyen** [comment]
Awesome work @ndelangen! 

The bugs I noticed: 
- Addons bar is not 40px high
image

- ActionBar not being positioned in the bottom right of the panel. 
image
image

**Comment by domyen** [comment]
This is ready to go from my end @ndelangen. There was a typescript issue that prevented me from updating snapshots though. Mind taking a look?

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
