### PR TITLE
CLI: Reuse existing chromium tab if possible

### LINKED ISSUE #10328: Reuse existing tab if possible
**Is your feature request related to a problem? Please describe.**
Whenever I am making changes to configuration files (e.g. adding a new addon) or just leaving tabs open because I forgot them open, I end up in a situation like this as result of running storybook multiple times:
image

It's a bit frustating.

**Describe the solution you'd like**
Would be nice if it could reuse an existing tab.

**Are you able to assist bring the feature to reality?**
Sure thing, it's on the way 🚀

### PR DESCRIPTION
**Pull request by yannbf**
Issue: #10328 

## What I did
This PR moves from the library open to better-opn. What it does is basically tries to use the well known solution [started at CRA](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/openBrowser.js), with an applescript to check if there is an existing tab on chrome and if so, reuses it. As a fallback, it uses the `open` lib.

This feature is unfortunately available on OSX Chrome only. `better-opn` is entirely based in the solution from facebook, and actually they recently added support for chromium based browsers [here](https://github.com/facebook/create-react-app/commit/d2de54b25cc25800df1764058997e3e274bd79ac). I might add a PR on `better-opn` to update that as well.

The alternatives to support reusing tabs are:

**instead of using:**
`import open from 'better-opn'`
**use:**
`import open from 'react-dev-utils/openBrowser'`
However they do not recommend to use their internal tools directly because they can always change it without notice. In this particular case, I guess the chances are small though.

## How to test

On OSX, checkout the branch and run `yarn start`, then kill the process and run it again.
You should see the tab being reused.
I couldn't test on windows, but as the lib falls back to `open`, it should behave the same as before, but of course if someone could test it out would be great.

closes #10328

### CODE REVIEW

**Comment by yannbf** [comment]
update: PR is open to update `better-opn` at https://github.com/ExiaSR/better-opn/pull/5, so if that is also merged then and storybook does use the lib, it will reuse the existing tab for most if not all chromium based browsers 😄

**Review by shilman — APPROVED** [review]
Awesome!! Should we wait until the `better-opn` PR is merged?

**Comment by yannbf** [comment]
> Awesome!! Should we wait until the `better-opn` PR is merged?

It's been merged and I have updated it! It would be great however if someone with windows could run it. It should be fine as it uses `open` as a fallback, but as I could not test I'd prefer if we could make sure it works fine.

**Comment by yannbf** [comment]
Did anyone by any chance manage to test on windows?

**Comment by shilman** [comment]
Yes, I think @tooppaaa tested on windows 👍

**Pull request merged**
