### PR TITLE
Fix(react-native) add missing `ws` dependency

### PR DESCRIPTION
**Pull request by joeybaker**
## Issue
`ws` was a dependency, but wasn't specified in `package.json`. We got away with this b/c `ws` is a dependency of `react-native`, but that causes a problem because the version of `ws` used by `storybook` is non-deterministic. This can cause the following error on startup:

```
this.wsServer = _ws2.default.Server({ server: this.httpServer });
                                 ^

TypeError: Class constructor WebSocketServer cannot be invoked without 'new'
    at new Server (.../node_modules/@storybook/react-native/dist/server/index.js:48:34)
```
## What I did
Added `new`, and added `ws` to `package.json`

## How to test
Just run `storybook start`. It now works. Before, it would crash.

### CODE REVIEW

**Review by ndelangen — DISMISSED** [review]

**Comment by ndelangen** [comment]
Thanks, I'll ask another react-native user to give this a test. on positive I'll merge it!

Can you explain to error message / bug a bit more? So it can be tested better and have a good changelog later on.

**Comment by joeybaker** [comment]
Sure? I just ran `storybook start` and got the stated error. It looks like an oversight/typo/node version issue.

**Comment by joeybaker** [comment]
Howdy @shilman – how would you like me to test this? There don't appear to be any tests setup for this kind of thing as far as I can tell?

**Comment by shilman** [comment]
Hi @joeybaker FYI I dismissed @ndelangen 's review because he didn't test it, not because you didn't provide tests.

We were discussing this in Slack and are a little confused about the change, since we've all been using storybook/react-native without problems. I'll work with you to get this in, or at least figure out what's going on.

**Comment by joeybaker** [comment]
hmmm… I'm not quite sure how I'm special. I'm happy to hope into a slack/IRC if you want. 

FWIW, the `ws` docs pretty clearly indicate that they require `new` to be used.

**Comment by shilman** [comment]
Sure, jump into slack, or we can discuss here. Either way!

https://storybooks-slackin.herokuapp.com/

If you can provide a broken repro, I'd love to look at it. I'll also provide you a working repro, and you can try it on your machine.

**Comment by sgtsquiggs** [comment]
This fix works for me locally as well.

**Comment by shilman** [comment]
@joeybaker don't doubt your fix, just trying to understand why it's working for most people. here's the simple repro that works on my machine:

shell1:
```sh
yarn create react-native-app rnapp
cd rnapp
getstorybook
yarn storybook
```

shell2:
```
open http://localhost:7007
yarn run ios
```

If I understand your fix properly this should break, but it doesn't. Any ideas?

**Comment by joeybaker** [comment]
Hmm… a few thoughts:

* I'm running node v7.9, maybe there's a difference there?
* I didn't use CRNA, maybe the dependency order matters?

**Comment by shilman** [comment]
@joeybaker mind sharing an analogous repro? I'd love to figure this out

**Comment by ajwhite** [comment]
This is a little bit of a tricky one, the new keyword was introduced in [v2.0.0](https://github.com/websockets/ws/releases/tag/2.0.0).

If you notice, `@storybook/react-native` does not specify the version of `ws`, it's implicitly using [React Native's dependency on `ws`, which is at `v1.1.x`](https://github.com/facebook/react-native/blob/b975342e7b1fb708e1be4e277215772e8b714ddd/package.json#L216).

@joeybaker - does your project define it's own `ws` dependency above `1.x`?

**Comment by ajwhite** [comment]
What we should probably do is add a dependency to `@storyboard/react-native` specifying `3.x`

**Comment by ajwhite** [comment]
I _think_ this is okay? It's marked as "extraneous", but I think it would still use it?

screen shot 2017-06-01 at 1 52 01 pm

**Package A (test-a)**
- `ws@3.0.0`

**Package B (test-b)**
- `package-a`
- `ws@1.1.0`

yields
```
test-b@1.0.0 /Users/atticus/Desktop/test-b
├─┬ test-a@1.0.0 invalid
│ └── ws@3.0.0 extraneous
└─┬ ws@1.1.0
  ├── options@0.0.6
  └── ultron@1.0.2
```

**Comment by joeybaker** [comment]
@ajwhite Good call! We specify `v1.1.1` for `ws`, but yarn.lock has:

```
ws@3.0.0:
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/ws/-/ws-3.0.0.tgz#98ddb00056c8390cb751e7788788497f99103b6c"
  dependencies:
    safe-buffer "~5.0.1"
    ultron "~1.1.0"

ws@^1.1.0:
  version "1.1.4"
  resolved "https://registry.yarnpkg.com/ws/-/ws-1.1.4.tgz#57f40d036832e5f5055662a397c4de76ed66bf61"
  dependencies:
    options ">=0.0.5"
    ultron "1.0.x"

ws@^2.0.3:
  version "2.3.1"
  resolved "https://registry.yarnpkg.com/ws/-/ws-2.3.1.tgz#6b94b3e447cb6a363f785eaf94af6359e8e81c80"
  dependencies:
    safe-buffer "~5.0.1"
    ultron "~1.1.0"
```

Resulting in:

```sh
cat node_modules/ws/package.json | json version
→ 3.0.0
```

So, if `storybook/react-native` doesn't specify a `ws` version it'll get v3 in our project.

The answer to your second question is that the two `ws` dependencies don't conflict – that's part of the genius of `npm`'s original design :)

I completely agree that `storybook/react-native` should always specify all it's dependencies.

**Comment by ajwhite** [comment]
> The answer to your second question is that the two `ws` dependencies don't conflict – that's part of the genius of `npm`'s original design :)

😃  thanks for clearing this up! I felt like this was the answer, but wanted to be _100%_.

So it sounds like we can add the appropriate version as a dependency and we should be good here. I think we can all agree being on the later version is the proper path forward?

**Review by atticoos — DISMISSED** [review]
Since the current form will lead to a breaking change, dropping in this review to make sure we add the `ws` dependency to `@storybook/react-native` before merging

**Comment by joeybaker** [comment]
@ajwhite I added `ws` to `package.json`, but I don't have time to test this out.

**Comment by ajwhite** [comment]
Thanks @joeybaker, if anyone can give this a test that would be great. Otherwise I can try to follow up tomorrow 📆

**Comment by shilman** [comment]
@joeybaker @ajwhite tested on my local machine with CRNA. Before this PR:

```
rnapp@0.1.0 /Users/shilman/projects/storybook/new/rnapp
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
└─┬ UNMET PEER DEPENDENCY react-native@0.44.2
  ├─┬ react-devtools-core@2.2.1
  │ └── ws@2.3.1 
  └── ws@1.1.4 
```

After this PR:

```
rnapp@0.1.0 /Users/shilman/projects/storybook/new/rnapp
├─┬ @storybook/react-native@3.0.0 invalid
│ ├── UNMET PEER DEPENDENCY react@15.5.4 extraneous
│ └── ws@3.0.0  extraneous
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
└─┬ UNMET PEER DEPENDENCY react-native@0.44.2
  ├─┬ react-devtools-core@2.2.1
  │ └── ws@2.3.1 
  └── ws@1.1.4 
```

And it's working for me. Merging. Thanks for the fix @joeybaker and @ajwhite !

**Review by shilman — APPROVED** [review]
@joeybaker @ajwhite tested on my local machine with CRNA. Before this PR:

```
rnapp@0.1.0 /Users/shilman/projects/storybook/new/rnapp
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
└─┬ UNMET PEER DEPENDENCY react-native@0.44.2
  ├─┬ react-devtools-core@2.2.1
  │ └── ws@2.3.1 
  └── ws@1.1.4 
```

After this PR:

```
rnapp@0.1.0 /Users/shilman/projects/storybook/new/rnapp
├─┬ @storybook/react-native@3.0.0 invalid
│ ├── UNMET PEER DEPENDENCY react@15.5.4 extraneous
│ └── ws@3.0.0  extraneous
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
└─┬ UNMET PEER DEPENDENCY react-native@0.44.2
  ├─┬ react-devtools-core@2.2.1
  │ └── ws@2.3.1 
  └── ws@1.1.4 
```

And it's working for me. Merging. Thanks for the fix @joeybaker and @ajwhite !

**Pull request merged**
