### PR TITLE
Storybook v8.0.0 initial merge

### PR DESCRIPTION
**Pull request by JReinhold**
This PR represents the temporary v8 branch of Storybook, that is used as a target for any breaking changes coming in 8.0.

When we're getting closer to finalising 8.0 and we don't plan on doing anymore 7.x minor releases, we'll merge this branch into next, and next will be the branch for 8.0 prereleases.

### 🦋 Canary release

This pull request has been released as version [`0.0.0-pr-24271-sha-4a56eddc`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-24271-sha-4a56eddc). Install it by pinning all your Storybook dependencies to that version.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-24271-sha-4a56eddc`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-24271-sha-4a56eddc) |
| **Triggered by** | @shilman |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`release-8-0`](https://github.com/storybookjs/storybook/tree/release-8-0) |
| **Commit** | [`4a56eddc`](https://github.com/storybookjs/storybook/commit/4a56eddc2269e3ee9c8cb0294e1c4fbcffee225a) |
| **Datetime** | Tue Nov 14 09:23:30 UTC 2023 (`1699953810`) |
| **Workflow run** | [6861600286](https://github.com/storybookjs/storybook/actions/runs/6861600286) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=24271`_
</details>

### CODE REVIEW

**Comment by ndelangen** [comment]
@SocketSecurity ignore undici-types

**Comment by ndelangen** [comment]
https://github.com/SocketSecurity ignore undici-types@*

**Comment by ndelangen** [comment]
@SocketSecurity ignore undici-types@*

**Comment by ndelangen** [comment]
@cdedreuille could you resolve the merge conflict on `NotificationList.tsx`?

**Comment by cdedreuille** [comment]
> @cdedreuille could you resolve the merge conflict on `NotificationList.tsx`?

Done @ndelangen

**Pull request merged**
