### PR TITLE
CLI: Don't add `@storybook/addon-links` by default

### LINKED ISSUE #29073: Remove `@storybook/addon-links` from the default addons that are part of `init`

### PR DESCRIPTION
**Pull request by tobiasdiez**
Closes https://github.com/storybookjs/storybook/issues/29073

## What I did

The link addon is installed by default when initializing storybook using the cli. Thus, I think, it make sense to make it part of "@storybook/essential-addons". One less package whose version has to be synchronized with the main storybook version and makes manual installation a bit simpler as well.

But maybe there was a reason why it was not essential...sorry if I might reopen an old discussion, this was not my intention.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  77.5 MB | 77.5 MB | 0 B | **3.74** | 0% |
| initSize |  162 MB | 162 MB | -19.6 kB | 0.27 | 0% |
| diffSize |  85 MB | 84.9 MB | -19.6 kB | -0.56 | 0% |
| buildSize |  7.57 MB | 7.57 MB | -2.11 kB | -1.14 | 0% |
| buildSbAddonsSize |  1.66 MB | 1.66 MB | -957 B | -1.06 | -0.1% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  2.34 MB | 2.34 MB | 0 B | - | 0% |
| buildSbPreviewSize |  352 kB | 352 kB | 0 B | - | 0% |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  4.55 MB | 4.55 MB | -957 B | -1.06 | 0% |
| buildPreviewSize |  3.02 MB | 3.02 MB | -1.15 kB | -1.22 | 0% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  17.5s | 23.4s | 5.9s | 1.08 | 25.4% |
| generateTime |  22.8s | 21.4s | -1s -377ms | 0.82 | -6.4% |
| initTime |  14.6s | 15.5s | 910ms | -0.47 | 5.9% |
| buildTime |  9.9s | 11.1s | 1.1s | -0.11 | 10.7% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  6.6s | 6s | -536ms | **-1.65** | 🔰-8.8% |
| devManagerResponsive |  4.4s | 4s | -333ms | **-1.33** | 🔰-8.2% |
| devManagerHeaderVisible |  782ms | 662ms | -120ms | **-1.88** | 🔰-18.1% |
| devManagerIndexVisible |  817ms | 693ms | -124ms | **-1.83** | 🔰-17.9% |
| devStoryVisibleUncached |  1.3s | 1s | -321ms | **-1.78** | 🔰-31.8% |
| devStoryVisible |  816ms | 694ms | -122ms | **-1.81** | 🔰-17.6% |
| devAutodocsVisible |  632ms | 656ms | 24ms | -1.04 | 3.7% |
| devMDXVisible |  666ms | 579ms | -87ms | **-1.96** | 🔰-15% |
| buildManagerHeaderVisible |  716ms | 635ms | -81ms | **-1.64** | 🔰-12.8% |
| buildManagerIndexVisible |  722ms | 641ms | -81ms | **-1.68** | 🔰-12.6% |
| buildStoryVisible |  782ms | 670ms | -112ms | **-1.78** | 🔰-16.7% |
| buildAutodocsVisible |  664ms | 596ms | -68ms | **-1.44** | 🔰-11.4% |
| buildMDXVisible |  652ms | 576ms | -76ms | **-1.48** | 🔰-13.2% |

## Greptile Summary

This PR marks the link addon as essential by incorporating it into the @storybook/addon-essentials package. Key changes include:

- Removed '@storybook/addon-links' from various configuration files and examples
- Added link addon to @storybook/addon-essentials package.json
- Created new files in code/addons/essentials/src/links for manager and preview
- Updated @storybook/addon-links package.json to include 'essentials' keyword
- Simplified addon installation process in CLI and generators

These changes streamline Storybook setup by including the link addon by default, reducing manual configuration and version synchronization needs.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Removing it from the default generator is an option as well 😄 I've done just that now.

It may be the case that it now has be added to the sandbox. Not sure how/where to do this best though.

**Comment by JReinhold** [comment]
Nice!

> It may be the case that it now has be added to the sandbox. Not sure how/where to do this best though.

I think you can add it by concating `link` to the `addons` array in this for loop:

https://github.com/storybookjs/storybook/blob/next/scripts/tasks/sandbox-parts.ts/#L178

**Review by jonniebigodes — APPROVED** [review]
@tobiasdiez, thank you for taking the time to put together this pull request and help with the documentation. I appreciate it 🙏 ! From my end (docs-wise), everything is good. I'm going to approve this, but I'll defer to the rest of the team for their input.

Hope you have a great day.

Stay safe

**Comment by tobiasdiez** [comment]
@JReinhold Thanks, but it seems this is actually not required (at least the test pass).

@jonniebigodes Thanks for the review!

**Comment by JReinhold** [comment]
> @JReinhold Thanks, but it seems this is actually not required (at least the test pass).

I see. 🤔 This might be because we add resolutions for it too.

**Review by JReinhold — APPROVED** [review]

**Pull request merged**
