### PR TITLE
Core: Add STORYBOOK environment variable

### PR DESCRIPTION
**Pull request by toshi1127**
Issue: #12416

## What I did
By Default, the environment variable `STORYBOOK` is set to `true`.

## How to test

- Is this testable with Jest or Chromatic screenshots?
yes.
I have tested that `process.env.STORYBOOK` is set to true.
image

- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?
Should I update [this document](https://storybook.js.org/docs/react/configure/environment-variables)?

### CODE REVIEW

**Comment by shilman** [comment]
@tmeasday WDYT? seems reasonable but I'm a little unclear on the use case

**Comment by tmeasday** [comment]
Sure, seems reasonable to me

**Comment by shilman** [comment]
Aha @toshi1127 this got converted to TS recently. Any chance you can redo the PR in the new files?

**Comment by toshi1127** [comment]
@shilman 
Of course.
I've fixed the same in the new file!

**Review by shilman — COMMENTED** [review]
Thanks @toshi1127 -- looking good!

**Review by shilman — APPROVED** [review]
Thanks @toshi1127 -- looking good!

**Comment by tremby** [comment]
Did this feature disappear? I need to change some postcss config for Storybook only, but in postcss.config.js `process.env.STORYBOOK` is undefined.

**Comment by oriooctopus** [comment]
Yeah, I'm also not seeing this anymore @shilman. Version 6.4.7

**Comment by yogarasu** [comment]
I found the current source
It's not working, but ...

version 6.5.9

https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/utils/envs.ts#L15

**Pull request merged**
