### PR TITLE
Remove text transform uppercase for knob labels

### PR DESCRIPTION
**Pull request by cnandreu**
Issue:

## What I did

Removed `text-transform: uppercase` from knob labels.

## How to test

Create a knob that's camel case (e.g. `boolean("isCollapsed", false)`). It should render `isCollapsed` instead of `ISCOLLAPSED`.

## FYI

I found this PR that does the same thing:

"Remove UPPERCASE text-transform from labels #53"
https://github.com/storybooks/storybook-addon-knobs/issues/53
but it looks like the `storybooks/storybook-addon-knobs` repository is now deprecated.

I saw this related issue on this repository:

"Remove UPPERCASE text-transform from labels #793"
https://github.com/storybooks/storybook/issues/793

with a comment saying:

> A PR fixing this was merged couple days ago.

but I still see `text-transform: 'uppercase'` on master:
https://github.com/storybooks/storybook/blob/master/packages/addon-knobs/src/components/PropField.js#L22

Sorry if this is a duplicate of something else I didn't find.

### CODE REVIEW

**Comment by aaronmcadam** [comment]
What's the motivation behind this change?

**Comment by cnandreu** [comment]
> What's the motivation behind this change?

I want to have a 1 to 1 mapping between props and knob labels. It's harder to read camel case props if you uppercase them  (e.g. ISCOLLAPSABLECHILD vs isCollapsableChild). Now there's no way to make them preserve casing, but with my PR you can choose to pass the label with all uppercase characters if you want it that way (e.g. 'boolean("LABEL, false)').

**Review by aaronmcadam — APPROVED** [review]

**Comment by cnandreu** [comment]
@aaronmcadam do you know if there's someone I can tag to get this merged (or have an additional code review and changes, if necessary)?

**Comment by aaronmcadam** [comment]
What do you think @ndelangen? Is this good to merge?

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
