### PR TITLE
Vue3: Update args without re-mounting component

### PR DESCRIPTION
**Pull request by thomasaull**
Issue: https://github.com/storybookjs/storybook/issues/13913

## What I did

Change `app:vue3` to update args, when user updates controls instead of re-mounting the entire component
- reassign `activeStoryComponent` only, when `forceRender` is not true (e.g. when changing stories)
- add `storyArgs` data to root vue component
- when rendering the actual story component, reading the `storyArgs` from the root vue component and use those as props

I based the changes on what I understand was done in `app:vue`, although everything is a bit different there. Happy to improve this further if anyone has suggestions.

## How to test

- Run example `vue-3-cli`
- Add the following to `Button.vue`:
```js
mounted() {
  console.log('mounted')
}
```
- Open storybook: http://localhost:6006/?path=/story/example-button--primary
- Update controls → there should not be any console log `mounted`
- Change story → there should be a console log `mounted`

I feel like this does not need an example, happy to include one if wanted though

### CODE REVIEW

**Comment by thomasaull** [comment]
Ok I just found a small bug with this one, considering the following example:

```js
const Template = (args) => ({
  components: { MyComponent },

  setup() {
    return {
      args,
    }
  },

  template: `
    <MyComponent
      v-bind="args"
    />
  `,
})
```
Even when I would remove the line `v-bind="args"`, all the args would be passed to the component. This is problematic, for example, when I want to define an arg via an argType and don't pass it to the component:

```js
const Template = (args) => ({
  components: { MyComponent },

  setup() {
    return {
      args,
    }
  },

  template: `
    <MyComponent
      v-bind="args"
    >
      {{ args.label }} <!-- I don't want this to be passed to the component --!>
    </MyComponent>
  `,
})
```

**Comment by thomasaull** [comment]
Follow up to my [last comment](https://github.com/storybookjs/storybook/pull/15168#issuecomment-858147894):

It does not seem to be a bug, but instead the way the story template is defined. When I change the example in `Button.stories.js` of `examples/vue-3-clip` it works just fine:

```js
const Template = (args, { argTypes }) => ({
  // Components used in your story `template` are defined in the `components` object
  components: { MyButton },
  props: Object.keys(argTypes),
  // And then the `args` are bound to your component with `v-bind="args"`
  template: '<my-button v-bind="$props"/>',
});
```

It seems to make the update of props/state work I reintroduced some changes, which were removed in https://github.com/storybookjs/storybook/pull/13981/files and I'm not sure if you can achieve this without relying on props… Maybe @phated has some ideas?

**Comment by pocka** [comment]
@shilman Took a look and realized it's vue3 :open_mouth: Probably vue3 guys are suitable for a reviewer.

**Comment by shilman** [comment]
@pocka we have no vue3 guys at this point 🙈

**Comment by thomasaull** [comment]
> @pocka we have no vue3 guys at this point 🙈

You guys remember who did the initial integration for vue3?

**Comment by thomasaull** [comment]
@shilman Any idea how we can progress on this?

**Comment by shilman** [comment]
@thomasaull i'll try to kick the tires right now to get it unstuck

**Review by shilman — APPROVED** [review]
Looking good! I'd like somebody more familiar with Vue3 to review, but I've tested it and it's looking good.

**Comment by thomasaull** [comment]
> Looking good! I'd like somebody more familiar with Vue3 to review, but I've tested it and it's looking good.

Sorry for the late reply, awesome this has been merged and is now released in the 6.3.0 :) A follow up question regarding https://github.com/storybookjs/storybook/pull/15168#issuecomment-858408687: From my perspective it would make sense to reintroduce the „old” way of writing vue stories as the recommended defaults, since it solves this issue and in general feels more like the way vue components are used in the wild. I understand, my view might be limited though and others have different opinions about that. If you want me to update the examples, let know. Additionally I could offer to ping some of the people in my network to chime in with their opinion

**Pull request merged**
