### PR TITLE
Update jest-preset-angular to 8.2.0

### PR DESCRIPTION
**Pull request by adover**
Issue:
Issue: #9072 - Affects addon-storyshots

## What I did
Modified the path to jest-preset-angular/setupJest as per migration documentation https…://github.com/thymikee/jest-preset-angular/blob/5c071692d174d78639f952bf795bc06abd72d28c/CHANGELOG.md#migration-guide

Updated jest.config references to preprocessor.js

### CODE REVIEW

**Comment by adover** [comment]
Hi @shilman here's another attempt. I found a few other things which needed to be updated. Please take a look and let me know if there are any other issues

**Comment by ndelangen** [comment]
There are some issues left i think:

```
/tmp/storybook/addons/storyshots/storyshots-core/src/frameworks/angular/renderTree.ts
  1:1   error  Unused eslint-disable directive (no problems were reported from 'import/no-extraneous-dependencies')
  2:39  error  Unable to resolve path to module 'jest-preset-angular/AngularSnapshotSerializer'                      import/no-unresolved
  3:1   error  Unused eslint-disable directive (no problems were reported from 'import/no-extraneous-dependencies')
  4:35  error  Unable to resolve path to module 'jest-preset-angular/HTMLCommentSerializer'                          import/no-unresolved
```

**Comment by ndelangen** [comment]
fixed, maybe..

**Comment by ndelangen** [comment]
@adover Do you think you could take a look at the CI failures?
https://circleci.com/gh/storybookjs/storybook/217155?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by adover** [comment]
@ndelangen I've found a few more issues and fixed those. Will wait and see what the CircleCI says this time.

**Comment by adover** [comment]
@ndelangen @shilman it looks like only snapshots are failing now. I'm on a Windows machine so it may not be best for me to update them. Would one of you be able to do this?

**Comment by ndelangen** [comment]
For sure! thanks so much for the help!

**Review by shilman — APPROVED** [review]
Thanks @adover !!! 🥇

**Pull request merged**
