### PR TITLE
Change example repository with new CRA and Typesc…

### PR DESCRIPTION
**Pull request by Luchanso**
## What I did
Change example repository with fresh dependencies

## How to test
- Clone example repository
- Run following commands in repo:
```
yarn
yarn storybook
```
- Check storybook work

### CODE REVIEW

**Comment by shilman** [comment]
This looks great. Have you tried the typescript preset? https://www.npmjs.com/package/@storybook/preset-typescript

**Comment by Luchanso** [comment]
@shilman nope, but I'll try tomorrow

**Comment by mrmckeb** [comment]
Hi there, I think this should be handled by the new CRA preset, without a preset for TypeScript. How do we feel about that?

**Comment by shilman** [comment]
@mrmckeb that sounds right to me!

**Comment by ndelangen** [comment]
@mrmckeb So we do not want to combine the typescript preset plus the cra preset.

That sounds right to me too.

How does that relate to this PR? Is this mergeable still, or should it be migrated to use the preset before merging?

**Comment by mrmckeb** [comment]
We could merge this in now, I'll need to rewrite in the very near future when we do a non-beta release of the preset (which will also have docgen in it).

**Pull request merged**
