### PR TITLE
Fixed Jest warnings

### PR DESCRIPTION
**Pull request by dangreenisrael**
Issue: N/A

## What I did
I fixed all Jest warnings except one in `addons/info/src/index.test.js`

No functionality was changed, I just cleaned up some test to make sure that everything marked as `.isRequired` in `propTypes` was indeed provided.

### CODE REVIEW

**Comment by ndelangen** [comment]
What a great first PR!, thank you! Will we be seeing more PRs like this from you? 😍

**Review by ndelangen — APPROVED** [review]
TESTED

**Comment by dangreenisrael** [comment]
@ndelangen Thanks for the kind words 😄 . You absolutely will be seeing more of me - I really want to get more into contributing to open source projects and I am really loving storybook.

**Comment by ndelangen** [comment]
If you're not already on there, please join our slack. You can self-invite here: https://now-examples-slackin-nqnzoygycp.now.sh/

If you need any help from me or anyone else in the community that's probably the best place to ask.
I'm always excited to be helping new contributors!

**Comment by ndelangen** [comment]
If you're into testing, this might be a awesome follow-up:
https://github.com/storybooks/storybook/issues/1746

You'll instantly be @shilman's best buddy!

**Pull request merged**
