### PR TITLE
Feat: Add support for Flow to @addons/storysource

### PR DESCRIPTION
**Pull request by Nemvts**
Issue: Feat: #4955 

## What I did
Add `Prettier` Flow parser to `@addons/storysource`

`flow` is now an available option for parser under the `loader` options

## How to test
I added some flow type annotations to a few kitchen sink app stories to ensure that storybook was able to launch and storysource was able to parse Flow's syntax.

- Is this testable with Jest or Chromatic screenshots? 
Can create a mock file to test the inject decorator with flow stories

- Does this need a new example in the kitchen sink apps?
No

- Does this need an update to the documentation?
Yes, include flow as an available option.

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by igor-dv — COMMENTED** [review]
LGTM, but can you please add some flow usecase to https://github.com/storybooks/storybook/blob/next/addons/storysource/src/loader/inject-decorator.test.js?

**Comment by Nemvts** [comment]
I have added unit tests for the flow usecase and the code coverage looks good now.

**Comment by igor-dv** [comment]
Can you please merge from the `next` branch. Should solve the CI problems

**Comment by ndelangen** [comment]
I merged in next for you

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@igor-dv Do you feel strongly about https://github.com/storybooks/storybook/pull/4971#pullrequestreview-183710797 ?

We could merge this and add the use-case later? I'll leave it up to you to merge.

**Comment by igor-dv** [comment]
The tests were added so 👌

**Pull request merged**
