### PR TITLE
Viewport: Fix the `defaultOrientation` config option

### PR DESCRIPTION
**Pull request by jpzwarte**
So https://github.com/storybookjs/storybook/pull/21048 was actually broken. This fixes that (tested this time!).

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@shilman I think this is actually a good bugfix to merge into 7.0. WDYT?

**Comment by ndelangen** [comment]
@jpzwarte did you intend to delete the branch (which auto-closes PRs)?

**Comment by jpzwarte** [comment]
NO :(

**Comment by jpzwarte** [comment]
I removed my local fork, which caused this PR to be closed :( Was not my intention.

**Comment by valentinpalkovic** [comment]
@ndelangen Can we merge this one?

**Comment by ndelangen** [comment]
I can't update this @jpzwarte 
```
(next) % git remote add jpzwarte git@github.com:jpzwarte/storybook.git                                                                                                                                                                                                 ~/Projects/Storybook/core
git fetch jpzwarte fix/viewport-orientation
git switch --track jpzwarte/fix/viewport-orientation
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: invalid reference: jpzwarte/fix/viewport-orientation
```

**Comment by jpzwarte** [comment]
@ndelangen see the new PR: https://github.com/storybookjs/storybook/pull/21962

**Pull request closed without merging**
