### PR TITLE
Add missing dependencies to ui/react

### PR DESCRIPTION
**Pull request by zkochan**
Issue:

## What I did

I added missing dependencies to @storybook/react and @storybook/ui.

## How to test

Use storybook with [pnpm](http://github.com/pnpm/pnpm)

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by crhayes** [comment]
@zkochan Just ran into this issue, thanks for fixing!

**Comment by crhayes** [comment]
@shilman Is it possible to get a new release with this included?

**Comment by shilman** [comment]
@crhayes will release an alpha today

**Comment by crhayes** [comment]
Thanks! Is it possible to get it released on the 5.1.x release branch?

**Comment by shilman** [comment]
@crhayes Sure. Will release on alpha now and release a patch tomorrow.

**Comment by shilman** [comment]
@crhayes released as a patch instead. check 5.1.9.

**Comment by crhayes** [comment]
@shilman You're the man, thanks!

**Pull request merged**
