### PR TITLE
vue-jsx: update babel-preset-vue to @vue/cli-plugin-babel/preset

### PR DESCRIPTION
**Pull request by songlairui**
#dependencies

…@vue/cli-plugin-babel/preset`

Issue: [babel-plugin-jsx-event-modifiers](https://github.com/nickmessing/babel-plugin-jsx-event-modifiers) was DEPRECATED

UPDATE to https://github.com/vuejs/jsx instead 

## What I did

update the static preset code in `src`

## How to test

- Is this testable with Jest or Chromatic screenshots?
no
- Does this need a new example in the kitchen sink apps?
no
- Does this need an update to the documentation?
yes

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
cc @graup @Aaron-Pool

**Comment by graup** [comment]
Hi @songlairui, could you share a bit more about your thought process? I totally agree that `babel-preset-vue` has to go, we've had some discussion about it here: #4475

I tend towards just removing it, without adding `@vue/cli-plugin-babel/preset` – that preset is supposed to be only used with vue-cli projects, and those typically already have a babel config which we can just pick up without adding this preset in storybook.

**Comment by Aaron-Pool** [comment]
I agree with the above. I think we should probably just do `preset-env` and `vue/jsx`. If the user is using Vue cli and wants the corresponding Babel preset, then he should install the Vue cli plugin for storybook. Although, that probably warrants a mention in the docs.

**Comment by songlairui** [comment]
> Hi @songlairui, could you share a bit more about your thought process? I totally agree that `babel-preset-vue` has to go, we've had some discussion about it here: #4475
> 
> I tend towards just removing it, without adding `@vue/cli-plugin-babel/preset` – that preset is supposed to be only used with vue-cli projects, and those typically already have a babel config which we can just pick up without adding this preset in storybook.

agree with 'removing it'

I use vue/jsx in stories like this
```jsx
<SomeForm
  on={{
    'update:value': val => {
      this['update:value'](val)
      this.modelData = val
    }
  }}
/>
```
it doesn't behavior as expected as said in vue/jsx repo.

for the preset updated.

I create the config below:
```js
const path = require('path')

module.exports = {
  // ...
  babelDefault(config) {
    const presets = config.presets.filter(item => {
      let presetFile = item
      if (Array.isArray(item)) {
        presetFile = item[0]
      }
      return !presetFile.includes(path.join('node_modules', 'babel-preset-vue')) // 过滤掉 babel-preset-vue
    })
    presets.push(require.resolve('@vue/cli-plugin-babel/preset'))

    return {
      ...config,
      presets
    }
  }
  // ...
}
```
it works, but it is a hack way.
The `babel-preset-vue` was not used, but must be installed, and hacked. 

if the preset was removed, all things was able to be ok

**Comment by pksunkara** [comment]
I think @graup is already working on removing it from this preset.

**Pull request closed without merging**
