### PR TITLE
UI: Improve ScrollArea to use Radix

### PR DESCRIPTION
**Pull request by cdedreuille**
## What I did

In this PR we are improving the underlying `ScrollArea` component to move from `overlayscrollbars` to `@radix-ui/react-scroll-area`. The API is much easier to use, resulting in less code to maintain and it is up to the latest standards in term of accessibility.

This is using the exact same API as before and should have not impact on the UI as it is an absolute object position on top of everything.

#### The changes in this PR are covered in the following automated tests:
- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. To test it, please run Storybook UI locally
2. Scroll vertically on the sidebar
3. Alternatively, go to this story to test it out: http://localhost:6006/?path=/story/components-scrollarea--vertical

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

**Review by ndelangen — CHANGES_REQUESTED** [review]
I cannot see the scrollbars in dark-mode on this story:
Screenshot 2023-10-09 at 12 14 22

They are there, but not styled right.

The old styling did not use transparency AFAIK

**Comment by valentinpalkovic** [comment]
Tested light mode on both, desktop and IOS

**Comment by cdedreuille** [comment]
@ndelangen I'm using the same styles as the `next` version. `theme.textMutedColor` with opacity of 0.5. When you hover it goes to 0.6 opacity. But in this version I'm pushing it to 0.8 for better visibility.

**Comment by cdedreuille** [comment]
New PR here: https://github.com/storybookjs/storybook/pull/24412

**Pull request closed without merging**
