### PR TITLE
HTML: Dynamic source snippets

### PR DESCRIPTION
**Pull request by pzuraq**
Issue: #12755

Adds dynamic source to the HTML 'framework' package.

## What I did

Emits the rendered HTML if the HTML output was a string, otherwise does nothing. Output is also dedented by default. Mostly based on this PR: https://github.com/storybookjs/storybook/pull/15337

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [x] Does this need a new example in the kitchen sink apps? -
- [x] Does this need an update to the documentation?

### CODE REVIEW

**Comment by pzuraq** [comment]
One quick note, I couldn't seem to get this working locally in the kitchen sink examples. They just weren't showing code previews at all. Unsure if I did something wrong, could definitely use some pointers!

**Comment by shilman** [comment]
@pzuraq working great for me:

html-dynamic-snippets


what I did:

```sh
yarn bootstrap --core
cd examples/html-kitchen-sink
yarn storybook
```

**Comment by yannbf** [comment]
Hey @pzuraq this is an incredible contribution, thanks a lot for that! 🤩 

I've got a couple of remarks:

1 - Could you check and update the snapshots in `examples/html-kitchen-sink/tests/htmlshots.test.js` -> `Storyshots › Addons/Docs › standard source` ? They were affected and the test is failing.

2 - Your commit doesn't link to your github user. Seems like your `git config user.email` is not correct, and as a result this contribution won't be linked to you. Is this something you expected? Otherwise you can change the author with something like:
```
git commit --amend --author="Your Name <your@email.com>"
```

The issues in the E2E tests don't seem to be related to your changes.

**Review by shilman — APPROVED** [review]
Looking great @pzuraq -- love the tests 🚀

**Comment by pzuraq** [comment]
@shilman ah, I didn't realize I had to run bootstrap again before using the kitchen sink apps! Cool, works perfectly now 😄 

@yannbf thanks for pointing those out, I updated the snapshots, and the issue with the commit was my Git settings were off (changed companies recently, and started signing commits but forgot to upload my public PGP key 😱). Everything should be good to go now!

**Comment by kerryj89** [comment]
Freakin' amazing!  Thank you so much pzuraq!

**Comment by andrewgtibbetts** [comment]
Thank you @pzuraq!!! I upgraded to pre-release but I am still getting "No code available". Is there a setting to get this to work?

>// preview.js
>    
>        import "./styles.css";
>
>        var bgColor = window
>            .getComputedStyle(document.documentElement)
>            .getPropertyValue("--color-bg");
>        
>        export const parameters = {
>            layout: "centered",
>            backgrounds: {
>                values: [
>                    {
>                        name: "dark",
>                        value: bgColor,
>                    },
>                ],
>            },
>        };

>// Button.js
>        
>        import "./Button.css";
>        
>        export const Button = ({ use, size, label, onClick }) => {
>            const btn = document.createElement("button");
>            btn.tabIndex = 0;
>            btn.className = "btn";
>            if (use) {
>                btn.className = btn.className.concat(` btn-${use}`);
>            }
>            if (size) {
>                btn.className = btn.className.concat(` btn-${size}`);
>            }
>            btn.addEventListener("click", onClick);
>            btn.innerText = label;
>            return btn;
>        };

>// Button.stories.js
>        
>        import { Button } from "./Button.js";
>        
>        export default {
>            title: "Components/Buttons",
>            component: Button,
>            argTypes: {
>                use: {
>                    table: {
>                        disable: true,
>                    },
>                },
>                size: {
>                    control: {
>                        type: "inline-radio",
>                        options: ["small", "medium", "large"],
>                    },
>                    defaultValue: "medium",
>                },
>                label: {
>                    control: {
>                        type: "text",
>                    },
>                    defaultValue: "Button",
>                },
>                onClick: {
>                    action: "clicked!",
>                },
>            },
>            args: {
>                label: "Button",
>            },
>        };
>        
>        const Template = (args) => new Button(args);
>        
>        export const Primary = Template.bind({});
>        Primary.parameters = {
>            design: {
>                type: "figma",
>                url: "https://www.figma.com/file/[redacted]/Buttons?node-id=2%3A2",
>            },
>        };

**Comment by andrewgtibbetts** [comment]
If I change line 19 in `Button.stories.js` from
```
  return createButton({ label, ...args });
```
to 
```
 return createButton({ label, ...args }).outerHTML;
```
it works, since it returns a string instead of a DOM node / HTMLElement.
It doesn't seem to affect the rendering of the story, but might there be any consequences to doing this?

**Comment by maddesigns** [comment]
Awesome! 😍 Thanks @pzuraq! Is there a config to make it “prettier”?

**Pull request merged**
