### PR TITLE
Tech/overhaul ui: shortcuts

### PR DESCRIPTION
**Pull request by Jessica-Koch**
screen shot 2018-09-30 at 8 58 24 pm
Issue:
This is the layout for the keyboard shortcuts, I wanted feedback on the look before continuing, they cannot currently be configured. 

## What I did
* Added an additional route, `settings/shortcuts`
* Added another option within the menu to navigate to this page via shortcut or by clicking
## How to test

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps?
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by tmeasday** [comment]
This will be a very appreciated feature I think
cc @domyen

**Comment by ndelangen** [comment]
Looks excellent @Jessica-Koch !

**Comment by Jessica-Koch** [comment]
#3702 #3984

**Comment by igor-dv** [comment]
Looks cool
I see the `edit` icon (pencil, am I right ?), does it mean it will be editable online? If so, how it will be persisted to make it work with the static SB build?

**Comment by gabrielcsapo** [comment]
super cool!

**Comment by ndelangen** [comment]
@Jessica-Koch let's merge this into ui-overhaul, so we do not have 2 long running parallel branches with similar changes.

WDYT?

**Comment by Jessica-Koch** [comment]
@ndelangen that works

**Pull request merged**
