### PR TITLE
CHANGE jest addon

### PR DESCRIPTION
**Pull request by ndelangen**
merge in https://github.com/storybooks/storybook-addon-jest/pull/12

I will also archive the old addon-jest repo

### CODE REVIEW

**Comment by ndelangen** [comment]
We likely want to update the example in the monorepo to validate this feature works.

**Comment by ndelangen** [comment]
@DanYellow if you could possibly add a usage or test for this? Would love to get this one merged, hoping on your help.

**Comment by ndelangen** [comment]
I'll send you a collaborator invite, so you can push directly on this branch

**Comment by DanYellow** [comment]
Hi @ndelangen,

Sorry for the delay but what I have to do exactly ?

**Comment by ndelangen** [comment]
@DanYellow If you could verify if the changes in this PR are correct, they should fix the actual problem you had.

If you have an idea how we could test is, that'd be a great help too!

**Review by DanYellow — APPROVED** [review]

**Comment by pksunkara** [comment]
@ndelangen Can you rebase on master?

**Comment by pksunkara** [comment]
Do you need to change documentation?

**Review by pksunkara — APPROVED** [review]

**Pull request merged**
