### PR TITLE
Update webpack config example to include module sass files

### PR DESCRIPTION
**Pull request by nad182**
This will let users know how to change config to allow using both `.scss` and `.module.scss` files.

Issue:
Nowhere in the docs it explains how to configure webpack in `main.js` to allow users style their components with modular SASS (or modular CSS).

## What I did
Change example in the docs.

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by nad182** [comment]
As a note, I've only made one change in `docs/src/pages/configurations/custom-webpack-config/index.md`: [here](https://github.com/storybookjs/storybook/pull/11507/files#diff-fd01c9639458804da4748a75e729842bR186).
I submitted PR to `next` branch as was mentioned in the PR instructions.

**Comment by shilman** [comment]
@nad182 did you base your change on the `next` branch tho? it looks like you've changed `master` and submitted to `next`

**Comment by nad182** [comment]
I actually tried to submit it from the documentation page, but it wouldn't allow me to do it directly, saying I need to fork project and only then submit a PR. I wasn't planning on cloning the repo, thought I could just submit a PR via UI.

**Comment by nad182** [comment]
> @nad182 did you base your change on the `next` branch tho? it looks like you've changed `master` and submitted to `next`

I submitted a [new PR](https://github.com/storybookjs/storybook/pull/11549) with changes only to the referenced doc file. This one can be closed.

**Pull request closed without merging**
