### PR TITLE
Core: Enable gzip compression on the development server

### PR DESCRIPTION
**Pull request by kaelig**
Issue: #14280 

## What I did

This PR enables compression on assets served by the dev server. The compression level is low, which yields good compression results without slowing down the feedback loop between saving a file and changes appearing in the browser.

This is useful when a Storybook has large bundles.

## How to test

Make sure HMR works as expected. It should be okay, but in older versions of the compression package, it could sometimes be an issue.

Also ensure loading and reloading performance is within acceptable parameters.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Hi @kaelig, this looks great! However, it looks like there are some types missing which is causing the build to break:

```
@storybook/core-server: src/dev-server.ts(2,25): error TS7016: Could not find a declaration file for module 'compression'. '/tmp/storybook/node_modules/compression/index.js' implicitly has an 'any' type.
@storybook/core-server:   Try `npm install @types/compression` if it exists or add a new declaration (.d.ts) file containing `declare module 'compression';
```

Looks like it's on DefinitelyTypeed:

```
MMBP15:storybook shilman$ npm info @types/compression

@types/compression@1.7.0 | MIT | deps: 1 | versions: 20
TypeScript definitions for compression
```

**Comment by kaelig** [comment]
Thanks! My local tests consisted of modifying the compiled version in `node_modules`… I should have tested compilation and type checked properly!

**Comment by shilman** [comment]
FYI, we're in a merge freeze while the latest release is stabilizing. We'll resume merging PRs and publishing daily-ish alphas in a week or two.

**Review by shilman — APPROVED** [review]
Nice, simple fix. 💯

**Pull request merged**
