### PR TITLE
Add airbnb-js-shims to client-side JS

### PR DESCRIPTION
**Pull request by wyattdanger**
This adds [airbnb-js-shims](https://github.com/airbnb/js-shims) to the admin js and the iframe js, which gets IE11 working for me, where it used to break on an `Array.from`

### CODE REVIEW

**Comment by arunoda** [comment]
Isn't this something babel does automatically? I like to know which code breaks this? 
Babel load it from the [corejs package](https://github.com/kadirahq/react-storybook/blob/e6fc05d05c2adf7722045f42adfa645f03be0774/dist/client/client_api.js#L7).

Could you try updating core-js to the latest: `2.2.3` in your project and see whether it fixes this or not.

**Comment by ljharb** [comment]
Babel transpiles syntax, not API. Shims are still required, and these are more reliable ones (and actively shim fewer things) than babel-polyfill/core-js.

**Comment by arunoda** [comment]
@ljharb doen't add more overhead. I think we only need es6 shims in that case. 
So, it seems like babel's core-js usage has a problem. So we may should open an issue on core-js repo. 

In the meantime, let's add only es6-shim to the core.

**Comment by ljharb** [comment]
@arunoda es5-shim and es5-sham are still required for React to work in IE 8. No browser, even latest Chrome, complies with ES5, even.

**Comment by arunoda** [comment]
@ljharb I'm not sure whether we need to support browsers like IE8

> No browser, even latest Chrome, complies with ES5, even.
What do you mean by this?

CC / @mnmtanish

**Comment by ljharb** [comment]
@arunoda the cost is tiny, and the benefits range from zero to very high, depending on users' browser support matrix.

As for ES5, there does not exist any version of any JS engine that fully complies with ES5. The failures are minimal at this point, but they exist, and using the shims ensures they are papered over.

**Comment by arunoda** [comment]
@ljharb I think we can go with this.
I'll take this.

**Comment by wyattdanger** [comment]
Rebased, conflicts resolved

**Comment by arunoda** [comment]
Awesome.

**Pull request merged**
