### PR TITLE
Use react-dev-utils@next

### PR DESCRIPTION
**Pull request by pelotom**
Recently `create-react-app` [published a new version of `react-dev-utils` on the `next` tag](https://github.com/facebook/create-react-app/issues/3815#issuecomment-397922864), which I believe should obviate the need for the `@storybook/react-dev-utils` fork. This reverts #3312 and instead makes storybook depend on `react-dev-utils@next`.

### CODE REVIEW

**Comment by ndelangen** [comment]
@pelotom 
is the failing test related to the change?

```
#!/bin/bash -eo pipefail
yarn test --coverage --runInBand --reactnative
yarn coverage
yarn run v1.6.0
$ node ./scripts/test.js --coverage --runInBand --reactnative
 PASS  examples/react-native-vanilla/__tests__/index.android.js (8.317s)
 PASS  examples/react-native-vanilla/__tests__/index.ios.js
 FAIL  examples/react-native-vanilla/__tests__/storyshots.js
  ● Test suite failed to run

    TypeError: Cannot read property 'replace' of null
      
      at node_modules/hosted-git-info/index.js:61:63
          at Array.map (<anonymous>)
      at fromUrl (node_modules/hosted-git-info/index.js:45:39)
      at Function.Object.<anonymous>.module.exports.fromUrl (node_modules/hosted-git-info/index.js:32:18)
      at Object.<anonymous> (node_modules/normalize-package-data/lib/fixer.js:150:36)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/normalize-package-data/lib/fixer.js:144:31)
          at Array.forEach (<anonymous>)
      at Object.fixDependencies (node_modules/normalize-package-data/lib/fixer.js:137:41)
      at node_modules/normalize-package-data/lib/normalize.js:32:38
```

**Comment by pelotom** [comment]
@ndelangen I'm not really familiar with the dev workflow for this project... I ran

```
yarn test --core
```

and all tests pass, but when I try to run

```
yarn test --reactnative
```

I get

```
● Validation Error:

  Module <rootDir>/node_modules/react-native/jest/assetFileTransformer.js in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

error Command failed with exit code 1.
```

even though `<rootDir>/node_modules/react-native/jest/assetFileTransformer.js` exists... any idea what I'm doing wrong?

**Review by danielduan — CHANGES_REQUESTED** [review]
please use actual version number

**Review by ndelangen — APPROVED** [review]

**Review by ndelangen — APPROVED** [review]

**Review by danielduan — APPROVED** [review]

**Comment by ndelangen** [comment]
Thank you very much @pelotom!

**Pull request merged**
