### PR TITLE
Add small design update to addon info package

### PR DESCRIPTION
**Pull request by lucasmotta**
Issue:
When using the "info" addon inline, the current designs blends in too much with the component, making it quite confusing and sometimes difficult to preview.

screen shot 2017-06-07 at 16 45 13

## What I did
This change wraps the Story info into a "box" with a light border and shadow, also adds some more padding and margin to give a bit more room.

screen shot 2017-06-07 at 16 45 01

### CODE REVIEW

**Comment by ndelangen** [comment]
We've been discussing the info addon quite a bit lately, and most of us agree it's contents should not be in the preview at all. We should move it into a panel.

What's your take on this?

**Comment by lucasmotta** [comment]
@ndelangen after submitting this PR I've found those discussions about moving the info addon to its own panel, and it makes much more sense.

If it's something that's near from happening, then I wouldn't even bother merging it.

**Comment by ndelangen** [comment]
This is super easy to merge now and release as `3.0.2`. I'm OK with that actually.

Moving the contents into a panel will not be part of `3.0.2`.

I'd really like everyone's input on wether we can just simply move the content of addon-info into a panel and what strategy we should have:
1. Move it, and not provide alternatives (users can use an old version for as long as it stays compatible)
2. Move it and provide a setting so users can choose to render it in preview
3. Not move it, but provide a setting so it can be moved into a panel
4. Not move it, and write a new addon that renders in a panel (fork)

Obviously (1) is preferable in the long game, for us the maintainers. But what do users want?

**Comment by shilman** [comment]
@ndelangen @lucasmotta full discussion of the panel proposal is here: https://github.com/storybooks/storybook/issues/1147

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
