### PR TITLE
CLI: Mark qwik as using addon-interactions

### PR DESCRIPTION
**Pull request by literalpie**
## What I did

Add Qwik to the list of frameworks that supports interactive stories.

See [this PR](https://github.com/literalpie/storybook-framework-qwik/pull/47/files) in the storybook-framework-qwik project where I update the templates to match other frameworks. If I release that before this PR, the storybook addon-interactions dependency will be missing for people who use npm init with Qwik.

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by literalpie** [comment]
@shilman are you okay with merging this one first? I'd also be willing to release my package's update first too, it's just not my first choice. (either way shouldn't be a big deal as long as we're quick about it)

**Comment by shilman** [comment]
@literalpie sorry I missed your previous comment. Fine with me. Can you update your PR from `next` so that CI passes? Then I can merge this.

**Review by shilman — APPROVED** [review]

**Comment by shilman** [comment]
@literalpie Done! Do you need me to release?

**Comment by literalpie** [comment]
Sweet! Yes, if you can that would be good. I can start a release too

**Comment by shilman** [comment]
@literalpie here you go. i'll release it on `latest` in the next patch release https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.5

**Comment by literalpie** [comment]
Great! Thank you

**Pull request merged**
