### PR TITLE
Change ng stories dir

### PR DESCRIPTION
**Pull request by Quramy**
Issue:

See #2645 

## What I did
- Change generated `stories` directory location.

## How to test

Is this testable with jest or storyshots?

### CODE REVIEW

**Comment by igor-dv** [comment]
@Quramy, can you take a look why are the cli test failing ? Looks like something is misconfigured with tsconfig.

**Comment by Quramy** [comment]
@igor-dv. As you said, this error is caused by `src/tsconfig.json`(I think `src/tsconfig.json` fails to configure `typeRoots` 🤔 ).

And the latest `@angualr/cli` generates not `src/tsconfig.json` but `src/tsconfig.app.json`, and using the latest generated tsconfig solves this error. So I'll update the fixture.

**Review by igor-dv — APPROVED** [review]
LGTM. 
@Hypnosphi any insights?

**Comment by Hypnosphi** [comment]
>  So I'll update the fixture.

Does it mean that this change will breake people's apps bootstrapped with previous versions of `@angular/cli`

**Comment by Quramy** [comment]
@Hypnosphi 

> Does it mean that this change will break people's apps that were initially bootstrapped with previous versions of @angular/cli?

The `@angular/cli` change related it is https://github.com/angular/angular-cli/pull/4924, and this PR merged on Feb 23, 2017 and is before `@angular/cli` v1.0.0. So I think we don't have to worry. How about it ?

**Comment by igor-dv** [comment]
So is it good to go?

**Comment by alterx** [comment]
I think we're good to go if the change was made pre v1 and we support v1+

Have we tested this?

**Comment by Hypnosphi** [comment]
I'll change the base branch for a moment, just to check if it fixes issues with #2712

**Pull request merged**
