### PR TITLE
Build: Avoid remapping exports in package.json

### PR DESCRIPTION
**Pull request by IanVS**
Issue: N/A

We had some challenges with tooling like eslint and typescript when the exports map in package.json changes the import for non-top-level exports.  For example, remapping from `@storybook/addon-actions/decorator` to the actual file in `/dist/decorator`.  This was causing errors in https://github.com/storybookjs/storybook/pull/19689, for example.

## What I did

As discussed with @ndelangen, I added `/dist` to the exports map, so that the import actually points to a real file that exists.  This causes eslint and typescript to be happier, and will improve compatibility with runtimes that do not support `exports`, though our minimum node.js version does support it (14+ does).  

Note: I did not change the addon exports for `register`, since those point to differently-named files anyway, so it seemed safer to just leave those how they were.

This change may be disruptive for community projects importing from non-top-level modules.  But, I don't see an existing migration note about the addition of `exports` in package.json limiting what can be imported.  So, maybe a note isn't needed?  Or, maybe we need a larger note that covers both?  Not sure how to proceed there.

Finally, I also simplified some exports of `package.json`, just to keep the noise down in the files.

## How to test

- CI should give a good indication that this is working correctly.

### CODE REVIEW

**Comment by IanVS** [comment]
@ndelangen @tmeasday Do either of you know what I need to do to handle this error now?

>Failed to load preset: "@storybook/react-vite/preset"

I tried adjusting presets.ts, but I guess I didn't do it correctly.

**Comment by ndelangen** [comment]
yeah the presets should be at the root.

**Comment by tmeasday** [comment]
I'm not sure I'm understanding the root problem here with the tooling, but all the `preview` etc entries are imported by this code: https://github.com/storybookjs/storybook/blob/5eaf7d89ed4c99ed0b9bd2c18205a3c9192905d3/code/lib/core-common/src/presets.ts#L109-L112

So I would expect that would need to be adjusted at the very least.

**Comment by IanVS** [comment]
Thanks, I forgot this was open, I think I e got a better solution brewing in a different PR, so I'll close this one out.

**Pull request closed without merging**
