### PR TITLE
Remove Stories and Addon panels when invisible

### PR DESCRIPTION
**Pull request by theKashey**
Issue: #4144

## What I did

I was trying to speedup Stories pannel rendering, but it's not so easy, as long problem lays inside `@ndelangen/react-treebeard`.
For now I am doing the simplest thing possible - not rendering Stories and Addon pannel when they are not visible. This will make tools like screenshot generation much faster.

## How to test

There are no visual or behavior changes.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Code looks fine to me, can you update the tests?

**Comment by theKashey** [comment]
Ah, sorry. Forgot to run the tests. My bad.
The root cause is hidden inside storybook/lib/ui/src/modules/ui/components/stories_panel/stories_tree/index.js : mapStoriesHierarchy - for every render it produces a "deeply" new object, bypassing all possible optimizations.

As I could see this file does not exists in your PR, and also there is no logic around generation some complex object for `Treeview.js`, so look like you already handled this.

**Comment by ndelangen** [comment]
Indeed my refactor has completely changed the way stories are stored and retrieved.

It should be much faster, though I have not benchmarked it, It definitely feels faster.

**Comment by theKashey** [comment]
> Error: Couldn't find package "remap-istanbul@^0.6.4" required by "karma-remap-istanbul@^0.2.1" on the "npm" registry.

🙀🤔

**Comment by ndelangen** [comment]
I think removing the addons panels shouldn't be done, their state will be lost, and they'll never be able to re-acquire some stories data.

Storysource breaks for example. 🤔 

The nav can be removed I think, it's state is managed by the manager store. Though I do not know if removing the component will bring big performance gains, as the calculations will probably still happen in the store.

**Comment by theKashey** [comment]
Let's wait for your PR - if it will solve performance issues - then ok. If no - then lets return to more radical solutions, like removing panels :)
Closing this for now, and wishing you luck with a state management.

**Comment by ndelangen** [comment]
Haha thanks @theKashey, it's going well actually!

Thank you for your time and energy, I'm hoping you'll find something else in storybook you want to fix/change! 🙇

**Pull request closed without merging**
