### PR TITLE
Addon-jest: Title case panel name

### PR DESCRIPTION
**Pull request by clayrisser**
Issue: #10160 

## What I did

Rename jest addon panel name to use title case

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM! Thanks!

**Comment by shilman** [comment]
@tmeasday @ndelangen we're still getting the chromatic build error. any idea what's going on?

**Comment by tmeasday** [comment]
@shilman is this the problem that @ndelangen is fixing in the generated entries PR

**Comment by ndelangen** [comment]
yes

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
Nice one @ndelangen !!!

**Pull request merged**
