### PR TITLE
Added flow support to getstorybook upgrade

### PR DESCRIPTION
**Pull request by AugustinLF**
This does work for me on a large flow typed codebase. I'm not sure if there's a cleaner way to pass the options to the generator, if you have any suggestion, don't hesitate, I'll update the PR!

### CODE REVIEW

**Comment by shilman** [comment]
@AugustinLF awesome -- great addition!! can you provide a simple example project to go along with it?

**Review by ndelangen — APPROVED** [review]

**Comment by AugustinLF** [comment]
Here is an [example](https://github.com/AugustinLF/example-getstorybook-flow). ` getstorybook` throws an error with the latest published version, while running fine when using my version with `getstorybook --parser flow`.

Do you want me to rebase my branch on master?

**Comment by shilman** [comment]
I'll review in the next few hrs and will ask if I need anything 🙇

**Review by shilman — APPROVED** [review]
Awesome!! 🚀 🌔

**Pull request merged**
