### PR TITLE
Angular: Support angular components without selector

### PR DESCRIPTION
**Pull request by ThibaudAV**
Issue: https://github.com/storybookjs/storybook/issues/13769

## What I did

Allows Storybook to handle components without a selector. 

This is a simple solution that uses the `*ngComponentOutlet` directive from angular. 

I have impression that there are several "more or less" advanced ways for angular to use these components. And these solutions depend, I think, on the context in which these components are used. 

This solution is therefore not perfect for all uses case of these components but aims to support single components

On these components it is not possible to modify their internal properties with props. It will be necessary to use the same mechanism as in an Angular app. For example with a provider. 

For more complex components I think it's better to make a "parent component" for each use case. In order to reproduce the final use case in the angular application of these components. 
(I've added a story example with an implementation of a "parent component")

## How to test

- Is this testable with Jest or Chromatic screenshots? yes
- Does this need a new example in the kitchen sink apps? yes
- Does this need an update to the documentation? no i think

### CODE REVIEW

**Comment by literalpie** [comment]
Yes, this looks like it would be a big improvement over the current behavior. Of course it would be better if the props worked on components without selectors, but I understand why that would be hard to support.

Thanks for helping with this issue, and all of the other improvements you've been making to storybook Angular support!

**Comment by ThibaudAV** [comment]
@literalpie to take into account your last return. I added a last example that allows to override properties of a component with a custom wrapper and `props` ;)

**Review by shilman — COMMENTED** [review]
LGTM!

**Comment by literalpie** [comment]
@shilman One thing to note about this approach is that it requires adding the component without selectors to `entryComponents` (which wasn't necessary in the past). Sorry it took so long for me to bring this up, and I don't really expect you to fix it (it's kind of weird that dynamically adding components _ever_ worked without `entryComponents` since this is all pre-ivy). I'm mostly letting you know because I think it would be good to mention in some kind of 6.2 upgrade documentation.

**Comment by shilman** [comment]
@literalpie thanks so much for the clarification. do you mind mind making a small PR to MIGRATION.md?

**Comment by ThibaudAV** [comment]
I hope that with ivy we will not need to add them anymore in `entryComponents`

**Comment by literalpie** [comment]
Done! #14228

**Pull request merged**
