### PR TITLE
write doc about .css/.scss rules for Angular

### PR DESCRIPTION
**Pull request by Quramy**
Issue: #2629 

## What I did

- write `apps/angular` docs about .css/.scss webpack rules.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Thank you @Quramy, this will really help our Angular users 👏

**Comment by Quramy** [comment]
@ndelangen thanks for review and merge 😄 

Visiting https://storybook.js.org/basics/slow-start-guide/, it seems that `guide-angular` is not deployed 🤔  Would you confirm it ?

**Comment by ndelangen** [comment]
Will deploy now

**Comment by ndelangen** [comment]
https://storybook.js.org/basics/guide-angular/

**Pull request merged**
