### PR TITLE
Chore: (Docs) Renames the vue snippets file names

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pull request the vue snippets file names were updated for clarity:

What was done:
- Snippets for Vue 2 and Vue 3 were renamed from `*.vue2.js.mdx` and `*.vue3.js.mdx` to `*.2.js.mdx`and `*.3.js.mdx`.
   Which yelds the following when the reader sees the docs/snippets for Vue
  vue2_vue_3_new_format

- Snippet references were updated per renaming of the files.

Feel free to provide feedback

### CODE REVIEW

**Review by phated — APPROVED** [review]
LGTM! 👍

**Review by domyen — APPROVED** [review]

**Comment by domyen** [comment]
lgtm! But why are the Chromatic tests triggering here?

**Comment by jonniebigodes** [comment]
Regarding Chromatic tests it could be related to the CI configuration we currently have. Probably @shilman or @tmeasday could answer that question better.

**Comment by domyen** [comment]
OK merge it. It appears like these changes are also on `next` which means a previous PR was merged before the baselines were approved.

**Comment by jonniebigodes** [comment]
Self merging this

**Comment by shilman** [comment]
@domyen @jonniebigodes still cleaning up a bad merge from earlier this week 🙈

**Pull request merged**
