### PR TITLE
Improve the decorator for vue

### PR DESCRIPTION
**Pull request by kazupon**
Issue: #1529

## What I did
Improve the decorator for Vue app storybook

## How to test
- npm i
- npm run bootstrap
- cd app/vue
- npm link
- cd ../../examples/vue-kitchen-sink
- npm link
- npm run storybook

### CODE REVIEW

**Comment by ndelangen** [comment]
Hey @kazupon you should be able to make branches on this repo and push to them, right?
I find reviewing forks a bit more involved from reviewing branches. FYI.

**Review by ndelangen — APPROVED** [review]
Thanks for this!

Tested locally ✅

**Comment by ndelangen** [comment]
We will possibly revisit the decorator concept with `4.0.0`, but for now I think this will help starting vue-users.

**Comment by ndelangen** [comment]
Can you fix the unit tests? it's probably just a matter of updating the snapshots

**Comment by kazupon** [comment]
fixed unit tests.

@ndelangen 
Should I support `centered` official decorator for Vue?
https://github.com/storybooks/storybook/tree/master/addons/centered

**Comment by ndelangen** [comment]
Well in the end, I want decorators to be framework independent.

Do you see any way of making this happen for `addon-centered`?

Even if not, I think Vue users will want the same thing, So I'd accept a PR for that.

**Comment by kazupon** [comment]
okay, 
I seem the it can be support `addon-centered` for both `react` and `due`.
I'll try to it. 💪

**Comment by kazupon** [comment]
done!

**Comment by ndelangen** [comment]
I fixed a merge-conflict in the package.json dependencies.

**Comment by kazupon** [comment]
Thanks!

**Pull request merged**
