### PR TITLE
API: Add method to set config for manager

### PR DESCRIPTION
**Pull request by ndelangen**
Issue:
Setting theme via parameters is really bad for performance
This is true for other config too.

## What I did
ADD a setConfig option on lib/addons, to pass data/config into the manager directly VS via parameters

This PR adds a API:

```js
import { addons } from '@storybook/addons';
import { themes } from '@storybook/theming';

addons.setConfig({
  theme: themes.dark,
});
```

You set this within `addons.js`.

## How to test
I've changed the dev-kits example to dark theme.

There's no flash of light theme anymore.

### CODE REVIEW

**Comment by ndelangen** [comment]
I implemented the setting of `theme`, but all other configs will still have to be implemented.

Looking forward to hearing your feedback @shilman

**Comment by shilman** [comment]
@ndelangen Super interesting, and raises lots of questions:
- Are these settings also available in the preview? (And vice versa)
- Which settings should be set this way vs. the old way?
- Do we want to rename `addons.js` to `manager.js`?
- What's the migration path for users?
- Is this a breaking change?

**Comment by ndelangen** [comment]
> Are these settings also available in the preview? (And vice versa)
No, parameters are shared meta-data on stories, those are shared

> Which settings should be set this way vs. the old way?
If the data is for the manager only, parameters only make sense if the data is related/attached to a story

> Do we want to rename addons.js to manager.js?
Would probably be a good change to make, that would be a breaking change though

> What's the migration path for users?
We'd need to change the documentation & our examples.
I don't think a codemod is viable. So much stuff can go down in `config.js`...
We can however add a deprecation and a warning how to change config.js to remove the custom theme, and how to add it to `addons.js`.

Is this a breaking change?
> No, not as it is right now.

**Comment by shilman** [comment]
I understand it & it's a pretty cool change! Not exactly sure what's the best way to communicate it to users, but it's a big perf win.

**Comment by ndelangen** [comment]
Addresses:
https://github.com/storybookjs/storybook/issues/8188

**Comment by ndelangen** [comment]
It would be nice to get some stricter types on this.

**Pull request merged**
