### PR TITLE
Patch 6.2 ie11 fixes

### PR DESCRIPTION
**Pull request by shilman**
Issue: #13692

## What I did

Copied the changes from 6.2 NOT including the corejs removal fixes

## How to test

- [ ] Let's see what CI says
- [ ] @thomasoreilly can you test the branch manually?

### CODE REVIEW

**Review by tooppaaa — APPROVED** [review]

**Comment by thomasoreilly** [comment]
@shilman, I'm still seeing the error on my end. That's running with the commands you commented with in the issue. 

image

**Comment by shilman** [comment]
Is that the same error you're seeing in 6.1? @tooppaaa Any ideas?

**Comment by thomasoreilly** [comment]
Yes. The angular dependencies aren't transpiled. 

I listed two errors when I created the issue first, the `Const must be initialized` error was due to the target in the tsconfig configured as es2015, when configured to es5 that error is resolved. The syntax error is still there.

**Comment by shilman** [comment]
@thomasoreilly Can you point me at the change you think solved it?

**Comment by thomasoreilly** [comment]
@shilman, I'm not sure. I was investigating how to fix it on my end when I built and installed the latest alpha for my test app and it just worked.

I did notice updating the `nodeModulesThatNeedToBeParsedBecauseTheyExposeES6` list with `node_modules/@angular` seem to fixed the transpiling for Angular deps, however, there are other deps experiencing the same problem such as `@ngrx`. 

 I'll review the changes and see if I can spot the change that fixes it.

**Review by ndelangen — APPROVED** [review]

**Comment by timbomckay** [comment]
I just updated to the recent beta release and am still getting the vendors-main.js syntax error in IE. This is only when we have `docs` enabled, for us. Not sure what the status is on this merge issue but would really love for this to be resolved by the time it's officially released.

**Pull request closed without merging**
