### PR TITLE
7161 Fix error raw loader module not found in angular 8

### PR DESCRIPTION
**Pull request by baraalex**
Issue: #7161

## What I did

Fix error webpack not finding `raw-loader` on angular build.

Webpack documentation on how to use [webpack loaders](https://webpack.js.org/concepts/loaders/#configuration)

### CODE REVIEW

**Review by kroeder — APPROVED** [review]
Seems reasonable, the docs describe to use loader like that and all tests have passed.
LGTM

I'm not sure why this 
1) has worked before
2) does fix the original issue. I could create an ng8 app without having trouble with raw-loader
@baraalex could you explain this if possible, please?

@shilman any doubts merging this?

**Comment by shilman** [comment]
@kroeder I don't really understand the change. @ndelangen can you take a look?

**Comment by ndelangen** [comment]
```
loader: require.resolve('ts-loader')
```

will enforce to resolve the `ts-loader` from the current file (`/node_modules/@storybook/angular/..`)

```
loader: 'ts-loader'
```

will have let webpack figure it out, I think that might resolve it from where the file is required.

---

In either case, at least one `raw-loader` should be at `/node_modules/raw-loader`. I don't understand why `raw-loader` would ever not be found.

---

> Fix error webpack not finding raw-loader on angular build.

Do you mean a build of the angular app or building a static version of storybook for angular?

**Comment by baraalex** [comment]
> In either case, at least one raw-loader should be at /node_modules/raw-loader. I don't understand why raw-loader would ever not be found.

I don't know why but I have an app on angular and when I updated it to angular 8, with the angular client, it stopped to work and it was because raw-loader couldn't be found.

> Do you mean a build of the angular app or building a static version of storybook for angular?

Both building a static version and running storybook live version were failing because of this problem.
I looked into webpack documentation and the recommendation is to use the `loader: 'ts-loader'`  expression as I linked on the description of the PR and it seems to solve all the issues with this error

**Pull request merged**
