### PR TITLE
[Addon: Knobs] - Performance Fix: added debouncing between keystrokes to speed up component rendering

### PR DESCRIPTION
**Pull request by CodeByAlex**
Issue: #5376 

## What I did
I added debouncing logic with lodash within the knob changed function to reduce the number of times a component is rendered when the user is typing. The knob changed functionality will only be called if there is a delay of 150ms(slightly faster than the average time between keypress) during user typing. The previous version re-rendered the component upon each keypress. This will help increase performance and is seen mostly when running large components within storybook.

For more information about this PR, please refer to #5376

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM?

**Comment by shilman** [comment]
cc @ndelangen @tmeasday

**Comment by tmeasday** [comment]
This seems good, although I wonder if we should use debounce from lodash instead of the handrolled `setTimeout` method?

**Comment by CodeByAlex** [comment]
Good idea @tmeasday . I agree since Lodash is tried and true and is already being used in the project where debouncing occurs. I've pushed to the branch and updated the PR. Mind taking another look?

**Review by tmeasday — APPROVED** [review]
LGTM!

**Pull request merged**
