### PR TITLE
Fix react bootstrap template for eslint rule - jsx-a11y/accessible-emoji eslint 

### PR DESCRIPTION
**Pull request by shobhitchittora**
Closes: #2736 
Fixes eslint errors with template.

---
This change is [Reviewable](https://reviewable.io/reviews/storybooks/storybook/2737)

### CODE REVIEW

**Review by Hypnosphi — CHANGES_REQUESTED** [review]
Cool, thanks. But this is just a snapshot for tests, actual templates live here: https://github.com/storybooks/storybook/tree/master/lib/cli/generators

Please check other generators as well, some of them may have the same story

**Comment by Hypnosphi** [comment]
Maybe you could just add `a11y/accessible-emoji` to our root `.eslintrc.js`, and fix all the errors that would apper?

Here's contributing guide for developer setup: https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md

**Comment by shobhitchittora** [comment]
@Hypnosphi Thanks for pointing that out. I'll try to add the rule in eslint.

**Comment by shobhitchittora** [comment]
@Hypnosphi  I tried adding the rule to the root `eslint.js` of the generators folder and found the following violations - 

```
/Users/gaurav/Desktop/stuff/storybook/lib/cli/generators/METEOR/template/stories/index.stories.js
  13:33  error  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji

/Users/gaurav/Desktop/stuff/storybook/lib/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index.js
  23:7  error  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji

/Users/gaurav/Desktop/stuff/storybook/lib/cli/generators/REACT_NATIVE/template/storybook/stories/index.js
  23:7  error  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji

/Users/gaurav/Desktop/stuff/storybook/lib/cli/generators/REACT_SCRIPTS/template/src/stories/index.js
  13:33  error  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji

/Users/gaurav/Desktop/stuff/storybook/lib/cli/generators/REACT/template/stories/index.stories.js
  13:33  error  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji

/Users/gaurav/Desktop/stuff/storybook/lib/cli/generators/WEBPACK_REACT/template/stories/index.stories.js
  13:33  error  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji

  ```

Fixing them in this PR.

**Comment by Hypnosphi** [comment]
> root eslint.js of the generators folder

Actually you can add it in project root, because there might be violations in examples as well

**Comment by ndelangen** [comment]
Snapshots don't match. Inspect your code changes or run 'yarn test --cli --update' to update them

**Comment by Hypnosphi** [comment]
@ndelangen that's because currently the only change is in snapshot itself, see comments above

**Comment by Hypnosphi** [comment]
Superseded by #3011

**Pull request closed without merging**
