### PR TITLE
Move builds to core

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: #2636

## What I did

1. Moved index.js to core
2. Moved build.js to core
3. Fixed polymer leftovers - (UglifyJsPlugin and getConfigDir)
4. Moved WatchMissingNodeModulesPlugin to core

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by Hypnosphi** [comment]
`WatchMissingNodeModulesPlugin` is actually a part of `react-dev-utils` package which we already depend on, in all apps (I guess, `react` is in the package name only because it's a part of `create-react-app` project. Let's import it from there instead of replicating on our side

**Comment by igor-dv** [comment]
Makes sense to me

**Comment by Hypnosphi** [comment]
Ok, I'll make a PR

**Comment by Hypnosphi** [comment]
https://github.com/storybooks/storybook/pull/3141

**Pull request merged**
