### PR TITLE
Chore: (Docs) updates testing examples

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pull request, the documentation is updated to address and close both #19572 and #19703.

What was done:
- Updated the documentation/snippets for supported frameworks for the usage of `canvasElement` throughout docs.
- Updated the links to point to the right documentation place.
- Removed the `step` function temporarily from the documentation as based on testing with the latest stable version, it's not working.
- Updated the documentation for usage of Vue TS throughout the docs as it's already documented.

A follow-up pull request porting the changes over to CSF 3 will be up after this is merged.
@shilman I've assigned this directly to you so that you could take a pass at this and pick it to allow it to be available to the current docs.

Let me know of any feedback. Thanks in advance.

### CODE REVIEW

**Comment by shilman** [comment]
@jonniebigodes Let's discuss this one. It looks like you're updating 7.0 examples back to 6.5 Template style? Is that because we're going to redo all of this in 7.0 anyway?

Would it be more appropriate to do a PR directly against `main` in this case?

**Comment by jonniebigodes** [comment]
@shilman yes, I'm already in the process of updating the examples per #19665.

**Comment by shilman** [comment]
@jonniebigodes so it's ok to merge this into `next` even if it reverts the examples back to 6.5 style?

**Comment by jonniebigodes** [comment]
We can merge now and pick it to be released, and I'll continue working on the examples, and once the pr is up, I'll leave the documentation label.

**Comment by shilman** [comment]
@jonniebigodes OK, i'm just worried there will be tons of merge conflicts when we bring it back to 6.5. It touches a ton of files.

**Comment by jonniebigodes** [comment]
@shilman if that's the case, feel free to close this one, and I'll create a branch of the main and base it on that and adjust accordingly and submit the pull request aimed at main. Sounds good?

**Comment by shilman** [comment]
Yes, or perhaps you can just try targeting this one into `main` and resolving the conflicts there if it's easier

**Comment by jonniebigodes** [comment]
I have already a backup of this so no worries there.

**Comment by shilman** [comment]
Ok, your call! Thanks & looking forward to the new PR 🙏

**Pull request closed without merging**
