### PR TITLE
Removed port to reduce confusion.

### PR DESCRIPTION
**Pull request by Gongreg**

### CODE REVIEW

**Review by shilman — APPROVED** [review]
@Gongreg LGTM. Can you add a note about the default port and what's going on there?

**Comment by Gongreg** [comment]
@shilman, what exactly do you mean?

**Comment by shilman** [comment]
@Gongreg something along the lines of:

> By default react-native-server will run on port 7007, which is what is expected by the react-native app.

**Comment by Gongreg** [comment]
@shilman, done

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
