### PR TITLE
Perf Testing for ESM Builds

### PR DESCRIPTION
**Pull request by hipstersmoothie**
Incrementally applying #12406 to measure perf changes

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@shilman I kinda gettting to my wits end on this one. I'm not sure where the startup time gets slower and I can't get certain parts of the build to pass :(

**Comment by hipstersmoothie** [comment]
Also just a little feedback on the `next` branch dev experience: It would be SUCH a time saver if the git sha and alpha versions weren't committed at all. I've spent SO much time resolving useless merge conflicts

**Comment by shilman** [comment]
@hipstersmoothie You're doing a lot of heavy lifting here, so apologies for any "accidental complexity" in the contribution process. I can remove the git hash commits pretty easily. I'm less sure about the version increments.

I'll see what we can do to fix the build first. I'll also try to take a look at the startup numbers, although that might take some time--I'm taking some time off right now.

**Comment by gaetanmaisse** [comment]
I will try to help and take a look to the failing e2e tests in the next few days 😉

**Comment by hipstersmoothie** [comment]
@gaetanmaisse Thank you! I was literally just about to message you about #12499. It is only upgrading babel+typescript and exhibits the same issue. I'll give you push access to my fork <3

**Comment by gaetanmaisse** [comment]
@ndelangen is there still something to do here? I would think everything has been applied with other PRs 🤔

**Comment by shilman** [comment]
I'm closing this. There are still aspects of this work that we might apply on top of the other work, but we can always dig it up when we get to it. @hipstersmoothie thank you for paving the way here!!!

**Pull request closed without merging**
