### PR TITLE
Tree view visual adjustments

### PR DESCRIPTION
**Pull request by Hypnosphi**
See discussion in #1523

This PR consists of several changes, which can be applied quite independently. I'll describe each of them in a separate comment, so that you can vote with emoji reactions.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Some minor indentation was added to stories to highlight the hierarchy

Before
screen shot 2017-08-05 at 03 51 02

After
screen shot 2017-08-05 at 03 37 34

**Comment by Hypnosphi** [comment]
Link color from [Welcome story](https://github.com/storybooks/storybook/blob/4752119868afabd78d6f84e95d125da8814211b0/app/react/src/demo/Welcome.js#L29) was used to indicate that story menu items are proper links

Before
screen shot 2017-08-05 at 03 43 49

After
screen shot 2017-08-05 at 03 20 01

**Comment by Hypnosphi** [comment]
As an alternative to the previous one, I can suggest slight underlines
screen shot 2017-08-05 at 03 29 12

**Comment by Hypnosphi** [comment]
Line heights for items were made lower than the items mininal height, so that it's easy to distinguish an item with wrapped lines from two consecutive items. Story's minimal height was lowered proportionally to the font size.

Before
screen shot 2017-08-05 at 03 45 50

After
screen shot 2017-08-05 at 03 34 45

**Comment by Hypnosphi** [comment]
The items' text is vertically aligned by lowercase letters, so that ascenders and descenders have both enough space

Before
screen shot 2017-08-05 at 03 49 42
screen shot 2017-08-05 at 03 48 59

After
screen shot 2017-08-05 at 03 36 51
screen shot 2017-08-05 at 03 36 19

**Comment by Hypnosphi** [comment]
Finally, the chevron's alignment and rotation centre were adjusted

<details><summary>Before</summary>
  </details>

<details><summary>After</summary>
  </details>

**Comment by TrevorEyre** [comment]
The blue/underlined links both seem a little too intense to me. I think sidebar navigation is a common enough UI pattern that making the links stand out that much is unnecessary. If anything, maybe a slightly lighter font color for story links? Or perhaps kinds could be bold, and story links normal weight?

Something more along the lines of this, perhaps?

sidebar nav

**Comment by Hypnosphi** [comment]
screen shot 2017-08-05 at 06 51 19

**Comment by shilman** [comment]
@igor-dv did you mean to close this?

**Comment by TrevorEyre** [comment]
Yeah, the dark grey story links looks much better IMO.

**Comment by Hypnosphi** [comment]
Just for the record, the current branch state contains all the upvoted changes, without the downvoted ones =)

**Review by danielduan — APPROVED** [review]
Changing the look and feel of something existing is always gonna be controversial. I'm pretty comfortable with the changes here, think this would add clarity.

**Review by ndelangen — APPROVED** [review]
Looks good: ✅
Locally tested: ❌

**Comment by ndelangen** [comment]
Anyone opposed to merging this? ( @shilman  )

**Review by igor-dv — APPROVED** [review]
LGTM

**Review by shilman — APPROVED** [review]
🎉

**Pull request merged**
