### PR TITLE
Addon-a11y: Add preset

### PR DESCRIPTION
**Pull request by dave-cross**
Issue: #9471 

## What I did

Add preset files based on addon-knobs. Also updated the readme, but it seems to have auto-formatted in interesting ways.

## How to test

- `yarn test --core`
- Test in examples/official-storybook by removing parameters from a11y stories.

### CODE REVIEW

**Comment by CodeByAlex** [comment]
Thanks for the quick turnaround! Could you try adding it to a demo app to ensure it works properly? It might be worth converting all of the demos to use the new format so that we are encouraging others to do so. @shilman any thoughts?

**Comment by cloudsociety** [comment]
@CodeByAlex 

A pre-existing one like examples/official-storybook? Something else? I can definitely do that (already made changes to official-storybook, but didn't want to commit that in case it's bad practice).

**Comment by shilman** [comment]
Thanks @cloudsociety, this is awesome!!!

Like @codebyalex said, please add it to all the examples (like official-storybook) as needed. I think what this means is just removing the manual decorator adding and confirm that it can also be disabled easily for some examples.

Also, please add it to MIGRATION.md because it’s actually a breaking change (which is fine—we’re in 6.0 now!!)

**Comment by cloudsociety** [comment]
Hopefully got them all. Everything seems to be working. Not sure where to add it in MIGRATION.md. Not really a breaking change. Just added functionality.

But more than happy to update that file with a little guidance.

**Review by ndelangen — APPROVED** [review]

**Review by shilman — APPROVED** [review]
Added the migration info. Thanks @cloudsociety !!!

**Comment by ndelangen** [comment]
Thank you @cloudsociety!

**Pull request merged**
