### PR TITLE
Replace Emotion theme context with a custom context implementation

### PR DESCRIPTION
**Pull request by fabian-hiller**
Issue: https://github.com/storybookjs/storybook/issues/10231#issue-589122617

## What I did
I have added a custom context to the storybook theming package and replaced the previous emotion apis or rewritten it to use the new context.

## How to test
I have started a storybook from the examples directory to check if there are errors in the console. I am open for further tests.

- Is this testable with Jest or Chromatic screenshots? - No
- Does this need a new example in the kitchen sink apps? - No
- Does this need an update to the documentation? - No

## Notes
Please have a look at my code and add improvements if necessary.

## Credits
- Thanks to @ndelangen for the introduction to Storybook
- Thanks to @connor-baer for the helpful code example

### CODE REVIEW

**Comment by ndelangen** [comment]
Thanks for taking this on @fabian-hiller this is not an easy task. 🙏

**Comment by ndelangen** [comment]
I've fixed a few TS typings, but I there are more. Perhaps you could investigate if you could improve the typings of styled somehow?

**Comment by ndelangen** [comment]
Actually it's currently `withTheme` that seems to have incorrect typings.

**Comment by fabian-hiller** [comment]
> I've fixed a few TS typings, but I there are more. Perhaps you could investigate if you could improve the typings of styled somehow?

I don't have too much experience with TypeScript yet, so I think it's better if someone else does it.

**Comment by connor-baer** [comment]
I've love to see this merged in Storybook 6. 

@mrmckeb + @ndelangen, I see that you tried to fix the types but based on the test failures I can't tell if you succeeded. Is there anything left to do, something I could help with?

**Comment by javialon26** [comment]
any news on this?

**Comment by connor-baer** [comment]
Now that Storybook 6 is out, is this something that can be tackled in a minor release? Or do we need to wait until v7?

**Pull request closed without merging**
