### PR TITLE
Tech: migrate to es version of `lodash`

### PR DESCRIPTION
**Pull request by ndelangen**
migrating to es version of lodash (manager)

### CODE REVIEW

**Comment by ndelangen** [comment]
that seems important, but not really super related to this PR? @valentinpalkovic

**Comment by valentinpalkovic** [comment]
I would say it is important, in a sense, that we potentially increase the bundle size of the manager quite a lot. But if we do not care that much about it, I would agree with you, that my comment is unrelated to this PR.

**Comment by valentinpalkovic** [comment]
So maybe we should first make sure that tsup tree-shakes properly (maybe it already does) and then switch out lodash and other packages by their es counterparts and adjust the imports.

**Comment by IanVS** [comment]
I agree with @valentinpalkovic.  I think we've been working hard to bring down the installation size of storybook, so blowing it up with all of lodash would be a step backwards, if it's not tree-shaking properly.

**Comment by ndelangen** [comment]
Ok, I'll investigate

**Pull request closed without merging**
