### PR TITLE
Addon-docs: Fix type aliases and enum types from Angular Compodoc JSON

### PR DESCRIPTION
**Pull request by lachieh**
Issue: #12531 

## What I did
Added functionality to resolved type aliases and extract enum types from the compodoc generated json file

## How to test

- Is this testable with Jest or Chromatic screenshots?
Added test cases for named enum types

- Does this need a new example in the kitchen sink apps?
Yes, there is a new Enum example component

- Does this need an update to the documentation?
Possibly. I was not able to get the base Enum type with auto-incrementing number values to work correctly. It will generate the select input, though switching between the values does not update the component.

### CODE REVIEW

**Comment by lachieh** [comment]
I've added test cases to cover the new Types.

@shilman If possible, can you add the `hacktoberfest-accepted` label [(i)](https://hacktoberfest.digitalocean.com/hacktoberfest-update) to this PR?

**Comment by lachieh** [comment]
Should I update the documentation for this? I'm trying to think if the detail should go in the docs for `addon-controls`, `addon-docs` or both.

**Review by shilman — APPROVED** [review]
LGTM @lachieh! Thanks for your patience on this!

**Review by shilman — APPROVED** [review]
LGTM @lachieh! Thanks for your patience on this!

**Comment by lachieh** [comment]
Thank you!

**Pull request merged**
