### PR TITLE
📜 tech preview of monaco editor + 📦sandpack

### PR DESCRIPTION
**Pull request by libetl**
Issue:
simplescreenrecorder-2019-03-19_16 32 47
https://codesandbox.io/s/github/libetl/storybook-to-codesandbox-test
## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
@libetl @ndelangen Awesome awesome awesome! Let's figure out a branching strategy before merging this.

**Comment by libetl** [comment]
This is a *DRAFT* PR. It is for internal review only. Don't consider it for merging.

**Comment by libetl** [comment]
The fix for reusing the same storystore is not working.
I should consider looking at the place were the data is upgraded, to merge the stories instead of just assigning them

**Comment by libetl** [comment]
hi, still want it ?

:arrow_right: the major challenge is how to get the recursive introspection working without exceeding the available memory.

**Comment by wildeyes** [comment]
@libetl can you explain more what does this do?

**Comment by shilman** [comment]
Closing due to inactivity

**Pull request closed without merging**
