### PR TITLE
Allow replacing of stories

### PR DESCRIPTION
**Pull request by mikeduminy**
Issue: #4056

## What I did
Replaced the error thrown when adding an already existing story with a `console.warn`. Created a test that covers this case. Note: `console.warn` is mocked as the jest config throws an error when this is called.

### CODE REVIEW

**Comment by michaelduminy** [comment]
Also note I made this change on my fork's `release/3.4` branch to be merged into storybook's `release/3.4` branch due to the ongoing work on version 4.

**Comment by Hypnosphi** [comment]
So the issue doesn't reproduce on master? If it does, please rebase your PR on master, we will cherry-pick it to release branch after merging

**Comment by michaelduminy** [comment]
@Hypnosphi I'm not sure. I didn't test on v4. 

Should I close this PR and create a new one from fork/master to master?

**Comment by Hypnosphi** [comment]
Not really, I've changed the base

**Comment by Hypnosphi** [comment]
Ok, It maight be easier to create a new PR than resolve all the conflicts correctly

**Comment by michaelduminy** [comment]
Okay cool. Thanks! I didn't realise you could change the base. Will create a new PR.

**Comment by michaelduminy** [comment]
New PR here: https://github.com/storybooks/storybook/pull/4061

**Pull request closed without merging**
