### PR TITLE
Add surplus support

### LINKED ISSUE #8485: Surplus support
**Describe the solution you'd like**
Support for [Surplus](https://github.com/adamhaile/surplus) would be wonderful.

**Describe alternatives you've considered**
Basic HTML mode, but that quickly ran into limitations.

**Are you able to assist bring the feature to reality?**
Yes.

**Additional context**
One of the fastest JSX libraries available (according to benchmarks), beginning to ramp up in popularity.

cc @adamhaile

### PR DESCRIPTION
**Pull request by Qix-**
Closes #8485 

## What I did

Added [Surplus](https://github.com/adamhaile/surplus) support.

image

## How to test

Well, storybook is pretty hairy to hack on, so this is how I've been testing:

1. Build everything using `yarn bootstrap`
2. Run verdacio via `yarn bootstrap` -> `Run local registry`
3. Publish all modules
4. `mkdir /tmp/test-sb-surplus && cd /tmp/test-sb-surplus`
5. `npm install @storybook/cli && node_modules/.bin/sb init`
6. Answer `y` to the initialization prompt; select `SURPLUS` from the list
7. After it initializes the package.json, there appears to be a bug somewhere that dumps `{"type": "buffer", "data": [...]}` which, for some reason, is the output of `npm init -y` (not the package.json file, but the literal console output) - not sure what is up with that. I simply `rm package.json` and move on with my day.
8. Run `node_modules/.bin/start-storybook -p 6006`

- Is this testable with Jest or Chromatic screenshots?

I'm sure. I need some guidance here.

- Does this need a new example in the kitchen sink apps?

I'm not a huge user of Storybook so I'm not a good person to answer this. I _think_ it needs a whole new kitchen sink - not just a new example.

- Does this need an update to the documentation?

Yes, I have not updated any docs (yet) in this PR. I'd like to make sure all of the functional aspects are there and available.

### CODE REVIEW

**Comment by Qix-** [comment]
@rauchg You caught a big one with storybook ;) Nice job.

**Comment by Qix-** [comment]
As for DeepScan:

> Imported binding 'Surplus' is not used.

Yes, that's intentional. It's required by the Surplus compiler in order to function properly. It's the runtime, and is similar to how `react` is imported.

Is there a way to tell DeepScan to ignore this line?

**Comment by Qix-** [comment]
Danger JS appears to be broken:

```
Failing the build, there is 1 fail.
Request failed [403]: https://api.github.com/user
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://developer.github.com/v3/users/#get-the-authenticated-user"
}
Request failed [403]: https://api.github.com/user
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://developer.github.com/v3/users/#get-the-authenticated-user"
}
Request failed [403]: https://api.github.com/repos/storybookjs/storybook/issues/8645/comments
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}
Feedback: undefined
##[error]Docker run failed with exit code 1
```

**Comment by Qix-** [comment]
If anyone wants to test with knobs (even though knobs aren't the best thing here - signals would be, but there is no `@storybook/signals` package, of course), this is how you'd do it:

1. Initialize a Surplus storybook
2. Install `@storybook/addon-knobs` and register it in `.storybook/addons.js` with `import '@storybook/addon-knobs/register';`
3. Then in your stories, do:

```javascript
import { withKnobs, number } from '@storybook/addon-knobs';

const knobbed = fn => () => withKnobs()(fn)({});

import Button from './button';

export default {
  title: 'Button',
  component: Button,
};

export const numbered = knobbed(() => {
	const num = number("Number", 1234);

	return (
		<Button onClick={action('clicked')}>{num}</Button>
	);
});
```

**Comment by Qix-** [comment]
Also cc @adamhaile

**Comment by ndelangen** [comment]
@Qix- it'd be great to have an example in the examples directory, do you think you could add a lightweight example there?

Those examples get smoke-tested and deployed on every commit.

**Comment by ndelangen** [comment]
I also invited you to the GitHub org 🎉

**Comment by woongsikchoi** [comment]
> 
> 
> As for DeepScan:
> 
> > Imported binding 'Surplus' is not used.
> 
> Yes, that's intentional. It's required by the Surplus compiler in order to function properly. It's the runtime, and is similar to how `react` is imported.
> 
> Is there a way to tell DeepScan to ignore this line?

@Qix- You can ignore DeepScan alarms occurring on a line with an inline comment:

```JavaScript
import * as Surplus from 'surplus'; // deepscan-disable-line
```

**Comment by Qix-** [comment]
Awesome, thank you!

**Comment by Qix-** [comment]
Been busy with work, but I intend to get back to this.

**Comment by Qix-** [comment]
This is still active, we've just been a bit on hold over the holidays. :)

**Comment by ndelangen** [comment]
Hey @Qix- I just got back from vacation myself, I just merged in the base branch & resolved conflicts

**Comment by ndelangen** [comment]
@Qix- Is this PR still in Draft status?

**Comment by ndelangen** [comment]
Do you think there should be an example included, so we can test this in the monorepo?

**Comment by Qix-** [comment]
Yeah there should be.

Not stale, just not our number one priority right now.

**Comment by Qix-** [comment]
Still plan on working on this. Just not on our radar.

**Comment by Qix-** [comment]
.

**Comment by Qix-** [comment]
Yeah I'm tired of fighting with stalebot. Sorry guys.

**Comment by ndelangen** [comment]
Feel free to open it again when you want!

**Pull request closed without merging**
