### PR TITLE
Fix addon Knobs: add array in Object PropTypes

### PR DESCRIPTION
**Pull request by jebarjonet**
#### Knobs addon

`value` prop in `object` type of knob now accepts `PropTypes.array`, while only `PropTypes.object` was accepted.

We now avoid warnings when we use arrays of objects in `object` knobs, which actually works perfectly fine.

**Example** working fine but throwing warnings in browser console concerning Proptypes.

```js
const values = object('options', [
  {
    value: 'red',
    title: 'Red',
    condition: '1',
  },
  {
    value: 'blue',
    title: 'Blue',
    condition: '1',
  },
  {
    value: 'yellow',
    title: 'Yellow',
    condition: '1',
  },
  {
    value: 'green',
    title: 'Green',
    condition: '1',
  },
])
```

screen shot 2017-11-03 at 5 17 09 pm

### CODE REVIEW

**Comment by Hypnosphi** [comment]
This is already fixed in `release/3.3` with #1701, but maybe we should do the same on `master`
@ndelangen what do you think?

**Review by ndelangen — APPROVED** [review]
great!

**Comment by Hypnosphi** [comment]
Should we backport the changes in docs as well?
https://github.com/storybooks/storybook/pull/1701/files

**Comment by ndelangen** [comment]
Yes that sounds like the logical thing to do!

**Comment by ndelangen** [comment]
@jebarjonet Do you want to add the documentation changes?

**Comment by Hypnosphi** [comment]
@jebarjonet do you want to do that? It should be just a matter of copypasting

**Comment by jebarjonet** [comment]
@ndelangen @Hypnosphi I updated the doc :) (I did not update stories as they are not the same as in `release/3.3`)

**Comment by ndelangen** [comment]
@jebarjonet Thank you for this, really appreciate you helping us out, every small improvement helps! 🙇 

If you want to help more and are looking for something, feel free to message me 👍

**Pull request merged**
