### PR TITLE
(#1286) [WIP] Update package.json to use workspaces in react native examples

### PR DESCRIPTION
**Pull request by dangreenisrael**
Issue:#1286

## Why this PR exists

Currently, our build process requires us to take some additional steps for React Native, which slows the development process. The goal here is to get React Native working with yarn workspaces.

## Checklist

- [ ] Implement Haul in react native vanilla
- [ ] Implement Haul in crna
- [ ] Update package.json in root directory
- [ ] Update package.json in example apps

## What I did

Updated `package.json` in `examples/crna-kitchen-sink` and `examples/react-native-vanilla`

## How to test

Is this testable with jest or storyshots?
Yes (existing tests should cover it)

Does this need a new example in the kitchen sink apps?
No

Does this need an update to the documentation?
No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Looks like it actually installs the published packages instead of linking, so it doesn't allow to test local code.

You should change those lines to just `examples/*` so that te RN example packages are actually included in workspaces: 
https://github.com/storybooks/storybook/blob/master/package.json#L13-L14

**Comment by Hypnosphi** [comment]
I tried to do this locally and `yarn storybook` fails in `crna-kitchen-sink`:

```
Error: Cannot find module '/Users/jetbrains/IdeaProjects/storybook/examples/crna-kitchen-sink/node_modules/react-native/local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

The reason is that yarn hoists `react-native` package to top-level `node_modules`, and we need it to be present in package level `node_modules` for some reason

**Comment by Hypnosphi** [comment]
We probably need to use something like `require.resolve('react-native/local-cli/cli.js')` here:
https://github.com/storybooks/storybook/blob/master/app/react-native/src/bin/storybook-start.js#L78

**Comment by Hypnosphi** [comment]
Btw, metro bundler still doesn't support symlinks https://github.com/facebook/metro-bundler/issues/1

So if we want to move RN examples to workspaces we should switch them to haul

**Comment by dangreenisrael** [comment]
@Hypnosphi It looks like haul may be a great solution. I'm going to try it out with the react native vanilla app first, then looking to doing it with the crna example (if it is even possible without ejecting).

**Comment by dangreenisrael** [comment]
Closing this, as I haven't made any progress

**Pull request closed without merging**
