### PR TITLE
Build: Update example to Angular 10

### PR DESCRIPTION
**Pull request by ThibaudAV**
Issue: na

## What I did
Update angular-cli exemple to angular 10

## How to test

- Is this testable with Jest or Chromatic screenshots?
> na
- Does this need a new example in the kitchen sink apps?
> na
- Does this need an update to the documentation?
> na

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ThibaudAV** [comment]
I plan to make angular 11 in another PR, after this one

**Comment by gaetanmaisse** [comment]
@ThibaudAV can you update your branch to fix the conflicts?

**Comment by ThibaudAV** [comment]
done

**Review by gaetanmaisse — APPROVED** [review]

**Review by shilman — APPROVED** [review]
Thanks @ThibaudAV !

**Pull request merged**
