### PR TITLE
Angular: Make innerTemplate customizable

### PR DESCRIPTION
**Pull request by manuelmeister**
Issue: #14596

## What I did
Published innerTemplate as a `StoryFnAngularReturnType` to provide a real fix for: https://github.com/storybookjs/storybook/issues/14596#issuecomment-933446102

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [x] Does this need a new example in the kitchen sink apps?
- [x] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@manuelmeister thanks for making this PR! @storybookjs/angular Can you please take a look?

**Comment by kroeder** [comment]
This is pretty cool and something I missed, too! 

I wonder if this would also support ng-content slots, e.g. 

```
<div style="...">
  <ng-content></ng-content>
</div>
<ng-content select="app-awesome"></ng-content>
```

```
innerTemplate: `
  This is rendered in ng-content
  <app-awesome>This is rendered somewhere else</app-awesome>
`
```

If not, I wonder if there's a way to do that 🤔 

@manuelmeister  have you tested this?

**Comment by manuelmeister** [comment]
I would assume, as I think this is generated before angular parses the ng-content.

@kroeder I did, but I think I had some issues with controls not updating the canvas. But I don't think that they are a result of my changes.

**Comment by kroeder** [comment]
Sorry for the delay, I was on holiday the last few days

Another question: I'm wondering if `innerTemplate` is a good name that others will understand. The general term for this is `content projection`.. maybe something like `projectedTemplate` (though it sounds clunky) or absolutely explicit `ngContentTemplate` 

@storybookjs/angular @shilman what do you think about the property name? I also am fine with `innerTemplate` if only I see a problem here or someone has a better idea. I don't hav

**Comment by ThibaudAV** [comment]
Maybe `componentInnerTemplate` would be better ? because it's only useful if you create/use story with a component class. 
It is useless with a template, right ?. We could even add a warning to help the user ?

**Pull request closed without merging**
