### PR TITLE
feat: merge global parameters

### PR DESCRIPTION
**Pull request by mortal94**
## What I did

deep merge `options` property when using `addParameters` to add global parameters.

## How to test

- Is this testable with Jest or Chromatic screenshots?
-> Yes. added test cases.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM!

**Review by ndelangen — APPROVED** [review]

**Comment by mortal94** [comment]
Hey @shilman , can you tell me when are you going to release this fix? thanks!

**Comment by shilman** [comment]
@mortal94 Thanks for the nudge -- I'd forgotten to merge it. Releasing today.

**Comment by shilman** [comment]
@mortal94 https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.4

**Comment by mortal94** [comment]
> @mortal94 https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.4

Awesome! thanks @shilman ! 🎉

**Pull request merged**
