### PR TITLE
avoid error "storyshots is intended only to be used with storybook" f…

### PR DESCRIPTION
**Pull request by osdevisnot**
…or transitive dependency on @storybook/react

Issue: When `@storybook/react` is not a direct dependency in package.json - the storyshots fails to execute tests with error "storyshots is intended only to be used with storybook". This is ok in normal circumstances, but limits wrapping "@storybook" into a higher order package. 

For example: a project depends on a higher order package (maybe CLI tool). this higher order package brings in both `@storybook/react` and `@storybook/addon-storyshots` with appropriate config. The storyshots will throw above mentioned error.

## What I did
Add a fallback check to see if package.json exists before bailing out on dependency being available.

## How to test
Tested it by using this package in my project.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
@osdevisnot thanks for your contribution! One thing --
 how do I test it on my machine?

**Comment by osdevisnot** [comment]
Setup storyshots as you normally would, and then remove "@storybook/react" dependency from package.json but leave the installed version in node_modules.

Without this PR, you should be able to see above error.

**Comment by shilman** [comment]
@osdevisnot OK great I'll give it a whirl. FYI, `"@storybook/react"` in your initial comment was not escaped, so it just showed up as `""` on github. I went through and fixed it for you, but for future reference ... 😉

**Comment by osdevisnot** [comment]
Aw, I feel stupid.. will be more careful with markdown :( thanks for correcting it.

**Review by tmeasday — APPROVED** [review]
I guess that makes sense!

**Review by shilman — APPROVED** [review]

**Comment by shilman** [comment]
@ndelangen looks like there are some CircleCI config issues when the pull is coming from a fork of our repo?

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Sorry for the delay, LGTM!

**Pull request merged**
