### PR TITLE
Build libs/router with ts-up

### PR DESCRIPTION
**Pull request by hayawata3626**
Issue: https://github.com/storybookjs/storybook/issues/18732

## What I did
Use tsup to build router

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks for the PR, @hayawata3626!  A few notes:

- I'll take care of the DeepScan issue in a different PR, not sure why it started failing suddenly.
- To solve the other error in CI, try adding `"platform": "browser"` to the `"bundler"` config in package.json.
- Lastly, you can remove `core-js` (and re-run `yarn install` to update `yarn.lock`) now that babel isn't being used to compile this package.

**Comment by hayawata3626** [comment]
@IanVS 
Thanks for some notes! 
I will try!

**Comment by IanVS** [comment]
Alright, I'm not sure what is causing the error now.  Maybe @ndelangen will know.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
This is great, I think that was the last package using my old prebundling custom util.
I'll remove the code in a follow up PR. Unless you want to do that @hayawata3626 ?

Thanks, I have a good feeling that this will work now.

**Comment by hayawata3626** [comment]
@ndelangen 
Thank you for your reply!
> I'll remove the code in a follow up PR

Should I just delete utils.js in the libs/router in  this PR ? if so i would like to try!

**Comment by ndelangen** [comment]
I'm not sure what utils.js is used for, but I think it's important. What I am referring to is the code in `../../../scripts/prebundle.ts`. That is a tool I custom made because I could not use ts-up at the time, because it required TypeScript v4, and we didn't think we'd be able to upgrade any time soon.

**Comment by hayawata3626** [comment]
@ndelangen 
Thank you for the explanation.
I will identify and delete files related to `../../../scripts/prebundle.ts`.
Is this PR okay?

**Comment by ndelangen** [comment]
It sure is! 🎉

**Comment by ndelangen** [comment]
Thank you so much for the help @hayawata3626 ❤️ !!

**Comment by hayawata3626** [comment]
@ndelangen 
i want to contribute!!!

**Comment by ndelangen** [comment]
I invited you to the org 🎈

**Comment by hayawata3626** [comment]
@ndelangen 
 I‘m so happy to be a member of storybook!! Thank you!!

**Comment by ndelangen** [comment]
Enjoy the free code co-pilot 😉

**Pull request merged**
