### PR TITLE
Add svelte v3 support

### PR DESCRIPTION
**Pull request by cam-stitt**
Issue: #6697 

## What I did
Updated the `@storybook/svelte` package to use the svelte v3 api. Attempted to update all addons and other areas that I could see directly mentioned svelte.

## How to test

- Is this testable with Jest or Chromatic screenshots? The existing tests should still work.
- Does this need a new example in the kitchen sink apps? No, I updated the existing svelte examples
- Does this need an update to the documentation? Already done.

### CODE REVIEW

**Comment by cam-stitt** [comment]
I'm working on getting the tests working. There are currently some strange issues with jest/svelte3 where imports require you to reference a default still.

```js
import Component from './component.html';

new Component.default({});
```

**Comment by shilman** [comment]
This is awesome @cam-stitt ! @plumpNation Any chance you can take a look at these changes?

**Comment by cam-stitt** [comment]
Update on the `.default` imports issue. Seems it *may* be related to this: https://github.com/sveltejs/svelte/issues/2562

**Comment by cam-stitt** [comment]
I may need some support. I've got the CLI tests passing locally, but seem to fail here.

**Comment by shilman** [comment]
@cam-stitt just update your lockfile?

```
$ node ./scripts/repo-dirty-check
 M yarn.lock
Git repo is dirty, please consider updating lockfiles by running `yarn bootstrap --reset --core`
error Command failed with exit code 1.
```

**Comment by ndelangen** [comment]
@cam-stitt need help?

**Comment by cam-stitt** [comment]
Thanks for getting it sorted. Was away over the weekend. I have just been given an idea on how to remove the need for the duplicate `.default` over at https://github.com/sveltejs/svelte/issues/2562

**Comment by shilman** [comment]
@cam-stitt @ndelangen are there docs that need updating? is this a breaking change that violates semver?

**Comment by cam-stitt** [comment]
@shilman From what I know (this was my first contribution) I've updated the right docs. It would be a breaking change that requires a major bump as svelte 2 would not be supported post this work being released.

**Comment by thollander** [comment]
Awesome ! Thank you, I was waiting for this one 🥳 
Do we have visibility on when it will be available ?

**Comment by shilman** [comment]
@thollander trying to get it out now

**Comment by plumpNation** [comment]
Nice work! Sorry, I've been away for a while. Really great that you did this, svelte 3 is the bomb :)

**Pull request merged**
