### PR TITLE
Bump react-native-vanilla example to 0.57

### PR DESCRIPTION
**Pull request by oblador**
Current `react-native-vanilla` example is not compiling and is out of date. Further it needs to be updated to illustrate issues with the new version (separate PR coming soon) as outlined in https://github.com/storybooks/storybook/issues/4179.

## What I did

Generated a new project from scratch using the latest version of React Native: 0.57. 

## How to test

Since Storybook is broken with the latest RN so is this PR, but if you want to test it out it can be done like this: 

```bash
$ yarn storybook
$ react-native start
$ yarn start
```

### CODE REVIEW

**Comment by ndelangen** [comment]
@Gongreg thoughts?

**Comment by ndelangen** [comment]
Hey @oblador I spoke to @Gongreg about this.

He's on vacation and besides spending time away from the keyboard (very healthy) he's also not able to log in to github on his current device, so I'm relaying a message:

> I want to remove that example as soon as I can,  remove packager and separate out the server.
> So these things will be obsolete.
> 
> For users using older react native with babel 6 they will be able to use the server as a separate separate project if necessary.

Do you think it's meaningful to merge this meanwhile @oblador ?

If yes, I'll gladly merge it.

I think @Gongreg could use someone to pair with about Storybook for RN, are you on slack/discord? You 2 should get in contact after his vacation about this.

**Comment by kdawgwilk** [comment]
This is broken due to the changes made here: 
https://github.com/facebook/react-native/commit/c5ce7626977a7650e8dce335f2ce78b94839a2a8#diff-4a892a6b8856f0253e2de7094e585ae6 and here https://github.com/facebook/react-native/commit/33ba5e8fa26a3e8f32e386f377107a7a03743360#diff-4a892a6b8856f0253e2de7094e585ae6

That changed the arguments from `--projectRoots [list]` -> `--watchFolders [list]` and `--root [list]` -> `--projectRoot [string]`

**Comment by oblador** [comment]
@kdawgwilk I know, and I mention it in the description; my plan is to attack it in a separate PR. However that diff also broke those new arguments, but I have a PR up for that: https://github.com/facebook/react-native/pull/21165

@ndelangen I'm on slack and have talked to him before. This PR is mostly preparation for the mentioned incompatibility with RN 0.57. I guess I could fix it regardless, but this way we could at least manually test it in lieu of automated tests. 

As a sidenote, my impression is that RN is a bit forgotten by the overall team/community and has regressions on a regular basis. Maybe we should discuss at least having some kind of basic smoke test to get rid of the worst of it?

**Comment by ndelangen** [comment]
@oblador YES that'd be fantastic! We use circleCI and they do provide macOS runners if we need that.

We could use OpenCollective money to pay for it, or ask CircleCI for sponsorship

**Comment by Gongreg** [comment]
Hey @oblador .
We are going to remove the packager from RN storybook.

It is not storybook responsibility to know what packager you want to use.

I think that would even make more sense to do now than later so people would know that you can use rn storybook not only by running storybook as a command but you can include it inside your app and start server (if neccessary) with --skip-packager command.

**Comment by Gongreg** [comment]
Also I want to leave only one example for RN storybook, preferably expo since it is more beginner friendly to use. Nobody is maintaining the vanilla one.
I would really like to add some tests for it, just have other priorities before that.

**Comment by oblador** [comment]
@Gongreg OK, fair enough. Does that mean that I shouldn't submit a PR with the new flags?

**Comment by AugustoAleGon** [comment]
I hope the merge will be released soon. I am currently facing an error probably the PR will help me.

**Comment by Gongreg** [comment]
Will updating the arguments break versions older than RN 0,57? If it doesnt it is definitely worth to push it. Otherwise I am not sure since most people dont migrate to latest RN version as soon as possible. I wont be able to do anything for few weeks so my changes will have to wait. I think @oblador it is your call now.

**Comment by oblador** [comment]
@Gongreg It can be done in a backwards compatible manner if we do some inspection of the react-native version, but it's somewhat slow, adds another second or two. I think I will go with the `--no-packager` route myself, but maybe we should communicate that somehow.

**Comment by Gongreg** [comment]
@oblador , I've been trying to document it on my PR. @ndelagen do you have ideas how we could document this issue and notify people about --no-packager option for the time I am away?

**Comment by AugustoAleGon** [comment]
What is the `no-package` option? @Gongreg .

**Comment by Gongreg** [comment]
I think it is actually --skip-packager.

It starts storybook server without packager so you can reuse same packager instance you use while developing your app. Then you just render storybook component anywhere in your app.

**Pull request closed without merging**
