### PR TITLE
Preview: Clean storybook-root innerHTML when switching to docs

### PR DESCRIPTION
**Pull request by codecansdev**
Closes #21736

## What I did

I added a line to clean **storyRoot() innerHTML**  when switching to docs view. This should take care of cleaning the DOM for modules that rely on dynamically generated attributes (

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by thangpqtechlead — APPROVED** [review]

**Comment by yannbf** [comment]
Hey @offbeat-dev thanks a lot for your contribution! @tmeasday would you mind taking a look?

**Comment by tmeasday** [comment]
Can you provide an example of when this is needed? Could we encode that as a story & E2E test?

**Comment by offbeat-dev** [comment]
hi @tmeasday, we run into the need for this, while testing a story for an accordion [https://stackblitz.com/edit/github-ls2xe1?file=src%2Fscripts%2Fmodules%2Faccordion.ts,src%2Fstories%2Fmodules%2Faccordion.stories.ts](https://stackblitz.com/edit/github-ls2xe1?file=src%2Fscripts%2Fmodules%2Faccordion.ts,src%2Fstories%2Fmodules%2Faccordion.stories.ts).  

We noticed that after switching between the module **docs** and **story** a couple of times, the accordion stopped working in the **docs**. This has to do with the accordion relying on the **document.getElementById** to match the trigger with its panels. Since the **storybook-root** node comes before **storybook-docs** in the DOM the triggers end up matching the wrong panels if the **storybook-root** node innerHTML is not clean when switching to **docs** view. 

I have added an accordion story to the html-vite-js sandbox in order to test this scenario. Haven't been able to work on the e2e test yet, though. Will try to do that this week.

Thank you for taking the time to review this issue.

**Comment by tmeasday** [comment]
@offbeat-dev so is the problem that the HTML renderer doesn't actually teardown the story? 

Notice that the react renderer returns a "teardown" callback from the `renderToCanvas` function:

https://github.com/storybookjs/storybook/blob/529089564eb1b369603ee3c563c3ed6f585002f9/code/renderers/react/src/render.tsx#L89

But that the HTML one does not:

https://github.com/storybookjs/storybook/blob/529089564eb1b369603ee3c563c3ed6f585002f9/code/renderers/html/src/render.ts#L43-L47

Maybe you should try adding a return function like `() => canvasElement.innerHTML = ''`?

**Re: tests**

Thanks for adding the stories! A couple notes:

- if the test is going to be html specific, put it this folder: https://github.com/storybookjs/storybook/blob/529089564eb1b369603ee3c563c3ed6f585002f9/code/renderers/html/template/stories/html-mdx.stories.mdx#L22
  - you'll then see them if you create an html sandbox (`yarn task` and choose an html template and the sandbox task)

- Can we boil the example down to a very simple case that shows the same behaviour? That'll make it easy to reason about in the the future.

**Comment by yannbf** [comment]
Hey @JReinhold would you mind taking a look? Thanks!

**Comment by ndelangen** [comment]
I strongly agree with @tmeasday on this:

> Maybe you should try adding a return function like () => canvasElement.innerHTML = ''?

**Comment by JReinhold** [comment]
> Maybe you should try adding a return function like () => canvasElement.innerHTML = ''?

This is most likely the correct way to fix this.

Feel free to open a new PR with that change.

**Pull request closed without merging**
