### PR TITLE
Improve cli for react-native

### PR DESCRIPTION
**Pull request by benoitdion**
Issue: #6470

## What I did

- Set port to the default
- Use `installBabel` primitive  to bring in babel-loader

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM! Looks like my issue was bogus? Or only applied to an old version of the CLI?

**Comment by benoitdion** [comment]
It got fixed in next but was broken for 5.0 which is what a lot of people are using.

**Comment by shilman** [comment]
@benoitdion I'm confused--there is no RN in 5.0?

**Comment by benoitdion** [comment]
I think we thought this was an issue because of users trying to install RN with a 5.0 cli. We should be good either way.

**Pull request merged**
