### PR TITLE
Remind to add a new script for running storybook

### PR DESCRIPTION
**Pull request by GitCodeDestroyer**
Every time, all new users of storybook stuck at here. Please, add some instruction to adding a script for running npm run storybook.

Issue:

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
If you run `npx sb init` which is the way we recommend installing Storybook, it will automatically add this to your `package.json`, so I'm not sure why we need this?

**Comment by phated** [comment]
I tend to agree with @shilman that the documentation should be clear on the recommended path `npx sb init` which will already include the script.

**Comment by jonniebigodes** [comment]
@GitCodeDestroyer thank you for the time and effort you put into this, but i'm going to close this. I'm with @shilman on this as well. We instruct users to use `npx sb init` for the optimal experience. As it will streamline the workflow for you. It adds Storybook and its dependencies, adjusts your project scripts accordingly and also some examples to get you started. If your specific case, or if you're using a framework /meta-framework (Gatsby for instance) that is not covered, or requires manual intervention feel free to open a discussion and we'll go from there.

Stay safe

**Comment by GitCodeDestroyer** [comment]
OK, I got it.

**Pull request closed without merging**
