### PR TITLE
Remove self-closing div tag, which is invalid HTML

### PR DESCRIPTION
**Pull request by wyattdanger**
Removes a self-closing div tag, because there is no such thing as a self-closing div tag (unless you're serving up XHTML) and older IEs get mad about it

screen shot 2016-04-25 at 1 49 07 pm

### CODE REVIEW

**Comment by arunoda** [comment]
Could you merge your branch with the our latest master branch.
Seems like there are some conflicts.

**Comment by wyattdanger** [comment]
@arunoda done, thank you

**Comment by wyattdanger** [comment]
@arunoda it is now rebased, conflicts are resolved

**Comment by arunoda** [comment]
Awesome.

**Pull request merged**
