### PR TITLE
Fix propTypes not showing in PropType table

### LINKED ISSUE #4016: PropTypes not being recognized/parsed from component.
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I added a story using addon-info, but PropTypes are not showing. 

### Steps to reproduce

The code has some specific implementation with HOCs, but the propTypes declaration and defaultProps are pretty straightforward. 

BTW, the propTypes are being recognized in other components of the same project. 

```
import R from 'ramda';
import {
  withState,
  withHandlers,
  lifecycle,
} from 'recompose';
import PropTypes from 'prop-types';

import TabsRenderer from './TabsRenderer.jsx';

const Tabs = R.compose(
  withState('actualTab', 'setActualTab', p => p.defaultTab),
  lifecycle({
    componentDidMount() {
      this.props.onActualTabChange(this.props.actualTab);
    },
  }),
  withHandlers({
    setActualTab: p => (v) => {
      p.onActualTabChange(v);
      p.setActualTab(v);
    },
  }),
)(TabsRenderer);

Tabs.displayName = 'Tabs';

Tabs.defaultProps = {
  keyExtractor: tab => tab.id
};

Tabs.propTypes = {
  tabs: PropTypes.array.isRequired,
  keyExtractor: PropTypes.func.isRequired,
  renderItem: PropTypes.func.isRequired,
  defaultTab: PropTypes.any.isRequired,
};


export default Tabs;
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.16
- @storybook/addon-info 4.0.0-alpha.16

### LINKED ISSUE #4087: Addon-Info: Fix issues with property names
### Bug or support request summary

Addon-info is destructing the `propType` object when it comes as a string. https://github.com/storybooks/storybook/blob/master/addons/info/src/components/types/PrettyPropType.js#L34

### Steps to reproduce

When using a simple component, the prop types are not being presented on the PropTables:

```js
import React from 'react';
import PropTypes from 'prop-types';

/** Button component description */
const Button = ({ disabled, label, style, onClick }) => (
  <button disabled={disabled} style={style} onClick={onClick}>
    {label}
  </button>
);

Button.defaultProps = {
  disabled: false,
  onClick: () => {},
  style: {},
};

Button.propTypes = {
  /** Boolean indicating whether the button should render as disabled */
  disabled: PropTypes.bool,
  /** button label. */
  label: PropTypes.string.isRequired,
  /** onClick handler */
  onClick: PropTypes.func,
  /** component styles */
  style: PropTypes.shape,
};

export default Button;

...

storiesOf('Button', module)
  .add(
    'Default',
    () => <Button label="test" />,
  );
...

```

button_story

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.14
- @storybook/addon-info 4.0.0-alpha.1

### PR DESCRIPTION
**Pull request by kkemple**
This is an attempt to fix the issue with `propType` not being displayed in the PropTypes table.

Issue:

## What I did
Attempted to fix the issue by not destructuring `propType` in `types/PrettyPropType.js`. Also updated `getPropTypes` function in `types/proptypes.js`.

## How to test
Not sure! First time contributor, would be glad to make any adjustments or run any tests needed.

Closes #4016 
Closes #4087

### CODE REVIEW

**Comment by kkemple** [comment]
Will fix linting errors if this is something y'all decide to move ahead with!

**Comment by ndelangen** [comment]
@kkemple hey sorry for this PR to have been open so long. I just checked it out, and fixed 2 minor things. if all is green, it's good to merge!

Well done @kkemple thanks for this!

**Comment by kkemple** [comment]
no worries! i'll take a look at failing tests today or tomorrow and try to get this green!

**Comment by ndelangen** [comment]
Please let me know if you need help!

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
