### PR TITLE
Blocks: Description stories

### PR DESCRIPTION
**Pull request by JReinhold**
Telescoping on top of #19805

This PR adds stories for the Description block as well as deprecations warnings.

Most of the features of Description is being deprecated, so it only supports showing descriptions from the docgen and not from story `notes` or `info` parameters, to simplify the API. `notes` and `info` were originally a migration path from their respective addons.

It also won't support manual descriptions passed as the `markdown` props or as a single markdown string child, as users can specify those directly in their MDX instead.
For users using this block in JSX and want to write markdown they have to build that conversion themselves using tools like [`react-markdown`](https://remarkjs.github.io/react-markdown/), and it's not considered to be the responsiblity of Storybook.

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
LGTM.

**Comment by tmeasday** [comment]
@JReinhold is this right:

image

Apologies I am a bit unclear on where these stories end up -- do they not appear in our `storybook-ui` SB? If so, is something broken here?

**Comment by JReinhold** [comment]
> @JReinhold is this right:
> 
> image
> 
> Apologies I am a bit unclear on where these stories end up -- do they not appear in our `storybook-ui` SB? If so, is something broken here? If not, should we be adding a chromatic step for wherever they do appear?

Good catch, I have no idea what's going on there. The stories are in the Storybook (also via Chromatic), but not all of them are visible in the Chromatic library. Looks like it's something off with the casing of the story names. I'll investigate further.

**Comment by tmeasday** [comment]
The visibility in the library I think is a bug where we filter out components at a certain depth (I think that's right @JonathanKolnik ?)

**Comment by JReinhold** [comment]
@tmeasday after pulling in `next` another time it apparently started recognising the changes 🤷

**Comment by tmeasday** [comment]
@JReinhold I think this is a TS misconfiguration issue. When I look at the `onlyStoryFiles` on the build, I see this path: `'./blocks/src/blocks/Description.stories.tsx'`, but when I look at the `fileName` parameter on the story, I see: `'./ui/blocks/src/blocks/Description.stories.tsx'`.

I'm not 100% sure on what the correct configuration is but it looks like it's wrong? Maybe the `--storybook-base-dir ./code/ui` on this line @ethriel3695?

https://github.com/storybookjs/storybook/blob/587aec7d660091a287cc74f6b54450a0338b69da/code/package.json#L84

The reason it worked when you merged next is that it probably reran every story due to a `yarn.lock` change.

**Comment by JReinhold** [comment]
> I'm not 100% sure on what the correct configuration is but it looks like it's wrong? Maybe the `--storybook-base-dir ./code/ui` on this line @ethriel3695?
> 
> https://github.com/storybookjs/storybook/blob/587aec7d660091a287cc74f6b54450a0338b69da/code/package.json#L84

I think you might be right here Tom. The directory setup is a bit confusing:
- all our stories and ui are within `/code/ui`, so that's where the `.storybook` dir is as well.
- but the the "base project" dir is `/code`, this is where the `package.json` and `node_modules` live.
- this is because that's the only way to satisfy Vite and dependencies.

So I think `--storybook-base-dir ./code` is more correct. I just changed it and it still built the correct stuff, however I don't know how to debug the `onlyStoryFiles` parameter like you did.

**Pull request merged**
