### PR TITLE
Transpile safe-eval package

### PR DESCRIPTION
**Pull request by Hypnosphi**
Issue: #5472

### CODE REVIEW

**Comment by ndelangen** [comment]
CLI tests are throwing an error:
```

ERROR in /tmp/storybook/node_modules/safe-eval/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/tmp/storybook/node_modules/@babel/preset-env/lib/index.js")
    at throwVersionError (/tmp/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/tmp/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/tmp/storybook/node_modules/@babel/preset-env/lib/index.js:154:7)
    at /tmp/storybook/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-loader/lib/index.js:50:20)
    at /tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/tmp/storybook/lib/cli/test/run/react_babel_6/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ /tmp/storybook/node_modules/telejson/dist/index.js 20:39-59
 @ /tmp/storybook/lib/channel-postmessage/dist/index.js
 @ /tmp/storybook/lib/core/dist/client/preview/start.js
 @ /tmp/storybook/lib/core/dist/client/preview/index.js
 @ /tmp/storybook/lib/core/dist/client/index.js
 @ /tmp/storybook/lib/core/client.js
 @ /tmp/storybook/app/react/dist/client/preview/index.js
 @ /tmp/storybook/app/react/dist/client/index.js
 @ ./.storybook/config.js
 @ multi /tmp/storybook/lib/core/dist/server/common/polyfills.js /tmp/storybook/lib/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

Do you know a fix?

**Comment by Hypnosphi** [comment]
Will investigate on the weekend

**Comment by Hypnosphi** [comment]
@ndelangen fixed

**Comment by ndelangen** [comment]
Where are we using `safe-eval` btw?

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
👏

**Pull request merged**
