### PR TITLE
Fix: reacts urlForAssets loading non js,css files

### PR DESCRIPTION
**Pull request by ianmcnally**
Issue: when building a non css or js file with webpack, storybook would throw the error: 

```
TypeError: Cannot read property 'push' of undefined
    at /Users/me/project/node_modules/@storybook/react/dist/server/iframe.html.js:69:33
    at Array.forEach (native)
```

## What I did

I added a [webpack plugin](https://github.com/kisenka/svg-sprite-loader/blob/master/examples/extract-mode/webpack.config.js#L44) to build an external svg.

That produced an assets bundle:

```
assets { preview:
   [ 'static/preview.bundle.js',
     'design-system-components.css',
     'static/preview.bundle.js.map',
     'design-system-components.css.map' ],
  manager: [ 'static/manager.bundle.js', 'static/manager.bundle.js.map' ],
  'patterns-sprite.svg': 'patterns-sprite.svg' }
```

Which the logic in [iframe.html.js](https://github.com/storybooks/storybook/blob/master/app/react/src/server/iframe.html.js#L34) fails to consider any extension beyond what it's define (`js`, `css`).

## How to test

Include a non css or non js file in your webpack bundle. Or you could rename something generated by extract text webpack plugin to something non js or css.

### CODE REVIEW

**Comment by ndelangen** [comment]
Does this change not also affect the vue app?

**Comment by ianmcnally** [comment]
@ndelangen 
> Does this change not also affect the vue app?

The issue effects the Vue app, having just looked it it. Looks like the same code in app/view/.../iframe.html.js. 

As for how to proceed with this PR, would you like to see that change there, an approach to share the code, or just to get this into the react app?

**Comment by ndelangen** [comment]
Copy the fix into the vue code sounds like the best course of action for now.

Yes I know this feels bad. It's a conscious choice to duplicate this code, and I knew there would be some pains because of it.

But we know where the duplication really hits us and with the angular work we'll know much better what we should abstract into common bits and what we shouldn't.

**Comment by ianmcnally** [comment]
Totally understand @ndelangen. Added the code in the view app in 89eb3c4.

**Comment by satazor** [comment]
Just wanted to let you guys know that I also have hit the same issue. Is there anything missing for this MR to land? 

@ianmcnally is there any quick workaround for this issue?

**Comment by ndelangen** [comment]
Verified by adding a svg-file as additional entrypoint in a custom webpack config.

**Comment by ianmcnally** [comment]
@satazor you could point to the commit into master 7ea6c54

**Comment by satazor** [comment]
@ianmcnally I installed from git pointing to that commit, but I can't point to a subdirectory (app/react). Any alternative way to install?

`"@storybook/react": "git+ssh://git@github.com:storybooks/storybook.git#7e60bc074696f2a7c3f66db18a5855d1dfa0f587",`

**Comment by Hypnosphi** [comment]
You can specify it whe importing: `import {...} from '@storybook/react/app/react'`

**Comment by satazor** [comment]
The issue is that when installing from git:

- `start-storybook` bin is not installed
- `node_modules/@storybook/react` is not present
- `node_modules/storybook` is not present either

Here's my package.json devDeps:

```
    "@storybook/addon-actions": "^3.2.0",
    "@storybook/addon-info": "^3.2.4",
    "@storybook/addon-knobs": "^3.2.0",
    "@storybook/addon-storyshots": "^3.2.3",
    "@storybook/react": "storybooks/storybook#7e60bc074696f2a7c3f66db18a5855d1dfa0f587",
```

I'm using npm5. Using npm4, the package installs but `start-storybook` is unavailable.
Alternatively, perhaps we could release this feature?

Thanks.

**Comment by ndelangen** [comment]
> @ianmcnally I installed from git pointing to that commit, but I can't specify the subdirectory (app/react). Any alternative way to install?

Indeed this is not possible. This feature [has been requested](https://github.com/npm/npm/issues/2974) but npm has shown 0 interest in adding it.

**Comment by ndelangen** [comment]
We will release to npm soon!

**Comment by ndelangen** [comment]
Should be on npm!

**Pull request merged**
