### PR TITLE
WIP: key and value for select knob match key/value of options

### LINKED ISSUE #799: select knob seems backwards
<a href="https://github.com/lifehackett"></img></a> **Issue by [lifehackett](https://github.com/lifehackett)**
_Tuesday Nov 01, 2016 at 20:18 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/71_

----

Every time I use the `select` knob object syntax I write it incorrectly, but it also is more limiting.  IMO it makes more sense that the dropdown would show the keys and on selection pass the value.  

Additionally, the current setup restricts what can be passed as the prop value to strings or numbers because object keys are more restricted.  i.e. you can't have a function or an object in the key position, but you could in the value.

I realize this would be a breaking change.

### PR DESCRIPTION
**Pull request by psimyn**
fixes #799

**Breaking change**

Issue:

Using knobs is currently confusing. 

Example, for complex strings and null values

```
select('My Select', {
  none: null, // renders empty item
  [`Computed key`]: 'computed', 
  'Some kind of long sentence. This is ok, mainly just looks odd as a key': 'sentence',
})
```

## What I did

Use value as value
Still uses key for the key property on each `<option>`

## How to test

```
select('My Select', {
  Empty: null,
  'First item': 'The first item selected',
  second: `The item with key 'second' is selected`
})
```

Will add some tests. Is there a preference between `__tests__` folder and `*.test.js`?

### CODE REVIEW

**Comment by shilman** [comment]
@psimyn @ndelangen how do we want to release this breaking change?
- keep the PR open until we hit 4.0?
- sneak it in for 3.2?
- sneak it in for 3.1.x?

**Comment by psimyn** [comment]
@shilman I'd like it in stable as soon as possible. On the fence about breaking semver, I'm not using knobs addon for anything critical. I addon package are supposed to stay at same version as main repo?

**Comment by ndelangen** [comment]
We release all packages with the same major.

This IS a breaking api change. this SHOULD be a major version.

BUT keeping this from users until `4.0.0` seems ... meh

Can we think about toggling this behavior somehow?

**Comment by shilman** [comment]
@psimyn regarding stability, it's about the thousands of companies and developers using storybook, not whether you're using it for anything critical 😉 

I propose we put it into 3.2, which should be a pretty good release. It's not strict semver, but at least people will be getting something for upgrading with a breaking change.

Another option would be to fix some stuff with the addons API and rename 3.2 to 4.0. Not ideal, but especially if we could get Angular2 in there, it would be a great release!

**Comment by igor-dv** [comment]
What about to backward-compatible it ? For example crate a new `Select_4_0.js` (or some better name =/ ) that will include the fix.. And in a major release (4.0) to break it..

**Comment by shilman** [comment]
@igor-dv can you explain in more detail what you are thinking? So we put this into a Select_next.js and then enable it using some kind of feature flag `setOptions({ knobSelectDisplayValue: true })` until 4.0 when we make that the default?

**Comment by igor-dv** [comment]
@shilman , exactly, I couldn't describe it better ;)

**Comment by psimyn** [comment]
Would it be ok to override for each select?.

```
--- a/addons/knobs/src/index.js
+++ b/addons/knobs/src/index.js
@@ -42,8 +42,8 @@ export function object(name, value) {
   return manager.knob(name, { type: 'object', value });
 }

-export function select(name, options, value) {
-  return manager.knob(name, { type: 'select', options, value });
+export function select(name, options, value, displayValue = false) {
+  return manager.knob(name, { type: 'select', options, value, displayValue });
 }
```

@igor-dv @shilman if global setting is better can you please point me to somewhere else that does it? I wasn't sure where to store global options

**Review by ndelangen — CHANGES_REQUESTED** [review]
This would be fine for `4.0.0` but that's some ways off I think.

Like I suggested, let's find a way to support both until `4.0.0`!

**Comment by EloB** [comment]
When will this be added? It's a really good feature! <3

**Comment by Hypnosphi** [comment]
What we can do without breaking (almost) anything is support an "array of objects" syntax, which is more verbose, but also more explicit:

```
[
  {
    label: 'None',
    value: null
  },
  {
    label: 'Mail',
    value: MailIcon
  }
]
```

**Review by ndelangen — APPROVED** [review]
Code LGTM, 

We need to agree on a release strategy

**Comment by psimyn** [comment]
I had some craziness happen with remotes, so I created https://github.com/storybooks/storybook/pull/1745

Adds `selectV2` until we make it default

**Pull request closed without merging**
