### PR TITLE
Core: CSS modules support out of the box

### PR DESCRIPTION
**Pull request by shashkovdanil**
Issue: #11961

## What I did

Added support css modules out of the box, because I think css modules now standart de-facto

## How to test

- Write story with components with css modules

### CODE REVIEW

**Comment by shilman** [comment]
I think this is technically a breaking change. Anybody know how breaking it actually is in practice? @ndelangen @bpscott @tmeasday

**Comment by BPScott** [comment]
Yep this is a breaking change unfortunately. Per the [css-loader docs](https://github.com/webpack-contrib/css-loader#modules) setting modules to true will enable css modules for all filenames that match `/\.module\.\w+$/i.test(filename)`.

For instance if you had a file named `foo.module.css` or `bar.module.scss` it would now be opted into using css modules and all its classnames would be mangled when they were not before.  `baz.css` would be unaffected and would not be passed through css modules

Something I've been meaning to add to that issue but never got around to it:

I think a good configuration step would be exposing a configuration parameter `styles` added to main.js in the same way as [`typescript`](https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration) allows for configuration of typescript options and the options therein could be used to configure styleing options - both the configuration of css modules and any additional things like "add the scss loader".

In main:

```js
module.exports = {
  styles: {
    cssModules: true // This key would be passed into the css-loader's `modules` key. IT should accept any of the valid valies of css-loader's modules option, such as being an object.
   scss: true // Setting this to true would add processing of scss files using scss-loader
  }
}


To start with we could have the default for the cssModules option as false - the current value and thus no breaking change, while allowing folks an easy in to activate css modules in their main.js. Then in a major release later down the line storybook could consider changing the default from false to true to opt into css modules by default

---

I figured the extra level of nesting style would allow grouping of other css related options (such as activating/deactivating scss loading if you don't want that to be a default behaviour) rather than expanding the number of top level options.

**Comment by tmeasday** [comment]
Where do we stand on options to turn features on vs just a preset that you have to install? 

The former is nicer for sure but I guess the downside is dependencies that are wasted on users that don't need them.

**Comment by ndelangen** [comment]
proposal:


```js
// main.js
module.exports = {
  stories: ['../stories/*.stories.@(ts|tsx|js|jsx|mdx)'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],
  css: { 
    modules: true,
  },
}
```

If a presetProperty name `css` is too generic:

```
  cssLoaderOptions: { 
    modules: true,
  },
```

---

> Where do we stand on options to turn features on vs just a preset that you have to install?

preferably we put this in a preset. BUT we already have css support, extending it to pass in extra options here:
https://github.com/storybookjs/storybook/blob/67a67eabc26a5eb0d835c764fe1678252dd2ec94/lib/core/src/server/preview/base-webpack.config.js#L58-L61

It'd be as simple as a `...(await presets.apply('css'))`. `createDefaultWebpackConfig` is already async.

**Comment by BPScott** [comment]
> Where do we stand on options to turn features on vs just a preset that you have to install?

I kinda alluded to this in #11961

> [`preset-scss`](https://github.com/storybookjs/presets/tree/master/packages/preset-scss) exists, and there [are docs for defining custom webpack config](https://storybook.js.org/docs/react/configure/webpack#extending-storybooks-webpack-config), however these still put the burden of implementation onto storybook users. Storybook has already decided that telling folks "use the typescript preset" is still too much to teach, so does the same ring true for "use the scss preset"?
>
> "If you use framework X, then use the storybook preset for framework X" is a reasonable argument for app that use a framework, however that doesn't address when you're writing a component library decoupled from an app framework.

To me it feels like with TS support being built-in and the addition of addon-essentials Storybook is leaning towards an "it works out the box" approach for super common configurations. II'd argue that support for css modules and scss both feel like common enough tech choices to be configurable without needing to install any extra addons.

> The former is nicer for sure but I guess the downside is dependencies that are wasted on users that don't need them (and more maintenance burden, maybe).

This is a concern for other features but I don't think it is an issue here. css-module configuration is exposing config options for an already depended upon loader. Scss support would require the adding a dependency on the `sass-loader` (which is pretty cheap) but wouldn't require a dependency on `sass` if we follow the convention used by frameworks like CRA/next. The "additional context" section of #11961 talks about this. While adding these built-in features does have a slight maintenance burden I think it is outweighed by reducing the education burden - it is easier to teach "if you want css modules / scss then configure this option"  than "you need to go install and configure this addon".

```js
module.exports = {
  stories: ['../stories/*.stories.@(ts|tsx|js|jsx|mdx)'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],
  // This object gets merged into css-loader's options
  css: { 
    modules: true,
  },
  // This object gets merged into sass-loader's options
  sass: {
    // blah
  }
}
```

vs

```js
module.exports = {
  stories: ['../stories/*.stories.@(ts|tsx|js|jsx|mdx)'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],
  styles: {  
    // This object gets merged into css-loader's options
    cssLoaderOptions: { 
      modules: true,
    },
    // This object gets merged into sass-loader's options
    sassLoaderOptions: {
      // blah
    }
  }
}
---

@ndelangen Have you got any thoughts on how you might add configuration for scss support (allowing options to be passed into sass-loader) into that proposed config object? Is adding additional top-level configuration for for that acceptable or would it be preferred to try and keep styles related config under one key?

I'm thinking one key might be a little easier to document on https://storybook.js.org/docs/react/configure/styling-and-css in a similar way to how https://storybook.js.org/docs/react/configure/typescript documents the typescript options. 

I note that the typescript key has a subkey for `reactDocgenTypescriptOptions` so there is already a pattern for naming subkeys that configure webpack plugins/loaders. Keeping some similarity with that feels nice.

**Comment by ndelangen** [comment]
```
module.exports = {
  stories: ['../stories/*.stories.@(ts|tsx|js|jsx|mdx)'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],
  // keys from this object that are accepted by css-loader are passed into css-loader's options
  css: { 
    modules: true,
    sass: {
      // sass loader options, could be just `true` if using defaults
    }
  },
}
```

we could detect main.js > css.sass, and if true, we apply the sass-preset with it's options.

This way users can both use the preset, or have the preset auto-loaded, and we can maintain the preset as a separate thing.

User should have `node-sass` & `@storybook/preset-sass` installed, we'll warn them if they are not installed.

**Comment by darleendenno** [comment]
Closing in favor of supporting css modules using community addons (like SASS, Less, Post-CSS) ❤️

**Pull request closed without merging**
