### PR TITLE
Upgrade react-dev-utils to 12.0.0

### PR DESCRIPTION
**Pull request by Taillook**
Issue: #16093

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by Taillook** [comment]
Oops, disruptive changes...

**Comment by Taillook** [comment]
e2e-teests-pnp and cra-bench is also failed by e7b8c49.

**Comment by Taillook** [comment]
Danger JS
> Command did not finish within the time limit

**Review by shilman — CHANGES_REQUESTED** [review]
Thanks so much @Taillook! 

As far as I can tell `WatchMissingNodeModulesPlugin` is the only thing we use from `react-dev-utils`, so if we're getting rid of that we can just remove the dependency entirely. @ndelangen do you have any thoughts on this?

The snapshot updates are unexpected. Any idea what's going on there?

**Comment by ndelangen** [comment]
@shilman neither the CI failures: https://app.circleci.com/pipelines/github/storybookjs/storybook/22702/workflows/19d86086-b0dd-4f1a-ac6d-f5c0003d0600/jobs/356794

nor the snapshots updates ring any of my bells, I do not know what's causing them.. sorry..

**Comment by Taillook** [comment]
Need to change the WatchMissingNodeModulesPlugin to not use it and upgrade react-scripts to v5.0.0

**Pull request closed without merging**
