### PR TITLE
Added instructions for adding JSON loader

### PR DESCRIPTION
**Pull request by ffxsam**
Storybook was yielding errors out of the box. These steps are critical IMO

### CODE REVIEW

**Comment by arunoda** [comment]
I like this, how about introducing `json-loader` by default. We already disucss this on #261 here. But kind a stop doing this for other workaround.

What do you think?

**Comment by ffxsam** [comment]
If it makes Storybook work out of the box, then I'm all for including it in the package! Ideally, for best developer experience, it should work after installing without extra work on the dev's part.

**Comment by arunoda** [comment]
Yeah agree. We will bring #261

**Comment by arunoda** [comment]
Closing since, now we've json-loader in 2.x

**Pull request closed without merging**
