### PR TITLE
React: Add hooks support to stories

### PR DESCRIPTION
**Pull request by shilman**
Issue: #5721 #6925 #4691 

## What I did

Invoke story function as `React.createElement` in `react` renderer to support hooks in stories.

## How to test

See modified stories in `official-storybook`

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]
AWESOME

**Comment by wilau2** [comment]
Should this fix be in react-native as well? 🤔

**Comment by ndelangen** [comment]
@wilau2 yes that'd be great, perhaps you would like to resolve this bug with @Gongreg's help?

**Comment by Gongreg** [comment]
@wilau2, it would be great if you could create a PR for it :)

**Pull request merged**
