### PR TITLE
Core: Add Rsbuild frameworks to known frameworks

### LINKED ISSUE #51: Creating new stories and saving stories in UI is not currently supported?
After switching to `storybook-rsbuild`, the `Save` functionality in the Storybook UI stopped working:

image

The `+` button to [create a new story](https://storybook.js.org/docs/get-started/whats-a-story#create-a-new-story) is also not available:

image

### PR DESCRIPTION
**Pull request by fi3ework**
Closes https://github.com/rspack-contrib/storybook-rsbuild/issues/51.

## What I did

Add `storybook-react-rsbuild` and `storybook-vue3-rsbuild` to known frameworks, which could make the former being detected as an `react` framework.

### Testing

1. Create an Rsbuild-react project `npm create rsbuild@latest`
2. Add Storybook https://rsbuild.dev/community/releases/v0-7#support-for-storybook
3. Try to use save from controls / add new component UI

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-28694-sha-b28ec221`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-28694-sha-b28ec221 sandbox` or in an existing project with `npx storybook@0.0.0-pr-28694-sha-b28ec221 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-28694-sha-b28ec221`](https://npmjs.com/package/storybook/v/0.0.0-pr-28694-sha-b28ec221) |
| **Triggered by** | @shilman |
| **Repository** | [fi3ework/storybook](https://github.com/fi3ework/storybook) |
| **Branch** | [`patch-3`](https://github.com/fi3ework/storybook/tree/patch-3) |
| **Commit** | [`b28ec221`](https://github.com/fi3ework/storybook/commit/b28ec221b8ad74f9140bc1bdf58580b28d856d9e) |
| **Datetime** | Sun Aug 11 19:42:52 UTC 2024 (`1723405372`) |
| **Workflow run** | [10342303731](https://github.com/storybookjs/storybook/actions/runs/10342303731) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=28694`_
</details>

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  76.3 MB | 76.3 MB | 0 B | 0.57 | 0% |
| initSize |  169 MB | 169 MB | 869 B | **1.24** | 0% |
| diffSize |  92.6 MB | 92.7 MB | 869 B | **1.24** | 0% |
| buildSize |  7.46 MB | 7.46 MB | 0 B | 1.23 | 0% |
| buildSbAddonsSize |  1.61 MB | 1.61 MB | 0 B | **1.28** | 0% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  2.3 MB | 2.3 MB | 0 B | 1.21 | 0% |
| buildSbPreviewSize |  351 kB | 351 kB | 0 B | -0.46 | 0% |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  4.46 MB | 4.46 MB | 0 B | 1.23 | 0% |
| buildPreviewSize |  3 MB | 3 MB | 0 B | 1.22 | 0% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  18.7s | 15.2s | -3s -489ms | -0.04 | -22.8% |
| generateTime |  20.8s | 20.5s | -279ms | 0.15 | -1.4% |
| initTime |  19.3s | 17.2s | -2s -85ms | -0.25 | -12.1% |
| buildTime |  11.4s | 12.5s | 1s | 0.15 | 8.5% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  8.2s | 6.5s | -1s -699ms | -1.19 | -25.9% |
| devManagerResponsive |  5.4s | 4.4s | -1s -57ms | -0.99 | -24% |
| devManagerHeaderVisible |  816ms | 1s | 278ms | **3.38** | 🔺25.4% |
| devManagerIndexVisible |  863ms | 1.1s | 273ms | **3.25** | 🔺24% |
| devStoryVisibleUncached |  1.5s | 1.2s | -346ms | -0.55 | -27.6% |
| devStoryVisible |  875ms | 1.1s | 263ms | **3.03** | 🔺23.1% |
| devAutodocsVisible |  684ms | 728ms | 44ms | -0.16 | 6% |
| devMDXVisible |  695ms | 650ms | -45ms | -0.89 | -6.9% |
| buildManagerHeaderVisible |  857ms | 725ms | -132ms | -0.29 | -18.2% |
| buildManagerIndexVisible |  866ms | 726ms | -140ms | -0.34 | -19.3% |
| buildStoryVisible |  963ms | 796ms | -167ms | -0.01 | -21% |
| buildAutodocsVisible |  774ms | 635ms | -139ms | -0.83 | -21.9% |
| buildMDXVisible |  723ms | 611ms | -112ms | -0.73 | -18.3% |

### CODE REVIEW

**Review by alcpereira — APPROVED** [review]

**Review by shilman — COMMENTED** [review]
@fi3ework thanks for the PR! `react`/`vue3` are renderers not frameworks, so you'll probably need to add `react-rsbuild` and `vue3-rsbuild` to the list of `SupportedFrameworks`, etc.

**Comment by fi3ework** [comment]
> @fi3ework thanks for the PR! `react`/`vue3` are renderers not frameworks, so you'll probably need to add `react-rsbuild` and `vue3-rsbuild` to the list of `SupportedFrameworks`, etc.

Thanks for hinting. I used to open the PR in github.dev so sorry for missing modifying others. There's one place blocking me here https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/helpers.ts#L141-L159. Since Rsbuild builder is either of the two core builder, there seems no way to change the code under the current code premise.

**Comment by jeffijoe** [comment]
@shilman any guidance for which core builder to use? Maybe `webpack` since Rspack is based on Webpack's API?

**Comment by shilman** [comment]
@fi3ework @jeffijoe Sorry for the slow response. AFAICT that constant `frameworkToDefaultBuilder` is only used in one place, which is here https://github.com/storybookjs/storybook/blob/next/code/lib/cli-storybook/src/automigrate/fixes/webpack5-compiler-setup.ts#L59-L70

I'm unsure if that code even needs updating, since it's purpose is to migrate from older versions of Storybook to post-8.0 conventions. And these Rsbuild frameworks are presumably 8.0+. But if it was necessary to include the new frameworks, I would probably change the type like this:

```ts
- export const frameworkToDefaultBuilder: Record<SupportedFrameworks, CoreBuilder> = {
+export const frameworkToDefaultBuilder: Record<SupportedFrameworks, CoreBuilder | string> = {
```

**Comment by fi3ework** [comment]
Thank you, @shilman, for the kind suggestion. I have updated the code.

**Review by shilman — APPROVED** [review]
That's even nicer. Thanks @fi3ework !!

**Comment by shilman** [comment]
@fi3ework @jeffijoe I've released a canary at `0.0.0-pr-28694-sha-b28ec221`. Mind testing it out to verify that it works as expected?

**Comment by jeffijoe** [comment]
@shilman just tested it, everything works and the `+` button to create new stories for components also works! Great work, thank you! 🙏

**Pull request merged**
