### PR TITLE
Addon-docs Props: Convert default prop value to string

### PR DESCRIPTION
**Pull request by atanasster**
Issue: #9394

## What I did
- check if the "summary" prop (used for default value) has a toString method and use it to convert to string. 
- added a boolean prop with default value to Button.tsx in cra-ts-kitchen-sink

## How to test

use cra-ts-kitchen-sink

### CODE REVIEW

**Review by shilman — APPROVED** [review]
@atanasster 🙌

**Comment by shilman** [comment]
@patricklafrance @tmeasday Can you think of any places where this would cause problems?

**Comment by patricklafrance** [comment]
I don't think so.

That being said, why doing this in the components instead of the code that transform react-docgen data code to display data?

Feels hacky.

Should also be done in a dedicated TypeScript transformation pipeline since it only happens for TS.

**Comment by patricklafrance** [comment]
BTW I believe settings react-docgen-typescript `savePropValueAsString` prop to true would be a better fix:

https://github.com/styleguidist/react-docgen-typescript#parseroptions

**Comment by atanasster** [comment]
@patricklafrance thanks for the feedback

Here are a few thoughts on my side
- react-docgen-typescript can be installed manually, or a different tool could be used (rumors are react-docgen 5 would support typescript)
- the PropValue component is the place where the value is needed as string, seems to me correct place to ensure it is actually converted to a string
- i think we should leave proptables as is, and allow them to be used by other code - ie the knobs-2 addon could use the prop tables

**Comment by patricklafrance** [comment]
Hey @atanasster

You’re right the PropValue is a correct place to ensure it’s a string. What I don’t like about it is that currently all the code that take care of these concerns is in the data transformation layer, not in the rendering layer. This is splitting the same concern in 2 places which makes the code harders to maintain if we continue this way.

A future refactor in 6.0 might change this, but in the current state, this is out it’s been built.

**Comment by atanasster** [comment]
Thanks @patricklafrance - you are right, lets work on refactoring that part for 6?

**Pull request merged**
