### PR TITLE
UI: Remove `nopreview` and show redbox for any story error

### PR DESCRIPTION
**Pull request by tmeasday**
## What I did

Some errors don't have a meaningful stack trace -- for those we include some debugging instructions in the error message. 

This has the side effect of fixing the flaky chromatic snapshot.

Here is the full set of errors a user can see (would be great to figure out how to get stories for these):

### Empty storybook

Pasted Graphic 4

### Missing story id on startup

Pasted Graphic

### Story removed (missing story id after HMR)
Pasted Graphic 1

### CSF file throws error (but valid enough to allow you to select the story)

Pasted Graphic 2

### Direct access to iframe without selection

Pasted Graphic 3

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Amazing job @tmeasday !!! 💯

**Review by shilman — CHANGES_REQUESTED** [review]
Chromatic error 😭

**Comment by tmeasday** [comment]
Backed out the final change as it was tripping up chromatic.

**Review by shilman — APPROVED** [review]
Really nice change Tom! Slow clap
👏    👏     👏      👏

**Pull request merged**
