### PR TITLE
Added error message for missing or invalid storyName

### PR DESCRIPTION
**Pull request by danielduan**
Issue: #722 

Added a check for storyName type to catch missing or invalid storyName.

### CODE REVIEW

**Comment by ndelangen** [comment]
Don't mind the failing build, nodejs.org seems to be having difficulties.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Thanks for the PR!

**Review by thani-sh — APPROVED** [review]

**Comment by mnmtanish** [comment]
LGTM 👍

**Comment by ndelangen** [comment]
last rebase, I'll merge it this time.

**Pull request merged**
