### PR TITLE
add codemod for deprecated addon-links and addon-actions from app

### PR DESCRIPTION
**Pull request by kebot**
Issue:

Part of https://github.com/storybooks/storybook/issues/1268

## What I did

add a Codemod to help developers easily migration to v3.0

## How to test

You can play around the codemod here:
https://astexplorer.net/#/gist/0f953dcda14eaed7df453ead00a25479/318680017de50a980ff95bd83c310bbb58631090

### CODE REVIEW

**Comment by UsulPro** [comment]
Thanks @kebot! 
But looks like we have migration tool here: https://github.com/storybooks/storybook/blob/master/lib/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index.js
(see [MIGRATION.md](https://github.com/storybooks/storybook/blob/master/MIGRATION.md#packages-renaming))
Could you check is this feature already included in it?

**Comment by tmeasday** [comment]
I think @ndelangen and @aaronmcadam wrote the original codemod, so they can correct me if I am wrong, but my understanding is that it just changes the names of the packages you import from, rather than any code changes like @kebot proposes here.

This looks great!

**Comment by ndelangen** [comment]
This is fantastic!!! 
Sorry this went unnoticed by me for so long, my github notifications are a mess 😓

**Review by ndelangen — APPROVED** [review]
I love the tests mate, WOW!

**Comment by ndelangen** [comment]
I'm missing some documentation on this change, do you think you can add it? 

If not, that's ok, I can write something then, thank you @kebot

**Comment by ndelangen** [comment]
@aaronmcadam Do you have some thoughts on how to enable this from the CLI?

**Comment by aaronmcadam** [comment]
I don't know how the CLI works @ndelangen, I've not had a chance to look at it. Would it make sense to add this as an extra step in the codemod we already have?

**Comment by tmeasday** [comment]
We may as well continue in the pattern from 3.0 and make `getstorybook` run the latest set of codemods if you already have storybook installed when you run it? 

We may need to update the CLI to understand which codemods have been run before (maybe it just looks at storybook version before and after), but it seems sensible?

**Pull request merged**
