### PR TITLE
Core: Replace calls to `getElementById` by id check

### PR DESCRIPTION
**Pull request by gaetanmaisse**
Issue: #16862

## What I did

Use id check instead of checking the whole element to find if story should be in `story` or `docs` mode

This has 2 benefits:
 - avoid some calls to `document.getElementById`
 - fix weird behaviours with some frameworks (Vue + SFC for instance) where the `canvasElement` wasn't populated yet when the first check was done. Causing `viewMode` to be wrong when loaders are applied - This was the root cause of E2E tests failure for sfcVue

## How to test

- [ ] sfcVue e2e tests should be back to 🟢 
- [ ] Everything else on CI  should be still 🟢

### CODE REVIEW

**Comment by tmeasday** [comment]
@gaetanmaisse thanks for investigating. I think this for this issue that @yannbf posted: https://github.com/storybookjs/storybook/issues/16862

**Comment by tmeasday** [comment]
However, I think this solution shifts the problem to docs mode, because when `vue` does `prepareForInline` it also creates an element with `id=root`: https://github.com/storybookjs/storybook/blob/08301a37b07f94dcbf272fdebd73864eb8e03639/addons/docs/src/frameworks/vue/prepareForInline.ts#L32-L33

**Comment by gaetanmaisse** [comment]
You're 💯  right @tmeasday I didn't investigate on docs side as it was the working part 😂 

@shilman do you remember why we have this `root` id there? It's the case only for Vue so I would say we could remove?
 https://github.com/storybookjs/storybook/blob/08301a37b07f94dcbf272fdebd73864eb8e03639/addons/docs/src/frameworks/vue/prepareForInline.ts#L32-L33

**Comment by shilman** [comment]
@gaetanmaisse I don't remember why it's `#root` ... try changing and see if it works?

**Comment by backbone87** [comment]
I can't remember writing this line with the comparison. I haven't worked with storybook 6 yet, so Code related to docs mode is most likely not from me

**Comment by tmeasday** [comment]
@backbone87 I wrote the comparison :) I think @shilman is just asking about:

> `   return h('div', { attrs: { id: 'root' } }, children); `

**Comment by tmeasday** [comment]
Thanks for putting me on the right track here @gaetanmaisse. Closing in favour of a more explicit solution: https://github.com/storybookjs/storybook/pull/16919

**Pull request closed without merging**
