### PR TITLE
Addon-interactions: Fix IE support by replacing array includes

### PR DESCRIPTION
**Pull request by JonathanKolnik**
Refactored a piece of logic introduced in #18706 so that it is compatible to run in Internet Explorer.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
@JonathanKolnik we can probably still use optional chaining because that will get transpiled by babel. The `includes` => `indexOf` change should be sufficient, right?

**Comment by dartess** [comment]
I'm confused - storybook@7 will continue to support IE11, or is this a request for the current version?

**Comment by shilman** [comment]
@dartess this got patched back to 6.5, so it's supposed to fix that. but actually @JonathanKolnik since this change is only for 6.5 this is kind of a special case and can you please target `main-prerelease` instead?

**Review by shilman — APPROVED** [review]
LGTM!!

**Pull request merged**
