### PR TITLE
[Addon-Knobs] Fixed addon for RN

### PR DESCRIPTION
**Pull request by Gongreg**
## Issue:  #1586 Addon-knobs wasn't working on React Native

After cleanup done in https://github.com/storybooks/storybook/commit/4c1daabf50f0c9fb9d789ba3d40ca37d154445e7 addon wasn't breaking RN (since channel is not set while user is not connected to between app and browser).

## What I did

Pretty much reverted the change back.

## How to test

Adding knob examples to crna and react-vanilla-apps in a separate pr.

### CODE REVIEW

**Review by danielduan — APPROVED** [review]

**Comment by danielduan** [comment]
is there anything preventing us from merging this? would love to get this into the next patch release.

**Comment by ndelangen** [comment]
Code LGTM, maybe @tmeasday wants to veto this and merge?

**Comment by tmeasday** [comment]
I don't really understand @Gongreg's [comment](https://github.com/storybooks/storybook/pull/1635#issue-249267124). 

Are you saying that it was broken after the refactor and this fixes it? And what do you mean about the channel? (sorry too many negatives in the sentence, I can't parse it ;) )

**Comment by Gongreg** [comment]
@tmeasday, Yes, I mean it broke after refactor and this commit fixes it.

By channel I mean that in RN app the channel is not instantly set. See this code:

app/react-native/src/preview/index.js

```
getStorybookUI(params = {}) {
    return () => {
      let webUrl = null;
      let channel = addons.getChannel();
      if (params.resetStorybook || !channel) {
        const host = params.host || parse(NativeModules.SourceCode.scriptURL).hostname;
        const port = params.port !== false ? `:${params.port || 7007}` : '';

        const query = params.query || '';
        const secured = params.secured;
        const websocketType = secured ? 'wss' : 'ws';
        const httpType = secured ? 'https' : 'http';

        const url = `${websocketType}://${host}${port}/${query}`;
        webUrl = `${httpType}://${host}${port}`;
        channel = createChannel({ url });
        addons.setChannel(channel);
      }
      channel.on('getStories', () => this._sendSetStories());
      channel.on('setCurrentStory', d => this._selectStory(d));
      this._events.on('setCurrentStory', d => this._selectStory(d));
      this._sendSetStories();
      this._sendGetCurrentStory();

      // finally return the preview component
      return params.onDeviceUI
        ? <OnDeviceUI stories={this._stories} events={this._events} url={webUrl} />
        : <StoryView url={webUrl} events={this._events} />;
    };
  }
```

And after refactor the code `addons.getChannel()` existed in global scope so it was required before channel was set. It is difficult to explain, but we have to require channel only before sending event in it, not at the start of the program.

**Comment by tmeasday** [comment]
Thanks for that @Gongreg, yes it makes perfect sense to me (cf https://github.com/storybooks/storybook/issues/1191)! I just was making sure I understood what you were saying correctly.

I haven't had a chance to test this but the code changes make sense to me.

**Comment by Gongreg** [comment]
I also added examples in #1636 for RN, so at least we could see in future if it stops working. But the pr checks screams to me about code duplication. I just have other priorities atm to fix it.

**Comment by ndelangen** [comment]
Either of you want to merge this then? @Gongreg @tmeasday

**Pull request merged**
