### PR TITLE
Use HtmlWebpackPlugin to import all assets (importing chunks in order)

### PR DESCRIPTION
**Pull request by thomasbertet**
Issue: https://github.com/storybooks/storybook/issues/1411

## What I did
- Removing manuel insertion of assets inside a index/iframe.html template.
- Use HtmlWebpackPlugin to import in correct order all chunks.

## How to test
- Have a build with multiple split points, everything should be loaded in order.

Is this testable with jest or storyshots?
Not sure how yet.. will do.

Does this need a new example in the kitchen sink apps?
No.

Does this need an update to the documentation?
No.

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by ndelangen — COMMENTED** [review]
Code looks good to me, 

Should we add this behavior to the cra-kitchen-sink to make sure it actually works?

The unit tests for this tests only a really small part of the puzzle. A huge portion is inside webpack, and we'd like to verify it works, not just know the order is correct.

cc @tmeasday @Hypnosphi @shilman

**Comment by Hypnosphi** [comment]
I agree.
@thomasbertet please add a custom webpack config for `examples/cra-kitchen-sinks` which will, for example, create a separate vendor chunk

**Comment by thomasbertet** [comment]
Fine by me, will add =) I'll let you know.

**Comment by thomasbertet** [comment]
@Hypnosphi after some digging around CRA, we cannot split bundles yet  https://github.com/facebookincubator/create-react-app/issues/2206 (at least, not using the webpack-like config). Meaning, splitting vendors & app cannot be done. Correct me if I'm wrong! 

I may need then to set some split points inside the code of cra-kitchen-sinks, WDYT ? This way I will be able to give it a name (using the magic comment of webpack import syntax) ang test some cases.

**Comment by Hypnosphi** [comment]
I mean, for storybook, not for app

**Comment by thomasbertet** [comment]
Ok then, here is my findings: 

- When you have split points in **your app**, you need to load them **after** `preview.bundle.js` (preview contains webpack's bootstrapping)
- When you use CommonsChunkPlugin in **.storybook/webpack.config.js** to extract, say, a "vendor" bundle,  then you will want to load it **before** `preview.bundle.js`.  (vendor contains webpack's bootstrapping)

These two use cases could not be solved using the quick fix in this PR in its current state. 
We might want to add extra sorting to assets so that they are inserted in the correct order depending on the dependency graph. 

When using the statsJson, the https://webpack.js.org/api/stats/#chunk-objects has a `parent` prop we can use to reorder correctly the chunks.

Maybe we should consider adding a similar logic as HtmlWebpackPlugin there: https://github.com/jantimon/html-webpack-plugin/blob/master/lib/chunksorter.js ? 

Please correct me if I'm misunderstanding something, any help appreciated :+1: 

Also, maybe @SpaceK33z you might want to give us a thought as its webpack's related  :)

Thanks!

**Comment by SpaceK33z** [comment]
Hi, this part of webpack is not my area of expertise, but what I can say is that in webpack 4 the order should not matter anymore (source, ctrl+f on 'pure jsonp'). But I realize this will take some time so for now this info is useless 😆.

**Comment by Hypnosphi** [comment]
> Maybe we should consider adding a similar logic as HtmlWebpackPlugin

Maybe we should consider just using the plugin =)

**Comment by thomasbertet** [comment]
@Hypnosphi I implemented a solution to this with HtmlWebpackPlugin. 

I tried my best with the little knowledge I have from the codebase to not break anything. 

Could you find the time to try it, and guide me through where I can create test cases to improve this PR ? 

Thanks in advance !

**Comment by ndelangen** [comment]
I like where this is going! Great work @thomasbertet

**Comment by Hypnosphi** [comment]
Works great! Please make the same chages to `app/vue` (yeah, the duplication isn't cool, but it's kinda by design as far as I know)

**Comment by thomasbertet** [comment]
Thanks @ndelangen ! Really appreciate this :-) 
It feels good to finally help improve storybook.

Will definately do the same for vue. Thanks @Hypnosphi !

**Comment by thomasbertet** [comment]
@Hypnosphi I added it for vue as well. 

Ready to take it to the next level, please let me know if I need to do something else.

**Comment by ndelangen** [comment]
I will test this now.

**Review by ndelangen — APPROVED** [review]
Tested the regular and static build for cra and vue, works great!

I added a custom webpack config with a vendor chunk for vue too.

**Comment by Hypnosphi** [comment]
@ndelangen should we probably merge it into `release/3.3` not `master`?

**Review by Hypnosphi — APPROVED** [review]
LGTM

**Comment by shilman** [comment]
I noticed changes for react/vue but not for RN, which also has a very similar webpack/preview setup (in addition to the device side of things). Do we need to change RN as well?

**Comment by Hypnosphi** [comment]
@shilman As far as I understand, RN app doesn't have a concept of manager/preview entries

**Comment by ndelangen** [comment]
@thomasbertet I think we should try to keep the apps in sync as much as possible.

Do you want to bring these changes to the RN app as well? Or do you want me to do it?

**Comment by thomasbertet** [comment]
Sure I can try.

Just to be certain, we would like all of them to use the same files, right
? As @Hypnosphi mentioned, is it a design we would like to keep ?

Thanks !

**Comment by ndelangen** [comment]
After Angular app has been merged in, we will be refactoring out most of the duplication.

So no it's not our goal to keep it exactly like this; though it's also not a goal to abstract away all forms of duplication. Nothing hurts a codebase more than early abstraction.

**Comment by thomasbertet** [comment]
@ndelangen this is it =) I added the same behavior for RN & the CRNA example.

**Comment by ndelangen** [comment]
I will test it @thomasbertet, you're awesome! 💪

**Comment by ndelangen** [comment]
Tested both the crna-example and the react-native-vanilla ✅

**Comment by thomasbertet** [comment]
Great ! Thanks @ndelangen :+1:

**Comment by ndelangen** [comment]
Congrats @thomasbertet !

I hope more PRs like this will follow! 🙇

**Pull request merged**
