### PR TITLE
CSF: Autotitle fix multiple dots and handle stories.js

### PR DESCRIPTION
**Pull request by agriffis**
Note: This is easier to review the two commits in sequence rather than all changes simultaneously. In particular the commit messages may be helpful.

Also, it's possible you'll prefer separate pull requests for the fix and feature, but I'm lazy and taking my chances.

## What I did

Fix an auto-titling bug when the filename contains multiple dots, for example `button.group.stories.js` would dumb down to `button`

Handle `stories.js` as a meaningless filename for auto-titling, similarly to `index.stories.js`

## How to test

Added new tests for both the fix and the feature.

## Why this matters to me

I prefer `stories.tsx` rather than `index.stories.tsx` to avoid tab-completion ambiguities. But I'd also like to use auto-titling.

I found the bug while auditing the code prior to adding the feature.

Ideally, I think we'd be able to supply an `autoTitle` function in the storybook config for customization, but that's a higher bar because of figuring out the best API, updating docs, etc.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by ndelangen — CHANGES_REQUESTED** [review]
Can you add some tests with windows paths?

**Comment by agriffis** [comment]
@ndelangen I'm just getting back to this after a long time.

I'm not sure this really needs a separate test on Windows, but I added one for completeness. Let me know what you think. Thanks!

**Comment by ndelangen** [comment]
@valentinpalkovic could you have a look at this? 🙏

**Comment by agriffis** [comment]
@valentinpalkovic This had fallen out of date, so I rebased it to the latest `next`. Do you think you'll have a chance to look at it soon?

**Comment by agriffis** [comment]
Rebased again and tweaked considering #23852

**Comment by agriffis** [comment]
@ndelangen @valentinpalkovic Did this get lost/forgotten?

**Comment by yannbf** [comment]
Hey @agriffis sorry about that! We are currently very busy (and some of us are on vacation) so it might take us time to go through the PRs.
Would you mind updating the branch with the latest from `next` and fixing CI? Some steps like unit tests and linting are failing. Once you're done, please ping Norbert. Thank you!

**Comment by ndelangen** [comment]
I updated the branch for you. Please reach out if you need assistance resolving the unit tests / linting problems.
Thank you @agriffis 🙏

**Comment by agriffis** [comment]
@ndelangen @yannbf I rebased to next and added an additional commit for the fix, along with an additional unit test.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I think this looks good, but will defer to either @shilman or @JReinhold to approve and merge this.

**Comment by valentinpalkovic** [comment]
Reminder @JReinhold, @shilman

**Comment by agriffis** [comment]
I hope it's okay to ping here. This PR seems relatively small, and I'd love to see it merged rather than languish.

**Review by shilman — APPROVED** [review]

**Comment by shilman** [comment]
@agriffis thanks for making this & for your patience on getting it merged! the change looks good to me, but it's also a technically breaking change -- you can see this from our chromatic changes where we see filenames like `attribute-selectors.component.stories.ts` result in new stories. i'm going to give the core team a chance to object & otherwise we'll merge this as a breaking change for 8.0. thank you!!! 🙏

**Review by yannbf — APPROVED** [review]

**Comment by yannbf** [comment]
@shilman can you review the Chromatic changes? This definitely affected the angular sandboxes, and for the Storybook UI there were big naming changes that I don't know if it's related to this PR.

**Comment by shilman** [comment]
Good catch @yannbf -- I looked at the Angular changes which look good. But the UI storybook changes looks like a regression.

**Comment by ndelangen** [comment]
@shilman Can we proceed with this PR?

**Pull request merged**
