### PR TITLE
updated npm broken link issue documentation #6556

### LINKED ISSUE #6556: Readme Images on NPM broken across the board
**Describe the bug**
README images are broken across the board.
(see https://github.com/storybooks/storybook/issues/1196)

**To Reproduce**
1. Go to https://www.npmjs.com/package/@storybook/addon-actions
2. Go to https://www.npmjs.com/package/@storybook/addon-storyshots

image

**Additional context**
There's a difference in the source paths between images that resolve and images that don't resolve.  I'm not fluent on how `github.com/path/image.png` becomes `raw.githubusercontent.com/path/image.png`, it may just be pending a publish -- i dont know. 

Regardless, it makes everything feel broken.

Image path from npm's addon-actions (as example):
`https://raw.githubusercontent.com/storybooks/storybook/HEAD/docs/screenshot.png`

Manually altered path:
`https://raw.githubusercontent.com/storybooks/storybook/HEAD/addons/actions/docs/screenshot.png`

### PR DESCRIPTION
**Pull request by rajatrao777**
Updated link  in readme files for displaying across npm
1)https://www.npmjs.com/package/@storybook/addon-actions
2)https://www.npmjs.com/package/@storybook/addon-storyshots
Let me know if any doubts.
Fixed #6556
Thanks

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Thank you @rajatrao777 ! 🙏

**Comment by rajatrao777** [comment]
No problem , most welcome.
Just wanted to get an idea when it will be reflected to npm pages?

**Comment by shilman** [comment]
Maybe next time I publish the packages? I'm not sure how it works tbh

**Comment by rajatrao777** [comment]
Oh cool.. :D

**Pull request merged**
