### PR TITLE
UI: Fix Brand anchor width

### PR DESCRIPTION
**Pull request by k-utsumi**
## What I did

Fix Brand anchor width.

<kbd> image

There are probably several solutions.
For example, changing [Heading maxWidth](https://github.com/storybookjs/storybook/blob/3c645b5271453f277cf7d6bbeb1d688eea72ec6f/code/ui/manager/src/components/sidebar/Heading.tsx#L34).

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

I tried it on [React demo v8.0.6 page](https://next--630511d655df72125520f051.chromatic.com/?path=/docs/configure-your-project--docs).

1. View react demo page
2. Change style

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by yannbf** [comment]
Thanks a lot for your contribution @k-utsumi ! @cdedreuille would you mind checking this out?

**Comment by cdedreuille** [comment]
I'm not sure what you are trying to solve here. Changing max-width to `100% + 8px` doesn't seems like a great solution to me. What is exactly the issue here?

**Comment by k-utsumi** [comment]
It's difficult to explain...

1. **BrandArea** is the space with **red background** (`#f003`)
2. **Anchor** inside the BrandArea is a space with a **blue background** (`#f003`)

<kbd> image

I think the size of the anchor inside the BrandArea is inappropriate.
If put text inside an anchor, it will wrap rather quickly and look uncomfortable.

<details>
<summary>Related code</summary>

https://github.com/storybookjs/storybook/blob/3c645b5271453f277cf7d6bbeb1d688eea72ec6f/code/ui/manager/src/components/sidebar/Heading.tsx#L20-L39
</details>

**Comment by k-utsumi** [comment]
In more detail,
BrandArea content is not aligned with the left and right button below,  
I would like it to look like this.

<kbd> image

**Pull request closed without merging**
