### PR TITLE
Next.js: Support disableStaticImages setting

### LINKED ISSUE #22899: [Bug]: @storybook/nextjs does not respect disableStaticImages flag in next.config.js
### Describe the bug

NextJs has an option to `disableStaticImages` in case a user wants to use an images string directly, instead of using the object.  That is the way we have our front-end app setup.  However with the latest update to storybook v7 using `@storybook/nextjs` that flag is not respected when we pass in the `next.config.js` file

```typescript
    framework: {
        name: "@storybook/nextjs",
        options: {
            nextConfigPath: path.resolve(__dirname, "../next.config.js"),
        },
    },
```

### To Reproduce

Here is an MVC repository to reproduce:
https://github.com/joebImagine/disablestaticimages_experiment

- first run yarn
- fire up the app `yarn dev`
- fire up storybook  `yarn storybook`
- notice that the image shows in the app, but is broken in storybook

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/22899

## What I did

Support [disableStaticImages](https://nextjs.org/docs/pages/api-reference/components/image#disablestaticimages) setting in Next.js-based Storybooks.

## How to test

- Create a Next.js sandbox
- set the setting like described here: https://nextjs.org/docs/pages/api-reference/components/image#disablestaticimages
- Importing an image like `import asset from './asset.jpg'` shouldn't return an object anymore, but a plain string instead, which can be passed to an `` element.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
LGTM!

**Comment by ssijak** [comment]
Very much interested in this. What is the expected timeline for this being available on npm?

**Comment by KseniaAK** [comment]
Hi! Thank you for working on this fix! My team is also very interested in this work as it's a blocker for our app's upgrade to storybook v7. Seconding the above question - what is the timeline for its release?

**Comment by valentinpalkovic** [comment]
Hi @ssijak, @KseniaAK Hopefully the next few days we can release this feature with a next 7.1 beta release!

**Pull request merged**
