### PR TITLE
CSF3: Normalize windows paths in autoTitle

### PR DESCRIPTION
**Pull request by yngvebn**
Issue:

## What I did

In order for autoTitle to work on windows, the paths needs to be normalized into unix-style paths

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
@yngvebn there's some problem with IE in this PR. is that something you can debug? cc @ndelangen @tooppaaa 

https://www.chromatic.com/build?appId=5def62c97bd45f0020ef370e&number=9053

**Comment by yngvebn** [comment]
> @yngvebn there's some problem with IE in this PR. is that something you can debug? cc @ndelangen @tooppaaa
> 
> https://www.chromatic.com/build?appId=5def62c97bd45f0020ef370e&number=9053

Let me have a look

**Comment by yngvebn** [comment]
A recap from discussions on Discord:

I've added a tiny package (https://www.npmjs.com/package/slash) for normalizing paths. At first I added the most recent version (4). This was a pure ESM module, and all the jest tests failed with ESM related errors. Upgrading to an older version made those errors go away, but now there seems to be problems with the bundling of this module:

So, I couldn't understand why this was happening on my branch... Seems the IE problem is not only on my branch... I checked a couple of the other netlify urls from different PRs, and they all fail with the same errors... :/
it does seem like it's related to some Angular modules not being transpiled down for IE11
However, for the cra-ts-essentials storybook, it's once again transpiling of slash that's missing
So what's odd, is that the vendor.js for cra-ts-essentials is not transpiling the slash-library, but the vendor.js for the angular-cli does.

```
// Angular cli vendor.js:
function(module, exports, __webpack_require__) {
    "use strict"; __webpack_require__("../../node_modules/core-js/modules/es.string.replace.js"), __webpack_require__("../../node_modules/core-js/modules/es.regexp.exec.js"),
        module.exports = function (path) {
            var isExtendedLengthPath = /^\\\\\?\\/.test(path),
                hasNonAscii = /[^\u0000-\u0080]+/.test(path);
            return isExtendedLengthPath || hasNonAscii ? path : path.replace(/\\/g, "/")
        }
}

// cra-ts-essential vendor.js:

function(module, exports, __webpack_require__) {
    "use strict";
    module.exports = path => {
        const isExtendedLengthPath = /^\\\\\?\\/.test(path),
            hasNonAscii = /[^\u0000-\u0080]+/.test(path);
        
        return isExtendedLengthPath || hasNonAscii ? path : path.replace(/\\/g, "/")
    }
}
```
so, on the latter, IE is obviously kicking it on the path =>  arrow function

**Comment by tooppaaa** [comment]
Hey @yngvebn, sorry about the delay.
I pushed a fix for es6Transpiler on your branch. Can I let you take over on your actual fix ? :)

@shilman, I'll update addon-ie11 as well

**Comment by yngvebn** [comment]
> Hey @yngvebn, sorry about the delay.
> 
> I pushed a fix for es6Transpiler on your branch. Can I let you take over on your actual fix ? :)
> 
> 
> 
> @shilman, I'll update addon-ie11 as well

Amazing, thanks! Yeah, I'll get the rest sorted 👍😊

**Comment by yngvebn** [comment]
@tooppaaa is the addin-ie11 the reason for the failing IE11 stories?

**Comment by tooppaaa** [comment]
I'll have a look.

**Comment by tooppaaa** [comment]
Looks like IE 11 is back on track. I'm not sure about the failing unit test though

**Comment by shilman** [comment]
Thanks @tooppaaa !! And thanks @yngvebn for putting this together!!

**Comment by yngvebn** [comment]
> Looks like IE 11 is back on track. I'm not sure about the failing unit test though

Thank you! :D

**Pull request merged**
