### PR TITLE
upgrade nx to add support for darwin-x64

### PR DESCRIPTION
**Pull request by chakAs3**
Closes #

all sandboxes  were breaking on Mac  darwin-x64

## What I did

add nx-darwin-x64 , and upgrade nx to minimum version to support that.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by mandarini** [comment]
If you need any help moving over to Nx 16, let me know! :)

**Comment by chakAs3** [comment]
> If you need any help moving over to Nx 16, let me know! :)

Hi @mandarini  i tried to run the migration to latest, but it is failing 
```/bin/sh: /var/folders/kv/y2txhjh11gs29bdg0blspbcr0000gr/T/tmp-2694-0wuo1SwrR1j6/node_modules/.bin/nx: No such file or directory```

**Comment by chakAs3** [comment]
> @chakAs3 oh I see. How can I reproduce this?

i'm not sure of how we should migrate but this is the steps:

`git clone git@github.com:storybookjs/storybook.git`
`cd code`
`yarn & yarn nx migrate lastest`

i get this 
```/bin/sh: /var/folders/kv/y2txhjh11gs29bdg0blspbcr0000gr/T/tmp-2694-0wuo1SwrR1j6/node_modules/.bin/nx: No such file or directory```

**Comment by mandarini** [comment]
@chakAs3 ok thanks! I'll take a look either later today or first thing on Monday! :D

**Pull request merged**
