### PR TITLE
only connect to serverChannel in development mode

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

I made it so the manager frame only attempts to connect to the serverChannel in development-mode.

### CODE REVIEW

**Review by tmeasday — COMMENTED** [review]
LGTM. What about the preview side?

**Comment by ndelangen** [comment]
@tmeasday here's what I could find:

https://github.com/storybookjs/storybook/blob/d760a5a4c01a21441b0a22c5cefd71c1ae4899da/code/lib/builder-vite/src/codegen-set-addon-channel.ts#L11

https://github.com/storybookjs/storybook/blob/d760a5a4c01a21441b0a22c5cefd71c1ae4899da/code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars#L15-L17

These 2 places seem unguarded indeed.

**Review by tmeasday — COMMENTED** [review]
OK, LGTM

**Review by tmeasday — APPROVED** [review]
OK, LGTM

**Pull request merged**
