### PR TITLE
add support to postcss

### PR DESCRIPTION
**Pull request by tavoli**
I think it would be interesting to make it possible to use on .svelte files postcss between <style> tags to.

### CODE REVIEW

**Comment by shilman** [comment]
Nice one! I don't think we want to build in postcss to svelte. What I'd propose instead is a preset, e.g. `storybook-svelte-preprocess`, that updates the svelte webpack plugin with the user-specified options.

I'd be happy to help guide you on that if you're interested in going that direction, and helping you promote your work to the Storybook/Svelte communities. LMK what you think.

**Comment by tavoli** [comment]
I would love to help with that. I am also thinking about the documentation component for svelte. Like ([https://storybook.js.org/docs/react/writing-docs/introduction]), this doesn't work for Svelte anymore. Any instructions on how to get started?

**Comment by shilman** [comment]
@tavoli Storybook docs works with Svelte. It can be a lot better though. If you're interested in working on that together, please jump on our Discord https://discord.gg/UUt2PJb and chat me

**Comment by YogliB** [comment]
@shilman I think the best approach would be to set a default preset (I think the present one is fine) and add the ability to configure svelte from a `svelte.config.js` file like it's done with other projects (an example can be seen [here](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/usage.md#with-svelte-vs-code)).

**Comment by phated** [comment]
The `preprocess` config was added in https://github.com/storybookjs/storybook/pull/13900 🎉

**Pull request closed without merging**
