### PR TITLE
WIP - upgrade to webpack 5

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: #9216

### CODE REVIEW

**Comment by gaetanmaisse** [comment]
@ndelangen I will have a few commits to add to this PR to clean things related to Yarn PnP so can you ping me when you think it will be ok for me to do these changes?

**Comment by kirill-konshin** [comment]
Is there any way I can help to speed up this merge? We've migrated to Webpack 5 and only thing that is not migrated is Storybook...

**Comment by shilman** [comment]
@kirill-konshin Don't hold your breath. We're in RC for 6.0 and will re-evaluate this in August after that ships. Since this is a breaking change, the earliest we can merge release as is would be 7.0. However, to support early webpack5 users like yourself and support the evolution of webpack, we could potentially publish an OFFICIAL storybook fork. If you have thoughts on how that could work, that might help us push this along after 6.0 is out.

**Comment by kirill-konshin** [comment]
@shilman thank you for clarification. I'd be happy to be among first adopters, alpha/beta does not matter. Probably a dedicated `dist-tag` would work, just like always.

**Comment by ndelangen** [comment]
We'd be very welcoming to any help you could offer us @kirill-konshin 🙇

**Comment by kirill-konshin** [comment]
> We'd be very welcoming to any help you could offer us @kirill-konshin 🙇

So is there a dist tag that I can take and try?

I only see 

```
% npm info @storybook/react

dist-tags:
latest: 6.0.5      next: 6.0.0-rc.30  
```

How can I install this branch into my project?

**Comment by shilman** [comment]
@kirill-konshin https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md#development-guide

**Comment by kirill-konshin** [comment]
@shilman wrote:
> @kirill-konshin https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md#development-guide

Unfortunately `yarn link` won't work because we have a large team of 40+ engineers and we need to have this running on CI. So `dist-tag` is a must here... I can clone and publish under my own scope, but that's an overkill...

**Comment by shilman** [comment]
@kirill-konshin my point was we typically develop INSIDE the monorepo. once there's something usable, i'd be happy to figure out a way to publish it on some special dist tag so you can dogfood it in your org.

**Comment by kirill-konshin** [comment]
@shilman sure, but I thought it's already in "shippable" state :)

**Comment by ndelangen** [comment]
This branch is not in a shippable state.

**Comment by kirill-konshin** [comment]
Antibot.

**Comment by dudiharush** [comment]
Hi @kirill-konshin,
are you still working on the upgrade to support Webpack 5?

**Comment by kirill-konshin** [comment]
@dudiharush I've put it on hold due to too many errors. I've updated things here and there and got more and more errors, so I just stopped at some point.

**Comment by dudiharush** [comment]
Ok, thanks.

**Pull request closed without merging**
