### PR TITLE
FIX storyshots using the wrong parameter for disabling

### PR DESCRIPTION
**Pull request by tmeasday**
It should be `disable: true` not `disabled: true`.

(I think this was my fault, sorry)

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Is it a breaking change?

**Comment by tmeasday** [comment]
I think this is unreleased, no?

**Review by shilman — APPROVED** [review]
LGTM

**Comment by tmeasday** [comment]
Just to confirm the feature has not yet been released: https://github.com/storybooks/storybook/commit/e0dee7eb5c5b5f93ea41bbd052847d3cac49a105

**Pull request merged**
