### PR TITLE
Add loading stories to various docs components

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: #16051

Docs Page rendered a poor loading state

### What I did

Added some "skeleton" states to some (now) async components.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
## Updated proposal:

docs-loading_1b

I have committed code that:
* Adds a loading spinner state to the `Preview` component
* Adds a loading state for the `ArgsTable`

### Remaining tasks

- [ ] Create a loading state for the `IconButton`
- [ ] Hook all the things up so that the loading state looks like the above screenshot

I attempted to create a loading state for `IconButton` without success. I would like the `IconButtons` used in the `Preview` block to show in a loading state (grey rectangles). I would appreciate help with this. @tmeasday , if you could create a loading state and story similar to what I did with `ArgsTable`, I can do my magic to make it look good. 

Once that is done, you can do your magic so the loading state `Preview` and `ArgsTable` show when the Docs page is loading. It should look pretty close to the above image.

**Comment by tmeasday** [comment]
Thanks @MichaelArestad! Will take a look today, and get back to you.

**Comment by tmeasday** [comment]
Ok, @MichaelArestad here is an update.

 - I added a `IconButtonSkeleton` as you asked.

 - As discussed, I also made an important change - I've made it so within docs, none of the components render async **if they are for a story in the current CSF file**. This is the case for regular `DocsPage`.

Let me try and explain all the loading that can go on and what the situation is right now, as there are a bunch of different things that can happen and it's quite confusing.

---

**Firstly**, when you hit the docs tab, you can either be looking at:
 1. the built in `DocsPage`, which renders all the stories for the *current CSF file*. This is the common case.
 2. a custom docs page, for example if the user uses MDX, which can render just about anything, including stories from other CSF files (this is much more rare, but possible).

**Secondly**, there are three different ways you could reach the docs tab:
 a) you could start there if you boot the storybook at a given URL.
 b) you could go from the stories tab -> docs tab for a given story.
 c) you could be on the docs tab for one story, and then click to a different story in a different component.

**Thirdly**, the things we need to load in order to render a docs view properly are:
 i. The CSF file containing the selected story. We can't do much until we have this because we don't even know what to render.
 ii. The JS bundle that contains the docs runtime (including React if the user isn't using React). This only happens the first time you visit docs.
 iii. The CSF files for any external stories that are included in the docs for custom docs pages.

So, considering the cases (a) -> (c) above, we would have to load:

case (a) [booting on docs] : (i - CSF for current story), (ii - docs runtime), [maybe] (iii - other CSF files)
case (b) [story -> docs] : [maybe] (ii - docs runtime), [maybe] (iii - other CSF files)
case (c) [docs -> docs] : (i - CSF for new story), [maybe] (iii - other CSF files)

OK, phew! that is confusing.

---

So! What should we show when? My proposal, to keep thing (relatively) simple is:

1. While loading (i) or (ii), we should show the "docs skeleton" you've sketched above. This seems fine, the only wrinkle with it is the cases when (ii - docs runtime) is loading, we don't actually have react loaded yet. So we would need to write the HTML+CSS for that skeleton into the base SB `iframe.html` page. Does that sound possible?

2. When loading (iii) [which is rare], render the docs page, but just use loading state as you've already implemented for the doc blocks. Here's an example of what a `<Canvas>` component containing a `<Story>` looks like as it loads right now:

Checkbox
Checkbox

[I'm not sure why the toolbar is there while it is loading but then dissapears, do you know @shilman?]

**Comment by MichaelArestad** [comment]
Thank you for writing this up. That makes sense.

> Does that sound possible?

I think so, but I have not tried yet. I could easily write some CSS/HTML representing the loading state, but I am unsure if any of the theming would work. Taking a look shortly.

**Comment by tmeasday** [comment]
Hmmm, OK that's a great point about theming. We could also look at a more complex solution if necessary, so let me know. Possibly we can improve things down in later iterations too.

**Comment by MichaelArestad** [comment]
@tmeasday can you mock up a loading state placeholder (I will add markup and styles) in `IFrame.tsx` (or wherever it belongs) for situations i and ii? I will continue working on individual blocks.

**Comment by tmeasday** [comment]
@MichaelArestad done! Also I merged https://github.com/storybookjs/storybook/pull/16539 into this so there is a story for the basic "story preparing" also.

**Comment by tmeasday** [comment]
This looks great @MichaelArestad! Are you good with it now?

**Comment by MichaelArestad** [comment]
@tmeasday I am good with the `iframe.html` styles.

I just pushed styles for the `IconButtonSkeleton`, but I am unsure the best way to implement it. I would like to see the icons in the `Preview` toolbar be replaced with their corresponding skeleton when loading.

**Comment by MichaelArestad** [comment]
I am unclear why the `ArgsTable` isn't showing its loading state in `DocsPage.stories.tsx`.

I also need to take a look at the `Source` skeleton.

**Comment by tmeasday** [comment]
@shilman want to take a look at this?

**Comment by MichaelArestad** [comment]
I am unsure if there is a regression or not, but when I am editing a component, it's corresponding story will update accurately and then immediately be replaced by the loading state in `iframe.html`

**Comment by MichaelArestad** [comment]
Alrighty, I walked through the designs with Dom and, after some great feedback, there are a few changes I plan to make:
- [ ] Add a bit more fidelity to the `ArgsTable` and use the actual code, not a duplication of the code. This might be a bit tricky for me, but ultimately would yield more future-friendly results as we update the `ArgsTable` component down the road. I will likely need to work out a loading state for `ArgsRow` as well. Again, any help in getting me started would be appreciated.
  - [ ] Match the styles in `iframe.html`. I would love it if we could generate a static version of this page instead of duplicating code.
- [ ] Adjust the line height of the loading rectangles in the `Source` component.

**Comment by tmeasday** [comment]
> Again, any help in getting me started would be appreciated.

Are you thinking maybe an `isLoading` prop to the `ArgsTable` and then an `ArgsRowSkeleton`?

> Match the styles in iframe.html. I would love it if we could generate a static version of this page instead of duplicating code.

Will think about this. There might be some way to do it as part of the dev process anyway.

**Comment by tmeasday** [comment]
> I am unsure if there is a regression or not, but when I am editing a component, it's corresponding story will update accurately and then immediately be replaced by the loading state in iframe.html

I'm not seeing this, not sure if I am doing the same thing as you 🤔

**Comment by tmeasday** [comment]
@MichaelArestad I pushed a commit that formalized the pattern we were exploring with an `isLoading` prop. I think it works pretty well: https://github.com/storybookjs/storybook/pull/16538/commits/67d6af101053f7b0affe39b33209ca205080e27d

**Pull request merged**
