### PR TITLE
Examples: Fix build on master

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://app.netlify.com/sites/storybookjs/deploys/5e3a8b3054f52300084af24c

The examples aren't building on master, because of some version mismatch with MiniCssExtractPlugin & cra.

## What I did

- I REMOVED the MiniCssExtractPlugin for CRA. It's only giving grief :(

### CODE REVIEW

**Comment by ndelangen** [comment]
@shilman the changes in the lockfile shouldn't affect users.

The snapshots & typings issues are just caused by a minor version bumps of some deps.

The removal of the MiniCSSExtract plugin I did, because I'm tired of that thing breaking.

**Comment by ndelangen** [comment]
This will make it so the examples on netlify start working

**Review by shilman — APPROVED** [review]
N/A

**Review by shilman — CHANGES_REQUESTED** [review]
Is removing the CSS minification actually necessary to get this working? If not, can you put it in separate PR? That's a user-facing change on `master`

**Comment by ndelangen** [comment]
@shilman I was not able to get it working without disabling the CSSMinificationPlugin :(

**Review by shilman — APPROVED** [review]
👍

**Comment by mtliendo** [comment]
Since upgrading to 5.3.13, my scss files are no longer loading and thus my build is breaking. I believe it has something to do with this being removed.

image

Downgrading to 5.3.12 resolves my issue instantly. Additionally, upgrading to 6-alpha breaks the build with the same error.

**Pull request merged**
