### PR TITLE
[docs] add maintainers guide to help define process

### PR DESCRIPTION
**Pull request by gabrielcsapo**
Issue: Just joined the project as a maintainer and closed an issue by accident

## What I did

Started a conversation for what the maintainers guide should look like and have

### CODE REVIEW

**Review by pksunkara — CHANGES_REQUESTED** [review]
There's a CONTRIBUTING.md which you should use for this.

**Comment by igor-dv** [comment]
I think it will be good to separate the contribution and maintenance. 
For example, things like adding `merged` label to the issues instead of closing them, is for maintaners, but not for the one time PRs.

**Comment by gabrielcsapo** [comment]
@pksunkara right as @igor-dv said this would be more for onboarding maintainers and socializing process. I think we should add more to it, just very new to know about any existing process that exists

**Comment by Keraito** [comment]
Definitely, like the idea of this and agree with the above comments of keeping it separated from the `CONTRIBUTING.MD`. When I started out stuff like what @igor-dv 	mentioned was definitely unknown to me. Having a kind of established guideline that can be referred to would be great imo

**Comment by gabrielcsapo** [comment]
@pksunkara thoughts on the comments about adding this?

**Review by pksunkara — APPROVED** [review]

**Comment by gabrielcsapo** [comment]
Merging, we can keep adding to this document as new processes are defined.

**Comment by igor-dv** [comment]
I think it's not really useful like this. I actually thought you will fill it a bit more before merging 🤣

**Pull request merged**
