### PR TITLE
UI: Default white preview background

### LINKED ISSUE #21080: [Bug]: Preview has dark background when browser is set to dark mode
### Is your feature request related to a problem? Please describe

https://discord.com/channels/486522875931656193/489892645087215636/1016356422956630016 In 7.0, we automatically set the SB theme based on user preferences. But this ends up visually breaking the example components that come out of the box with sb init.

### Describe the solution you'd like

I think this could be fixed by setting the background: white. That way, all example components stick with a light theme.
(Open to other suggestions)

### Describe alternatives you've considered

_No response_

### Are you able to assist to bring the feature to reality?

no

### Additional context

@domyen:
Stackblitz had the [exact same problem](https://fvsch.com/transparent-iframes#toc-5) we have. They set the iframe bg color to white when color-scheme was in dark mode.

Something like this:
```
:root.theme-dark {
  color-scheme: dark;
}

.preview-iframe {
  /* tell browsers to make the iframe opaque
     for documents with color-scheme:dark */
  color-scheme: light;
  background-color: white;
}
```
More context? See the long discussion in Slack [here](https://chromaticqa.slack.com/archives/C02K88CKTFW/p1670438176839659?thread_ts=1670431468.616029&cid=C02K88CKTFW).

@JReinhold:
I think that is a sound solution, let's try that out when we work on this.

One thing I don't understand, is why we can't just always set the iframe to a white background, regardless of the color scheme. In my head that would mimic browsers more closely, which always have white backgrounds - and I would assume that the story's style would override the background color anyway because they're children of the iframe.

But it's just a note to self, I'll experiment with both.

### PR DESCRIPTION
**Pull request by JReinhold**
Closes #21080

## What I did

Set the preview iframe to default to a white background. Previously it was transparent, meaning that Storybook in dark mode would cause a dark background, which is unexpected given that browsers default to a white background - only the user's code should change the background color, not Storybook's code.

Setting the color on the iframe element ensures that user code that sets it on `html`, `body`, or something else **within** the iframe still overrides it.

I've tested that

1. this still works with the backgrounds addon
2. it's still possible for user code to change the background, even based on browser theme, with:

```css
@media screen and (prefers-color-scheme: dark) {
  body {
    background-color: darkblue;
    color: lightgray;
  }
}
```

## How to test

1. Open one of the published sandboxes (eg. this one:)
2. Navigate to one of the page stories:
3. Change your browser color scheme to dark (see screenshot) and reload
4. see that Storybook UI goes dark, but the preview stays white.

Feel free to test this out locally with custom css in stories.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Can you please add a note to MIGRATION.md?

**Comment by MichaelArestad** [comment]
I am noticing on `cra/default`, the light and dark themes don't seem to do anything, but I don't think that's a regression with this PR. The backgrounds addon still works just fine. Nice work!

**Review by MichaelArestad — APPROVED** [review]

**Comment by JReinhold** [comment]
> Can you also change the Backgrounds addon to not default to light mode? (in the "cleared" state)

I'm not sure what you mean by this @MichaelArestad . When it's cleared it doesn't set anything, as if it wasn't there?

**Comment by MichaelArestad** [comment]
@JReinhold
@yannbf mentioned that Before you made this fix, the Backgrounds addon (used on the Example storybook) was changed to default to light so that the background color wouldn't change when dark mode was enabled. If that's the case, we should revert that change.

**Comment by JReinhold** [comment]
Aha I see what you mean, are you referring to https://github.com/storybookjs/storybook/pull/20982 ? I've reverted it as I think it makes sense. Any objections @ndelangen ?

**Comment by ndelangen** [comment]
None @JReinhold

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
