### PR TITLE
fix(webpack-dev-server) : enable webpack to rebuild changes in node_modules by default

### PR DESCRIPTION
**Pull request by rgranger**
Issue: https://github.com/storybooks/storybook/issues/5572

## What I did

I removed the "ignore: /node_modules/" from watchOptions.
Webpack should be able to rebuild changes inside node_modules by default
Even on very huge projects, I never had any performance issue, so I don't see the point of ignoring the node_modules.

## How to test

You have to run storybook, and changea file inside the `node_modules` folder.
Webpack should be able to see the change, and rebuild accordingly.

- Is this testable with Jest or Chromatic screenshots?
I don't think so
- Does this need a new example in the kitchen sink apps?
No idea
- Does this need an update to the documentation?
No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by rgranger** [comment]
How can I make the checks successful ?

**Review by shilman — APPROVED** [review]
@rgranger I'm ok with this change but worried about performance. When you say you've never had any problems with this option even in large projects, does that include Storybook projects?

cc @ndelangen @Hypnosphi @tmeasday @igor-dv any thoughts?

I'm thinking we might as well merge and release in alpha, and see if anyone complains. If so, it's an easy change to back out.

**Comment by shilman** [comment]
@rgranger don't worry about the checks 😖

**Comment by rgranger** [comment]
@shilman Yes, i'm currently working on a very huge project (~40 Mo in dev), and I never had performance issues. The initial building is a bit long, but the watch rebuild is pretty fast.

I need this because i'm working with private dependencies, and thus i'm constantly modifying them in `node_modules` (while being `npm link`ed or not).

**Comment by shilman** [comment]
@rgranger you should be able to override this in "full control mode" right? Have you tried that?

**Review by ndelangen — CHANGES_REQUESTED** [review]
I'd like to see some actual performance measurements before merging this.

@rgranger If you could:

time the start-up time without this change on your codebase

and then

time the start-up time after applying the customization to your storybook webpack config

and show us what the before and after diff is...

We really don't want to just 'wing it' on this one.

**Comment by rgranger** [comment]
@shilman Yes I did override the option in full control mode like this :

```js
export default (baseConfig) => {
  baseConfig.watchOptions = {
    ignored: false,
  }

  return baseConfig
}
```

But It took me times to figure this out when I upgraded storybook from previous major version.

And it doesn't feel quite right to override this options to set it to false...

@ndelangen Here are the results of webpack build times on my huge project :

Webpack build / rebuild times

### Before (watchOptions: ignored node_modules)

* build : ~ 25s
* rebuild : ~ 1.7s

### After (watchOptions: ignored false)

* build : ~ 26s
* rebuild : ~ 1.8s

**Comment by Hypnosphi** [comment]
Oh, that's probably the reason why `WatchMissingNodeModulesPlugin` didn't work for me

**Review by Hypnosphi — APPROVED** [review]

**Review by Hypnosphi — CHANGES_REQUESTED** [review]
You probably need to apply the same change to "manager" config: 

https://github.com/storybooks/storybook/blob/e14d57e63c7bb9243af43cb84e333a92224fb731/lib/core/src/server/dev-server.js#L48

**Review by ndelangen — APPROVED** [review]
@rgranger thanks for the tests, sounds good.

What do you think about @Hypnosphi's suggestion?

**Comment by rgranger** [comment]
Seems good to me. Unfortunately, I won't have any time soon to push another commit

**Review by Hypnosphi — APPROVED** [review]

**Comment by ndelangen** [comment]
related: https://github.com/storybooks/storybook/pull/6566

**Comment by ndelangen** [comment]
wait with merge until 5.1 has been released

**Comment by ndelangen** [comment]
Related:
https://webpack.js.org/configuration/watch/

**Pull request merged**
