### PR TITLE
Implement a routing system using react-router #6

### PR DESCRIPTION
**Pull request by lowkay**
Implemented a routing system using react-router, so that routing could drive the application and synchronise a route handler is required to pull in the data from the synchronised store, respond to updates and push updates.

### CODE REVIEW

**Comment by mikem-mup** [comment]
Looking forward to this - deep linking to component examples is a great way for teams to collaborate on UI patterns

**Comment by arunoda** [comment]
@mikem-mup We hold this PR since we are working on some core changes to the UI. I hope we could deliver the new UI core and routing layer by early next week.

**Comment by arunoda** [comment]
In the latest release `v1.20.0` it has the support for the routing.
We don't use React Router and simply use pushState + history API.
That's because we simply need to change some queryparams.

It was easy to do that manually and configurable.

**Comment by arunoda** [comment]
BTW: @lowkay Thanks for working on this.

**Pull request closed without merging**
