### PR TITLE
Addon Controls: Remove unused hideNoControlsWarning type

### LINKED ISSUE #25344: Remove hideNoControlsWarning in ControlsPanel

### PR DESCRIPTION
**Pull request by yannbf**
Closes #25344

## What I did

This PR removes references to an unused parameter which got removed [here](https://github.com/storybookjs/storybook/pull/23635) in Storybook 7.2.1.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

No need

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Review by valentinpalkovic — APPROVED** [review]

**Comment by shilman** [comment]
@yannbf shouldn't this be labeled `breaking change`?

**Comment by yannbf** [comment]
> @yannbf shouldn't this be labeled `breaking change`?

Technically not, but we can add it!
Reason: The change was made in [here](https://github.com/storybookjs/storybook/pull/23635) and released in Storybook 7.2. This PR only removes the references to it.

**Review by jonniebigodes — APPROVED** [review]
@yannbf thanks for taking the time to address this deprecation and factoring in the documentation changes. Appreciate it 🙏 ! All is good on my end.

**Comment by yannbf** [comment]
I'm holding off on this one based on @cdedreuille's request to possibly do a rework here!

**Pull request merged**
