### PR TITLE
custom output path in compodoc 

### PR DESCRIPTION
**Pull request by blackthread**
Issue:

## What I did
i added the possibility to specify a custom output path via the compodocArgs

## How to test

- [X] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?
didn't find any documentation to update

### CODE REVIEW

**Comment by blackthread** [comment]
the build is failing but unrelated to my changes i believe ?

**Comment by MichaelArestad** [comment]
Howdy @blackthread, can you provide a use case for this? 

Also, the failing build i s unrelated to your changes.

**Comment by jogelin** [comment]
@MichaelArestad When we are working on a monorepo (like Nx) and we have multiple storybook instance, we want to specify where the json file will be generated (in a dist folder per example). A different path will also help to cache all outputs generated by the storybook.

Otherwise, it will be generated at the root and erase the previous one.

**Comment by ndelangen** [comment]
@storybookjs/angular Could someone review/approve this? If it looks right, it can be merged IMHO.

**Comment by ndelangen** [comment]
@blackthread I'm unable to update your branch with the `next` branch because of:

```
(output-compodoc-args) % git push                                                                                                                                      ~/Projects/Storybook/core/code
Enumerating objects: 43, done.
Counting objects: 100% (43/43), done.
Delta compression using up to 10 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 1.83 KiB | 1.83 MiB/s, done.
Total 15 (delta 14), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (14/14), completed with 14 local objects.
To https://github.com/blackthread/storybook.git
 ! [remote rejected]       output-compodoc-args -> output-compodoc-args (refusing to allow an OAuth App to create or update workflow `.github/workflows/generate-repros-next.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/blackthread/storybook.git'
```

I'm not sure if there's something I should do to make it work, or is there is something you could do to remedy this.

But it'd be helpful if you could update this feature branch with `next` from the upstream remote. 🙏  Thank you for contributing!

**Comment by blackthread** [comment]
> @MichaelArestad When we are working on a monorepo (like Nx) and we have multiple storybook instances, we would like to be able to specify a custom path where the json file will be generated (in a dist folder per example). That will help to cache all outputs generated by the storybook.
> 
> Otherwise, it will be generated at the root and erase the previous one.

@MichaelArestad What Jonathan explained was in fact the use case ?

**Review by ThibaudAV — APPROVED** [review]

**Comment by ndelangen** [comment]
@blackthread I'd love to get this updated so it can be merged, but your PR won't allow upstream maintainers to push to your fork. Meaning we can't merge in the base-branch which contains changes in CI, etc. I did notify you about that before:
https://github.com/storybookjs/storybook/pull/18962#issuecomment-1268515593

Screenshot 2022-12-20 at 10 19 17

I love to get your changed merged, but we need to make sure the changes are good.
I afraid I'll have to close this PR and re-create it.

**Pull request closed without merging**
