### PR TITLE
React/Angular/HTML/Vue: Fix typings for `configure`

### PR DESCRIPTION
**Pull request by shilman**
Issue: #7595 

## What I did

Fix typings

### CODE REVIEW

**Review by nickofthyme — APPROVED** [review]
@shilman This looks good to me but is there a reason you didn't make these type changes on the `ClientApi.configure` to be consistent with all the other types/methods defined/exported in these `preview/index` files?

https://github.com/storybookjs/storybook/blob/86370b51296f62b318404e3f8858ed1762992d24/app/angular/src/client/preview/index.ts#L13

**Comment by shilman** [comment]
@nickofthyme Probably because I'm an idiot, or because it's nearly 3am here. Take two! 😅

**Comment by nickofthyme** [comment]
@shilman nonsense! You need to go to sleep! This is not that important...lol 😅

**Review by nickofthyme — APPROVED** [review]
Much Better 👍

**Pull request merged**
