### PR TITLE
Netlify for examples again

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/9528
now.sh seems to have troubles building our project, which is unreproducible on CircleCI or local machines.

## What I did

- This exchanges the docs-deployment with examples-deployment in netlify
- removed now.sh

## How to test

Netlify should report a link with the full examples

### CODE REVIEW

**Comment by ndelangen** [comment]
😢

**Comment by ndelangen** [comment]
So netlify won't allow for build script that take longer then 15 minutes :( Seems this can't work

**Comment by ndelangen** [comment]
I'll try reaching out to netlify

**Comment by ndelangen** [comment]
A very big thank you to the netlify team, including, but not limited to @sw-yx for helping get this build to work on Netlify!

**Comment by sw-yx** [comment]
np!

**Pull request merged**
