### PR TITLE
Replaced deprecated `markdown-to-react-components` with `marksy`

### PR DESCRIPTION
**Pull request by ranneyd**
Issue: #1114 

## What I did

Looking at issue 1114 (https://github.com/storybooks/storybook/issues/1114)...
The error came from a package called `markdown-to-react-components`. Looking at this package's github (https://github.com/christianalfoni/markdown-to-react-components) it's clear that the package is deprecated. They recommend using `marksy` (https://github.com/cerebral/marksy).

Marksy appears to be a fork of `markdown-to-react-components` because the APIs are almost identical (namely, the configuration is exactly the same). This made swapping out the old version for the new one very easy, which is what I did. I also updated the name of the config (which can be passed as an argument to this addon) to reflect the new underlying mechanism.

## How to test

1. Create a simple Storybook project with info (use the readme of @storybook/addon-info for helP)
2. Make a story for a component WITH PROPTYPES DEFINED.
2. Confirm that when you run your storybook, clicking on "Show Info" at the top shows the correct PropType info.

### CODE REVIEW

**Comment by shilman** [comment]
Thanks @ranneyd for diagnosing the problem and then fixing it. You rock! 👊 

Edited the PR description slightly. Code looks great. I'll test it out on my machine and merge if it works.

Many thanks!

**Review by shilman — CHANGES_REQUESTED** [review]
@ranneyd Looks like you need to update `package.json` to add `marksy` and remove `markdown-to-react-components`?

**Comment by ranneyd** [comment]
`facepalm`

I actually had but I accidentally undid that change. Fixing now.

**Comment by ranneyd** [comment]
@shilman try it now. Let me know how it goes!

**Review by shilman — APPROVED** [review]
@ranneyd Figured you must have made the changes at some point to get this working. Looks great and thanks so much for contributing! 🏅  Merging.

**Pull request merged**
