### PR TITLE
`active` PropTypes on MobileLayout

### PR DESCRIPTION
**Pull request by ShimiSun**
Issue: #5910

Not sure if this is the right approach, but `active` on Panels is being fetched from Mobile, and Mobile treats `active` as bool (L-132), hence I assume the `active` PropTypes is missing the support of boolean.
This should solve the following warning message :
```
vendors~main.fe9333fdaa91c3bc407a.bundle.js:8776 Warning: Failed prop type: 
Invalid prop `active` of type `boolean` supplied to `<<anonymous>>`, 
expected `number`.
    in Unknown (created by MobileLayout)
    in MobileLayout (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
```

Issue:

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Thank you @ShimiSun! @ndelangen mind taking a look at this?

**Comment by Armanio** [comment]
Hmm, I think we need to fix initial state in Mobile component. On component start `state.active` has boolean value.

**Comment by ndelangen** [comment]
I think the problem isn't that the PropTypes are incorrect, I think we're passing the wrong value to the component.

**Comment by Armanio** [comment]
@ShimiSun could you fix initial state on Mobile component? [here](https://github.com/storybooks/storybook/pull/6241/files#diff-79e0e9d8f1ea97dc4fc17a5fc33063aeR132) 
If not let me know - I fix it self.
Thank you for effort!

**Comment by iamandrewluca** [comment]
Use this GitHub Tip for better linking between issue and PR :) 
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by ShimiSun** [comment]
@Armanio done, let me know if that works.

**Comment by ndelangen** [comment]
I'll fix the tests and merge

**Pull request merged**
