### PR TITLE
Vue3: Dynamic Snippet Rendering experiment

### PR DESCRIPTION
**Pull request by pocka**
Issue: #13917

## What I did

This branch contains an experiment I did for Dynamic Snippet Rendering for Vue.js v3.x.
Because the one for Vue2 has a lot of shortcomings, I took a template-parsing approach instead of traversing VNode.
I hope this code helps someone implement the feature.

The `addons/docs/src/frameworks/vue3/sourceDecorator.ts` does

1. Lookup the story component (exit when not found)
2. Generate internal node tree
    - If the component has `template`,
      1.  Parse it with `@vue/compiler-core#baseParse`
      2. Search `v-bind="something"` then expand it to individual bindings (AST transform) (e.g. when `something` is `{foo: 1, bar: "2"}`, turn it to `:foo="1" bar="2"`)
      3. Convert AST to internal node tree
    - Otherwise, convert VNode to internal node tree (fallback)
3.  Serialize the internal node tree and Emit `SNIPPET_RENDERED`

### Limitations & Considerations

- ~Does not support render function/JSX.~ implemented VNode serializer.
- ~When a user write `<foo-component v-bind="args" :bar="baz" />`, `baz` will be printed as-is. This could be solved by additional evaluation process, though.~ implemented.
- Needs to declare additional dependencies, `@vue/compiler-core` and `@vue/runtime-core`. These are deps of Vue 3 but I'm not sure how to declare/use them without both a user manually installing and causing version inconsistency.
- VNode parser cannot handle several use cases, such as scoped slots or named slots.

While I think the majority of Storybook for Vue3 users write a story in a string template, the last limitation might be critical for JSX users.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [x] Does this need a new example in the kitchen sink apps? ... `examples/vue-3-cli/src/stories/addons/docs/DynamicSnippet.stories.js` includes some test stories.
- [ ] Does this need an update to the documentation? ... idk

If your answer is yes to any of these, please make sure to include it in your PR.

## Additional Note

I have not tried the custom renderer, which is discussed in #13917 . From seeing type signatures and their usage at `runtime-test` package, I'm not sure we can access enough component meta through a custom renderer (e.g. directives).

### CODE REVIEW

**Comment by shilman** [comment]
@pocka I started playing with this in the monorepo and it really looks great. I'm not a vue3 expert, so maybe this is an instance of the limitation you describe above, but here's a case in `examples/vue-3-cli` that produces a slightly strange result. What do you think?

Mouse_Highlight_Overlay_and_Example___DynamicHeading_-_Six_⋅_Storybook

**Comment by pocka** [comment]
@shilman 
The reason `<component/>` is shown instead of `<DynamicHeading/>`, is [the story creates a temporary component named `component`](https://github.com/storybookjs/storybook/blob/next/examples/vue-3-cli/src/stories/DynamicHeading.stories.ts#L29-L34). Current implementation detects the root component (story) only by checking whether a component registers the `story` component. Therefore the logic thinks the wrapper component provided storybook (which is something like `{ components: { story }, template: "<story/>" }`) as the root (story) and renders its contents. Maybe this is also the reason the first snippet includes decorator contents `<div :style="~">`.

That root (story) lookup function definitely needs improvement, but I have no idea how it could be done...

**Comment by ndelangen** [comment]
@pocka I this something you want to continue working towards?

**Comment by pocka** [comment]
@ndelangen No. I don't think this PR could advance without any feedback/technical support... I'd close for now.

**Comment by ndelangen** [comment]
@shilman This might be useful for later for docs 2.0

**Comment by vhoyer** [comment]
@ndelangen what do you mean "docs 2.0"? is the docs addon getting an makeover?

**Comment by vhoyer** [comment]
> That root (story) lookup function definitely needs improvement, but I have no idea how it could be done...

couldn't we traverse the tree until we find the `component` the story is about and then render all it's siblings and parents?

**Comment by shilman** [comment]
@vhoyer yes, docs is getting a makeover as part of SB 7.0. we'll be sharing some details about that soon. I don't think we'll be changing the source snippet stuff much -- if at all -- so this PR could probably be revived in its current form if somebody wanted to pursue it!

**Comment by vhoyer** [comment]
Oh sweet, I'm interested in this feature, do you recommend we wait for the SB 7.0 before working on this then?

**Pull request closed without merging**
