### PR TITLE
Remove blue outline when story node is focused

### PR DESCRIPTION
**Pull request by brenordr**
Remove blue outline defined by the user argent

Issue:
Browsers define a blue outline when a node is on focus.
Setting the outline to none prevent this behavior
```storybook version: 3.1.9```

screenshot 2017-07-20 11 09 43

## What I did
Reset the outline when a node is in focus to 'none'
at ```@storybooks/react``` and ```@storybooks/react-native```

## How to test
Run ``` yarn run storybook```
And click in one of the tests.

### CODE REVIEW

**Comment by ndelangen** [comment]
At some point I'd like to get better keyboard accessibility, this is on my list. But for now, I guess I should just let this pass, and worry about improving it later.

**Comment by ndelangen** [comment]
Thanks for the contribution @rodriguesbreno !

**Review by ndelangen — APPROVED** [review]

**Comment by rodriguesbreno** [comment]
@ndelangen Storybooks is a great project.
I'm glad to contribute.

Btw, I can help with the keyboard accessibility 😄

**Comment by ndelangen** [comment]
That's great @rodriguesbreno!

What I'd like to happen is extract react components for storybook itself into the `lib/components` package. and re-evaluate their styling and markup to facilitate better keyboard accessibility. 

Improve the UI in general and provide a collection of components suited for usage in addons.

**Comment by igor-dv** [comment]
It breaks this one - #1427. Just to be sure that is was expected.

**Comment by rodriguesbreno** [comment]
@ndelangen I'll schedule sometime to explore it 😄

**Comment by ndelangen** [comment]
What do you mean?

**Comment by rodriguesbreno** [comment]
@igor-dv I see, so the blue outline is necessary for accessibility.
Maybe a better solution is add a blue line in the bottom of the focused,
but not a rectangle around

**Comment by igor-dv** [comment]
It's one of the options.. but maybe making it gray and thin will be even better. For example:

image

gray-outline

**Comment by ndelangen** [comment]
So what I'd love to happen is to move this navigation component into `lib/components` and style it using glamorous.

Then give it some nice looking `:active, :hover` etc.

**Comment by rodriguesbreno** [comment]
@igor-dv I agree gray and thin is better

**Comment by Hypnosphi** [comment]
> @igor-dv I agree gray and thin is better

You might want to use Firefox then,  that's how default outline looks there

**Pull request merged**
