### PR TITLE
Fix autodetection of used components in info addon

### LINKED ISSUE #3989: Proptypes component autodetection broken
Regression in v4.0.0-alpha.16. If `propTables` option is omited, `addon-info` used to render proptypes tables for all used components. It does not render anything in v4.0.0-alpha.16  any more. It does not render proptypes tables at all.

It is caused by a search&replace typo in 935cefd2. See my comment where exactly: https://github.com/storybooks/storybook/commit/935cefd27a720548fb3fabcff9824dd8703d7b1b#r30022947

I can create a PR fixing it.

### PR DESCRIPTION
**Pull request by martinmacko47**
Closes #3989 

Fixes regression in v4.0.0-alpha.16. If propTables option is omited, addon-info used to render proptypes tables for all used components. It does not render anything in v4.0.0-alpha.16 any more. It does not render proptypes tables at all.

It was caused by a search&replace typo in 935cefd. See my comment where exactly: https://github.com/storybooks/storybook/commit/935cefd27a720548fb3fabcff9824dd8703d7b1b#r30022947

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Thanks, 
Verify the snapshot change and fix it? You can do so by running the unittests locally and signal you want to update the snapshots.

I will merge as soon as possible.

**Comment by ndelangen** [comment]
The snapshot change is what I expect, so all we have to do is accept the update (by running the tests with `--update`)

**Comment by szimek** [comment]
@ndelangen Hi! Any chances to merge it soon? Is there anything I can do to get it merged sooner? 

I have exactly the same issue and was debugging it just to find out the commit where `props.children` were accidentally renamed to `props.innerChildren` :)

**Comment by ndelangen** [comment]
@szimek yeah I'll put in the effort to fix the snapshots and merge in master

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
