### PR TITLE
Addon-docs: Fix source block tree shaking

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Source-block importing entire source-loader which is killing build times

## How to test

Compare `yarn storybook` before & after

Mouse_Highlight_Overlay

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
Great starting point, hopefully we can fix this in a better way later on!

**Comment by yannbf** [comment]
Also kudos to @guilhermewaess for identifying the bug!

**Comment by shilman** [comment]
Yes, thank you @guilhermewaess !!! I'd seen those charts creep up so I knew there was something wrong, but since they actually start moving a few days before the change was introduced, it threw me off. You're a hero for figuring it out.

**Comment by guilhermewaess** [comment]
Thanks, @shilman and @yannbf. I'm glad that I helped :D
I just tested the last version, and looks perfect 👍

**Pull request merged**
