### PR TITLE
Core: Rename `generated-stories-entry` to `cjs` extension so require works

### PR DESCRIPTION
**Pull request by jpzwarte**
Possible fix for https://github.com/storybookjs/storybook/issues/14877.

### CODE REVIEW

**Review by tmeasday — CHANGES_REQUESTED** [review]
@jpzwarte I am surprised you don't need to make the same adjustment to the `xxx-generated-config-entry.js` also? (lines 128 & 136 above?).

**Comment by jpzwarte** [comment]
@tmeasday I've added them, but afaics they're not really necessary somehow.

**Review by tmeasday — APPROVED** [review]
LGTM. I guess we may as well use `.cjs` everywhere we are going to compiling templates to `require()` code.

**Review by shilman — CHANGES_REQUESTED** [review]
@tmeasday this seems to break angular somehow per the e2e tests

**Comment by tmeasday** [comment]
Ok, so the reason this breaks is that the `virtualModuleEntry.template.js` is not compiled to CJS (in the `dist/cjs` directory), because of these line (I think?) 

https://github.com/storybookjs/storybook/blob/8ea0e35213fcdd29005ec7d0ac77334bb2048786/.babelrc.js#L139-L156

@shilman git blame isn't helping me much here. Do you recall why this is here (seems a bit weird, but I don't particularly want to change it). I guess we have 3 options:

1. Actually compile the `virtualModuleEntry.template.js` file to CJS in the `dist/cjs` folder. This seems like the logical thing to do but I guess maybe it is like this for a reason.

2. Also not compile `virtualModuleStory.template.js` to CJS in `dist/cjs`. This would be consistent with the other file, and possibly fix the original problem 🤷 

3. Just use `.js` for the first and `.cjs` for the second, with a comment explaining why.

I would lean towards 3 for reasons of caution I guess.

**Comment by shilman** [comment]
I think this is a question for @ndelangen

**Comment by tmeasday** [comment]
@ndelangen can I get you take a quick look at my comment above? If it doesn't ring any bells, we'll just take my option 3 and be done with it. Sorry for the delays @jpzwarte!

**Comment by ndelangen** [comment]
Let's do option 3, and revisit this for 7.0?

**Comment by tmeasday** [comment]
@jpzwarte any appetite for reverting what I asked you to do and adding a comment explaining why? 🙏

**Review by shilman — APPROVED** [review]
LGTM! Thanks @jpzwarte @tmeasday 🚀

**Comment by jpzwarte** [comment]
Thanks for finishing this @shilman & @tmeasday ! Too busy to do it myself :/

**Comment by tmeasday** [comment]
Totally understand @jpzwarte, no problem at all!

**Pull request merged**
