### PR TITLE
Core: Add pluggable indexers

### PR DESCRIPTION
**Pull request by shilman**
Issue: #18081

## What I did

- [x] Add pluggable indexers API
- [x] Move MDX indexer to `addon-docs`

## How to test

- [ ] CI passes

### CODE REVIEW

**Comment by j3rem1e** [comment]
Shouldn't this check be opened too ?  

https://github.com/storybookjs/storybook/blob/4db554b2fd8d91f5246ba53060f067e1d58b2398/lib/core-server/src/utils/StoryIndexGenerator.ts#L56

**Comment by shilman** [comment]
Good catch @j3rem1e! I updated it to allow for all file extensions 👍

**Review by tmeasday — APPROVED** [review]
Looks great. Should we drop `readCsfOrMdx` too?

**Comment by yannbf** [comment]
@shilman could you take a look at the failures in CI?

```
No matching story indexer found for /tmp/storybook/examples/html-kitchen-sink/stories/__snapshots__/addon-a11y.stories.storyshot
```

**Pull request merged**
