### PR TITLE
fix: jsondoc extraction does not set 'type' property used for automatic argType inference

### PR DESCRIPTION
**Pull request by crixx**
Issue: #13594

## What I did
Implemented the proposed change in the mentioned issue

## How to test
1. clone the repo on branch next
2. run the bootstrap command yarn bootstrap --core
3. cd to ember-cli
4. run yarn
5. run yarn storybook
6. the controls.story does not show the correct types in the `controls` tab
7. switch to this PR branch
8. repeat steps 2-5. 
9. The controls.story does now correctly show the correct types and provides controls for the arguments in the `controls` tab

### CODE REVIEW

**Comment by crixx** [comment]
@shilman anything I can do?

**Comment by shilman** [comment]
@crixx Sorry, am behind on github notifications thanks to the Addon catalog launch that went out earlier this week. Will review & merge soon. Thanks for your patience!

**Review by shilman — COMMENTED** [review]
@crixx This all looks great, but unfortunately there doesn't appear to be a required example in the `examples/ember-cli` directory. Can you add one? I'd expect to see a red asterisk next to the arg name when I run the example to verify the feature is working. Thanks!

**Comment by crixx** [comment]
hi @shilman. Thanks for looking into this. I already implemented a new Story showcasing the required setup. It's already in my first commit in `examples/ember-cli/stories/addon-controls.stories.js`. To show the YUIDoc annotations in action, I created a new component in `examples/ember-cli/app/components/arg-types-inference-example.js`.
If I'm honest the component could be some smarter and styled a bit more nicesly, but tried to keep it as simple as possible without adding to much of CSS etc.

What I don't understand is 
>  I'd expect to see a red asterisk next to the arg name when I run the example to verify the feature is working.
Where would you expect a red asterisk to show up? 🤔 


Here my branch when i build the ember app first and then run storybook
- `cd examples/ember-cli/`
- `$ember build --e=production` and start storybook ``
-  `npm run storybook`

Screenshot 1
image
Screenshot 2
image

/crixx

**Comment by crixx** [comment]
@shilman anything I can do?

**Comment by crixx** [comment]
@shilman anything I can do?

**Comment by shilman** [comment]
Looking now. Thanks for your patience @crixx

**Comment by shilman** [comment]
Mouse_Highlight_Overlay

@crixx if a text and toggle are required it should show a red asterix next to the property name, as shown in the image.

**Comment by ndelangen** [comment]
@crixx I updated this PR with next, Could you have a look to see if it all looks right to you?

I think @shilman's comments are about a regression he sees where the red asterisks es are no longer there, when they should be. Can you confirm this is indeed a regression and if it is one, address it?

**Comment by kylegach** [comment]
@crixx — Are you still interested in pursuing this PR?

**Comment by crixx** [comment]
Hi @kylegach thanks for asking. I switched jobs in the meantime and am not going to find any time to dive into the details again, sorry...

**Comment by kylegach** [comment]
Hey, @crixx. Thanks for the quick reply! And congratulations on your new job! 🎉 

No worries on not having the time for this any longer. Because Ember is a community-provided framework, I'm going to go ahead and close this one. Thanks again for the time you spent on it!

**Pull request closed without merging**
