### PR TITLE
Add support for preview-decorators.

### PR DESCRIPTION
**Pull request by arunoda**
With this, we could set a decorator for preview via an addon.
This is pretty useful for Storybook Designer where we could add more tools to the preview area.

Currently, it's only possible to set only one preview decorator  for the whole app.

### CODE REVIEW

**Comment by arunoda** [comment]
@mnmtanish Check this out.
I also did this: https://github.com/kadirahq/storybook-addons/commit/c4d256c4317e0f495cd7ad5c168c65f64527ad76

**Comment by mnmtanish** [comment]
We can give this feature without introducing another api function. In React Native Storybook it's done like [this](https://github.com/kadirahq/react-native-storybook/blob/a8469c9ebe4fae521d965b978a039474bb3db269/src/manager/provider.js#L21). To set a custom preview area, we just have to write an addon and call `addons.setPreview` in there.

For React Storybook, we can simply move the iframe code to an addon `storybook-addon-iframe-preview` and include it in addons.js file by default. If anyone wants to add a custom preview area (designer?) they can simply fork the iframe preview addon and change it as they wish.

I strongly suggest we remove the Preview decorator API methods from storybook-addons repo ASAP and use the existing one.

**Comment by arunoda** [comment]
Okay. I'll revert.
No need to move iframe code into another project.
We can work with the old API.

**Comment by mnmtanish** [comment]
I'm just saying that it'll be really easy to **fork and extend** it it's in another project

**Comment by arunoda** [comment]
No need to fork and extend. We don't want to replace the preview. Just need to decorate it.
So, I we don't need this code at all.

**Comment by mnmtanish** [comment]
Let's agree to disagree then

**Pull request merged**
