### PR TITLE
Addon-docs: Add `docs.forceExtractedArgTypes` parameter

### PR DESCRIPTION
**Pull request by matheo**
Issue:

I wanted to extend the Inputs of my Story with a couple custom controls, but ATM adding a non-Subset of args/argTypes results on a resetted `extractedArgTypes = {}`. I wanted to preserve the extracted Args while adding/overriding some controls.

## What I did

I added the `docs.forceExtractedArgTypes: boolean` parameter to skip the validation and be able to combine all the existing parameters: extractedArgTypes, userArgTypes and inferredArgTypes.

@shilman I'm not sure where to document this because it's mostly related to `argTypes` customization (addon-controls), but the parameters seems logically connected to the extraction located in the addon-docs.

PS/ as always, if you realize a better name, it's fine.

### CODE REVIEW

**Comment by shilman** [comment]
Nice solution. I struggled with that problem and wasn’t fully happy with what i ended up with. Using a parameter seems like a great approach!

Will do a proper review later today

**Comment by matheo** [comment]
@shilman I guess that `forceExtractedArgTypes` is more meaningful, and fits pretty well this optional behavior.

**Review by shilman — APPROVED** [review]
LGTM, and I like the new name. Can you find a good place to document the parameter? Maybe in `props-tables.md` or `controls/README.md`?

**Comment by matheo** [comment]
I've added a little paragraph next to the `argTypes` docs in `controls/README.md` :)

**Pull request merged**
