### PR TITLE
React: Move argType stories to template/stories folder

### PR DESCRIPTION
**Pull request by tmeasday**
## What I did

- Move the stories that test argType detection (in react) to the `template/stories` folder.
- As this is a `.tsx` file, it'll only appear in TS-based react sandboxes.
- Note I needed to comment out 4 test cases that required styled components or emotion. They still seem to pass unit tests though (for now).

## How to test

- [ ] We should check the chromatic stories match the old stories in official storybook before merging

### CODE REVIEW

**Comment by tmeasday** [comment]
This PR is currently breaking in vite, not sure why.

**Comment by tmeasday** [comment]
@shilman two things blocking me right now:

1. Jest tests failing because we cannot use ESM code in these files due to the use of `requireFromString` (I think). However we need to write ESM for these stories to work in Vite. Any idea which we should prefer? (obvious things we could do: a. skip these examples in the jest tests; b. remove them from *all* sandboxes).

2. Styled components TS test case causing build to fail (annoying because we aren't even including it in the SB). Should we just delete these stories? (Eventually we won't have SC in the monorepo anyway and that'll be an issue eventually).

**Comment by shilman** [comment]
@tmeasday let's delete the styled components code & bring it back later in the annotations server if we even need it at all

As for Jest vs Vite, I think we prefer Vite at this point no question

**Review by shilman — APPROVED** [review]
LGTM. Thanks for toughing this one out!

**Comment by tmeasday** [comment]
The issue [here](https://www.chromatic.com/build?appId=630511d655df72125520f051&number=425) seems to be https://github.com/storybookjs/storybook/issues/17458 -- basically that `assert` is not available in the browser environment. This seems to be a problem with `doctrine` that isn't ever getting fixed. @IanVS @joshwooding what do you think about adding an alias for `assert` to the vite builder, similar to https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2 (but probably using `browser-assert` like [we do in the manager and webpack builder](https://github.com/storybookjs/storybook/blob/5f3e7137e188e9a960ac5b6128656b85cce04fde/code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts#L261))

**Comment by joshwooding** [comment]
> The issue [here](https://www.chromatic.com/build?appId=630511d655df72125520f051&number=425) seems to be #17458 -- basically that `assert` is not available in the browser environment. This seems to be a problem with `doctrine` that isn't ever getting fixed. @IanVS @joshwooding what do you think about adding an alias for `assert` to the vite builder, similar to https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2 (but probably using `browser-assert` like [we do in the manager and webpack builder](https://github.com/storybookjs/storybook/blob/5f3e7137e188e9a960ac5b6128656b85cce04fde/code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts#L261))??

This has come up previously, I think ultimately we would want to move away from doctrine since it’s no longer being supported but for now adding a shim for assert seems like a good mitigation for now. 👍

**Pull request merged**
