### PR TITLE
CLI: Change generators to Triconfig

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/9032

## What I did
migrated all generators to triconfig (only 1 file 🎉)

### CODE REVIEW

**Comment by ndelangen** [comment]
@shilman @mrmckeb I could use some help, I think there's something not incorrect here.

```
Running smoke test in react_scripts
$ start-storybook -p 9009 -s public --smoke-test --quiet
info @storybook/react v5.3.0-beta.16
info 
info => Loading static files from: /home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/public .
info => Loading presets
info => Loading presets
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
info => Adding stories defined in ".storybook/main.js".
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack setup.
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
```

throws with:

```
ERROR in ./.storybook/generated-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
    at assertNoDuplicates (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
    at createDescriptors (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/lib/index.js:5:194)
    at /home/runner/work/storybook/storybook/lib/cli/test/run/react_scripts/node_modules/babel-loader/lib/index.js:5:364
 @ multi /home/runner/work/storybook/storybook/lib/core/dist/server/common/polyfills.js /home/runner/work/storybook/storybook/lib/core/dist/server/preview/globals.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true main[2]
```

**Comment by ndelangen** [comment]
I'm guessing it's because of what we talked about recently @shilman:

https://github.com/storybookjs/presets/blob/master/packages/preset-create-react-app/src/helpers/checkPresets.ts#L12

**Review by tmeasday — COMMENTED** [review]
Looks great, love it!

**Comment by shilman** [comment]
> This is causing the preset to apply multiple times.

Why? Doesn't it just require the file?

**Comment by ndelangen** [comment]
I found a bug in presets resolution and fixed it & added a option-property so preset-properties can know which presets exist and can respond to it.

**Review by shilman — APPROVED** [review]
🎉🎉🎉

**Comment by mrmckeb** [comment]
Great work, and thanks @ndelangen! Sorry I didn't reply, I was on a weekend holiday.

**Comment by ndelangen** [comment]
I hope you had an amazing holiday!

**Pull request merged**
