### PR TITLE
Add codemod for deprecated addon-info API

### PR DESCRIPTION
**Pull request by trevoreyre**
Issue:

## What I did

Added a codemod to convert the outdated `addWithInfo` API from the addon-info package.

## How to test

`./node_modules/.bin/jscodeshift -t ./node_modules/@storybook/codemod/dist/transforms/update-addon-info.js . --ignore-pattern "node_modules|dist"`

### CODE REVIEW

**Comment by TrevorEyre** [comment]
Note - This doesn't modify the `setAddon(infoAddon)` call made in the Storybook config file. I wasn't sure how to catch all possible permutations of setting up the addon in that file, and it's a pretty easy change to make manually.

**Comment by TrevorEyre** [comment]
This doesn't include any tests yet, but they are coming. In the meantime, if anyone wants to try out the codemod or provide any feedback, that would be great!

**Comment by TrevorEyre** [comment]
This is ready for final review.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Looks good to me! anyone else want to pitch in here? @storybooks/team

**Comment by UsulPro** [comment]
Maybe it's not related to this PR directly but I think we need to add some info about this codemod otherwise users will not know about its existence

**Comment by ndelangen** [comment]
Yes @UsulPro we do, Right now the "how to test" @TrevorEyre wrote describe how to run codemods. And I think some codemod is also part of the CLI.

But it's definitely something we must improve!

**Comment by TrevorEyre** [comment]
@ndelangen @UsulPro - I can add some info about the new codemod at `lib/codemod/README.md`. That should help. But I do think there should be a little more documentation about the existence of these codemods and how to find them somewhere else. Maybe in the main README? Or in the CHANGELOG? Or somewhere else on the docs site?

**Comment by danielduan** [comment]
@TrevorEyre I think it would be helpful to link it to the deprecation console message as well.

**Comment by UsulPro** [comment]
maybe https://github.com/storybooks/storybook/blob/master/MIGRATION.md is also an option

**Comment by ndelangen** [comment]
I think for now it's fine to add it to the readme of the codemod package, if you could add it there, we can get this merged!

A mention about codemods and where to find info about them would be perfect in MIGRATION.md!

**Comment by TrevorEyre** [comment]
@ndelangen I added a couple examples in the codemod package's README.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
