### PR TITLE
Addon Info: Omit empty inline info header

### PR DESCRIPTION
**Pull request by duncanbeevers**
Issue: Creating stories using `addWithInfo`, configured not to show headers, and to render info inline displays a blank header container on each story.

## What I did
Instead of unconditionally rendering the header container and filling it with the (possibly `null`) result of `_getInfoHeader()`, I check the result first, and render the container conditionally.

## How to test
Check the `'simple usage (no header)'` example. Before this change is applied, it appears with a large empty white area above the example.
screen shot 2017-06-17 at 2 35 02 pm

After this change is applied, the empty white area is absent.
screen shot 2017-06-17 at 2 32 22 pm

### CODE REVIEW

**Comment by duncanbeevers** [comment]
Looks like this is a duplicate of https://github.com/storybooks/storybook/pull/1297/files

Feel free to take whichever approach seems appropriate.

**Comment by shilman** [comment]
@duncanbeevers this one is a little cleaner, so I'm going to merge it. thanks for the PR!

**Comment by shilman** [comment]
@duncanbeevers **NOTE:** we are planning to move the info addon into a panel soon: #1147

**Review by shilman — APPROVED** [review]
LGTM!

**Pull request merged**
