### PR TITLE
Preact: Add automatic ArgType extraction

### PR DESCRIPTION
**Pull request by ccsenter**
Closes #

Related issues: 
https://github.com/storybookjs/storybook/issues/14876
https://github.com/storybookjs/storybook/issues/19739

## What I did
The Preact framework and renderer in Storybook still does not have an out-of-box support for docs annotations although the current [feature matrix](https://storybook.js.org/docs/configure/frameworks-feature-support#community-frameworks) shows full docs support for Preact, I tried to tackle this issue by:

1. adding the same docs support for the Preact renderer as we have today for React (mostly copied the src/docs folder from 
2. adding a new docs preset for preact-webpack following the same pattern found in the react-webpack preset  (see framework-preset-preact-docs.ts)
3. adding missing TS support for the preact-webpack5/default-ts sandbox storybook template: although this template is available when creating a sandbox, the proper TS entries under renderers/preact/template/cli were missing, the task was always creating JS components
4. adding a test file for the framework-preset-preact-docs preset

I have limited knowledge on the Storybook monorepo ecosystem so I probably missed some pieces (especially the test cases) or did not think on all the implications but these changes should be a good starter to have the docs support be complete for Preact as well. 

**Note:** at the time of this PR submission I was not able to create any sandbox application in my local repo, not sure it is my environment or it is broken but I keep getting:
Error: Command failed with exit code 1: node /home/opc/Git/ccsenter/storybook/code/lib/cli/bin/index.js repro react-vite/default-ts --output /home/opc/Git/ccsenter/storybook/sandbox/react-vite-default-ts --no-init
🚨 Failed to download sandbox template: TypeError: fetch failed
🚨 Failed to create sandbox

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Run a sandbox for template: yarn task --task generate --template preact-webpack5/default-ts
2. Open Storybook in your browser: from sandbox/preact-webpack5-default-ts run yarn storybook
3. Click on on Button example and notice the available Description and Default column values in ArgsType table

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by JReinhold** [comment]
I wonder how this compares to https://github.com/storybookjs/storybook/pull/20631 that has similar intentions. Any thoughts @KrofDrakula ?

**Comment by KrofDrakula** [comment]
@JReinhold Not sure; the original PR I submitted covered a wide range of different component shapes and inferrence, but it is also quite out of date by this point since it has been stale for a while waiting for input. There is also the potential of being extended to support Vue, Solid and Svelte quite easily.

It would need a bit of TLC, but I've been swamped at my day job to do any meaningful work on it in the meantime.

**Comment by ccsenter** [comment]
Hello,
do you guys need anything from me at this point? Is there an obstacle that prevents the review (besides the time factor of course) where I can maybe contribute? Please let me know if I could be of any help.

**Comment by yannbf** [comment]
Hey @ccsenter thanks a lot for your contribution. We're currently quite busy with the preparations of Storybook 8 (which is currently in beta) so it might take us some time to do a proper review of your PR, please bear with us!

cc @shilman @vanessayuenn

**Comment by JReinhold** [comment]
Thanks for the PR!

This looks like mostly a copy of the React implementation with some minor tweaks. As it stands today we're not ready to commit to maintaining this double functionality.

In the future we might revisit this if we can implement it in a more maintainable way where we share the logic between multiple renderers or something similar.

**Pull request closed without merging**
