### PR TITLE
docs: ✏️ Refactor all img src with absolute URL's

### PR DESCRIPTION
**Pull request by eubenesa**
Issue:

N/A

## What I did

Update all `img` `src` attributes with absolute URL's . 🎉 

## How to test

N/A

### CODE REVIEW

**Comment by ndelangen** [comment]
Hey @eubenesa, could you tell me why this is preferred?

**Comment by shilman** [comment]
@ndelangen This is so the images show up properly on NPM

**Comment by ndelangen** [comment]
This will make it impossible to link to a newly added image, since it won't be on master yet.

**Comment by shilman** [comment]
@ndelangen then link to next? it's broken on NPM and makes our packages look low quality. do you have another idea?

**Comment by ndelangen** [comment]
I'd say it should be fixed on NPM's side, so effectively no, not better ideas 😢

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
@ndelangen could we possibly do this automatically in `prepare.js`?

**Pull request merged**
