### PR TITLE
Removes default CSS margins on viewport

### PR DESCRIPTION
**Pull request by quentind**
Related to issue #7724 and [PR#7640](https://github.com/storybookjs/storybook/pull/7640/files)

## What I did

This resets the default CSS margins on the body element. This prevents having vertical and horizontal scrollbars on the preview viewport as is the case in version 5.1.10, for instance.

This also fixes a regression on the latest version compared to the [live examples](https://storybooks-official.netlify.com/?path=/settings/about) running on 5.1.3, where there is no whitespace around the preview area.

This 8px whitespace -- the browsers' default margin on the body -- around the preview area is not desirable in my opinion, especially when the previewed component has a width of 100% or is simply a _block_ element.

### CODE REVIEW

**Comment by shilman** [comment]
@quentind How does this affect the centered addon zooming behavior that the original PR was trying to fix? Regardless, this fix is more important than the original PR, but it would be great to know whether we'll need to revisit that issue. Thanks!

**Comment by quentind** [comment]
@shilman I'm not experiencing any issues with the centered addon on 5.1.10 + the changes I've suggested.

My understanding is that the changes from [PR#7640](https://github.com/storybookjs/storybook/pull/7640/files) can be fully reverted actually since they were simply accounting for the margin on the `<body>` which is removed by my PR.

So [this line](https://github.com/ndom91/storybook/blob/12bf6aae2063f67736d88ce1ea0a07ec7af82ec5/lib/ui/src/components/preview/iframe.js#L31) can be reverted back to:

```diff
- width: `calc(${nextProps.scale * 100}% - 16px)`,
+ width: `${nextProps.scale * 100}%`,
```


Thank you for the feedback.

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
@quentind can you add the change you suggest in this PR?

**Comment by quentind** [comment]
@shilman Done! Thanks

**Comment by shilman** [comment]
Thanks @quentind. Waiting to merge this until we figure out the implications to visual regression tools that depend on this.

**Comment by shilman** [comment]
@ndelangen why does this PR not show any changed files?

**Comment by ndelangen** [comment]
Because after merging in next, there were none. I could have just closed the PR, but I think merging makes for a better indication that @quentind contributed, and that's appreciated.

**Comment by NMinhNguyen** [comment]
@ndelangen having installed `5.3.0-alpha.15` and looking at `next` branch, I have a suspicion that this change never made it in:

https://github.com/storybookjs/storybook/pull/7742/commits/4fc3b6187c54452971b53a57f8d23a8856f51c78 (commit that seems to have been due to a merge conflict, and you can see code removed)

https://github.com/storybookjs/storybook/blob/1d517d0/lib/core/src/server/templates/base-preview-head.html (`next` branch without those lines of code)

**Pull request merged**
