### PR TITLE
Fix typo in CSS pseudo selector

### PR DESCRIPTION
**Pull request by rygine**
Issue:

## What I did

Replaced `laste-of-type` with `last-of-type` in a CSS selector.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Thanks so much @rygine !! Fix looks good to me 🙈

**Review by ndelangen — APPROVED** [review]

**Comment by IanVS** [comment]
Hi, is there a reason not to merge this PR?

**Comment by MichaelArestad** [comment]
@shilman This is good to go. Can you merge when you get a chance?

**Comment by ndelangen** [comment]
Yeah It's labelled `patch` so @shilman should be picking it soon-ish.

**Comment by IanVS** [comment]
Oh cool, I missed that, thanks!

**Pull request merged**
