### PR TITLE
Add hierarchySeparator to README

### PR DESCRIPTION
**Pull request by joscha**
Add `hierarchySeparator` example.

### CODE REVIEW

**Comment by shilman** [comment]
@joscha @igor-dv @ndelangen vote for `'/'` as the one we push users towards. And I think Norbert doesn't even want it to be configurable?

**Comment by joscha** [comment]
I am fine either way - I have a preference for `.`, but can arrange myself with anything else as well :)

**Comment by igor-dv** [comment]
At the current project I am working on, we use `'.'` syntax, that actually was inspired by [this](https://storybook.js.org/basics/writing-stories/#prefix-with-dots). But there is nothing tragic to change it.
(Maybe worth it to change the docs as well)
 
@ndelangen why not to expose this as a setting ?

**Comment by ndelangen** [comment]
Having it configurable makes life more difficult for us in the long run.

Imagen webpack inline-loaders-syntax being configurable, what a mess that would quickly turn into.
We need to be careful to add special syntax into a string. It needs to make sense.

I don't think it makes a whole lot of sense to make this configurable other than, in 1 documentation-page we advocate for another character.

From what I hear everyone is actually OK with the `/` character, but some slightly prefer a `.`

I think we need a good **why** to increase the api-surface.

How about this: I'll do a poll on twitter

**Comment by joscha** [comment]
> How about this: I'll do a poll on twitter

sounds good to me!

**Comment by ndelangen** [comment]
https://twitter.com/storybookjs/status/884749480259710976

**Comment by joscha** [comment]
One question that just occured to me - dots have been advocated a while: https://storybook.js.org/basics/writing-stories/#prefix-with-dots that's why we initially chose them. Has that changed? Is there special logic anywhere to do matching against dots in the search?

**Comment by danielduan** [comment]
Is there a middle ground we can go for? maybe `/` as default with an option for `.`?

**Review by ndelangen — APPROVED** [review]
Let's just go for it.

Please change default to `/`

**Comment by joscha** [comment]
changed to `/`, however in docs only.

**Comment by igor-dv** [comment]
I'll add the default in code later today/tomorrow

**Comment by shilman** [comment]
Merging and leaving @igor-dv for the code followup 👍

**Pull request merged**
