### PR TITLE
Angular: Reduce the warnings from `ts-loader` via stricter list of `includes`

### LINKED ISSUE #24487: [Bug]: tsconfig.json generated for Angular projects out of the box should not result in warnings
### Describe the bug

Since 7.5, webpack will produce more warnings that were previously hidden. We should make sure an out-of-the-box Angular projects can be run without these warnings.

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #24487

## What I did

I changed the `includes` list so it only targets story files.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

@valentinpalkovic & @yannbf could you assist me in remembering if this was the solution we discussed on Tuesday?

@yannbf you had a project that showed the symptoms from #24487 was it this project: https://github.com/bitwarden/clients ?

We might want to release a canary of this and test it out?

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

**Comment by ndelangen** [comment]
@valentinpalkovic I could use your help here 🙏

**Comment by valentinpalkovic** [comment]
@ndelangen I am a bit confused here. Now, it seems that every file part of the compilation must be mentioned. When we tested things, it was necessary to add only the entry points, instead of all files. I will take a closer look on monday.

**Comment by ndelangen** [comment]
Do we keep this open @valentinpalkovic ?

**Comment by valentinpalkovic** [comment]
Yes we do.

**Review by valentinpalkovic — APPROVED** [review]

**Pull request merged**
