### PR TITLE
Update ember docs for ember-cli-storybook@0.1.0

### PR DESCRIPTION
**Pull request by billpull**
Issue: Ember docs have unnecessary steps

## What I did

In ember-cli-storybook@0.1.0 the addon installs the necessary `@storybook/ember` dependencies and creates files needed to start using Storybook. Also removed section about creating a `package.json` file via `npm init` since ember applications & addons should already be configured via ember-cli.

## How to test

Create an ember app via ember-cli & `ember install ember-cli-storybook`

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
I don't see any dep on `@storybook/ember` in `ember-cli-storybook`, so I don't think this is an optional step.

@gabrielcsapo can you confirm?

**Comment by billpull** [comment]
This [`afterInstall`](https://github.com/storybooks/ember-cli-storybook/blob/e8e11387bf2ff4ec9e26115c41a74822aedd8460/blueprints/ember-cli-storybook/index.js#L5) step in the addon configuration will install the needed deps.

https://ember-cli.com/api/classes/Blueprint.html#method_addPackagesToProject

**Comment by shilman** [comment]
OK thanks for the clarification @billpull -- I don't use ember so I'll let @gabrielcsapo 

I just didn't see reference to `@storybook/ember` anywhere in `ember-cli-storybook` so it looked suspicious 😉

**Comment by gabrielcsapo** [comment]
@shilman would you be able to help me publish ember-cli-storybook under @storybook? So we can keep the library under the storybook namespace.

**Comment by gabrielcsapo** [comment]
Merging this as this is accurate right now, will update when we update the location of ember-cli-storybook. Thanks @billpull!

**Comment by gabrielcsapo** [comment]
Wait is this needed? This information exists since I added it in https://github.com/storybooks/storybook/commit/d6ed6fffc2ec22e845054b48384aabaddc0daa5f?

**Comment by gabrielcsapo** [comment]
@shilman we probably need to revert this.

**Comment by shilman** [comment]
@gabrielcsapo Sure. Let's sort it out after v5 is released

**Pull request merged**
