### PR TITLE
fix build command for netlify

### PR DESCRIPTION
**Pull request by ndelangen**
fix netlify config

### CODE REVIEW

**Comment by ndelangen** [comment]
@tmeasday we have a missing script now:
> 10:41:17 AM: Usage Error: Couldn't find a script named "build-storybooks".

So we need to find out what to actually build and upload to netlify.

**Comment by tmeasday** [comment]
> So we need to find out what to actually build and upload to netlify

We don't have a single script that builds all templates (would we want one anyway, I'm not sure?). We should probably discuss this.

**Comment by ndelangen** [comment]
I noticed the `cd code` missing.

As all examples are removed this will eventually become empty, contain nothing, and should therefore be removed.
What to replace it with?

We should discuss that with the DX team perhaps?

I think it doesn't need to be in the monorepo?

In fact come to think of it, we likely have all we need here:
https://github.com/storybookjs/repro-templates-temp/

**Comment by tmeasday** [comment]
We definitely need to discuss. Do people want to see our sandbox tests stories in various templates? I'm really not sure.

They likely want to see our two "internal SBs" (one for `components`, one for `blocks`). They might want to see some other example "complete" storybooks for other frameworks. But I'm not sure exactly what value the template sandboxes give. Maybe there's value in just the fact that they work, but then maybe the pure repro templates are enough.

**Comment by ndelangen** [comment]
Whatever we decide to do, we should ensure the CI step isn't broken.

Let's schedule a meeting with some folks of the DX team to figure out how to best replace this.

**Pull request merged**
