### PR TITLE
Core: Generate manager cache in smoke test, but don't use/clear any cache

### PR DESCRIPTION
**Pull request by ghengeveld**
Issue: -
Discussion: https://github.com/storybookjs/storybook/discussions/13737

## What I did

When running with `--smoke-test`, currently no manager cache is used, created or cleared. However, sometimes it's beneficial to be able to prepare (generate) a cached manager without actually starting Storybook, for example when preparing a Docker image with embedded manager cache. This change makes `--smoke-test` cache the manager it built like normal, but won't use or clear any cache it finds as was intended in #13266.

## How to test

- Is this testable with Jest or Chromatic screenshots? no
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? no

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM 🙏

**Review by shilman — CHANGES_REQUESTED** [review]
@ghengeveld Unit test are failing, can you fix?

**Comment by phated** [comment]
@shilman I believe unit tests are failing because of https://github.com/storybookjs/storybook/pull/13752 (an old, bad cache is used when a new cache is not found).

**Comment by phated** [comment]
@ghengeveld That PR was landed, but I think you need to rebase master to get that action base to run 🎉

**Pull request merged**
