### PR TITLE
Catching up to changes react-docgen@6.0.0-alpha.4

### PR DESCRIPTION
**Pull request by tnzk**
It seems like [react-docgen 6.0.0-alpha.4 introduced breaking changes](https://react-docgen.dev/docs/release-notes/react-docgen#600-alpha4) that Storybook 7.0.0-beta.54 relies on.

As they all look just a small set of trivial changes, after I debugged in [de-obfuscated version of react-vite/src/plugins/react-docgen.ts](https://github.com/storybookjs/storybook/blob/9d9f9f026bd7e68ad495cc633076bd1775a05cf6/code/frameworks/react-vite/src/plugins/react-docgen.ts), I decided to create this PR for anyone with working environment at hand might fix this.

Of course, I'd be happy to contribute myself if I setup dev env on my box before anyone do the fix :)

For ease of anyone with the same situation to search, I would share the error I encounteredw hen I ran "$ storybook build" below:

```
ERR! TypeError: Cannot convert undefined or null to object
ERR!     at Function.values (<anonymous>)
ERR!     at <anonymous> (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:97:16)
ERR!     at <anonymous> (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:7:36)
ERR!     at <anonymous> (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:145:53)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at Object.M (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:145:17)
ERR!     at build (/~/me/app/node_modules/@storybook/builder-vite/dist/index.js:162:10374)
ERR!     at async Promise.all (index 0)
ERR!     at Module.build2 (/~/me/app/node_modules/@storybook/builder-vite/dist/index.js:162:12721)
ERR!     at async Promise.all (index 0)
ERR!  TypeError: Cannot convert undefined or null to object
ERR!     at Function.values (<anonymous>)
ERR!     at <anonymous> (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:97:16)
ERR!     at <anonymous> (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:7:36)
ERR!     at <anonymous> (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:145:53)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at Object.M (/~/me/app/node_modules/@storybook/react-vite/dist/preset.js:145:17)
ERR!     at build (/~/me/app/node_modules/@storybook/builder-vite/dist/index.js:162:10374)
ERR!     at async Promise.all (index 0)
ERR!     at Module.build2 (/~/me/app/node_modules/@storybook/builder-vite/dist/index.js:162:12721)
ERR!     at async Promise.all (index 0)
```

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by ndelangen** [comment]
@tnzk We're not going to merge this soon, because of the feaure-freeze for 7.0.

In fact I'm afraid this might never be merged, because:

- I'm not sure this PR works as-is.
- Long term we want to move away from having project-annotations injected via builders. We want to build a annotation-server that runs outside of the builders.

**Comment by tnzk** [comment]
Makes sense

**Comment by ndelangen** [comment]
We appreciate your time and effort that you put into this. Thank you. Sorry we couldn't merge your PR.

**Comment by tnzk** [comment]
No need to be sorry, thanks for mantaining Storybook :)

**Pull request closed without merging**
