### PR TITLE
[react-native] fix drawer width

### PR DESCRIPTION
**Pull request by ahanriat**
## Fix the navigation drawer width
simulator screen shot - iphone x - 2017-11-13 at 15 35 22
Issue:

## What I did
The navigation drawer width was based on the `screenWidth / 2` while the **StoryListView** itself was based on a `maxWidth: 200` which could lead to the visibility of the drawer in case the 
`screenWidth / 2 < StoryListView width` 

I've just remove the `MinMaxWidth` component and put a fix width to the drawer (standard behavior).

## How to test

Is this testable with jest or storyshots? Maybe

Does this need a new example in the kitchen sink apps? No

Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ndelangen** [comment]
Hello @ahanriat Thank you for contributing!

Do you think you could run the tests, update the snapshots and push?

This looks good to me, @danielduan ?

**Review by danielduan — APPROVED** [review]
should fix https://github.com/storybooks/storybook/issues/2301 thanks!

**Comment by danielduan** [comment]
Actually, please update the snapshot test that way we can merge it. It came from your emoji in the story name 👍

**Comment by ahanriat** [comment]
🎉 thanks guys!

**Comment by ndelangen** [comment]
🎉

**Pull request merged**
