### PR TITLE
Use Flow instead of prop-types in lib/components

### PR DESCRIPTION
**Pull request by Hypnosphi**

### CODE REVIEW

**Review by danielduan — APPROVED** [review]

**Comment by ndelangen** [comment]
I'd like @shilman's approval on this before we merge this. 

We need to discuss this properly before adding it to our codebase.

**Comment by shilman** [comment]
Thanks for pinging me @ndelangen 

I've used Flow on projects and like it. However I'm skeptical of adding this to Storybook. I think it will make it harder for people to contribute to the project and possibly even scare people off, especially because  `@storybook/components` will be a package where we're bound to have a lot of first-time contributors.

In the interest of making Storybook as open as possible, I'd vote to hold off on adding this until Flow is a lot more popular/mature than it is now.

**Comment by ndelangen** [comment]
I support your statement @shilman 

This codebase will definitely see higher numbers of 'first-time-contributions'. Some of those will be people not too familiar with react or flow or even JS (think about people changing styling).

I want to be welcoming to those contributors, and I think adding new syntax goes against this credo.

I really really appreciate you going out of your way to improve the codebase and all the stuff you do @Hypnosphi. 

👍👍👍

**Comment by Hypnosphi** [comment]
> I think it will make it harder for people to contribute to the project and possibly even scare people off, especially because @storybook/components will be a package where we're bound to have a lot of first-time contributors.

> This codebase will definitely see higher numbers of 'first-time-contributions'. Some of those will be people not too familiar with react or flow or even JS (think about people changing styling).

Those are perfectly valid points! But they also apply to Glamorous, in my view. Should we maybe use CSS then? With CSS modules or BEM conventions, of course

**Comment by ndelangen** [comment]
Yeah some point apply to glamorous indeed. In that case I feel it's worth it, and it's not adding an new syntax: We're already using JS objects for styling.

I'm personally happy to do some hand-holding to help people overcome the glamorous barrier.
With FlowType I can't.

CSS-modules add considerable complexity in the webpack config department, there's quite a bit of 'magic' there.

**Comment by shilman** [comment]
I also have reservations about glamorous!!! But fewer concerns because the barrier to entry is much lower. 😄

**Pull request closed without merging**
