### PR TITLE
 Addon-docs: add escape hatch css classes in docpages

### PR DESCRIPTION
**Pull request by Jeremie-Chauvel**
Issue: #8502 

## What I did
Implemented escape hatch to style docpages
## How to test

- Is this testable with Jest or Chromatic screenshots? yes -> update WIP
- Does this need a new example in the kitchen sink apps? don't think so
- Does this need an update to the documentation? probably WIP

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by Jeremie-Chauvel** [comment]
I'm a little lost concerning where I should add the documentation of this change ?

Concerning the tests, I'm surprised that my change didn't break any ? Should I create an additionnal story with overriden style to test the change ? (In chromatic ?)

**Comment by ndelangen** [comment]
@shilman This is something for us to consider... 

I feel like we should -at some point- have a structured method for automatically adding these escape-hatch-css-classes to our components, rather then do it manually all over the place. We'll eventually forget them when we refactor.

I personally don't feel like adding a ton of tests for them either.
Maybe a few, to ensure the classes are there.

**Review by shilman — COMMENTED** [review]
Thanks for for fixing this @Jeremie-Chauvel!

Generally looks good. I'm wondering, though, in some cases you are passing `className` through various layers of indirection. Why can't we just set the `className="sbdocs sbdocs-argstable"` directly where its used rather than adding the extra complexity of passing it around as a variable?

**Comment by Jeremie-Chauvel** [comment]
It's been long enough, I'm not quite confident I remember such decision reasons, I will investigate it on occasion.

**Pull request closed without merging**
