### PR TITLE
Insert 'yarn' command between 'cd storybook' and 'yarn bootstrap (--core)'

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Yeseul Jeon <yeseouler52@gmail.com>

Issue:

## What I did

This is the error message that I encountered when I executed '**yarn bootstrap --core**' command **without trying 'yarn' command before.** 

```
internal/modules/cjs/loader.js:796
    throw err;
    ^
Error: Cannot find module 'inquirer'
Require stack:
- C:\Users\Yeseul JEON\git\storybook\scripts\bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Timeout.run [as _onTimeout] (C:\Users\Yeseul  JEON\git\storybook\scripts\bootstrap.js:32:20)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Yeseul  JEON\\git\\storybook\\scripts\\bootstrap.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this  command.`
```

So I inserted 'yarn' command where it was missing in Contributing to Storybook:
(url: https://github.com/storybookjs/storybook/blob/master/CONTRIBUTING.md))
    1. Testing against master > 1.Download the latest version of this project, and build it:
    2. Reproductions > In the monorepo

Actually, this was already mentioned in the same page if you scroll down the page a little bit more: Development Guide > Initial Setup. But to keep a consistency of Setup guide & avoid a confusion, I hope the storybookjs team to consider updating upper two parts in the Contributing to Storybook page (CONTRIBUTING.md).

### CODE REVIEW

**Comment by shilman** [comment]
@yeseouler thanks for your PR! however, i'm not able to replicate the problem -- running `yarn bootstrap` or `yarn bootstrap --core` works for me without needing to run `yarn` first... 🤷‍♂

**Comment by yeseouler** [comment]
Thanks for taking time to review my PR!

I understand that you were not able to replicate this error since all the Mac (iOS) users in my team didn't encounter this problem when they run `yarn bootstrap --core` or `yarn bootstrap` without running `yarn` first. 

I'm not 100% sure, however, I think that error appears to windows environment like mine since OS was the only difference when me and my team members followed the steps written in Contributing to Storybook (CONTRIBUTING.md). 

Just to help newbies to storybookjs like myself, could you please reconsider adding at least a comment something like  

> try `yarn` command 

 if it doesn't work like mine did? 

Also, since _running `yarn` command before trying `yarn bootstrap --core` or `yarn bootstrap`_
didn't come out from nowhere (it's already written in  Development Guide > Initial Setup), I believe there won't confuses other users but help them if the storybookjs updates the current document. 😬

**Comment by shilman** [comment]
Hi @yeseouler I modified your PR slightly to make the instructions a little more explicit. Thanks so much for your contribution to Storybook! 감사합니다! 🙏

**Review by shilman — APPROVED** [review]
잘했어요

**Pull request merged**
