### PR TITLE
React: Add ComponentStory convenience type

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Added a convenience type, `ComponentStory` for the common case of a story that spreads args directly into a React component.

```diff
- // Before
- const Template: Story<React.ComponentProps<typeof TsButton>> = (args) => <TsButton {...args} />;
+ // After
+ const Template: ComponentStory<typeof TsButton> = (args) => <TsButton {...args} />;
```

@tooppaaa @gaetanmaisse @ndelangen @tmeasday WDYT?

@yannbf also has some other ideas [which are documented here](https://www.typescriptlang.org/play?#code/PTAEFpK6dvNAYQPYFsAOyB2BTLAXUAMwEsAbHCeamgKBI2QCdCAlHAQwGN8AaUAN6gAYgFcsPEthSNcBfjMxz8ABSbJ0AZ34ApAMoANAKIVUefCiyb8TUT2agAvsXWpQAciace7gNy1afABPdEoAWSDFbHM1DU1QAF5BWlBQLA4zAC5QayYSLABzXhTQDgKcbKxRVAAjHCZixwCubGtQCKjlYRImawA5ZHwOfCksbLEJEek0JXMAHg6Z6IJYrQA+RNAACiF0sycASkSNuYATEgA3NYE9nEc54HOr5tbCRdlzPRwWrFOBoamWE2OzSGUojmy71mK3UWiOCROT2ut3uj0uaxeVjekSWygAklgyPkcKt4kkQbcnNldmDsrl8kVSuU6TYGYdjqAzuibmDUUjMW0oct8BNJNh-sNRpsiOIxUCKWCqe0cR8YXEjgISl58KImECuVceWY+ejaE0AiAqDRrXBQHp8MwgjVkMgANagYKheI2n1QegEepEbiUAAiOCDojI+HtjrmAEEmAVNBtNakOInNNkVOmRhwyPGMxjzZaY0wgtk4x6QpR8AALYageu-CjxZ110AJpOgBydcylX6gfJEerxEj4eLoWGaQLVu0OstzAAqGySi9AOAAHvg8Kd4qLAb2CHMh-VQCoNgB+UBhiNR0tBOaH1RTpdrDbZG8cSPR+cP5cWsAnznR1sj0UIuBIUguCrUJiAcdAOE0TQ2Q4UAWlVQhPRwGdYKfe9H3XLcd3iV0cCCZAiFAfQDAAOgJVkrBILgTBwMwCHiAAfKjDBYtiLFeWx7CYOYOCwII302T9v3wp9SUfN8AloS1fRU8BgLyHB4lICgrVU60ANAIwNwydAdIARlA38CyTDEfjaAB1Mda07TN1IfIVlFJFdtnhFMnFoRy6xcmj0y7JJU1BLJQAAIh0ZBaywaLilSYkNxIawYlhRd62jWtkEjU4jCYdQmGpJpizAIyTJ0gAmSzYywiikFxcxbNeNyqowCh6oXRrKI88xul6fAJUBbytl8wR-PvTrTJwEKM02CLbmyaKAAkcDIMhkCSkpUvS7c1XQbLhj0PKCqKkqyrNAVCBm4yupwOq3LmPrlTw75sD+QZJWwcbJqEJp7uqp6FrC5JUhWmKNq2nbksHXA0oyo6Tty-KyEK4rmGu807Lu39ZooABmHqHzegaCAJIlcC84EAemgmHrmomwbJCHIoqaHNu23aUsRg7Mo0VGzvRzGrsEcrbo6pmKAAFlJ17qyaimRVlQFRtGf6OUB2hgce2XWaWkoofW7m4b2-nkefIWcpFi6sdKiWbqUyqZcoEnmow-C3qfNqsU96F8EJzm8Ks8mVUDob+h+sa6e1-yn2Dw3wuN2kudh3mEc3AWUdt86Mcu7Gndx9rE7d57Q4apX+oj4Uvh+b6AU1uOESmpoy5Bmrk-Zk2YZ5+H9qt1ZhfzsWi4ESXaDxgPhWDj3K966v3paynCWJWnyXp9uV6Dt2WdCtnlrT02M4Hy3Dut4689FwvHYn53p47x755372l5V-dRg1v6W787eMLnt3I+UUT79wttnIeWVr723FvfJoQA)

## How to test

CI passes

### CODE REVIEW

**Comment by yannbf** [comment]
This is a great addition, and it will work as well for components which have inline props like:
```jsx
const Button = ({ label, color }: { label: string, color: string }) => <.../>
```

Adding to that, in the [typescript playground](https://www.typescriptlang.org/play?#code/PTAEFpK6dvNAYQPYFsAOyB2BTLAXUAMwEsAbHCeamgKBI2QCdCAlHAQwGN8AaUAN6gAYgFcsPEthSNcBfjMxz8ABSbJ0AZ34ApAMoANAKIVUefCiyb8TUT2agAvsXWpQAciace7gNy1afABPdEoAWSDFbHM1DU1QAF5BWlBQLA4zAC5QayYSLABzXhTQDgKcbKxRVAAjHCZixwCubGtQCKjlYRImawA5ZHwOfCksbLEJEek0JXMAHg6Z6IJYrQA+RNAACiF0sycASkSNuYATEgA3NYE9nEc54HOr5tbCRdlzPRwWrFOBoamWE2OzSGUojmy71mK3UWiOCROT2ut3uj0uaxeVjekSWygAklgyPkcKt4kkQbcnNldmDsrl8kVSuU6TYGYdjqAzuibmDUUjMW0oct8BNJNh-sNRpsiOIxUCKWCqe0cR8YXEjgISl58KImECuVceWY+ejaE0AiAqDRrXBQHp8MwgjVkMgANagYKheI2n1QegEepEbiUAAiOCDojI+HtjrmAEEmAVNBtNakOInNNkVOmRhwyPGMxjzZaY0wgtk4x6QpR8AALYageu-CjxZ110AJpOgBydcylX6gfJEerxEj4eLoWGaQLVu0OstzAAqGySi9AOAAHvg8Kd4qLAb2CHMh-VQCoNgB+UBhiNR0tBOaH1RTpdrDbZG8cSPR+cP5cWsAnznR1sj0UIuBIUguCrUJiAcdAOE0TQ2Q4UAWlVQhPRwGdYKfe9H3XLcd3iV0cCCZAiFAfQDAAOgJVkrBILgTBwMwCHiAAfKjDBYtiLFeWx7CYOYOCwII302T9v3wp9SUfN8AloS1fRU8BgLyHB4lICgrVU60ANAIwNwydAdIARlA38CyTDEfjaAB1Mda07TN1IfIVlFJFdtnhFMnFoRy6xcmj0y7JJU1BLJQAAIh0ZBaywaLilSYkNxIawYlhRd62jWtkEjU4jCYdQmGpJpizAIyTJ0gAmSzYywiikFxcxbNeNyqowCh6oXRrKI88xul6fAJUBbytl8wR-PvTrTJwEKM02CLbmyaKAAkcDIMhkCSkpUvS7c1XQbLhj0PKCqKkqyrNAVCBm4yupwOq3LmPrlTw75sD+QZJWwcbJqEJp7uqp6FrC5JUhWmKNq2nbksHXA0oyo6Tty-KyEK4rmGu807Lu39ZooABmHqHzegaCAJIlcC84EAemgmHrmomwbJCHIoqaHNu23aUsRg7Mo0VGzvRzGrsEcrbo6pmKAAFlJ17qyaimRVlQFRtGf6OUB2hgce2XWaWkoofW7m4b2-nkefIWcpFi6sdKiWbqUyqZcoEnmow-C3qfNqsU96F8EJzm8Ks8mVUDob+h+sa6e1-yn2Dw3wuN2kudh3mEc3AWUdt86Mcu7Gndx9rE7d57Q4apX+oj4Uvh+b6AU1uOESmpoy5Bmrk-Zk2YZ5+H9qt1ZhfzsWi4ESXaDxgPhWDj3K966v3paynCWJWnyXp9uV6Dt2WdCtnlrT02M4Hy3Dut4689FwvHYn53p47x755372l5V-dRg1v6W787eMLnt3I+UUT79wttnIeWVr723FvfJoQA) that michael shared, you will find both solutions:

1 - **Story\<typeof Component\>** (under Example 2)
Extension of the existing `Story` type, making it flexible enough to handle either `Story<Args>` or a `Story<typeof Component>` scenarios.

2 - **ComponentStory\<typeof Component\>** (under Example 3)
Type specifically created to extract props of a component. Won't and shouldn't work as `ComponentStory<Args>`.

A couple of things to consider:
- Which solution is less confusing and might bring best value to the users
- Should we already handle the Strict type here? (see discussion from #14550), and depending if we do, we might have either `Story` and `StrictStory` types, or `Story`, `StrictStory`, `ComponentStory` and `StrictComponentStory`.

**Review by ndelangen — APPROVED** [review]

**Comment by yannbf** [comment]
@ndelangen what are your thoughts? :D

**Comment by ndelangen** [comment]
I like it, the only thing I'm unsure about is the addition of a new versioned ts-definition file. I'm not sure that's required considering the definition is an addition anyway?

**Comment by shilman** [comment]
@ndelangen happy to remove it -- just did it for consistency (figuring we'd collapse it all at some point anyway)

**Comment by ndelangen** [comment]
Not a blocker @shilman

**Comment by yannbf** [comment]
@shilman Just thought of another scenario: `Meta`, which also receives args as generic. Will we end up `Story`, `ComponentStory`, `Meta`, `ComponentMeta`, `StrictStory`, `StrictComponentStory`, `StrictMeta` and `StrictComponentMeta`?

**Review by gaetanmaisse — APPROVED** [review]

**Comment by shilman** [comment]
@yannbf Great point. I'll add `ComponentMeta` to the PR. I don't think we need `StrictComponent{Meta,Story}` -- users can construct that from `Strict{Story,Meta}` by hand. If that becomes the popular way to type stories, we can revisit the type system in 7.0. WDYT?

**Pull request merged**
