### PR TITLE
Improve the interaction readme

### PR DESCRIPTION
**Pull request by 0xR**
The original docs show a story without a template. An example with template is more useful for most people.

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @0xR thanks a lot for your contribution! The reason it does not have a template is because the snippet is using [CSF 3.0](https://storybook.js.org/blog/component-story-format-3-0/) which is the newer format of writing stories and it's also framework agnostic. [In the storybook docs](https://storybook.js.org/docs/react/essentials/interactions#writing-interactions) there are React examples with the template though!

@shilman WDYT? Should we add framework specific examples to the README?

**Comment by shilman** [comment]
@yannbf @ghengeveld  There's a page for interactions here:

https://storybook.js.org/docs/react/essentials/interactions

I'd probably strip down the README, point at this page, and potentially add framework-specific examples (as appropriate) to the page, since our documentation system supports framework-specific snippets

**Comment by yannbf** [comment]
> @yannbf @ghengeveld There's a page for interactions here:
> 
> https://storybook.js.org/docs/react/essentials/interactions
> 
> I'd probably strip down the README, point at this page, and potentially add framework-specific examples (as appropriate) to the page, since our documentation system supports framework-specific snippets

Sounds like a good idea. @0xR is that something you're interested in contributing? Else I could do that.
Thanks for bringing this to our attention!

**Comment by ndelangen** [comment]
@shilman @yannbf These lines should still exist in CSF3, correct?
https://github.com/storybookjs/storybook/pull/16938/files#diff-0ee8c294d04117b0485604dc0768e93b320649a4ae2812eb13298d4547ac97f0R44-R50

You just don't need the template or bind it.
I could update the PR to make it valid CSF3, if you'd like.

The documentation page being linked to, has code that is nearly identical to what this PR updates the code to in the README.

I think the PR should be merged, and then the docs can be updated in both places to show CSF3 when that's ready, but we should be consistent.

Let's loop in @jonniebigodes about the other docs changes if those need to happen.

I agree we should keep our README files to a minimum to lower the maintenance burdon, boilerplate & framework preferism.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
