### PR TITLE
CLI: Add aurelia detection

### PR DESCRIPTION
**Pull request by tooppaaa**
Issue: 
Aurelia is not part of the detected framework
Preparatory work for e2e on this framework

## What I did
Add detection

## How to test

- `npx aurelia-cli@ new aurelia-latest --unattended`
- sb init (locally of course)

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM but let's merge when we start 6.1

**Review by yannbf — COMMENTED** [review]
Nice work!
I believe there are different ways of setting up Aurelia projects, and one of them includes using jspm (check [here](https://aurelia.io/docs/build-systems/jspm/setup#running-the-unit-tests) and [here](https://github.com/aurelia/dialog/blob/master/package.json#L47)) and such format is not in our detection, BUT I have no experience with Aurelia, so let's ask the expert!

Hey @brandonseydel, what are the possible ways to detect if a project is an Aurelia project? Are the generated templates via storybook CLI compliant with older projects or only new ones? We need to figure out if a user has an Aurelia project and runs `sb init` if they will get a properly set Storybook for them, and even if we support all versions. Thanks!

**Review by ndelangen — APPROVED** [review]

**Comment by brandonseydel** [comment]
@tooppaaa this is aurelia 2 and such this will not work.

**Comment by tooppaaa** [comment]
@brandonseydel you mean this `dependencies: ['aurelia-bootstrapper'],` ? I'm not sure what to put here, I'm happy to use your suggestions :)

**Comment by brandonseydel** [comment]
'aurelia' || '@aurelia/runtime'

**Pull request merged**
