### PR TITLE
Angular: Fix allowed types of webpackStatsJson in angular-builder

### PR DESCRIPTION
**Pull request by hnicke**
Issue: #20520

## What I did
Backport a fix from `next` branch to `main`.

The `--webpack-stats-json` option should accept a string (a path) as well.

Note that the underlying implementation already accepts a path.
Only the schema was too strict.

## Why I did it
Our team is using chromatic.
When using chromatic with turbosnap (`--only-changed`), it does expect that the storybook-builder option `--webpacks-stats-json` accepts a string.

### CODE REVIEW

**Comment by bmayen** [comment]
🙏 This blocks Chromatic Turbosnap

**Review by valentinpalkovic — DISMISSED** [review]

**Comment by valentinpalkovic** [comment]
@shilman any idea why the pipeline is failing? Seems to be unrelated to that change. Can we force merge?

**Comment by valentinpalkovic** [comment]
@shilman Can I ignore the failing tests? Can we rely on the pipeline for branches which are based on `main`?

**Comment by shilman** [comment]
Closing as duplicate to #20296 which was released in https://github.com/storybookjs/storybook/releases/tag/v6.5.16-alpha.0 and which I'll release today in 6.5.16 proper. Thanks for your patience!

**Pull request closed without merging**
