### PR TITLE
Remove upper bound on react-native peerDependency

### PR DESCRIPTION
**Pull request by atticoos**
Issue: #1418

The goal is to allow new `react-native` versions without having to maintain an upper bounded version in Storybook. 

## What I did

Updates Storyboard's `react-native` module to allow any versions `>=0.27.0`, rather than keeping a capped upper-bound. As described in https://github.com/storybooks/storybook/issues/1418#issuecomment-313234328, if a breaking change is later introduced the next version of storyboard can set the new minimum version. This removes the need to maintain an upper bound every time `react-native` rotates out a new release. I personally think it's okay to be a little less strict here.

_Note: we cannot use `^0.27.0` since this is a prerelease, which will not be satisfied by semver_

## How to test

- Create a new `react-native` project on a version later than `0.43.x`
- Locally link `@storybook/react-native` and observe a successful installation without an invalid `peerDependency` message

### CODE REVIEW

**Review by ndelangen — COMMENTED** [review]
I'm not sure

**Review by Gongreg — APPROVED** [review]
I don't think we should lock out on versions. Especially on 0.43 when it is already quite old.

**Comment by ndelangen** [comment]
@tmeasday can you take a look at this perhaps?

**Comment by tmeasday** [comment]
I guess it comes down to how "solid" we want to be at the expense of being a bit slow. It's not difficult for someone to check each new version of RN and bump the range when we see that it works. But obviously the fact that it hasn't happened shows that no maintainer is particularly on top of this right now.

In any case I think most people ignore peer dependency warnings anyway so I suspect it's all a bit academic. I don't think npm uses them to decide which version to use or anything like that. So ultimately, it's about: for the subset of users that would be bothered by a warning about SB being incompatible with RN, is it better to be "loose" and hope for the best (not show the warning if we aren't sure we are compatible), or "tight" (show the warning if we aren't sure).

Thinking about it like that, I would suggest the latter. What do you all think?

**Comment by Rovack** [comment]
@tmeasday The concern is that for anyone still using shrinkwrap, peer dependency issues mean actual errors. In that sense, erring on the side of being too "tight" can be a very real problem as well.

**Comment by tmeasday** [comment]
Ahh! Ok so I am wrong when I say users don't typically care about peer deps.

I'm OK with loosening it then, at least until someone who is actively using RN wants to take responsibility for bumping our versions.

**Review by tmeasday — APPROVED** [review]

**Pull request merged**
