### PR TITLE
Feature/add data-tags attribute to sidebar items 

### PR DESCRIPTION
**Pull request by thehuijb**
Issue: [9209](https://github.com/storybookjs/storybook/issues/9209) Add an option to hide a story from the sidebar

## What I did
I made an adjustment to how stories are written out to the sidebar to include a `data-tags` attribute which defaults to `data-tags="none"` 

the tags can then be used to show or hide stories based on plain css selectors:
for instance one could add a rule to hide all stories with `data-tags="hidden"`:
```
[data-tags=hidden] {
  display: none;
}
```
or more complex to hide all stories that do not have a certain TAG so you could show just the stories that belong to that TAG:
```
[data-tags]:not([data-tags~=TAG] {
  display: none;
}
```
> NOTE: - these css options are not included in the PR one must add these depending on the solution they are looking for.

to add the tags to the stories you only need to add it to the default like so:
```
export default {
  title: 'Welcome',
  tags: 'hidden',
};
```
or to a specific story like this:
```
Button.story = {
  tags: 'hidden'
}
```

you can specify multiple tags using the pipe symbol `|` e.g. `tags: 'web|app'` to specify that the component or story belongs to the `web` and to the `app`
if you would add `tags: 'web|app'` to default and then add `tags: 'web'` to a story and `tags: 'app'` to another, one could show and hide different stories based on a selected TAG
if components are created under the same branch, the branch will receive the tags from all component and pipe `|` them together e.g. if one storyfile has 
```
export default {
  title: 'Components/Category/Headings',
  tags: 'web'
}
```
and another storyfile has
```
export default {
  title: 'Components/Category/Buttons',
  tags: 'app'
}
```
the resulting link in the sidebar to `Category` will have `data-tags="web|app"`

## How to test

1. start one of the example apps
2. add `tags: 'hidden'` to one of the stories files like described above
3. refresh page and inspect the stories in the sidebar with the devtools
4. see that the links in the sidebar contain `data-tags` attibutes

- Is this testable with Jest or Chromatic screenshots? NO
- Does this need a new example in the kitchen sink apps? probably NOT
- Does this need an update to the documentation? YES included

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
Thanks for putting this together! Since it's a fairly substantial change to CSF, expect a lot of back and forth on this one..

cc @ndelangen @tmeasday

**Comment by thehuijb** [comment]
thanks for adding the labels

**Comment by tmeasday** [comment]
Before adding a top-level feature to CSF for tags (which I'm not against, it has come up several times), perhaps we should use `parameters.tags` to begin with?

Also, a more general solution of allowing addons to alter the rendering of sidebar entries (combined with the above this would allow this feature to be implemented as an addon) would make a lot of sense to me. I don't have a great feel for how we could create such an API without introducing problems of addons clobbering each other though.

One idea would be to have an "area" of each sidebar item where each addon can add a DOM element. Would it work for this filtering use case to have an element `<span data-tags="x y" />`-- or is it not possible to do the CSS targetting we need with that structure?

I am thinking the obvious use case is to badge stories visually, for things like a count of failing tests (or visual changes), simply a coloured label, or even a tag element ;)

**Comment by ndelangen** [comment]
I've changed the UI code for the explorer quite a bit in https://github.com/storybookjs/storybook/pull/9210

I really like this feature a lot, but expect merge-conflicts.

**Comment by thehuijb** [comment]
> Before adding a top-level feature to CSF for tags (which I'm not against, it has come up several times), perhaps we should use `parameters.tags` to begin with?
>
> Also, a more general solution of allowing addons to alter the rendering of sidebar entries (which, combined with the above this would allow this feature to be implemented as an addon) would make a lot of sense to me. I don't have a great feel for how we could create such an API without introducing problems of addons clobbering each other though.
> 
> One idea would be to have an "area" of each sidebar item where each addon can add a DOM element. Would it work for this filtering use case to have an element `<span data-tags="x y" />`-- or is it not possible to do the CSS targetting we need with that structure?
> 
> I am thinking the obvious use case is to badge stories visually, for things like a count of failing tests (or visual changes), simply a coloured label, or even a tag element ;)

Thanks for reviewing my PR, I see your point about using parameters.tags, perhaps that would be a better approach, I'll have a look and see if I can rework this.
I personally think that allowing addons to alter the renderings in the sidebar would also be a nice addition, great idea.
The filtering would not work if you put de data-tags on a different element unless it would be the one right before the sidebar item so you would be able to select it like `[data-tags] + a` but it would make advanced filtering alot more complex.

**Comment by thehuijb** [comment]
> I've changed the UI code for the explorer quite a bit in #9210
> 
> I really like this feature a lot, but expect merge-conflicts.

I don't mind, keep up the good work.

**Comment by thehuijb** [comment]
I noticed that my PR doesn't work on mdx stories, could anyone point me in the right direction to fix that? Thanks in advance.

**Comment by ndelangen** [comment]
How come this PR has 316 commits & 200+ files changed?

**Comment by thehuijb** [comment]
> How come this PR has 316 commits & 200+ files changed?

good question, how did that happen?
I rebased on the next branch, then did some rework to fix the conflicts you predicted.
guess I'm going to have to submit a new PR

**Pull request closed without merging**
