### PR TITLE
Fix/angular cli config

### PR DESCRIPTION
**Pull request by JounQin**
Issue:

## What I did

`outputPath`, `scripts`, `styles` are required by `@angular-devkit/build-angular`, make sure it won't break if they are not presented.

## How to test

- Is this testable with Jest or Chromatic screenshots?
Yes, added.

- Does this need a new example in the kitchen sink apps?
No need.

- Does this need an update to the documentation?
No need.

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by kroeder — APPROVED** [review]
Thanks for the PR! LGTM 
Don't know why a couple of CI tests don't pass - I'll look into this 🙂

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Something in the test makes to unable to finish

**Comment by JounQin** [comment]
@ndelangen Sorry but I should not be my fault, all the merged commits have error status. I've rebased from next branch, hope it will work.

**Comment by ndelangen** [comment]
@kroeder I merged in next, hope the CI approves this time. Would you be able to give your final review?

**Comment by kroeder** [comment]
ci tests still have errors :| I also have trouble getting them green in #7747 
The changes in this PR LGTM

**Comment by kroeder** [comment]
I changed the cli test in https://github.com/storybookjs/storybook/pull/7747/commits/e187e79b9332f81c2fb07a895766bdc9f4a9798b

I also split functions in order to improve the tests. If I get CI green we can merge it in this branch. Hopefully this helps

**Comment by JounQin** [comment]
So the CI error has not been fixed?

And as I can see, the PR should not be prevented from merging like other merged PRs.

**Comment by shilman** [comment]
```
 FAIL  app/angular/src/server/__tests__/angular-cli_utils.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'filter' of undefined

      1 | import fs from 'fs';
      2 | import { basename, dirname, normalize, relative, resolve, Path } from '@angular-devkit/core';
    > 3 | import {
        | ^
      4 |   getCommonConfig,
      5 |   getStylesConfig,
      6 | } from '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs';

      at loadTsLibFiles (node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/transformers/ast_helpers.js:109:41)
      at Object.<anonymous> (node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/transformers/ast_helpers.js:46:20)
      at Object.<anonymous> (node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/transformers/index.js:14:10)
      at Object.<anonymous> (node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:26:24)
      at Object.<anonymous> (node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/index.js:13:10)
      at Object.<anonymous> (node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js:14:19)
      at Object.<anonymous> (node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/index.js:18:10)
      at Object.<anonymous> (app/angular/src/server/angular-cli_utils.ts:3:1)
      at Object.<anonymous> (app/angular/src/server/__tests__/angular-cli_utils.test.ts:3:1)
```

**Comment by shilman** [comment]
@JounQin @kroeder The test that's failing is the test that's introduced in this PR. We can't merge it in the current state, otherwise our builds would be broken for all PRs.

**Comment by JounQin** [comment]
@shilman Are you sure? The error message you mentioned seems having nothing related to this PR.

**Comment by ndelangen** [comment]
You added the test here:
https://github.com/storybookjs/storybook/pull/7485/commits/df76d4496645f9dae737969853483df2088854c1

👀

**Pull request closed without merging**
