### PR TITLE
Keycodes

### PR DESCRIPTION
**Pull request by Jessica-Koch**
Issue:

## What I did
* Refactored the state structure of keycodes.
* appropriately renders "dead" key codes/ alt gr keycodes, ie( `alt` + `J`  no longer renders `alt` + `∆`)
* fix filter search so that it is dynamic and changes based upon the current search shortcut value
* fixed lint warnings

## How to test

- Is this testable with Jest or Chromatic screenshots?
yes but i do need to update the tests to reflect the changes to the data structure
- Does this need a new example in the kitchen sink apps?
no
- Does this need an update to the documentation?
no

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
@Jessica-Koch Mind resolving the merge conflicts? Also, does this need to go out with 5.0 or is post 5.0 ok? Trying to restrict 5.0 changes to critical bugs. Thanks! 🙇

**Comment by tmeasday** [comment]
I'm happy to take care of getting this over the line. I don't think we can get this into 5.0 at this stage but we can get it out with the next release!

**Comment by shilman** [comment]
@tmeasday Cool, can we merge this later then? I'd rather deal with more conflicts at that point, rather than diverging `next` and `release/5.0` further than they already are. If that sounds OK, let's mark this with `do not merge` for the time being?

**Comment by tmeasday** [comment]
Yes fine by me. I’ll deal with any merge consequences

**Pull request closed without merging**
