### PR TITLE
Server: Initial support for @storybook/server

### PR DESCRIPTION
**Pull request by tmeasday**
I can't commit to #9250 so this is a follow up PR to try and get it over the line

@jonspalmer there are still two unresolved comments on that PR that we need to sort out:

1. Is this a mistake or did I misunderstand: https://github.com/storybookjs/storybook/pull/9250#discussion_r366776949

2. Do we need to deal with this TODO: https://github.com/storybookjs/storybook/pull/9250/files/be4d06c0cd69b2ed4a79ad390852770bfd6ccfeb#diff-83aae226cfb73b52d12dfd37ae15a411?

Also a change to `mdx.tsx` got dropped because `generateHrefWithHash` doesn't exist any more. I'm not sure if that's going to be a problem but I'll have a proper play with this once the above two questions are resolved.

### CODE REVIEW

**Comment by tmeasday** [comment]
Oop, actually I can push to your branch, closing this.

**Comment by jonspalmer** [comment]
1. I think is a bug. However, I was just pattern matching from the same code in html and web-components. Are they all bugs?
2. We do eventually want the group support but lets add it later unless anyone things its critical

the mdx.tsx stuff really has nothing to do with this PR. That was @shilman piggy backing on the PR. I'd leave it to him to comment.

**Comment by shilman** [comment]
The `mdx.tsx` change was a temporary workaround to deal with some CORS errors we were seeing on the docs in-page linking logic. I ended up fixing it properly as part of 5.3, so those changes should be backed out if they're not already.

**Comment by tmeasday** [comment]
>  Don't re-mount the element if it didn't change and neither did the story

I guess the comment implies as "neither did the story" (which is true, the story didn't change if force render is true) that the behaviour is intended. Let's leave it for now.

**Comment by tmeasday** [comment]
Going to merge from this branch

**Pull request merged**
