### PR TITLE
Core: Expose Server instance through the pluggable Builder API

### PR DESCRIPTION
**Pull request by eirslett**
This PR mirrors the changes in https://github.com/SasanFarrokh/storybook/commit/b6f5bb2a5bb772e919aa401d1f21c0714ab26f13
where Vite needs to hook up its websocket to Storybook's underlying http.Server instance in order to support HMR.

I just want some input from @SasanFarrokh and @patak-js. Once we expose Storybook's underlying http.Server through the API, there's no going back (because of backwards compatibility in the API). Is there any way we can connect Vite's HMR websocket to Storybook's underlying dev server, purely through the express.Router that is already provided in the existing Builder API? Or is exposing the http.Server the best option?

### CODE REVIEW

**Comment by shilman** [comment]
Change looks clean but I'd like to hear back from the Vite side to see if there's any way we can do this with the router per your description comment.

cc @ndelangen @tmeasday

**Comment by patak-js** [comment]
@eirslett discussed in Vite Land with other members that have more experience regarding integrating Vite with other tools. So I trust his assessment regarding the need for this PR.

FWIW, I think that exposing the server is a good idea independently of its usage in Vite. As explained in this PR https://github.com/vitejs/vite/pull/2338, where the config for a custom server for hmr was added to Vite, there are some environments where creating a separate server is not an option.

About the feature request regarding Vite specifically, @eirslett I think it would be good if you could explain a bit more why letting Vite create its own hmr server doesn't work for the StoryBook integration, so it is documented why this is needed in this context.

**Comment by eirslett** [comment]
> I think it would be good if you could explain a bit more why letting Vite create its own hmr server doesn't work for the StoryBook integration, so it is documented why this is needed in this context.

I'm not sure how to best explain it... I suppose in theory Vite could create a dev server of its own, completely independent of Storybook's own server, but then we would have to listen on two separate HTTP ports, one for Storybook's dev server and another one for Vite's. It would mean configuring two ports, or assigning a random available port and coordinating between the two servers. It's just so much better to integrate Storybook and Vite on the same dev server.

**Review by shilman — APPROVED** [review]
Going to merge this. If we end up not going this route, let's revert it before 6.3 is released to reduce the surface area.

**Pull request merged**
