### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **24%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /examples/official-storybook/image-snapshots/__image_snapshots__/storyshots-image-runner-js-image-snapshots-addons-storyshots-block-1-snap.png | 3.19kb | 0.49kb | 84.64% |
| /docs/src/design/homepage/built-for.png | 7.72kb | 2.41kb | 68.86% |
| /docs/src/pages/examples/thumbnails/gov-uk.png | 52.98kb | 18.55kb | 64.99% |
| /docs/src/design/docs/docs-content.png | 54.38kb | 19.37kb | 64.37% |
| /docs/src/design/homepage/header.png | 6.64kb | 2.46kb | 62.97% |
| /lib/cli/test/fixtures/react_native_scripts/assets/icon.png | 2.91kb | 1.24kb | 57.33% |
| /addons/storyshots/storyshots-core/docs/storyshots-fail.png | 380.39kb | 170.42kb | 55.20% |
| /app/react-native/docs/assets/readme/screenshot.png | 339.80kb | 155.55kb | 54.22% |
| /docs/src/pages/testing/static/login_form.png | 68.28kb | 31.68kb | 53.60% |
| /docs/src/components/Footer/images/github-icon.png | 13.78kb | 6.41kb | 53.48% |
| /lib/cli/docs/getstorybook.png | 237.22kb | 110.64kb | 53.36% |
| /addons/storyshots/storyshots-core/docs/storyshots.png | 254.06kb | 118.88kb | 53.21% |
| /docs/src/design/homepage/storybook-icon.png | 15.34kb | 7.32kb | 52.28% |
| /docs/src/pages/logos/squarespace.png | 41.48kb | 20.83kb | 49.77% |
| /addons/ondevice-notes/docs/demo.png | 252.99kb | 132.54kb | 47.61% |
| /docs/src/pages/examples/thumbnails/vanilla.png | 93.29kb | 49.56kb | 46.88% |
| /docs/src/pages/testing/static/storybook-iframe-screenshot.png | 139.73kb | 79.73kb | 42.94% |
| /docs/src/pages/examples/thumbnails/carbon.png | 64.37kb | 36.75kb | 42.91% |
| /docs/src/pages/addons/static/stories-without-notes.png | 142.56kb | 81.96kb | 42.51% |
| /docs/src/pages/addons/static/default-addons.png | 143.91kb | 82.93kb | 42.38% |
| /addons/options/docs/screenshot.png | 108.10kb | 62.40kb | 42.28% |
| /docs/src/pages/examples/thumbnails/grommet.png | 242.59kb | 142.06kb | 41.44% |
| /docs/src/pages/testing/static/specs-addon.png | 65.07kb | 38.32kb | 41.11% |
| /docs/src/pages/examples/thumbnails/mockingbot.png | 138.56kb | 81.78kb | 40.98% |
| /docs/src/pages/examples/thumbnails/semanticui.png | 109.90kb | 65.37kb | 40.52% |
| /addons/notes/docs/demo.png | 155.88kb | 93.01kb | 40.33% |
| /docs/src/pages/addons/static/stories-with-notes.png | 155.88kb | 93.01kb | 40.33% |
| /addons/knobs/docs/demo.png | 142.81kb | 85.39kb | 40.21% |
| /docs/src/pages/examples/thumbnails/react-svg-pan-zoom.png | 80.90kb | 49.16kb | 39.24% |
| /docs/src/pages/examples/thumbnails/todomvc.png | 114.43kb | 69.55kb | 39.22% |
| /lib/cli/test/fixtures/react_scripts_ts/public/logo192.png | 8.38kb | 5.10kb | 39.13% |
| /docs/src/pages/testing/static/storybook-screenshot.png | 193.24kb | 121.16kb | 37.30% |
| /lib/cli/test/fixtures/react_scripts_ts/public/logo512.png | 22.38kb | 14.05kb | 37.24% |
| /docs/src/design/homepage/homepage.png | 118.63kb | 74.94kb | 36.83% |
| /docs/src/design/homepage/demo.png | 21.61kb | 13.68kb | 36.71% |
| /addons/graphql/docs/screenshot.png | 248.55kb | 158.53kb | 36.22% |
| /docs/src/design/homepage/heading.png | 24.12kb | 15.39kb | 36.19% |
| /addons/actions/docs/screenshot.png | 162.76kb | 104.40kb | 35.86% |
| /docs/src/design/homepage/main-links.png | 17.79kb | 11.56kb | 35.02% |
| /addons/docs/docs/media/mdx-simple.png | 63.27kb | 41.39kb | 34.59% |
| /examples/riot-kitchen-sink/src/logo.png | 50.53kb | 33.19kb | 34.32% |
| /examples/riot-kitchen-sink/public/logo.png | 50.53kb | 33.19kb | 34.32% |
| /lib/cli/test/fixtures/riot/public/assets/images/logo.png | 50.53kb | 33.19kb | 34.32% |
| /docs/src/components/Homepage/Featured/images/airbnb.png | 8.25kb | 5.42kb | 34.31% |
| /docs/src/pages/examples/thumbnails/coursera-ui.png | 204.55kb | 136.05kb | 33.49% |
| /docs/src/pages/testing/static/storyshots-diff-view.png | 133.39kb | 89.93kb | 32.58% |
| /addons/docs/docs/media/mdx-page.png | 190.25kb | 128.41kb | 32.50% |
| /docs/src/pages/examples/thumbnails/rebass.png | 109.60kb | 74.07kb | 32.42% |
| /addons/a11y/docs/screenshot.png | 342.10kb | 232.14kb | 32.14% |
| /docs/src/design/homepage/footer.png | 12.74kb | 8.66kb | 31.98% |
| /addons/knobs/docs/storybook-knobs-example.png | 230.53kb | 157.25kb | 31.79% |
| /docs/src/pages/logos/nulogy.png | 7.30kb | 4.99kb | 31.55% |
| /docs/src/pages/examples/thumbnails/wix.png | 137.92kb | 94.99kb | 31.12% |
| /docs/src/pages/logos/lonelyplanet.svg | 5.01kb | 3.46kb | 31.01% |
| /docs/src/pages/testing/static/storyshots-first-run.png | 48.33kb | 33.41kb | 30.87% |
| /addons/docs/docs/media/faq-devtools.png | 538.92kb | 373.20kb | 30.75% |
| /docs/src/design/homepage/featured-storybooks.png | 21.41kb | 14.87kb | 30.57% |
| /addons/docs/docs/media/docs-tab.png | 149.24kb | 103.79kb | 30.46% |
| /docs/src/pages/examples/thumbnails/uber.png | 75.74kb | 53.19kb | 29.77% |
| /docs/src/pages/examples/thumbnails/hackoregon.png | 468.14kb | 335.94kb | 28.24% |
| /addons/docs/docs/media/docspage-slots.png | 152.84kb | 110.53kb | 27.68% |
| /docs/src/pages/testing/static/image-diff-2.png | 43.21kb | 31.35kb | 27.45% |
| /addons/docs/docs/media/mdx-documentation-only.png | 193.08kb | 140.65kb | 27.15% |
| /docs/src/design/docs/docs-nav.png | 20.58kb | 15.03kb | 26.97% |
| /addons/docs/docs/media/mdx-hero.png | 47.53kb | 35.04kb | 26.28% |
| /docs/src/pages/addons/static/storybook-components.png | 230.07kb | 171.32kb | 25.53% |
| /docs/src/design/homepage/screenshot.png | 19.13kb | 14.36kb | 24.95% |
| /docs/src/design/docs/docs.png | 98.62kb | 74.84kb | 24.11% |
| /addons/info/docs/home-screenshot.png | 160.25kb | 122.20kb | 23.75% |
| /docs/src/components/Homepage/Featured/images/rb.png | 3.09kb | 2.37kb | 23.40% |
| /docs/src/pages/basics/static/screenshot.png | 398.62kb | 307.10kb | 22.96% |
| /docs/src/pages/basics/static/basic-stories.png | 398.62kb | 307.10kb | 22.96% |
| /addons/docs/docs/media/faq-debug.png | 67.11kb | 51.81kb | 22.80% |
| /addons/viewport/docs/viewport.png | 121.04kb | 93.59kb | 22.68% |
| /docs/src/components/Footer/images/slack-icon.png | 6.33kb | 4.98kb | 21.42% |
| /docs/src/pages/examples/thumbnails/griddle.jpg | 211.25kb | 167.33kb | 20.79% |
| /docs/src/pages/examples/thumbnails/reactnativeweb.jpg | 82.62kb | 65.78kb | 20.38% |
| /docs/src/design/docs/docs-container.png | 75.72kb | 60.51kb | 20.09% |
| /addons/docs/docs/media/docspage-hero.png | 422.31kb | 338.95kb | 19.74% |
| /docs/src/pages/examples/thumbnails/timeline.jpg | 165.63kb | 133.21kb | 19.57% |
| /docs/src/pages/examples/thumbnails/buffer.jpg | 134.77kb | 112.43kb | 16.58% |
| /docs/src/pages/examples/thumbnails/lucid-ui.png | 241.27kb | 203.16kb | 15.80% |
| /addons/storysource/docs/theming-light-dark.png | 247.22kb | 209.33kb | 15.32% |
| /docs/src/pages/examples/thumbnails/cosmos.png | 658.07kb | 557.99kb | 15.21% |
| /docs/src/pages/examples/thumbnails/airbnb.jpg | 133.82kb | 114.01kb | 14.81% |
| /docs/src/pages/examples/thumbnails/atlassian.png | 298.38kb | 254.32kb | 14.76% |
| /examples/vue-kitchen-sink/src/logo.png | 6.69kb | 5.73kb | 14.40% |
| /lib/cli/test/fixtures/sfc_vue/src/assets/logo.png | 6.69kb | 5.73kb | 14.40% |
| /docs/src/pages/examples/thumbnails/algolia.jpg | 98.45kb | 84.89kb | 13.78% |
| /docs/src/pages/testing/static/image-diff-1.png | 73.18kb | 63.28kb | 13.53% |
| /docs/src/components/Homepage/Featured/images/rnw.png | 32.21kb | 27.91kb | 13.33% |
| /docs/src/pages/examples/thumbnails/artsy.png | 3,742.73kb | 3,267.15kb | 12.71% |
| /docs/src/pages/examples/thumbnails/quran.jpg | 89.50kb | 78.28kb | 12.53% |
| /docs/src/pages/examples/thumbnails/terraeclipse.jpg | 386.20kb | 341.73kb | 11.51% |
| /docs/src/pages/examples/thumbnails/react-pakistan.jpg | 57.91kb | 51.50kb | 11.08% |
| /docs/src/pages/logos/postmates.png | 37.05kb | 32.98kb | 10.97% |
| /docs/src/pages/logos/mozilla.svg | 4.06kb | 3.68kb | 9.33% |
| /docs/src/pages/examples/thumbnails/lonelyplanet.jpg | 299.25kb | 273.05kb | 8.75% |
| /docs/src/pages/examples/thumbnails/appbase.jpg | 386.11kb | 354.28kb | 8.24% |
| /docs/src/pages/examples/thumbnails/trunks.png | 136.77kb | 125.61kb | 8.16% |
| /docs/src/pages/logos/airbnb.svg | 3.37kb | 3.11kb | 7.73% |
| /docs/src/pages/logos/appbase.svg | 5.95kb | 5.51kb | 7.29% |
| /docs/src/pages/logos/coursera.svg | 5.09kb | 4.75kb | 6.69% |
| /lib/cli/test/fixtures/react_native/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png | 7.54kb | 7.04kb | 6.66% |
| /docs/src/pages/logos/buffer.svg | 5.73kb | 5.36kb | 6.52% |
| /lib/cli/test/fixtures/react_native/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png | 4.73kb | 4.46kb | 5.76% |
| /docs/src/pages/examples/thumbnails/gumgum.png | 30.83kb | 29.20kb | 5.28% |
| /docs/src/pages/logos/algolia.svg | 10.12kb | 9.69kb | 4.17% |
| /examples/html-kitchen-sink/stories/logo.svg | 1.42kb | 1.36kb | 3.59% |
| /lib/cli/test/fixtures/react_native/android/app/src/main/res/mipmap-hdpi/ic_launcher.png | 3.34kb | 3.24kb | 2.90% |
| /lib/cli/test/fixtures/react_native/android/app/src/main/res/mipmap-mdpi/ic_launcher.png | 2.15kb | 2.10kb | 2.40% |
| /docs/src/pages/examples/thumbnails/tachyons.png | 503.54kb | 492.48kb | 2.20% |
| /docs/src/pages/logos/quran.svg | 15.37kb | 15.11kb | 1.71% |
| /examples/cra-react15/src/logo.svg | 2.61kb | 2.57kb | 1.46% |
| /lib/cli/test/fixtures/update_package_organisations/src/logo.svg | 2.61kb | 2.57kb | 1.46% |
| /lib/cli/test/fixtures/react_scripts/src/logo.svg | 2.61kb | 2.57kb | 1.46% |
| /lib/cli/test/fixtures/react_scripts_v2_forked/src/logo.svg | 2.61kb | 2.57kb | 1.46% |
| /lib/cli/test/fixtures/react_scripts_v2/src/logo.svg | 2.61kb | 2.57kb | 1.46% |
| /addons/docs/docs/media/hero.png | 831.65kb | 822.03kb | 1.16% |
| /docs/src/pages/logos/wix.svg | 4.69kb | 4.64kb | 1.12% |
| /examples/marko-cli/src/components/welcome/logo.png | 41.92kb | 41.50kb | 1.01% |
| /examples/cra-kitchen-sink/src/logo.svg | 2.59kb | 2.57kb | 0.87% |
| /docs/src/pages/logos/dbsbank.svg | 2.61kb | 2.60kb | 0.41% |
| /docs/src/design/homepage/storybook-logo.svg | 6.50kb | 6.50kb | 0.06% |
| /docs/static/images/logo-storybook.svg | 6.50kb | 6.50kb | 0.06% |
| /lib/cli/test/fixtures/react_scripts_ts/src/logo.svg | 8.01kb | 8.01kb | 0.01% |
| | | | |
| **Total :** | **18,849.55kb** | **14,324.98kb** | **24.00%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by ndelangen** [comment]
This seems super useful!

Why close this PR?

**Comment by ndelangen** [comment]
I added the bot!

**Comment by MichaelDeBoey** [comment]
@ndelangen #8565 was opened, because this one had merge conflicts

**Pull request closed without merging**
