### PR TITLE
Addon-Queryparams: Add addon preset

### PR DESCRIPTION
**Pull request by jonspalmer**
## What I did

Added a preset for QueryParams addon allowing simpler configuration

### CODE REVIEW

**Comment by shilman** [comment]
@ndelangen tests are running out of memory... any idea what's up with that?

**Comment by ndelangen** [comment]
which test is running out of memory?

I'm not seeing any substantial change that might be the cause of any memory issues in tests tbh.

**Comment by jonspalmer** [comment]
this run failed: https://circleci.com/gh/storybookjs/storybook/199948

CircleCI tests sometimes flake out. I've seen it in other branches too. In my experience there is a lot of variability  in the nodes running the test suite (I believe they're using a bunch of containers in different regions/cloud providers). Some nodes miss caches others are just 'not as good'. I bet we're running close to the memory limit of the basic test node and every now an then get unlucky. We could opt for medium+ resources on CircleCI but that would likely add 50% to our credit usage (maybe the tests get faster with more RAM to compensate?)

**Comment by jonspalmer** [comment]
Running the test command locally that we use on CircleCI I see the the two threads end up using about 2GB of RAM each. So on a medium instance we're right up against it (https://circleci.com/docs/2.0/configuration-reference/#resource_class)

**Review by shilman — APPROVED** [review]
LGTM! Great fix 💯

**Pull request merged**
