### PR TITLE
feat(cli): Adds a new info command which prints local environment information

### LINKED ISSUE #6926: Have a dedicated command to print debugging information about local environment
## The idea

Have a dedicated `info` command that prints out debugging information about the local environment which proves to be useful especially while submitting bug reports. 

### Proposed API
`sb info`

```md
Environment Info:

  System:
    OS: Linux 4.18 Ubuntu 18.10 b(Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.17.0-0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.5
  npmGlobalPackages:
   @storybook/cli: 5.0.11
```

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Fixes #6926 

### Proposed API

Added a new info command that prints debugging information about the local environment.

`sb info`

```md
Environment Info:

  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.17.0-0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.5
  npmGlobalPackages:
    @storybook/cli: 5.1.0-rc.3
```

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@shilman Thoughts :thinking:

**Comment by jamesgeorge007** [comment]
cc @shilman @ndelangen

**Comment by jamesgeorge007** [comment]
cc @shilman @ndelangen

**Review by shilman — APPROVED** [review]
This is pretty awesome--great work!

**Comment by jamesgeorge007** [comment]
@shilman Not sure what causes the CI build to fail :thinking:

**Review by ndelangen — APPROVED** [review]

**Comment by jamesgeorge007** [comment]
Are we all set to ship?

**Pull request merged**
