### PR TITLE
Webpack: Hide runtime errors

### PR DESCRIPTION
**Pull request by donaldpipowitch**
**Work-in-progress**

Closes #

## What I did

Storybook shows runtime errors by default in an error overlay. As React in dev-mode is re-throwing actually handled errors, this can get very confusing. If I understood correctly Storybook is not using webpack-dev-server, so we can't specify this config in user land in `main.js`. If I'm not mistaken this has to be passed as a query param to the dev middleware instead.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by ndelangen** [comment]
@donaldpipowitch how do I test this?

Can you supply links to documentation & explaining the intend of the change?

Is this PR still a "Work-in-progress"? I'll make it a draft PR, so it won't come up in our triage until it's ready, I hope you don't mind.

I tested this in a codespace, and it looked fine, but honestly couldn't really determine if any really changed; hence my question above.

**Comment by donaldpipowitch** [comment]
Thanks for asking @ndelangen.
I'll probably add an example for a documented error boundary in Storybook. This should illustrate the problem quite well: if you're working on some error boundary and want to document it in storybook you'll likely throw some artificial error somewhere. In the development mode this is currently picked up as a runtime error from the webpack error overlay, which makes it hard to properly work on it.

**Comment by ndelangen** [comment]
@yannbf I'm wondering what you think of this change; considering you've worked on webpack error handling (with me) before.

**Comment by donaldpipowitch** [comment]
FYI: Since creating this MR we switched to vite. I'd also be fine with closing this MR.

But maybe it would in general be nice to add more error boundary examples to Storybook to cover some edge cases better (the test runner also had "problems" with error boundaries that is tracked in an issue).

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
