### PR TITLE
Build: Add vite-react to e2e tests

### PR DESCRIPTION
**Pull request by yannbf**
Issue: N/A

## What I did

Added vite builder example to E2E, so we guarantee there are no unintended breaking changes 👌 

cc @IanVS 

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by IanVS** [comment]
This is great, seems easy!  But, is it actually running in CI?  I see:

```
Will run E2E tests for:react, vue3
```

and don't see vite actually running.

**Comment by yannbf** [comment]
> 

The e2e tests under **e2e-tests-core** happen in parallel so you might have checked the first batch of tests. You can find the one with vite [here](https://app.circleci.com/pipelines/github/storybookjs/storybook/24780/workflows/cd6f2a3c-b80f-4934-864f-99f9cfe864a4/jobs/372266/parallel-runs/1?filterBy=FAILED) but it's unfortunately failing with no helpful message. I'll have to check this further!

image

**Comment by IanVS** [comment]
@yann, it seems the error is occurring because `@storybook/builder-vite` is not in https://github.com/storybookjs/storybook/blob/43be92e13b75f91b99372f0707043739ca5951b9/lib/cli/src/versions.ts.  And furthermore, when running `yarn local-registry --port 6000 --open --publish`, then `yarn npm info @storybook/builder-vite --fields version --json` errors out because it's looking for a locally published package.

```
Not Found - GET http://localhost:6000/@storybook%2fbuilder-vite - no such package available
```

🤦

**Comment by IanVS** [comment]
I've pushed up a fix as a separate PR (https://github.com/storybookjs/storybook/pull/17897)

Maybe you could also add this, so that the interactions are tested?

```
// addon-interactions.spec.ts

onlyOn('vite_react', () => {
    it('should have interactions', test);
  });
```

**Comment by yannbf** [comment]
> I've pushed up a fix as a separate PR (#17897)
> 
> Maybe you could also add this, so that the interactions are tested?
> 
> ```
> // addon-interactions.spec.ts
> 
> onlyOn('vite_react', () => {
>     it('should have interactions', test);
>   });
> ```

You're the best! I updated this branch with latest next and included vite_react to the E2E test. 🤞

**Review by shilman — APPROVED** [review]
LGTM

**Pull request merged**
