### PR TITLE
Core: Fix manager assets to be routed in express

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: #9443

## What I did

I changed the way the manager webpack process starts/watches. By doing this it's possible to add all the webpack routes to express.

This was already the way preview works.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM, great job! but what's up with the deepscan issues @ndelangen ?

**Comment by ndelangen** [comment]
Should be fixed now @shilman

**Comment by shilman** [comment]
@ndelangen do you think it's safe to patch this back to `master`?

**Comment by ndelangen** [comment]
Yes, I think this is safe to port to 5.3 really.

**Comment by kylepeeler** [comment]
Please port back to 5.3!

**Pull request merged**
