### PR TITLE
Move react-docgen dependency to docs addon preset.

### PR DESCRIPTION
**Pull request by patricklafrance**
Issue: https://github.com/storybookjs/storybook/issues/9273

## What I did

- Moved `babel-plugin-react-docgen` and `babel-plugin-add-react-displayname` from `app/react` to docs addon.

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by patricklafrance** [comment]
Hey @shilman any idea why it doesn't work?

I get the following for every components, PropTypes or TS:

image

I am using cra-ts-kitchen-sink to test.

**Comment by patricklafrance** [comment]
@shilman nvm

**Comment by patricklafrance** [comment]
Still failing with the following error, not sure what to do here:

image

**Comment by shilman** [comment]
@patricklafrance how do i reproduce this problem? i updated from `next` and am not seeing it

**Comment by patricklafrance** [comment]
@shilman it's working now, seems like the problem might have been fixed in next?

**Comment by patricklafrance** [comment]
As part of this PR I am also moving `babel-plugin-add-react-displayname` to the docs preset. Is it a good idea? Do you know if it's used by another feature of SB?

**Comment by shilman** [comment]
Hmm I think both are used by `addon-info`. I'm thinking we should deprecate `addon-info` in 6.0, but we still have to have a solution for it.

**Comment by patricklafrance** [comment]
@shilman ok I thought deprecating `addon-info` was a done deal, that's why I started this PR.

What does `addon-info` do that docs doesn't?

**Comment by shilman** [comment]
Deprecating does not mean deleting. It's still used 3x as much as `addon-docs`, so it means there are a bunch of people out there who rely on it. We need to formally announce that `addon-info` is deprecated THEN give people time to migrate off.

After a little thought, here's my `addon-info` proposal. I think we can use the same playbook for `addon-notes`, `polymer`, and any other package we want to EOL in 6.0 cc @tmeasday @ndelangen:

- Move `addon-info` into its own repo
- Move all existing `addon-info` issues to the new repo (if possible)
- Add deprecation warnings with a directive to upgrade to `addon-docs`
- Add deprecation warning to the top of the README
- Add migration instructions for how to use `main.js` config to get `babel-plugin-react-docgen` and `babel-plugin-add-react-displayname` for `addon-info`
- Immediately close all incoming `addon-info` issues and direct author to new repo

**Comment by patricklafrance** [comment]
Ok I see @shilman i’ll close this PR then since we can’t move react-docgen!

**Comment by shilman** [comment]
@patricklafrance you missed my point. we can move it. we just need to document it for `addon-info` users.

**Comment by patricklafrance** [comment]
@shilman ahh got it! :)

**Comment by ndelangen** [comment]
I can put this on my todo-list:

> Move addon-info into its own repo

**Comment by patricklafrance** [comment]
Would be great @ndelangen, thank you!

**Comment by ndelangen** [comment]
@tmeasday I'm not sure if I should be assigned to this.

I proposed I'd handle the extraction of addon-notes & addon-info from the monorepo.

This PR itself deals with a different issue (which I do not have a lot of context on)?

**Comment by ndelangen** [comment]
@patricklafrance Is this PR completely blocked until addon-notes & addon-info are extracted?

**Comment by shilman** [comment]
I'll take this one @ndelangen

**Comment by shilman** [comment]
Won't fix. Took a different approach in https://github.com/storybookjs/storybook/issues/8444

Users still take the dependency hit, but it's an easy to change to decide which docgen you want

**Pull request closed without merging**
