### PR TITLE
Disable webpack performance hints in manager config

### PR DESCRIPTION
**Pull request by lozinsky**
Issue: #5872

## What I did
I added the [performance](https://webpack.js.org/configuration/performance) property to manager config for prevent webpack warnings during static build.
## How to test
Run the following script: `yarn build-storybooks`

**Actual output:**
```
...
info => Copying static files from: dist
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom addons config.
info => Compiling manager..
info => manager built (4.02 s)
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets: 
WARN   main.86687b96f20fe0537f37.bundle.js (470 KiB)
WARN   vendors~main.431fe3c2cdbce42bcc68.bundle.js (1.75 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (2.21 MiB)
WARN       runtime~main.bf7f1bbd18bd2f1ec8df.bundle.js
WARN       vendors~main.431fe3c2cdbce42bcc68.bundle.js
WARN       main.86687b96f20fe0537f37.bundle.js
WARN 
WARN webpack performance recommendations: 
WARN You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
WARN For more info visit https://webpack.js.org/guides/code-splitting/
info => Building preview..
...
```
**Expected output:**
```
...
info => Copying static files from: dist
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom addons config.
info => Compiling manager..
info => manager built (4.01 s)
info => Building preview..
...
```

### CODE REVIEW

**Comment by lozinsky** [comment]
It may also be worthwhile to remove the condition in [iframewebpack.config.js](https://github.com/storybooks/storybook/blob/next/lib/core/src/server/preview/iframe-webpack.config.js#L107). Whether there are practical benefits of these hints?

**Review by ndelangen — APPROVED** [review]

**Review by ndelangen — APPROVED** [review]

**Comment by gabriel-kohen-jdas** [comment]
I'm running version 5.2.5 and still get the following:
`info => Preview built (10 s)
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets: 
WARN   vendors~main.a5ee4bf1a5b8f6a08c48.bundle.js (838 KiB)`
Am I missing something?

**Comment by lozinsky** [comment]
These changes disable hints in the manager config. To make it work the same for the preview config you need to add the following code to your `webpack.config.js`:
```js
performance: {
  hints: false
}
```

**Comment by ronnyek** [comment]
I am using storybook 5.2.6 and still have this problem. I tried adding that very snippet to my webpack.config.js in .storybook, and it errors like webpack doesnt know what that file is

**Comment by absalonv** [comment]
I am using 5.3.13 and still get the same warning

**Comment by lozinsky** [comment]
Storybook has at least two webpack configs:
* manager webpack config — internal config, need for build storybook's app
* iframe webpack config (preview) — [user-customizable](https://storybook.js.org/docs/configurations/custom-webpack-config/#examples) webpack config, need for build user's stories

The changes in this PR relate to the **manager webpack config**. If with your codebase you get the same warning, then you need to add the following code to your [custom webpack config](https://storybook.js.org/docs/configurations/custom-webpack-config) and the warning must be muted.
```js
performance: {
  hints: false
}
```

**Comment by kkomelin** [comment]
For those who's in search of how to adjust Storybook webpack config, see [Custom Webpack Config](https://storybook.js.org/docs/configurations/custom-webpack-config/) section of the Storybook docs.

**Pull request merged**
