### PR TITLE
CLI (React Native): ensure having an explicit dependency on `prop-types`

### PR DESCRIPTION
**Pull request by Hypnosphi**
This is a follow-up to #1710 
It's safer to have a direct dependency to anything you import from your code

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
@Hypnosphi great catch. i thought about this but got lazy .. thanks for picking up the slack!

Looks like `prop-types` wants to be in `dependencies` though, not `devDependencies`:

https://www.npmjs.com/package/prop-types

**Comment by Hypnosphi** [comment]
Not in that particular case, as stories are part of development process

**Comment by tmeasday** [comment]
Do we need to do this for the other project types also?

**Comment by Hypnosphi** [comment]
No, as we don't have usages of `prop-types` in those templates

**Review by shilman — APPROVED** [review]

**Comment by shilman** [comment]
Gotcha, good call! 👍

**Pull request merged**
