### PR TITLE
make changes to typings files to ensure this the check command succeeds

### PR DESCRIPTION
**Pull request by ndelangen**
trying to get the `check` command to go green on tom's PR

telescoped on https://github.com/storybookjs/storybook/pull/20425

### CODE REVIEW

**Comment by ndelangen** [comment]
@kasperpeulen would you have an idea why all this might be needed all of a sudden?

See the CI failures here:
https://app.circleci.com/pipelines/github/storybookjs/storybook/37944/workflows/4d851337-0126-4043-9a38-2d371497aba9/jobs/467028

... on tom's PR (see here: https://github.com/storybookjs/storybook/pull/20425)

**Comment by tmeasday** [comment]
It's pretty weird given the set of changes in my PR that triggered this: https://github.com/storybookjs/storybook/pull/20425/files#diff-5f3b461267dd493f3353db09d428b794e60fb594b2695d8c9977c054c005977b -- no changes to any config files and pretty minor type changes.

Are we only type checking these files when there are changes to them or something?

**Comment by ndelangen** [comment]
I was hoping @kasperpeulen would be able to assist in figuring out what happened 🙏

**Comment by yannbf** [comment]
These errors happened on `next` as well, with an Angular template:

image

**Comment by ndelangen** [comment]
I'm just going to push this forwards then, to unblock `next`.

**Pull request merged**
