### PR TITLE
Added CRNA app with getstorybook

### PR DESCRIPTION
**Pull request by shilman**
Issue: #1218 

## What I did

Equivalent of:
```
yarn create react-native-app crna-getstorybook
cd crna-getstorybook
getstorybook
```

Plus added a few `/* eslint-disable */` for files generated by `create-react-native-app` which don't follow our coding conventions and added snapshot testing.

I did not hook up storybook with the app, per
https://github.com/storybooks/storybook/tree/master/app/react-native#create-react-native-app-crna

## How to test

Automated test:
```
yarn bootstrap
cd examples/crna-getstorybook
yarn test
```

Manual test:
```
yarn bootstrap
https://github.com/storybooks/storybook/pull/1219
yarn storybook
yarn ios
```

### CODE REVIEW

**Comment by tmeasday** [comment]
Is this ready for review?

**Comment by shilman** [comment]
@tmeasday please see my comments in `what i need` above

**Comment by tmeasday** [comment]
@shilman, my answer to the above was: it doesn't look like it'll be possible hijack the packager in the same way for CRNA. Instead of the vanilla packager, a CRNA app ends up using something deep in the bowels of `xdl` (Expo's lib) to package the app, AFAICT. It's all programatic so it doesn't seem like it'd be possible to pass configuration through and change the `projectRoot` that it packages (that's what we do in the vanilla RN case).

**Comment by shilman** [comment]
@tmeasday any thoughts on the best way to make this testable?

**Comment by tmeasday** [comment]
We can use `jest` to test it with storyshots, right? If you want to test the actual native app connection works, I think that's pretty complicated :/

**Comment by alexandrebodin** [comment]
Hey. 

I think we need to decide for a n example folder structure. Here is a proposal to apply here and in #1224 

## Current state

```
examples
|-- cra-storybook
|-- react-native-vanilla
|-- test-cra
|-- crna-getstorybook // This PR
```

## Goals

- Have clear getstarted examples for both react and react-native and any other lib we plan on supporting
- Have examples for addons usage
- Have a good project for us to develop / experiment on and test addons and new features.
- Have a live storybook for sotrybook source code documentation 

## Proposal

```
examples
|-- react
	|-- getstarted // would be cra + getstorybook
	|-- advanced // vanilla + addons
|-- react-native
	|-- getstart // crna + getstorybook
	|-- advanced // same
|-- storybook // testing our components / development workplace / experimenting => Could be live on the website to serve as a live demo.
```

I tried to synthesize some of the discussion we all had. Sorry If I missed sth :)

**Comment by shilman** [comment]
@alexandrebodin my proposal was here:

https://github.com/storybooks/storybook/pull/1224#issuecomment-307539284

I prefer a flat file structure both because it's simpler with Lerna and also simpler for a user to scan all of the examples in one place.

**Comment by alexandrebodin** [comment]
Aren't you afraid there will be too many flat projects if we start supporting angular cycle vue etc ?  For now we can go with your idea of flat strucutre and wait for future evolution. 

I don't think it's really clear for a user to see cra-getstorybook imho 

i would at least expect react-getstarted (rather thant react-getstorybook as you suggested I think) 

That's only my opinion of course :)

**Comment by shilman** [comment]
@alexandrebodin You're right that when we start to support multiple frameworks we should divide it up. Currently we just support two though, so let's keep it simple to start and refactor once we have more frameworks.

I'm fine with renaming `x-getstorybook` to `x-getstarted` and will rename accordingly in both PRs

**Comment by shilman** [comment]
Merging this into https://github.com/storybooks/storybook/pull/1224

**Pull request closed without merging**
