### PR TITLE
Svelte: Add Slots and Events to the generated ArgsTable

### PR DESCRIPTION
**Pull request by j3rem1e**
Issue: None

## What I did

Improvements on the generated ArgsTable with Svelte, like Vue : 3 sections, Properties, Events and Slots.

## How to test

- Is this testable with Jest or Chromatic screenshots? Done
- Does this need a new example in the kitchen sink apps? Done
- Does this need an update to the documentation? No

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Thanks @j3rem1e !

One request: you're including test cases for slots and events in the extraction unit test, but can you also include an example in the Args Table story for `svelte-kitchen-sink`? Thanks! 🙏

**Comment by j3rem1e** [comment]
I have added examples for slots and events in the argstable story.
I have attached the related code to this story to show how to document theses properties.

As discussed on Discord, you can see that this source is not fully highlighted, because the language is jsx and not svelte.

**Comment by jonniebigodes** [comment]
@DaleSeo don't worry it won't. It's on my todo list. Yours should be merged soon. I'm going about it iteratively and check the pull requests. I'm going to do a last sweep today and if nothing stands out it will be merged today still or no latest than tomorrow. 

Stay safe

**Review by shilman — APPROVED** [review]
Looking great! 💯

**Pull request merged**
