### PR TITLE
Replace UglifyJS with babel-minify

### PR DESCRIPTION
**Pull request by ndelangen**
This came up in: #1501
A node_module we want to use has not been transpiled to es5 before publishing.

We could add the module to be run through babel, or we could do this:
Switch over to an alternative minifier. This PR swaps UglifyJS for Babel-Minify.

Why? Well the browsers we target actually support 90%+ of ES6+. Transpiling down 

Related issue: #1005

This only affects static builds!

## How to test
Run `yarn build-storybook` on cra-kitchen-sink
Serve the static site

## What about bundle size?
1.396.924 bytes (1,4 MB on disk)
That's down considerably from before:
2.032.284 bytes (2 MB on disk)

### CODE REVIEW

**Comment by ndelangen** [comment]
screen shot 2017-08-24 at 23 12 46
screen shot 2017-08-24 at 23 15 03

**Comment by UsulPro** [comment]
I tried to test it locally with my branch and it takes about 8 min to finish building
All except this works fine! :+1:

**Comment by ndelangen** [comment]
Wow, that's a long time.. For me it was about 80 seconds

**Review by Gongreg — APPROVED** [review]

**Comment by UsulPro** [comment]
got 87 sec today!

**Review by usulpro — APPROVED** [review]
I'd love to have it merged

**Comment by ndelangen** [comment]
I want someone to verify react-native other then me

**Comment by tmeasday** [comment]
I tried it with RN-vanilla (just ran the storybook as usual), and it worked fine. How do I run a build with RN?

**Comment by ndelangen** [comment]
@tmeasday I've looked into this, and it would appear there is no production build possible for RN.
This kinda makes sense to me.

I'm hoping @mnmtanish can verify?

**Comment by ndelangen** [comment]
This in combination with https://github.com/storybooks/storybook/pull/1775#pullrequestreview-60470518 could be the opening to auto-deployed examples (because filesize of manager and preview bundle is lowered)

**Comment by ndelangen** [comment]
I would like @shilman 's approval for merging this into 3.3

**Comment by shilman** [comment]
@ndelangen I tried this out in IE11 per our discussion.

This works:
```
yarn bootstrap
cd examples/cra-kitchen-sink
yarn storybook
# open 10.0.0.4:9010 in IE11
```

This does not:
```
yarn bootstrap
cd examples/cra-kitchen-sink
yarn build-storybook
cd storybook-static
serve
# open 10.0.0.4:5000 in IE11
```

Do you think you could try this out and get it working for IE11 before we merge?

**Review by shilman — CHANGES_REQUESTED** [review]
See my request above

**Comment by ndelangen** [comment]
I'll take a look at that @shilman

**Comment by ndelangen** [comment]
traced to:
`Object doesn't support property or method 'assign'`

**Comment by ndelangen** [comment]
I'm having some difficulty getting the proper polyfills to be injected for IE11 😭

**Comment by Hypnosphi** [comment]
>`Object doesn't support property or method 'assign'`

Weird, I thought it should be handled by `transform-runtime`

**Comment by Hypnosphi** [comment]
@shilman looks like it's broken on `release/3.3` as well

**Comment by ndelangen** [comment]
Is there something you can do here @Hypnosphi ?

**Comment by Hypnosphi** [comment]
Should be fixed with #1905

**Comment by Hypnosphi** [comment]
Now the error is
```
Unable to get property 'length' of undefined or null reference
manager.a7189be9c9c73c8b5188.bundle.js (1,299715)
```

**Comment by Hypnosphi** [comment]
Now storybook start successfully, but there are stil some errors when trying to switch addon panels or click the buttons with actions

**Comment by Hypnosphi** [comment]
Looks like everything works in IE now. @shilman please check

**Comment by ndelangen** [comment]
Related:
- #1352 
- #213 
- #1917 
- #298

**Comment by igor-dv** [comment]
Took 70 secs for me. Looks OK. I have some errors in the actions addon, but looks like they appear in the release branch too (or maybe it's again a windows party-pooping).

**Comment by Hypnosphi** [comment]
@igor-dv which are the errors, namely?

**Comment by igor-dv** [comment]
I'm getting the `ReferenceError: handler is not defined` when clicking on the button with the "action" callback (for example `Button/with text`). I've checked it again in the release branch and it doesn't happen there (There was something with cross-origin in iframe). I can dig into it later if it's indeed the problem but would like someone else will be able to reproduce it...

**Comment by Hypnosphi** [comment]
So do those errors happen foryou in IE11 only, or in other browsers as well?

**Comment by igor-dv** [comment]
In Chrome and FF

**Comment by Hypnosphi** [comment]
I can confirm this in Chrome on mac as well

**Comment by Hypnosphi** [comment]
The problem was the name mangling, plus the fact that we have to use `eval` in `addon-actions`

**Comment by igor-dv** [comment]
Nice! But what is the bundle size now ?

**Comment by Hypnosphi** [comment]
For `cra-kitchen-sink`, it's 3.2M vs 2.9M on `release/3.3` (but mangling is [disabled](https://github.com/storybooks/storybook/blob/release/3.3/app/react/src/server/config/webpack.config.prod.js#L52) there as well)

**Comment by danielduan** [comment]
This feels like something that's valuable for us to get merged.

**Comment by evan-scott-zocdoc** [comment]
`uglifyjs-webpack-plugin` v1 is out, which has full ES6+ support btw. https://github.com/webpack-contrib/uglifyjs-webpack-plugin

**Comment by ndelangen** [comment]
Latest stats:

## before 'mange'

manager = 1.915.735 bytes (1,9 MB on disk)
preview = 206.408 bytes (209 KB on disk)
vendor = 966.175 bytes (967 KB on disk)


## after 'mange'

manager = 1.332.127 bytes (1,3 MB on disk)
preview = 118.647 bytes (119 KB on disk)
vendor = 698.993 bytes (700 KB on disk)

**Comment by danielduan** [comment]
@ndelangen you mean mangle right?

I still don't think we should be using `mangle` but anything else we can do to get the bundle size down is a plus for me.

**Comment by Hypnosphi** [comment]
I'd prefer to keep avoiding mangling. Even in the case of static build, storybook is still a developer tool, and debugging experience should be among top priorities. And I believe we actually display some original variable and function names in addons like info and actions.

**Comment by Hypnosphi** [comment]
@shilman is there anything else that should be done here in your opinion?

**Comment by Hypnosphi** [comment]
@ndelangen we need to apply the same changes to angular app

**Comment by ndelangen** [comment]
Putting this back into the freezer, gonna have a look at the uglify-webpack-plugin that was mentioned: https://github.com/storybooks/storybook/pull/1733#issuecomment-343326477

**Comment by ggarek** [comment]
@ndelangen Thank you for investigating into this issue! Since i am also interested in this fix and i had some free time, i tried to use `uglify-es`.

Please, check it when you have time

**Comment by ndelangen** [comment]
Thank you @ggarek, I will close this PR in favour of yours!

**Pull request closed without merging**
