### PR TITLE
Revert "Move `.` to `lint:js` and `lint:md`"

### PR DESCRIPTION
**Pull request by ndelangen**
This reverts commit 7b038313155de06cc55f921ab87a8e35b7aae348.

Issue: The precommit hooks now run yarn lint on ALL files, not just the changed ones.

## What I did

reverted the change see above

### CODE REVIEW

**Comment by IanVS** [comment]
Oh I didn't realize there's a pre-commit hook.  It's kind of a bummer to use the same npm script for linting in CI and also linting individual files, since the cache will be constantly cleaned out due to running eslint against different files.  I wonder if it might be possible to create a separate script for the pre-commit hook, with a different cache-location.  Would you be willing to review a PR to try it out if I work on that real quick?

**Comment by ndelangen** [comment]
> constantly cleaned out due to running eslint against different files. 

I am unaware of this. I'd assume eslint would keep a cache based on files, so running ona subset of files would not clear the cache. Is this an assumption? or do you have a link to the docs about this?

**Comment by IanVS** [comment]
That's how it used to work, I'll do a little investigating.

**Comment by ndelangen** [comment]
We could change the precommit hook of course, it's configured here:
https://github.com/storybookjs/storybook/blob/7c871457920dcb01b2a258a043916272bb55b706/package.json#L88-L95

**Comment by IanVS** [comment]
Alright cool, either things changed or I was just wrong, but changing the target does not remove the cache.  But running `--fix` _does_ remove the file(s) from the cache (https://eslint.org/docs/user-guide/command-line-interface#--cache), but that's not a huge deal as long as husky is only running on the files that changed (oops).  

I've opened an alternative to this revert PR at https://github.com/storybookjs/storybook/pull/17662.  Please let me know what you think.

**Pull request closed without merging**
