### PR TITLE
React Native <0.43 support

### LINKED ISSUE #1553: OnDeviceUI breaks RN versions <0.43
StoryListView [makes use of SectionList](https://github.com/storybooks/storybook/blob/v3.2.0/app/react-native/src/preview/components/StoryListView/index.js#L79), which is new to ReactNative `v0.43`. We currently support a minimum version of `0.27`, so that breaks a number of lower versioned users.

I'd suggest continued usage of `ListView`. While this will [ultimately be deprecated in the future](https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html#future-work), we can operate with the proper foresight by creating a backward-compatible approach where it creates a `ListView` or `SectionList` depending on the platform support.

While ideal, an MVP of this would be to use a `ListView`.

### PR DESCRIPTION
**Pull request by atticoos**
Issue: Builds were broken for React Native versions `<0.43`. (#1553)

## What I did
Swapped out `SectionList` for `ListView`. This will be deprecated in the future (I don't believe anytime soon/immediate), so ideally we may want to export a List component that interfaces with whichever underlying `ListView` / `SectionList` implementation is supported. For now, this simply unbreaks `<0.43` builds.

There are two additional regressions: `StyleSheet.absoluteFillObject` and the use of `maxWidth` in a style. For ease of use moving forward, I added a `polyfills/` directory to address these head on.

#### `StyleSheet.absoluteFillObject`

This is only supported in recent versions. It's simply a preset style for a full screen absolutely positioned element.

#### `MinMaxViewPolyfill`

The min/max width/height features of styles are not available on earlier versions of React Native. This adds a Higher Order Component that can declaratively (through props) apply these bounding rules to any child component.

## How to test

Run the `react-native-vanilla` project and verify all continues to work.

<details><summary>Proof</summary>

screen shot 2017-07-31 at 1 35 46 pm
</details>

Closes #1553

### CODE REVIEW

**Comment by rmevans9** [comment]
This looks good to me. I personally dislike having to "go backwards" but I understand the need.

**Review by rmevans9 — DISMISSED** [review]

**Comment by ajwhite** [comment]
I just realized I hand't audited other components. Verifying `StatusBar` is supported in `0.27`

**Comment by ajwhite** [comment]
`StatusBar` [is supported](http://facebook.github.io/react-native/releases/0.27/docs/statusbar.html) in `0.27`. I think we're all good here. 

I should pull this into my `0.27` project and verify that it all works as expected prior to merging.

**Review by shilman — DISMISSED** [review]
LGTM! Tested (but not on old RN)

**Comment by ajwhite** [comment]
Testing RN 0.27 right now. Will report back shortly

**Comment by ajwhite** [comment]
Have some `minWidth` and `maxWidth` problems:

screen shot 2017-07-31 at 1 58 22 pm

WIP

**Comment by ajwhite** [comment]
Ran into two additional backward incompatibilities. For ease of use moving forward, I added a `polyfills/` directory to address these head on.

#### `StyleSheet.absoluteFillObject`

This is only supported in recent versions. It's simply a preset style for a full screen absolutely positioned element.

#### `MinMaxViewPolyfill`

The min/max width/height features of styles are not available on earlier versions of React Native. This adds a Higher Order Component that can declaratively (through props) apply these bounding rules to any child component.

**Comment by ajwhite** [comment]
d5af172 moves the polyfill implementations into `react-native-compat`

**Comment by rmevans9** [comment]
:+1:

How far back do we want to support? I understand we want to make sure that we support older versions of React Native but there has to be a limit to how far back we go.

**Review by rmevans9 — APPROVED** [review]

**Comment by ajwhite** [comment]
> How far back do we want to support? I understand we want to make sure that we support older versions of React Native but there has to be a limit to how far back we go.

It's all about finding the proper balance. Storybook itself doesn't require much UI, so with minimal effort we're able to keep folks on earlier versions supported. If there's any drawback, I think it'll be on the contributor and reviewer side to keep those requirements taught and enforced.

I don't think this is the proper thread to make a formal decision, but it is something to consider moving forward with the compatibility support in, and observe how things go in future reviews.

**Review by shilman — APPROVED** [review]
LGTM and tested

**Pull request merged**
