### PR TITLE
Addon-docs: Docs only MDX and navigation UI

### PR DESCRIPTION
**Pull request by shilman**
Issue: #6644 

## What I did

Documentation-only MDX files get compiled with a dummy story that has parameters `{ docsOnly: true }`. The UI handles renders these components with a document icon and always renders them in docs mode:

docs-only-nav

Here's the MDX that generated the above:

```mdx
import { Meta } from '@storybook/addon-docs/blocks';

<Meta title="Addons|Docs/docs-only" />

# Documentation-only MDX

This file is a documentation-only MDX file, i.e. it doesn't contain any `<Story>` definitions.

Therefore, it shows up in the navigation UI as a document icon.
```

## How to test

```
cd examples/official-storybook
yarn storybook
```

### CODE REVIEW

**Comment by Stephanemw** [comment]
LGTM! Looking forward to using this feature!

**Comment by joeycozza** [comment]
Just want to make sure: 
Because you create a dummy **component**, this would play nicely with [Render Components As Leaves in Docs Mode](https://github.com/storybookjs/storybook/pull/7700), right?

**Comment by shilman** [comment]
Clicking on the docs-only doc should always take you to docs tab. (Even if you don't get back to canvas tab when you click back)

**Comment by shilman** [comment]
@tmeasday @igor-dv @ndelangen 

This was a breaking change because docs-only stories are not renderable and any tools (like storyshots, chromatic, etc.) that try to render the stories will break.

To avoid making a breaking change, I added an options argument to the `raw` and `extract` methods that filters out docs-only stories by default. `dumpStorybook` never exports docs-only stories.

Please take a careful look at this part since it's core code. Comments welcome!

**Comment by tmeasday** [comment]
That seems a reasonable solution.

**Review by tmeasday — APPROVED** [review]
I wonder if having a different set of stories in legacy data (rather than filtering in `getStorybook`) might cause confusion down the road, but I am good with this otherwise

**Comment by kevinSuttle** [comment]
_[Been out of the loop, so trying to catch up.]_

One thing my design team wants is the ability to have _only_ MDX stories. I've supplemented this request by exporting with `--docs` and hiding the toolbar, but JSX files are still required. 

Does this facilitate that, now or in the future?

**Comment by shilman** [comment]
@kevinSuttle This allows you to write MDX without any stories in them but still have it show up in the stories menu. You've been able to write stories in MDX from day 1.

Can you help me understand what your design team wants?

If you want the entire MDX content to show up in the canvas, that's not supported (and probably won't be unless there's something I'm missing). Your workaround of disabling the canvas is probably the right thing here. Would love to discuss more.

And I don't understand why JSX files are still required.

Happy to discuss here or in Discord.

**Comment by kevinSuttle** [comment]
Thanks @shilman. Allow me to explain in a more useful way. My previous post was more confusing than I intended. Forget everything I said :sweat_smile:

My Design team wants this: 



- One non-nested nav item on the left (like you have here in this PR)
- No Canvas tab, or any tabs 
- MDX authoring/file format
- Rendered story `Preview` with
   - Toolbar
   - Story Source (automated)
       - Live editing of source code (eventually, categorized under "nice to have")
   - Prop table (automated—in our case, this isn't possible with Flow, at least not the way we have things configured)

I can get around most of these, as I mentioned. The one hangup for now is that Preview in MDX doesn't generate the Story Source like `Preview` in JSX. 

I also am not sure how to get the toolbar into `Preview`.

Hopefully that helps clarify. Thanks for your patience! :man_bowing:

**Comment by shilman** [comment]
@kevinSuttle Thanks for the clarification. Right now it should do everything you want running in `--docs` mode except for the toolbar, which is WIP and should be ready this week. As for the story source, maybe we can debug that together in Discord?

**Comment by kevinSuttle** [comment]
BTW, is there a way to enable "docs mode" per-story or per-file? What does adding that flag do under the hood?

**Comment by shilman** [comment]
@kevinSuttle enabling docs mode per story or file is not currently supported. Right now the "docs-only stories" do something like that (automatically switch you to docs tab) -- could probably add that to other stories pretty easily. What's the use case?

**Comment by kevinSuttle** [comment]
Just curious. No specific use case.

**Pull request merged**
