### PR TITLE
Refactor: Use Array.includes instead of indexOf

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Use `includes()` to check for existence.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
not stale

**Review by shilman — APPROVED** [review]
LGTM!

**Review by shilman — CHANGES_REQUESTED** [review]
@jamesgeorge007 Do we have the right polyfill for IE?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility

**Comment by jamesgeorge007** [comment]
@shilman I guess we could make use of this polyfill:-
```js
if (!String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    'use strict';
    if (typeof start !== 'number') {
      start = 0;
    }

    if (start + search.length > this.length) {
      return false;
    } else {
      return this.indexOf(search, start) !== -1;
    }
  };
}
```

Is it fine including the respective code-block just above where we use `includes()` :thinking:

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
> @jamesgeorge007 Do we have the right polyfill for IE?
> 
> [developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility)

Should be auto polyfilled by core-js

**Comment by jamesgeorge007** [comment]
@ndelangen hope we're all set to land this one :thinking:

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
