### PR TITLE
addon-docs: Added a button to refresh component

### PR DESCRIPTION
**Pull request by toshi1127**
Issue: #12101

## What I did

Added a button to refresh component.

## How to test

- Is this testable with Jest or Chromatic screenshots?
yes.
I added animation to the component and made sure they were refreshed.
result

- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

### CODE REVIEW

**Comment by shilman** [comment]
@tmeasday @domyen WDYT?

**Comment by tmeasday** [comment]
I would implement this by emitting an event probably. I'm not really sure about the feature -- it sounds like something that an addon should do, but I guess we don't currently have a way for an addon to add buttons here.

**Comment by domyen** [comment]
Unclear about the use case. Is the use case refreshing components that animateIn?

**Comment by toshi1127** [comment]
That's right. You won't have to reload your browser when you want to check the animation.

**Pull request closed without merging**
