### PR TITLE
Document generic addons and knobs select migration

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Added documentation of breaking changes around:
- generic addons
- knobs select key/value reorder

## How to test
N/A

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps?
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by shilman** [comment]
@Hypnosphi do we need a codemod for this?

**Comment by Hypnosphi** [comment]
It wouldn't hurt if it's not too hard to implement. But please don't hurry, we have more plans for select in 4.0: https://github.com/storybooks/storybook/pull/3922#issuecomment-409140069

**Review by danielduan — APPROVED** [review]

**Comment by ndelangen** [comment]
@Hypnosphi I don't think that would need to be a breaking change, it might, but I don't think it's something worth delaying over.

I was also considering proposing exposing a new knob `options` instead of overloading `select` once again. Do you think that would be a good idea?

**Comment by Hypnosphi** [comment]
Sure @ndelangen

**Pull request merged**
