### PR TITLE
Make context argument work with decorators

### PR DESCRIPTION
**Pull request by thani-sh**
Fix a bug where the context argument don't get passed through
decorators.

### CODE REVIEW

**Comment by mnmtanish** [comment]
In the code, the intermediate function is there to make decorators work without any breaking changes. The decorator can simply call `getStory()` without manually forwarding a context argument.

Travis is acting weird with this one, all tests are passing and there are no lint errors.

**Comment by arunoda** [comment]
@mnmtanish I merged this with the recent master and I think it'll work by now.

**Comment by mnmtanish** [comment]
I'll close this one then

**Comment by arunoda** [comment]
I have implemented this in the addons branch and it'll be merged sooner to master.
So, I am closing this.

**Pull request closed without merging**
