### PR TITLE
Addon-docs: CSS classes for escape-hatch theming wrapper/content

### PR DESCRIPTION
**Pull request by alazurenko**
#8051 

## What I did
Created CSS classes for DocsWrapper and DocsContent so it could be customised by end-user of addon-docs by adding specific rules.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Thanks @alazurenko, this is great!

One request is that the `DocsWrapper` and `DocsContent` components get their default styling from Emotion, so we don't need to add those styles to `base-preview-head`. The classes simply allow users to override that styling. Maybe we can add an example of that to `official-storybook`?

**Comment by alazurenko** [comment]
Hi @shilman ,
I've fixed the remarks. However, I haven't found a way to import CSS file to a specific `docs-styles.mdx` file, to show an outcome of the change to container's CSS class in one story file. If I'd add this, those changes are going to be show for every story. This is exactly what I wanted to have in terms of feature, as it would be consistent across all stories.

**Review by shilman — APPROVED** [review]
LGTM! I hijacked your PR and added some stuff to it. Thanks for kicking this off!

**Comment by kevinSuttle** [comment]
Thanks! Will this be documented somewhere?

**Comment by shilman** [comment]
@kevinSuttle https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/theming.md#css-escape-hatches

**Pull request merged**
