### PR TITLE
Add Docgen info to PropTable (#122)

### PR DESCRIPTION
**Pull request by jribeiro**
* Support show docgen prop description

* Update to comply PR

* Update Readme + Example

* Refactor to comply #PR122

Issue:

### CODE REVIEW

**Comment by ndelangen** [comment]
What happened?

**Comment by jribeiro** [comment]
Apologies, trying to apply this commit to my own fork but accidentally created against the main repo.

Looks like this PR (https://github.com/storybooks/react-storybook-addon-info/pull/122) for adding react-docgen to the info addon got lost while migrating repos so I was trying to keep the history and author.

Sorry.

**Comment by ndelangen** [comment]
Are you maintaining a fork? a PR for this is actually welcome! I'm sorry if by some poor timing/managing a PR got lost. Definitely not the intention obviously.

**Comment by jribeiro** [comment]
No. Just forked so I could try to apply the patch cleanly. There's also a small bug on the initial implementation which I fixed here:
https://github.com/jribeiro/react-storybook-addon-info/commit/4b400d230e544eb00e5ecfc0f2104d3426667c93#diff-fba4de7257304fd4af078af93a683822

I'll see if I can apply the original commit from @phthhieu otherwise I'll re-implement it and open a new PR.

Thanks and apologies for the "noise".

**Pull request closed without merging**
