### PR TITLE
Add BBC to list of examples

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Issue:

## What I did
Added the BBC's psammead react component library to the list of examples.

## How to test

- Does this need an update to the documentation? Yes

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
@ndelangen @HarveyPeachey there's no `bbc.jpg` in the PR

**Comment by ndelangen** [comment]
@HarveyPeachey could you please add it asap?

Should I revert @shilman ?

**Comment by shilman** [comment]
Yeah let's revert until there's a thumbnail 🙏

**Comment by HarveyPeachey** [comment]
@shilman @ndelangen There is a `bbc.jpg`? https://github.com/HarveyPeachey/storybook/blob/246734b7bc0e48502d1218d36d11e599509e0efc/docs/src/pages/examples/thumbnails/bbc.jpg

Or have I put it in the wrong directory?

**Comment by shilman** [comment]
sorry @HarveyPeachey my bad -- completely missed that somehow 🙈

will get this fixed. thanks for your patience.

**Pull request merged**
