### PR TITLE
Fix docs typo

### PR DESCRIPTION
**Pull request by christianliebel**
Issue: N/A

## What I did
I changed `Checkgox` to `Checkbox`.

## How to test

N/A

### CODE REVIEW

**Review by jamesgeorge007 — APPROVED** [review]

**Comment by jamesgeorge007** [comment]
cc @ndelangen

**Comment by jamesgeorge007** [comment]
Congrats on your first PR :tada:

**Comment by jamesgeorge007** [comment]
Thanks :heart:

**Comment by jamesgeorge007** [comment]
Also, congrats on getting your very first PR merged :tada:

**Comment by christianliebel** [comment]
Thank you so much! ❤️

**Pull request merged**
