### PR TITLE
FIX configure not being called in preview when there are no stories

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/12705

## What I did

- change so the virtual entrypoint for stories is always added

### CODE REVIEW

**Review by gaetanmaisse — APPROVED** [review]
LGTM

**Review by shilman — CHANGES_REQUESTED** [review]
@ndelangen this appears to be breaking chromatic. can you investigate?

**Comment by ndelangen** [comment]
@shilman I've tested the mithryl-kitchen-sink locally on this branch, and couldn't reproduce :(

```
dev@New-Hampshire ~/Projects/GitHub/storybook/core/examples/mithril-kitchen-sink                                                                    [17:06:45]
ಥ_ಥ  npx -p chromatic chromatic --project-token=8adgm46jzk8                                                     [±12705/always-add-stories-entry-in-preview ●]


npx: installed 326 in 12.223s

Chromatic CLI v5.3.0
https://www.chromatic.com/docs/cli

  ✔ Authenticated with Chromatic
    → Using project token '*******jzk8'
  ✔ Retrieved git information
    → Commit '1e6fcfa' on branch '12705/always-add-stories-entry-in-preview'; found 2 baseline commits
  ✔ Collected Storybook metadata
    → Storybook v6.1.0-rc.3 for React; supported addons found: A11y, Actions, Backgrounds, Cssresources, Design Assets, Docs, Events, Google Analytics, Graphql
, Jest, Knobs, Links, Queryparams, Storyshots, Storysource, Viewport
  ✔ Storybook built in 23 seconds
    → View build log at /Users/dev/Projects/GitHub/storybook/core/examples/mithril-kitchen-sink/build-storybook.log
  ✔ Publish complete in 11 seconds
    → View your Storybook at https://5def63f07bd45f0020ef3d2f-iajohjwxgb.chromatic.com
  ✔ Started build 6060
    → View build details at https://www.chromatic.com/build?appId=5def63f07bd45f0020ef3d2f&number=6060
  ✔ Build 6060 passed!
    → Took 13 snapshots (6 components, 13 stories) in 16 seconds; no changes found

ℹ Speed up Continuous Integration
Your project is linked to GitHub so Chromatic will report results there.
This means you can pass the --exit-once-uploaded flag to skip waiting for build results.
Read more here: https://www.chromatic.com/docs/cli#chromatic-options

✔ Build 6060 passed!
No visual changes were found in this build.
ℹ View build details at https://www.chromatic.com/build?appId=5def63f07bd45f0020ef3d2f&number=6060

⚠ No 'chromatic' script found in your package.json
Would you like me to add it for you? [y/N] n

ℹ No problem. You can add it to your package.json yourself like so:
"scripts": {
  "chromatic": "npx chromatic --project-token 8adgm46jzk8"
}
```

**Comment by gaetanmaisse** [comment]
@ndelangen I updated the branch to get the latest CI workflows and we still have the same issue, it's about `web-components-kitchen-sink`: 
```
 "errorType": "GraphQLError",
  "errorMessage": "✖ Failed to verify your Storybook\nCannot run a build with no stories. Please add some stories!",
  "isolatorUrl": "https://5def65ac9aec2800201cd814-ukdvngkecg.chromatic.com/iframe.html"
```

**Comment by tmeasday** [comment]
I notice that `web-components-kitchen-sink` uses `configure()` directly in `preview.js`.

I'm not quite sure what the best way forward but my feeling is calling `configure()` twice isn't a great idea. I wonder if we need more logic to check if `preview.js` already called `configure()` (it doesn't necessarily have to though).

**Comment by ndelangen** [comment]
> check if `preview.js` already called `configure()`

I don't think that's really possible..

To me the way forward is to no longer allow the direct calling of `configure` in `preview.js`. That's a 7.0 breaking change then.

Alternatively, we can make the second calling of `configure()` do nothing, or simply wrap it in a try-catch?
We can make the warning message after the catch mention that calling `configure()` in `preview.js` is deprecated and users should use the `stories` field in `main.js` to configure stories.

**Comment by shilman** [comment]
we fixed web-components so that it no longer calls configure in preview.js by default

**Comment by ndelangen** [comment]
But users might still be doing it?

**Comment by shilman** [comment]
Yes, but it's no longer the recommended way to set up web components and we can tell users not to do it anymore. The reason that was the template before was that there was no HMR solution for web components prior to 6.3

**Pull request closed without merging**
