### PR TITLE
Development: Manage Node version with .nvmrc

### PR DESCRIPTION
**Pull request by johnhunter**
Closes #

## What I did

Implements changes discussed in https://github.com/storybookjs/storybook/discussions/23909 and reverts changes from PR https://github.com/storybookjs/storybook/pull/23709

1. Remove Volta config from root `package.json`
2. Add an `.nvmrc` file to the project root
3. Update contributing docs to suggest using [FNM](https://github.com/Schniz/fnm) for local development.
4. Update GH actions to use the `.nvmrc` rather than hardcoded node versions.

**Open issues for review**

- The CircleCI workflows use cimgs with specific node versions. Configuring those to use the `.nvmrc` file would be involved. It might be possible with [Dynamic configs](https://circleci.com/docs/dynamic-config/) although maybe not worth it.
- RFC feedback suggests not using the `.nvmrc` node version in the publish script. It looks like these would be called in the canary-release and publish actions which where already hardcoded to node@16

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [x] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by johnhunter** [comment]
Danger task failing on branch due to a 403 on the GitHub user "Resource not accessible by integration".

"Could not add a commit status, the GitHub token for Danger does not have access rights."

**Review by JReinhold — APPROVED** [review]
This all looks good to me! 👍

Don't worry about CircleCI, it's not worth it right now. One day we might migrate to dynamic configs for other reasons.

I'll defer to @kylegach for the docs changes.

**Review by kylegach — APPROVED** [review]
Thanks, @johnhunter. I have no issue with these docs changes.

I'm fairly sure most contributors use `nvm`, though...

**Comment by johnhunter** [comment]
Thanks @kylegach 

> I'm fairly sure most contributors use `nvm`, though...

I think that's true, for them the changes will just work and for new contributors fnm is a faster tool.

I'm not sure of the process - @JReinhold are you able to merge this PR?

**Comment by johnhunter** [comment]
Force-pushed from merge conflicts with upstream next

**Pull request merged**
