### PR TITLE
React: Remove react-dev-utils

### PR DESCRIPTION
**Pull request by Taillook**
Issue: #16093 #17017

## What I did

- don't use WatchMissingNodeModulesPlugin
- `yarn test -u`

checked local `yarn build`, `yarn test` and `cd examples/cra-ts-essentials && yarn storybook`

### CODE REVIEW

**Comment by Taillook** [comment]
> 🧮 E2E Results
cra: KO
sfcVue: OK

😵‍💫

**Comment by Taillook** [comment]
I thought is better wait for green of CI of `next` branch.

**Review by shilman — APPROVED** [review]
Thanks for your contribution @Taillook and thanks for your patience too! 🙏  Merging

**Comment by Scotchester** [comment]
Any possibility of getting this fix backported to the 6.4.x series? We've got multiple repos yelling about the critical-severity immer vulnerability that this is the ultimate fix for, and it looks like 6.5.0 is still a ways off.

**Comment by shilman** [comment]
@Scotchester Can you verify that 6.5 fixes the issue for you? Once I have a few confirmations, I can patch it back to 6.4.x

**Comment by Scotchester** [comment]
Yes, I can confirm that once I updated my project to 6.5 alpha, the GitHub security alert pertaining to immer has been resolved.

**Comment by Scotchester** [comment]
🙌 Thank you so much!

**Pull request merged**
