### PR TITLE
Moved to lerna 3

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@shilman any objections?

**Comment by igor-dv** [comment]
Will this fix #1433 ?

**Review by shilman — COMMENTED** [review]
Hey @pksunkara ! I tried out this branch publishing to a local NPM registry per @ndelangen 's CLI tests.

I have a few questions before merging.

1. This version apparently doesn't support `--force-publish`, which we currently use to publish all the packages at the same version.

2. It also doesn't seem to support `--skip-git` which makes it harder to test without messing up our git repo

3. When I run it against the local registry I see a lot of errors:

```
MMBP:storybook shilman$ npm run publish:alpha

> @storybook/root@4.0.0-alpha.16 publish:alpha /Users/shilman/projects/storybook/new/storybook
> npm run publish -- --concurrency 1 --force-publish=* --npm-tag=alpha prerelease


> @storybook/root@4.0.0-alpha.16 publish /Users/shilman/projects/storybook/new/storybook
> lerna publish --exact "--concurrency" "1" "--force-publish=*" "--npm-tag=alpha" "prerelease"

lerna notice cli v3.1.4
lerna info current version 4.0.0-alpha.18
lerna ERR! Error: Command failed: git remote update
lerna ERR! fatal: Couldn't find remote ref refs/heads/reproduce-against-master
lerna ERR! error: Could not fetch storybooks
lerna ERR! fatal: Couldn't find remote ref refs/heads/patch-1
lerna ERR! error: Could not fetch joeybaker
lerna ERR! fatal: Couldn't find remote ref refs/heads/patch-1
lerna ERR! error: Could not fetch joscha
lerna ERR! fatal: Couldn't find remote ref refs/heads/haul-support
lerna ERR! error: Could not fetch ericwooley
lerna ERR! fatal: Couldn't find remote ref refs/heads/add-parser-option-getstorybook
lerna ERR! error: Could not fetch AugustinLF
lerna ERR! fatal: Couldn't find remote ref refs/heads/storybook-native-ui
lerna ERR! error: Could not fetch matt-oakes
lerna ERR! fatal: Couldn't find remote ref refs/heads/patch-1
lerna ERR! error: Could not fetch Hypnosphi
lerna ERR! fatal: remote error:
lerna ERR!   Repository not found.
lerna ERR! error: Could not fetch mrmartineau
lerna ERR! fatal: Couldn't find remote ref refs/heads/fixes-877
lerna ERR! error: Could not fetch mattleff
lerna ERR!
lerna ERR! Fetching origin
lerna ERR! Fetching ajfuller
lerna ERR! Fetching storybooks
lerna ERR! Fetching joeybaker
lerna ERR! Fetching ranneyd
lerna ERR! Fetching joscha
lerna ERR! Fetching ericwooley
lerna ERR! Fetching AugustinLF
lerna ERR! Fetching igor-dv
lerna ERR! Fetching thomasbertet
lerna ERR! Fetching marcfallows
lerna ERR! Fetching jhurley23
lerna ERR! Fetching matt-oakes
lerna ERR! Fetching ajwhite
...
```

FYI: I tried upgrading to `3.2.1` and am getting the same errors.

**Review by shilman — CHANGES_REQUESTED** [review]
Don't think this is ready to merge until we can fix the above issues.

**Comment by pksunkara** [comment]
I have updated the PR. And in this comment I will be addressing your review.

> This version apparently doesn't support --force-publish, which we currently use to publish all the packages at the same version.

It does support it. It's documented [here](https://github.com/lerna/lerna/tree/master/commands/version#--force-publish). All `lerna version` keywords are supported by `lerna publish`

> It also doesn't seem to support --skip-git which makes it harder to test without messing up our git repo

It has been deprecated, but it still works for now. It has been divided into `--no-git-tag-version` and `--no-push` as can be seen [here](https://github.com/lerna/lerna/blob/21e134c3d11e3ce688735bf1b59d37f847c19b3c/commands/version/command.js#L168)

> npm run publish:alpha

I am not sure what errors you got. It looks like some git errors and not related to lerna. I will be pasting the logs from my local lerna testing of the publish workflow now on a personal fork of storybook repo.

I have upgraded the lerna after taking the recent release. You can see the git log below

```
● ⍴/storybooks/storybook master → git lg
* 626c8c36a (HEAD -> master, origin/master) Using lerna 3
* 620dc75db (tag: v4.0.0-alpha.20) v4.0.0-alpha.20
* bf8da874e 4.0.0-alpha.20 changelog
* caaf1aa09 (tag: v4.0.0-alpha.19) v4.0.0-alpha.19
```

Running publish:alpha with debug

```
● ⍴/storybooks/storybook master → yarn publish:alpha
yarn run v1.9.4
$ npm run publish -- --force-publish --npm-tag=alpha --loglevel=debug

> @storybook/root@4.0.0-alpha.16 publish /Users/pksunkara/Coding/storybooks/storybook
> lerna publish --exact --concurrency 1  "--force-publish" "--npm-tag=alpha" "--loglevel=debug"

lerna sill argv { _: [ 'publish' ],
lerna sill argv   exact: true,
lerna sill argv   concurrency: 1,
lerna sill argv   'force-publish': true,
lerna sill argv   forcePublish: true,
lerna sill argv   'npm-tag': 'alpha',
lerna sill argv   npmTag: 'alpha',
lerna sill argv   loglevel: 'debug',
lerna sill argv   composed: 'publish',
lerna sill argv   lernaVersion: '3.3.0',
lerna sill argv   '$0':
lerna sill argv    '/Users/pksunkara/Coding/storybooks/storybook/node_modules/.bin/lerna' }
lerna notice cli v3.3.0
lerna verb rootPath /Users/pksunkara/Coding/storybooks/storybook
lerna sill argv { _: [ 'publish' ],
lerna sill argv   exact: true,
lerna sill argv   concurrency: 1,
lerna sill argv   'force-publish': true,
lerna sill argv   forcePublish: true,
lerna sill argv   'npm-tag': 'alpha',
lerna sill argv   npmTag: 'alpha',
lerna sill argv   loglevel: 'debug',
lerna sill argv   composed: 'publish',
lerna sill argv   lernaVersion: '3.3.0',
lerna sill argv   '$0':
lerna sill argv    '/Users/pksunkara/Coding/storybooks/storybook/node_modules/.bin/lerna' }
lerna verb rootPath /Users/pksunkara/Coding/storybooks/storybook
lerna info current version 4.0.0-alpha.20
lerna sill isAnythingCommitted 
lerna verb isAnythingCommitted 1
lerna sill currentBranch 
lerna verb currentBranch master
lerna sill isBehindUpstream 
lerna sill isBehindUpstream master is behind origin/master by 0 commit(s) and ahead by 0
lerna sill hasTags 
lerna verb hasTags true
lerna sill git-describe.sync "v4.0.0-alpha.20-1-g626c8c36a" => {"lastTagName":"v4.0.0-alpha.20","lastVersion":"v4.0.0-alpha.20","refCount":"1","sha":"626c8c36a","isDirty":false}
lerna info Looking for changed packages since v4.0.0-alpha.20
lerna verb updated @storybook/addon-a11y
lerna verb updated @storybook/addon-actions
lerna verb updated @storybook/addon-backgrounds
lerna verb updated @storybook/addon-centered
lerna verb updated @storybook/addon-events
lerna verb updated @storybook/addon-graphql
lerna verb updated @storybook/addon-info
lerna verb updated @storybook/addon-jest
lerna verb updated @storybook/addon-knobs
lerna verb updated @storybook/addon-links
lerna verb updated @storybook/addon-notes
lerna verb updated @storybook/addon-options
lerna verb updated @storybook/addon-storysource
lerna verb updated @storybook/addon-viewport
lerna verb updated @storybook/addon-storyshots
lerna verb updated @storybook/addon-storyshots-puppeteer
lerna verb updated @storybook/angular
lerna verb updated @storybook/html
lerna verb updated @storybook/marko
lerna verb updated @storybook/mithril
lerna verb updated @storybook/polymer
lerna verb updated @storybook/react-native
lerna verb updated @storybook/react
lerna verb updated @storybook/riot
lerna verb updated @storybook/svelte
lerna verb updated @storybook/vue
lerna verb updated angular-cli
lerna verb updated cra-kitchen-sink
lerna verb updated html-kitchen-sink
lerna verb updated marko-cli
lerna verb updated mithril-example
lerna verb updated official-storybook
lerna verb updated polymer-cli
lerna verb updated riot-example
lerna verb updated svelte-example
lerna verb updated vue-example
lerna verb updated @storybook/addons
lerna verb updated @storybook/channel-postmessage
lerna verb updated @storybook/channel-websocket
lerna verb updated @storybook/channels
lerna verb updated @storybook/cli
lerna verb updated @storybook/client-logger
lerna verb updated @storybook/codemod
lerna verb updated @storybook/components
lerna verb updated @storybook/core-events
lerna verb updated @storybook/core
lerna verb updated @storybook/node-logger
lerna verb updated @storybook/ui
lerna verb git-describe undefined => "v4.0.0-alpha.20-1-g626c8c36a"
lerna sill git-describe parsed => {"lastTagName":"v4.0.0-alpha.20","lastVersion":"v4.0.0-alpha.20","refCount":"1","sha":"626c8c36a","isDirty":false}
? Select a new version (currently 4.0.0-alpha.20) Custom Prerelease
? Enter a prerelease identifier (default: "alpha", yielding 4.0.0-alpha.21) 4.0.0-alpha.21

Changes:
 - @storybook/addon-a11y: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-actions: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-backgrounds: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-centered: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-events: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-graphql: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-info: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-jest: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-knobs: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-links: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-notes: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-options: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-storysource: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-viewport: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-storyshots: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/addon-storyshots-puppeteer: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/angular: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/html: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/marko: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/mithril: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/polymer: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/react-native: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/react: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/riot: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/svelte: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/vue: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - angular-cli: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - cra-kitchen-sink: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - html-kitchen-sink: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - marko-cli: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - mithril-example: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - official-storybook: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - polymer-cli: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - riot-example: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - svelte-example: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - vue-example: 4.0.0-alpha.20 => 4.0.0-alpha.21 (private)
 - @storybook/addons: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/channel-postmessage: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/channel-websocket: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/channels: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/cli: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/client-logger: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/codemod: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/components: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/core-events: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/core: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/node-logger: 4.0.0-alpha.20 => 4.0.0-alpha.21
 - @storybook/ui: 4.0.0-alpha.20 => 4.0.0-alpha.21

? Are you sure you want to publish these packages? Yes
```

As you can see, `--force-publish` worked. Here is the git log showing that a new tag has been pushed.

```
● ⍴/storybooks/storybook master → git lg
* d0fa7c570 (HEAD -> master, tag: v4.0.0-alpha.21, origin/master) v4.0.0-alpha.21
* 626c8c36a Using lerna 3
* 620dc75db (tag: v4.0.0-alpha.20) v4.0.0-alpha.20
* bf8da874e 4.0.0-alpha.20 changelog
* caaf1aa09 (tag: v4.0.0-alpha.19) v4.0.0-alpha.19
```

Now, I created a commit representing a new change in the package.

```
● ⍴/storybooks/storybook master → touch a
● ⍴/storybooks/storybook master☭  → git commit -am "Touch a"
[master dfeb0d068] Touch a
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
```

Now, trying to publish with `--skip-git`

```
● ⍴/storybooks/storybook master 1↑  → yarn publish:alpha -- --skip-git
yarn run v1.9.4
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ npm run publish -- --force-publish --npm-tag=alpha --loglevel=debug --skip-git

> @storybook/root@4.0.0-alpha.16 publish /Users/pksunkara/Coding/storybooks/storybook
> lerna publish --exact --concurrency 1  "--force-publish" "--npm-tag=alpha" "--loglevel=debug" "--skip-git"

WARN deprecated --skip-git has been replaced by --no-git-tag-version --no-push
lerna sill argv { _: [ 'publish' ],
lerna sill argv   exact: true,
lerna sill argv   concurrency: 1,
lerna sill argv   'force-publish': true,
lerna sill argv   forcePublish: true,
lerna sill argv   'npm-tag': 'alpha',
lerna sill argv   npmTag: 'alpha',
lerna sill argv   loglevel: 'debug',
lerna sill argv   composed: 'publish',
lerna sill argv   lernaVersion: '3.3.0',
lerna sill argv   '$0':
lerna sill argv    '/Users/pksunkara/Coding/storybooks/storybook/node_modules/.bin/lerna',
lerna sill argv   gitTagVersion: false,
lerna sill argv   'git-tag-version': false,
lerna sill argv   push: false }
lerna notice cli v3.3.0
lerna verb rootPath /Users/pksunkara/Coding/storybooks/storybook
lerna sill argv { _: [ 'publish' ],
lerna sill argv   exact: true,
lerna sill argv   concurrency: 1,
lerna sill argv   'force-publish': true,
lerna sill argv   forcePublish: true,
lerna sill argv   'npm-tag': 'alpha',
lerna sill argv   npmTag: 'alpha',
lerna sill argv   loglevel: 'debug',
lerna sill argv   composed: 'publish',
lerna sill argv   lernaVersion: '3.3.0',
lerna sill argv   '$0':
lerna sill argv    '/Users/pksunkara/Coding/storybooks/storybook/node_modules/.bin/lerna',
lerna sill argv   gitTagVersion: false,
lerna sill argv   'git-tag-version': false,
lerna sill argv   push: false }
lerna verb rootPath /Users/pksunkara/Coding/storybooks/storybook
lerna info current version 4.0.0-alpha.21
lerna sill isAnythingCommitted 
lerna verb isAnythingCommitted 1
lerna sill currentBranch 
lerna verb currentBranch master
lerna sill hasTags 
lerna verb hasTags true
lerna sill git-describe.sync "v4.0.0-alpha.21-1-gdfeb0d068" => {"lastTagName":"v4.0.0-alpha.21","lastVersion":"v4.0.0-alpha.21","refCount":"1","sha":"dfeb0d068","isDirty":false}
lerna info Looking for changed packages since v4.0.0-alpha.21
lerna verb updated @storybook/addon-a11y
lerna verb updated @storybook/addon-actions
lerna verb updated @storybook/addon-backgrounds
lerna verb updated @storybook/addon-centered
lerna verb updated @storybook/addon-events
lerna verb updated @storybook/addon-graphql
lerna verb updated @storybook/addon-info
lerna verb updated @storybook/addon-jest
lerna verb updated @storybook/addon-knobs
lerna verb updated @storybook/addon-links
lerna verb updated @storybook/addon-notes
lerna verb updated @storybook/addon-options
lerna verb updated @storybook/addon-storysource
lerna verb updated @storybook/addon-viewport
lerna verb updated @storybook/addon-storyshots
lerna verb updated @storybook/addon-storyshots-puppeteer
lerna verb updated @storybook/angular
lerna verb updated @storybook/html
lerna verb updated @storybook/marko
lerna verb updated @storybook/mithril
lerna verb updated @storybook/polymer
lerna verb updated @storybook/react-native
lerna verb updated @storybook/react
lerna verb updated @storybook/riot
lerna verb updated @storybook/svelte
lerna verb updated @storybook/vue
lerna verb updated angular-cli
lerna verb updated cra-kitchen-sink
lerna verb updated html-kitchen-sink
lerna verb updated marko-cli
lerna verb updated mithril-example
lerna verb updated official-storybook
lerna verb updated polymer-cli
lerna verb updated riot-example
lerna verb updated svelte-example
lerna verb updated vue-example
lerna verb updated @storybook/addons
lerna verb updated @storybook/channel-postmessage
lerna verb updated @storybook/channel-websocket
lerna verb updated @storybook/channels
lerna verb updated @storybook/cli
lerna verb updated @storybook/client-logger
lerna verb updated @storybook/codemod
lerna verb updated @storybook/components
lerna verb updated @storybook/core-events
lerna verb updated @storybook/core
lerna verb updated @storybook/node-logger
lerna verb updated @storybook/ui
lerna WARN version Skipping working tree validation, proceed at your own risk
? Select a new version (currently 4.0.0-alpha.21) Custom Prerelease
? Enter a prerelease identifier (default: "alpha", yielding 4.0.0-alpha.22) 4.0.0-alpha.22

Changes:
 - @storybook/addon-a11y: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-actions: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-backgrounds: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-centered: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-events: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-graphql: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-info: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-jest: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-knobs: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-links: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-notes: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-options: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-storysource: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-viewport: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-storyshots: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/addon-storyshots-puppeteer: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/angular: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/html: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/marko: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/mithril: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/polymer: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/react-native: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/react: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/riot: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/svelte: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/vue: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - angular-cli: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - cra-kitchen-sink: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - html-kitchen-sink: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - marko-cli: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - mithril-example: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - official-storybook: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - polymer-cli: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - riot-example: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - svelte-example: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - vue-example: 4.0.0-alpha.21 => 4.0.0-alpha.22 (private)
 - @storybook/addons: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/channel-postmessage: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/channel-websocket: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/channels: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/cli: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/client-logger: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/codemod: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/components: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/core-events: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/core: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/node-logger: 4.0.0-alpha.21 => 4.0.0-alpha.22
 - @storybook/ui: 4.0.0-alpha.21 => 4.0.0-alpha.22

? Are you sure you want to publish these packages? Yes
lerna info execute Skipping git tag/commit
lerna info execute Skipping git push
```

If I do git log now, you will see that there are no extra commits

```
● ⍴/storybooks/storybook master 1↑ ☭  → git lg
* dfeb0d068 (HEAD -> master) Touch a
* d0fa7c570 (tag: v4.0.0-alpha.21, origin/master) v4.0.0-alpha.21
* 626c8c36a Using lerna 3
* 620dc75db (tag: v4.0.0-alpha.20) v4.0.0-alpha.20
* bf8da874e 4.0.0-alpha.20 changelog
* caaf1aa09 (tag: v4.0.0-alpha.19) v4.0.0-alpha.19
```

When I do `git diff`, you can see the `alpha.22` changes have been written into package.json files

```
● ⍴/storybooks/storybook master 1↑ ☭  → git d
diff --git a/addons/a11y/package.json b/addons/a11y/package.json
index 66558b05a..6704a8da5 100644
--- a/addons/a11y/package.json
+++ b/addons/a11y/package.json
@@ -1,6 +1,6 @@
 {
   "name": "@storybook/addon-a11y",
-  "version": "4.0.0-alpha.21",
+  "version": "4.0.0-alpha.22",
   "description": "a11y addon for storybook",
   "keywords": [
     "a11y",
@@ -26,10 +26,10 @@
   },
   "dependencies": {
     "@emotion/styled": "0.10.5",
-    "@storybook/addons": "4.0.0-alpha.21",
-    "@storybook/client-logger": "4.0.0-alpha.21",
-    "@storybook/components": "4.0.0-alpha.21",
-    "@storybook/core-events": "4.0.0-alpha.21",
+    "@storybook/addons": "4.0.0-alpha.22",
+    "@storybook/client-logger": "4.0.0-alpha.22",
+    "@storybook/components": "4.0.0-alpha.22",
+    "@storybook/core-events": "4.0.0-alpha.22",
     "axe-core": "^3.0.3",
     "global": "^4.3.2",
     "prop-types": "^15.6.2"
```

I am now really convinced that the errors you had were because of something different.

**Comment by shilman** [comment]
OK let's give this a try! 👍 👍 👍

**Pull request merged**
