### PR TITLE
Ensure no duplicate code in preview when using vite

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/20514

## What I did

I switched out one rollup plugin for a vite plugin, and after a bit of experimentation I found the setting that would cause no duplicate code, and make vite 100% use the prebundled code, and never include prebundled code

### CODE REVIEW

**Comment by ndelangen** [comment]
Replaced this:
https://www.npmjs.com/package/rollup-plugin-external-globals

With this:
https://www.npmjs.com/package/vite-plugin-externals

**Comment by ndelangen** [comment]
I verified that `getSelectionSpecifierFromPath` is only defined once in the preview in these 4 situations:

- webpack dev
- webpack build
- vite dev
- vite build

**Review by IanVS — APPROVED** [review]
Oh wow, nice win!  Thanks for figuring this one out.

**Comment by thebuilder** [comment]
@ndelangen see #20643 - It appears the [vite-plugin-externals](https://www.npmjs.com/package/vite-plugin-externals) plugin breaks HMR. Might work with the `disableInServe: true` option? Can it be set true in `dev` in dev mode?

**Comment by IanVS** [comment]
@thebuilder we figured that out as well, but unfortunately we need to replace the externals in dev as well.  You can watch https://github.com/storybookjs/storybook/pull/20655 for any progress.

**Comment by IanVS** [comment]
@ndelangen I'm testing out a different approach, but not sure it's doing what we want.  Could you explain the method you used to verify that `getSelectionSpecifierFromPath` is only included once in the preview?

**Comment by ndelangen** [comment]
@IanVS the way I used was this:

- I start storybook in dev-mode (using vite). any sandbox with vite will do.
- I open the browser and open dev-tools
- I open the global search tool ,and search for the string I know will appear in the prebundle, and should NOT be in the vite-bundle.
- If it finds it twice, I know things are wrong.

Screenshot 2023-01-23 at 11 51 18

I then do the same for build-mode.

**Pull request merged**
