### PR TITLE
Inline emotion css calls that require theme to avoid using state

### LINKED ISSUE #3840: Cannot read property 'mainBorder' of undefined
After upgrading from 4.0.0-alpha.9 to 4.0.0-alpha.12 i got this error ` Cannot read property 'mainBorder' of undefined`.

Anyone know what cause this error ? 
It looks like it comes from the theme.

I set the theme in `setOptions`.
```
import { themes } from '@storybook/components';
setOptions({ 
 ...
  theme: themes.normal
});
```

### PR DESCRIPTION
**Pull request by tkh44**
Issue:

`getDerivedStateFromProps` can be called before the prop `theme` is set by react-emotion which causes errors.

## What I did

Inlined the `css` calls instead of placing them on the component's state. `withTheme` will rerender this component when the `theme` changes so there is no need to use `getDerivedStateFromProps`.

## How to test

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps?
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

fixes #3840

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by tkh44** [comment]
I've tried to get all the checks but I am unable to get it right. If someone could give me some pointers I'd be grateful.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Thank you @tkh44 !

**Comment by tkh44** [comment]
@ndelangen I should have been more clear that this is a bugfix and the bug this issue causes keeps the storybook from rendering at all in the latest alpha releases in some situations. I couldn't pin down the exact cause of the bug but this PR fixes it.

image

**Comment by ndelangen** [comment]
@shilman as @tkh44 mentions, let's do an alpha release rather quick?

**Pull request merged**
