### PR TITLE
migrate @storybook/addon-mdx-gfm to strict TS

### PR DESCRIPTION
**Pull request by 1234tgk**
Issue #22176

## What I did

Adjust the code so that the package allows strict typing.

## How to test

Run yarn check on @storybook/addon-mdx-gfm directory.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by kasperpeulen — APPROVED** [review]
LGTM and thanks!

**Comment by jonniebigodes** [comment]
@1234tgk, one thing left to address as part of this initiative and the amazing work you did by helping us convert Storybook's packages to allow stricter TypeScript support. If you're ok with it, can you message me on our [Discord server](https://discord.gg/storybook) ( same username) so that I can follow up with you?


Hope you have a fantastic day.

Stay safe

**Comment by 1234tgk** [comment]
@jonniebigodes Hello! Which discord channel should I message you from? I've only send messages at wg-typescript channel previously.

**Comment by jonniebigodes** [comment]
If you're ok with it, you can message me directly, or if you're not comfortable with it, drop a message in the `wg-typescript` channel and tag me and I'll follow up with you.

**Comment by 1234tgk** [comment]
@jonniebigodes Just sent you a friend request instead since I couldn't send a DM to you (Discord blocked me from doing so)

**Comment by jonniebigodes** [comment]
@1234tgk no worries there. I just saw the notification and will follow up with you.

**Pull request merged**
