### PR TITLE
Vue2: Source Decorator reactivity

### LINKED ISSUE #23132: [Bug]: Code block does not react to controls changes for Vue components
### Describe the bug

In docs pages, interacting with the default story's controls does not have any effect on the source code block. The story itself does re-render properly to reflect the controls' state. But the code block seems to be stuck on the initial values.

Screenshot 2023-06-19 at 7 24 10 AM

### To Reproduce

https://gitlab-org.gitlab.io/gitlab-ui/?path=/docs/base-alert--docs

Expand the default story's code and interact with controls below.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.5
  npmPackages:
    @storybook/addon-a11y: 7.0.20 => 7.0.20
    @storybook/addon-docs: 7.0.20 => 7.0.20
    @storybook/addon-essentials: 7.0.20 => 7.0.20
    @storybook/addon-storyshots: 7.0.20 => 7.0.20
    @storybook/addon-storyshots-puppeteer: 7.0.20 => 7.0.20
    @storybook/addon-viewport: 7.0.20 => 7.0.20
    @storybook/builder-webpack5: 7.0.20 => 7.0.20
    @storybook/theming: 7.0.20 => 7.0.20
    @storybook/vue: 7.0.20 => 7.0.20
    @storybook/vue-webpack5: 7.0.20 => 7.0.20
    @storybook/vue3: 7.0.20 => 7.0.20
    @storybook/vue3-webpack5: 7.0.20 => 7.0.20
```

### Additional context

This used to work in older versions of Storybook, but I don't remember what exact version that was. Likely Storybook 6 though.

Tried Storybook v7.1.0-alpha.36 as well, the issue is still there.

### PR DESCRIPTION
**Pull request by chakAs3**
Closes #23132

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by kasperpeulen** [comment]
We will merge this in for the 7.2-alpha.

**Review by kasperpeulen — APPROVED** [review]
LGTM

**Comment by OssamaSijbesma** [comment]
@chakAs3 slots are still not reactive (Storybook v2.7.1), it is not updating the slot but an unrelated prop instead.

Screenshot 2023-08-03 162132

**Comment by chakAs3** [comment]
hi @OssamaSijbesma for now slots reactivity is not supported in Vue2.  Please open a new issue regarding this and mention me, so i can look at it.

**Pull request merged**
