### PR TITLE
Controls: Fix type summary when table.type unset

### LINKED ISSUE #25909: [Bug]: Storybook v8.0.0-alpha.16 unknown types
This is happening in a nextjs14 project with typescript.

this is part of my package.json
```
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "test": "jest",
    "test:watch": "jest --watchAll",
    "story": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "next": "14.0.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "styled-components": "^6.1.8"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^8.0.0-alpha.16",
    "@storybook/addon-interactions": "^8.0.0-alpha.16",
    "@storybook/addon-links": "^8.0.0-alpha.16",
    "@storybook/addon-onboarding": "^1.0.10",
    "@storybook/blocks": "^8.0.0-alpha.16",
    "@storybook/nextjs": "^8.0.0-alpha.16",
    "@storybook/react": "^8.0.0-alpha.16",
    "@storybook/test": "^8.0.0-alpha.16",
    "@testing-library/jest-dom": "^6.2.0",
    "@testing-library/react": "^14.1.2",
    "@types/jest": "^29.5.11",
    "@types/node": "^20",
    "@types/react": "^18.2.51",
    "@types/react-dom": "^18",
    "@types/styled-components": "^5.1.34",
    "@typescript-eslint/eslint-plugin": "^6.20.0",
    "@typescript-eslint/parser": "^6.20.0",
    "eslint": "^8.56.0",
    "eslint-config-next": "14.0.4",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-storybook": "^0.6.15",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "prettier": "^3.2.4",
    "storybook": "^8.0.0-alpha.16",
    "ts-jest": "^29.1.2",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3"
```

image

My config seems to be fine. Types of props are not being defined in the storybook docs

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shilman**
Closes: https://github.com/storybookjs/storybook/issues/25909

## What I did

When the user specifies a `type` but there is no `table.type` annotation generated, display this correctly in the ArgRow components

#### The changes in this PR are covered in the following automated tests:
- [x] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

See the Chromatic changes for the `ArgRow` stories

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by ndelangen** [comment]
Does this fix: https://github.com/storybookjs/storybook/issues/25909 @shilman ?

**Comment by shilman** [comment]
@ndelangen I haven't tested it. It fixes the bug we looked at together yesterday, but that may or may not fix the bigger problem. I can take a closer look this weekend.

**Comment by ndelangen** [comment]
OK, you might want to use both reproductions in the issue, they seem related, but are different.

I suspect [the second one](https://github.com/storybookjs/storybook/issues/25909#issuecomment-1973084430) has a completely different cause.

**Comment by shilman** [comment]
@ndelangen I commented on the cause of the second issue. Self-merging this PR which fixes a bug, possibly not related to either of the issues in the linked issue.

**Pull request merged**
