### PR TITLE
fix(angular): removing deprecated import to fix storyshots

### LINKED ISSUE #21652: [Bug]: TypeError: Cannot read properties of undefined (reading 'clientApi')
### Describe the bug

After trying to update to storybook@7.0.0-rc.4 for TS 5.0 support, I'm seeing

```
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'clientApi')

      11 | );
      12 |
    > 13 | initStoryshots();
         |               ^
      14 |

      at .yarn/__virtual__/@storybook-addon-storyshots-virtual-f338e9c3bc/0/cache/@storybook-addon-storyshots-npm-7.0.0-rc.4-b1d5a8161c-7f08071aeb.zip/node_modules/@storybook/addon-storyshots/dist/frameworks/react/loader.js:25:49
      at Object.load (.yarn/__virtual__/@storybook-addon-storyshots-virtual-f338e9c3bc/0/cache/@storybook-addon-storyshots-npm-7.0.0-rc.4-b1d5a8161c-7f08071aeb.zip/node_modules/@storybook/addon-storyshots/dist/frameworks/react/loader.js:30:23)
      at loadFramework (.yarn/__virtual__/@storybook-addon-storyshots-virtual-f338e9c3bc/0/cache/@storybook-addon-storyshots-npm-7.0.0-rc.4-b1d5a8161c-7f08071aeb.zip/node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:36:19)
      at testStorySnapshots (.yarn/__virtual__/@storybook-addon-storyshots-virtual-f338e9c3bc/0/cache/@storybook-addon-storyshots-npm-7.0.0-rc.4-b1d5a8161c-7f08071aeb.zip/node_modules/@storybook/addon-storyshots/dist/api/index.js:28:99)
      at Object.<anonymous> ([OBFUSCATED_PATH]/storyshots.test.ts:13:15)
```

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
```
```


### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manbearwiz**
Closes #21652

## What I did

Update import from `core-client` to `preview-api`. Seems like this was missed as part of PR https://github.com/storybookjs/storybook/pull/19749.

This was causing the warning `importing from @storybook/core-client is deprecated and will be removed in 8.0, please import canvas related modules from @storybook/preview-api` and error `TypeError: Cannot read properties of undefined (reading 'clientApi')` when running storyshots.

## How to test

I tested via linking to a working project. I probably can come up with a minimum reproduction case if need be, but Angular + Jest + Storyshots is sorta an [interesting configuration](https://github.com/storybookjs/storybook/blob/187b02b0ce8797495d17ce93626c160e4fc3af60/code/addons/storyshots-core/src/frameworks/angular/loader.ts#L7) and runs take a long time.  

-->

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by manbearwiz** [comment]
Rebased

**Comment by valentinpalkovic** [comment]
Hi @manbearwiz,

Thank you so much for your contribution. Might you resolve the conflicts. I will merge the PR then as soon as the pipeline is green.

**Review by valentinpalkovic — APPROVED** [review]

**Comment by manbearwiz** [comment]
Rebased

**Comment by manbearwiz** [comment]
@valentinpalkovic rebased again. Should be good to go now.

**Comment by manbearwiz** [comment]
It looks like e2e tests are failing, any insight into that? they are using the cra sandbox, the change in this PR shouldn't affect that.

**Pull request merged**
