### PR TITLE
Core: Add typings for globalTypes

### PR DESCRIPTION
**Pull request by timkinnane**
Issue: #12658 

## What I did

- Add type definition for global types toolbar annotation.
- Add documentation code snippets showing TS versions of existing JS snippets.
- Add example at `storybook/examples/react-ts-globals` using the `GlobalTypes` type to define a global toolbar with controls for language selection.

The example helped me confirm usage of the exported type, but I'm not sure it's as useful as other top level examples, so maintainers might feel like removing the example file additions from this PR. I'd be happy either way.

## How to test

No tests added as only added one type which is a basic composition of existing types.

The included example demonstrates the type usage. The fact this compiles without type errors could be taken as a pass?

Documentation was updated at the link below, to show an example of a Typescript version similar to `preview.ts` from the example provided in this PR.

https://storybook.js.org/docs/react/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation

---

*Docs preview*

Screen Shot 2021-05-29 at 4 24 42 pm

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Thank you @timkinnane !! I took a look and this looks great.

I'm a little concerned with how this plays out when we add more globalTypes. We'll increasingly use this for other addons as a way to configure state (current background, current viewport, etc.). I just want to make sure that this solution composes well with those types. cc @yannbf

**Comment by yannbf** [comment]
Hey @timkinnane nice contribution! I believe that will not suffice though. The return type in [this line](https://github.com/storybookjs/storybook/pull/15088/files#diff-725878bc91696560defce822dcdfca77649c2a61052a65b02f7582968cf67a99R19) is of type `any` for instance. Ideally we'd like to have this type defined once and shared across every place where GlobalTypes are used.. I think we can only achieve that with module augmentation, following practice that is already used in libraries like [Material UI](https://material-ui.com/guides/typescript/#customization-of-theme) and [Styled components](https://styled-components.com/docs/api#create-a-declarations-file)

**Comment by timkinnane** [comment]
@shilman, yes I was also a bit confused about the semantics coming into this. I just exported the type as `GlobalTypes` to match the `globalTypes` const but that's obviously very generic and not semantically indicative of the toolbar type's it contains.

> concerned with how this plays out when we add more globalTypes

Are you saying there could be other types exported within `globalTypes` in the preview file? So it would end up more like `Record<string, ToolbarArgType | ViewportArgType>`? Or would there be different types of `globalTypes` exported at different locations, so it would make more sense to export something like `GlobalToolbarTypes` and `GlobalViewportTypes`?

**Comment by shilman** [comment]
Yeah `ToolbarGlobalTypes` sounds good to me. But I haven't checked if the type  `ToolbarGlobalTypes | ViewportGlobalTypes` is semantically equivalent to `Record<string, ToolbarGlobalType | ViewportGlobalType>`. If it is, that's perfect. If not, we should think harder about how this will work.

**Comment by timkinnane** [comment]
@yannbf thanks for the input. I agree it would be great to have the output of `useGlobals` expose the custom types. I was focused on the goal of just allowing TS projects to make strict config declarations and not mix JS/TS.
Is it possible to limit the scope of this issue to that or would a short term fix get in the way of the optimal capability?

> I think we can only achieve that with module augmentation

I'll have a look at that, but it could be quite a challenge to expose something that's simple to consume, because it's not a direct type mapping between `globalTypes` and the values returned by `useGlobals`. `GlobalTypes` might need to accept type arguments to narrow the constraints for toolbar value types and the augmentation might need some utility to map the toolbar config type to the type of values returned by `useGlobals`. e.g.

```ts
type GlobalTypesToolbarItemValues<T extends GlobalTypes> = {
  [K in keyof T]: T[K]['toolbar']['items'][number]['value'];
};
type GlobalValues = GlobalTypesToolbarItemValues<typeof globalTypes>;
```

In the case of the example that would define a type that could be used to augment `useGlobals` returns:

```ts
type GlobalValues = {
    locale: 'EN' | 'FR' | '...etc';
}
```

Or if it wasn't worth that complexity to achieve strict narrow types, since toolbar values are all strings by default, it could be simply:

```ts
type GlobalTypesToolbarItemValues<T extends GlobalTypes> = {
  [K in keyof T]: T[K]: string;
};
type GlobalValues = GlobalTypesToolbarItemValues<typeof globalTypes>;
```
```ts
type GlobalValues = {
    locale: string
}
```

There are simpler alternatives to module augmentation, like letting `useGlobal` take optional type arguments, e.g.

```ts
// hooks.d.ts
export declare function useGlobals<ArgTypes extends Args = Args>(): [ArgTypes, (newGlobals: ArgTypes) => void];
```
```ts
// locale-text.stories.tsx
const Template: Story<LocaleTextProps> = (args) => {
  const [{ locale }] = useGlobals<{ locale: LocaleTextProps['locale'] }>();
  return <LocaleText {...args} locale={locale} />;
};
```

That would be a much smaller change to Storybook probably be easier and more flexible for consumers to get strict returns?

**Comment by yannbf** [comment]
Hey @timkinnane I agree that `useGlobals` could take a generic, and very likely should! I think it's good to implement anyway. However, I think `<Pick<LocaleTextProps, 'locale'>>` is too complicated for the end users.

I think the upside of module augmentation is that it's scalable. It might be a bit confusing for some, but it works well in scenarios like the ones I mentioned above (styled-components, material-ui). I think we could scope this PR down indeed, but keep in mind the broad usage of globals from multiple places in Storybook.

**Comment by ndelangen** [comment]
>  I think <Pick<LocaleTextProps, 'locale'>> is too complicated for the end users.
That's a matter of preference, user also have to option of declaring the type separately, if they wish?

**Comment by yannbf** [comment]
> That's a matter of preference, user also have to option of declaring the type separately, if they wish?

I think I interpreted the code in a wrong way. The type is 100% from the user so that could be a simple inline like `<{ locale: 'en' | 'nl' }>`.. Ignore that remark!

**Comment by timkinnane** [comment]
@yannbf as you say, the type could be as simple as you like. I probably should have made a simpler example, but I was just picking off the type I'd defined in `preview.ts` to show how it could be reused with the hook.

So I'll have another attempt, renaming `GlobalTypes` to `ToolbarGlobalTypes` and adding an optional type argument to `useGlobals` to type its returns. Is that a satisfactory short term solution?

@shilman unfortunately `ToolbarGlobalTypes | ViewportGlobalTypes` is *not* semantically equivalent to Record<string, ToolbarGlobalType | ViewportGlobalType>. But what is the purpose of the union that you were thinking? Where is the need to combine the types in one record? Would `globalTypes` exported from `preview.ts` potentially contain toolbar objects, viewport objects and other definitions in future? I'd assumed they be separate exports.

If they'll be combined, then an approach might be to just add other arg types to a single exported `GlobalTypes`, similar to what I committed: `export type GlobalTypes = Record<string, ToolbarArgType | ViewportArgType>`. Then when processing global types Storybook could use type guards to map over them appropriately, as long as they each have at least one unique property.

**Comment by shilman** [comment]
@timkinnane Yes, but I don't think the package structure will lend itself to that. If `addon-toolbars` defines one type and `addon-viewport` defines another type, and arbitrary addons can define their own types, then it only makes sense to combine the types in the user's project based on which addons they are using.

Also, whatever we come up with should be added to an existing example in the repo (in the current repo structure). If we add an example for every feature in storybook, the monorepo is going to blow up.

**Comment by timkinnane** [comment]
Thanks @shilman. Is there a good example of plugins extending or overloading core interfaces in a similar way to what's required here or is global types unique?

**Comment by JesusTheHun** [comment]
I assume this will move forward with https://github.com/ComponentDriven/csf ?
The version `0.0.2-alpha.0` already bring better generics.

**Comment by ndelangen** [comment]
@shilman I'll close this PR, as it seems movement has been made in the CSF package to remedy the problem this PR tries to solve?

Please re-open if not, and there's something to do here still ❤️ 

Sorry about closing the PR @timkinnane 
We really appreciate the time, energy and effort you've put into this PR.

**Comment by yannbf** [comment]
@kasperpeulen shall we discuss about this for the csf package at some point?

**Pull request closed without merging**
