### PR TITLE
fix: avoid including line numbers when copying the code

### PR DESCRIPTION
**Pull request by donotlb**
Issue: #18629

## What I did

Removed the `onCopyCapture` event listener from the container element of `ReactSyntaxHighlighter`. 

## How to test

Start the html-kitchen-sink example, then open the Story addon panel of Button.Primary story, after that, select and copy (ctrl+c) the source code, and finally paste it somewhere.

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @donotlb thank you so much for your contribution!

@ndelangen could you take a quick look at this? Thanks!

**Comment by donotlb** [comment]
I did more tests, and found that react-syntax-highlighter itself has a few problems, the copy-paste behavior is different in different browsers when showLineNumbers is turned on. 

We can visit [here](https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/) and test it with different browsers (remember to tick the “Show line numbers” checkbox)

I found a simple workaround to make the copy-paste behavior more consistent across browsers: use a custom renderer to process `span.linenumber` element in each line of code, and use a pseudo element to display line numbers.

## How to test

1. `yarn start`
2. open the Basics / SyntaxHighlighter / showlinenumbers story
3. test the copy-paste behavior in Chrome/Safari/Firefox

**Review by ndelangen — APPROVED** [review]

**Comment by donotlb** [comment]
Hi @ndelangen, thanks for your review, are there plans to merge this PR ?

**Comment by wangshijun** [comment]
When will this feature be included in the new release? It's really annoying to have line numbers copied.

**Pull request merged**
