### PR TITLE
cli: replaced merge-dirs dependency by fs-extra

### PR DESCRIPTION
**Pull request by debel27**
Issue: #4241

## What I did

I replaced the merge-dirs dependency by fs-extra.
See #4241 for more information

## How to test

- Is this testable with Jest or Chromatic screenshots? **Can't say** (but I guess so)
- Does this need a new example in the kitchen sink apps? **No**
- Does this need an update to the documentation? **No**

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ndelangen** [comment]
Thanks for this, seems like the lockfile has to be updated for the CI to approve,

I can do that too monday, unless you feel like doing it.

Should be as simple as running `yarn` and committing the new `yarn.lock`

**Comment by debel27** [comment]
Hey @ndelangen,

I can surely do it, but the `cli` package didn't have any `yarn.lock` to begin with. Should I generate one from scratch using `yarn` ?

Thanks for adding the required labels, I was unsure to have to proper rights to do so.

**Comment by debel27** [comment]
I upgraded the `yarn.lock` at the root of the project. The dependency change is located in the cli `package.json` though, so I don't think it will make much of a difference.

Sorry, I'm unfamiliar with monorepos.

**Comment by ndelangen** [comment]
@debel27 you nailed it!

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
