### PR TITLE
Add note for need of main package dependecies

### PR DESCRIPTION
**Pull request by mccullochk**
## Issue

If you clone the repository and only run `yarn install` in the `/docs` directory and not in the root (`/`) directory, you get the following error.

`ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/_name_/Documents/personal/projects/storybook/.babelrc" at 0, attempted to resolve relative to "/Users/_name_/Documents/personal/projects/storybook"`

## What I did
Documented the dependency need in hopes of helping future users avoid the `ReferenceError`

### CODE REVIEW

**Comment by ndelangen** [comment]
Thanks @mccullochk !

Maybe we're just missing a few dependencies in the `docs/package.json`. If you add the missing dependencies, does the local docs development work without bootstrapping the core?

I don't think this flow where you need to bootstrap the core in order to develop on the docs is the intention.

**Comment by mccullochk** [comment]
@ndelangen, it actually doesn't look like there is a missing dependency. I added all the core dependencies to the `package.json` in `/docs` but the error still persists. However, when I import the `.babelrc` file from the core it works without error.

**Comment by ndelangen** [comment]
Ah so basicly what we need to do is create a `.babelrc` file in `/docs` ? And that fixes the problem? 👍

**Comment by mccullochk** [comment]
Yes. Sorry if my first solution was misleading. I can change this pull request to include a `.babelrc` in `/docs` if you like?

The `.babelrc` from the core:
```json
{
  "presets": ["env", "stage-0", "react"],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
```

**Comment by Hypnosphi** [comment]
Yeah, that would be great

**Comment by danielduan** [comment]
@Hypnosphi is this still relevant with your upgrade of gatsby?

**Comment by Hypnosphi** [comment]
I didn't touch the Babel stuff, so probably yes

**Comment by danielduan** [comment]
@mccullochk do you still want to take care of this one?

**Review by ndelangen — APPROVED** [review]

**Comment by Hypnosphi** [comment]
@ndelangen are you sure we don’t want to add `docs/.babelrc` instead?

**Review by Hypnosphi — CHANGES_REQUESTED** [review]
See conversation

**Comment by ndelangen** [comment]
Fine either way, thb

What do you prefer?

**Comment by Hypnosphi** [comment]
I'd say we should either include docs into workspaces, or keep it as an isolated package. In the latter case, it should work without bootstrapping everything else

**Comment by ndelangen** [comment]
Ok, my gut feeling would be to keep them isolated, do you agree?

**Comment by Hypnosphi** [comment]
Sure

**Comment by ndelangen** [comment]
@mccullochk Is this something you could do?

We'd like to be able to install & run the docs -WITHOUT- having to bootstrap the core.
It seems we just need to add a `.babelrc` for that in the docs folder.

https://github.com/storybooks/storybook/pull/2203#issuecomment-341235283

👍

**Comment by Hypnosphi** [comment]
Superseded by #2585

**Pull request closed without merging**
