### PR TITLE
6998: fix for the pseudo class ":first-child" is potentially unsafe

### PR DESCRIPTION
**Pull request by yashicon21**
changed ':first-child' to ':first-of-type' in tabs

Issue: #6998

## What I did
changed the pseudo class for tabs from ':first-child' to ':first-of-type'

## How to test
Check to see if any error is present in development console.

### CODE REVIEW

**Comment by shilman** [comment]
Thanks so much for fixing this! Do you mind updating the snapshots?

```
yarn test --core --update
```

**Comment by yasharzolmajdi** [comment]
@shilman sure, they are updated now

**Review by shilman — APPROVED** [review]
LGTM!!! 🙇

**Comment by ndelangen** [comment]
the problem with first-of-type is that if you have

```html
<div>
  <span/>
  <i/>
  <b/>
</div>
```

All 3 inner elements match first-of-type.

first-child only matches the first element.

It's totally different.

Though we can try to make a concerted effort to make them do the same by making sure all element in the container are of the same type:

```html
<div>
  <span/>
  <span/>
  <span/>
</div>
```

this is actually incredibly hard to enforce when things like Fragments, and render-props come into play.

Since we're not using SSR and have no plans to do so, I'd rather be able to turn off this warning tbh.

**Pull request closed without merging**
