### PR TITLE
Addon info prop options

### PR DESCRIPTION
**Pull request by binomialstew**
Issue:

Previously, `maxPropsIntoLine` had no effect on `object` or `array` props, potentially resulting in very long lines in the story source. Now, `maxPropsIntoLine` affects these in the same way as props, including the correct indentation for each key/value.

### CODE REVIEW

**Comment by CLL80** [comment]
Tests/snapshots will pass but were broken with latest merge from master. Due to [this issue](#3427 ).

**Comment by CLL80** [comment]
I'm not sure how to tag the PR as was requested. I don't have permission to add a label.

**Comment by Hypnosphi** [comment]
Can you please add a prop with large object to addon info example in official-storybook

**Comment by CLL80** [comment]
@Hypnosphi, definitely. Good idea.

**Comment by CLL80** [comment]
In looking at this again, I noticed that truncated prop ellipses weren't broken to the next line. The latest push corrects this and adds the test @Hypnosphi suggested.

**Review by Hypnosphi — APPROVED** [review]

**Comment by Hypnosphi** [comment]
Released as [`3.4.5`](https://github.com/storybooks/storybook/releases/tag/v3.4.5)

**Pull request merged**
