### PR TITLE
Replace setGlobalConfig with setProjectAnnotations

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Apply review comments to #17282

## How to test

N/A

### CODE REVIEW

**Comment by shilman** [comment]
@yannbf a bunch of TS errors when you run `yarn build-storybook` in `cra-ts-essentials`. can you please fix them so we can merge?

**Comment by yannbf** [comment]
> @yannbf a bunch of TS errors when you run `yarn build-storybook` in `cra-ts-essentials`. can you please fix them so we can merge?

pushed!

**Comment by shilman** [comment]
@yannbf still failing

```
ERR! /tmp/storybook/examples/cra-ts-essentials/src/stories/1-Button.stories.tsx
ERR! TypeScript error in /tmp/storybook/examples/cra-ts-essentials/src/stories/1-Button.stories.tsx(13,6):
ERR! Property 'args' does not exist on type '(args: any) => Element'.  TS2339
ERR! 
ERR!     11 | 
ERR!     12 | export const Text = Template.bind({});
ERR!   > 13 | Text.args = {
ERR!        |      ^
ERR!     14 |   children: 'Hello button',
ERR!     15 | };
ERR!     16 | 
```

**Comment by yannbf** [comment]
> @yannbf still failing
> 
> ```
> ERR! /tmp/storybook/examples/cra-ts-essentials/src/stories/1-Button.stories.tsx
> ERR! TypeScript error in /tmp/storybook/examples/cra-ts-essentials/src/stories/1-Button.stories.tsx(13,6):
> ERR! Property 'args' does not exist on type '(args: any) => Element'.  TS2339
> ERR! 
> ERR!     11 | 
> ERR!     12 | export const Text = Template.bind({});
> ERR!   > 13 | Text.args = {
> ERR!        |      ^
> ERR!     14 |   children: 'Hello button',
> ERR!     15 | };
> ERR!     16 | 
> ```

sorry about that! pushed

**Pull request merged**
