### PR TITLE
Build: Move Preact E2E tests on a Node 12 executor

### PR DESCRIPTION
**Pull request by gaetanmaisse**
## What I did

E2E tests are broken for a few weeks because Preact CLI isn't working on Node 10 anymore although it officially supports it.
I opened a PR to fix that: https://github.com/preactjs/preact-cli/pull/1493. However, even if it fixes a breaking change there was no release since so we are still stuck on our side. 

Plus, the opinion on Node 10 support isn't very clear, see https://github.com/preactjs/preact-cli#requirements and then https://github.com/preactjs/preact-cli/pull/1493#issuecomment-744227337.

So I decided to work around this issue by creating an E2E job that runs with Node 12 and plays Preact tests in it. Keeping all the other ones on Node 10 executor.

To do so, I added a `--skip <framework>` option in the script used to run the e2e tests and updated the CircleCI workflow. I also cleaned some E2E related things on my way. 

---

Also, I had to fix a bug in the CJS/ESM build of `@storybook/cli`: the generated directories were cleaned just after been created so the package was missing some files for Angular and Aurelia.

## How to test

- CI should be 🟢, especially the new node-12 job

### CODE REVIEW

**Comment by gaetanmaisse** [comment]
Arf, Angular tests are now failing, I will 🔍  later today

**Review by ThibaudAV — APPROVED** [review]
Maybe not be the best reviewer for this, but LGTM 🚀

**Comment by gaetanmaisse** [comment]
🙇🏻  @ThibaudAV, don't worry @shilman will do a post-merge review too ;)

**Comment by gaetanmaisse** [comment]
Self merging to make `next` back to 🟢  and unlock other PR

**Pull request merged**
