### PR TITLE
Addon-docs: Rename Preview/Props to Canvas/ArgsTable

### PR DESCRIPTION
**Pull request by shilman**
Issue: #11696 

## What I did

- [x] Renamed blocks
- [x] Added deprecations
- [x] Update MDX compiler
- [x] Update documentation
- [x] Added migration instructions

## How to test

Let's see what CI says

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
Looks good but can't we keep the old export and make this non-breaking?

**Comment by shilman** [comment]
We do. Technically this isn't breaking.

**Comment by sunguru98** [comment]
Hey there, I just went over the change log for Storybook v6 (especially https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#previewprops-renamed), and this PR related change was mentioned there as breaking. 

Just to be clear whether <Preview> would be deprecated in future releases, or <Canvas> is just for convenience?

Thanks in advance.

**Comment by shilman** [comment]
> Just to be clear whether would be deprecated in future releases, or is just for convenience?

This PR already deprecates the old names. They will be removed in 7.0.

**Pull request merged**
