### PR TITLE
Addon-docs: Add Props for Ember

### PR DESCRIPTION
**Pull request by meirish**
Issue #8646

## What I did
Added support for ember for addon-docs. This requires https://github.com/storybookjs/ember-cli-storybook/pull/24 on the ember-cli side of things. That PR describes the approach to generate a document JSON file which is used to construct props tables here.

This doesn't yet include support for inline story rendering. 

Screen Shot 2019-12-04 at 9 32 08 PM

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps? yes
- Does this need an update to the documentation? yes

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
GREAT WORK! 👏👏👏 

Will merge/release after the other PR is merged & released.

It looks like that will be required (and perhaps the version updated?!) to fix the broken build.

**Comment by meirish** [comment]
Thanks! Any hints about how to get the chromatic build green? Looks like it can't find a build output directory. All of the puppeteer failures look to be contrast failures on the axe tests too - not sure why those would be different with the changes here.

**Comment by shilman** [comment]
@meirish don't worry about the a11y tests. i think somebody's still trying to get those working (cc @ndelangen @Hypnosphi)

**Comment by Hypnosphi** [comment]
@shilman current failures are correct and related to #8935

**Pull request merged**
