### PR TITLE
Angular: Update Angular cli templates

### LINKED ISSUE #22453: [Bug]: Storybook Angular sample components are not marked standalone?
### Describe the bug

I think the markup for the annotation in the Angular components is meant to include `standalone:true` like this:

```
@Component({
  standalone:true,
  selector: 'storybook-button',
  imports: [CommonModule],
  template: ` <button
    type="button"
    (click)="onClick.emit($event)"
    [ngClass]="classes"
    [ngStyle]="{ 'background-color': backgroundColor }"
  >
    {{ label }}
  </button>`,
  styleUrls: ['./button.css'],
})

```

This resolves some linting errors when the project is openend.

Also for the button demo the `primary` input is documented as:

```
  /**
   * Is this the principal call to action on the page?
   */
  @Input()
  primary = false;

```

And I think the intention is to have something like:

```
  /**
   * Is this a primary button.
   */
  @Input()
  primary = false;

```

Also the `primary` property on the button is set like this in the heading story (It's actually set twice):

``` 
primary
...
primary="true"
```
Which creates the linting error:

```
Type 'string' is not assignable to type 'boolean'.ngtsc(2322)
```

[It should proxy with a `setter as described in this article.](https://fireflysemantics.medium.com/converting-angular-inputs-to-boolean-values-10fd4bdbaba2)

Alternatively the `primary` property could just have type `any` and that resolves the linting errors ...

The heading component should be declared like this (Currently missing `standalone` and `imports`:

```
@Component({
  standalone: true,
  imports: [ButtonComponent, CommonModule],
  selector: 'storybook-header',
  template: `<header>
```

And the `User` type is missing the `name` property, and this also creates linting errors.  It should be declared like this:

```
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface User {
    name:string,
}

```

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Marklb**
Closes #22453

## What I did

Fixed a few issues with the initial stories in an Angular project.

I left a mix of standalone and non-standalone, since Angular supports both, but I can change them to all standalone if we want.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Create a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template angular-cli/default-ts`
2. Open Storybook in your browser
3. Access Example stories

The code was incorrect, but because of how Storybook generates the NgModule they happened to still work in a story. So, you can access the stories to make sure I didn't break them, but this is mainly just a correction of the code.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by Marklb** [comment]
@valentinpalkovic I didn't notice that PR, when I decided to make this one, but sure I can add those changes. The parts I don't have are that yours set each component as standalone. Is that what we want? It is ideally what should be done, but do we want the examples to be ideal or a mix of what is supported?

**Comment by Marklb** [comment]
I made the changes and removed a few other things that didn't seem necessary.

Should the stories file names be changed to lowercase? I assume the uppercase is from matching the React files, but I don't think Angular apps typically have files with an uppercase name.

**Comment by valentinpalkovic** [comment]
Sure! :)

**Comment by Marklb** [comment]
Updated the filenames. I also removed the default exports, since I don't think I have actually seen an Angular project doing that, but I can change that back if not wanted.

**Review by valentinpalkovic — APPROVED** [review]

**Comment by shilman** [comment]
Should this be patched back to 7.6 @valentinpalkovic @Marklb ?

**Comment by valentinpalkovic** [comment]
Yes lets do it.

**Pull request merged**
