### PR TITLE
docs: Show Code Open by default

### PR DESCRIPTION
**Pull request by kschoi**
Issue: #10430 

## What I did
I added 'previewSource' parameter.

## How to test

API is following
```javascript
addParameters({ docs: { previewSource: 'open' } })
```

### CODE REVIEW

**Comment by ndelangen** [comment]
@shilman what do you think? Do we want to add this?

**Comment by shilman** [comment]
@ndelangen I think it's a good feature but I want to think a little about how to make the story parameters and doc blocks props line up and I haven't had a chance to work it out.

@kschoi sorry for the slow response on this... really appreciate your contribution & patience!

**Comment by shilman** [comment]
Hi @kschoi! Thanks so much for making this PR. I merged https://github.com/storybookjs/storybook/pull/14729 which implements the same feature, so I'm going to close this.

**Comment by dutscher** [comment]
@shilman where is this documented?
thanks for the implementation!

cheers

**Pull request closed without merging**
