### PR TITLE
Disable eslint rules for click-events-have-key-events

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://www.codefactor.io/repository/github/storybooks/storybook/file/master/addons/info/src/components/Story.js

## What I did
configure eslint to allow onClick handles without a keyboard handler.

### CODE REVIEW

**Comment by ndelangen** [comment]
I'm trying to take the number of issues on CodeFactor down a bit, This PR is related to a support ticket, please do not merge just yet.

**Comment by Hypnosphi** [comment]
Should we rather add the listeners maybe? We could introduse a helper component in `@storybook/components`

**Comment by ndelangen** [comment]
Doesn't react call onClick when a users focusses an element and presses `ENTER`? Browsers do...

I just don't understand why this rule exists in the first place.

**Comment by Hypnosphi** [comment]
> Doesn't react call onClick when a users focusses an element and presses ENTER?

That's the default browser behavior for buttons but not for anything else

**Comment by Hypnosphi** [comment]
I switched this rule to warning level in #2212 so that we can fix it later

**Pull request closed without merging**
