### PR TITLE
Storyshots: Fix support for test failures in async tests

### PR DESCRIPTION
**Pull request by kahirokunn**
## What I did
some times I wanna reject test like this.
https://github.com/facebook/jest/issues/6121#issuecomment-386296997

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Sorry for the slow turnaround on this. Shouldn't this be done with the `done(error)` API instead?

https://jestjs.io/docs/en/asynchronous#callbacks

**Comment by kahirokunn** [comment]
Yeah, I wanna write code like it.
So, I tried this code but I got success all test in storyshots. 😢 

```javascript
import initStoryshots from '@storybook/addon-storyshots'
import path from 'path'

initStoryshots({
  asyncJest: true,
  test: async ({ done }) => {
    try {
      expect(1).toEqual(2)
      done()
    } catch (error) {
      done(error)
    }
  },
})
```

**Comment by kahirokunn** [comment]
Is there any `done(error)` test code?

**Comment by shilman** [comment]
@kahirokunn i see. then WDYT about something more like:

```js
        new Promise((done, reject) =>
          testMethod({
            done: (err) => (err ? reject(err) : done())
            ...
```

**Comment by kahirokunn** [comment]
@shilman I tried it and that worked for me.

**Review by shilman — APPROVED** [review]
💯

**Comment by kahirokunn** [comment]
@shilman 
Thanks for the quick reply!

One more thing.
I want to do this kind of thing with storyshots-puppeteer too, can I remove this assertion `expect.assertions(1);`? (I feel like these assertions should be in the test code and not in the runtime code.

https://github.com/kahirokunn/storybook/blob/e48ad84e1b1f9872a5e0c31e35583341aa37d684/addons/storyshots/storyshots-puppeteer/src/imageSnapshot.ts#L14

**Comment by shilman** [comment]
@kahirokunn i don't have enough context on that to respond. maybe a separate PR and we can figure that out?

**Comment by kahirokunn** [comment]
Thanks a lot.
I tried like it.
https://github.com/storybookjs/storybook/pull/12657

**Comment by kahirokunn** [comment]
Why CI is failed? 🤔 
Is there anything I can do to?

**Comment by shilman** [comment]
@kahirokunn ignore it! 😁

**Pull request merged**
