### PR TITLE
Added meta IE=edge

### PR DESCRIPTION
**Pull request by nutgaard**
IE is sometimes configured to fall back to IE7-emulation on internal sites. 

This forces IE to use its latest version on this site.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@nutgaard would you be OK if this https://github.com/storybooks/react-storybook/pull/723 was added (see issue here: https://github.com/storybooks/react-storybook/issues/650). This would allow you to add `X-UA-Compatibility` response header, the see: https://msdn.microsoft.com/en-us/library/ff955275(v=vs.85).aspx

**Comment by nutgaard** [comment]
@ndelangen I'm not that familiar with webpackDevMiddleware, so I'm not sure. 
If #723 also affects the `index.html` when running `build-storybook` (e.g generating the static site) then I see no problems with that solution.

**Comment by ndelangen** [comment]
I'll give that a try myself. If it doesn't work, I'll merge this. Thank you!

**Comment by nutgaard** [comment]
Found an alternative way of solving this, if the current solution seems a bit specific. 

Currently storybook support adding elements to `<head>` in the iframe by creating a `head.html` file inside the `.storybook` folder (like the good people at [airbnb](https://github.com/airbnb/react-dates/blob/master/.storybook/head.html) have done). The contents are then merged into `iframe.html.js`.

 I've just verified that this works as expected when running `build-storybook`.

So another option to this PR is to expose a similar head-file that can be injected into `index.html.js` giving us a bit more flexibility further down the line.

**Comment by ndelangen** [comment]
Thank you @nutgaard !, 

I'll just merge this, but may add a issue later that we should move this behaviour into a header, and the consumer should set such header using server-middleware.

**Pull request merged**
