### PR TITLE
Core: Fix config.base relative paths

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/20138

## What I did

I changed the path to begin with `./`

### CODE REVIEW

**Review by IanVS — COMMENTED** [review]
Does this need to be changed in `index.ts` as well?

```ts
router.use(`/sb-preview`, express.static(previewDirOrigin, { immutable: true, maxAge: '5m' }));
```

**Comment by ndelangen** [comment]
no, that would have no effect @IanVS

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by Terrel007** [comment]
@shilman @ndelangen  I found this commit is missing for the next branch. 
When I try to run "storybook-build" in my project, the "sb-preview/runtime.js" returns 404. 
After I patched the "@storybook/builder-vite" package with these changes for my project, and it works fine. So do we still need this commit for the version 7.6.4 or 8.x alpha?

**Pull request merged**
