### PR TITLE
UI: Add a parent level toolbar exclusion key for tabs

### PR DESCRIPTION
**Pull request by JonathanKolnik**
Issue:
Sometimes you might want to exclude tabs altogether but you can't know the specific addon keys that could populate the tabs section of the toolbar ahead of time.

## What I did
Added a parent level toolbar exclusion key `storybook/tabs` that follows the same API as the rest of the toolbar exclusions but filters out all tabs in the toolbar section.

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
What about `*` which is a bit more idiomatic?

Also, does this need to be documented somewhere?

**Comment by JonathanKolnik** [comment]
@shilman do you mean something like `tabs/*` ?

**Comment by shilman** [comment]
@JonathanKolnik Discussed with the triage team. Initial consensus is that this is a weird API. How about `showTabs=false` instead to make it more consistent with the other APIs? And if we provide this do we still need the `toolbarExclude` parameter? If not, can we remove it?

**Review by shilman — CHANGES_REQUESTED** [review]
@JonathanKolnik small nit, but it looks like the new story looks just like the default story, i.e. there are no tabs to hide so it doesn't really test the feature.

**Comment by JonathanKolnik** [comment]
🤦‍♂️ updated @shilman thank you!

**Review by shilman — APPROVED** [review]
LGTM! Thanks for fixing up the test case @JonathanKolnik  -- looking great

**Pull request merged**
