### PR TITLE
UI: Add toolbar "text" input type

### PR DESCRIPTION
**Pull request by razor-x**
Closes #18738

## What I did

Implemented a new toolbar type: text input. Works like this

```
userName: {
  name: 'User name',
  description: 'What is your name?',
  toolbar: {
    title: 'Name',
    icon: 'user',
    isSecret: false,
  },
},
```

image

https://user-images.githubusercontent.com/721372/230291847-43988b19-69f5-4b61-bcaf-d2c7a40edd99.mp4

## How to test

1. yarn start
2. Open Storybook in your browser
3. Access story: http://localhost:6006/?path=/story/addons-toolbars-globals--basic
4. Type text into input box, watch greeting change.
5. Edit `template/stories/preview.ts` and update the `userName` value.
6. Refresh the page to see change.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by razor-x** [comment]
I could use some help checking if the `defaultValue` is working. Having a hard time testing that.

**Comment by razor-x** [comment]
@GeorgeWL If you are still looking for the feature, let me know if you want to help get this merged!

**Comment by razor-x** [comment]
- Sorted out the type errors: build is green now!
- Verified default value works as expected.
- Password box only triggers save password on firefox, not chrome. I think it's ok to leave it as-is, since users can just click "never save" and it will go away.

Let me know if I can do anything else to get this merged.

**Comment by MichaelArestad** [comment]
Howdy @razor-x! Thank you for the contribution. We took a look at this earlier today and I think this requires a bit more design thinking. I'm not sure a text input in the toolbar is the best solution for this particular issue. @cdedreuille and I have been ideating a bit on the Storybook interface and might have some ideas on a better way to do this.

@JReinhold, @jonniebigodes mentioned you might also have some ideas on how to handle something like this without a text input in the toolbar. Do you have any thoughts?

**Comment by razor-x** [comment]
I agree that the text input up there is a bit awkward, but the toolbar is the only place (that I could find) where it made sense to put this global state. Anyway I'm happy that this PR can get the ball rolling on a solution.

What if the input was hidden and only appeared when you press the icon / text?

Otherwise, I'm excited to hear some alternative ideas.

**Comment by JReinhold** [comment]
I'm sorry @MichaelArestad but I don't recall anything like that.

Even before I read @razor-x's suggestion, I would also think that the text input would be more suitable inside a dropdown that opens when you click a button in the toolbar.

**Comment by jonniebigodes** [comment]
@JReinhold and @razor-x, so that we're clear, what was discussed during the triage meeting was for @razor-x to elaborate a bit more and hopefully come up with a good RFC mentioning this pull request and the attached issue it solves so that we can discuss it more and come up with a more suitable solution. Hopefully, when #21835 is merged, you have the tools at your disposal to get it out. 

Will that work for you?

**Comment by razor-x** [comment]
@jonniebigodes Sounds good. I do believe the input as a drop down is closer to the right thing, but I am happy to go through the new RFC process. It looks like the RFC PR is ready to merge, anything still blocking that?

**Comment by jonniebigodes** [comment]
@razor-x the RFC was merged just now, and you should be able to go through it when you're able. Looking forward to reading your RFC.

**Comment by ndelangen** [comment]
@cdedreuille could you have a look at this PR, from a designer's point of view.

I personally am not a fan of rendering the textbox in the toolbar..

**Comment by GeorgeWL** [comment]
honestly the one use case I originally came up with is to set a global value, say a value coming from a react context that we're mocking in storybook

But if you can think of a better method I'm all for it

**Comment by razor-x** [comment]
My original use case for opening this PR ended up going in a different direction, so it's unlikely I will be able dedicate time to see this one though now. However, anyone is welcome to pick up where I left off on this branch.

**Pull request closed without merging**
