### PR TITLE
Builder-Vite: use user's build.target

### LINKED ISSUE #22223: [Bug]: Overwriting "build" object in vite config in build mode prevents use of top-level await
### Describe the bug

I have the need to use a toplevel await in 2 places. The current way to support this with vite and prevent the following error is to add:

```json
build: {
    target: 'esnext'
}
```

to the config. However the code of storybook deletes this on builds.

The error you get in vite with top-level awaits is:

```
✓ 2358 modules transformed.
rendering chunks (49)...[vite:esbuild-transpile] Transform failed with 1 error:
assets/preview-!~{00m}~.js:143144:18: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
143142|      ...middlewares
143143|    ],
143144|    preloadedState: await getInitialState()
   |                    ^
143145|  });
143146|  sagaMiddleware.run(rootSaga);
```

For reference: https://github.com/vitejs/vite/issues/6985

### To Reproduce

Any storybook is fine as long you got a top-level await anywhere in the code and use vitejs to build it.

### System

```shell
Environment Info:

  System:
    OS: Linux 6.2 Fedora Linux 37 (Container Image)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-a11y: ^7.0.6 => 7.0.6 
    @storybook/addon-essentials: ^7.0.6 => 7.0.6 
    @storybook/addon-interactions: ^7.0.6 => 7.0.6 
    @storybook/addon-links: ^7.0.6 => 7.0.6 
    @storybook/addon-styling: ^1.0.1 => 1.0.1 
    @storybook/blocks: ^7.0.6 => 7.0.6 
    @storybook/builder-vite: ^7.0.6 => 7.0.6 
    @storybook/react: ^7.0.6 => 7.0.6 
    @storybook/react-vite: ^7.0.6 => 7.0.6 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

### Additional context

The code causing the issue are these lines https://github.com/storybookjs/storybook/blob/7b2e1a707f1a76e5bc0713d62debe74ef0d2b80c/code/lib/builder-vite/src/build.ts#L13-L17 which replaces the user-set values for `build`

### PR DESCRIPTION
**Pull request by Hoishin**
Closes #22223

## What I did

If user has `build.target` in Vite config, use it for Storybook's Vite config.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
Hi @Hoishin,

Thank you very much for this PR.

I don't feel very confident about merging this PR. This change could potentially cause the application to stop working. Therefore, since this is a potential breaking change, I would like to merge this PR for SB 8.0 after internal consultation.

Until then, the already mentioned workaround can be used:

```tsx
async viteFinal(config) {
    return mergeConfig(config, {
      build: {
        target: 'esnext'
      },
    });
  },
  ```
  
I hope you understand our worries.

**Comment by IanVS** [comment]
>This change could potentially cause the application to stop working.

@valentinpalkovic do you mean to say that storybook cannot be built with that target?  Or when you say "cause the application to stop working", do you somehow mean the user's application itself?

I do agree that this is likely best left to 8.0, just curious if there are specific concerns about storybook being incompatible with different targets other than the default.

**Comment by valentinpalkovic** [comment]
@IanVS As far as I remember, we discussed this internally. We concluded that merging this PR could potentially break Storybook since the target might differ from the default one, and unexpected behavior might pop up. This is a precaution rather than basing the decision on some incidents in the past.

**Comment by IanVS** [comment]
>since the target might differ from the default one

This makes sense, but on the other hand if Storybook is using a target that is different from the one specified in the user's vite config, I could also see that as being a bug, since their SB won't match their application.  Personally I think it wouldn't be bad to release it before 8.0, but don't feel strongly one way or the other, especially since there's a pretty straightforward workaround.

**Pull request merged**
