### PR TITLE
Addon-docs: Include Vue methods in ArgsTable

### PR DESCRIPTION
**Pull request by ndelangen**
Replaces See https://github.com/storybookjs/storybook/pull/13127
Because the contributor deleted their repository, I cannot get it updated with changes from next

Issue: Methods not shown use ArgsTable with vue framework( https://github.com/storybookjs/storybook/issues/13105)

## add SECTION Methods

test in node_modules: change file content as same as in PR（node_modules\@storybook\addon-docs\dist\frameworks\vue\extractArgTypes.js），and it worked in my project

@hmleo

### CODE REVIEW

**Comment by ndelangen** [comment]
@storybookjs/vue Could anyone help me out verify this? And perhaps add a testcase / story demonstrating the feature?

**Comment by pocka** [comment]
@ndelangen Is this PR #16975 but for Vue3? It seems that PR fixed the original issue (for Vue2).

**Comment by ndelangen** [comment]
I honestly do not know @pocka that sounds about right. I was trying to bring a list of PRs to a close because having 120+ PRs doesn't reflect well on the project and is just rude to the people giving up their time making these PRs.

Any help you could offer to understand the issues this pr is solving would be appreciated

**Comment by ndelangen** [comment]
Yes, @pocka you're 100% correct! Thank you for pointing that out.

**Pull request merged**
