### PR TITLE
examples: improve HTML framework's generated typescript stories

### PR DESCRIPTION
**Pull request by Matthew-Smith**
Issue:

## What I did

The example stories for the typescript version of the `HTML Framework` had some issues that caused typescript to complain. This improves that and also adds a section to the `HTML Framework` readme to explain how to get the typescript versions of the examples when starting from a new project. 

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
Hey @Matthew-Smith thanks a lot! This is amazing 🚀🚀

**Comment by Matthew-Smith** [comment]
@yannbf is there a reason this PR was closed? I'm happy to fix it up if there are any changes needed

**Comment by yannbf** [comment]
Great question @Matthew-Smith , this should not have been closed, but merged instead. I'm on holidays so I can't do much but @ndelangen could you please take a look? Thank you!!

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@Matthew-Smith It closed because you deleted the fork:
https://github.com/Matthew-Smith/storybook/tree/fix-html-ts-template-stories

**Comment by ndelangen** [comment]
I need to update this branch with `next` so I'll close this PR, and open a new one..

**Comment by Matthew-Smith** [comment]
I see now! Sorry about the confusion!

**Pull request closed without merging**
