### PR TITLE
Fix: resolve errors of yarn test

### PR DESCRIPTION
**Pull request by g1eny0ung**
Issue:

Due to the CI failed a long time, I try to repair these failures.

## What I did

1. Fix the regular tests `ci/circleci: test`

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by g1eny0ung** [comment]
I'm trying to figure out the Danger JS failed problem. I found an issue that describes the same problem that occurred in storybook GitHub actions: https://github.com/danger/danger-js/issues/1031.

Seems the failed reason is now the `GITHUB_TOKEN` isn't be permitted to create a comment in PR and we should be using a custom token. @shilman PTAL. Sorry for always bothering u because I don’t know who else I can ask to review 🤣.

ref: https://github.com/storybookjs/storybook/pull/13010/checks?check_run_id=1352707924

**Comment by shilman** [comment]
@g1eny0ung don't worry about it. it fails for all forked repos. sorry for the inconvenience!

**Comment by g1eny0ung** [comment]
> @g1eny0ung don't worry about it. it fails for all forked repos. sorry for the inconvenience!

Got it.~ And the changes in this PR fixed errors generated by the `yarn test`.

**Comment by gaetanmaisse** [comment]
Thanks for the effort @g1eny0ung! I will close this PR as it is quite outdated now and the CI is back to 🟢 . Feels free to update the branch and reopen the PR if you think it's needed.

**Pull request closed without merging**
