### PR TITLE
[RFC] addon-knobs options

### PR DESCRIPTION
**Pull request by astrotim**
*Request for comments* proposed approach to creating a new `options` knob which combines the similar knobs under the hood.

Issue: see https://github.com/storybooks/storybook/issues/3972#issuecomment-411343776

## What I did

Added `optionsKnob` knob (was getting lint errors due to `options` variable already existing in namespace) which composes `SelectType`, `RadiosType` and `BooleanType` under the hood.

## Not yet done

Make it work with multiple select and multiple checkboxes.

## How to test

No tests yet. Just looking for feedback on the approach.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by ndelangen** [comment]
@astrotim You have a pending invite to join the storybook org on github

That will allow you to make branches on this origin.
Those are easier to review and collab on.

**Comment by ndelangen** [comment]
Welcome back! 👏

**Comment by astrotim** [comment]
@ndelangen I haven't seen the pending invite anywhere... I assume it should appear in my Github profile - at least on [this page](https://github.com/settings/organizations) - but nothin' 😥 

Resend perhaps?

**Comment by ndelangen** [comment]
try here:
https://github.com/storybooks

**Comment by astrotim** [comment]
Oh there it is... thanks, I'm in!

**Comment by astrotim** [comment]
FYI, I have created a [new branch from the storybook repo here](https://github.com/storybooks/storybook/tree/issue-3972-options-knob) with my continued progress.

Shall I close off this PR and spin up a new PR for that branch?

Also, re:

> We'd need a demo of this in the official storybook

In which part of the codebase should I implement this?

**Comment by astrotim** [comment]
Superseded by https://github.com/storybooks/storybook/pull/4723

**Pull request closed without merging**
