### PR TITLE
Allow build-package to build @storybook/angular in watch mode

### PR DESCRIPTION
**Pull request by Marklb**
## What I did

Added a hack to allow `yarn build angular --watch` to work. When building angular, `compile-babel.js` doesn't execute a command and ends. Since `concurrently --kill-others` is used, `compile-tsc.js` gets killed.

It may be better to decide a better way to handle this, such as not even running `compile-babel.js` or not killing the other script if one ends for any reason. This is the ugly way I am currently handling the problem for myself.

## How to test

Run `yarn build angular --watch` without the script getting killed in a few seconds from `compile-babel.js` ending.

### CODE REVIEW

**Comment by Marklb** [comment]
I can try some better ways of doing this later, or open an issue if it would be better to discuss there. I just did a PR only, because it is a small build script change.

**Comment by shilman** [comment]
@yannbf can you take this one?

**Comment by Marklb** [comment]
I changed this PR to only call `compile-tsc.js` if `angular` is the only package build built in watch mode.

I realized build script works, without this PR, if multiple packages are in watch mode at once (ex. `yarn build angular core --watch`), so this PR would only affect building angular only in watch mode (ex. `yarn build angular --watch`).

I don't know much about lerna, but I assume it doesn't break, without this PR, when multiple packages are built is because multiple packages are compiling per `compile-` script.

**Comment by yannbf** [comment]
Hey @Marklb sorry for the delayed response! I'm glad you found a way to unblock your progress, but I analysed the script reached a conclusion:

@ndelangen when executing both watch-tsc and watch-babel, if watch-babel fails it should be ok, right? there's no impact in this as far as I can see, and the commands would only fail in case they are not applicable to the projects being built, right?

Example:
When running build on watch mode for rax, `watch-tsc` is unnecessary, but it will just exit in case it's not applicable.

If we remove `--kill-others` from the command, all packages will be built without breaking. At least I tested in every single framework package and it worked fine.

**Comment by Marklb** [comment]
I reverted this back to the original with `--kill-others` removed, like your suggestion @yannbf.

The reason I didn't go with this solution originally was to avoid potentially leaving processes alive unexpectedly, like what happened to me when using `yarn dev`, but it looks like it also uses '--kill-others', so I don't think it was the cause of that. What happened to me when I got an error using `yarn dev` was that the process died and left 2-3 detached processes running the background for every package it had started building.

**Comment by yannbf** [comment]
Interesting. So you managed to run without --kill-others and the behavior was not the same? Could you verify if there are possible dangling processes when running the command without that flag?

**Comment by Marklb** [comment]
No, it's fine without `--kill-others` from what I can see. I was just mentioned that problem, because it is the reason I was hesitant to remove it at first. After noticing that `yarn dev` also uses `--kill-others`, I am more confident that it wasn't what caused that problem, so removing `--kill-others` shouldn't cause that problem.

I have been unable to reproduce that dangling processes problem, but I also never attempted `yarn dev` again after it happened. It may have been Windows killing the root process that does the cleanup for some reason, since I normally have multiple other projects building in watch mode also, which causes `yarn dev` to struggle anyway.

**Comment by Marklb** [comment]
Should this be merged? I haven't needed this, since I learned that running at least one other package will keep the process from getting killed, but there is nothing documenting that.

**Comment by yannbf** [comment]
> Hey @Marklb sorry for the delayed response! I'm glad you found a way to unblock your progress, but I analysed the script reached a conclusion:
> 
> @ndelangen when executing both watch-tsc and watch-babel, if watch-babel fails it should be ok, right? there's no impact in this as far as I can see, and the commands would only fail in case they are not applicable to the projects being built, right?
> 
> Example:
> When running build on watch mode for rax, `watch-tsc` is unnecessary, but it will just exit in case it's not applicable.
> 
> If we remove `--kill-others` from the command, all packages will be built without breaking. At least I tested in every single framework package and it worked fine.

@ndelangen could you check this comment when you have the time? thanks!

**Comment by yannbf** [comment]
I'm closing this issue as it's been fixed in #13822. Thanks for your contribution nonetheless!

**Pull request closed without merging**
