### PR TITLE
Controls: Add id to setter button for undefined values

### PR DESCRIPTION
**Pull request by revik**
Issue: https://github.com/storybookjs/storybook/issues/15690

## What I did
added getControlSetterButtonId function to calculate id of setter button for undefined control values

## How to test
added a test for the getControlSetterButtonId function

- Is this testable with Jest or Chromatic screenshots? yes
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? no

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Thanks @revik! This is looking pretty good. However, I noticed the following controls are missing: `Color`, `Date`, `Files`, `Options`, `Range`, `Checkbox`, `Radio`, `Select`. If we're adding test IDs to some of the controls we should add to all. WDYT?

**Comment by revik** [comment]
> Thanks @revik! This is looking pretty good. However, I noticed the following controls are missing: `Color`, `Date`, `Files`, `Options`, `Range`, `Checkbox`, `Radio`, `Select`. If we're adding test IDs to some of the controls we should add to all. WDYT?

@shilman those controls do not display the 'Set' button when no value is sent to them. They all display the control without a specific set value. IMHO - aligning all controls to have the 'Set' button when there is not value set IS the best choice..
Do you want me to try and add it to all of the above controls?

Should this added change be in this PR or in a different one?

**Comment by shilman** [comment]
Aha, my bad @revik -- I totally missed that. I agree that we should have a unified UI for unset values. I know @tmeasday and @domyen didn't agree before, but I think everybody agrees now. It would be great if you could also fix that in this PR! 🙏

**Comment by shilman** [comment]
Hi @revik I'm going to merge this in the interest of moving things forward. If you still have any interest, could you please pick up the other changes in a new PR?

**Review by shilman — APPROVED** [review]

**Comment by shilman** [comment]
Merging despite failing tests. Those tests are already failing on `next`

**Pull request merged**
