### PR TITLE
Vite: Automatically use vite.config.js

### PR DESCRIPTION
**Pull request by IanVS**
Issue:

## What I did

This is an exploration into two things:

1) Use a `vite.config.js` (or similar) vite config file as the basis for the storybook vite builder, while still allowing `viteFinal` as an override if necessary.  This makes it much easier to get up-and-running with storybook in a vite project, and would also solve https://github.com/storybookjs/builder-vite/issues/286, a particularly nasty issue, because we could just use the babel config that the user set in their normal vite config.
2) Step 1 above only works if we don't need a special version of the react/svelte/vue plugins, which up to now we have.  We needed to exclude `.stories.x` files from HMR, because it conflicted with Webpack's HMR.  This approach removes those exclusions, and allows HMR to happen in stories files.

Item 2) caused a bit of problems, because vite incorrectly adds HMR boundaries to story files that it shouldn't (https://github.com/vitejs/vite/issues/9869).  Until/unless that issue is fixed, the approach taken here is to add one more `post` plugin, which looks at only `.stories` files, and removes `import.meta.hot.accept();` if it finds it, which allows the change to bubble up and be handled correctly.

## How to test

Run `yarn sandbox`, pick one of the vite frameworks, and answer the questions that it asks.  You should then be able to go into `/sandbox` and start up storybook.  Try configuring vite with `vite.config.js`, and verify that your changes appear in the vite config by logging it out in `viteFinal`.  Verify that modifying the config in `viteFinal` still impacts the final build.

### CODE REVIEW

**Comment by IanVS** [comment]
This is working correctly for react, and for svelte projects that do not use svelte-native stories.

I cannot yet get svelte-native stories working in 7.0, I'm not sure if it's supported yet or not.  Once that's working, we may need to remove `import.meta.hot.accept()` from those files too, but I'm holding off on that for now.

That said, this PR is ready for review.

**Comment by IanVS** [comment]
I see that Historie has a way to easily filter out unwanted plugins by name (https://histoire.dev/guide/config.html#ignoring-plugins), maybe that's something we could explore too.  Not sure where that would go in the config file though.  Maybe `core.builder.options.ignoredVitePlugins`?

**Review by joshwooding — APPROVED** [review]
LGTM

**Review by shilman — APPROVED** [review]
Without deep knowledge of all the decisions here, this LGTM

**Pull request merged**
