### PR TITLE
Vite: Fix missing @storybook/global dependency

### LINKED ISSUE #22695: [Bug]: PNPM/Vite Failed to resolve import "@storybook/global"
### Describe the bug

after updating to v7.0.14 I got this error message:

```bash
10:43:44 AM [vite] Internal server error: Failed to resolve import "@storybook/global" from "../../../../../virtual:/@storybook/builder-vite/setup-addons.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/setup-addons.js:1:25
  1  |  import { global } from '@storybook/global';
     |                          ^
  2  |      const { createChannel: createPostMessageChannel } = __STORYBOOK_MODULE_CHANNEL_POSTMESSAGE__;
  3  |      const { createChannel: createWebSocketChannel } = __STORYBOOK_MODULE_CHANNEL_WEBSOCKET__;
      at formatError (file:///Users/omarkhatib/Documents/GitHub/fusion-you/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.0_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:42645:46)
      at TransformContext.error (file:///Users/omarkhatib/Documents/GitHub/fusion-you/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.0_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:42641:19)
      at normalizeUrl (file:///Users/omarkhatib/Documents/GitHub/fusion-you/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.0_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:40508:33)
      at async file:///Users/omarkhatib/Documents/GitHub/fusion-you/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.0_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:40651:47
      at async Promise.all (index 0)
      at async TransformContext.transform (file:///Users/omarkhatib/Documents/GitHub/fusion-you/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.0_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:40577:13)
      at async Object.transform (file:///Users/omarkhatib/Documents/GitHub/fusion-you/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.0_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:42919:30)
      at async loadAndTransform (file:///Users/omarkhatib/Documents/GitHub/fusion-you/node_modules/.pnpm/vite@4.3.8_@types+node@18.16.0_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53385:29)
^C ELIFECYCLE  Command failed.
```

### To Reproduce

Just update to v7.0.14

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 18.10.0 - ~/Library/Caches/fnm_multishells/41563_1684771105350/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/41563_1684771105350/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: ^7.0.14 => 7.0.14 
    @storybook/addon-essentials: ^7.0.14 => 7.0.14 
    @storybook/addon-interactions: ^7.0.14 => 7.0.14 
    @storybook/addon-links: ^7.0.14 => 7.0.14 
    @storybook/addon-storysource: ^7.0.14 => 7.0.14 
    @storybook/addon-styling: ^1.0.8 => 1.0.8 
    @storybook/blocks: ^7.0.14 => 7.0.14 
    @storybook/react: ^7.0.14 => 7.0.14 
    @storybook/react-vite: ^7.0.14 => 7.0.14 
    @storybook/testing-library: ^0.1.0 => 0.1.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/22695

## What I did

This package is referenced in the code, but there was no dependency in the package.json

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by ndelangen** [comment]
Yes, and Yes! @chakAs3 ! ❤️

**Review by shilman — COMMENTED** [review]
@ndelangen Fix looks reasonable, but how to test? The sandbox seems to be working fine even without the change.

**Review by IanVS — APPROVED** [review]
Looks correct to me.

**Review by shilman — APPROVED** [review]
Merging since this looks reasonable, but would be nice to have a test for this in the monorepo somehow

**Comment by IanVS** [comment]
I think to test it out, you'd need to start up a sandbox with `yarn storybook` (dev mode).

**Pull request merged**
