### PR TITLE
Fix Docgen in static builds for Info

### PR DESCRIPTION
**Pull request by danielduan**
Issue:
Fixes: #1661 #1141

PropTypes get removed during our build and Docgen never runs so the Prop Table in Info shows up empty and undefined.

## What I did

* set webpack static build environment to dev to prevent PropTypes from being stripped out
* added docgen plugin to static build babelrc
* created new story component in example to show PropType table from fallback method
* updated storyshots

## How to test

run cra-kitchen-sink and check the 3 AddonInfo buttons.

Is this testable with jest or storyshots?
yes
Does this need a new example in the kitchen sink apps?
yes
Does this need an update to the documentation?
no
If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
> set webpack static build environment to dev to prevent PropTypes from being stripped out

Can we find a way to restrict this to `prop-types` package?

**Comment by danielduan** [comment]
@Hypnosphi I think the `babel-preset-react` is the one that strips out the PropTypes when compiling for production. I'll see what I can do there in terms of making that run in dev.

We don't really have a framework for turning features on and off in Webpack without using a custom Webpack config. Sadly, we never enabled custom `.babelrc` configs for static builds.

New issue created to track custom babel config: https://github.com/storybooks/storybook/issues/1731

**Comment by Hypnosphi** [comment]
> I think the babel-preset-react is the one that strips out the PropTypes when compiling for production

As far as I know, this logic lives inside `prop-types` package

**Comment by danielduan** [comment]
Actually yeah, I was thinking of how flow types are stripped out. I can't find any documentation on how to supply the `NODE_ENV` other than the link on the bottom of the readme. https://github.com/facebook/prop-types#proptypescheckproptypes which links to https://facebook.github.io/react/docs/optimizing-performance.html#webpack

That's what I'm doing already to unset the production flag. Any other suggestions?

**Comment by Hypnosphi** [comment]
One possible solution is to add custom loader just for `prop–typesˋ package which will do nothing but replace ˋ‘process.env.NODE_ENV‘ˋ with ˋ‘“production“‘ˋ

**Comment by danielduan** [comment]
@Hypnosphi That feels really hacky.

I don't think the benefits of avoiding a dev webpack flag outweigh the cost of maintaining a custom webpack plugin.

**Comment by Hypnosphi** [comment]
> That feels really hacky

That's exactly what `DefinePlugin` does for all the packages

**Review by Hypnosphi — CHANGES_REQUESTED** [review]
Please limit the scope of dev flag to `prop-types` package (see above) or remove it completely.

Please make al those changes optional (as you don't need it if you're not using info plugin)

**Comment by danielduan** [comment]
Removed the webpack dev environment. Definitely agree on the performance but I think making webpack settings option is out of scope of this bug fix.

**Comment by Hypnosphi** [comment]
Well, now it's only babel, mut maybe it won't hurt to have this plugin always

Please address the unit tests failure

**Comment by danielduan** [comment]
how can I get the file-stub locally without modifying it manually?
```
    -      src="logo.svg"
    +      src="file-stub"
```

**Comment by danielduan** [comment]
@ndelangen @shilman any thoughts on this getting merged into master instead of 3.3? it's a small change to prod babel config and a new example app story.

**Review by Hypnosphi — APPROVED** [review]

**Comment by danielduan** [comment]
Gave up on trying to rebase it to `master`. It's just gonna go into `3.3`.

**Pull request merged**
