### PR TITLE
Add consistentNames parameter

### PR DESCRIPTION
**Pull request by Hypnosphi**
Issue: `story.name` doesn't affect story ids, which is especially confusing in case of storyshots

## What I did
Added `consistentNames` parameter, see https://github.com/storybookjs/storybook/pull/7878#issuecomment-532397143 which makes `exportedFunction.story.name` used as `storyObject.name`. Display name for UI can still be set independently via `parameters.displayName` if needed.

### CODE REVIEW

**Comment by shilman** [comment]
Hi @Hypnosphi, thanks for putting this together. I just discussed with @ndelangen and here's where we ended up:

Current solution is confusing. This new solution is not substantially LESS confusing, is destabilizing, and is also incompatible with potential future work on monoconfig.

Here's a counter-proposal for your consideration:
- Keep existing `storiesOf` API
- Update CSF loader to call into `storyStore` directly:
  - export name maps into `data.id` in backwards compatible way
  - `export.story.name` maps into `data.name` (currently `data.id` is always a function of `data.name`)

This change would happen in 6.0 and would necessitate updates to documentation, codemods, etc. But it would simplify things in a mostly backwards compatible way.

What do you think?

**Comment by ndelangen** [comment]
De-coupling the story.id & story.name is something I'd feel more conformable with in a major release.

**Comment by Hypnosphi** [comment]
> export name maps into data.id

Would that mean URLs like `/?path=/story/my-kind--story-5`?

**Comment by shilman** [comment]
> Would that mean URLs like `/?path=/story/my-kind--story-5`?

Yes but only if you name your export `story5`?

**Comment by Hypnosphi** [comment]
> only if you name your export `story5`

storiesof-to-csf does that AFAIK

**Comment by shilman** [comment]
@Hypnosphi only if there's a name collision. Typically it just camelCases the story name: https://github.com/storybookjs/storybook/blob/master/lib/codemod/src/lib/utils.js#L7

> support both id-based URLs for robots and name-based ones for humans

🤔 hmmmm...

**Comment by Hypnosphi** [comment]
What I mean is that https://storybookjs-next.now.sh/official-storybook/?path=/story/core-scroll--story-1 should be accessible both by the current URL and by something like https://storybookjs-next.now.sh/official-storybook/?path=/story/core-scroll/story-with-100vh-padding-1. And the sidebar links should use the latter

**Comment by shilman** [comment]
@Hypnosphi Those stories were converted with a very old version of `storiesof-to-csf`. IMO the exports should just be renamed.

**Comment by Hypnosphi** [comment]
OK, what about storyshot tests? Can we make `stories-to-csf` not lead to storyshot changes?

**Comment by shilman** [comment]
@Hypnosphi spelling it out just to make it more clear for myself:

```js
storiesOf.add("foo", () => ...)
```

should become 

```js
export const foo = () => ...
foo.story = { name: "foo" }
```

which translates back into:

```js
storiesOf("Foo", () => ..., { displayName: "foo" });
```

(Yes, I realize this all looks pretty ridiculous.)

The rationale behind decoupling the display name is so that you could change how the story name is displayed without changing the ID of the story. Could we just use the story ID in storyshots instead? It would be a one-time change, but I think it would be a worthwhile one. And snapshots are meant to be updated, right?

**Comment by ndelangen** [comment]
Yeah using the story.id to generate snapshots makes sense over using the names

**Comment by ndelangen** [comment]
@shilman doesn't this make more sense then:

```js
storiesOf("Foo", () => ..., { id: "foo" });
```

**Comment by shilman** [comment]
@ndelangen Yeah, I think that makes a lot of sense and we can get rid of `displayName` in 6.0. Cc @tmeasday

**Comment by Hypnosphi** [comment]
@ndelangen that's more or less what I did here

**Pull request closed without merging**
