### PR TITLE
Group deprecated stories

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: Deprecated stories were muddled up with other stories.

Also: most of the info stories were still using the deprecated APIs (cc @Keraito)

## What I did

Put all deprecated stories into their own sections. (Was this what you had in mind @shilman?)

## How to test

Hopefully name changes are self explanatory and snapshots will match up.

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Great! But I think snapshots need to be updated?

**Review by ndelangen — APPROVED** [review]

**Review by Keraito — APPROVED** [review]
Looks good, thanks for covering up what I should've done 😅🙇

**Comment by tmeasday** [comment]
This is weird, it seems like the snapshots are up to date (no changes and tests pass when I run `yarn test --core --update` on the branch), yet the builds still fail. Anyone have any idea?

**Comment by ndelangen** [comment]
I dunno @tmeasday but I ran it, and it found 2 snapshots to be in need of some updating.

**Pull request merged**
