### PR TITLE
Setup TeamCity Cloud

### PR DESCRIPTION
**Pull request by Hypnosphi**
As discussed with @ndelangen, we're going to give a try to TeamCity Cloud

I mostly just transferred the config from Circle CI. The main workflow is here: https://storybook.beta.teamcity.com/buildConfiguration/Hosted_Root_TestWorkflow?mode=builds

To view the builds, just click "Login as Guest". If you need permissions to run builds or edit settings, please send me your email via Discord PM

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Now cypress screenshots and videos get attached to test results:

https://storybook.beta.teamcity.com/buildConfiguration/Hosted_Root_E2E/4405?buildTab=tests&pager.currentPage=1

image

**Comment by jonspalmer** [comment]
Curious what the motivation is for TeamCity vs GitHub Actions, CircleCI etc.

**Comment by Hypnosphi** [comment]
Disclaimer: I'm a developer at TeamCity, so I'm biased.

TeamCity is feature-loaded, there's a lot of things you can do there. One example is [above](https://github.com/storybookjs/storybook/pull/9875#issuecomment-590013467): atttaching media to test results
Other examples are:
– [Rendering HTML artifact in an iframe](https://storybook.beta.teamcity.com/buildConfiguration/Hosted_Root_AggregateExamples/6626?mode=builds&buildTab=report_project1_Official)
– [Viewing history for a particular test](https://storybook.beta.teamcity.com/project.html?projectId=Hosted_Root&testNameId=-5694897419290215882&tab=testDetails)
– [Monitoring various customizeable stats](https://storybook.beta.teamcity.com/viewType.html?buildTypeId=Hosted_Root_TestWorkflow&tab=buildTypeStatistics&fromExperimentalUI=true)

**Comment by ndelangen** [comment]
We'll use both, in parallel.

**Comment by Hypnosphi** [comment]
@ndelangen What should be done to get this merged? Tests in `next` fail only because that branch lacks [the fix](https://github.com/storybookjs/storybook/pull/9875/files#diff-3e842acbb414beca9b7973e2eb549577)

**Comment by ndelangen** [comment]
@Hypnosphi Let's have a short meeting about merging this in and spreading some knowledge about how this all works?

**Comment by Hypnosphi** [comment]
Sounds OK. Who's going to participate?

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
