### PR TITLE
fix: only try to extract docs from mdx files

### PR DESCRIPTION
**Pull request by tobiasdiez**
## What I did

If you have stories that are no classical js files (in my case these are vue native stories), then one gets the following error:
```
Extraction error on components\n-button.stories.vue [2:36: Could not parse import/exports with acorn: SyntaxError: Unexpected token]
```
since the mdx parser gets upset. Thus, we add a check that the docs extraction is only run on mdx files.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by tobiasdiez** [comment]
@shilman @JReinhold could you please have a look at this PR? Thanks!

**Review by JReinhold — CHANGES_REQUESTED** [review]
I think this change makes sense, looks like a mistake to not check for docs file on the second pass. But I think there's been some changes here since you opened the PR (and sorry for forgetting all about this), and somewhere else a similar fix was applied.

Could you reuse the existing `isDocsMdx` instead of creating a new `isDocsFile` function?

**Comment by JReinhold** [comment]
Hmmm I see what you mean..

@tmeasday do we need to run `extractDocs` for all files (like we do now), or just `.mdx`, or both `.stories.mdx` and `.mdx`? I assume the last, but I want to be sure.

**Comment by tmeasday** [comment]
>  do we need to run extractDocs for all files (like we do now), or just .mdx, or both .stories.mdx and .mdx? I assume the last, but I want to be sure.

Only `.mdx`, because `.stories.mdx` files are treated as CSF files.

@tobiasdiez although this change isn't strictly wrong, I don't understand why it is needed. The second `updateExtracted` call will only touch files that weren't extracted in the first pass. 

So if you have a file with a `.stories.vue` extension it would get extracted on the first loop and not the second. How is it possible that it does not?

**Comment by tobiasdiez** [comment]
I just upgraded to the latest version and now indeed get a proper error at the first pass: "No matching story indexer found for ...stories.vue". So I guess the proper fix is to implement a vue stories indexer. I'll look into this at https://github.com/tobiasdiez/storybook-vue-addon/issues/30.

**Pull request closed without merging**
