### PR TITLE
UI: Remove keyboard shortcut hint in search bar on mobile viewports

### LINKED ISSUE #25816: [Bug]: mobile view should not hint at keyboard shortcut
### Describe the bug

The search bar in mobile view has the keyboard shortcut indicator `⌘ K`:
Screenshot 2024-01-25 at 14 38 03

### To Reproduce

1. Open any storybook build
2. Resize to trigger mobile view
3. Open menu from bottom left button

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tusharwebd**
Closes #25816

## What I did

This commit resolves issue: [25816](https://github.com/storybookjs/storybook/issues/25816) (mobile view should not hint at keyboard shortcut). Used react hooks to check window width whenever it changes, if the window width is less that 768 px, we consider it as mobile view (widely accepted practice) and not show the keyboard shortcuts.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Ran end to end test `yarn task --task e2e-tests --template=react-vite/default-ts --start-from=auto`
2. Open test Storybook in my browser using `yarn start`
3. Verified story views are not affected. Only change is keyboard shortcut is not displayed in mobile view.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @tusharwebd thanks for your contribution! @ndelangen would you mind checking this out? Thanks!

**Comment by cdedreuille** [comment]
There's no need to create a new function to know if you are on mobile. We already have a hook for this:
```
const { isMobile } = useLayout();
```

**Comment by tusharwebd** [comment]
> There's no need to create a new function to know if you are on mobile. We already have a hook for this:
> 
> ```
> const { isMobile } = useLayout();
> ```

Makes sense. Will update commit with this function.

**Comment by tusharwebd** [comment]
Updated branch with commits to remove unnecessary config changes and use existing function to check viewport instead of creating a new hook.

**Review by ndelangen — APPROVED** [review]

**Comment by tusharwebd** [comment]
Thanks for approving! Can someone merge this for me please? I am not able to merge because of this:
`Merging is blocked
The base branch restricts merging to authorized users. [Learn more about protected branches.](https://docs.github.com/articles/about-protected-branches/)`

**Pull request merged**
