### PR TITLE
Addon-backgrounds: Customizable Grid Cell Size

### PR DESCRIPTION
**Pull request by pmmmwh**
Issue: #5853 #6252

## What I did

- The functionality is lost during the large refactoring that happened between v5.1 and v5.2
- Added a param for the Grid selector: `grid`, with a single option `{ cellSize: number }`
  - The original implementation in #6252 used the theme object, but from what I understand this should be converted to a param after refactoring into an addon (which is done), so I chose to do it this way instead.
  - I can also remove the param from the theme and remove the relevant tests, but it will be a breaking change. Should I also allow consumption of the theme variable?
- Switched the backgrounds to use `backgroundColor` instead of `background`, because the latter would override the grid css
- Fixed the `rgba` issue in the grid css

## How to test

- Is this testable with Jest or Chromatic screenshots? **Yes**
  - A story regarding this change is added to the official storybook
- Does this need a new example in the kitchen sink apps? **Probably no**
- Does this need an update to the documentation? **Unsure**
  - If needed, I can also document it in the README of the addon

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by donaldpipowitch** [comment]
FYI: This change actually broke our usage of the addon:

https://github.com/storybookjs/storybook/pull/7951/files#diff-f01e7bd996316ee937af51de4ab40f37L131

We used a base64 encoded image as our background. Was it intended that this was never supported?

**Comment by pmmmwh** [comment]
> FYI: This change actually broke our usage of the addon:
> 
> https://github.com/storybookjs/storybook/pull/7951/files#diff-f01e7bd996316ee937af51de4ab40f37L131
> 
> We used a base64 encoded image as our background. Was it intended that this was never supported?

I cannot speak for the core team, but I think it wouldn't be too difficult to revert that and still have stuff working (possibly via `!important` on grid styles, or artificially injects specificity). The tradeoff is that Grid will not work for background values other than standard colors?

**Comment by shilman** [comment]
cc @ndelangen

**Comment by lukebarton** [comment]
@donaldpipowitch a quick workaround that you inspired:

```js
  backgrounds: [{
      name: "white-grid",
      value: `; background: url(...);`,
      default: true
    }]
```

A bit of CSS injection never hurt anyone huh?

**Pull request merged**
