### PR TITLE
Workaround broken treebeard animations

### PR DESCRIPTION
**Pull request by shilman**
Issue: #6248

## What I did

Disable sidebar animations by default

This means that treebeard won't create `velocity-react` transition elements, which are apparently broken for reasons I don't understand.

## How to test

UI will break per #6248 before this change, and be fixed after this change:

```
rm yarn.lock # forces the latest version of react?
yarn bootstrap --reset --core
cd examples/official-storybook
yarn storybook
```

### CODE REVIEW

**Comment by shilman** [comment]
Self-merging because this is breaking people and I'm confident that it's a safe fix

**Comment by Laviro** [comment]
Hi, thanks for the great work :+1: 
is it a valid fix for older versions ? in our project we have used 3.4.11, 
what is the best solution here? thanks

**Comment by shilman** [comment]
@laviro aha it's also broken for 3.x? I'll fix that too

**Comment by shilman** [comment]
@Laviro https://github.com/storybooks/storybook/releases/tag/v3.4.12

**Comment by Laviro** [comment]
Thanks for the fast response :) works great

**Pull request merged**
