### PR TITLE
Vue: Pass vite aliases imports to `vue-docgen-api`

### LINKED ISSUE #21691: [Bug]: Neither '@/mixins/window.vue' nor '@/mixins/window.js(x)' or '@/mixins/window/index.js(x)' or '@/mixins/window/index.ts(x)' could be found in '/Users/something/Desktop/something/repos/vue3-playground/packages/storybook/src/components/Modules/MainNav'
### Describe the bug

When I try to import a js file that exists inside the src/ folder it seems to not be bundled or available to storybook in the client.

### To Reproduce

image
Create a file structure like this in storybook 7 and put js files inside it. 

Type to import them in a vue component with the following alias: "@/mixins/file.js".

You get the following error: 
image
image

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Apple M2 Pro
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.47 => 7.0.0-rc.5
    @storybook/addon-essentials: ^7.0.0-beta.47 => 7.0.0-rc.5
    @storybook/addon-interactions: ^7.0.0-beta.47 => 7.0.0-rc.5
    @storybook/addon-links: ^7.0.0-beta.47 => 7.0.0-rc.5
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
    @storybook/vue3: ^7.0.0-beta.47 => 7.0.0-rc.5
    @storybook/vue3-vite: ^7.0.0-beta.47 => 7.0.0-rc.5
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bdriguesdev**
Closes #21691 

## What I did
When we use an import alias to a component that `vue-docgen-api` will need to parse to be able to generate the metadata it will not understand how to deal with this import
The import aliases config is declared at the vite, so we need to pass it to `vue-docgen-api` too, but if we pass it directly we will have a problem
In `vite` we can define an absolute path that the reference is actually where the `vite` server is running, example:
```js
{
    "@": "/src"
}
```
If the project is running at the path ```/home/projects/vue-storybook``` `vite` will consider the absolute path ```/src``` relate to the server, but `vue-docgen-api` needs the system absolute path to find the file, in this case the actually path is: ```/home/projects/vue-storybook/src```. So, before passing the aliases to `vue-docgen-api` we need to deal with this kind of absolute paths, we need transform it to actually system paths.

## How to test

It's possible to reproduce the error here:
- [Vue 2 StackBlitz](https://stackblitz.com/edit/github-pnfhmx?file=README.md)
- [Vue 3 StackBlitz](https://stackblitz.com/edit/github-j5c74f?file=README.md)

Or if you want to use the repo:
1. Run a sandbox for template, e.g. `yarn task --task dev --template vue3-vite-default-js`
2. Add in `vite.config` the alias: ```"@": '/src'```
3. Create a mixin inside `src/mixins`
4. Import this mixin using the alias in a component that has a story and use this mixin in the component
5. Open Storybook in your browser
6. Access the story of the component and you will see warning at the terminal

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by chakAs3** [comment]
i will review this for now, However i'm finishing a PR that implements volar ( vue-meta-component ) instead of  vue-docgen-api, i guess we won't have this issue let see .

**Comment by ndelangen** [comment]
Related: https://github.com/storybookjs/storybook/pull/22010

**Review by ndelangen — APPROVED** [review]

**Comment by JReinhold** [comment]
@kasperpeulen is this PR no longer needed because of Volar?

**Comment by kasperpeulen** [comment]
@chakAs3 @larsrickert Can you check if this is still necessary?

**Comment by larsrickert** [comment]
> @chakAs3 @larsrickert Can you check if this is still necessary?

No I'd say this is not needed. As far as I know both `vue-docgen-api` and `vue-component-meta` are TypeScript based parsers so the issue here is not the `vite.config.ts`.

For the reproduction code, you need to create a tsconfig where you define the alias so it works correctly:
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["src/**/*"],
  "compilerOptions": {
    "rootDir": "./src",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

For `vue-component-meta` there is currently a know limitation for aliases: https://storybook.js.org/docs/8.0/get-started/vue3-vite#limitations

**Comment by kasperpeulen** [comment]
@larsrickert I see, closing this PR then.

**Pull request closed without merging**
