### PR TITLE
Fix linting in addon-info

### PR DESCRIPTION
**Pull request by usulpro**

### CODE REVIEW

**Comment by theinterned** [comment]
Nice one @UsulPro I'm also working on fixing linting, and _luckily_ hadn't done this package yet. I will be sure to skip this package in my PR: https://github.com/storybooks/storybook/pull/911

**Comment by ndelangen** [comment]
Can we do this all in 1 PR?
Which ones can we close?

**Comment by theinterned** [comment]
@ndelangen if this is merged now as-is it shouldn't cause problems with PR #1000. In fact I haven't rebased in a while so if this is merged now I can deal with this change along with any others when I do rebase.

**Comment by theinterned** [comment]
strangely, the fixes done in this PR are not things I was seeing reported when runnig the linting on the whole project.

**Comment by ndelangen** [comment]
Sure if that's easier, I can merge this.

**Pull request merged**
