### PR TITLE
Use UTC timezone in formatting too for knobs test

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: https://github.com/storybooks/storybook/issues/2859

Previously I fixed the TZ of the date itself but not the timezone we are formatting relative to.

## What I did

Fixed both.

## How to test

Run storyshots tests

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Please apply locale and tz to vue-kitchen-sink example as well

**Review by Hypnosphi — APPROVED** [review]

**Comment by tmeasday** [comment]
It looks like there is a date in the Angular stories (although it uses the built in date formatting), and the [polymer tests](https://github.com/storybooks/storybook/blob/1ada6692ea64143c4091d580c37701cf6e298535/examples/polymer-cli/src/stories/advanced.stories.js)

**Comment by tmeasday** [comment]
LMK what you think we should do in the angular case @Hypnosphi

**Comment by Hypnosphi** [comment]
Let's keep it as is until we hit any issues with angularshots

**Pull request merged**
