### PR TITLE
display storybook version

### PR DESCRIPTION
**Pull request by usulpro**
here it is #553

### CODE REVIEW

**Review by arunoda — CHANGES_REQUESTED** [review]
Add this to the `build.js` in the same directory.
That's what's get invoked when you run `npm run build-storybook`.

**Comment by UsulPro** [comment]
Ok

**Comment by UsulPro** [comment]
Hi @arunoda 
Is everything Ok with it? Just let me know if I need to fix something
I checked it under Windows:

start-storybook | build-storybook
------------ | -------------
image | image

It may be worth adding "start" and "build" between the name and version?

**Comment by arunoda** [comment]
I just published a new version with the PR you sent.

I didn't get this part? 
> It may be worth adding "start" and "build" between the name and version?

**Comment by UsulPro** [comment]
I just wrote this in the same moment when you merged it and didn't see it :)
I think in general it should be clear what the command is executed. So it's not necessary

**Pull request merged**
