### PR TITLE
Addon-controls: Infer color and date controls

### PR DESCRIPTION
**Pull request by yannbf**
Issue:

Args like "iconColor, background, purchaseDate" shouldn't be inferred as control type "text" by default. 
Most of the time props that end with color or background will indeed be a color control, and props ending with `date` will be date.. so let's infer those to save people's time 👌 

## What I did

This PR adds more inference to controls, for `color` and `date` types.

Before:
image

After:
image

## How to test

1 - checkout the branch
2 - `yarn build client-api`
3 - run `yarn start`
4 - add this to any story in the example:
```jsx
MyStory.args = {
  iconColor: '#BADA55',
  purchaseDate: '10/11/2012', // could also be unix timestamp
};
```

- Is this testable with Jest or Chromatic screenshots? no
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? not that I know of

### CODE REVIEW

**Review by gaetanmaisse — APPROVED** [review]

**Review by shilman — COMMENTED** [review]
Much better! Looking great 💯 

Do you want to:
- [ ] Add support for other types
- [x] Add documentation

**Comment by yannbf** [comment]
Docs are updated! I think it would be awesome if @jonniebigodes could take a look at it <3

**Review by shilman — APPROVED** [review]
💯

**Comment by tmeasday** [comment]
Is this technically a breaking change? (Nice feature though!)

**Comment by yannbf** [comment]
Hey @tmeasday thinking about it, kind of.. It will change the behavior for users that used to see strings instead of the pickers and it's opt out rather than opt in 🤔. I guess we should mention about it on the migration!

**Comment by tmeasday** [comment]
Yeah, probably easy enough to opt out if people really care and a nice automatic upgrade, so I guess we can not worry about it.

**Pull request merged**
