### PR TITLE
Vite: Export storybook utilities from frameworks for better pnpm support

### PR DESCRIPTION
**Pull request by IanVS**
Issue: N/A

This is one step towards improved pnpm and yarn pnp support for vite-based storybook frameworks.  It does this by moving the imports of various storybook utilities to an explicit user dependency, the frameworks. 

## What I did

The reason we had some problems in the past, is that even though the vite builder was depending on these packages, they're used in a virtual module in the browser, which sets up its own module resolution context.  So, unless the user has those packages in their own package.json (or turns on hoisting), those utilities won't be at the root node_modules, and will error out.

This has the downside that we now have duplicated re-exports in all of the vite frameworks.  We could clean this up by re-introducing a `vite-core` package, that handles it in one place, and then each of the frameworks can just export everything from core.

## How to test

I attempted to test this in a sandbox, using pnpm and vercaddio, but I hit a strange snag:

```
Error: Cannot find module 'property-information/svg'
```

It seems this comes from a transitive dependency of mdx@1.

The other way I tested this out was by hacking on node_modules in a separate project, and it worked out alright there.  But, pnpm won't work "out of the box" until https://github.com/storybookjs/storybook/issues/19176 is addressed.  But it limits the number of packages that the user needs to install in their package.json to just addons, so it's a step in the right direction.

### CODE REVIEW

**Comment by IanVS** [comment]
The svelte sandbox errors seem to be related to the `onClick` arg not wiring up correctly to the svelte component in the `UseState` story.  I think it would fail in svelte-webpack as well, but it looks like we don't have a sandbox for that.

And I think the react-vite snapshots are actually broken in the baseline but fixed now, so should be accepted.

**Comment by ndelangen** [comment]
@IanVS I fixed the svelte component..

@tmeasday I think you should take at this..

**Review by shilman — APPROVED** [review]
@IanVS Let's merge this as is, then potentially follow up with a refactor to get this into `core-vite` along with the utils from https://github.com/storybookjs/storybook/pull/19259?

**Comment by shilman** [comment]
@tmeasday WDYT about the feasibility of https://github.com/storybookjs/storybook/issues/19176 ?

**Comment by tmeasday** [comment]
Question: **is this issue not also present in webpack also?** I would imagine the same limitation about importing from non-direct dependencies in a WP build would apply.

I'm generally in agreement about this change but I'd suggest we do it in a slightly different way. Why don't we factor out this little chunk of code that's common to both https://github.com/storybookjs/storybook/blob/next/code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars and https://github.com/storybookjs/storybook/blob/next/code/lib/builder-vite/src/codegen-iframe-script.ts and export it as a single symbol from `core-server`? Then each framework just needs to re-export one thing?

**Comment by tmeasday** [comment]
> @tmeasday WDYT about the feasibility of https://github.com/storybookjs/storybook/issues/19176 for 7.0?

I think we should do it.

**Comment by IanVS** [comment]
>Why don't we factor out this little chunk of code that's common to both [next/code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars](https://github.com/storybookjs/storybook/blob/next/code/lib/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars?rgh-link-date=2022-09-27T02%3A03%3A07Z) and [next/code/lib/builder-vite/src/codegen-modern-iframe-script.ts](https://github.com/storybookjs/storybook/blob/next/code/lib/builder-vite/src/codegen-modern-iframe-script.ts?rgh-link-date=2022-09-27T02%3A03%3A07Z) and export it as a single symbol from core-server? Then each framework just needs to re-export one thing?

That's an interesting thought.  That could be a nice way to keep things DRY, though I worry a little bit about coupling webpack and vite together in a way that may cause troubles.  Then again, the way things are now we run the risk of them drifting apart, so I guess it's a tradeoff.  

As for this issue happening in webpack, it doesn't seem to have the same problem.  I suspected as much after searching through issues for `pnpm`, and not finding anything similar to the ones we get in the vite-builder repo about hoisting.  Then I tested it out, using `npx -p @vue/cli vue create . --default --packageManager=npm --force --merge`, deleting `node_modules` and `package-lock.json`, and then `pnpm i && pnpm run serve`, and the app loaded up just fine without any kind of hoisting config or installing extra packages.  Webpack's way of bundling everything for the browser might help it in this regard, I guess.

Anyway, would you be opposed to taking an incremental approach here, continuing with this strategy for now, then cleaning up the duplication into a `vite-core` package or similar, and then maybe also DRYing it up with webpack in the future?  I'd love to get pnpm into a better spot as soon as possible.

**Comment by shilman** [comment]
@tmeasday I'm going to merge & release this (if CI passes) to let @IanVS test this more easily. If we want to tackle it differently, let's iterate once this has been validated.

**Comment by IanVS** [comment]
I tested out alpha.34, and now in a pnpm svelte-vite project, I needed to only install the following packages manually:

```
	"@mdx-js/react": "1",
	"@storybook/addon-actions": "^6.5.12",
    "@storybook/addon-backgrounds": "^6.5.12",
    "@storybook/addon-docs": "^6.5.12",
    "@storybook/addon-highlight": "7.0.0-alpha.7",
	"@storybook/addon-measure": "^6.5.12",
    "@storybook/addon-outline": "^6.5.12",
    "@storybook/core-client": "^6.5.12",
	"react": "^18.2.0",
    "react-dom": "^18.2.0",
```

React and react-dom are peer-deps (for all frameworks, due to mdx, which is a bit confusing for users sometimes), and `@storybook/core-client` isn't used directly in `builder-vite`, but `@storybook/core-client/dist/esm/globals/globals.js` is one of the modules returned in the `previewAnnotations` from: https://github.com/storybookjs/storybook/blob/104123625d825557330a0acf52d6063422c481bb/code/lib/core-server/src/presets/common-preset.ts#L96

**Comment by shilman** [comment]
cc @ndelangen ☝️

**Comment by tmeasday** [comment]
I guess the `core-client` issue would be resolved by https://github.com/storybookjs/storybook/issues/19176?

Still I think it's a bit weird that the code is in that package, which otherwise is only used for legacy v6 stuff. @ndelangen I'd really like to take some time to fix up the preview packages sometime soon.

**Comment by tmeasday** [comment]
@IanVS is there going to be any way to resolve the addons/react thing? Or do we just make the CLI install those packages as part of `sb init` if it detects pnpm and friends?

**Comment by IanVS** [comment]
I don't think it's pnpm specific, using MDX requires react, I believe. Although with MDX2, there are ways to render using other frameworks, like vue and preact https://mdxjs.com/packages/. Not all frameworks we support though, and I'm guessing it would be a lot of work to use them. @shilman has a better idea of that I'm sure. 

Another idea would be to make mdx optional. Not every project needs it or wants it, and some teams might opt for a smaller and cleaner installation instead. But again, not sure how much work that is.

**Comment by tmeasday** [comment]
Yeah, I guess a `sb init --no-mdx` would make sense, not sure when that'll get done but hey 🤷

**Comment by IanVS** [comment]
I think `core-client/globals/globals` can just be deleted.  It's only to add `STORYBOOK_REACT_CLASSES`, which seems to not even be used anymore, as far as I can tell.

**Pull request merged**
