### PR TITLE
upgrades including webpack 5

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: #9216 

## What I did

- [x] upgrades dependencies
- [x] fixed linting issues
- [x] fixed webpack build in official example

I think this PR replaces:
https://github.com/storybookjs/storybook/pull/12999
https://github.com/storybookjs/storybook/pull/12964
https://github.com/storybookjs/storybook/pull/11326

This PR should be broken into multiple smaller PRs, really this was a spike to try how close we are to webpack 5 support.
We should collaborate with CRA (@mrmckeb ) on when webpack 5 support is planned.

This PR has NO backwards compatibility for webpack 4. So we either have to come up with a strategy to add backwards compatibility somehow, OR this is a major breaking change, and a pretty disruptive one at that.

### CODE REVIEW

**Comment by lukeapage** [comment]
Tried this branch on my project - it builds ok but watch fails:

```
ERR! TypeError: compiler.plugin is not a function
ERR!     at filewatcherPlugin.apply (\node_modules\filewatcher-webpack-plugin\index.js:9:12)
ERR!     at createCompiler (\node_modules\webpack\lib\webpack.js:69:12)
ERR!     at create (\node_modules\webpack\lib\webpack.js:113:15)
ERR!     at webpack (\node_modules\webpack\lib\webpack.js:137:31)
ERR!     at f (\node_modules\webpack\lib\index.js:37:15)
ERR!     at startPreview (\node_modules\@storybook\core\dist\server\dev-server.js:413:39)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (\node_modules\@storybook\core\dist\server\dev-server.js:481:29)
ERR!     at async buildDevStandalone (\node_modules\@storybook\core\dist\server\build-dev.js:317:33)
ERR!     at async buildDev (\node_modules\@storybook\core\dist\server\build-dev.js:380:3)
```

looking at filewatcher-webpack-plugin it uses api's deprected in webpack v4 and looks basically unmaintained: https://github.com/sap9433/filewatcher-webpack-plugin

**Comment by m7kvqbe1** [comment]
Is this also now stale?

**Comment by timkindberg** [comment]
Would it be possible to publish a special alpha release on npm from this branch? Since it's not possible to install github sub-directories with npm, that means folks would have to tarball a cloned version. We've moved completely to Webpack 5 and I imagine a lot of folks who have moved to Webpack 5 do not need Webpack 4 backwards compat. So while you guys sort that out we can use `@webpack5-alpha` as a temporary hold over.

**Comment by shilman** [comment]
@timkindberg hoping to have a version to release in a proper alpha next week #13808

**Comment by shilman** [comment]
closing in favor of #13808

**Pull request closed without merging**
