### PR TITLE
Release 5.0

### PR DESCRIPTION
**Pull request by shilman**
sb5

## What I did

Merge 5.0 release branch into `next` now that the tests are passing

Released this on `debug` NPM tag as `5.0.0-debug.3`

## How to test
```
yarn test
cd examples/official-storybook
yarn storybook
```

### CODE REVIEW

**Comment by Hypnosphi** [comment]
`^5.0.0-alpha.N` will match `5.0.0-debug` =(

**Comment by shilman** [comment]
I took two shortcuts to get this building:

1. Downgraded `react-syntax-highlighter` in `addon-cssresources` due to some version conflict with 5.0 components cc @nm123github 
2. Commented out `cra-svgr.stories.js` due to a storyshots issue cc @igor-dv

**Comment by Hypnosphi** [comment]
> Any ideas what we should do next time around?

Use any word that stands before `alpha` alphabetically =)

**Comment by Hypnosphi** [comment]
@tmeasday aadebug

**Comment by tmeasday** [comment]
👌

**Comment by SimenB** [comment]
Reminds me of https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#600-tactical-rc1-2018-04-07 😀 

In the meantime, could you do a dist-tag with `delta` or something? Or `rc`? Just to avoid the issue, even though I agree one should not necessarily use semver ranges on pre-releases

**Comment by tmeasday** [comment]
We're looking to do an `rc` pretty soon anyway, so hopefully this particular example will be a non-event ;)

**Pull request merged**
