### PR TITLE
CHANGE to use react-split-view 0.1.63 over the fork

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did
Replaced the fork of react-split-view for the original.

## How to test
Run `npm install`, `cd examples/cra-storybook`, `npm run storybook`
Open browser
drag panel size handles

last step fails, needs work.

### CODE REVIEW

**Comment by UsulPro** [comment]
@ndelangen I started to work on this.
I will continue to push into this branch

**Comment by ndelangen** [comment]
Thanks man!!!

**Comment by UsulPro** [comment]
#### What I did additionally

- Setup `react-split-pane`:
-- remove `resizerChildren` props (not supported in orig repo) in favor of `resizerStyle`
-- remove 'hsplit' and 'vsplit' in favor of universal 'usplit'
-- put resizer ('usplit') inside panels and make them hiding together
-- adjust styles to keep original appearance (but there're minor changes)

> **how to test:**
-- Open browser
-- drag panel size handles
-- compare with the previos version of UI

- Setup panels hiding and restoring:
-- add `size` prop to `react-split-pane`'s
-- store panel sizes in `localStorage`

> **how to test:**
-- drag panel size handles
-- hide panels and restore (`Ctrl - Shift - L`, `Ctrl - Shift - D`) - notice how now it works: it should hide proprely and restore to the same size
-- put addons panel to the right  (`Ctrl - Shift - J`) and change size - notice that each size stores separatelly

- Add feature: "Left panel on Top":
-- via `split` prop in `react-split-pane`

> **how to test:**
At this moment it's only a privatе feature. To test it you need to change `const leftPanelOnTop = false;` to `true` in `render` manually. 
-- should work same as `downPanelInRight` (hide, restore, store size)
we can use this feature later

**Comment by ndelangen** [comment]
I will test this!

**Comment by ndelangen** [comment]
I resolved the conflicts, should be good to go.

**Comment by UsulPro** [comment]
@ndelangen please don't merge for a while. one more commit is coming

**Comment by UsulPro** [comment]
**issue**: when the left/down panel is hidden the resizer still draggable

**what I did**: add `allowResize` prop, fix `resizerStyle`

**how to test**: hide a panel, try to resize

@ndelangen It's ready now!

**Comment by UsulPro** [comment]
**Note**: By merging this we close the following issues:
#466 #869 #780 [#67](https://github.com/storybooks/storybook-ui/pull/67)

and take a step towards a solution: #813 #868 #124

**Comment by ndelangen** [comment]
I can now resize the left panel, this is new behaviors I think.

Is this something you wanted to do?

**Comment by UsulPro** [comment]
> I can now resize the left panel, this is new behaviors I think.

Do you mean `leftPanelOnTop` mode? Normally it was resizable before, I just fixed some issues. The new behavior isn't available for users at this moment.

I think we can finish this PR as it is for now. How best to switch to this mode is the issue of next step

**Comment by ndelangen** [comment]
This is what I mean:
https://www.youtube.com/watch?v=yiz_u-kATJ0&feature=youtu.be

**Comment by ndelangen** [comment]
But I do agree, this is ready to merge 👍

**Comment by Hypnosphi** [comment]
@UsulPro Do we still want to support stories panel on top at some point in future?

**Comment by UsulPro** [comment]
@Hypnosphi I believe it would be a great option for mobile screens. But at this moment this option not exposed to users. 
Do you have any ideas about it?

**Comment by Hypnosphi** [comment]
Not really, I just was curious do we still need this dead code

**Comment by UsulPro** [comment]
There are some details about possible way to use it in this comment https://github.com/storybooks/storybook/pull/908#issuecomment-298836684

**Pull request merged**
