### PR TITLE
Move prettier to devDependencies

### PR DESCRIPTION
**Pull request by ShaunEvening**
Issue:
this is leaking into our packages as a dependency
and resolves to an unexpected version in our yarn.lock file

## What I did
- Moved prettier into your devDeps list in packages that had it listed as a dependent

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ShaunLloyd** [comment]
Hey friends at storybook 👋 

I'm sure there's other dependencies in here that could be moved over to devDependencies but I didn't want to blast y'all with a big change that would probably require a lot of testing

**Review by shilman — COMMENTED** [review]
Hi @ShaunLloyd thanks for this PR! Unfortunately Prettier is an actual dependency of Storybook, so this fix won't work for us. We've started prebundling some of our dependencies (e.g. [emotion](https://github.com/storybookjs/storybook/pull/17000), [react-router](https://github.com/storybookjs/storybook/pull/17294)) to deal with this kind of situation, so I'll see if we can do something similar for prettier as part of 6.5

**Comment by shilman** [comment]
Closing this and will follow up in #17553

**Comment by ShaunLloyd** [comment]
Thank you so much for your reply, @shilman :D I'll follow you over to the other thread

**Pull request closed without merging**
