### PR TITLE
Controls: Tighten color control inference heuristic and test

### PR DESCRIPTION
**Pull request by yannbf**
Issue: #14674, #14704, #14902

## What I did

Made sure that when inferring controls automatically via custom matchers for `color`, if the value of the arg is not supported, warn to the user and continue with normal inference instead of defining the control as color.

Added tests for inferControls functionality in client-api and an e2e scenario for addon controls, testing the basic functionality + args from url

## How to test

For the custom matchers, either run storybook with a wrongly set argtype for color
```jsx
export const Story = Template.bind({});
Story.args = {
  color: {
    notSupported: 0
  }
};
Story.parameters = {
  controls: {
    matchers: {
      color: /color/i,
    },
  },
};
```

or run the unit tests
```
npx jest inferControls
```

For the controls e2e:
```
yarn test:e2e-framework react
```

### CODE REVIEW

**Comment by shilman** [comment]
Seems like your test is failing @yannbf !

**Comment by yannbf** [comment]
Hey @shilman it's awesome that the tests are failing, actually! The tests just showed me that there's an inconsistency between the starter templates from React and Vue. 

On React, there's no hardcoded argType for button size (small, medium, large) and it's inferred from proptypes/typescript interface, and it's inferred to a radio group control (enum I believe).

For the Vue template, on the other hand, this is [hardcoded](https://github.com/storybookjs/storybook/blob/64a88856815a48a57570d74dffbb28cefcf09e99/lib/cli/src/frameworks/vue3/Button.stories.js#L9) to a select control:
```
size: { control: { type: 'select', options: ['small', 'medium', 'large'] } },
```

So from that conclusion, we either:

1 - Make sure every CLI template outputs the exactly same experience (meaning we might need to hardcode argTypes where they're not automatically inferred)

2 - Rethink about the E2E tests. Maybe run them against the official-storybook example instead, knowing that the drawback is that we won't have E2E tests for an essential addon in every framework

**Comment by yannbf** [comment]
Additionally, given that #14704 seems to fit nicely with this PR, I ended up adding a fix for it here. If it does not make sense let me know, I can separate these into two PRs. It's just nice to reuse it because both works need unit tests in the same file which was created in this PR.

**Comment by shilman** [comment]
@yannbf changing to radio didn't seem to fix the problem?

**Comment by yannbf** [comment]
Hey @shilman as discussed via discord, I disabled the e2e test for the radio as we will be making sure the CLI templates are  standardised in another PR. I fixed the CLI templates for web components and the tests are now fine, but in the extended e2e pipeline there's a problem when installing angular 10. Is angular 10 webpack 5 compliant? I wonder if you could help figure out why this is happening @gaetanmaisse :D

[here's the problem](https://app.circleci.com/pipelines/github/storybookjs/storybook/18461/workflows/b4029c35-c23d-4b69-8edb-dbf5ab68914d/jobs/317991)
```
Starting type checking service...
(node:3152) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
ERR! => Failed to build the preview
ERR! Module not found: TypeError: Cannot destructure property 'descriptionFileData' of 'resourceResolveData' as it is undefined.
ERR! ModuleNotFoundError: Module not found: TypeError: Cannot destructure property 'descriptionFileData' of 'resourceResolveData' as it is undefined.
ERR!     at /tmp/storybook-e2e-testing/angular10/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compilation.js:1765:28
ERR!     at /tmp/storybook-e2e-testing/angular10/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:730:13```

**Review by shilman — APPROVED** [review]
Looking good!! 💯

**Pull request merged**
