### PR TITLE
Addon-docs: Fix inline stories using react hooks

### PR DESCRIPTION
**Pull request by atanasster**
Issue: #7924

## What I did

Replaced the storyFn instead of direct call, to be rendered as a react element

## How to test

added reactHook story to Stories.stories.tsx and can be tested in official-storybook

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
cc @Aaron-Pool can you take a quick look?

**Review by shilman — APPROVED** [review]
Thanks @atanasster! Good catch and great fix!

**Comment by Aaron-Pool** [comment]
@shilman as to if this will have any effect on inlining other frameworks--shouldn't be a problem. I can just set storyFn directly to the result of `prepareForInline`, rather than to a function that returns that result.

As for most everything else in this PR, my knowledge of React hooks and React rendering is pretty limited, so... LGTM? 🤷‍♂️

**Comment by atanasster** [comment]
@Aaron-Pool - my vue.js is like your react :) Can you help me - how do you test the vue.js integration, I can try to run some tests on my end. 
On the other hand, I think the preview window was already using the react magic for rendering and the stories with hooks were not breaking there.

**Comment by Aaron-Pool** [comment]
@atanasster this almost certainly won't break any _current_ Vue functionality. 5.2 only support iframe stories for non-react frameworks (e.g. Vue), so changes to inline rendering shouldn't effect the Vue side of things yet. Shilman tagged me (I assume) because of a PR I'm doing for 5.3 to add inline rendering support for Vue, as well as a path to inline support for other frameworks.

But yes, like you said, story preview is already pretty tightly bound to react magic, so these changes shouldn't impede my project. Might have to make a few tiny tweaks, but it should be fine! 👍

**Comment by shilman** [comment]
You guys are awesome. 💯 Merging this!

**Pull request merged**
