### PR TITLE
Undo channel stubbing - causes NPM version errors to fail silently

### PR DESCRIPTION
**Pull request by shilman**
Issue: #1486 

## What I did

Undo bad changes in PR

## How to test

CI tests

(Or force a messed up NPM version error... has bitten many of us, but not sure the best way to repro)

### CODE REVIEW

**Comment by shilman** [comment]
Got @ndelangen 's approval over slack 🍷

**Comment by tmeasday** [comment]
Perhaps we should replace it with functions that throw useful errors?

**Comment by shilman** [comment]
@tmeasday updated per your suggestion

**Review by ndelangen — APPROVED** [review]

**Review by tmeasday — CHANGES_REQUESTED** [review]

**Comment by ndelangen** [comment]
Is this mergable @tmeasday ?

**Comment by tmeasday** [comment]
LGTM!

**Review by tmeasday — APPROVED** [review]

**Pull request merged**
