### PR TITLE
Examples: Add Ivy support to angular example

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Add ivy to `examples/angular-cli` per @ThibaudAV 's comment here: https://github.com/storybookjs/storybook/pull/14653#issuecomment-822569850

@ThibaudAV @kroeder please review!

## How to test

CI passes

### CODE REVIEW

**Comment by ThibaudAV** [comment]
LGTM 
but we have respectively tested ivy support on our projects and it doesn't work completely. We haven't found the reason yet

I wonder if we should wait longer for storybook exemple 🤷‍♂️  what do you think @kroeder ?

**Comment by ThibaudAV** [comment]
✏️  Here are our last conclusions on the ivy subject 

With this PR we reproduce a problem on the component `http://localhost:9008/?path=/story/basics-ngmodule-forroot-pattern--base` (same problem on our projects with @kroeder)
The error is : 
image

It seems to be linked to this line: https://github.com/storybookjs/storybook/blob/bb0856e226671a87b1fddb01ed8a5402ec84c016/app/angular/src/client/preview/angular-beta/RendererService.ts#L91
because it is no longer present if you comment them
but on the other hand other errors occur when navigating between components 
like : 
image

My last insights:
I think that the `ɵresetCompiledComponents` should not be done before the bootstrap of a story. but during the destroy of it. 
I guess ɵresetCompiledComponents resets already initialized parts. 🤷‍♂️ 
So it must be executed after the `platform.destroy()` 

So I made a commit in this sense and this solves the problem 

but it breaks the doc with several stories :/ because the rendering is requested in parallel
we need to find a solution so that each doc stroy element can be generated sequentially 🤔 

🙈 not sure to be clear and a little complex to understand when you are not in the subject

**Comment by shilman** [comment]
@ThibaudAV @kroeder great work! perhaps we can release your fix and then fix docs support in a separate piece of work. i know @ndelangen is currently looking at how addon-docs renders stories, so this might be related. WDYT?

**Comment by ThibaudAV** [comment]
why not but if we do that I won't be able to add ivy support on my company's project 😁 
but as you wish.
I can also present the problem to one of you if you are interested

**Comment by shilman** [comment]
@ThibaudAV would love to talk it through with you and @ndelangen when you both have time!

**Comment by ndelangen** [comment]
> but it breaks the doc with several stories :/ because the rendering is requested in parallel
we need to find a solution so that each doc stroy element can be generated sequentially 🤔

Let's schedule a zoom call about this!

**Comment by ThibaudAV** [comment]
yeah next week ?  
For example Tuesday or Wednesday around 15h, 16h UTC

**Pull request closed without merging**
