### PR TITLE
fixed Duplicate declaration h

### PR DESCRIPTION
**Pull request by yi-ge**
Issue:

## What I did

fixed `Duplicate declaration h` bug.

## How to test

only add "h"

### CODE REVIEW

**Review by danielduan — APPROVED** [review]

**Comment by yi-ge** [comment]
@danielduan `eslint-disable-line` is great, but snapshots unable to pass test.

**Comment by danielduan** [comment]
run `yarn test --core --update`, it should change some snapshots

**Review by Hypnosphi — CHANGES_REQUESTED** [review]

**Comment by yi-ge** [comment]
@Hypnosphi I merge last master, run `yarn test --cli --update`, install `@storybook/codemod`, but I get it:
```
Detecting project type. ✓
 • Adding storybook support to your "React Native" app
     TypeError: Invalid Version: [object Object]
    at new SemVer (/Users/wangyi/Project/storybook/lib/cli/node_modules/semver/semver.js:291:11)
    at compare (/Users/wangyi/Project/storybook/lib/cli/node_modules/semver/semver.js:578:39)
    at gt (/Users/wangyi/Project/storybook/lib/cli/node_modules/semver/semver.js:607:10)
```

**Comment by Hypnosphi** [comment]
> install @storybook/codemod

Weird, this shouldn't be needed. Did you run `yarn bootstrap --core`?

**Comment by yi-ge** [comment]
@Hypnosphi I have updated the snapshots. Thank you.

**Review by Hypnosphi — APPROVED** [review]

**Pull request merged**
