### PR TITLE
Build: Fix CI checks

### PR DESCRIPTION
**Pull request by gaetanmaisse**
## What I did

 - Add `eslint` ignore comment to disable a `no-underscore-dangle` error in `lib/components/src/bar/button.stories.tsx` (introduced by https://github.com/storybookjs/storybook/pull/16429)
 - Update Preact preset filename
 - Skip source snippet cypress test for @storybook/html

## How to test

- [ ] CI should be 🟢

### CODE REVIEW

**Comment by gaetanmaisse** [comment]
Still to discuss (@yannbf @shilman I will ping you on Discord): 
 - Background change isn't working every time with Vue (but after multiple selections it finally works) -> Locally I have the following warning in console: `Setting a global value that is undeclared (i.e. not in the user's initial set of globals or globalTypes) is deprecated and will have no effect in 7.0.` so maybe we have to update the CLI templates?
 - `addon-docs` cypress tests for Preact -> are the feature implemented but not working or should we disable the tests?

**Comment by yannbf** [comment]
> Still to discuss (@yannbf @shilman I will ping you on Discord):
> 
> * Background change isn't working every time with Vue (but after multiple selections it finally works) -> Locally I have the following warning in console: `Setting a global value that is undeclared (i.e. not in the user's initial set of globals or globalTypes) is deprecated and will have no effect in 7.0.` so maybe we have to update the CLI templates?
> * `addon-docs` cypress tests for Preact -> are the feature implemented but not working or should we disable the tests?

I'll check this as soon as I can! My feeling is that @tmeasday knows what could be causing this. I think that message has been introduced recently

**Comment by tmeasday** [comment]
Wow, it was a while ago I added that warning and I can't quite remember, but I am sure it would have been something we discussed @shilman? Perhaps you recall.

In any case, I guess the warning is sort of self explanatory. Is this an issue with the backgrounds addon?

**Comment by shilman** [comment]
I'll look into the HTML snippet issue

**Comment by gaetanmaisse** [comment]
HTML code snippet is ok now ✅ 

There is still an issue with addon background + vue, see CircleCI artefact: https://351763-54173593-gh.circle-artifacts.com/3/cypress/sfcVue/addon-backgrounds.spec.ts.mp4

@shilman I can try to investigate a bit more on ⬆️ during the next few days but I think it worth it to merge this PR as it fixes a lot of other CI issues

**Pull request merged**
