### PR TITLE
Vite: Clean up framework dependencies / unused files

### PR DESCRIPTION
**Pull request by IanVS**
Issue:

## What I did

Similar to https://github.com/storybookjs/storybook/pull/19025, this cleans up unused dependencies in `svelte-vite` and `vue3-vite`.  It also:

- Updates the description to mention vite in all vite frameworks
- Updates the `engines` to match vite's requirements
- Removes some unused source files

## How to test

CI should pass

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
@IanVS Any idea what's up with the failing smoke tests?

**Comment by IanVS** [comment]
I can't see how the changes here could have broken CRA, so I'm tempted to call it flake. I'll rebase and push a commit to see if it happens again.

**Comment by IanVS** [comment]
Yep, seems like it was flake.

**Review by shilman — APPROVED** [review]
LGTM!

**Pull request merged**
