### PR TITLE
CLI: Create package.json when `init` run in empty project

### PR DESCRIPTION
**Pull request by billfeller**
Issue: #6002 (this PR just fix react template init problem, but is the same problem as #6002 )

run `sb init --type react` in a block directory, throw error `Cannot create property 'dependencies' on boolean 'false'`

```
$ sb init --type react

 sb init - the simplest way to add a storybook to your project.

 • Installing Storybook for user specified project type. ✓
 • Adding storybook support to your "React" app
     TypeError: Cannot create property 'dependencies' on boolean 'false'
    at default (C:\Users\wadezhan\AppData\Roaming\nvm\v10.16.0\node_modules\@storybook\cli\generators\REACT\index.js:24:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## What I did

when the package.json not exist in project, just run `npm init -y`.

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ndelangen** [comment]
I just made this so it addresses all frameworks and actually fixes: #6002

**Review by ndelangen — APPROVED** [review]

**Review by shilman — DISMISSED** [review]
@ndelangen since we're doing this across the board, it should be in a function. keep it DRY buddy! 👍

**Comment by ndelangen** [comment]
@shilman ok, it's done.

**Comment by ndelangen** [comment]
```
 • Adding storybook support to your "Create React App" based project
     TypeError: Cannot set property 'storybook' of undefined
    at default (/home/travis/build/storybookjs/storybook/lib/cli/generators/REACT_SCRIPTS/index.js
```

**Comment by billfeller** [comment]
> ```
>  • Adding storybook support to your "Create React App" based project
>      TypeError: Cannot set property 'storybook' of undefined
>     at default (/home/travis/build/storybookjs/storybook/lib/cli/generators/REACT_SCRIPTS/index.js
> ```

/home/travis/build/storybookjs/storybook/lib/cli/generators/REACT_SCRIPTS/index.js missing initial: `packageJson.scripts = packageJson.scripts || {};`

**Comment by billfeller** [comment]
> > ```
> >  • Adding storybook support to your "Create React App" based project
> >      TypeError: Cannot set property 'storybook' of undefined
> >     at default (/home/travis/build/storybookjs/storybook/lib/cli/generators/REACT_SCRIPTS/index.js
> > ```
> 
> /home/travis/build/storybookjs/storybook/lib/cli/generators/REACT_SCRIPTS/index.js missing initial: `packageJson.scripts = packageJson.scripts || {};`

fix it, re-review it.

**Comment by shilman** [comment]
One more:

>  Running storybook-cli in react_native_scripts
$ /home/travis/build/storybookjs/storybook/node_modules/.bin/sb init --skip-install --yes
 sb init - the simplest way to add a storybook to your project. 
 • Detecting project type. ✓
 • Adding storybook support to your "React Native" appls: no such file or directory: ios/*.xcodeproj
(node:11272) UnhandledPromiseRejectionWarning: react-dom: No matching version found for react-dom@undefined.
    at pickManifest (/home/travis/build/storybookjs/storybook/node_modules/libnpm/node_modules/npm-pick-manifest/index.js:122:13)
    at fetchPackument.then.packument (/home/travis/build/storybookjs/storybook/node_modules/libnpm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by billfeller** [comment]
> One more:
> 
> > Running storybook-cli in react_native_scripts
> > $ /home/travis/build/storybookjs/storybook/node_modules/.bin/sb init --skip-install --yes
> > sb init - the simplest way to add a storybook to your project.
> > • Detecting project type. ✓
> > • Adding storybook support to your "React Native" appls: no such file or directory: ios/*.xcodeproj
> > (node:11272) UnhandledPromiseRejectionWarning: react-dom: No matching version found for react-dom@undefined.
> > at pickManifest (/home/travis/build/storybookjs/storybook/node_modules/libnpm/node_modules/npm-pick-manifest/index.js:122:13)
> > at fetchPackument.then.packument (/home/travis/build/storybookjs/storybook/node_modules/libnpm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14)
> > at process._tickCallback (internal/process/next_tick.js:68:7)
> > (node:11272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

😢  @shilman i have fix it, you can re-review it again. 
any more question, i will try my best to fix it. 😄

PS: i use storybook first, and i think the generators is not perfectly automatical in some scene. `it still need some manual work at this moment.`

**Comment by shilman** [comment]
HMM CI is still busted and I'm not quite sure what's going on. @ndelangen any ideas?

**Comment by Qix-** [comment]
Bump. This is blocking development of a feature and rebasing off this patch just to test breaks everything.

What is blocking this from being merged?

**Comment by shilman** [comment]
@Qix- CI tests are failing for this PR. Something to do with Angular, but there's no error message. Want to investigate?

**Comment by billfeller** [comment]
how to solve the conflicts? there is too many conflicts i dot not confirm it. need some help.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I resolved all conflicts, LGTM

**Pull request merged**
