### PR TITLE
fix(addon-info): Display description when story name matches component

### LINKED ISSUE #4860: addon-info: story description not displaying since 4.0.9
The JSDoc description from my components disappear from my storybook in 4.0.9.

The root cause are the changes in #4685. My problem is exactly the opposite of of #4643 - my components have the same name as the story (and not necessarily as the kind).

Would a PR that accomodates both this pattern and the one from #4685 be welcome?

## Need to see code to understand?
Here's a sample of the pattern that no longer works as I expected in 4.0.9.

```js
// src/atoms/MyComponent.js
import React from 'react';

/** JSDoc description from the component; visible in 4.0.8 but not in 4.0.9. */
const MyComponent = props => <div>Hello</div>;

export { MyComponent };
```

```js
// stories/my-category/MyComponentStory.js
import React from 'react';
import { withInfo } from '@storybook/addon-info';

import { MyComponent } from '../../src';

const MyComponentStory = () => <MyComponent />;

export default withInfo('Parameter passed to withInfo.')(MyComponentStory);
```

```js
// stories/my-category/index.js
import { storiesOf } from '@storybook/react';

import MyComponentStory from './MyComponentStory';

// Note the two following lines
export default () => storiesOf('My Category')
	.add('MyComponent', MyComponentStory);
```

```js
// stories/index.js
import myCategory from './my-category';

myCategory();
```

### PR DESCRIPTION
**Pull request by misund**
Fixes #4860

See #4643
See #4685

## What I did
- Display description from JSDoc when the story name matches the component
- This matches the behavior in 4.0.8
- Also retains the behavior from 4.0.9, from when the JSDoc decription is displayed when the story _kind_ matches the component

## How to test
- I added a test for when the story name matches alongside the the test for when the story kind matches

### CODE REVIEW

**Comment by misund** [comment]
@shilman You merged #4643, would you mind having a quick look at this PR as well? They are sort of related.

**Comment by misund** [comment]
Any feedback would be appreciated.

**Comment by igor-dv** [comment]
Tests are failing. Besides that LGTM.

**Review by ndelangen — APPROVED** [review]

**Review by igor-dv — APPROVED** [review]

**Comment by misund** [comment]
Wow, I messed that up real good, didn't I.

**Comment by ndelangen** [comment]
Looks like mostly linting errors?

**Pull request merged**
