### PR TITLE
Build: Fix Angular sandbox

### PR DESCRIPTION
**Pull request by Marklb**
Closes #

## What I did

Fix errors preventing Angular sandboxes from running.

I regenerated the lock file, to fix an issue with browserlist, I think. The error was `Unknown version 115 of edge (While processing: "base$0$0")`.

The linked dev lib builds do not work with the default Angular tsconfig, so I set:
```json
"compilerOptions": {
    ...,
    "noImplicitOverride": false,
    "noPropertyAccessFromIndexSignature": false,
    "jsx": "react"
}
```

I did not narrow down what import is causing the `node_modules/@storybook/angular/node_modules/@angular-devkit` to get used, instead of `node_modules/@angular-devkit`, but for the Angular 15 sandbox I set a path in the tsconfig:
```json
"compilerOptions": {
    ...,
    "paths": {
      "@angular-devkit/*": [
        "node_modules/@angular-devkit/*"
      ]
    }
}
```

## How to test

1. Run the three sandbox templates for dev, e.g. `yarn task --task dev --template angular-cli/15-ts`, `yarn task --task dev --template angular-cli/default-ts`, `yarn task --task dev --template angular-cli/prerelease`

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by JReinhold** [comment]
Thanks for the PR @Marklb ! 💪

How would I reproduce the issue that you're fixing here?

**Comment by Marklb** [comment]
> Thanks for the PR @Marklb ! 💪
> 
> How would I reproduce the issue that you're fixing here?

Just cloning the repo, without these changes, and running any of the three Angular sandboxes has been failing for a while.

**Comment by Marklb** [comment]
I will update this to the current `next` branch in a little bit, but is there anything else I need to do or do differently?

This only happens when using the dev build of the libraries, so I am applying them and keeping them unstaged every time I want to try any changes in an Angular sandbox.

I can maybe add a condition to only apply the changes when generating a dev sandbox, if that is exposed to the sandbox generation, or do the libraries dev builds need to be changed? I don't remember which libraries were causing the issues, but I can try to find those instead of adjusting the sandbox.

**Comment by yannbf** [comment]
> I will update this to the current `next` branch in a little bit, but is there anything else I need to do or do differently?
> 
> This only happens when using the dev build of the libraries, so I am applying them and keeping them unstaged every time I want to try any changes in an Angular sandbox.
> 
> I can maybe add a condition to only apply the changes when generating a dev sandbox, if that is exposed to the sandbox generation, or do the libraries dev builds need to be changed? I don't remember which libraries were causing the issues, but I can try to find those instead of adjusting the sandbox.

Hey Mark! Sorry we haven't looked into this yet. I'll do this as first thing next week. Thank you so much!!

**Comment by Marklb** [comment]
@yannbf I thought the #1 only happened on the `angular-cli/15-ts`, but I will check that again. #2 is why I generated the lock file, so you may have to reinstall dependencies to test that fix. I haven't seen #3 before, but I will check. #4 is a warning that I have seen off and on for years, but I don't know what is causing it.

**Comment by Marklb** [comment]
@yannbf I thought the #1 only happened on the `angular-cli/15-ts`, but I will check that again. #2 is why I generated the lock file, so you may have to reinstall dependencies to test that fix. I haven't seen #3 before, but I will check. #4 is a warning that I have seen off and on for years, but I don't know what is causing it.

**Comment by valentinpalkovic** [comment]
Hey @Marklb,

Thank you for your contribution!

This PR is superseded by https://github.com/storybookjs/storybook/pull/24367.

I have updated the yarn.lock file once again to fix an issue related to the Angular 15 sandbox on our CI. Another issue popped up and it seems, that your fix isn't needed anymore. 

I am closing this PR for now. Let me know if we should reopen it.

**Comment by Marklb** [comment]
It would be nice to not have to alter the default config, but reverting #24373 and applying the three `"compilerOptions"` from this PR are the only way I have been able to use the sandbox locally. `--no-link` seems to expect prod builds of all the packages and I didn't ever figure out how to do that in a way that would actually work, because I just kept running into different problems.

If we want to reopen this PR, I can update this branch.

**Review by valentinpalkovic — APPROVED** [review]
LGTM!

**Pull request merged**
