### PR TITLE
Interactions: Fix `waitFor` behavior while debugging

### PR DESCRIPTION
**Pull request by ghengeveld**
Issue: #16872

## What I did

Don't intercept calls inside callbacks, and bubble exceptions inside callbacks up to the parent rather than forwarding it to the next interceptable call. Show child interactions in log and display errors in the appropriate place. I got rid of the `forwardedException` concept entirely because it didn't (and can't) work with chained interactions (`a().b()`). Instead, any interaction that raises an exception will now appear in the log, even if it's not interceptable.

## How to test

1 - Install @storybook/testing-library0.0.14--canary.23.ac6b056.0 in the `oficcial-example` project
2 - Run `yarn start`

- [x] Is this testable with Jest or Chromatic screenshots? Yes
- [x] Does this need a new example in the kitchen sink apps? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by yannbf** [comment]
Awesome stuff @ghengeveld !

I noticed a possible issue in [this story](https://5a375b97f4b14f0020b0cda3-puugkrxyfd.chromatic.com/?path=/story/addons-interactions-accountform--wait-for)

**Issue:**

1 - waitFor is not visible, so it looks like the two last steps are child of userEvent
2 - when interacting, it fails

image

**Steps to reproduce**

1 - Click on Go to Start
2 - Click on Go forward 2x

**Comment by yannbf** [comment]
> @yannbf you need [storybookjs/testing-library#23](https://github.com/storybookjs/testing-library/pull/23) as well.

Thanks! I updated the "How to test" section to reflect that.

**Comment by yannbf** [comment]
I just tested many scenarios and they all were pretty good, awesome work @ghengeveld 🙌

**Review by yannbf — APPROVED** [review]

**Comment by ghengeveld** [comment]
@shilman This is ready to merge. I'll leave that up to your discretion.

**Comment by IanVS** [comment]
Will this be picked into 6.5 as well, or does it rely on 7.0 changes?

**Comment by yannbf** [comment]
> Will this be picked into 6.5 as well, or does it rely on 7.0 changes?

This was just released in [7.0.0-alpha.3](https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.3) and the corresponding fix of testing-library was released in [14.0.0-next.0](https://www.npmjs.com/package/@storybook/testing-library/v/0.0.14-next.0) and the idea is to test it out enough to see if we bring it back to 6.5!

**Comment by IanVS** [comment]
Awesome, I was able to hack it into my 6.5 vite project, and it seems like it's working great.  I did find one potential bug, though:

```js
await expect(newRoles).toEqual(expect.arrayContaining([expect.objectContaining({ name: 'New role' })]));
```

crashes the whole storybook app (white screen of death) with the following error in the console:

```
Encountered two children with the same key, `[object Object]`.
```

**Comment by ghengeveld** [comment]
That looks like a key prop warming, but I doubt fixing it will resolve the white screen of death. Will investigate anyway.

**Comment by ghengeveld** [comment]
> Awesome, I was able to hack it into my 6.5 vite project, and it seems like it's working great. I did find one potential bug, though:
> ...

Fixed here: https://github.com/storybookjs/storybook/pull/18499

I did not encounter the key prop warning, so I didn't address it.

**Comment by ghengeveld** [comment]
This should be backported to 6.5.

**Pull request merged**
