### PR TITLE
Add sidebarAnimations config prop

### PR DESCRIPTION
**Pull request by michaltaberski**
Issue:

## What I did
add option `sidebarAnimations` which allows to disable sidebar tree animation. By default animations are enabled

## How to test
```
import { setOptions } from '@storybook/addon-options';

setOptions({
  sidebarAnimations: false,
});
```

### CODE REVIEW

**Review by Hypnosphi — APPROVED** [review]
LGTM

**Comment by Hypnosphi** [comment]
In fact, we can think about using CSS transitions instead of JS animation provided by react-treebeard to make things less laggy with heavy stories. But an ability to completely opt out of animations won't hurt anyway

**Comment by UsulPro** [comment]
whether it will lead to the fact that in the future we will have a bunch of options for tweaking UI? I guess we'll able to provide the same options via UI components when it's ready

**Comment by ndelangen** [comment]
Indeed @UsulPro

**Pull request merged**
