### PR TITLE
Limit react versions to >=15

### PR DESCRIPTION
**Pull request by danielduan**
Issue:
I don't think our code base supports React ~0.14 anymore. It's been a while since 15 was released and lots has changed in React land. I think it's probably better for us maintenance wise to drop 14 as well.

Either that, or we should have some tests in place to make sure our code base doesn't regress on 14.

This might break support for alpha builds like `16.0.0-alpha.2`. We could also document it somewhere in a README about deprecating support instead of in a peer dependency warning that everyone ignores.

Suggestions?

## What I did

Seems like we don't support React 0.14 anymore out of the box. Issue came up in support slack and our CRA example app won't take 0.14 either.

## How to test

Run CRA example app.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
> This might break support for alpha builds like 16.0.0-alpha.2

I believe there is a way not to break that

**Comment by ndelangen** [comment]
Anyone with a strong opinion on this? who wants to review / approve? @storybooks/team

**Review by Hypnosphi — CHANGES_REQUESTED** [review]
Looks like it should be `>=15.0.0 || ^16.0.0-alpha`.

Checked it on http://jubianchi.github.io/semver-check/
```
16.0.0-beta.5 satisfies constraint >=15.0.0 || ^16.0.0-alpha
```

**Comment by danielduan** [comment]
should we implement this across the board in every `package.json`?

**Comment by ndelangen** [comment]
With what @Hypnosphi mentions, if we do merge this... we need to explicitly update every time a beta/alpha/rc is released.

**Comment by Hypnosphi** [comment]
> we need to explicitly update every time a beta/alpha/rc is released.

Only after we make sure we support it

**Comment by danielduan** [comment]
Wouldn't the peerDep just be a warning anyway? I think it will still use any version that's available but complain to you in the console.

**Comment by danielduan** [comment]
I think one warning on the main react package is probably enough instead of adding it for all the addons. I don't think RN works on `react@0.14` so for the time being, `*` should be fine.

**Review by Hypnosphi — APPROVED** [review]

**Comment by Hypnosphi** [comment]
LGTM

**Pull request merged**
