### PR TITLE
lower babel-loader required version everywhere

### PR DESCRIPTION
**Pull request by osdiab**
Issue: #5183 

## What I did

I reduced the version of `babel-loader` required by all the storybook subpackages to `^8.0.0` instead of `^8.2.2` so that modern versions of `react-scripts` can resolve the version it wants

## How to test

- Is this testable with Jest or Chromatic screenshots? Irrelevant
- Does this need a new example in the kitchen sink apps? Nope
- Does this need an update to the documentation? Nope

One thing that we should test is the missing dependency I saw here: https://github.com/storybookjs/storybook/issues/5183#issuecomment-829029201

Not sure why the particular dependency was missing but i can't find mention of `babel-plugin-polyfill-corejs2` in the storybook codebase, not really sure what was going on with that; maybe it was an addon?

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by merceyz** [comment]
This wont fix anything, `babel-loader` will be resolved to the latest version either way.

There isn't an issue on Storybooks' end, it's an issue with how `create-react-app` does their preflight check. Their preflight check assumes all their dependencies will be hoisted to the root which is not guaranteed to happen and is therefor a flawed check. They do get the expected version at runtime but their check is broken.

**Comment by osdiab** [comment]
@merceyz i don't think that's true. If you install react-scripts, which specifies exactly Babel-loader 8.1.0 in its package.json, then yarn/NPM should resolve a mutually compatible version for both requirements I believe, unless I'm mistaken.

**Comment by ndelangen** [comment]
The issue we're addressing here, is that storybook's babel dependencies were too 'latest' compared to CRA's, lowering them means we allow for more versions-ranges, which means we allow the resolve to the same version as CRA.

**Comment by osdiab** [comment]
Looks like I was mistaken, when I tried it on a repo it did end up installing multiple versions. But that said at least it's possible for me to modify my `yarn.lock` to install the version I desire instead of relying on breaking resolution for `babel-loader` for all subpackages of my company's monorepo by setting a Yarn `resolutions` entry override in the root `package.json`.

**Comment by osdiab** [comment]
and to clarify, by too "latest" i mean that the current version of `react-scripts` demands `8.1.1` but `storybook` specifies `^8.2.2` so they're mutually exclusive of one another.

**Comment by ndelangen** [comment]
We should try to keep our version ranges in `package.json` files of public packages, as low a possible, and leave it up to users to install the latest.

This will ensure we stay compatible with other tools as much as possible, and do not burden users with forcing them to upgrade other tools when they are not ready yet.

With "as low as possible" I mean:
```diff
- "babel-loader": "8.2.9",
+ "babel-loader": "8.0.0",
```

Unless we actually depend on something that was introduced in "8.2.x" of course. But I think generally we're not.

**Comment by goldo** [comment]
Also interested in this PR !  🙏   (react-script/babel-loader conflict)

**Comment by shilman** [comment]
A little bird told me CRA is going to drop this constraint in their next release

**Comment by osdiab** [comment]
@shilman either way might still be worth doing this (and may make sense for other deps too) just to minimize conflicting versions on install, that definitely makes it less urgent if it materializes though!

**Comment by merceyz** [comment]
https://github.com/facebook/create-react-app/issues/10123#issuecomment-759167032 seems to indicate the specified version is what it is for a reason

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
@ndelangen ping!

**Pull request merged**
