### PR TITLE
CLI: Don't output startup information on smoke test

### PR DESCRIPTION
**Pull request by iliyanyotov**
Issue: https://github.com/storybookjs/storybook/issues/5164

Don't output the startup information when running a smoke test.

## What I did
Moved the function call into the condition so it's not showing when running a smoke test.

The snapshots were failing prior to my changes, so I updated them in order to run the tests successfully.

## How to test

- Run the CLI command without the smoke test flag, startup information should be available.
- Run the CLI command with the smoke test flag, you should see only the stats, but not the startup information.

### CODE REVIEW

**Comment by libetl** [comment]
next or master ?

**Comment by libetl** [comment]
This change was created on top of https://github.com/storybookjs/storybook/tree/release/5.0

**Comment by libetl** [comment]
Rebasing just to compare, but requesting changes.

**Review by libetl — DISMISSED** [review]
this is wrong, you should rebase on `next`

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
cherry-picked & rebased

**Comment by ghengeveld** [comment]
This changed introduced the unwanted side effect that `--ci` now also doesn't show the startup info anymore. This makes it impossible to know for sure on which port Storybook was actually started.

This is about to be fixed: https://github.com/storybookjs/storybook/pull/7822

**Pull request merged**
