### PR TITLE
Use addons.setPreview to set the preview.

### PR DESCRIPTION
**Pull request by arunoda**
Now we use addons.setPreview and addons.getPreview introduce by the addon api.

This allows addons to decorate the preview area.
See demo:  https://gist.github.com/arunoda/df0b1f83a1189b739b9c3ecfc18e53aa

It's also possible to set the completely new preview. But it won't make sense because it can't load the iframe.

### CODE REVIEW

**Comment by arunoda** [comment]
@mnmtanish could you check this?

**Comment by mnmtanish** [comment]
With the post-message channel, we really don't need to create a dataId every time the page loads. So it is perfectly fine to replace the preview builder completely. The get->wrap->set thing in the gist may cause unexpected bugs and it's just kinda weird.

**Comment by mnmtanish** [comment]
We used dataId in pagebus because it stored data in local storage which is global. The post-message channel only exists between the parent window and the iframe. We can set a constant key like `storybook-channel` as an added safety measure. But even that will only be necessary if there are other postmessage exchange between manager and preview pages which don't use the channel.

**Comment by arunoda** [comment]
This PR is not about dataId. Let's talk about in another issue.
I want to way to write some code for designer in the preview area outside of the iframe.
What your suggestion?

**Comment by mnmtanish** [comment]
This problem is very much related to dataId. It is the only thing the preview builder needs other than the kind and the story. As dataId is not necessary preview builders can be written outside react-storybook repo.

For the designer issue:

**myapp/.../addons.js**
```js
import '@kadira/storybook-addon-designer/register';
```

**storybook-addon-designer/.../manager.js**
```js
// init function
addons.setPreview((selectedKind, selectedStory) => {
  const query = qs({ selectedKind, selectedStory });
  const url = 'iframe.html?${query}';
  return (
    <div>
      <div>-image-</div>
      <iframe url={url} />
    </div>
  )
})
```

**react-storybook/.../provider.js**
```js
// constructor
if(!addons.getPreview()) {
  // NOTE: load default preview code from preview.js instead
  addons.setPreview((selectedKind, selectedStory) => {
    const query = qs({ selectedKind, selectedStory });
    const url = 'iframe.html?${query}';
    return <iframe url={url} />;
  })
}

// renderPreview
renderPreview(selectedKind, selectedStory) {
  const previewBuilder = addons.getPreview();
  return previewBuilder(selectedKind, selectedStory);
}
```

**Comment by arunoda** [comment]
Okay. So, then only one addon could set the preview.
If not, we need to throw an error. 
So, user know what's going on and he/she could choose what's needed.

This is apply for both for the database and for the channel.

**Comment by arunoda** [comment]
Okay. Not it looks good.

**Comment by ioss** [comment]
I'd suggest, that addons.getPreview should be preset with the default preview-function.
As suggested in the initial comment/gist.
That way addons do not need to know how to create the base preview (which could change in future versions) and it would also help addons that only decorate the preview to be mostly independent from other addons that decorate the preview.

_A safer approach would be to add additional areas, where we could add components to. But for now this PR would be of great use to me, so I do not have to patch it in by myself. :)_

**Comment by shilman** [comment]
@arunoda any plans to merge this? it currently seems like the `dist` files are out of sync with the `src` files...

**Comment by ndelangen** [comment]
@mnmtanish Do you think you could give this an look-through and choose to continue or close?

**Pull request closed without merging**
