### PR TITLE
UI: Update background color

### PR DESCRIPTION
**Pull request by MichaelArestad**
## What I did

Testing out a slightly different background color.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@dominictwlee I noticed when going through docs images that the blue in screenshots was wrong. I must have copied the wrong value in. This will resolve it. What do you think?

**Review by domyen — APPROVED** [review]

**Comment by domyen** [comment]
I can confirm that this is the correct bg color

**Comment by MichaelArestad** [comment]
@shilman Can you get this one in sooner than later?

**Comment by valentinpalkovic** [comment]
@MichaelArestad can we merge this one? :)

**Comment by MichaelArestad** [comment]
@valentinpalkovic @shilman Thank you for getting this in!

**Pull request merged**
