### PR TITLE
using process.exitCode instead of process.exit()

### PR DESCRIPTION
**Pull request by davidkwan95**
This PR should fix issue #2716

### CODE REVIEW

**Comment by ndelangen** [comment]
Thank you for this PR, Looks good. Can you teach my why the issue occurred and why this fixes it?

**Comment by Hypnosphi** [comment]
I'm intrigued as well. Docs actually [say](https://nodejs.org/api/process.html#process_process_exit_code) that using `process.exit()` is not a recommended practice, but the reason is that it may force the exit *too early* which is contrary to the referenced issue

**Comment by davidkwan95** [comment]
I'm not too sure, but I noticed that calling `process.exit()` inside the callback function seems to wait for some process to be finished before exitting. I'm assuming it has something to do with webpack or node.
Without calling the `process.exit()`, we will be able to exit the program after the event loop is done, but since we got an error, we need to set the exit code to 1 by using `process.exitCode = 1`

**Comment by Hypnosphi** [comment]
> after the event loop is done

If there's some process running (as you say), event loop won't be sone until the process is finished

**Comment by davidkwan95** [comment]
I've checked that the fix works in my current project.

**Comment by ndelangen** [comment]
So I've actually hit this problem now on an other library.
https://github.com/danielstjules/jsinspect/pull/69

I'm ready to approve this.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
