### PR TITLE
Add TypeScript CRA example

### LINKED ISSUE #5006: CRA2 TypeScript example
**Is your feature request related to a problem? Please describe.**
Would be really helpful for many newcomers to have some good base example for CRA + TypeScript case as it's getting to be very popular in react community.

**Are you able to assist bring the feature to reality?**
I can send a PR if you agree with including it 👍

### PR DESCRIPTION
**Pull request by mucsi96**
Issue:

## What I did

I have created an example incorporating CRA2, TypeScript, TSLint, Jest, Enzyme

image

Closes #5006
Closes #5011

@igor-dv @ndelangen Please review

### CODE REVIEW

**Comment by igor-dv** [comment]
We need to setup netlify and CI, other than that LGTM.

**Review by shilman — APPROVED** [review]
This is great. However, it looks like the acceptance test is not set up properly since it's not rendering right in Chromatic. Not sure what's going on because the code looks good to me.

**Review by shilman — CHANGES_REQUESTED** [review]
see comment above

**Comment by mucsi96** [comment]
On what server is Chromatic checking the UI? Is it Netlify?

**Comment by Hypnosphi** [comment]
> Not sure what's going on

This one should be a symlink not a plain text file:
https://github.com/storybooks/storybook/blob/f9bdd9ab4dfed0561cc3d72e3abb5a35344e0f2b/examples/official-storybook/built-storybooks/cra-ts-kitchen-sink

**Comment by Hypnosphi** [comment]
The problem is that right now teamcity doesn't build the new example. You need to add an entry here. And unfortunatelty you need to do it on `next` branch first because that's the branch that forms the builds graph. You need to set `merged` flag to `false` when doing that in `next`, and then to `true` in this branch.

**Comment by mucsi96** [comment]
Can you help with that? I not sure I understand as this is my first contribution to storybook. Probably I don’t have rights for that.

**Comment by shilman** [comment]
Thanks @Hypnosphi for taking care of the teamcity -- looks great!

**Review by shilman — CHANGES_REQUESTED** [review]
@mucsi96 Thanks for your patience on this and your contribution. It looks like the yarn lockfile is dirty. Can you update that and I'll merge?

**Comment by mucsi96** [comment]
Thx @shilman ! Thx @Hypnosphi for helping out with TeamCity! I updated the lockfile. Unfortunately the `CRA TS` build is failing with 
```
Failed to resolve artifact dependency <Open-source projects / Storybook / Bootstrap, build #2331 [id 1871311]>: No files matched for patterns "dist.zip" from <Open-source projects / Storybook / Bootstrap, build #2331
```

Can you help with resolving this?

**Comment by shilman** [comment]
Looks like it's building now, so I'm merging. Thanks for hanging in there!

**Pull request merged**
