### PR TITLE
Set ESlint rules more strict 🚑

### PR DESCRIPTION
**Pull request by theinterned**
Issue: -should create one-

> This is a continuation of the work by @ndelangen in PR #911

> This is in progress

## What I did
As described in review comments #904 linting is rather non-strict right now.
Though I'm personally of the opinion too strict linting can be harmful, I agree, we could make it a bit more strict to weed out some bad code we have and prevent bad come from getting pushed to master.

## How to test
run `npm run lint`

### CODE REVIEW

**Comment by theinterned** [comment]
I thought I'd give an update on my work. 

I'm down to `✖ 72 problems (64 errors, 8 warnings)`

For the time being I'm skipping jsx-a11y issues as I didn't feel comfortable fixing a number of the UI-related issues without running the "kitchen-sink" project and generally making more nuanced decisions. I plan to tackle that in a separate PR.

My PR is here https://github.com/storybooks/storybook/pull/1000

@ndelangen does it make sense to close that one in favour of this?

**Comment by ndelangen** [comment]
Hey good work! any reason you've decided to create another PR? which one can we close?

**Comment by theinterned** [comment]
@ndelangen I wasn't sure if I should merge my forked branch back into this one or just replace this PR with my own.

Unless there is a good reason not to, I would be in favour of cloisng this PR and keeping #1000 around.

I started that PR as a fork of this branch anyways so all the work here in #911 is also in #1000

**Comment by ndelangen** [comment]
✖ 67 problems (57 errors, 10 warnings)

**Review by ndelangen — APPROVED** [review]

**Comment by shilman** [comment]
@theinterned @ndelangen sorry I missed that this was waiting for my review. We need to get this merged, see e.g. #1163 

@theinterned do you mind resolving the merge conflicts and we can get this merged to do a follow-on release? Who knows what other bugs are lurking behind this PR! 😱

**Comment by ndelangen** [comment]
closed in favour of #911

**Comment by theinterned** [comment]
Hi sorry I didn't reply! I was on vacation. Looks like you've got things sorted here though! I'll see if I can help out on the #911 branch

**Pull request closed without merging**
