### PR TITLE
Add TypeScript CRA example

### LINKED ISSUE #5006: CRA2 TypeScript example
**Is your feature request related to a problem? Please describe.**
Would be really helpful for many newcomers to have some good base example for CRA + TypeScript case as it's getting to be very popular in react community.

**Are you able to assist bring the feature to reality?**
I can send a PR if you agree with including it 👍

### PR DESCRIPTION
**Pull request by mucsi96**
Issue:

## What I did

I have created an example incorporating CRA2, TypeScript, TSLint, Jest, Enzyme

image

Closes #5006

### CODE REVIEW

**Comment by mucsi96** [comment]
@shilman Can you help me with broken build? Looks like its totally not related to the changes I have made. Would be very helpful to move this forward

**Review by ndelangen — APPROVED** [review]

**Comment by igor-dv** [comment]
This PR is containing changes from wrong commits (probably needs a merge from `next`).
IMO we don't need this as an example app, considering maintenance cost. Better having it as a CLI test. If this more like having a working example, it can also be done out of the monorepo..

**Comment by mucsi96** [comment]
I can see that storybook itself is migrating over TypeScript. Its a very popular setup. Because of that I thought it makes sence to have a similar example setup as well. It looks easy now but I spent half a day to make it working as it required quite a bit of investigation. IMO if this is out of monorepo less people will find it. What do you think?

**Comment by igor-dv** [comment]
@mucsi96, mind solve the conflicts + fix the linter?

**Pull request closed without merging**
