### PR TITLE
Generate lib/cli-storybook with ts-up

### PR DESCRIPTION
**Pull request by GanHingLong0423**
Issue: https://github.com/storybookjs/storybook/issues/18732

## What I did
Migrated `lib/cli-storybook` to use the `ts-up` bundler.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots? No
- [ ] Does this need a new example in the kitchen sink apps? No
- [ ] Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@GanHingLong0423 thanks for taking the time and effort to create this pull request. We appreciate it your willingness to help us with part of Storybook.

@ndelangen when you have a chance can you take a look at this one? Thanks in advance

**Comment by ndelangen** [comment]
@GanHingLong0423 thank you for this PR, unfortunately I'm going to close this one; sorry.

This package doesn't have any build steps at all, it's just a single file which is CJS only, and also never needs type definitions.
It's only purpose is to allow people to install/run `@storybook/cli` alias'd as just `storybook`.

Because this package has no build-system, it also does not need to be converted to ts-up. Sorry about the confusion!

**Comment by GanHingLong0423** [comment]
@ndelangen Thank you for the review, may I ask which package still need migration? Is `lib/core-webpack` able to migrate?

**Comment by ndelangen** [comment]
Yes, I think `lib/core-webpack` is a good target!

**Pull request closed without merging**
