### PR TITLE
add support for all devServer options

### PR DESCRIPTION
**Pull request by thabti**
Webpack chunks details can be too noises, allowing users to pass additional options to disable noise.

example webpack file:

```js
// you can use this file to add your custom webpack plugins, loaders and anything you like.
// This is just the basic way to add addional webpack configurations.
// For more information refer the docs: https://getstorybook.io/docs/configurations/custom-webpack-config

// IMPORTANT
// When you add this file, we won't add the default configurations which is similar
// to "React Create App". This only has babel loader to load JavaScript.
const package = require('../package.json');
const webpack = require('webpack');
module.exports = {
  plugins: [
    // your custom plugins
    new webpack.NoErrorsPlugin()
  ],
  devServer: {
    stats: 'errors-only',
  },
  module: {
    loaders: [
  
      {
        test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/
      },
      {
        test: /\.css|.scss$/,
        loader: `style!css?modules&importLoaders=2&sourceMap&localIdentName=${package.config.cssModulePattern}!sass?outputStyle=expanded&sourceMap`
      }
    ],
  },
};

```

Will stop this noise:
screen shot 2017-03-05 at 1 35 12 pm

### CODE REVIEW

**Comment by einarlove** [comment]
Similar to this open PR https://github.com/storybooks/react-storybook/pull/697, but I think both options could we useful.

The `--quiet` option suggested also silences the output in the console in the browser.

**Comment by ndelangen** [comment]
Hey @sabeurthabti, do you think you could resolve the conflicts?

**Comment by sabeurthabti** [comment]
@ndelangen I think there is no need for this PR anymore. Someone already passed the `config. devServer`. Happy for this to be closed.

**Comment by ndelangen** [comment]
@sabeurthabti Thanks anyway !!!

**Pull request closed without merging**
