### PR TITLE
Build: Switch to an alternative `node:fs` mocking system

### LINKED ISSUE #24915: [Bug]: ENOENT: no such file or directory, open 'undefined/templates/base-preview-head.html'
### Describe the bug

The following errors occur when using NodeJS version 20.5.0 or above:

```
 FAIL  lib/core-common/src/utils/__tests__/template.test.ts
  ● server.getPreviewHeadHtml › when .storybook/preview-head.html does not exist › return an empty string

    ENOENT: no such file or directory, open 'undefined/templates/base-preview-head.html'

      26 |   interpolations?: Record<string, string>
      27 | ) {
    > 28 |   const base = fs.readFileSync(`${sync(__dirname)}/templates/base-preview-head.html`, 'utf8');
         |                   ^
      29 |   const headHtmlPath = path.resolve(configDirPath, 'preview-head.html');
      30 |
      31 |   let result = base;

      at readFileSync (src/utils/template.ts:28:19)
      at Object.<anonymous> (src/utils/__tests__/template.test.ts:24:44)

  ● server.getPreviewHeadHtml › when .storybook/preview-head.html exists › return the contents of the file

    ENOENT: no such file or directory, open 'undefined/templates/base-preview-head.html'

      26 |   interpolations?: Record<string, string>
      27 | ) {
    > 28 |   const base = fs.readFileSync(`${sync(__dirname)}/templates/base-preview-head.html`, 'utf8');
         |                   ^
      29 |   const headHtmlPath = path.resolve(configDirPath, 'preview-head.html');
      30 |
      31 |   let result = base;

      at readFileSync (src/utils/template.ts:28:19)
      at Object.<anonymous> (src/utils/__tests__/template.test.ts:44:44)

  ● server.getPreviewBodyHtml › when .storybook/preview-body.html does not exist › return an empty string

    ENOENT: no such file or directory, open 'undefined/templates/base-preview-body.html'

      10 |   interpolations?: Record<string, string>
      11 | ) {
    > 12 |   const base = fs.readFileSync(`${sync(__dirname)}/templates/base-preview-body.html`, 'utf8');
         |                   ^
      13 |
      14 |   const bodyHtmlPath = path.resolve(configDirPath, 'preview-body.html');
      15 |   let result = base;

      at readFileSync (src/utils/template.ts:12:19)
      at Object.<anonymous> (src/utils/__tests__/template.test.ts:64:44)

  ● server.getPreviewBodyHtml › when .storybook/preview-body.html exists › return the contents of the file

    ENOENT: no such file or directory, open 'undefined/templates/base-preview-body.html'

      10 |   interpolations?: Record<string, string>
      11 | ) {
    > 12 |   const base = fs.readFileSync(`${sync(__dirname)}/templates/base-preview-body.html`, 'utf8');
         |                   ^
      13 |
      14 |   const bodyHtmlPath = path.resolve(configDirPath, 'preview-body.html');
      15 |   let result = base;

      at readFileSync (src/utils/template.ts:12:19)
      at Object.<anonymous> (src/utils/__tests__/template.test.ts:84:44)
```

This is because of [this issue](https://github.com/tschaub/mock-fs/issues/377) in mock-fs. Short version: NodeJS added an optimisation in 20.5.0 where reading a UTF-8 file uses a dedicated fast path. This breaks mock-fs.

### To Reproduce

1. Make sure to use NodeJS version >= 20.5.0
2. Clone this repository
3. Issue `yarn test` in the project root

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (16) x64 AMD Ryzen Threadripper 1900X 8-Core Processor
    Shell: 5.2.15 - /usr/bin/bash
  Binaries:
    Node: 20.5.1 - ~/.local/share/nvm/v20.5.1/bin/node
    Yarn: 4.0.0 - ~/.local/share/nvm/v20.5.1/bin/yarn <----- active
    npm: 9.8.0 - ~/.local/share/nvm/v20.5.1/bin/npm
```

### Additional context

Still trying to work on issue #11486.

### PR DESCRIPTION
**Pull request by samvv**
Closes #24915

## What I did

On recent versions of NodeJS, the tests failed to run due to `mock-fs` being outdated. This pull request should fix that by getting rid of mock-fs entirely. See https://github.com/backstage/backstage/issues/20436 for some motivation why this would be a good thing.

I created a new file `code/lib/core-common/src/mock.ts` that performs roughly the same features as [mock-fs](https://www.npmjs.com/package/mock-fs) but in a different (hopefully more stable) manner. The tests `code/lib/core-common/src/utils/__tests__/interpret-files.test.ts` and `code/lib/core-common/src/utils/__tests__/template.test.ts` were only adjusted in their import path, which now points to `mock.ts`. The API remains the same.

## To Do Before Merge

 - [ ] Rimraf the test data when tests have completed
 - [ ] Some tests behave different with the new system. Is this expected or a bug?
 - [ ] Check whether the location of `mock.ts` is a good one. Do we  need to create a separate package?

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

No manual testing should be necessary, as this is an issue related to the unit tests.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by samvv** [comment]
Going to ask @valentinpalkovic since he merged my last pull request: who should I ask for feedback about the 'To Do Before Merge' in my pull request?

**Review by ndelangen — APPROVED** [review]

**Comment by valentinpalkovic** [comment]
Hi @samvv
Could you try to fix the unit tests

**Comment by samvv** [comment]
> Hi @samvv
> Could you try to fix the unit tests

I can but I'm not sure if the unit tests failed because they allowed something invalid or because the new system is broken. Does somebody know anything more about the failing test cases?

**Comment by valentinpalkovic** [comment]
As far as I can see the mocks are not applied but the real files are loaded

**Comment by samvv** [comment]
Oh thanks that is actually really helpful. I will try to make some time available this evening to work on it.

**Comment by shilman** [comment]
@samvv We've switched the entire monorepo over to Vitest. FYI, if you're going to resume this PR!

**Comment by shilman** [comment]
@ndelangen would we really want to switch from a library to something we need to maintain ourselves?

**Comment by ndelangen** [comment]
@shilman yes, I'm optimistic about that.
see: https://github.com/backstage/backstage/issues/20436#issue-1930084020

**Comment by ndelangen** [comment]
@samvv Do you see a possibility to take this PR over the finish line?

We migrated to vitest in the mean time 😓 
A few tests are failing.. Could you fix them? If so, I think we can merge this.

**Comment by ndelangen** [comment]
@samvv please re-open if you're interested in pursuing this further ❤️

**Pull request closed without merging**
