### PR TITLE
Make compatible with yarn Pnp

### PR DESCRIPTION
**Pull request by crubier**
Issue: https://github.com/storybookjs/storybook/issues/6899

## What I did

Followed indications of @arcanis here https://github.com/storybookjs/storybook/issues/6899#issuecomment-496909337 to make Storybook compatible with Yarn Pnp.

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by thiagoteles** [comment]
Hey @ndelangen ... Can you give a hand here? :P

**Comment by shilman** [comment]
@crubier Can you provide instructions for how to test this change?

**Comment by thiagoteles** [comment]
@shilman Apply the pull request and make: yarn --pnp 

Note: 
1 - The folder node_modules won't be created (or it's need to be empty)
2 - The second time installing storybook dependencies the speed will be 80% faster due a cache strategy of yarn plug and play.

**Comment by naldorp** [comment]
+1

**Comment by evertonalvess** [comment]
+1

**Comment by ndelangen** [comment]
Will this make pnp work for storybook as it's being developed in this monorepo, make it work for users or both?

**Comment by crubier** [comment]
@ndelangen my changes were to make it work to users using storybook in a react project which is part of a monorepo managed with yarn pnp

**Comment by ndelangen** [comment]
Cool! have you been able to verify that it works yet? The list of changes seems to only add dependencies, not really add the plugins/configs? are those implemented somewhere else? Can you explain to me how these changes make it work? I'd expect more changes to be necessary.

We're doing `require.resolve` and `node_modules` path walking in a few places in `lib/core`,   I think.

There's a local registry script in the `yarn bootstrap` command that might help with testing this.

**Comment by crubier** [comment]
@ndelangen as explained in #6899 the additional dependencies are to avoid this issue with pnp:

https://yarnpkg.com/en/docs/pnp/troubleshooting#toc-is-trying-to-require-without-it-being-listed-in-its-dependencies

As for the rest, `require.resolve` is hooked by yarn pnp so that it resolves to the right place, @arcanis can confirm I believe.

Anyway, Yes I tested it an II am using this in my large monorepo as we speak.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
