### PR TITLE
Remove check for sender on channel.

### PR DESCRIPTION
**Pull request by Gongreg**
Issue: Because of check for sender in channels library, it is impossible to communicate between manager and addons.

Right now it is only possible to communicate between 

* addons -> provider
* provider -> manager.

If you want to communicate between manager and addons, you need to send the message from manager to provider and from provider to addons (and vice versa).

What I am afraid about is that I see that this check was added as a separate commit. Could we try to reach @mnmtanish so he could share his knowledge about why he added it in first place?

Also I would really like to get your opinion about this. I thought about adding this check as an opt-out, but @ndelangen feels like we remove the check completely if possible.

## What I did
Removed the sender check.

## How to test
We need to check out that all addons still work. I feel like this can break someones usage.

### CODE REVIEW

**Comment by UsulPro** [comment]
@Gongreg I wonder why do you need to communicate between manager and (panel) addons via the channel? Why you can't use API for that?
I guess we use channel to organize communication with iframe (preview)
Maybe if existing API is not enough we need to add more?

**Comment by ndelangen** [comment]
I think this is perfectly understandable.

I'd like the channel to be the event-bus we can just throw events at, and have either side respond.

Sometimes an event is of interest to both the manager and preview.
Having to send an event on 2 different event-busses to get the actions to happen just doesn't make a lot of sense, right?

**Review by ndelangen — APPROVED** [review]

**Comment by UsulPro** [comment]
is it a breaking change?

**Comment by Gongreg** [comment]
@UsulPro, that I am not sure about. It can be breaking change for users
who were using same name events between manager <-> provider and provider <-> addons.

**Comment by ndelangen** [comment]
I doubt this is a breaking change actually

**Comment by UsulPro** [comment]
I guess ["writing-addons"](https://storybook.js.org/addons/writing-addons/) guide encourage to use the one channel ID for addons.
At least Material-UI addon use the same ID for sending and for listening.
So if I understand right it will be broken.
Not sure about other addons... Do we know how many people use it the same way?

**Comment by Gongreg** [comment]
@UsulPro, do you mean that they use same event name
*addon_name/eventName*
both for communication between manager addons and manager preview?

I mean for it to happen this way they would have to do two emits with same name in different locations.

**Comment by ndelangen** [comment]
Can you please fix the unit test that is failing?

**Comment by Gongreg** [comment]
@ndelangen, looks like it is fixed?

**Comment by shilman** [comment]
@Gongreg do you mind doing a test pass on the addons in `cra-kitchen-sink`?

**Comment by mnmtanish** [comment]
Hi @Gongreg 
We didn't have any special reasons to add the check. It was just part of the design at that time. If you guys think removing the check (event bus approach) will make things simpler, please go ahead. Just check the code where storybook sends/receives messages a bit.

**Comment by ndelangen** [comment]
I did a manual test pass when I approved this @shilman, but I guess example has changed quite a bit, so someone should retest.

Let's get this merged!

**Comment by ndelangen** [comment]
Why is this based on 3.3 btw?

**Comment by Gongreg** [comment]
@ndelangen , I guess @shilman wants me to finish working on my feature for 3.3. :D

**Review by ndelangen — APPROVED** [review]
Tested, works fine!

@UsulPro @tuchk4 If you need help getting your addon compatible, just ask for help on slack, ok?

**Pull request merged**
