### PR TITLE
upgrade vitejs and esbuild

### PR DESCRIPTION
**Pull request by codeisforme**
Issue: #20190 

## What I did

This upgrades the dependencies so that a fresh pull will compile and start. If you have an existing build please clear out all files NOT checked in to the code base (git ignored, including node_modules)

## How to test

- Test yarn start and yarn ci-tests

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by codeisforme** [comment]
@MichaelArestad looks like `react-mdx.stories.mdx` is the deal-breaker, same in other PR's, any thoughts?

**Comment by JReinhold** [comment]
> looks like `react-mdx.stories.mdx` is the deal-breaker, same in other PR's, any thoughts?

I've addressed that in #20210

**Review by JReinhold — CHANGES_REQUESTED** [review]
Could you upgrade `@sveltejs/vite-plugin-svelte` in `svelte-vite` and `@vitejs/plugin-vue` in `vue3-vite` as well?

**Comment by IanVS** [comment]
We discussed in the triage meeting that it would be best to make this PR only upgrade ESBuild.  I'll work on a separate PR to update vite and the associated plugins.

**Comment by codeisforme** [comment]
> We discussed in the triage meeting that it would be best to make this PR only upgrade ESBuild. I'll work on a separate PR to update vite and the associated plugins.

@IanVS I reverted the changes to `@vitejs/plugin-react`. The build won't pass without it, but esbuild is still upgraded to 0.16.4

**Comment by IanVS** [comment]
The failing tests are in svelte.  I wonder if they'll be fixed by https://github.com/storybookjs/storybook/pull/20212, or if something else is going on.

**Comment by JReinhold** [comment]
Pulling in `next` should turn CI green now.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
