### PR TITLE
Update docs to use docgen loader instead of plugin

### PR DESCRIPTION
**Pull request by leandrooriente**
## What I did

Updated documentation to use `react-docgen-typescript-loader` intead of `react-docgen-typescript-plugin`. 

Docgen plugin was deprecated and should be replaced by the custom loader. The plugin slows down storybook development a lot (in our case from 2 minutes to 10 seconds), so it's quite important to remove it from your documentation. 

## How to test

Should I provide a small example of a storybook running with TS and docgen loader?

### CODE REVIEW

**Comment by leandrooriente** [comment]
We also use `cache-loader` in any custom loader that we add to our custom webpack config.
Not sure if you should recommend it, but it improves a lot the build time

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
> We also use cache-loader in any custom loader that we add to our custom webpack config.
Not sure if you should recommend it, but it improves a lot the build time

This PR is good to go, IMHO. But adding a section about cache-loader would be great I think.

**Comment by leandrooriente** [comment]
If I'm not wrong, the next topic already covers it: https://storybook.js.org/configurations/typescript-config/#using-typescript-with-the-tsdocgen-addon

**Comment by Hypnosphi** [comment]
@leandrooriente please resolve conflicts

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
