### PR TITLE
Addon-docs: Scroll story into view

### PR DESCRIPTION
**Pull request by atanasster**
Issue: #7870

## What I did
* added id to InlineStory (IframeStory seemed to already have an id)
* added a `scrollIntoView` by the story id, when the selected story id changes in DocsContainer.

## How to test
This one could be involved and I wasnt sure about all the design decisions (it currently scrolls to end to leave the title visible).

- test iframe stories.
- test mdx/csf stories
- test stories that are at the top /bottom/middle of the screen
- switch docs/preview/other page.
- test current story examples `<Story id="." />`

### CODE REVIEW

**Comment by shilman** [comment]
@atanasster TS error:

```
$ node ../../scripts/prepare.js
src/blocks/DocsContainer.tsx(4,26): error TS7016: Could not find a declaration file for module 'global'. '/tmp/storybook/node_modules/global/window.js' implicitly has an 'any' type.
  Try `npm install @types/global` if it exists or add a new declaration (.d.ts) file containing `declare module 'global';`
```

**Comment by atanasster** [comment]
added `declare module 'global';` - very strange it didn't give me an error at compile time or at linting

**Comment by shilman** [comment]
@atanasster I love your solution to the problem--really clean.

I improved it slightly in the following ways:
- there's now an Anchor prop that wraps the story, which improves the scrolling
- Anchor is super flexible for MDX (e.g. scrolling to a heading)
- If the user doesn't use an Anchor, it falls back to the Story
- Fixed a bug that iframes didn't work in the current PR.

**Review by shilman — APPROVED** [review]
WOOT

**Pull request merged**
