### PR TITLE
Build: Migrate @storybook/postinstall and @storybook/router to strict TS

### PR DESCRIPTION
**Pull request by kuriacka**
Issue https://github.com/storybookjs/storybook/issues/22176

## What I did

Migrate @storybook/postinstall and @storybook/router to strict-ts

## Checklist
- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by kasperpeulen** [comment]
Thanks @kuriacka! 
Can you rebase them on the latest next!

**Review by kasperpeulen — APPROVED** [review]
LGTM!

**Comment by jonniebigodes** [comment]
@kuriacka, one thing left to address as part of this initiative and the amazing work you did by helping us convert Storybook's packages to allow stricter TypeScript support. If you're ok with it, can you message me on our [Discord server](https://discord.gg/storybook) (same username) so that I can follow up with you?


Hope you have a fantastic day.

Stay safe

**Comment by kuriacka** [comment]
@jonniebigodes, I was unable to send you message via Discord. How can I help you?

**Pull request merged**
