### PR TITLE
React: Fix RSC compatibility with addon-themes and hooks

### LINKED ISSUE #26239: [Bug]:  withThemeByClassName decorators breaks any RSC story
### Describe the bug

We are using [this addon](https://storybook.js.org/addons/@storybook/addon-themes) for global themes and it works fine in any component but NextJS Pages(RSC): 
StoryBookDecoratorIssueWithRSC

It breaks only there giving `Storybook preview hooks can only be called inside decorators and story functions.`

### To Reproduce

1. Create a new NextJS project.
2. Setup the addon:
```ts title="main.ts"
import path from "path";

import type { StorybookConfig } from "@storybook/nextjs";

const config: StorybookConfig = {
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-links",
    "@storybook/addon-onboarding",
    "@storybook/addon-storysource",
    "@storybook/addon-themes",
    "storybook-addon-pseudo-states",
    "storybook-addon-rtl",
    "msw-storybook-addon",
  ],
  docs: {
    autodocs: true,
  },
  features: { experimentalRSC: true },
```

```ts title="preview.ts"
const preview: Preview = {
  decorators: [
    withThemeByClassName<ReactRenderer>({
      themes: {
        light: "light-theme",
        dark: "dark-theme",
      },
      defaultTheme: "light",
    }),
  ],
  ```
3. Create a page and its story.
4. Run the project and check it.

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.4 - /usr/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-a11y: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/addon-essentials: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/addon-interactions: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/addon-links: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/addon-onboarding: 1.0.11 => 1.0.11 
    @storybook/addon-storysource: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/addon-themes: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/blocks: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/nextjs: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/react: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/test: ^8.0.0-beta.5 => 8.0.0-beta.6 
    @storybook/theming: ^8.0.0-beta.5 => 8.0.0-beta.6 
    eslint-plugin-storybook: 0.8.0 => 0.8.0 
    msw-storybook-addon: 2.0.0-beta.1 => 2.0.0-beta.1 
    storybook: ^8.0.0-beta.5 => 8.0.0-beta.6 
    storybook-addon-pseudo-states: 2.1.2 => 2.1.2 
    storybook-addon-rtl: 1.0.0 => 1.0.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shilman**
Closes #26239

## What I did

Try applying the workaround described in #24625 to the RSC decorator, which appears to have been written incorrectly.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

@SalahAdDin can you please test out this PR's canary release in your project when it's ready?

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-26243-sha-c7b1761e`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-26243-sha-c7b1761e sandbox` or in an existing project with `npx storybook@0.0.0-pr-26243-sha-c7b1761e upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-26243-sha-c7b1761e`](https://npmjs.com/package/storybook/v/0.0.0-pr-26243-sha-c7b1761e) |
| **Triggered by** | @yannbf |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`26239-rsc-themes-compatibilty`](https://github.com/storybookjs/storybook/tree/26239-rsc-themes-compatibilty) |
| **Commit** | [`c7b1761e`](https://github.com/storybookjs/storybook/commit/c7b1761ed6a6ff1ca529721ae113da0f4d6a8eef) |
| **Datetime** | Thu Dec  5 14:08:16 UTC 2024 (`1733407696`) |
| **Workflow run** | [12181408919](https://github.com/storybookjs/storybook/actions/runs/12181408919) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=26243`_
</details>

## Greptile Summary

This PR modifies the React Server Components (RSC) decorator to fix compatibility issues with addon-themes by adjusting how stories are rendered within the Suspense boundary.

- Modified `code/renderers/react/src/entry-preview-rsc.tsx` to use standard `Addon_DecoratorFunction` type for RSC decorator
- Changed story rendering from component-style (`<Story/>`) to function-style (`story()`) to fix hook-related errors
- Added React version check to ensure RSC compatibility (requires React ≥ 18.3)
- Wrapped story output in `React.Suspense` with proper ReactNode casting

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@shilman For sure I will test it, it is the basic setup for our project.

Thank you!

**Comment by SalahAdDin** [comment]
> Closes #26239
> ## What I did
> 
> Try applying the workaround described in #24625 to the RSC decorator, which appears to have been written incorrectly.
> ## Checklist for Contributors
> ### Testing
> #### The changes in this PR are covered in the following automated tests:
> 
>     * [ ]  stories
> 
>     * [ ]  unit tests
> 
>     * [ ]  integration tests
> 
>     * [ ]  end-to-end tests
> 
> 
> #### Manual testing
> 
> @SalahAdDin can you please test out this PR's canary release in your project when it's ready?
> ### 🦋 Canary release
> 
> This pull request has been released as version `0.0.0-pr-26243-sha-393e9350`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-26243-sha-393e9350 sandbox` or in an existing project with `npx storybook@0.0.0-pr-26243-sha-393e9350 upgrade`.
> More information

Tested, it seems it does not solve the problem:
```bash
Storybook Environment Info:

  System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.4 - /usr/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-a11y: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/addon-essentials: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/addon-interactions: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/addon-links: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/addon-onboarding: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/addon-storysource: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/addon-themes: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/blocks: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/nextjs: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/react: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/test: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    @storybook/theming: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    eslint-plugin-storybook: 0.8.0 => 0.8.0 
    msw-storybook-addon: 2.0.0-beta.1 => 2.0.0-beta.1 
    storybook: 0.0.0-pr-26243-sha-393e9350 => 0.0.0-pr-26243-sha-393e9350 
    storybook-addon-rtl: 1.0.0 => 1.0.0 
```

**Comment by SalahAdDin** [comment]
How is this going on?

**Comment by CHC383** [comment]
Hi, when could we expect this to be merged and released? Using custom decorators with RSC seems to be broken and needs to be fixed by this, otherwise I am getting "Storybook preview hooks can only be called inside decorators and story functions."

**Review by kasperpeulen — APPROVED** [review]

**Pull request merged**
