### PR TITLE
Add copy button for individual story

### PR DESCRIPTION
**Pull request by thollander**
Issue: #6708 

## What I did
Add copy button to get individual story link.

## How to test
There should be a copy button on all stories.

### CODE REVIEW

**Comment by shilman** [comment]
@thollander thanks for adding this! the snapshot tests are currently failing due to the change -- would you mind updating the snapshots with `yarn test --core --update`?

**Comment by thollander** [comment]
@shilman, sure ! thanks for the tip.

**Comment by ndelangen** [comment]
@domyen WDYT?

**Review by ndelangen — APPROVED** [review]
Code looks good to me, would like @domyen design eye on this.

**Comment by ajitbohra** [comment]
Looks good small suggestion would be good to have some visual feedback that link is copied.

**Comment by thollander** [comment]
What kind of visual feedback would you put ? 
Because you already have a visual feedback with the blue focus : 
image

For instance on GitHub, you only have a blue border : 
image

**Comment by domyen** [comment]
lgtm

**Comment by shilman** [comment]
Sneaking this into 5.1

**Comment by ndelangen** [comment]
Thanks for the contribution @thollander !

**Comment by thollander** [comment]
No problem @ndelangen !

**Comment by Hypnosphi** [comment]
@thollander @domyen can we instead make the "Open canvas" a link instead of a button? Then we would get all the benefits of native HTML links, which include:

– Ability to copy the href from context menu
– Ability to open it in new tab or window using context menu or cmd/ctrl/shift+click or mouse wheel click
– Href is displayed in a corner of browser window on hover

**Comment by ndelangen** [comment]
That sounds like a good improvement indeed!

This would merge both use cases into a single piece of UI.
Maybe a tooltip would be in order?

**Pull request merged**
