### PR TITLE
Vite: Update @vitejs/plugin-react to v4.2.0

### PR DESCRIPTION
**Pull request by ryoheinan**
## What I did
This PR updates `@vitejs/plugin-react`, used by `@storybook/react-vite` to 4.2.0 to fix an unmet peer dependency error. (please see below image)

Storybook supports Vite 5 since v7.5, but it seems that `@storybook/react-vite` still uses the old version of `@vitejs/plugin-react` and it does not support Vite 5. So, I updated the library.

See also: https://github.com/vitejs/vite-plugin-react/releases/tag/v4.2.0

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Build `@storybook/react-vite`
2. Create React project with Vite
3. Add `@storybook/react-vite` to the React project as dependency

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks for the PR, @ryoheinan.  The tricky thing is that we need to keep supporting Vite 3 for now, and the version you've updated to in this PR only supports [^4.2.0 || 5](https://github.com/vitejs/vite-plugin-react/blob/3748fc7493cf0a07a2ae275fbd1ae035f01010cc/packages/plugin-react/package.json#L48C31-L48C31).  This package is actually only used by Storybook when the user does not have their own vite config, which is not very often.  

I think that in Storybook 8.0, we will drop support for older versions of Vite, and will be able to update this fallback plugin, so we have changed the target branch to 8.0.  

As a workaround in the meantime, to avoid the peer dependency warning, you can add a resolution/override to your package.json to force only the newer version of `@vitejs/plugin-react` to be installed.  

Thanks again for the PR, and I hope you understand why we can't merge it into 7.0 immediately.  Let us know if you've got any questions.

**Comment by ryoheinan** [comment]
@IanVS 
Oh, I understand.
I should have investigated the changes more...
Anyway, thank you for your time and your detailed response!

**Comment by eddiemonge** [comment]
@IanVS doesn't seem like 8.0.0-alpha has this change in it.

**Comment by IanVS** [comment]
@eddiemonge The first alphas will be mostly the same as 7.6, with more and more changes as we go.  We're discussing a different approach entirely for 8.0, which does not use fallback plugins, so we may not end up merging this PR if we do that.

**Comment by AriPerkkio** [comment]
> The tricky thing is that we need to keep supporting Vite 3 for now, and the version you've updated to in this PR only supports [^4.2.0 || 5](https://github.com/vitejs/vite-plugin-react/blob/3748fc7493cf0a07a2ae275fbd1ae035f01010cc/packages/plugin-react/package.json#L48C31-L48C31).

The currently used version `@vitejs/plugin-react@3.0.1` doesn't support Vite 3 in its `peerDependencies` either: https://github.com/vitejs/vite-plugin-react/blob/d758a2a44b0a2cb3c206fa61166cda9d5cf58221/packages/plugin-react/package.json#L47-L49. Same issue with latest `^3`: https://github.com/vitejs/vite-plugin-react/blob/cda8145b8dc5a7211c0e3f8a253b4cac9c2c3d42/packages/plugin-react/package.json#L48-L50

Is this a real blocker then?

**Comment by skratchdot** [comment]
I'd like to see this pr get merged as well. We might want to update `code/package.json` as well (see: https://github.com/storybookjs/storybook/pull/25078/files)?

**Comment by kasperpeulen** [comment]
We think it is better to remove the dependency, see this PR:
https://github.com/storybookjs/storybook/pull/25427

This means that users have to add the `@vitejs/plugin-react` their vite config.
In some cases, users might not have a vite config, so it is breaking change, but it seems like the best way to solve this kind of issues long term, and as vite is really easy to configure, probably not a big of a deal for most users.

**Pull request closed without merging**
