### PR TITLE
Extract channels store

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: #4063

## What I did
I've extracted ChannelsStore out of the AddonsStore

### CODE REVIEW

**Comment by Gongreg** [comment]
I am afraid this will not help when we start using addons inside react native.
I would like to reuse same addon logic, that means I need to import @storybook/addons inside react-native code.

Is it really necessary to have UI code inside addons? Couldn't it be moved somewhere to keep addons without UI code?

**Comment by igor-dv** [comment]
CC @ndelangen 

There is a `TabWrapper` that was added for performance optimization. Maybe we can refactor it to have a RnTabWrapper for rn usage...

**Comment by igor-dv** [comment]
BTW, we need to fix this to v4 anyway

**Comment by Gongreg** [comment]
@igor-dv I will be talking with @ndelangen soon. I will also try to talk about this issue.

**Comment by Gongreg** [comment]
Hey @igor-dv,
What we've decided to do is to remove that check for legacy addons from this module.

It will be moved somewhere into /lib/ui.

So for now only these lines should be removed.
https://github.com/storybooks/storybook/blob/master/lib/addons/src/index.js#L56-L62

This will solve the blocker and reimplementing the check in ui can be a separate task.

Will you update the PR or should I create a new one?

**Comment by igor-dv** [comment]
> Will you update the PR or should I create a new one? 

I can finish it later, or if you want you can create a new one. I think we need to fix it asap. at least for the next alpha. So if you have time, it will be great.

**Comment by Gongreg** [comment]
@igor-dv Do we still want to extract the channels?

**Comment by igor-dv** [comment]
Nope =) at least not now.

**Comment by igor-dv** [comment]
If our twitter could to make it public that'd be great 😆

**Pull request closed without merging**
