### PR TITLE
add stylesheet to inline children rendering

### PR DESCRIPTION
**Pull request by davemcorwin**
Issue:

## What I did

Added children styles to the div that contains the story content when rendering inline.

## How to test
Provide configuration like the following to`addWithInfo()` or globally:
```
{
  inline: true,
  styles: stylesheet => {
    stylesheet.children = {
      textAlign: 'center',
      border: '1px dashed #beeed2',
      padding: '16px',
      background: '#fafdfb'
    }
    return stylesheet
  }
}
```

### CODE REVIEW

**Comment by ndelangen** [comment]
@shilman does this make sense considering #1147 ?

**Comment by shilman** [comment]
@ndelangen I don't think so, but I'm not positive. Actually @UsulPro is going to implement #1147 (#1452 was a warmup to that), so he'd be the best person to review this.

**Comment by davemcorwin** [comment]
@shilman @ndelangen Thanks for looking into this. My 2 cents is that it depends on the implementation. If #1147 will remove the inline option, than its moot and can be dropped. If the inline option remains, then the goal is to be able to decorate the stories, but not the info. I haven't checked yet, but if #1452 takes care of this, then we can definitely drop this PR, otherwise, its a small change that may bridge the gap until better solutions come along.

**Comment by ndelangen** [comment]
Sounds like we need @UsulPro to pitch in here! 🙇

**Comment by ndelangen** [comment]
This change/PR is now redundant with changes made in `3.2.0` branch (which is now merged to master)

Thank you @davemcorwin for contributing! I hope to see another PR from you in the future.
Sorry this change was overtaken somewhere else.

**Comment by davemcorwin** [comment]
No worries! glad its no longer necessary!




On July 28, 2017 at 5:59:47 AM, Norbert de Langen (notifications@github.com)
wrote:

This change/PR is now redundant with changes made in 3.2.0 branch (which is
now merged to master)

Thank you @davemcorwin <https://github.com/davemcorwin> for contributing! I
hope to see another PR from you in the future.
Sorry this change was overtaken somewhere else.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/storybooks/storybook/pull/1431#issuecomment-318623993>,
or mute the thread

**Pull request closed without merging**
