### PR TITLE
links should navigate in the parent window

### LINKED ISSUE #1122: Link to external site would navigate preview iframe with no way to reset
For a story that has a link to an external site, if the user clicks and navigates to the site, there's no way to return the preview iframe back except to refresh the page.

Story:
```
<a href="https://www.google.com">Click here to be banished forever!</a>
or 
<a href="/somewhere/far/far/away">Click here to get lost!</a>
```

Discovered this bug while playing with Lonely Planet's Storybook:
https://github.com/lonelyplanet/backpack-ui

I think we can fix it by detecting the location of the iframe when navigating to a new story and reload the entire iframe if it's in the wrong place.

### PR DESCRIPTION
**Pull request by blairanderson**
## Issue:
fixes #1122

## What I did
I found that creating normal `<a target="_blank" href="https://www.google.com">foo</a>` links inside of a story would update the iframe and not actually take the user out to the external link

`<base>`tag is supported by all browsers https://stackoverflow.com/a/2656798/1536309 

## How to test

before: 
add a link to a component and click on it. 
`<a href="https://www.google.com">google</a>`
will only update the iframe

after: 
link moves on the parent window.

### CODE REVIEW

**Comment by blairanderson** [comment]
fyi users can temporarily fix with using their own head tags:

https://storybook.js.org/configurations/add-custom-head-tags/

**Comment by Hypnosphi** [comment]
Good fix! Please update it in [`app/vue`](https://github.com/storybooks/storybook/blob/master/app/vue/src/server/iframe.html.js) as well

**Review by danielduan — CHANGES_REQUESTED** [review]
If you can update `app/vue`, think we're good to merge. Thanks for fixing!

**Comment by blairanderson** [comment]
@danielduan I updated `app/vue` file as well 👍

**Review by danielduan — APPROVED** [review]

**Pull request merged**
