### PR TITLE
Modified the Knobs onChange debounce function so that knob storage occurs on keypress but rendering waits until debouncing has completed

### PR DESCRIPTION
**Pull request by CodeByAlex**
Issue: #6005

## What I did
Modified the component force render debounce so that knob storage still occurs on keypress but the force rendering is debounced. In the 5.0.1 version, the debouncing rate is 150ms which is a little faster than the average typing speed. The change in this PR sets the debouncing rate at 325ms so that the component renders when the user has completed their thought. Frameworks render at different speeds and waiting longer reduces glitchiness. I tested this change in the CLI project to ensure that characters were not being removed as seen in Vue projects.

*I chose 325ms because I felt that it was long enough to reduce glitchiness but not too long to cause frustration. If people believe that this time is too long or too short, please comment below so that we can resolve before merging this in. 

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

@shilman @kristremblay @kylepeeler

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by kristremblay** [comment]
@shilman When upgrading to the most recent commit, I get the following error when clicking on the Knobs tab:
````
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    in Unknown (created by Context.Consumer)
    in Styled(Component) (created by KnobPanel)
    in KnobPanel
    in div (created by Context.Consumer)
    in Styled(div)
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Context.Consumer)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout) (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root

**Comment by kristremblay** [comment]
For now the only version working correctly for me is 5.0.0.

**Comment by CodeByAlex** [comment]
@kristremblay, when you say latest commit, do you mean the most recent published @next version - 5.1.0-alpha.4?

**Comment by kristremblay** [comment]
@CodeByAlex Sorry, yes,.

After installing `5.1.0-alpha.4` it breaks when clicking the Knobs tab.

**Comment by CodeByAlex** [comment]
No worries @kristremblay. This pr hasn’t been published yet even though it has been merged into the next branch. If you are seeing new errors popping up when upgrading to alpha.4, I would suggest that you open a new issue with your finding. Thanks for your feedback:) This PR will be published soon and should help with the original issue you brought up.

**Comment by kristremblay** [comment]
Thanks, @CodeByAlex , for the time being I'll probably just stick with 5.0.0 and upgrade later :)

**Comment by FrankiePo** [comment]
Can we add global configuration for debounce time?

**Pull request merged**
