### PR TITLE
Addon: Interactions - include the source of jest-mock

### LINKED ISSUE #23570: [Bug]: Storybook 7.1 interactions addon fails to build with Yarn PnP
### Describe the bug

Storybook 7.1 introduces an issue when trying to build and start Storybook with Webpack using Yarn PnP. The output of running `yarn build-storybook` is this:

```
@storybook/cli v7.2.0-alpha.0

info => Cleaning outputDir: \storybook-static
info => Loading presets
info => Building manager..
info => Manager built (1.88 s)
info => Compiling preview..
info => Copying static files: C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\@storybook-manager-npm-7.2.0-alpha.0-2ad5c945fc-3e08d89dd1.zip\node_modules\@storybook\manager\static at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\storybook-static\sb-common-assets
info Addon-docs: using MDX2
info => Using implicit CSS loaders
info => Using default Webpack5 setup
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve 'url' in 'C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\jest-util-npm-29.6.1-b316c3a23f-fc553556c1.zip\node_modules\jest-util\build'
ERR!
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR!
ERR! If you want to include a polyfill, you need to:
ERR!    - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
ERR!    - install 'url'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR!    resolve.fallback: { "url": false }
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve 'url' in 'C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\jest-util-npm-29.6.1-b316c3a23f-fc553556c1.zip\node_modules\jest-util\build'
ERR!
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR!
ERR! If you want to include a polyfill, you need to:
ERR!    - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
ERR!    - install 'url'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR!    resolve.fallback: { "url": false }
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\Compilation.js:2022:28
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:817:13
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:275:22
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:448:22
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:118:11
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:689:25
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:893:8
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\neo-async-npm-2.6.2-75d6902586-deac9f8d00.zip\node_modules\neo-async\async.js:6883:13
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:996:45
ERR!     at finishWithoutResolve (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:372:11)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:461:15
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\forEachBail.js:39:13
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\AliasPlugin.js:148:14
ERR!     at next (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\forEachBail.js:35:3)
ERR!     at forEachBail (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\forEachBail.js:49:9)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\AliasPlugin.js:61:5
ERR!     at _next0 (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:41:15
ERR!     at processTicksAndRejections (node:internal/process/task_queues:81:21)
ERR!     at runNextTicks (node:internal/process/task_queues:64:3)
ERR!     at process.processImmediate (node:internal/timers:442:9)
ERR!  ModuleNotFoundError: Module not found: Error: Can't resolve 'url' in 'C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\jest-util-npm-29.6.1-b316c3a23f-fc553556c1.zip\node_modules\jest-util\build'
ERR!
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR!
ERR! If you want to include a polyfill, you need to:
ERR!    - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
ERR!    - install 'url'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR!    resolve.fallback: { "url": false }
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\Compilation.js:2022:28
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:817:13
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:275:22
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:448:22
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:118:11
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:689:25
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:893:8
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\neo-async-npm-2.6.2-75d6902586-deac9f8d00.zip\node_modules\neo-async\async.js:6883:13
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\__virtual__\webpack-virtual-19f90b1b2e\0\cache\webpack-npm-5.88.2-38717ace6f-79476a782d.zip\node_modules\webpack\lib\NormalModuleFactory.js:996:45
ERR!     at finishWithoutResolve (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:372:11)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:461:15
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\forEachBail.js:39:13
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\AliasPlugin.js:148:14
ERR!     at next (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\forEachBail.js:35:3)
ERR!     at forEachBail (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\forEachBail.js:49:9)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\AliasPlugin.js:61:5
ERR!     at _next0 (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\Resolver.js:519:5
ERR!     at eval (eval at create (C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\enhanced-resolve-npm-5.15.0-16eb7ddef9-fbd8cdc926.zip\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:41:15
ERR!     at processTicksAndRejections (node:internal/process/task_queues:81:21)
ERR!     at runNextTicks (node:internal/process/task_queues:64:3)
ERR!     at process.processImmediate (node:internal/timers:442:9)
ERR! resolve 'url' in 'C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\jest-util-npm-29.6.1-b316c3a23f-fc553556c1.zip\node_modules\jest-util\build'
ERR!   Parsed request is a module
ERR!   using description file: C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\jest-util-npm-29.6.1-b316c3a23f-fc553556c1.zip\node_modules\jest-util\package.json (relative path: ./build)
ERR!     Field 'browser' doesn't contain a valid alias configuration
ERR!     resolve as module
ERR!       request is not managed by the pnpapi
ERR!         jest-util tried to access url. While this module is usually interpreted as a Node builtin, your resolver is running inside a non-Node resolution context where such builtins are ignored. Since url isn't otherwise declared in jest-util's dependencies, this makes the require call ambiguous and unsound.
ERR!         Required package: url
ERR!         Required by: C:\Users\nbier\Documents\storybook-7-1-yarn-pnp\.yarn\cache\jest-util-npm-29.6.1-b316c3a23f-fc553556c1.zip\node_modules\jest-util\build\
√ Would you like to help improve Storybook by sending anonymous crash reports? ... no

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry
```

### To Reproduce

https://github.com/Methuselah96/storybook-7-1-yarn-pnp

Starting from a fresh Storybook, steps to reproduce are:

1. `yarn set version stable` (to use Yarn PnP)
2. `yarn install`
3. `yarn build-storybook`
4. Observe error

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
```

### Additional context

Looks to be the same root issue as https://github.com/storybookjs/storybook/issues/23557, in my opinion closed too early. It should be safe for Storybook to be hoisted and is a sign of a deeper issue.

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/23570

## What I did

I copied the source code of `jest-mock` into the source code of addon interactions.
I did this because `jest-mock` depends on `jest-util`. Both these packages are compiled to CJS. That cannot be treeshaken, which causes the dependencies for (unused code-paths) in `jest-util` to be included in the browser bundle.

## How to test

- Maybe we can use the canary release process and ask the issue-reporter to test on their reproduction repo

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This pull request has been released as version [`7.2.0-canary-23593-1690276507-975d4e05.0`](https://npmjs.com/package/@storybook/cli/v/7.2.0-canary-23593-1690276507-975d4e05.0). Install it by pinning all your Storybook dependencies to that version.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`7.2.0-canary-23593-1690276507-975d4e05.0`](https://npmjs.com/package/@storybook/cli/v/7.2.0-canary-23593-1690276507-975d4e05.0) |
| **Triggered by** | @ndelangen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/jest-mock-included`](https://github.com/storybookjs/storybook/tree/norbert/jest-mock-included) |
| **Commit** | [`975d4e05`](https://github.com/storybookjs/storybook/commit/975d4e0513a3a69fc099d3b041c242e976d530c5) |
| **Datetime** | Tue Jul 25 09:15:07 UTC 2023 (`1690276507`) |
| **Workflow run** | [5654913774](https://github.com/storybookjs/storybook/actions/runs/5654913774) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=23593`_
</details>

### CODE REVIEW

**Comment by ndelangen** [comment]
@Methuselah96 would you be willing to assist verifying if this PR resolves the issue your reported?

I've triggered a canary release, it should appear soon allowing you to test this.

**Comment by Methuselah96** [comment]
@ndelangen Looks like you went with just downgrading `jest-mock` in https://github.com/storybookjs/storybook/pull/23597 instead? Let me know if you still want me to test.

**Comment by ndelangen** [comment]
Yes, though I'm not happy with that route. I'd love to know if this solution actually worked, so if you wouldn't mind testing it that would be 🙏

**Comment by Methuselah96** [comment]
Makes sense. I tested this and it seems to fix the issue for me.

**Pull request closed without merging**
