### PR TITLE
Addon-knobs: Fix search params with URI encoding

### LINKED ISSUE #11641: Knobs: Wrong URI-encoding in torn-away iframe
**Describe the bug**
The torn-away `<iframe>` with a knob value changed has wrong URI-encoding, not properly escaping `%` character.

**To Reproduce**
1. Clone https://github.com/asudoh/storybook-knobs-test
2. `yarn install`
3. `yarn storybook`
4. Open http://localhost:6006/?path=/story/button--emoji
5. Replace `aria-label` knob content with `10% 20% 30%`
6. Click on torn-away button (An icon with square with up arrow)
7. Inspect `aria-label` in `<span role="img">` with DOM inspector

BUG: `aria-label` shows `10%%2020%%2030%`.

**Expected behavior**

1. The `aria-label` shows `10% 20% 30%`.
2. The URL shows `http://localhost:6006/iframe.html?id=button--emoji&knob-aria-label=10%25%2020%25%2030%25` (`aria-label` having `encodeURIComponent('10% 20% 30%')`) instead of `10%%2020%%2030%`

**Screenshots**
image
image

**System:**
Got below unfortunately:

```
> npx -p @storybook/cli@next sb info

Environment Info:
(node:85942) UnhandledPromiseRejectionWarning: TypeError: e.filter is not a function
...
```

But hope above provides enough info.

### PR DESCRIPTION
**Pull request by asudoh**
Issue: #11641

## What I did

This change applies basic URI encoding to knob keys/values in `<iframe>` URL and torn-away window URL in preview.

## How to test

Use the newly added Knobs - withKnobs - With Knob Value To Be Encoded story in `examples/official-storybook`, put `10% 20% 30%` to the knob value, click on torn-away icon (icon with square and up arrow), and see if the content is right.

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks for the fix + test @asudoh. I think maybe we should use the built in [`querystring`](https://nodejs.org/api/querystring.html) library for this stuff?

**Comment by asudoh** [comment]
Thank you for your feedback @tmeasday! I had an impression that the offending code runs in browser as supposed to in node.js and thus chose browser-native `encodeURIComponent` API, but please correct me if I'm wrong here.

**Comment by asudoh** [comment]
BTW I'm open for [`URLSearchPatams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) polyfill if it's more desirable.

**Comment by shilman** [comment]
I think @tmeasday means `qs`, which we use here:

https://github.com/storybookjs/storybook/blob/next/lib/router/src/utils.ts#L43

**Comment by asudoh** [comment]
Thanks @shilman for clarifying, updated.

**Comment by shilman** [comment]
Hmm, I tried to test it on the deploy preview, editing the "Name" knob to "Storyteller 10%":

https://deploy-preview-11642--storybookjs.netlify.app/official-storybook/?path=/story/addons-knobs-withknobs--tweaks-static-values

But the behavior seems to be identical to the Next branch:

https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-knobs-withknobs--tweaks-static-values

Any idea what could be going on @asudoh?

**Comment by asudoh** [comment]
@shilman The problem happens _only_ in town-away `<iframe>`. You can see the problem at: https://next--storybookjs.netlify.app/official-storybook/iframe.html?id=addons-knobs-withknobs--tweaks-static-values&knob-Name=Storyteller%252010%25%252020%25%252030%25&knob-Age=70&knob-Fruit=apple&knob-Other%20Fruit=watermelon&knob-Dollars=12.5&knob-Years%20in%20NY=9&knob-background=&viewMode=story

**Comment by shilman** [comment]
Cool, thanks for the clarification!

**Review by shilman — APPROVED** [review]
LGTM 😻

**Pull request merged**
