### PR TITLE
Loosen puppeteer dependencies to allow last major version

### PR DESCRIPTION
**Pull request by vmalay**
Issue: Pupeteer version used by storyshots is very old. It is 6 major updates late. Following https://github.com/storybookjs/storybook/issues/15079

## What I did
I updated the puppeteer version to the last major version in the package.json for @storybook/storyshots-puppeteer. 

## How to test

- Is this testable with Jest or Chromatic screenshots? No.
- Does this need a new example in the kitchen sink apps? 
- Does this need an update to the documentation? No.

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Since puppeteer is a peer dependency, can we accept the range of compatible versions? This change forces any project that uses it to upgrade, but I think that's more disruptive than it needs to be. WDYT?

**Comment by vmalay** [comment]
Yes you're right @shilman , I've updated the PR !

**Review by shilman — APPROVED** [review]
LGTM. Also upgraded the monorepo and tested with:

```
cd examples/official-storybook
yarn storyshots-puppeteer
```

**Comment by vmalay** [comment]
PR has been reverted. New PR: https://github.com/storybookjs/storybook/pull/15163

**Pull request merged**
