### PR TITLE
Bugfix - Addons relative path

### PR DESCRIPTION
**Pull request by RuneKR**
Issue: https://github.com/storybookjs/storybook/issues/9343

## What I did
Editing the presets function to allow local addons to be included in main.js

## How to test
Current function is not tested in existing unit tests as the function is only indirectly exposed.
Test the functionality by adding an addon to main.js like the following:
```
require.resolve('../packages/node_modules/@my/addon/dist/register')
```

### CODE REVIEW

**Comment by shilman** [comment]
Thanks @RuneKR! Can you add at least one test to `presets.test.js` to show how this works?

**Comment by RuneKR** [comment]
Sure thing! :)

**Comment by RuneKR** [comment]
Added test - Mocked the files so really only testing if MacOS is supported. I could create actual mock files, but that would then just test the OS on which the test is run anyway. Looked at current code and this example for my tests: 'https://jestjs.io/docs/en/manual-mocks'

**Review by MylesArkell — APPROVED** [review]

**Comment by shilman** [comment]
Closing this in favor of https://github.com/storybookjs/storybook/pull/9485, which I think is a simpler and more correct fix/test. Thanks so much for getting to the bottom of this!!!

**Pull request closed without merging**
