### PR TITLE
documentation: improved jest configuration of stories

### PR DESCRIPTION
**Pull request by silversonicaxel**
Set to `string` when `string[]` is not necessary

Issue:

## What I did

Improved documentation

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [x] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Thanks for this @silversonicaxel! Can you please target your PR to the `next` branch instead of main? Many thanks.

**Comment by silversonicaxel** [comment]
@shilman no problem. done!

**Comment by kylegach** [comment]
Hello, @silversonicaxel. Thank you for responding to `@shilman`'s request. Unfortunately, it looks like that resulted in a lot of unrelated changes in this PR, which makes it very difficult to review. I believe the problem is that while you're targeting the `next` branch here in the PR, your local branch was based on `main`. So, to resolve:

1. Create a new local branch, from `next`
1. [cherry-pick](https://git-scm.com/docs/git-cherry-pick) your changes onto that branch
1. Close this PR and submit a new one for the new branch

Thanks!

**Comment by silversonicaxel** [comment]
@kylegach done, here is the new PR -> https://github.com/storybookjs/storybook/pull/17009 
and now I close this PR

**Pull request closed without merging**
