### PR TITLE
Test: Fix user event being inlined by tsup by using an interface

### LINKED ISSUE #25258: [Bug]: `@storybook/test` exports `any` types for `userEvent`
### Describe the bug

In v8, all the types for `userEvent` from `@storybook/test` are typed as `any` instead of keeping/wrapping the `@testing-library/user-event` types during instrumentation.

`@storybook/test`:
image

`@testing-library/user-event`:
image

### To Reproduce

on a codebase that implements the `@typescript-eslint/no-unsafe-call` lint rule, upgrade from `@storybook/jest` and `@storybook/testing-library` to use `@storybook/test` instead.  notice all the new eslint errors:
```
error  Unsafe call of an `any` typed value  @typescript-eslint/no-unsafe-call
```
due to `userEvent`

### System

```bash
➜ npx storybook@latest info

Storybook Environment Info:

  System:
    OS: macOS 14.2
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v18.18.2/bin/npm <----- active
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.2
  npmPackages:
    @storybook/addon-a11y: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/addon-coverage: ^1.0.0 => 1.0.0
    @storybook/addon-essentials: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/addon-interactions: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/addon-links: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/blocks: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/nextjs: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/react: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/test: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    @storybook/test-runner: ^0.16.1--canary.c6e45e4.0 => 0.16.1--canary.c6e45e4.0
    eslint-plugin-storybook: ^0.6.15 => 0.6.15
    storybook: ^8.0.0-alpha.3 => 8.0.0-alpha.3
    storybook-addon-rtl: ^0.5.0 => 0.5.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kasperpeulen**
Fixes https://github.com/storybookjs/storybook/issues/25258

## What I did

Fix user event being inlined by tsup by using an interface

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by skratchdot** [comment]
@kasperpeulen - i had to manually override the version of userEvent my repo is using for these changes to take effect. I'm not sure why.

I am using `8.0.0-alpha.10`, and I need:
```
  "pnpm": {
    "overrides": {
      "@testing-library/user-event": "^14.5.2"
    }
  }
```

or else I see errors like:
```
 error  Unsafe call of an `any` typed value  @typescript-eslint/no-unsafe-call
```

So I see errors with this:
```
@storybook/test 8.0.0-alpha.10
└── @testing-library/user-event 14.3.0
```

But no errors with:
```
@storybook/test 8.0.0-alpha.10
└── @testing-library/user-event 14.5.2
```

I think we downgraded and pinned userEvent here:
https://github.com/storybookjs/storybook/pull/25004

I use firefox as my primary browser and haven't ran into that issue (that I'm aware of).

Any chance we can update the whole repo so every `userEvent` is using:
```
"@testing-library/user-event": "^14.5.2"
```

I can submit a PR for that if we are okay with it.

**Comment by IanVS** [comment]
FWIW several of my stories also broke when upgrading from 7.6.0 to 7.6.1, and I tried overriding the version of `user-event` in my package.json but of course I couldn't because it's pre-bundled.  :(

**Comment by tmeasday** [comment]
@kasperpeulen is there a workaround for FF users by tweaking their play function or similar?

**Comment by kasperpeulen** [comment]
I belief there are some workarounds indeed, but it is not pretty:
https://github.com/testing-library/user-event/issues/1075#issuecomment-1814578287

Shall I try to make a canary, and see if I can make a workaround for all the issues we found in our internal codebases, and see if the workaround is acceptable? cc @shilman

**Comment by shilman** [comment]
@kasperpeulen SGTM

**Comment by kasperpeulen** [comment]
@shilman @vanessayuenn added it to the storybook 8.0 project:
https://github.com/storybookjs/storybook/issues/25853

**Pull request merged**
