### PR TITLE
Update Angular tests

### PR DESCRIPTION
**Pull request by Marklb**
Update cli init generator.
Remove deprecated support for projects not using builder.

Issue:

## What I did

Updated Angular tests, so they can be added back to CI tests.

This also adds two changes that probably should have been separate PRs, but some of the problematic tests were going to be stripped out when support for using Angular without a builder was dropped. I went ahead and made those changes here, but I can revert that and just exclude those tests in this PR if needed.

Since this drops support for using Angular without a builder, this is a breaking change. I updated the init generator, but did not try to add a migration yet.

Can someone more familiar with the ArgTypes changes help with what the expected results should be in `frameworks/angular/src/client/docs/compodoc.test.ts` for the failing tests.

Since the Angular builder takes care of reading most of the workspace files, I dropped most of the tests in `frameworks/angular/src/server/framework-preset-angular-cli.test.ts`. I am trying to decide if I dropped to much or should change or add to what is now there.

I added a dependency (`jju`) for updating a json5 file, since `angular.json` can have comments. If there is already a function or dependency for that in the monorepo that I missed then I can switch that.

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ndelangen** [comment]
@Marklb can you update this branch with `next` please? It'd be awesome to move this forwards, don't you think?

**Comment by Marklb** [comment]
@ndelangen I merged `next` and all the Angular tests should be passing now.

Can someone to confirm that I fixed the tests `compodoc.test.ts extractType with compodoc type []`, `compodoc.test.ts extractType with compodoc type EnumNumeric`, `compodoc.test.ts extractType with compodoc type EnumNumericInitial`, `compodoc.test.ts extractType with compodoc type foo`, and `compodoc.test.ts extractType with compodoc type T[]` correctly? I am not too familiar with Storybook's ArgTypes, so I am not positive is my change to make the tests pass is how it should have been done.

Most of my change to the cli will be overwritten by #20559. This is a smaller change, as far as non-test specific breaking changes, so it may be better to merge this one first and have the Angular tests enabled.

**Comment by Marklb** [comment]
@ndelangen The tests changes are the only important part from this. I had implemented a minimal version on the initial generator changes, so I could drop those tests, but that will be replaced by the other PR.

The only part on this PR's init generator change that I think should be preserved is modifying `angular.json` as json5 to avoid losing comments or formatting.

**Comment by valentinpalkovic** [comment]
@ndelangen The tests of this PR were failing, and because my PR is ready to merge, I wanted to test out how enabled tests behave on my PR. I wanted to go one step further to avoid being blocked and wait for this PR to merge. And some adjustments were also necessary, which depended on some refactorings I made.

**Comment by Marklb** [comment]
If we want to just handle the test changes in the other PR I can take a look through it and see if I notice anything missing then close this one.

**Comment by Marklb** [comment]
The main parts of this PR have already been done by other PR's. I will submit another, if I want to add anything that is still missing.

**Pull request closed without merging**
