### PR TITLE
Composition: Filter out disabled refs in getAutoRefs

### PR DESCRIPTION
**Pull request by g1eny0ung**
Issue:

If some packages don‘t export `package.json`, start storybook will warn:

image

## What I did

I think to solve this problem we can define these packages in the `refs` and set it as disabled in `.storybook/main.js`, like:

```js
refs: {
  rollup: { disable: true },
  '@rollup/plugin-node-resolve': { disable: true },
}
```

Then filter out the disabled refs in `getAutoRefs` func. Also, the changed code will reduce the extra disabled refs check than the previous code.

I'm not sure if this is correct or reasonable, please help me point out if there is an error, thx. 😃

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Hi @shilman, is there any progress on this PR?

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by ndelangen** [comment]
it's possible for an npm package to not contain a package.json?!?!

**Comment by g1eny0ung** [comment]
> it's possible for an npm package to not contain a package.json?!?!

@ndelangen They actually have the package.json. The reason I guess is both `rollup` and `@rollup/plugin-node-resolve` defined the `exports` field to limit the scope of resolve.

**Review by ndelangen — APPROVED** [review]

**Comment by g1eny0ung** [comment]
@shilman @ndelangen I noticed the latest changes use typescript and I have already resolved the conflicts. Please check again.

**Pull request merged**
