### PR TITLE
DocsPage: Add subcomponents parameter

### PR DESCRIPTION
**Pull request by enagy27**
Issue: #7811 

## What I did
Added `subcomponents` parameter to `DocsPage` to allow named props tables

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes, TODO
- Does this need a new example in the kitchen sink apps? Yes, TODO
- Does this need an update to the documentation? Yes, TODO

### CODE REVIEW

**Comment by shilman** [comment]
@domyen @enagy27 So I tried this out in a simple example and realized that it needs some design. Here's what the simple example looks like:

Addons___Docs___ButtonGroup_-_Basic_⋅_Storybook

And here's a real-world example from https://github.com/evergarden-ui/evergarden/pull/6 that I think is pretty representative. This `Alert` component also has `AlertIcon`, `AlertTitle`, `AlertDescription` subcomponents which are not currently shown:

Alert_-_Defaults_⋅_Storybook

**Comment by patricklafrance** [comment]
@shilman here's how we solved this problem in our design system:

sb-sub-components

The code is available here:

https://github.com/gsoft-inc/sg-orbit/tree/storybook-docs/storybook/stories/components/props-tabs

https://raw.githubusercontent.com/gsoft-inc/sg-orbit/storybook-docs/packages/react-components/components/date-picker/stories/date-range-picker.stories.mdx

**Comment by shilman** [comment]
@enagy27 This ended up getting fixed in #8855, so I'm going to close this. Thanks so much for taking the initiative on this -- I'll include your work in the release post, even tho the code itself didn't make it in!

**Comment by enagy27** [comment]
@shilman sounds great! I’m just glad to have it, thanks for the heads up 😄

**Pull request closed without merging**
