### PR TITLE
Controls: Fix grouped Radio controls to have the same name

### PR DESCRIPTION
**Pull request by srapilly**
# Closes #

no existing issue

## What I did

Each radio control in the same group should have the same name. This fix the keyboard behavior, it was not possible to changes radio with the arrow keys. This will also group them for screen reader users.

image

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Open Storybook in your browser
3. Access a args table from a story (
4. Try to changes a radio control with arrow keys

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by srapilly** [comment]
I didn't add any test for now, I don't think you have component test ?

**Review by cdedreuille — APPROVED** [review]
LGTM!

**Review by JReinhold — APPROVED** [review]
Great idea. ❤️

**Comment by srapilly** [comment]
Thanks for the merge, I had completely forgotten this PR :)

**Pull request merged**
