### PR TITLE
Add option to pass custom styles for angular components

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: https://github.com/storybooks/storybook/issues/2616#issuecomment-361004910

## What I did

Added an option to provide custom styles for angular components. Works only with templates becasue "dynamic component" is generated only for the templates now: 

```js
storiesOf('Custom Style', module).add('Default', () => ({
  template: `<storybook-button-component [text]="text" (onClick)="onClick($event)"></storybook-button-component>`,
  moduleMetadata: {
    declarations: [Button],
  },
  props: {
    text: 'Button with custom styles',
    onClick: action('log'),
  },
  styles: [
    `
    storybook-button-component {
      background-color: yellow;
      padding: 25px;
    }
  `,
  ],
}));
```

---
This change is [Reviewable](https://reviewable.io/reviews/storybooks/storybook/2856)

### CODE REVIEW

**Comment by alterx** [comment]
Just a thought, are we sure we don't want this as an add-on?
I mean, is there a similar way to achieve this in the other apps (vue, react, polymer?)

**Comment by igor-dv** [comment]
🤷‍♂️  I don't know... Can we achieve the same behavior for all the apps with custom styles?

**Comment by alterx** [comment]
Dunno, I was just thinking out loud here. I guess if, for example, someone is using react and css-in-js then we wouldn't be able to, but if they're using regular css we could.

Anyway, if we want we can reuse most of this code to create an add-on later on. This LGTM :)

**Comment by igor-dv** [comment]
@alterx , would you mind to accept? 😏

**Review by alterx — APPROVED** [review]

**Comment by alterx** [comment]
Of course, good sir. There you go 🎉

**Pull request merged**
