### PR TITLE
[Addon Storysource] Add auto scrolling to the selected story

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: When selecting a story, panel should be scrolled to a selected area in code

## What I did

Added an auto-scrolling

### CODE REVIEW

**Comment by igor-dv** [comment]
If storysource addon will be merged to 3.3, I assume this one is also might be

**Comment by Hypnosphi** [comment]
Ok let's wait what @shilman says

**Review by Hypnosphi — APPROVED** [review]

**Comment by igor-dv** [comment]
@Hypnosphi , I've added a delay for 2 secs there. Is it still needed after your #3027 ?

**Comment by Hypnosphi** [comment]
No, #3027 should replace it

**Pull request merged**
