### PR TITLE
Bump react-syntax-highlighter to 13.2.1

### PR DESCRIPTION
**Pull request by Naturalclar**
Issue: #11890

there was new security alert for prismjs, which react-syntax-highlighter was using.

## What I did

bumped react-syntax-highlighter to 13.2.1 to address security alert for prismjs.

it's a change in major version, but the only breaking change is `dracula` theme being changed to `darcula`

https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

n/a

### CODE REVIEW

**Comment by stof** [comment]
it would be great to finish this, merge it and release it.
Btw, would it make sense to backport that to the 5.x version as it fixes a security issue in the dependencies ?

**Comment by brayfe** [comment]
+1 for backporting this fix to the 5.x version.  Would love to keep dependencies up to date with Storybook!

**Comment by fernandopasik** [comment]
Looks like several CI tasks are failing, would you mind update to latest next branch?

Also react-syntax-highlighter has release a few more times up to 13.4.0.

**Comment by fernandopasik** [comment]
Please could you also update it in https://github.com/storybookjs/storybook/blob/next/addons/storysource/package.json#L45

**Comment by Naturalclar** [comment]
@fernandopasik thanks for the comment!
I've pulled the latest `next` branch and updated dependency

**Review by fernandopasik — APPROVED** [review]
LGTM, maybe @shilman would like to have a look too.

**Review by shilman — CHANGES_REQUESTED** [review]
Looks like there are definitely some breaking changes to deal with before we can merge. @Naturalclar are you able to access the Chromatic diffs linked below? cc @ndelangen 

Reviewing_Build_18423_•_storybookjs_storybook

**Comment by ndelangen** [comment]
Seems the syntax parsing works great, the theme changed a bit, but we can fix that. I did some quick checks.

**Comment by fernandopasik** [comment]
Sorry guys I didn't noticed this. Yes, there's definitely a theme change.

**Comment by ndelangen** [comment]
@fernandopasik would you want to fix this today? We could do it together if you'd like?

**Comment by fernandopasik** [comment]
Yes, I'll help on this tomorrow.

**Comment by ndelangen** [comment]
@Naturalclar want to pair program with us tomorrow?

**Comment by Naturalclar** [comment]
@ndelangen I'd be happy to join on the pair programming if I'm available :) 
What time are you planning on working?

**Comment by ndelangen** [comment]
17:30 UTC 20th of August (today) 2020
If you send me a DM on discord I can invite you to the meeting, and we should be able to get this working pretty quickly, I think!

https://discord.gg/7yKH3EU

**Comment by fernandopasik** [comment]
@Naturalclar we went through the code and seems like there's a new option in react-syntax-highlighter that would make at least the biggest issue away 

https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases/tag/13.0.0

I hope you don't mind I pushed the change to the branch. I'm looking at the color issues, seems like the theme got messed by some css classes duplicated from the update somehow.

**Comment by Naturalclar** [comment]
@ndelangen @fernandopasik 
Sorry I couldn't join the pair programming (it was 2:30am my time (JST), and I was fast asleep)
I don't mind change being pushed to this branch :+1:

**Comment by ndelangen** [comment]
@Naturalclar happy to chat directly on discord and find a better time-slot for you, I didn't notice your timezone 🙈

**Comment by ndelangen** [comment]
💯 x 💯 👏

**Review by ndelangen — APPROVED** [review]

**Review by lauthieb — APPROVED** [review]

**Comment by fernandopasik** [comment]
@shilman could this one be merged?

**Comment by ndelangen** [comment]
It will 💯!!

@shilman wants the ensure 6.0.x is stable first, before merging in 6.x.x changes.

**Comment by pavel-sindelka** [comment]
It breaks Storybook for IE 11 https://github.com/storybookjs/storybook/issues/12399

**Pull request merged**
