### PR TITLE
UI: open brandUrl in new window

### PR DESCRIPTION
**Pull request by toshi1127**
Issue: #6070

## What I did
Opened brandUrl in new window when the brand image was clicked
## How to test

- Is this testable with Jest or Chromatic screenshots? Yes. I updated the snapshot.
- Does this need a new example in the kitchen sink apps?  No.
- Does this need an update to the documentation?  No.

### CODE REVIEW

**Review by ndelangen — CHANGES_REQUESTED** [review]
I like it! one feature-request and then this will get merged:

Please only add the target when the url is an external link.

**Comment by toshi1127** [comment]
@ndelangen 
only added the target when the url is an external link.
Please confirm!!

**Comment by ndelangen** [comment]
If target is an empty string, `target=""` I guess nothing special happens.

Not having the prop at all seems a bit cleaner to me, but this is good to merge IMHO!

Good addition @toshi1127 👍

**Review by ndelangen — APPROVED** [review]

**Comment by aganglada** [comment]
This can be closed right?

**Pull request merged**
