### PR TITLE
Sort the story books alphabetically

### PR DESCRIPTION
**Pull request by gnagel**
Sort the story books alphabetically.  Makes it much easier to see stories that group together (ex Homepage: Search, Homepage: Login, ...) and find existing stories

### CODE REVIEW

**Comment by arunoda** [comment]
I agree this is something great. But sometimes, if we want to order by the natuaral order, it won't work. 
So, I would to make this as an option. May be passed via configure function call or something.

**Comment by andresin87** [comment]
I prefer not to be sorted alphabetically

**Comment by aray12** [comment]
I believe that the ability to sort alphabetically is an important feature. It give the user way more flexibility on how to organize their storybook and is far more intuitive (esp. when you are sharing with non-tech users).

Is there a timeline on this?

**Comment by arunoda** [comment]
@mnmtanish Is this something we could do with our new plugin system?

**Comment by mnmtanish** [comment]
We can expose some API from storybook-ui to update the list [here](https://github.com/kadirahq/storybook-ui/blob/765becf97791b1e8928b23eecb0bc82cb88c901e/src/modules/api/configs/init_api.js#L2,L11) so addons can use it.

**Comment by dziamid** [comment]
Is it resolved? How to enable sort?

**Pull request closed without merging**
