### PR TITLE
Build: Publish to NPM with provenance

### PR DESCRIPTION
**Pull request by gabibguti**
Closes #23916

## What I did

Adds a flag to publish to npm with provenance.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. On the next release, run the regular release workflow `publish.yml`
2. Check if the workflow passes
3. Check if the packages pages on npm show the [provenance badge](https://github.blog/2023-04-19-introducing-npm-package-provenance/#verification)
(e.g. https://www.npmjs.com/package/next#provenance)

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by yannbf** [comment]
Muito obrigado @gabibguti ! 🙌 
Is there anything we need to do on the org side in NPM?

**Comment by gabibguti** [comment]
Yeah, we need to change [actions/setup-node version](https://github.com/storybookjs/storybook/blob/next/.github/workflows/publish.yml#L48) from `16` to `18`. I'll bump, let me know if you see any blockers or problems here.

**Comment by yannbf** [comment]
> And, as far as I understand, all packages being published by storybook are public, can you confirm that?
That's right, AFAIK!

> Yeah, we need to change [actions/setup-node version](https://github.com/storybookjs/storybook/blob/next/.github/workflows/publish.yml?rgh-link-date=2023-08-22T16%3A16%3A53Z#L48) from `16` to `18`. I'll bump, let me know if you see any blockers or problems here.
I believe we use node 16 in our actions because that's the lowest node version that we support, however given that your change only affects the publish workflow, I think it's totally fine. @JReinhold could you confirm?

**Comment by yannbf** [comment]
So it seems like we are blocked from doing this change until this issue is resolved:

https://github.com/yarnpkg/berry/issues/5430

**Comment by wojtekmaj** [comment]
Psst @yannbf! You can work around this issue by packing using Yarn, but publishing using npm:

https://github.com/wojtekmaj/react-async-button/commit/585692056cb04422c6f4594b46a3022d1157e5fa

**Comment by gabibguti** [comment]
My understanding in this case is that we would really need yarn to support the provenance flag. Sorry about that folks, I did not see the tolerate republish problem. As @JReinhold suggested, we can do the yarn pack, then publish with npm, but we would need another logic to perform the retrying the publish for packages (--tolerate-republish), because the publish might fail since we are publishing multiple packages.

**Comment by JReinhold** [comment]
@gabibguti's last comment is correct. I'm closing this for now, we can always re-visit if we want to do the extra work needed.

**Pull request closed without merging**
