### PR TITLE
Convert issue templates to forms

### PR DESCRIPTION
**Pull request by mrhappyma**
I tried to copy these from the existing templates as much as possible.

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @mrhappyma Thank you so much for your contribution! Unfortunately we can't see the end result unless we merge this PR, so I'll set this up somewhere else and share it here, so that we can discuss further about this.

Thank you once again!

**Comment by mrhappyma** [comment]
@yannbf I do have issues enabled on my fork! You can try creating one there to see what it looks like: https://github.com/mrhappyma/storybook/issues/new/choose

**Comment by yannbf** [comment]
Thank you @mrhappyma  I'll share the screenshots here so we can discuss this further with the team!

Here's the view for filing a bug report:
image

Once you click on any field, it becomes a markdown-like editor
image

And here's the one for filing a feature request:
image

I think this change is great but the current state of the form could be changed, maybe this is our chance to improve this template as it hasn't been touched for quite some time. I'd love to hear your thoughts @kylegach @winkerVSbecks @jonniebigodes @ShaunLloyd @storybookjs/core

**Comment by yannbf** [comment]
I really like the form created for [storybook-addon-designs](https://github.com/pocka/storybook-addon-designs/issues/new?assignees=&labels=category%3A+bug&template=bug_report.yml)

image

We could use something that makes it easier for users to specify configurations such as renderer, framework, builder, Storybook version, etc.

**Comment by JReinhold** [comment]
Overall I also think this looks really good.

> We could use something that makes it easier for users to specify configurations such as renderer, framework, builder, Storybook version, etc.

Agree. The challenge here is that we'll end up with a lot of options, and we don't want a dropdown because you'd want to be able to select multiple, so we'd have a **lot** of checkboxes. But maybe that's okay. Two open questions:

- Do we need to make a distinction between officially and community supported renderers/frameworks?
- We have a mismatch in terms. What we call "renderers" the industry calls "frameworks"*, and what we call "frameworks" the industry calls "metaframeworks". Do we need to handle this? Maybe if the user has options anyway it won't be that confusing. (we were bound to run into this term-mismatch eventually)

\* except we also have an HTML renderer which no one would call a framework.

I also really like the Importance/Severity from the SvelteKit repo. Makes it easier to triage even though users tend to overestimate this.

Bug reports:
image

Feature requests:
image

**Comment by winkerVSbecks** [comment]
@JReinhold would be nice to add a field for reproduction i.e., not just steps but an actual repo/gist

**Comment by ndelangen** [comment]
Are we moving this forward? I think this is an improvement.

**Review by ndelangen — APPROVED** [review]

**Review by IanVS — APPROVED** [review]
I agree.  Maybe merging this as-is would be a good first step, since it keeps the same basic info as we have currently, and then we can make another PR with further improvements and refinements?

**Review by JReinhold — APPROVED** [review]

**Comment by mrhappyma** [comment]
🎉 thanks!

**Pull request merged**
