### PR TITLE
Addon-a11y: Skip flakey tests

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

The skipped test is flakey in CI, e.g. https://app.circleci.com/pipelines/github/storybookjs/storybook/26195/workflows/cd121630-6d27-488d-95ba-c5c8a2342575/jobs/383243

Also, this should use SB interaction testing, but I don't have time.

## What I did

Skip it for now

## How to test

- [ ] CI passes

### CODE REVIEW

**Comment by jsomsanith** [comment]
Hey @shilman,
The logs you gave me indicated that `should set filter` test was failing, not the one your skipped.

**Review by jsomsanith — APPROVED** [review]

**Comment by jsomsanith** [comment]
Changed the `skip` position

**Comment by jsomsanith** [comment]
Hmm ok it seems that the issue in test in linked to the tooltip so it impacts both tests.
Skipped both.

**Review by yannbf — APPROVED** [review]
LGTM. I spent some time trying to figure out a way to make them pass but couldn't

**Comment by jsomsanith** [comment]
> LGTM. I spent some time trying to figure out a way to make them pass but couldn't

Yeah same here, they pass locally, that doesn't help :(

**Pull request merged**
