### PR TITLE
Added sass package in installation command

### PR DESCRIPTION
**Pull request by NishargShah**
Issue: Added `sass` package in installation command

## What I did

Added `sass` package in installation command because it's giving the error

> PostCSS received undefined instead of CSS string

## How to test

Just Docs change

### CODE REVIEW

**Review by phated — APPROVED** [review]
👍 It looks like latest sass-loader demands `sass` as a peerDep

**Comment by NishargShah** [comment]
Yes, `sass` is `peer dependency` of `sass-loader`, can you change this for `presets` also ( https://github.com/storybookjs/presets/tree/master/packages/preset-scss )

**Comment by jonniebigodes** [comment]
@NishargShah thank you for the time and effort you put into this pull request. @phated i'm good with this. If you want to follow up on this pull request with one for the package i'll gladly merge it. Or i can take care of it. I'll leave it to you.

**Comment by NishargShah** [comment]
@jonniebigodes Welcome :)

**Comment by jonniebigodes** [comment]
@phated i'll take care of it in a moment. I'm working on it and i'll make the pull request and get both merged at the same time.

**Review by shilman — APPROVED** [review]
LGTM

**Pull request merged**
