### PR TITLE
Update the axe version in addon-a11y to 4.0

### PR DESCRIPTION
**Pull request by adierkens**
Issue: #10693

## What I did

Updated to the latest: `axe-core@4.0.1`. 
The `restoreScroll` config option was removed in `4.0.0` by https://github.com/dequelabs/axe-core/pull/2408 so I removed that as a default option from the addon. 

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? Probably just a mention in the release notes of the addon, the API remains unchanged. 

I tested this using the cra-kitchen-sink example and the Accessibility tab

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Thanks for the upgrade! I've marked this as "do not merge" temporarily so that we can release it in 6.1 alpha next week.

In the meantime our e2e tests are failing. Are you able to access the attached Circle CI logs? @tooppaaa can you help get this through?

**Comment by tooppaaa** [comment]
E2E looks all green to me ?

**Comment by shilman** [comment]
Hmm I re-ran the e2e so maybe that fixed it. At any rate, let's wait on merging until next week.

**Review by CodeByAlex — APPROVED** [review]
LGTM

**Pull request merged**
