### PR TITLE
Addon-docs: Fix newline handling in ArgsTable code blocks

### LINKED ISSUE #11358: [addon-docs] Newlines not rendered in markdown code blocks in prop comments
**Describe the bug**
When adding code blocks to a docblock in markdown format, they appear in Storybook as a single line instead of properly formatted.

**To Reproduce**
Add the following comment to a propType declaration:
```
/**
 * ```
 * classNames={{
 *   appear: 'my-appear',
 *   appearActive: 'my-active-appear',
 *   appearDone: 'my-done-appear',
 *   enter: 'my-enter',
 *   enterActive: 'my-active-enter',
 *   enterDone: 'my-done-enter',
 *   exit: 'my-exit',
 *   exitActive: 'my-active-exit',
 *   exitDone: 'my-done-exit',
 * }}
 * ```
 */
```

**Expected behavior**
It should appear in Storybook as follows:
```
classNames={{
  appear: 'my-appear',
  appearActive: 'my-active-appear',
  appearDone: 'my-done-appear',
  enter: 'my-enter',
  enterActive: 'my-active-enter',
  enterDone: 'my-done-enter',
  exit: 'my-exit',
  exitActive: 'my-active-exit',
  exitDone: 'my-done-exit',
}}
```

**Actual Behavior**
It appears as:
```
classNames={{ appear: 'my-appear', appearActive: 'my-active-appear', appearDone: 'my-done-appear', enter: 'my-enter', enterActive: 'my-active-enter', enterDone: 'my-done-enter', exit: 'my-exit', exitActive: 'my-active-exit', exitDone: 'my-done-exit', }}
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.5 - ~/Desktop/react-skeleton-generator/waltz/node_modules/.bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: ^5.3.19 => 5.3.19
    @storybook/addon-actions: ^5.3.19 => 5.3.19
    @storybook/addon-docs: ^5.3.19 => 5.3.19
    @storybook/addon-knobs: ^5.3.19 => 5.3.19
    @storybook/addon-links: ^5.3.19 => 5.3.19
    @storybook/addon-viewport: ^5.3.19 => 5.3.19
    @storybook/addons: ^5.3.19 => 5.3.19
    @storybook/react: ^5.3.19 => 5.3.19
```

### PR DESCRIPTION
**Pull request by niklasmh**
Issue: #11358 (propTypes) and #12848 (interface)

## What I did

Added `white-space: pre-wrap;` on code blocks (specifically). This does not affect inline code.

### Before:
image

### After:
image

## How to test

- Is this testable with Jest or Chromatic screenshots?
  - **No, unless ArgsTables are included in the screenshots**
- Does this need a new example in the kitchen sink apps?
  - **Yes**
  - **Added a propTypes example in `cra-kitchen-sink\src\components\Container.js` together with an ArgsTable in the test story: `cra-kitchen-sink\src\stories\test.stories.mdx`.**
  - **Added an interface example in `cra-ts-kitchen-sink\src\components\Button.tsx`.**
- Does this need an update to the documentation?
  - **No**

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by niklasmh** [comment]
This is how the examples that were added looks like:

## For the `cra-kitchen-sink` app:
image

## For the `cra-ts-kitchen-sink` app:
image

**Review by ndelangen — APPROVED** [review]

**Review by RichardVoyles09 — APPROVED** [review]

**Comment by MichaelArestad** [comment]
It looks like the code block is missing styles. Compare the inline code examples to the block:

image

**Comment by niklasmh** [comment]
Thanks for the feedback, @MichaelArestad!

Do you mean making the inline code (here in red) to become a single block when it breaks, like the block in the green area?

image

**Comment by MichaelArestad** [comment]
@niklasmh Not quite. I'm referring for the differences in styles between this:

image

and this:
image

It's somewhat tricky to spot, but you'll see they actually have different font and color styles.

**Comment by niklasmh** [comment]
@MichaelArestad Nice spotted! I can attempt to do something about it. I assume the first style is preferred? As it is the default for inline code.

**Comment by MichaelArestad** [comment]
@niklasmh That would be great. Yes. The styles for the inline code are preferred. Thank you!

**Comment by niklasmh** [comment]
@MichaelArestad As far I could find the only difference was the font-size which made the text appear darker. I also saw that setting a smaller font-size on inline code blocks is a normal practice (e.g. GitHub) - therefore it seems like a reasonable change to add.

Now it looks like this:
image

**Comment by niklasmh** [comment]
Now the font should be good too! Thanks for guiding me through my first PR here at storybook, @MichaelArestad :)

**Review by MichaelArestad — APPROVED** [review]

**Comment by MichaelArestad** [comment]
I'm seeing some visual diffs of changes that are unrelated to this PR. I suspect a rebase or merging an updated `next` branch will resolve those changes. As for the changes you made, they look great. Thank you!

**Comment by MichaelArestad** [comment]
@shilman I think this one is ready to 🚢

**Review by shilman — APPROVED** [review]
Thanks @niklasmh !!! 🙏

**Pull request merged**
