### PR TITLE
 Use yarn workspaces on master

### PR DESCRIPTION
**Pull request by Hypnosphi**
See https://github.com/storybooks/storybook/pull/1803#issuecomment-332990394

### CODE REVIEW

**Comment by ndelangen** [comment]
This is happening on my machine:
screen shot 2017-09-30 at 11 40 37

**Comment by ndelangen** [comment]
This doesn't look right to me:
https://circleci.com/gh/storybooks/storybook/13728?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Hypnosphi** [comment]
> This is happening on my machine
Which yarn version do you have?

**Comment by ndelangen** [comment]
screen shot 2017-09-30 at 13 12 32

**Comment by ndelangen** [comment]
I can confirm this on my machine now.

I tested bootstrapping everything, cra-kitchen-sink, docs

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
