### PR TITLE
Core: Ensure we set `parameters.filePath` in v7 mode

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: We weren't setting `parameters.filePath` in `storyStoreV7`  mode.

## What I did

Ensure we set it (from the `importPath`) when processing a CSF file

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?

I tested in `react-ts` both with and without `storyStoreV7` set.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Looks reasonable to me!

**Review by shilman — COMMENTED** [review]
@tmeasday do we want to remove this with `features.breakingChangesV7`?

**Comment by tmeasday** [comment]
> @tmeasday do we want to remove this with features.breakingChangesV7?

I'm not sure, I think if we did, we should decide where else to put the `importPath` / `parameters.fileName` on the story context, as otherwise you'd need to go and look it up in the story index, which seems a bit much.

If we were starting from scratch I might put it in `story.importPath`, or `story.parameters.importPath`, I'm not really sure.   What do you think?

**Review by shilman — APPROVED** [review]
Looking good 😎

**Pull request merged**
