### PR TITLE
3.0.0 migration assistance : codemod, update installation and usage instructions

### PR DESCRIPTION
**Pull request by aaronmcadam**
I noticed that the codemod script name is wrong.

## TODO

- [x] Verify the best practice for installing codemods: local repo clone or global registry?
- [x] Write usage guide for codemods
- [ ] Record screen video of usage
- [x] Write manual migration guide

### CODE REVIEW

**Comment by shilman** [comment]
@aaronmcadam Can you add instructions for how to apply this to a whole project from start to finish?
1) do i have to install this as a dev dependency for my project?
2) how is there some typical `find *.js | xargs ...` command to run this over my entire project?

**Comment by aaronmcadam** [comment]
> 2. ...

You need to be careful to ignore your `dist` or other bundle output. You can use your `.gitignore` file for this.

Can you try `jscodeshift -t lib/codemod/src/transforms/update-organisation-name.js --ignore-config .gitignore path/to/your/project`?

We also need to check whether we have to tell users to clone the repo, like [react-codemod](https://github.com/reactjs/react-codemod), or like the docs say, install the package and register it with `jscodeshift` somehow.

**Comment by ndelangen** [comment]
@aaronmcadam Do you think you can demo this?

We could create a video like so:
1. create a folder
2. start CRA in it
3. start 2.x.x storybook in it
4. run codemods
5. cleanup
6. run cra & storybook
7. cake

I need help with step 4.

**Comment by shilman** [comment]
@aaronmcadam how hard would it be to add this to `getstorybook`? Or is that a terrible idea? 😬

**Comment by ndelangen** [comment]
I have big plans for the cli, and that would be one of them @shilman 

I actually want to build something like this (eventually):
```sh
storybook start   # starts and opens storybook 
```
```sh
storybook start --public  # starts and create a temp public url to share
```
```sh
storybook build  # builds to static site
```
```sh
storybook deploy  # builds to static site & deploy to heroku
```
```sh
storybook help <searchterm>  # search our documentation 
```
```sh
storybook migrate  # run codemods to latest version
```

**Comment by shilman** [comment]
@aaronmcadam it's not working for me. here's my steps:
```
  505  yarn create react-app testapp
  506  cd testapp/
  507  yarn add getstorybook
  508  ./node_modules/.bin/getstorybook 
  509 cd ../storybook
  510 jscodeshift -t ./lib/codemod/src/transforms/update-organisation-name.js --ignore-config .gitignore ../testapp/
```

I'm getting errors that look like this:
```
MBP:storybook shilman$ jscodeshift -t ./lib/codemod/src/transforms/update-organisation-name.js --ignore-config .gitignore ../testapp/
Processing 17179 files... 
Spawning 3 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
 ERR ../testapp/node_modules/asn1.js/test.js Transformation error
SyntaxError: Unexpected token (6:0)
    at Parser.pp.raise (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExprAtom (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:425:12)
    at Parser.parseExprAtom (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseVar (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:493:24)
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
 ERR ../testapp/node_modules/errno/cli.js Transformation error
SyntaxError: 'return' outside of function (8:2)
    at Parser.pp.raise (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.parseReturnStatement (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:275:10)
    at Parser.pp.parseStatement (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:89:19)
    at Parser.parseStatement (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseIfStatement (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:268:26)
    at Parser.pp.parseStatement (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:87:19)
    at Parser.parseStatement (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/Users/shilman/.config/yarn/global/node_modules/babel-core/node_modules/babylon/lib/index.js:45:50)
```

And the resulting files look something like this (note this is from a different app, but the pattern is the same):

```js
import { configure } from undefined;

import undefined

const req = require.context('../src', true, /.story.js$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**Review by shilman — CHANGES_REQUESTED** [review]
Need help! See my comment above 😄

**Comment by aaronmcadam** [comment]
Hey @shilman judging from that output, it looks like the `.gitignore` isn't ignoring `node_modules`. I'll try this later though and get back to you

**Comment by ndelangen** [comment]
Here's the implementation of the codemod:
https://astexplorer.net/#/gist/f2d0b42c37e4556a4f816892be6ca402/ad64d6387a68461556dd57d1cc3d4124425f1573

Give it a test

**Comment by shilman** [comment]
@ndelangen I am still having problems running this on my project. Can you please test it on a from-scratch project that is not part of the monorepo and tell me if it works for you. Here are my exact repro steps:

```
  505  yarn create react-app testapp
  506  cd testapp/
  507  yarn add getstorybook
  508  ./node_modules/.bin/getstorybook 
  509 cd ../storybook
  510 jscodeshift -t ./lib/codemod/src/transforms/update-organisation-name.js --ignore-config .gitignore ../testapp/
```

**Review by shilman — APPROVED** [review]
GREAT!!!

**Pull request merged**
