### PR TITLE
Core: Fix WebProjectAnnotations export in preview-web for back-compat

### PR DESCRIPTION
**Pull request by clintandrewhall**
Issue: https://github.com/storybookjs/testing-react/issues/106
Discussion: https://github.com/storybookjs/storybook/discussions/18531

## What I did

I added a type export to resolve.  It was unclear if this, too, would affect `builder-vite`, (I can't imagine it would), but I added the export immediately following for visibility and completeness.

Hope this helps!

## How to test

- [ ] ~~Is this testable with Jest or Chromatic screenshots?~~
- [ ] ~~Does this need a new example in the kitchen sink apps?~~
- [ ] ~~Does this need an update to the documentation?~~

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by IanVS** [comment]
@shilman this is what we talked about in discord.  I'm not sure what's needed to get CI running/passing.  I attempted to start a discussion in https://discord.com/channels/486522875931656193/839297503446695956/1013924170918269008.

**Comment by shilman** [comment]
@tmeasday the background here is that a type got moved as a breaking change in 6.5. This re-exports the type to fix the break, which affects the test runner specifically.

Questions:
- Are you good with the change?
- How about for 7.0?

**Review by shilman — APPROVED** [review]
Thanks so much @clintandrewhall !! 🙏

**Comment by clintandrewhall** [comment]
@shilman @IanVS I don't see any further type issues locally.  I can't test in our CI, but I have fairly high confidence in this fix.  Should be good to go!

**Review by IanVS — APPROVED** [review]

**Comment by tmeasday** [comment]
Fine by me, to re-export it. I'm not totally sure I recall why it moved in the first place, but either way re-exporting makes sense to avoid breaking in any case.

**Comment by BHA8273** [comment]
Guys please help

**Comment by sipkoepp** [comment]
@shilman you fixed this in the latest alpha release. Is it possible to fix this for a stable version?

**Comment by IanVS** [comment]
It has the `patch` label, which means that when it comes time to cut another 6.5 patch release, it will get picked into it.

**Comment by dakotalightning** [comment]
Fix released in https://github.com/storybookjs/storybook/releases/tag/v6.5.11

**Pull request merged**
