### PR TITLE
Replace demo.gif

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: ☝️

### CODE REVIEW

**Review by pksunkara — APPROVED** [review]

**Comment by ndelangen** [comment]
👏

**Comment by ewolfe** [comment]
This is really nice! What'd you use to create it?

**Comment by ndelangen** [comment]
Glad you like it @ewolfe, Daniel Egerev created it for us, maybe he can explain the process?

**Comment by iDanbo** [comment]
@ewolfe the animations were done in Adobe After Effects. I first created the illustrations in Adobe Illustrator and then imported to After Effects to animate them 🙂

**Pull request merged**
