### PR TITLE
Core: Typing useArgs

### PR DESCRIPTION
**Pull request by saiichihashimoto**
Issue:
useArgs is great, but it would be nice to type it so it can conform with my component props.

## What I did
- Typed useArgs with a generic, defaulting to the same behavior to be non-breaking.
- Also, resetArgs was typed with a tuple of `[string]` rather than being an array as it should be.

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Nice one @saiichihashimoto -- thanks so much!!!

Any chance you can add an example that demonstrates the feature as part of `examples/official-storybook`? 🙏

**Comment by saiichihashimoto** [comment]
I'm not sure how to go about this @shilman, a little help? There's a lot going on there.

**Comment by saiichihashimoto** [comment]
Not sure if you're able to help me here @shilman, not sure how to go about adding examples tbh.

**Comment by ndelangen** [comment]
I updated with an example! Works great, thank you for this @saiichihashimoto !

@shilman I'll merge this as soon as it's green, because this change just makes sense to me.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
