### PR TITLE
Source-loader: Fix Typescript support

### PR DESCRIPTION
**Pull request by shilman**
Issue: #8198

## What I did

A bunch of bugfixes for source-loader typescript support. AFAIK source-loader now works out of the box, at least with the CRA typescript preset.

## How to test

- See updated tests/snapshots
- Run `cra-ts-kitchen-sink`	& observe source in `Docs` tab

### CODE REVIEW

**Review by libetl — APPROVED** [review]
Lgtm

**Comment by shilman** [comment]
@libetl See the last commit:

```
        // return insertAfterImports(preamble, source);
        return `${preamble}${source}`;
```

`insertAfterImports` function needs to be fixed (OR the code needs to be restructured). The code should actually parse `source` into an AST and then perform the insertion based on the AST. The current heuristic fails on the following (EVIL) file:

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-notes.stories.js#L15

Since the "import" string is located inside a string constant, the heuristic actually inserts `preamble` inside the string constant, which is wrong.

Please help!

**Comment by libetl** [comment]
I would opt for the refactor definitely, the search and replace approach is not going anywhere

**Comment by libetl** [comment]
suggestion applied + conflicts from next are merged.

Sorry, resuming *so* slowly from my regular job to a more regular pace.

**Comment by shilman** [comment]
@libetl snapshot tests are failing. first i had to update an import, which looks a little weird. Now that it's fixed, the snapshot looks weird:

GitHub_Desktop

**Comment by libetl** [comment]
aïe

**Comment by shilman** [comment]
@libetl It looks like source-loader is still not quite right:

```
#!/bin/bash -eo pipefail
cd examples/cra-ts-kitchen-sink
yarn storybook --smoke-test --quiet

[...]

WARNING in ./src/components/Button.stories.tsx
Module Error (from /tmp/storybook/node_modules/react-scripts/node_modules/eslint-loader/dist/cjs.js):

  Line 22:9:  Import in body of module; reorder to top  import/first
  Line 23:1:  Import in body of module; reorder to top  import/first
  Line 24:1:  Import in body of module; reorder to top  import/first
  Line 25:1:  Import in body of module; reorder to top  import/first
```

**Comment by libetl** [comment]
@shilman please update the yarn.lock again, I am using the laptop from my company and it is using windows.

**Pull request merged**
