### PR TITLE
add shortcut for running `yarn storybook` in `cra-kitchen-sink`

### PR DESCRIPTION
**Pull request by Hypnosphi**
Before
```
cd examples/cra-kitchen-sink && yarn storybook
```

After
```
yarn start
```

### CODE REVIEW

**Comment by UsulPro** [comment]
Great! It's a sort of script that I really wanted to have :+1: 

The only inconvenience for me that my terminal doesn't support auto filling yarn commands by [Tab]. And I will need to type it manually (while it works for paths). So, in this case, I'd prefer something shorter e.g. `yarn start` :)

**Comment by Hypnosphi** [comment]
Ok, renamed that

**Comment by UsulPro** [comment]
Looks good to me!
(could you change script name in your first comment?)

**Comment by Hypnosphi** [comment]
Did that as well

**Review by usulpro — APPROVED** [review]

**Comment by ndelangen** [comment]
Good first step, to making running the example(s) easier, thanks. Will be improving on this at a later stage! (we do have more examples 👍 )

**Pull request merged**
