### PR TITLE
Deprecate builtin addons (links and actions) - no longer included by default

### PR DESCRIPTION
**Pull request by shilman**
Issue: #1017

## What I did

Added HISTORY.md to track changes with each release, modeled after
Meteor’s: https://github.com/meteor/meteor/blob/devel/History.md

## How to test

Follow instructions in HISTORY.md (if you want)

### CODE REVIEW

**Comment by UsulPro** [comment]
I wonder can we additionally add a deprecating warning to `@kadira/storybook-addon-...` packages?

**Comment by shilman** [comment]
@UsulPro I'm not sure I understand your comment. I just deprecated the builtin-ness of the addons, not the addons themselves, so I don't think it's appropriate to deprecate them. What do you think?

**Comment by ndelangen** [comment]
I think @shilman means we can deprecate all `@kadira/*` packages on npm.
We'd need to get membership on those packages, in order to publish.

**Review by ndelangen — COMMENTED** [review]
I think a before and after code example would make this text a lot more understandable.

**Comment by shilman** [comment]
OK I understand @UsulPro 's `@kadira/*` deprecation comment now. Thanks!

**Comment by shilman** [comment]
@ndelangen Added before/after example. Not sure whether this is the best place for it or format. Suggestions welcome!

**Review by usulpro — APPROVED** [review]
LGTM

**Pull request merged**
