### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**
## What I did
Add Node.js for CI builds to test the current stable Node.js version.

### CODE REVIEW

**Comment by DanielRuf** [comment]
> failed during stage 'building site': Deploy directory 'netlify-build' does not exist

It seems there is an issue with the Netlify setup in the last few builds.

> PR is not labeled with one of: ["cleanup","BREAKING CHANGE","feature request","bug","documentation","maintenance","dependencies:update","dependencies","other"]

No commitlint style? So should I label it `other: ...`?

**Comment by DanielRuf** [comment]
> No commitlint style? So should I label it other: ...?

It seems no one applies this to the PRs / commits so where is the sense in this atm? Some commitlint / husky solution should be probably used to enforce this (if `--no-verify` is not used).

**Comment by Hypnosphi** [comment]
Actually teamcity builds are running on `node:latest` image

**Comment by wuweiweiwu** [comment]
Might have some unintended consequences. https://github.com/storybooks/storybook/issues/3529

**Comment by ndelangen** [comment]
@wuweiweiwu testing in node 10 should not have any side-effects for users.

If I understand @Hypnosphi correctly we are already testing on Node8 on CircleCI and Node10 on TeamCity.

---

@DanielRuf You may commit with any message you like as long as it's decent. Our release process is mostly manual, but the commit process is beginner friendly.

**Comment by ndelangen** [comment]
We run many test on both CircleCI and TeamCity. TeamCity runs some additional tests on examples.
We do not use TravisCI AFAIK.

> It seems there is an issue with the Netlify setup in the last few builds.

Indeed, I've been meaning to get to that and fix it for the past few days, haven't gotten around to doing that. The TeamCity example tests are mostly a improved version so it hasn't made top priority on my list.

**Pull request closed without merging**
