### PR TITLE
Option to select an addon panel && rename selectedDownPanel to selectedAddonPanel

### PR DESCRIPTION
**Pull request by usulpro**
Issue: #811

we had `selectedDownPanel` option in our UI module but it wasn't available by `setOptions`

## What I did

Allow to set `selectedDownPanel` by `setOptions`.

Now it's possible to select the spesific addon panel this way:

```js
setOptions({ selectedAddonPanel: 'storybook/notes/panel' })
```

You need to pass a panel ID to select a panel (same value that you pass to `addons.addPanel()`)

If you don't know the ID you can pass anything and find in the console output the list of all registered 
panels

## How to test

run `cra-kitchen-sink`
Check out "Button" section. Selecting stories with different addons you'll see appropriate addon panels auto selected
Try to pass `null` or something else.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
`selectedAddonPanel` maybe?

**Comment by UsulPro** [comment]
Done!
I guess in glamorous components we'll rename all "down" to "addon" and "left" -> "stories"

**Review by Hypnosphi — APPROVED** [review]
LGTM

**Comment by matheo** [comment]
For the record (for those googling `selectedAddonPanel`)
it was moved to `addons.setConfig({ selectedPanel })` on v5:
https://storybook.js.org/docs/configurations/options-parameter/

**Pull request merged**
