### PR TITLE
Core: Pass proper stack of an error

### PR DESCRIPTION
**Pull request by extempl**
Reopening https://github.com/storybookjs/storybook/pull/14336

Issue: Stack of an error is not the error's, but the storybook's.

## What I did
Pass stack explicitly (toString does not include it).

## How to test

- Is this testable with Jest or Chromatic screenshots? - Passively?
- Does this need a new example in the kitchen sink apps? - No
- Does this need an update to the documentation? - No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
This looks identical to the previous PR you made, #14336. Can you provide an example or detailed steps to reproduce the issue you are having?

**Comment by extempl** [comment]
@MichaelArestad @yannbf  indeed it is identical, this is the only way I can 'reopen' it, since it was closed.
The example of the issue and solution is in the latest comment: https://github.com/storybookjs/storybook/pull/14336#issuecomment-900259574

The issue is that (new Error).toString does not contain a stacktrace, but message only. The stack trace is visible after that does not help to solve any problems occured because of the error, as it shows nothing, but the fact that something went wrong and the error message.

**Review by yannbf — APPROVED** [review]
Thanks for this PR @extempl! It certainly makes things much better. I simulated this error by calling a function that does not exist in a .stories file.

Here's the result prior to your fix:
image

Here's with your fix:
image

Great contribution! 👏

**Comment by shilman** [comment]
@yannbf any chance you can help get CI passing?

**Comment by yannbf** [comment]
@shilman this seems good to go!

**Pull request merged**
