### PR TITLE
UI: Wait 100ms before showing spinner and fix story overlaying it

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: https://github.com/storybookjs/storybook/issues/17122

## What I did

1. Hide user content during preparing, before rendering
2. Ensure we still show the story during rendering (https://github.com/storybookjs/storybook/issues/16847)3. 
3. Wait 100ms before showing preparing (https://github.com/storybookjs/storybook/issues/17122)

### How to test

For 1. see http://localhost:9011/?path=/story/core-loaders--z-index -- try switching to the other loading story, notice the spinner overlay/hides the z-index story

For 2. see http://localhost:9011/?path=/story/core-rendering--auto-focus

For 3. switch between first two backgrounds stories: http://localhost:9011/?path=/story/addons-backgrounds--story-1

### CODE REVIEW

**Comment by yannbf** [comment]
@tmeasday this is great!!! Incredibly better.


I noticed a regression related to loaders, maybe it's out of scope but I thought of sharing:
https://user-images.githubusercontent.com/1671563/159902667-be851e5d-6ce7-4128-8b92-6a2effa23811.mp4

**Comment by tmeasday** [comment]
Just to write down what's in the video:

 1. Changing globals re-runs loaders without re-displaying the spinner
 2. Docs mode does not display spinner
 3. Switching back from docs mode->story mode shows a flash of the "old" story.

**Comment by tmeasday** [comment]
@yannbf fixed #3.

Thinking about things for a bit:
 - Fixing 1. would require calling `preview.view.showPreparingStory` from inside the `StoryRender` object, which is a bit messy. OTOH I'm not 100% convinced that showing a spinner is the behaviour we want here. Let's discuss.

 -Fixing 2. would require a bit of a refactor of the way the `<Story/>` doc block works. Definitely a longer term thing. Something to think about in the work we are doing @shilman.

**Review by yannbf — APPROVED** [review]
Thanks @tmeasday! I agree on your points 👍 

Can you check CI? Seems like there's a typescript issue
image

**Pull request merged**
