### PR TITLE
Fix the d.ts file of addon-links, mark LinkTo in index as deprecated

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/20580

## What I did

- Add react entrypoint to types exports map
- fix the .d.ts file which seems to suffer from a bug in tsup
  Can likely be removed at 8.0 when preview-api is simplified
- mark LinkTo as deprecated in the index entrypoint

### CODE REVIEW

**Comment by ndelangen** [comment]
I found of there was confusion about the LinkTo component, which should come from the `react` entrypoint, but everything else should come from the index entrypoint:
https://github.com/DannyJoris/storybook-nextjs-linkto/pull/1/files#diff-8f0abfa5fd53937fe7e24ab4c3987d3b9e6558e770409898a13b2800934aab02R1-R2

**Comment by DannyJoris** [comment]
@ndelangen Thanks for that!

The TypeScript issue for `LinkTo` still remains it looks like. This is using `7.0.0-beta.31`:

Screenshot 2023-01-23 at 10 49 36 AM

**Comment by ndelangen** [comment]
@DannyJoris do you have any custom type definitions setup for `@storybook/addon-links`?

try adding this to the top of your file:
```
import React from 'react'
```

**Comment by DannyJoris** [comment]
@ndelangen No other types defined, and importing React didn't work either.

What did work is upgrading: something in beta32 or 33 is fixing it: https://github.com/storybookjs/storybook/issues/20580#issuecomment-1401357368

Thanks again for all your help! I appreciate it.

**Pull request merged**
