### PR TITLE
Addon-Toolbars: Global args support in the toolbar

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Created `addon-toolbars`, an evolution of `addon-contexts`, based on Storybook's new Global Args feature and decorators.

hero

This addon allows people to easily create custom toolbars that set global variables which are accessible from within decorators and stories. See included README for details.

## How to test

See included toolbar stories in `official-storybook`

### CODE REVIEW

**Comment by leoyli** [comment]
Thanks for creating this! The first look really promising to me. It did solve the pain point I was facing on porting the addon with other frameworks. Really well done guys!  I will dive in deeper to see if anything I can suggest to make it event better.

**Review by tmeasday — APPROVED** [review]
LGTM, great stuff

**Comment by lifeiscontent** [comment]
@shilman where do the icons come from?

**Comment by shilman** [comment]
https://next--storybookjs.netlify.app/official-storybook/?path=/docs/basics-icon--labels

**Pull request merged**
