### PR TITLE
Build: Bundle lib/channel-postmessage with ts-up

### PR DESCRIPTION
**Pull request by javier-arango**
Issue: [#18732](https://github.com/storybookjs/storybook/issues/18732)

## What I did
Migrated `lib/channel-postmessage` to use the `ts-up` bundler.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by javier-arango** [comment]
@IanVS & @ndelangen do you guys know what should I do to pass the `smoked-test-sandboxes` and the `Socket Security` checks ?

**Comment by IanVS** [comment]
@javier-arango I think those are issues with the current state of the repo, and not something you've done here.

**Comment by javier-arango** [comment]
> 

@IanVS sounds good, should I put the PR ready for review ?

**Review by IanVS — APPROVED** [review]
Woo hoo, CI is green!  Thanks @javier-arango!

**Pull request merged**
