### PR TITLE
Adding airbnb-js-shims again.

### PR DESCRIPTION
**Pull request by arunoda**
Issue #400 is only related to a Chrome thing.
So, it's fine to use where the standards lie.

### CODE REVIEW

**Comment by arunoda** [comment]
@ljharb check the latest release. It has `airbnb-js-shims` now.

**Comment by ljharb** [comment]
Thanks, much obliged!

**Comment by ljharb** [comment]
@arunoda what is `babel-polyfill` used for? that also pulls in `core-js`.

**Comment by arunoda** [comment]
Yep. But we have disabled polyfills and helpers when transforming. 
What did you mean?

**Comment by ljharb** [comment]
Then shouldn't it not be a dependency?

**Comment by arunoda** [comment]
@ljharb Yep. I think we can remove that altogether.

**Comment by ljharb** [comment]
Thanks, that'd be great :-)

**Comment by arunoda** [comment]
Removed and did a new release: `v2.11.0`

**Pull request merged**
