### PR TITLE
Angular: sandbox to update to Angular v13

### LINKED ISSUE #16355: Angular 13 Support
**Describe the bug**
Storybook does not run with the latest Angular 13 RC. There seems to be a problem with using `require` in framework-preset-angular-ivy

<details>
  <summary>Failed to load preset error message:</summary>
<code>
info @storybook/angular v6.4.0-beta.11
info 
info => Loading presets
WARN   Failed to load preset: "/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js"
ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@angular/compiler-cli/bundles/ngcc/index.js from /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js not supported.
ERR! Instead change the require of index.js in /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js:70:14)
ERR!     at interopRequireDefault (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:159:16)
ERR!     at getContent (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:175:10)
ERR!     at loadPreset (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:184:20)
ERR!     at /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:236:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:235:18)
ERR!     at getPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:293:23)
ERR!     at loadAllPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:318:10)
ERR!     at buildDevStandalone (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:103:48)
ERR!     at async Object.buildDev (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:160:5)
ERR!  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@angular/compiler-cli/bundles/ngcc/index.js from /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js not supported.
ERR! Instead change the require of index.js in /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js:70:14)
ERR!     at interopRequireDefault (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:159:16)
ERR!     at getContent (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:175:10)
ERR!     at loadPreset (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:184:20)
ERR!     at /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:236:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:235:18)
ERR!     at getPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:293:23)
ERR!     at loadAllPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:318:10)
ERR!     at buildDevStandalone (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:103:48)
ERR!     at async Object.buildDev (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:160:5) {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }
</code>
</details>

**To Reproduce**
Add storybook to any Angular 13 project, or see [this reproduction branch](https://github.com/literalpie/sb-ng-performance/tree/ng-13).

**System**
```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: 3.0.1 - /usr/local/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/addon-docs: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/addon-essentials: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/addon-links: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/angular: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/builder-webpack5: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/manager-webpack5: ^6.4.0-beta.11 => 6.4.0-beta.11 
```

**Additional context**
Angular just entered the Release Candidate phase.

### PR DESCRIPTION
**Pull request by ThibaudAV**
Issue: TRy to fix https://github.com/storybookjs/storybook/issues/16355

## What I did

try to fix .... 

Several problems overcome now the error is the following: 

```
99% done plugins webpack-hot-middlewarewebpack built preview 01814e7164069945260a in 24840ms
ModuleNotFoundError: Module not found: Error: Can't resolve 'rxjs/operators' in '/Users/thibaud/sb-workspace/storybook/node_modules/@angular/core/fesm2020'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'rxjs/operators' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/Compilation.js:1660:28
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:708:13
    at eval (eval at create (/Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:632:24
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:774:8
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:894:5
    at /Users/thibaud/sb-workspace/storybook/node_modules/neo-async/async.js:6883:13
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:811:17
    at finishResolved (/Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/thibaud/sb-workspace/storybook/lib/builder-webpack5/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve 'rxjs/operators' in '/Users/thibaud/sb-workspace/storybook/node_modules/@angular/core/fesm2020'
  Parsed request is a module
```

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ThibaudAV** [comment]
now sb start but i've this error : 
image

something to do with angular linker 🤷‍♂️ 🤷‍♂️

**Comment by ThibaudAV** [comment]
well now it seems to work for some of the storybook sotry but not all 
image


and if i copy angular dist to this  @yannbf 's project https://github.com/literalpie/sb-ng-performance/tree/ng-13 it works for all stories 

too magic for me 🪄  and i'm not sure what i'm doing

**Comment by yannbf** [comment]
Hey @ThibaudAV, @stefanoslig was taking a dab at this as well yesterday. Make both of you could collaborate or share some ideas?

**Comment by shilman** [comment]
For clarification, we currently support NG12 in the package without actually having an example in the monorepo. I assume we can do the same for NG13 in this case. @ndelangen can guide here if it's useful.

**Comment by ThibaudAV** [comment]
Yes, but it's not that easy. I think it's lucky for ng12

Summary of issues cc @shilman @yannbf @gaetanmaisse @ndelangen :

- Multi angular version 
Storybook is looking to be compatible with multiple versions of Angular (`"@angular/core": ">=6.0.0"`) 😱 
Storybook use Angular CLI private function to complete the webpack configuration
There is only one version of angular/* in the apps/angular project
And so the typescript sources is based on this version but with a lot of magic it works 🪄 

- Typescript version
As storybook and angular are not aligned on this one if we bump the `devDependencies` dependency of the `app/angular` project the build fail because during the build some types do not work in the current typescript version of storybook  
Error ex (not available in ts 3.9):
image


And all this makes the thing hard & long to maintain as we can't rely on typescript. And even the angular cli private properties change path and don't return the same thing ext... even between minor versions. And this is normal


I think we need to simplify this and find a way to make it more robust. especially since it's t's maintained by contributors. 

I have a few ideas: 
1.  Support only one version of angular at a time 
> The simplest. We can use angular cli types and private code.
> Make sure to run on at least one version 😁 
> On the other hand obliged to follow the versions of angular
> And for the typescript problem, I don't know 
 
 2. Go back to JavaScript (`i'm this old`) 
 > Separate the webpack preset in different file by angular version and add a main one that check the angular project version to use the right preset 
> No more type or build problem (it seems to me)

3. Play with alias yarn / npm 
```
    "@angular12-devkit/architect": "npm:@angular-devkit/architect@~0.1200.0",
    "@angular12-devkit/build-angular": "npm:@angular-devkit/build-angular@12.2.12",
```
 > Separate the webpack preset in different file by angular version and add a main one that check the angular project version to use the right preset 
> Allows to have the functional typescript by version 
> allows to make test I think
> Ask to do some magic to replace the aliases `@angular12-devkit/architect` -> `@angular-devkit/architect` after the typescript compilation

4. Don't use private code of angular cli !
> basically start angular without angular-cli and all those feature 
> create a custom webpack configuration and reproduce the necessary angular cli features for storybook 
> probably long to do 🤷‍♂️ 

5. Lobbying to the angular team 
> to find a way to combine the wepback config of storybook and angular cli

sorry for the long post 🥔 

There are surely other solutions, I would like to have feedback 🙏 🙏 🙏 . I can also make a mistake

**Comment by stefanoslig** [comment]
Hi @ThibaudAV . I was working the last days on this one. I had almost the same fixes as you. Finally, based on your branch I managed to have a working version with angular 13.0.0.

**Comment by juristr** [comment]
Hey, we from [Nx](https://nx.dev), are also currently in the process of updating all our tooling to make sure it works with Angular 13. Storybook is a blocker there atm :)

I tested this PR quickly today morning on an Nx 13 repo with the latest Angular 13 & Storybook. There are a few TypeScript tweaks missing which @stefanoslig had in his PR (which he closed now). So adding those locally it worked for me & fixes the ESM issues.

That said, I'm also curious for a timeline as we plan to release Nx with Angular 13 support soonish ..in like very soon 😅 . And we want Storybook to work there 🙂. 

Any way we can help? Also, would this be patched into some v6.3.x version or only go into 6.4?

**Comment by shilman** [comment]
@juristr we probably won't ship this with 6.3. we might ship it with 6.4 if we can figure something out in the next day or two. i'll see if i can get everybody in the same room to discuss including you cc @ThibaudAV @stefanoslig @ndelangen

**Pull request closed without merging**
