### PR TITLE
Addon-a11y: 'element' arg in config not ignored

### PR DESCRIPTION
**Pull request by Armanio**
Issue: #5945

## What I did
Fix process `a11y.element` arg in `addParamerers` call

## How to test
Run cra-kitchen-sink
Open `storybook/examples/cra-kitchen-sink/.storybook/config.js`
Add snippet
```
addParameters({
    a11y: {
      element: '#foo'
    }
  });
``` 
Reload page
axe must be throw error on incorrect element

- Is this testable with Jest or Chromatic screenshots?
no
- Does this need a new example in the kitchen sink apps?
no
- Does this need an update to the documentation?
no

### CODE REVIEW

**Comment by shilman** [comment]
@Armanio looking now. FYI, please label your PRs e.g. `Issue: #5945` in the first line. If it's labeled like that my script will comment on the issue when the package is published. Thanks!

**Review by shilman — APPROVED** [review]
LGTM!!

**Comment by Armanio** [comment]
I got it. 👍

**Review by gaetanmaisse — APPROVED** [review]

**Comment by shilman** [comment]
There are too many a11y changes so this will only be available in `5.1.0` alphas

**Pull request merged**
