### PR TITLE
Next.js: Avoid conflicts with the raw loader

### LINKED ISSUE #26991: [Bug]: Importing anything that contains a word `raw` in NextJS+Storybook project from ant-design makes every other import null
### Describe the bug

There is a weird bug that happens in a project with latest NextJS 14 + Stroybook  + Ant-Design. In Next everything works as expected but when I am trying to run storybook some imports from Ant-Design do not work. For instance this code works when I run NextJS server and doesn't work in Storybook (Drawer is null):

```
import { Drawer } from 'antd'

export default function Page() {
  return (
    <>
      <Drawer>test</Drawer>
    </>
  );
}
```

After some experimenting I found that problem arise only with ant-design components that have the word `raw` in them. So, importing Button works but D**raw**er doesn't.

Note: 
1. I am using `transpilePackages` and `optimizePackageImports` to make ant-design work with NextJS. So probably bug is somewhere in `@storybook/nextjs` 
2. Bug is reproducible with a few other packages. For instance `rxjs`. Maybe this is because of the next's internal optimizations for these packages
3. Everything works well with NextJS 13

### To Reproduce

[Reproduction repository](https://github.com/11bit/next-storybook-import-raw-bag)

Here I:
1. Installed nextjs, Storybook, Ant-Desigin
2. Added transpiration options for ant-design to [next.config.mjs](https://github.com/11bit/next-storybook-import-raw-bag/blob/main/next.config.mjs#L3)
4. Created a [test story](https://github.com/11bit/next-storybook-import-raw-bag/blob/main/stories/Page.tsx). It doesn't work until Drawer is removed

### System

```bash
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.asdf/installs/nodejs/21.7.3/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/21.7.3/bin/yarn
    npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm <----- active
    pnpm: 9.0.6 - ~/.asdf/installs/nodejs/21.7.3/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.93
    Safari: 17.4.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.9 => 8.0.9
    @storybook/addon-interactions: ^8.0.9 => 8.0.9
    @storybook/addon-links: ^8.0.9 => 8.0.9
    @storybook/addon-onboarding: ^8.0.9 => 8.0.9
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3
    @storybook/blocks: ^8.0.9 => 8.0.9
    @storybook/nextjs: ^8.0.9 => 8.0.9
    @storybook/react: ^8.0.9 => 8.0.9
    @storybook/test: ^8.0.9 => 8.0.9
    storybook: ^8.0.9 => 8.0.9
```

### Additional context

Error screenshot, but it just says that all imports from ant-design are empty:
error

### PR DESCRIPTION
**Pull request by seanparmelee**
Closes #26991

## What I did

When `@storybook/nextjs` configures the SWC loader, it updates the [raw loader rule](https://github.com/storybookjs/storybook/blob/7c433480c160c383c2cdeddac0d378368ed7e05c/code/builders/builder-webpack5/src/preview/base-webpack.config.ts#L77-L83) to exclude `__barrel_optimize__` requests, which pertain to Next's [`optimizePackageImports`](https://nextjs.org/docs/pages/api-reference/next-config-js/optimizePackageImports) feature. For example, in a project using `@mui/material`, a resource may look like

```
__barrel_optimize__?names=Box,Button,Divider,Drawer,List,useMediaQuery,useTheme!=!./node_modules/.pnpm/@mui+material@5.15.15_@emotion+react@11.11.4_@types+react@18.3.1_react@18.3.1__@emotion+style_6tay2ra76drsmamcoqb5ygip6u/node_modules/@mui/material/index.js
```

and the `Drawer` here would match the `/raw/` test, preventing the resource from being loaded correctly.

We could also just update the raw rule accordingly, but I figured since this is specific to Next.js and SWC, I put the logic in the `configureSWCLoader` function.

### Testing

Looking for guidance on how you'd prefer this change be covered. I've tested this using a storybook that's using `@storybook/nextjs` and `@mui/material` with a story that uses the `Drawer` component. Would you prefer to have an integration test for this specific scenario?

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

There is a reproduction in https://github.com/storybookjs/storybook/issues/26991 (https://github.com/11bit/next-storybook-import-raw-bag) that could be used to confirm [this story](https://github.com/11bit/next-storybook-import-raw-bag/blob/main/stories/Page.tsx) loads with these changes.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]
LGTM! 

@seanparmelee Thank you for your contribution. It is much appreciated 🥳

**Comment by valentinpalkovic** [comment]
@seanparmelee it seems the PR has introduced a regression to everyone, who sets up a custom @svgr loader: https://github.com/storybookjs/storybook/issues/27195#issuecomment-2119159011

Can't we use the `exclude` property instead of `test` to exclude barrel requests?

**Comment by seanparmelee** [comment]
Sorry about that @valentinpalkovic, yes `exclude` can be used instead. I can submit an PR with that change unless you're already planning to?

FWIW, we too are using `@svgr/webpack`, but we are mutating every loader similar to how you demonstrated in [your comment](https://github.com/storybookjs/storybook/issues/27195#issuecomment-2119159011).

**Comment by valentinpalkovic** [comment]
@seanparmelee That would be amazing!

**Pull request merged**
