### PR TITLE
try/catch package.json resolve - fixes #10955

### LINKED ISSUE #10955: Storybook beta blowing up since beta.7
**Describe the bug**
Ever since beta-6 I get the following error when trying to run storybook:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports"` It appears to be rooted in `getManagerWebpackConfig (/Users/kodmunki/source/kodmunki/ku4/web/ku4web-component/node_modules/@storybook/core/dist/server/manager/manager-config.js:83:18)`

**To Reproduce**
1. install beta.7+
2. run `start-storybook -s www,assets -p 6006` _(obviously you may not have www or assets)_

**Expected behavior**
Storybook should start as it has through version 5 and up to version 6.0.0-beta.6

**System:**
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Edge: 83.0.478.37
    Firefox: 76.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-actions: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-docs: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-google-analytics: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-knobs: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-links: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-notes: ^5.3.19 => 5.3.19 
    @storybook/addon-storyshots: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-viewport: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addons: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/react: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/theming: 6.0.0-beta.16 => 6.0.0-beta.16

### PR DESCRIPTION
**Pull request by MarkLyck**
This fixes #10955

Issue:

## What I did

Added safety around package.json resolve function.

## How to test

- Run storybook in a rollup project. It should NOT fail.

Without this fix, it fails with the error mentioned in #10955

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Can we log an error in the catch block? @ndelangen can you take a close look at this? Also deepscan errors

**Comment by ndelangen** [comment]
I'd like to understand why the JSON can not be found honestly.

**Comment by ndelangen** [comment]
Do you have a reproduction repo for me to inspect?

**Review by ndelangen — APPROVED** [review]

**Comment by michaelbayday** [comment]
We're not using rollup in our shared UI library, but it is a devdependency and storybook is throwing a warning of unable to find package.json for rollup when using version  >= 2.3.4

**Comment by akmoulai** [comment]
I'm using rollup with SB and I get the same as @michaelbayday 

```
WARN unable to find package.json for @rollup/plugin-node-resolve
WARN unable to find package.json for rollup
```

Seems like SB is trying to load the `package.json` for rollup. Is there a way to exclude it? (SB + CRA + Rollup, all vanilla and nothing special)

**Pull request merged**
