### PR TITLE
Fix/tooltip tools

### PR DESCRIPTION
**Pull request by ndelangen**
Issue:
- I found a couple of state & initial state bugs in the tool addons
- When switching panels/nav with hotkeys the tooltip would stick
- When clicking inside the preview the tooltip would stick

## What I did
Added an core-event for a PreviewClick
I'm not quite done, I wasn't able to successfully testing it.

### CODE REVIEW

**Comment by tmeasday** [comment]
Can we merge the bug fixes to the addons separately? 

I'm not sure about this technique, I think we can do this another way

**Comment by tmeasday** [comment]
So I have thought about this a bit. I think it is better for:

A. The `WithTooltip` component to setup its own global `keydown` listener (it does this for `click` already via the `react-popper-tooltip` lib. This will pickup keydowns inside the manager

B. We don't need to detect keydowns inside the iframe I don't think (you'd have to click or press a key first to get in there).

C. Maybe the tooltip component should also find all iframes on the screen (when it opens) and bind a `click` listener (and a `keydown` one too?) inside them. 

The technique of triggering a click via a message over the channel is a bit hacky for me and also will break if there are more iframes on the screen (which there may be one day)

**Comment by ndelangen** [comment]
@tmeasday Sure, good point, I removed the last 2 commits, so now it's just fixes on the tool addons

**Review by tmeasday — APPROVED** [review]
:+1:

**Comment by shilman** [comment]
@ndelangen This is not merging cleanly into `release/5.0` because it relies on code that's not part of the 5.0 release: `BackgroundSelector.tsx`. Mind taking a look?

**Comment by ndelangen** [comment]
Can you explain what I should do? Try to merge this into `release/5.0` ?

**Comment by shilman** [comment]
@ndelangen For now, nothing. After we get the next RC out I'm going to cherry-pick the PR that introduced `BackgroundSelector.tsx` and this PR into `release/5.0`. At that point I might enlist your help getting things working there depending on how it turns out.

**Pull request merged**
