### PR TITLE
Add react error overlay (based on #2900)

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: #2900

## What I did
Merged to this branch inside the organization for an easier fix of the middleware conflicts.

### CODE REVIEW

**Comment by igor-dv** [comment]
Not sure what should be done with the stories that throw the error on purpose (storyshots wise) + there is some code block in comments.

**Comment by Hypnosphi** [comment]
> Not sure what should be done with the stories that throw the error on purpose (storyshots wise)

Let's just ignore those

**Comment by igor-dv** [comment]
@Hypnosphi , something else here?

**Comment by Hypnosphi** [comment]
https://github.com/storybooks/storybook/pull/2900#issuecomment-362947703
https://github.com/storybooks/storybook/pull/2900#issuecomment-362961929

**Comment by ndelangen** [comment]
@Hypnosphi both comments refer to a merged PR, can this be merged as well?

I can't determine what is blocking this PR.

**Comment by Hypnosphi** [comment]
@ndelangen it's merged into this branch (`add-react-error-overlay`), not into `master`

You can run official storybook and reproduce both issues

**Comment by ndelangen** [comment]
@Hypnosphi something I can do here?

**Comment by Hypnosphi** [comment]
I'm not sure we really want it on our side, given that our error handling is now framework-agnostic

**Comment by ndelangen** [comment]
OK, so should we close?

**Pull request closed without merging**
