### PR TITLE
UI: Remove css zoom

### LINKED ISSUE #21302: [Bug]: Don't use css zoom in ZoomElement
### Describe the bug

The css [zoom](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) rule is a non-standard feature and should not be used.

I was rendering a full width and full height fixed div in a docsPage story.
I noticed that in firefox (it doesn't support zoom) it works as expected: the fixed div covers the story box. It does not overflow to the rest of the document page

image

In Chrome and Safari (they support zoom) zoom rule is used and the fixed div covers the entire docs page.

image

Firefox is using `transform: scale()` that [causes the current div to act as containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/transform). This is what i expect from a Story box.

Chrome and Safari are using zoom and we don't have the benefit of containing block functionality

### PR DESCRIPTION
**Pull request by Luk-z**
Closes #21302

## What I did

Remove the support of css zoom because it's a non-standard feature and should not be used as i described [here](https://github.com/storybookjs/storybook/issues/21302).

## How to test

Just create a story in a docs page with a fixed div (with top, left, bottom and right 0px).

## Checklist

- [X] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [X] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by SaurabhChauhan213** [comment]
git add init

**Comment by Integrayshaun** [comment]
Hi @Luk-z!

Could you share an example for us to look into this in more detail, please?

**Comment by Luk-z** [comment]
Hi @Integrayshaun , sorry for late response... Here the [example](https://stackblitz.com/edit/github-xu9bta).

As You can see I wrapped the 2 story inside a div, simulating Canvas story container using transform scale. In the Docs page using scale the result is more coherent with a canvas/container behavior.

**Comment by valentinpalkovic** [comment]
Hi @Luk-z,

Thank you for your contribution!

It seems, that you have some Typescript related issues on your branch: https://github.com/storybookjs/storybook/actions/runs/4718187330/jobs/8367516000?pr=21303#step:4:367

**Comment by Luk-z** [comment]
@valentinpalkovic fixed!

**Review by valentinpalkovic — APPROVED** [review]

**Comment by valentinpalkovic** [comment]
Causing unexpected behaviors in the following Github Issues:
- https://github.com/storybookjs/storybook/issues/23586
- https://github.com/storybookjs/storybook/issues/16774

**Pull request merged**
