### PR TITLE
feat: add accessibility on searchbar react-native

### PR DESCRIPTION
**Pull request by wilau2**
Make it easier to navigate between stories with detox.
(When list of story get big it's easier to navigate using the filter searchbar)

### CODE REVIEW

**Review by benoitdion — APPROVED** [review]

**Comment by ndelangen** [comment]
Thanks, what does testID do?

**Comment by wilau2** [comment]
@ndelangen 
It's an attribute test ID, a lot of modern e2e test framework recommend having some to interact with your app. 
- https://github.com/wix/detox
- https://github.com/cypress-io/cypress

It will normally keep your tests safe from css or js changes: 
https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements

You can check in the very same file I modified, it was already present on list item elements: 
https://github.com/storybooks/storybook/blob/ad8edd2d66515d171f78ceb7d9138efb15577f8f/app/react-native/src/preview/components/StoryListView/index.tsx#L58

**Comment by Gongreg** [comment]
@shilman, any reason we don't merge it? It is a non breaking change that can help for users using e2e tests with storybook.

**Comment by shilman** [comment]
@Gongreg We're in a feature freeze for shipping 5.1. Can merge non-bug changes if there's good reason, but otherwise this is a 5.2 feature

**Comment by Gongreg** [comment]
Got it @shilman. This one definitely doesn't break anything and helps people using detox or other e2e test tools. IMO we could silently add it to 5.1

**Review by shilman — APPROVED** [review]
ok!

**Pull request merged**
