### PR TITLE
added arrow to a11y addon HeaderBar

### PR DESCRIPTION
**Pull request by jmiazga**
Issue: #3641

## What I did
Added arrow to indicate button is expandable. Rotate arrow when a11y violation is expanded.

Closed:
image

Expanded:
image

## How to test

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps?
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by Keraito** [comment]
I totally forgot about this one, thanks for picking it up!

**Comment by jmiazga** [comment]
@Keraito It looks like a build step failed, I don't think the problem was introduced by me. Can you check it out?

**Comment by Hypnosphi** [comment]
Let's use the same symbol as in sidebar stories list: https://github.com/storybooks/storybook/blob/master/lib/ui/src/modules/ui/components/stories_panel/stories_tree/tree_decorators.js#L18

**Comment by Keraito** [comment]
Hey @jmiazga, I don't think you have to worry about that for now. I agree with the above comment that it's better to use the svg component that already exists in the project. That was also the direction that I took when I was looking into the issue, but the main difficulty is getting the proper properties for it. Would you like to give this approach a shot?

**Comment by jmiazga** [comment]
@Hypnosphi @Keraito I'll take a look at using whats in react-icons

**Comment by Keraito** [comment]
@jmiazga I think the easiest is to use the `IoChevronRight` that was linked to, which is the same as currently used in the sidebar stories list. But if you can find something better due to specific reasons, go ahead.

**Comment by jmiazga** [comment]
@Keraito yep thats the plan

**Comment by jmiazga** [comment]
@Keraito I can use ```IoChevronRight``` and rotate it with css, or swap it with ```IoChevronDown```, do you have a preference?

**Comment by jmiazga** [comment]
Here are some updated screen grabs:

image

image

**Comment by jmiazga** [comment]
@Keraito any feedback on this?

**Comment by Hypnosphi** [comment]
I'd say 1px higher in collapsed state

**Comment by jmiazga** [comment]
@Hypnosphi Made the change, here are some updated screen grabs

image

image

**Comment by igor-dv** [comment]
I think should wait for the #3628 merging, it much easier to solve conflicts here.

**Comment by jmiazga** [comment]
@igor-dv Ill keep an eye on #3628 and update from master once it's merged in.

**Comment by Hypnosphi** [comment]
How do you feel about adding some CSS transition?

**Comment by jmiazga** [comment]
@Hypnosphi I can add something. Is there a similar transition somewhere you'd like to replicate?

**Comment by Hypnosphi** [comment]
Something like `transition: transform 0.3s ease-in-out;` should work

I also don't really like how it jumps when expanding because of appearing scrollbar (on mac with touchpad you can observe that when enabling "Show scrollbars: always" in system settings -> general). Maybe we shouldn't use `text-align: center` there?

**Comment by igor-dv** [comment]
FYI, theming PR was merged.

**Comment by ndelangen** [comment]
@jmiazga Can I help you this this PR in a merge-able state?

**Review by danielduan — APPROVED** [review]

**Comment by danielduan** [comment]
thanks for the PR. when you get a chance, please follow up with another PR like you've mentioned.

**Comment by ndelangen** [comment]
@jmiazga There are some more improvements possible to the a11y addon, don't you think?

Are you on the storybook slack? If you'd like we could discuss them there?
https://now-examples-slackin-rrirkqohko.now.sh/

**Pull request merged**
