### PR TITLE
Add dotenv support for storybook in vue and react

### PR DESCRIPTION
**Pull request by RWOverdijk**
Issue:

## What I did

Added support for dotenv

## How to test

Add to a new CRA app and use the .env files.

## Misc

I guess this could be added to the docs but I wouldn't know where. Busy busy so if it's a must I'll look for it this weekend.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
I didn't see any lock files when adding this.

**Review by Hypnosphi — APPROVED** [review]

**Comment by Hypnosphi** [comment]
What happens when you run `yarn bootstrap --reset --core --docs` ?

**Comment by RWOverdijk** [comment]
My bad. Pushed.

**Comment by danielduan** [comment]
is there any way to silence the error when there isn't a `.env` file?

It's an optional file so I feel like the `Failed to load ./.env.` is misleading @RWOverdijk

**Comment by priley86** [comment]
+1 for not requiring `.env` and throwing a warning w/o it.

**Pull request merged**
