### PR TITLE
Update React to 16.1.0

### PR DESCRIPTION
**Pull request by Hypnosphi**
[Release notes](https://github.com/facebook/react/releases/tag/v16.1.0)
Example app seems to work OK

I would also consider hoisting all those React `devDependencies` to root package manualy, so that they are more manageable. `app/vue` (and other non-react apps) still need direct `dependencies` to React though.

@storybooks/team, what do you think?

### CODE REVIEW

**Comment by danielduan** [comment]
Please test the crna react-native as well. React 16 isn't officially supported by crna, let alone 16.1: https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md

**Comment by Hypnosphi** [comment]
This PR doesn't actually update anything in crna example. In `app/react-native`, it's `devDependencies`, so they don't get installed in apps, either.

I think that, given the concerns you brought up, we shouldn't update React in CRNA example in the same PR.

Any thoughts about the hoisting proposal?

**Comment by Hypnosphi** [comment]
Anyway, I chacked that CRNA example works on this branch

**Review by ndelangen — APPROVED** [review]

**Comment by Hypnosphi** [comment]
@ndelangen how do you feel about moving all the react `devDeps` to root?

**Pull request merged**
