### PR TITLE
Update version to `8.0.0-alpha.0`

### PR DESCRIPTION
**Pull request by kylegach**
## What I did

Ran `cd scripts && yarn release:version --exact 8.0.0-alpha.0` against this branch, which is based on `release-8-0`.

The current version is causing problems when attempting to build `8.0` docs in `frontpage`.

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by ndelangen** [comment]
Accepting this would cause merge conflicts every time we merge `next` into this branch.

How important is this @kylegach, you didn't specify which problems are occuring.

**Comment by kylegach** [comment]
@ndelangen — Per this work, https://github.com/storybookjs/frontpage/pull/603, we want to publish `8.0` docs so that we can link to the URLs directly in error and deprecation messages. But we do _not_ want that version to appear in the version selector yet (because there's no actual version released). The issue is that frontpage uses the version in `code/package.json` for its logic, so this code having a version of `7.6.0-alpha.x` causes that to break, because it doesn't match the `8.0` expectation.

**Comment by shilman** [comment]
@kylegach didn't we publish the 7.0 docs ahead of the 7.0 release & have it show up in the version selector with some kind of "future" formatting?

**Comment by kylegach** [comment]
@shilman — Yes, we did. I'm having a hard time remembering how exactly we did that, or finding any evidence for it. I think we had three active versions in the monorepo: latest, e.g. `6.3`, on `main`; next, e.g. `6.4`, on `next`, and future, e.g. `7.0` on `future`.

But `frontpage` requires a `release-x-x` branch to do its thing, and I cannot find anywhere that we mapped `future` to `release-7-0` (unless we just did that manually for while?).

In any case, that `future` branch would've had to have had a version beginning with `7.0`, just as this branch needs one beginning with `8.0`. If I had to guess, the primary difference between the two was workflow related.

**Pull request closed without merging**
