### PR TITLE
UI: Make panel position a persistent preference

### PR DESCRIPTION
**Pull request by burhanuday**
Issue: https://github.com/storybookjs/storybook/issues/17938

## What I did

Made `layout.panelPosition` a `permanent` config

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by MichaelArestad — APPROVED** [review]
Nice work! Thank you!

**Comment by burhanuday** [comment]
@shilman can you help with merging this

**Review by shilman — CHANGES_REQUESTED** [review]
It looks like there are chromatic diffs. @JonathanKolnik can you please take a look?

**Comment by JonathanKolnik** [comment]
@shilman looks good to me. Not sure why this change would introduce that icon/why it wasn't there before, but it makes sense in the context of this story still because it is an icon that isn't explicitly excluded in the story.

**Review by shilman — APPROVED** [review]
Thanks @burhanuday and @JonathanKolnik ! 🙏

**Pull request merged**
