### PR TITLE
Maintenance: Provide packageManager when copying template files

### PR DESCRIPTION
**Pull request by yannbf**
This fixes the `generate-repros` workflow, which has been failing for a few days: https://github.com/storybookjs/storybook/actions/workflows/generate-repros.yml by a [regression](https://github.com/storybookjs/storybook/commit/d2c23c82abd09e2faac6355d761df7f1c7d99621) last week

### CODE REVIEW

**Comment by JReinhold** [comment]
Are you sure? I don't think I understand the code flow from this change to here, where I guess the error is happening

https://github.com/storybookjs/storybook/blob/next/scripts/sandbox-generators/generate-sandboxes.ts

But maybe I'm just misunderstanding.

**Comment by yannbf** [comment]
> Are you sure? I don't think I understand the code flow from this change to here
Yes, I'm sure.
- GH action trigger -> generate-sandboxes -> sbInit -> baseGenerator -> copyTemplateFiles -> getRendererDir -> resolveUsingBranchInstall -> packageManager.getRegistryURL() where packageManager is `undefined`

**Comment by yannbf** [comment]
Subsequent issue after this fix:

```🧬 generating React 17 Webpack5 (TS)
Trace: Error: Command failed with exit code 1: /home/runner/work/storybook/storybook/code/lib/cli/bin/index.js init --yes
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@babel/preset-env' imported from /home/runner/work/storybook/storybook/repros/react-webpack/18-ts/tmp/babel-virtual-resolve-base.js
```

**Review by JReinhold — APPROVED** [review]

**Comment by yannbf** [comment]
Subsequent error is caused by missing dependencies in the package.json generated from https://github.com/storybookjs/create-webpack5-react/. @ndelangen is fixing it

**Comment by yannbf** [comment]
That previous was fixed, and subsequent error is caused by pnp being enabled by default in the monorepo

**Comment by yannbf** [comment]
That issue is kind of fixed, but probably not the best solution. Subsequent issue is caused by Vue CLI sandbox:

```
Trace: Error: Command timed out after 300000 milliseconds: npx -p @vue/cli vue create . --default --packageManager=yarn --force --merge
Timed out
```

**Pull request closed without merging**
