### PR TITLE
Fixed addon knobs proptypes deserialization

### PR DESCRIPTION
**Pull request by Gongreg**
Issue: #1265

## What I did
Fixed proptype.
Deserialization doesn't return array anymore.

## How to test

https://github.com/jkempff/storybook-addon-knobs-proptypes-issue .

### CODE REVIEW

**Comment by shilman** [comment]
@Gongreg do you mind adding some examples to the `examples/cra-kitchen-sink` project to test this out?

**Review by ndelangen — APPROVED** [review]

**Comment by Gongreg** [comment]
@shilman, is the example project created by user is not enough? :)

**Comment by shilman** [comment]
@gongreg if it's checked in we can test it automatically in the near future

**Comment by Gongreg** [comment]
@shilman, ah, makes sense, I will just not be able to do that in the next few days.

**Comment by shilman** [comment]
@gongreg OK I'll just add it and merge then

**Review by shilman — APPROVED** [review]
LGTM!

**Pull request merged**
