### PR TITLE
Ability to add action decorator

### PR DESCRIPTION
**Pull request by ritz078**
A better solution for kadirahq/storybook-ui#14

This gives you more control over the data logged in the action logger. You can modify or pick the data from the arguments according to your needs. This is how you can use an action decorator :

``` js
import React from 'react';
import { storiesOf } from '@kadira/storybook';
import MyComponent from '../my_component';

storiesOf('MyComponent', module)
  .addActionDecorator((name, args) => args[0])
  .add('without props', () => (<MyComponent />))
  .add('with some props', () => (<MyComponent text="The Comp"/>));
```

You can also change the returned value based on action name.

Note: Make sure you return a valid data structure. Values like `'LOG' + args` or `args[0] + ', ' + args[1]` won't work for now.

### CODE REVIEW

**Comment by arunoda** [comment]
I get your point. This is a great concept. 
But we need some few stuff to be done, since this is a public API. 

Here are some of them:

* Add support for multiple decorators
* Add support for local and global apis
* Change the name as addActionDecorator
* Add support to the context

@mnmtanish could you help @ritz078 more on these stuff. 
May be add some inline comments.

**Comment by ritz078** [comment]
> Add support for multiple decorators
Don't see how it could be useful or its use case. In a single story you may have different actions with different names. you can return different data structures from the same decorator based on their name.
```js
import React from 'react';
import { storiesOf } from '@kadira/storybook';
import MyComponent from '../my_component';

storiesOf('MyComponent', module)
  .addActionDecorator((name, args) => {
    if(name === 'x') return args[0]
   else if(name === 'y) return args[1]
  })
  .add('without props', () => (<MyComponent  onClick={action('x')}/>))
  .add('with some props', () => (<MyComponent text="The Comp" onClick={action('y')}/>));
```

> Add support for local and global apis
According to me there are very little chances someone will want to define a global decorator for actions as actions will be different at different places but can't even rule it out. Can't we implement this if there's a demand. Implementing global API won't break anything. It will just be an addition.

> Change the name as addActionDecorator
Done

> Add support to the context
Same here. don't see the use case. action decorators are just data modifiers and I don't see how context plays a role here. Let me know if I am missing anything.

**Comment by mnmtanish** [comment]
Hi @ritz078 @arunoda 
I just created a branch in this repo and started a PR so it'll be easier to collaborate.
https://github.com/kadirahq/react-storybook/pull/317

**Comment by mnmtanish** [comment]
Even inside a kind there may be different types of actions. Checking them by story name also doesn't scale well does it?

Honestly, it's more flexible if we create and use custom actions. For an example, if user wants to send only the first argument with an action he can create a custom action and use it wherever he wants to.

```js
function firstArgAction(name) {
  const action = action(name);
  return (...args) => action(args[0]);
}
```

So an example story file will look something like below.

```js
import React from 'react';
import { storiesOf } from '@kadira/storybook';
import MyComponent from '../my_component';
import firstArgAction from './first_arg_action';

storiesOf('MyComponent', module)
  .add('without props', () => (<MyComponent />))
  .add('without props', () => (<MyComponent onClick={action('x')}/>))
  .add('without props', () => (<MyComponent onSubmit={firstArgAction('x')}/>))
```

**Comment by ritz078** [comment]
Fine then. I am closing this PR.

**Pull request closed without merging**
