### PR TITLE
Improve the warning given when using channel before it's defined

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: https://github.com/storybooks/storybook/pull/1514 fixed an issue where a "fake" channel that threw a warning broke RN. This left us without a warning

## What I did

Instead, let's throw directly and check for that in the RN initializer.

## How to test

Check RN-vanilla, plus general testing (CI + CRA-ks).

## Note

This is targeted to #1514, we should change the target when that is merged.

Sometimes it's possible things grab the channel and don't access it, which might be a problem.

Another approach would just be to log a warning rather than throwing.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
LGTM, ready to merge @tmeasday

**Review by ndelangen — APPROVED** [review]

**Comment by tmeasday** [comment]
Merge to `master` @ndelangen ?

**Comment by ndelangen** [comment]
Ow I didn't notice this isn't actually based on master.

In that case, we first need to rebase on master, or merge into it's current base, and proceed from there.

This particular change look good to me, I haven't seen #1509-fix-react-native-example

**Comment by tmeasday** [comment]
That's been merged I think. Let me mess with the PR

**Comment by tmeasday** [comment]
@UsulPro -- why does it fail? In what context? Storyshots?

**Comment by UsulPro** [comment]
@tmeasday it fails if I run Jest test which imports this file. Actually I already have fixed this just by removing this line inside the not covered code

**Comment by tmeasday** [comment]
A Jest test -- is it storyshots or something else?

If something else perhaps it needs to setup a fake channel like SS does?

**Comment by UsulPro** [comment]
I faced it in #1501 (addon-info)
But the easiest way to reproduce it -- just insert `const channel = addons.getChannel();` in `*.test.js` and run Jest. 
Actually, I agree - fake channel it the best and right way to deal with it. In my case, I don't test part of code related to channel since it's a very small piece of code so I left it uncovered. Maybe I should write a test for that later.

**Comment by tmeasday** [comment]
Yeah i'm not sure. I couldn't figure out a better way to warn people about the `addons.getChannel() = undefined` problem (which otherwise leads to a vanilla "can't access X on undefined" issue), and how they might solve it

Fake/mock channel seems pretty reasonable. With jest you can do it with one line I reckon.

**Comment by ndelangen** [comment]
With 4.0 I will change channel to be a Promise

**Pull request merged**
