### PR TITLE
Fix links addon examples

### PR DESCRIPTION
**Pull request by Hypnosphi**
Issue: Examples for links addon are broken

### CODE REVIEW

**Review by igor-dv — APPROVED** [review]
I think other examples are broken too

**Comment by Hypnosphi** [comment]
> I think other examples are broken too

How? Why?

**Comment by igor-dv** [comment]
After I've separated all the examples in the other apps, I didn't check if links are working 😓 So probably they are not.

**Comment by Hypnosphi** [comment]
Can you check it then?

**Comment by igor-dv** [comment]
Yep, tomorrow though.

**Pull request merged**
