### PR TITLE
Vue: Tweak vue app

### PR DESCRIPTION
**Pull request by kazupon**
Issue:

## What I did
Refactoring of vue app

## How to test
- `cd examples/vue-kitchen-sink`
- `npm link ../../app/vue` 
- `npm run storybook`

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]
LGTM

**Comment by ndelangen** [comment]
@kazupon I 'rebased' this unto the 3.2 branch. I had some merge conflicts on the `package.json`s. Can you check if all the changes you made are still in place and working correctly?

👍

**Comment by kazupon** [comment]
@ndelangen Thanks! I checked ! OK! 🙆

**Review by shilman — APPROVED** [review]
Tested and merging! Will release a new alpha soon!

**Pull request merged**
