### PR TITLE
Merge `master` into `shilman/refactor-core`

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: #2241 was out of date

## What I did

Merged `master`. Also re-applied #2349 in ad97f325c

## How to test

Please test all 3 web-based frameworks, especially around HMR and the issues explored in #2349

### CODE REVIEW

**Comment by tmeasday** [comment]
We could also just merge this directly into `master`, if that is preferred.

**Comment by igor-dv** [comment]
Oh, man 🤕 ...

**Comment by tmeasday** [comment]
I'm not sure how best to show the diff between this branch and @shilman's? Perhaps I should just change the base of this to `master`?

**Comment by igor-dv** [comment]
I think better merge it to #2241 and we will review it again there

**Comment by ndelangen** [comment]
```
/tmp/storybook/app/angular/src/client/index.js
  1:56  error  getStorybook not found in './preview'  import/named

/tmp/storybook/app/vue/src/client/index.js
  7:56  error  getStorybook not found in './preview'  import/named
```

**Comment by tmeasday** [comment]
oops, sorry fixed this but forgot to push last night.

**Comment by tmeasday** [comment]
I think everyone is sufficiently weirded out by this PR, I will change the base to `master`.

**Comment by tmeasday** [comment]
Hopefully a little easier to understand now.

**Comment by tmeasday** [comment]
This is passing now.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
