### PR TITLE
don't clean outputDir by default

### LINKED ISSUE #1608: build-storybook: Improve file deletion
I found out that `build-storybook` appends `static` to the folder name, so:

```
build-storybook -c storybook -o storybook/static
```

Spouts everything to `storybook/static/static`. I just wanted to put everything storybook related inside the `storybook` directory, so I assumed that:

```
build-storybook -c storybook -o storybook
```

Would just make a `static` folder on the `storybook` folder.

But instead, it deleted everything and spouted an error: `Create a storybook config file in "storybook/config.js`.

I accidentally got all of my uncommitted code deleted :(.

## Suggestion

Delete only the files inside the `static` folder.

### PR DESCRIPTION
**Pull request by Hypnosphi**
Fixes #1608 

After this change, `outputDir` is cleaned only if an explicit `--clean` argument is passed, which prevents the unintended loss of user's data

### CODE REVIEW

**Comment by igor-dv** [comment]
IMO it's a breaking change

**Comment by Hypnosphi** [comment]
Well, formally any bug fix is a breaking change, as it removes some behaviour

**Comment by igor-dv** [comment]
Actually I rely on it, but I've seen this PR =)

**Comment by Hypnosphi** [comment]
I think I'll make a "non-breaking" version of this PR later today

**Comment by Hypnosphi** [comment]
It will clear only webpack directory, as was suggested in the issue. Other files don't have hashes in their names, so they will just be overwritten, and the behaviour will stay effectively the same

**Comment by danielduan** [comment]
Closing this because there hasn't been any activity here for a while. Feel free to reopen when this is ready for discussion again.

**Pull request closed without merging**
