### PR TITLE
Web-components: Support lit 2 with back-compat

### PR DESCRIPTION
**Pull request by Westbrook**
Issue: refs #13489

## What I did
Use split versions of `lit-html` and `lit-element` pointing to the pre-`lit@2.0` versions that support the `isTemplateResult()` helper.

I checked out the `@storybook/lit` build, and I'm not sure what it's over all goals are, but having it separate seems like a weird play in the context of the x-compatibility story of web components, but happy to revisit if not. 

## How to test

- Is this testable with Jest or Chromatic screenshots? By testing the `@storybook/web-components` examples.
- Does this need a new example in the kitchen sink apps? Uses the `@storybook/web-components` examples.
- Does this need an update to the documentation? Possibly?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
@gaetanmaisse @brion-fuller can explain more fully, but the rough goals of the `@storybook/lit` project is first-class support for lit2 including some features not supported in web-components such as:
- addon-docs dynamic snippet support
- HMR support
- modern custom-elements support
- plus a variety of details such as args spreading

The rationale behind the rename is to make the lit connection more explicit. Just like you can use `@storybook/html` to write stories for web-components, you can also use lit. The idea is to phase out `@storybook/web-components` in favor of `@storybook/lit` or other variants (e.g. `@storybook/stencil`). If you think this is a bad direction, I'd love to discuss. We're still in early alpha with it, and nothing's set in stone yet.

**Comment by shilman** [comment]
@gaetanmaisse @brion-fuller can explain more fully, but the rough goals of the `@storybook/lit` project is first-class support for lit2 including some features not supported in web-components such as:
- addon-docs dynamic snippet support
- HMR support
- modern custom-elements support
- plus a variety of details such as args spreading

The rationale behind the rename is to make the lit connection more explicit. Just like you can use `@storybook/html` to write stories for web-components, you can also use lit. The idea is to phase out `@storybook/web-components` in favor of `@storybook/lit` or other variants (e.g. `@storybook/stencil`). If you think this is a bad direction, I'd love to discuss. We're still in early alpha with it, and nothing's set in stone yet.

**Comment by anoblet** [comment]
@shilman Is there any way we could merge this for the time being, until `@storybook/lit` is figured out?

**Comment by shilman** [comment]
@anoblet we're meeting with @Westbrook @daKmoR etc on thursday to figure out a path forward on this

**Review by gaetanmaisse — APPROVED** [review]
🚀  LGTM

@shilman I updated a bit the e2e tests to have both lit 1 + 2, it also means we have a repro config for Lit 2. Before any public announcement, I would like to make more test with both Lit 1 + Lit 2 based projects (and try to migrate my company project 😉 ).

Note: SB WC + Lit 2 will not work out of the box with Yarn in PnP mode as SB is doing imports from `lit-html` directly. For now, the recommended workaround is to add `lit-html` as dep to satisfy SB WC peer dependency. We will be able to simplify/fix that easily when `lit-*` will be deprecated in favour of `lit`.

**Review by shilman — APPROVED** [review]
Looking great @Westbrook @gaetanmaisse 💯

**Comment by gaetanmaisse** [comment]
Note: Depending on the package manager used and the dependency hoisting it can be necessary to add `lit-html` 2.x to your dev dep to make Storybook Web Components work with Lit 2. I will be working on improving that soon.

**Pull request merged**
