### PR TITLE
Vite/React: Align with webpack react docgen

### PR DESCRIPTION
**Pull request by joshwooding**
Issue:

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by IanVS — APPROVED** [review]
This looks good to me, but we'll probably need to wait for CI to get fixed on `next` before we can get a good CI run and merge.

**Comment by yannbf** [comment]
Hey @ndelangen @IanVS seems like you might have to discuss a little more regarding this solution, please don't merge before that is settled. Thanks!

**Comment by IanVS** [comment]
For what it's worth, here is the webpack version that this is aligning with: https://github.com/storybookjs/react-docgen-typescript-plugin/blob/next/src/index.ts

**Comment by IanVS** [comment]
@ndelangen's idea is to detect (or maybe even prompt!?) the use of typescript during project `init`, and set the `typescript. reactDocgen` option explicitly, so then we don't need to figure it out each time at runtime, and can just use the setting.

**Comment by joshwooding** [comment]
> @ndelangen's idea is to detect (or maybe even prompt!?) the use of typescript during project `init`, and set the `typescript.reactDocgen` option explicitly, so then we don't need to figure it out each time at runtime, and can just use the setting.

Is it worth making this change to fix the behaviour of the alpha in the short term or is this something that would happen soon?

**Comment by ndelangen** [comment]
I don't have an estimate of when that suggestion will happen @joshwooding, so If you think this change will make an improvement, we should add the improvement for now 👍

**Pull request merged**
