### PR TITLE
Update: [#17934] CLI docs

### PR DESCRIPTION
**Pull request by SulthanNK**
Issue: #17934

## What I did

- Replaced `npx sb` to `npx storybook` command on both documentation and code.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [x] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
We're going leave this open for now. We are looking at resolving this another way for Storybook 7.0 so either `sb` or `storybook` will work as expected. Thank you for making these changes.

**Review by kylegach — APPROVED** [review]
Thanks for this, @SulthanNK. While we do plan to try to fix the issue with the `sb` command, we've decided that `storybook` will be the canonical API and it makes sense to update the docs accordingly in the meantime. We appreciate the contribution!

**Comment by kylegach** [comment]
I think the CI errors are unrelated to these changes, so I'm going to merge. Thanks again!

**Comment by SulthanNK** [comment]
That's sweet!!! Thanks, @kylegach  Glad to contribute to this awesome project. 😊

**Comment by jonniebigodes** [comment]
@SulthanNK, one thing related to this pull request that I wanted to address, if you could message me on our Discord [server](https://discord.gg/storybook) (same username), I'd appreciate it—looking forward to hearing from you. 

Hope you have a great week.

Stay safe

**Comment by SulthanNK** [comment]
Hi, @jonniebigodes I tried to connect with you in discord. But, Didn't get your username on the discord server. Is that any other way to communicate with you?

**Comment by jonniebigodes** [comment]
@SulthanNK, when you're able, could you check your Twitter messages? I've just messaged you in there.

**Comment by SulthanNK** [comment]
Sure, I'll check

**Pull request merged**
