### PR TITLE
CLI/Svelte: add interactions to cli template

### PR DESCRIPTION
**Pull request by italoteix**
Issue: https://github.com/storybookjs/storybook/issues/16722

What I did
Similar to PR https://github.com/storybookjs/storybook/pull/17345. Added interactions to Svelte cli template.

How to test
Build cli locally and run repro to select Svelte as a framework

 Is this testable with Jest or Chromatic screenshots?
 Does this need a new example in the kitchen sink apps?
 Does this need an update to the documentation?
If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by j3rem1e — APPROVED** [review]

**Comment by yannbf** [comment]
Hey @j3rem1e do you happen to have any idea why an error like that would happen in the svelte project? It does work on other projects i.e. React

**Comment by j3rem1e** [comment]
Honestly.. I don't know ^^ 
I am lost with the cjs/mjs and type:"module" things.

However, I reproduce this issue easly in addon-svelte-csf by upgrading to @storybook/testing-library 0.0.10. And a fix is to add this rule to the configuration of webpack : 

```
{
  test: /\.mjs$/,
  include: /node_modules/,
  type: 'javascript/auto'
},
```

**Comment by yannbf** [comment]
This is good now, the problem was circumvented in a new release of `@storybook/testing-library`. Thanks @j3rem1e for the tip, the problem is in `@testing-library/dom` and might take some time to be fixed.

**Comment by jonniebigodes** [comment]
@italoteix if you could message me (same username) on our [Discord Server](https://discord.gg/storybook) I'd appreciate it as I would like to follow up on this pull request and the other one you created that includes the interactions for Preact. Looking forward to your message.

Hope you have a great weekend!

Stay safe

**Pull request merged**
