### PR TITLE
Emit messages when stories fail to render

### PR DESCRIPTION
**Pull request by tmeasday**
Issue:

There is no way for external tools or the manager context to know when a story fails to render

## What I did

Emitted two events when the story errors or throws.

## How to test

I added stories for the two cases, however there are a couple of problems/questions:

1. The current use of emotion's `ThemeProvider` in official storybook means that my "error" story ends up throwing rather than triggering the react layer's error code. Any ideas on how to work around this @ndelangen? -- I don't want this decorator to apply for this story -- Perhaps we need to do something hacky like `addDecorator(story, ({kind})) => kind === 'Errors' ? story() : <ThemeProvider>...)`

2. I'd like to also throw the error if the story *throws sometime after the initial render*. Is this out of scope? It would be useful for Chromatic to know that a component has errored even if it does it async. This would require work from all the view layers so perhaps is a separate PR. Could be out of scope for storybook in any case.

3. Is there a way to test the event is emitted correctly?

### CODE REVIEW

**Comment by ndelangen** [comment]
Please explain why the `<ThemeProvider>` is involved here at all?

Would a try-catch decorator work here?

**Comment by tmeasday** [comment]
> Please explain why the <ThemeProvider> is involved here at all?

Sorry, that was a bit low on detail.

So the React integration has some code that calls `setError` if a story returns something that is not renderable by React. However, the use of the `<ThemeProvider>` decorator means that when a story wrapped by it returns something not renderable, the `ThemeProvider` internally breaks and an exception is thrown. Ultimately this leads to `setException` being called (as you can see from this PR, there is a subtle difference in the meaning).

I think we need a story that results in `setError` being called. AFAICT, the only way we can make this happen is to not apply the decorator to this story. Can you think of a better way than my ternary above?

**Comment by tmeasday** [comment]
What do you think @ndelangen? Also any thoughts on how to test it?

**Comment by tmeasday** [comment]
I added a test and sorted out the theming thing (let me know if you are happy with that @ndelangen)

**Comment by igor-dv** [comment]
Yeah, it's a nice API. What if you would like to exclude stories from one test but include them into another one?

**Comment by tmeasday** [comment]
> What if you would like to exclude stories from one test but include them into another one?

Do you mean in a different "suite"? We could also add something like `{ storyshots: { suite: 'X' } } ` -- would that be good?

**Comment by tmeasday** [comment]
This is ready to merge I think, we can add the params API to storyshots later https://github.com/storybooks/storybook/issues/4010

**Review by ndelangen — APPROVED** [review]

**Comment by thedamon** [comment]
I'm confused... is this now a feature of storyshots? 
If so.. a way to distinguish between storyshots and imageSnapshot from storyshots-puppeteer in these story options would be a, maze, ing.

**Pull request merged**
