### PR TITLE
Build: Bundle @storybook/cli with tsup

### PR DESCRIPTION
**Pull request by IanVS**
Issue:

Refs: https://github.com/storybookjs/storybook/issues/18732

## What I did

Converted `@storybook/cli` to use tsup build script

## How to test

CI?

### CODE REVIEW

**Comment by IanVS** [comment]
Getting `Error: Couldn't find template dir` in the angular e2e tests, but don't know why.

**Comment by ndelangen** [comment]
I can explain.. 
https://github.com/storybookjs/storybook/blob/6f4ca1785d6838e2cb1f9bb0669c37df801e09a6/code/lib/cli/src/generators/ANGULAR/index.ts#L44

...will be the problem

in the bundled mode, this will not point to the right path.. in the bundled version it will point to `./dist` and that will not contain the te templates dir.

Screen Shot 2022-09-08 at 12 46 51

See that `template-csf` dir? That's what's missing.

We'll need to move that to the root of the repo similar to how we moved `rendererAssets` to the root of the package:

Screen Shot 2022-09-08 at 12 49 16

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Wow this is awesome!!! Thank you @IanVS ❤️

**Comment by ndelangen** [comment]
@shilman can we get this in an alpha release? It's a big deal.

**Comment by shilman** [comment]
@IanVS @ndelangen 

https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.33

**Pull request merged**
