### PR TITLE
Docs: E2E tests for Source block update fix

### PR DESCRIPTION
**Pull request by chakAs3**
Closes #

## What I did

this an e2e to for  sourceSnippet should faild if the source is not changing back to previous value

should be merged after  #22807

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by chakAs3** [comment]
So @shilman, you can see it is failing now on next branch.
to reproduce it is easy:  toggle the source on Button story and   change the label  to => `Button1` then => `Button` => `Button1`  , keep switching between these 2 labels, the snippet will never update

**Comment by tmeasday** [comment]
Thanks for the repro @chakAs3 very helpful!

**Review by shilman — APPROVED** [review]
Approved, with caveats discussed in https://github.com/storybookjs/storybook/pull/22807 and comment to the code that I've added. Thanks so much @chakAs3 and @tmeasday for working this out. 🙏

**Review by chakAs3 — COMMENTED** [review]
@shilman  I need to look deeper into the Block implementation, it seems an easy task, but I'm not aware of the reasons behind tell implementation.
In my opinion, The block should be only responsible for how the snippet will be rendered ( layout, design aspect+ show/hide/copy actions ). the Optimisation should be done in the decorator level. which is the case I guess at least for Vue, we only fire the RERENDRED_SNIPPET event if the args are changed.

**Pull request merged**
