### PR TITLE
Addon-viewports: Fix initial load state

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/11548

## What I did
- CHANGE code to respect the existing state in useAddonState

## how to test
- load official example
- go to `/?path=/story/addons-viewport-custom-default-kindle-fire-2--overridden-via-with-viewport-parameterized-decorator`

expected: the story loads in the 'ipad' viewport immediately

### CODE REVIEW

**Comment by ndelangen** [comment]
@shilman merge and fix using global args in 6.1?

**Comment by gianpaj** [comment]
Could this fix be backported to 6.0.x? or what's the process to request that?

If it's already on a todo list, which Issue/PR I can I subscribe to, to know when it's fixed on 6.0.x?

Thanks :)

**Comment by shilman** [comment]
@gianpaj it won't be backported. we're releasing 6.1 this week

**Comment by gianpaj** [comment]
great! thanks so much for letting me know

**Pull request merged**
