### PR TITLE
feat: adds new app "web-components"

### LINKED ISSUE #4958: Support for lit-element with storybook/polymer
**Is your feature request related to a problem? Please describe.**
`lit-element` seems to be the next evolution of polymer, but using the @storybook/polymer package with `lit-element` is not working out of the box.

**Describe the solution you'd like**
There is a little configuration that must be added in the webpack config file in order to make the storybook work with `lit-element`.

**Describe alternatives you've considered**
You may override the webpack configuration yourself (in the `.storybook/webpack.config.js` file) with:
```js
module.exports = (baseConfig, env, config) => {
  config.module.rules[0].exclude = /node_modules\/(?!(lit-html|@polymer)\/).*/;
  return config;
};
```

**Are you able to assist bring the feature to reality?**
The solution is to add the previous exclude line directly in the webpack configuration.

**Additional context**
The exclude regexp may contain more elements like `/node_modules\/(?!(@webcomponents\/shadycss|lit-html|@polymer|@vaadin|@lit)\/).*/` (discussion here: https://github.com/Polymer/lit-element/issues/54#issuecomment-439901575).

### PR DESCRIPTION
**Pull request by daKmoR**
hey there 🤗 

happy Hacktoberfest 💪 

closes: https://github.com/storybookjs/storybook/issues/4958 https://github.com/storybookjs/storybook/issues/6208

## What I did

- [x] Added a new app called `web-components`
- [x] Added a preset for addon-docs 
- [x] Added a kitchen sink example
- [x] Transpiling code setup (e.g. most code is es7 even in node_modules so we need to mark that and compile it => also added info to the readme how you can add your own packages)
- [x] Added to generator
- [x] ~~How to handle HMR? in the kitchen sync I currently force a hard refresh => I am using this since quite a while and it works fine even for bigger apps~~
  => documented howto add page refresh  

It is sort of an alternative to https://github.com/storybookjs/storybook/pull/7731. 

## How to test

- Open kitchen sink example

### CODE REVIEW

**Comment by hsablonniere** [comment]
I've been using hard refresh instead of HMR on our WC based storybook: works great.

https://www.clever-cloud.com/doc/clever-components/?path=/story/atoms--cc-button

**Comment by daKmoR** [comment]
@hsablonniere how did you implement the hard refresh?

**Comment by shilman** [comment]
Great work @daKmoR !!! Love that it includes the docs integration out of the box ❤️

**Comment by daKmoR** [comment]
anything else I can do to help?

I'm not really sure what that CI "Dangerfile" error is? It shows something about `package-lock.json` but we are only using yarn here right?

if there is no easy way of using full page reloads (instead of HMR) via the preset config then it would also be fine to "just" document it for now 🤗

**Comment by ndelangen** [comment]
Danger doesn't seem to work with forks:
https://help.github.com/en/articles/virtual-environments-for-github-actions
https://github.community/t5/GitHub-API-Development-and/Resource-not-accessible-by-integration-when-requesting-GitHub/m-p/14027#M182

**Review by ndelangen — APPROVED** [review]

**Comment by daKmoR** [comment]
So I updated and added all the needed documentation to get started. I also rebased to latest next branch.

@shilman @stijnkoopal may I request your review/approval 🤗 

please let me know if there is anything else I should do 🤗

**Comment by daKmoR** [comment]
new week new energy 🤗 rebased for your convenience 🤗

**Review by shilman — APPROVED** [review]
So awesome. Let's merge this if it's ready!

**Comment by hsablonniere** [comment]
@daKmoR Not so sure but I use the @storybook/html and when I save, it does a hard refresh.

**Comment by ndelangen** [comment]
🎉

**Comment by ericclemmons** [comment]
Great work everyone!  This will help converting my React components + stories to Stencil. 🤞

**Comment by steel** [comment]
I wrote this little diddy to get HMR working with our custom elements in storybook. https://github.com/polleverywhere/hmr-custom-element

If you are using Sass, also be sure to enable `hmr` in the `MiniCssExtractPlugin` if you are using that.

**Pull request merged**
