### PR TITLE
Fix placement of notificationistList on docs page

### PR DESCRIPTION
**Pull request by lonyele**
Issue: #7289 

## What I did
I pass `placement` object to `NotificationList` so that it renders inside of Component wrapper.

Now it looks like this. I left last one `placement` as it is because I thought that is an intended result though I feel like things can be improved
Screenshot_2019-07-04 Storybook(1)

### CODE REVIEW

**Comment by lonyele** [comment]
@shilman @ndelangen  (sorry)I didn't' mean to perster you guys, would you review my PRs? If something looks wrong or implementation is bad please let me know. If it is something I can do it, I definitely can apply feedbacks. Because I have 4 PRs right now I'll just write here once for a simple ping. 

#7241 I checked that there are not many places using `setState`, but for this case it is needed?
#7327 There is one chromatic result that looks bad, but on my machine and now deployment looks ok. Is there a possibility that chromatic result can be wrong?(maybe a bug?)
#7200 Everything looks fine except the now deployment. What should I do to fix this one?

**Comment by shilman** [comment]
@lonyele Thanks for the ping and sorry for the delay on this. I'll take a look at them tonight.

**Review by shilman — APPROVED** [review]
LGTM

**Comment by lonyele** [comment]
Thanks! as you already know. I'm a junior level... I try hard not to take others times away while doing some PRs, but many times it is just a hope...

**Pull request merged**
