### PR TITLE
Core: Fix generated entry to import at top of file

### PR DESCRIPTION
**Pull request by shilman**
Issue: #9397 

## What I did

Reorder the file to get rid of error

## How to test

See issue. (NOTE: didn't test, but looks like a no-brainer)

### CODE REVIEW

**Review by mrmckeb — APPROVED** [review]

**Comment by Kamahl19** [comment]
@shilman  I can confirm this fixes the issue (changed it locally) although I am getting another one, I will continue in my original Issue

**Comment by Kamahl19** [comment]
@shilman you also need to change this
```
import { configure, addDecorator, addParameters } from '@storybook/${framework}';
```

to
```
import { configure } from '@storybook/${framework}';
```

to avoid these warnings
```
WARNING in ./storybook/generated-entry.js
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):

  Line 2:27:  'addDecorator' is defined but never used   @typescript-eslint/no-unused-vars
  Line 2:41:  'addParameters' is defined but never used  @typescript-eslint/no-unused-vars
```

**Comment by pribilinskiy** [comment]
Hey @shilman I believe this issue https://github.com/storybookjs/storybook/issues/9400 is somehow connected to this PR, please check

**Comment by pksunkara** [comment]
@pribilinskiy No, It's not. I am working on a fix to that issue.

**Pull request merged**
