### PR TITLE
Examples page qualification

### PR DESCRIPTION
**Pull request by domyen**
Issue:na

## What I did
I added qualification criteria for the Storybook examples page. 

When I created the examples page I only mentioned that these examples were a "curated" list. That's confusing because it doesn't give specifics about how the list is curated. 

The goal with the example page isn't to list every Storybook.

## How to test

- Is this testable with Jest or Chromatic screenshots? no
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? no

### CODE REVIEW

**Review by shilman — APPROVED** [review]
👍

**Comment by domyen** [comment]
Heads up @Taimoormk, I reverted your [PR](https://github.com/storybookjs/storybook/pull/12170) because the qualification criteria for the example page changed in the docs rewrite. 

Sorry! I didn't make the criteria clear via a code comment when I added the examples.md. And didn't see your earlier PR till now. 😅

**Comment by jonniebigodes** [comment]
LGTM as well, going to merge it.

**Review by jonniebigodes — APPROVED** [review]

**Comment by Taimoormk** [comment]
@domyen Okay thanks for the heads up.

**Pull request merged**
