### PR TITLE
Issue 3972 options knob

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

Added `optionsKnob`* to addon-knobs which composes SelectType, RadiosType and BooleanType under the hood. This PR is for issue #3972 

This knobs has six display types:

- select
- multi-select
- radio
- inline-radio
- checkbox
- inline-checkbox

`radio` and `inline-radio` re-use the existing RadiosType.

`checkbox` and `inline-checkbox` introduces a new `CheckboxesType`.

`select` and `multi-select` use the [react-select](https://github.com/JedWatson/react-select) package.

*using the name `options` was causing lint errors due to options variable already existing in namespace, so I used the name `optionsKnob` to workaround. I'm open to suggestions for how to optimize this.

See: https://deploy-preview-4723--storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs&selectedStory=optionsKnob&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

screenshot

## How to test

Is this testable with Jest or Chromatic screenshots?

Yes, with Jest. I have added `__tests__/Options.js` with unit tests.

Does this need a new example in the kitchen sink apps?

Yes. I have added the new story at Knobs/withKnobs/optionsKnob which demonstrates the six display variants.

**Note** I have noticed a UI issue with the `select` and `multi-select` variants used in the dark theme. It looks like I need to contextually pass a text color style to the React Select component. If anyone can help me do this, that would be greatly appreciated.

Does this need an update to the documentation?

Yes. I have updated addons/knobs/README.md

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by astrotim** [comment]
@shilman @ndelangen Do I need to do anything on my end to get this passing?

**Comment by ndelangen** [comment]
@astrotim There seems to be some linting and tests failing,

I could look at it, but if you could get it al green that's be awesome and free me to work on he ui-overhaul!

**Comment by astrotim** [comment]
OK, will do

**Comment by igor-dv** [comment]
What is the difference with #4855 ?

**Pull request closed without merging**
