### PR TITLE
adds error when storyshots finds no stories

### PR DESCRIPTION
**Pull request by theshortcut**
Issue: https://github.com/storybooks/storybook/issues/1330

## What I did

Added an error when storyshots finds no stories. This is makes the test suite failure more obvious than the current failure of no tests being run.

## How to test

Modify `.storybook/config.js` to find no stories, or create a new project with a storyshots suite without any stories.

Is this testable with jest or storyshots?
no
Does this need a new example in the kitchen sink apps?
no
Does this need an update to the documentation?
no
If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by Hypnosphi — APPROVED** [review]
Totally makes sense to me, thanks!

**Comment by Hypnosphi** [comment]
@ndelangen @shilman technically it's a feature, so should we rebase it on `relase/3.3`

**Comment by ndelangen** [comment]
This will introduce a breaking build when there wasn't one before. Definitely a 3.3 feature!

**Comment by theshortcut** [comment]
What is the new build failure? A build without any stories will already currently fail due to Jest failing a suite with zero tests.

**Comment by ndelangen** [comment]
@theshortcut ow, right. You're :100:% correct!

**Pull request merged**
