### PR TITLE
Add font family to info panel

### PR DESCRIPTION
**Pull request by mateoholman**
Issue: #5723 

## What I did

Add the same font family to the info panel that is used by the outer panels.

## How to test

Use the info addon. I tested with the cra-kitchen-sink example. Previously, the info panel did not have the same font family as the outer panel(s).

- Is this testable with Jest or Chromatic screenshots? Possibly
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by mateoholman** [comment]
Not sure if a new test is required for the font-family change? If so, how would you prefer to test it?

**Comment by shilman** [comment]
@mateoholman Thanks for the quick fix on this! Please update the snapshots and we'll get it merged.

**Comment by mateoholman** [comment]
@shilman  I thought I updated the appropriate snapshots, but looks like some checks are still failing? This is my first contribution, so let me know if I'm missing something 🤷‍♂️ . Thanks!

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
tested locally, all is good

**Pull request merged**
