### PR TITLE
Test renderer options

### PR DESCRIPTION
**Pull request by ndelangen**
This PR replaces: https://github.com/storybooks/storybook/pull/896

---

Issue:
When running storyshots with a story for a component that uses refs, it will throw a null reference error (see https://github.com/facebook/react/issues/7371)

## What I did
This PR adds the ability to pass options to the react-test-renderer create method, for example to allow mocking refs as per https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing

## How to test
Run `yarn test` - `ComponentWithRef.stories.js` should use the `createNodeMock` function defined in `storyshots.test.js` to mock its ref and not fail with a null reference error. The story for `ComponentWithRef` attempts to get the scrollWidth of a div when the component mounts.

### CODE REVIEW

**Comment by ndelangen** [comment]
@tmeasday Can you review and test this?

**Comment by tmeasday** [comment]
Hey @ndelangen 

1. I think you missed a key line in rebasing this PR: https://github.com/jrdrg/storybook/commit/af02d80139cbaaef6f0d35fff894a20fa3bb7e9d#diff-5c231c3fa2827654dca8a602336f00a9 (I'm guessing it got messed up the merge).

2. I suspect the solution of providing a single `createNodeMock` implementation is probably not going to scale to large projects (each story is probably going to want to provide it's own `createNodeMock`). So I think @theinterned's idea of story metadata in https://github.com/storybooks/storybook/issues/993 is probably the way forward on this.

3. In the meantime, we can use the new `test` option to achieve the behavior allowed by this PR I think:

```js
import initStoryshots from '@storybooks/addon-storyshots';
import renderer from 'react-test-renderer';

const createNodeMock = () => {
 // ...
]

initStoryShots({
  test({ story, context }) {
    const storyElement = story.render(context, { createNodeMock });
    const tree = renderer.create(storyElement).toJSON();
    expect(tree).toMatchSnapshot();
  }
});
```

@jrdrg -- I wonder if the above works for you with the latest alpha?

4. I'll work to bring this test case across to `test-cra` and prove the above works.

**Comment by tmeasday** [comment]
Perhaps the `snapshot` test-body should be a higher-order function that takes `options` as an argument and produces a test-body?

**Comment by tmeasday** [comment]
I think this can be closed as it's superceded by https://github.com/storybooks/storybook/pull/1090

**Pull request closed without merging**
