### PR TITLE
fix: align behavior of name and storyName properties

### LINKED ISSUE #22540: [Bug]: storyName cannot be set during instantiation
### Describe the bug

Creating a story, and then defining the storyName works:
```
export const Primary: Story = {
  args: {
    primary: true,
    label: 'Button',
  },
};
Primary.storyName = 'Example';
```

However, defining it during instantiation does not work:
```
export const Primary: Story = {
  args: {
    primary: true,
    label: 'Button',
  },
  storyName: 'Example',
};
```

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Edge: 113.0.1774.35
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: ^7.0.11 => 7.0.11
    @storybook/addon-essentials: ^7.0.11 => 7.0.11
    @storybook/addon-interactions: ^7.0.11 => 7.0.11
    @storybook/addon-jest: ^7.0.11 => 7.0.11
    @storybook/addon-links: ^7.0.11 => 7.0.11
    @storybook/preset-create-react-app: ^7.0.11 => 7.0.11
    @storybook/react-webpack5: ^7.0.11 => 7.0.11
    @storybook/testing-library: ^0.1.0 => 0.1.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joaonunomota**
Closes #22540

## What I did

Update `name` and `storyName` to have consistent behavior with each other and across the sidebar and docs. Both properties will display the same results when assigned to during or after the instantiation of an exported variable (story).

I didn't add any more documentation on this as it is not encouraged to use `storyName` in a CSF3 object, and the user is already warned about this when used directly in a CSF3 object. Other changes did not require updated documentation either.

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Update Button.stories.ts to include:
```
export const PrimaryNoReset: Story = {
  args: {
    primary: true,
    label: 'Button',
  },
  name: 'Primary',
};

export const PrimaryReset: Story = {
  args: {
    primary: true,
    label: 'Button',
  },
};
PrimaryReset.name = 'Primary (reset)';

export const SecondaryNoReset: Story = {
  args: {
    label: 'Button',
  },
  storyName: 'Secondary',
};

export const SecondaryReset: Story = {
    args: {
      label: 'Button',
    },
};
SecondaryReset.storyName = 'Secondary (reset)';
```
3. Open Storybook in your browser
4. Check name of stories in sidebar and docs

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by shilman** [comment]
Hi @joaonunomota thanks for your PR! This behavior that you're trying to "fix" here is actually the intended behavior of CSF3. A little background.

In CSF1, we supported the following syntax:

```js
export const Foo = () => <Button />;
Foo.story = {
  name: 'override',
  parameters: { baz: 1 }
}
```

Then in CSF2, we added support for args and made it possible to set those properties directly on the story function:

```js
export const Foo = (args) => <Button {...args} />;
Foo.name = 'override';
Foo.parameters = { baz: 1 };
```

Unfortunately, `.name` is a reserved property in JS, so we had to rename it to `.storyName`.

Finally in CSF3, we switched to an object API and went back to `name`.

```js
export const Foo = {
  // optional render: (args) => <Button {...args} />,
  name: 'override',
  parameters: { baz: 1 },
}
```

I didn't add support for `storyName` because I hope that CSF3 will be the basis for all future APIs, and I wanted it to be forward-looking. Even the `csf-2-to-3` codemod automatically updates it:

https://github.com/redbugz/storybook/blob/3307dbc2fdf814a46be94c5b3361215e663da3e0/code/lib/codemod/src/transforms/__tests__/csf-2-to-3.test.ts#L35-L56

@kasperpeulen and I looked at the CSF TypeScript types and it looks like `storyName` is optional in CSF3. But he's going to remove it from the CSF3 types for consistency.

Given all this, I'd like to close this PR as "won't fix". But I'd also like to hear your opinion on all this in case you disagree. Please let me know what you think!

**Comment by zb-sj** [comment]
@shilman (returning from this [comment](https://github.com/storybookjs/storybook/issues/22540#issuecomment-1569571184))
I understand that you are meant to phase out `storyName`

but I still think inconsistency between these be cared:

``` ts
// works
export const Name: Story = {
  name: 'The Name',
};

// only in docs
export const NameReset: Story = {};
NameReset.name = 'The NameReset';
```

or the name should be typed as const if not allowed

**Comment by shilman** [comment]
@zb-sj Thanks for your feedback. @kasperpeulen is updating the types, so if he fixed that would it address your concerns?

**Comment by zb-sj** [comment]
> @zb-sj Thanks for your feedback. @kasperpeulen is updating the types, so if he fixed that would it address your concerns?

I just met original trouble that made me reset the name with `storyName` while stripping all workaround to preferred `name` 

will it also fix another `satisfies` keyword inconsistency between:

```ts
// works
export const Name: Story = {
  name: 'The Name',
};

// no go
export const NameStatisfies = {
  name: 'The NameStatisfies',
} satisfies Story;
```

**Pull request closed without merging**
