### PR TITLE
REMOVE addon/center peerDependencies

### PR DESCRIPTION
**Pull request by leoyli**
Issue: #7989

## What I did

- Remove addon/center peerDependencies.

## How to test

N/A

### CODE REVIEW

**Comment by leoyli** [comment]
Related to #7675.

**Comment by leoyli** [comment]
@shilman, do you know how to fix CD/CI here... ? I don't see the log from _NOW_... (it is fetching log endlessly)

**Comment by shilman** [comment]
@leoyli bunch of linting errors! 😱

**Comment by leoyli** [comment]
@shilman, yes... I have noticed.  Do you have any suggestion?  I don't think that make sense for people to install the entire framework. And I think we don't want peer or optional dependencies set up right?

```
/tmp/storybook/addons/centered/src/mithril.tsx
  2:1  error  'mithril' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

/tmp/storybook/addons/centered/src/preact.tsx
  2:1  error  'preact' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies

/tmp/storybook/addons/centered/src/react.tsx
  1:1  error  'react' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```

**Comment by shilman** [comment]
@leoyli what did you do for the other PR? can't we just use eslint-ignore to get rid of those errors?

**Review by leoyli — COMMENTED** [review]
Oh thanks! 👍

**Pull request merged**
