### PR TITLE
HTML: Add CSF types

### PR DESCRIPTION
**Pull request by yannbf**
## What I did

This PR does the following:

1. Add 6.0 types to @storybook/html
2. Add HTML typescript CLI templates
3. A kitchen sink project in the examples folder for HTML typescript

## How to test

- Is this testable with Jest or Chromatic screenshots? no
- Does this need a new example in the kitchen sink apps? Added!
- Does this need an update to the documentation? no

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
@yannbf looking great! 💯 

one thing: can you add this to the exiting `html-kitchen-sink` instead of creating a new example? every example we create adds overhead to the build etc.

**Comment by yannbf** [comment]
> @yannbf looking great! 💯
> 
> one thing: can you add this to the exiting `html-kitchen-sink` instead of creating a new example? every example we create adds overhead to the build etc.

You mean convert the entire project to typescript? I can do that

**Comment by shilman** [comment]
@yannbf do we need to convert anything? TS is built into storybook, so i'd expect random bits of typescript to work in the existing project without needing to update anything else. or am i missing something?

**Comment by yannbf** [comment]
> @yannbf do we need to convert anything? TS is built into storybook, so i'd expect random bits of typescript to work in the existing project without needing to update anything else. or am i missing something?

If anyone wants to copy the entire html kitchen sink folder they wouldn't be able to run it if it was mixed like that I believe, but I'm also not sure how likely people would do that

**Comment by yannbf** [comment]
@shilman there seems to be changes in chromatic, but I don't think it's related to this PR 🤔

**Review by shilman — APPROVED** [review]
LGTM! 👍

**Pull request merged**
