### PR TITLE
Addon-docs: Lazy load docs to reduce bundle size

### PR DESCRIPTION
**Pull request by tmeasday**
## What I did

Load the docs part of rendering + the docs page/container lazily in `WebPreview`.

## Results

For `react-ts`, this reduced:

 - Initial development bundle from 12.6MB -> 11.1MB = 14% saving
 - Initial production bundle from 5.5MB -> 4.8MB = 13% saving

## Caveats / Questions

 - <strike>This adds a dependency on `@storybook/addon-docs` from `@storybook/preview-web`. We might want to make it an optional peer dep? </strike>
 - <strike>Changing `parameters.docs.container/page` to be strings (or maybe symbols?) is technically a breaking change. I'm not sure anyone would look at them directly. We might want to feature flag this?</strike>
 - Changing `parameters.docs.container/page` to be `getContainer/Page` is technically a breaking change. I'm not sure anyone would look at them directly. We might want to feature flag this?

## How to test

I guess it shows up on bundle size tracking somewhere?

### CODE REVIEW

**Comment by tmeasday** [comment]
So the build issue is due to this dependency cycle:

```
docs => builder-wp4 => preview-web => docs
```

@ndelangen what's up with this line: 

https://github.com/storybooks/storybook/blob/80e8aaa039c655c747d04299ebb482709526f332/addons/docs/src/frameworks/common/preset.ts#L9

How can we fix it? Is it easy?

**Comment by tmeasday** [comment]
Ok, so the circularity is more complex than the above, also there is 

```
docs => react [and others] => core => core-server => builder-webpackX => web-preview
```

I'm not sure those dependencies will be as easy to unravel. We might need to find an approach that doesn't lead to `web-preview` depending on `docs` @shilman

**Review by shilman — CHANGES_REQUESTED** [review]
Clever idea @ndelangen @tmeasday. I think the logic is slightly reversed, but otherwise LGTM!

**Review by shilman — APPROVED** [review]
LGTM!

**Review by shilman — APPROVED** [review]
Chef's kiss 👨‍🍳 💋

**Pull request merged**
