### PR TITLE
[Angular] Change template story files extension .ts

### PR DESCRIPTION
**Pull request by Quramy**
Issue:
Angular developers prefer TypeScript to JavaScript. It's useful that `getstorybook` cmd creates `.ts` stories files.

## What I did
- [Angular] Change template story files' extension to `.ts` .

### CODE REVIEW

**Comment by NetanelBasal** [comment]
+1

**Comment by Hypnosphi** [comment]
Make sense to me, but I'd like like to hear from people familiar with angular stuff

**Comment by igor-dv** [comment]
LGTM, but something is wrong with `snapshots/angular-cli`. It is looking for the index.stories.js

**Comment by ersel** [comment]
I've updated the snapshots required for this change. @Quramy changes and new snapshots can be found on this branch here:

https://github.com/storybooks/storybook/tree/Quramy-prefer-ts-temp

**Comment by ersel** [comment]
I have updated the angular snapshots so it looks for `.ts` files.

**Review by igor-dv — APPROVED** [review]

**Comment by NetanelBasal** [comment]
I am very familiar with Angular. I can tell that 99% of developers are working with typescript. Also, the angular-cli creates your projects with typescript files.

**Comment by Quramy** [comment]
> I have updated the angular snapshots so it looks for .ts files.

Thanks, @ersel , I missed it 😆

**Pull request merged**
