### PR TITLE
CLI: Clean up handling of unknown subcommands

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Issue:

## What I did
Use `commander.js` API to handle unknown subcommands.

## How to test
This PR aims at leveraging the arg parser lib to handle unknown args.

### CODE REVIEW

**Comment by ndelangen** [comment]
LGTM, did you test it?

**Comment by jamesgeorge007** [comment]
> LGTM, did you test it?

Yup, works fine 👍
It's nice to have tests for the CLI behavior. As of now, I can just see a shell script for the purpose.

**Review by shilman — CHANGES_REQUESTED** [review]
I ran `yarn sb asdf` in this branch and also in `next` and both versions produced the same result. Can you please double check?

Mouse_Highlight_Overlay

**Comment by jamesgeorge007** [comment]
> I ran `yarn sb asdf` in this branch and also in `next` and both versions produced the same result.

This PR aims at introducing a refactor, and hence the behavior remains the same.

**Review by shilman — COMMENTED** [review]
Aha gotcha. Thanks for the clarification @jamesgeorge007

**Review by shilman — APPROVED** [review]
👍

**Pull request merged**
