### PR TITLE
UI: Create DropdownMenu component in Core UI

### PR DESCRIPTION
**Pull request by danielmarcano**
## What I did

- I have created a new experimental Core UI component called DropdownMenu.

- This component's styles draw inspiration from the following legacy components:
  - WithTooltip, SidebarMenu, SidebarIconButton
  - ToolbarMenu, IconButton
  - SidebarMenuList, TooltipLinkList, List, Item, ListItem, Title

However, there might still be a need for further refinement of certain styles. I will review them with @cdedreuille.

The idea is to use any component as the `DropdownMenu.Trigger`, while maintaining consistent styles for its `DropdownMenu.Content` and `DropdownMenu.Item` components. These styles mirror those found in the legacy Storybook drop-downs, which were originally constructed using the aforementioned components. By introducing this new component, we not only enhance accessibility, but also eliminate the complex inter-dependencies that existed among the former components required to build a dropdown in Storybook.

## How to test

- Run a sandbox from a template
- Open Storybook
- Visit "DropdownMenu" stories from the Core UI section

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by cdedreuille** [comment]
Thanks a lot @danielmarcano for creating this component. This is so refreshing to be able to navigate easily with your keyboard.

I think we should create a sub component, perhaps to replace `<DropdownMenu.Item />` that will have props for the left icon, when it's active, ... We want to control how each elements look with an easy prop to add an icon. We don't want to make this too loose to put anything. This could perhaps be it's own component with its own stories with different states.

What would also be great is to add a couple more stories to present the different possibilities of the menu:
- Default
- With dividers
- Open/Close
- ...

**Comment by danielmarcano** [comment]
> Thanks a lot @danielmarcano for creating this component. This is so refreshing to be able to navigate easily with your keyboard.
> 
> I think we should create a sub component, perhaps to replace `<DropdownMenu.Item />` that will have props for the left icon, when it's active, ... We want to control how each elements look with an easy prop to add an icon. We don't want to make this too loose to put anything. This could perhaps be it's own component with its own stories with different states.
> 
> What would also be great is to add a couple more stories to present the different possibilities of the menu:
> 
> * Default
> * With dividers
> * Open/Close
> * ...

Hi @cdedreuille, thank you for reviewing the draft. Your suggestions are aligned with some doubts I had, so it's perfect.

I think there's two components to be made here, though:

- DropdownMenu.Item, which are items that are assigned the attribute `role="menuitem"`, which would also include an Icon property, for example, just like the new Button does.

- DropdownMenu.CheckboxItem, which are assigned the attribute `role="menuitemcheckbox",` since that role allows the usage of `aria-checked="true/false"`, to indicate whether a menu item checkbox is active or not, which is exactly what we need for these menu items:

image

- Another thing to keep into consideration with DropdownMenu.CheckboxItem, is the fact that it's basically used for actions which happen to have keyboard shortcuts. Hence, using the [attribute aria-keyshortcuts](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-keyshortcuts) would be necessary so that screen readers let users know of the existence of said shortcuts.

Let me know what your thoughts are on this, when you have some time, and in the meantime, I can continue adding these changes! ✨

**Comment by cdedreuille** [comment]
I wonder if we could create one unique component `<DropdownMenu.Item />` with a prop called `isToggle` or something like that to change the type of the item and all the accessibility features with it. This would be way easier to maintain and to track stories.

**Comment by cdedreuille** [comment]
I'm thinking about these props:
- `icon`
- `isCheckbox`
  - This will auto ident on the left to give space for the check.
  - Icons will only show when not ticked if there's one.
- `leftIndent`
  - Add a left padding to match the alignment with the checkboxes

What do you think @danielmarcano ?

**Comment by danielmarcano** [comment]
> @danielmarcano I wonder if we could create one unique component `<DropdownMenu.Item />` with a prop called `isToggle` or something like that to change the type of the item and all the accessibility features with it. This would be way easier to maintain and to track stories.

I think it would be possible, but perhaps not so desirable, as the roles, and the accessibility details, are assigned/managed by these components' props, as well as their internal logic. For example, the `aria-checked="true/false"` value is set when passing the prop `checked` to `DropdownMenu.CheckboxItem`, but there's no way to set it with `DropdownMenu.Item`, unless we manually added `aria-checked="true/false"` to it, and replaced its default `role="menuitem"` by a `role="menuitemcheckbox"`, but we would be overriding that component's behavior/purpose this way.


- DropdownMenu.Item

image
</br>

- DropdownMenu.CheckboxItem

image

</br>
</br>

The screenshots are taken from the [Radix UI's Dropdown Menu docs](https://www.radix-ui.com/docs/primitives/components/dropdown-menu).

**Comment by danielmarcano** [comment]
> I'm thinking about these props:
> 
> * `icon`
> * `isCheckbox`
>   
>   * This will auto ident on the left to give space for the check.
>   * Icons will only show when not ticked if there's one.
> * `leftIndent`
>   
>   * Add a left padding to match the alignment with the checkboxes
> 
> What do you think @danielmarcano ?

Sounds good! I'm just unsure about the `isCheckbox` part, as, if we used `DropdownMenu.Item`, we would need to add more props to it, basically, the ones that `DropdownMenu.CheckboxItem` has by default: `checked`, `onCheckedChange`, which is another reason why I think it might be better to create those two components, as their purposes and usage is somewhat different.

Also: what do you think about renaming `leftIndent` to `inlineStartIndent`? Basically to express its purpose in terms of the new [CSS logical props](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values), which take into account languages that can be read from right to left, top to bottom, etc.

**Comment by cdedreuille** [comment]
Oh I didn't realised it was actually 2 components on Radix. This would make sense to keep it as 2 components though as you suggested @danielmarcano

**Comment by danielmarcano** [comment]
> Oh I didn't realised it was actually 2 components on Radix. This would make sense to keep it as 2 components though as you suggested @danielmarcano

Hi, @cdedreuille! Based on your feedback, I have created a single `CustomMenuItem` component, which I have then reused in both `DropdownMenu.Item` and `DropdowmMenu.Checkbox`, so your idea of creating and having to maintain a single component was kind of met. Thank you for your suggestions.

I have also added more stories, and created a `KeyboardShortcut` component.

Please let me know if we are good to go, so that I can mark this PR as "Ready for review" and thus remove it from its "Draft" status 🥳

**Comment by danielmarcano** [comment]
@cdedreuille as I was developing these components, I noticed that we are using the pixel unit for font sizes in Storybook's theme. This is not accessible, as the app is currently not responding to the browser's font size value configured by people who need to increase it in order to navigate through it properly, due to visual impairments, for example.

Using the `rem` unit for all font sizes would be ideal. Since we are working on these new experimental components, it might be great to tackle this issue with these.

What are your thoughts on this?

**Comment by danielmarcano** [comment]
I am closing this PR, since it's taking GitHub Actions resources while periodically trying to run some jobs, and also due to the Storybook team's decision on not updating the UI components in the near future, as talked with @cdedreuille.

Should this component be needed, feel free to reach out to me, so as to re-open a new PR, as its development has actually been completed, based on @cdedreuille's designs and functionality requirements.

CC @JReinhold @ndelangen

**Comment by JReinhold** [comment]
Thanks for your hard work @danielmarcano and your patience.

It's a shame we had to change course midway and I'm sorry it has affected you.
I'm sure we'll eventually come up with a path forward and I think your work here is important.

**Comment by danielmarcano** [comment]
@JReinhold thank you all for your trust, and for walking me through on the entire RFC creation process, and on the development of this PR as well.

In the meantime, I will look for other ways to contribute to Storybook ❤️

**Pull request closed without merging**
