### PR TITLE
Dependencies: Upgrade `file-system-cache`

### PR DESCRIPTION
**Pull request by seriouz**
Reverts https://github.com/storybookjs/storybook/pull/23221 as the issue has now been fixed upstream.

## What I did

Removed the pinned dependency file-system-cache with 2.3.0 and set it to the fixed version 2.4.1.
Links:
- https://github.com/philcockfield/file-system-cache/issues/30
- https://github.com/storybookjs/storybook/pull/23221#issuecomment-1612218621

This is the result of `yarn why file-system-cache` in code:

```
├─ @storybook/core-common@workspace:lib/core-common
│  └─ file-system-cache@npm:2.4.1 (via npm:^2.4.1)
│
└─ @storybook/types@workspace:lib/types
   └─ file-system-cache@npm:2.4.1 (via npm:^2.4.1)
```

## How to test
Must be tested in a case-sensitive operating system like Linux - not MacOS or Windows.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by JReinhold** [comment]
Thanks for the PR!

It appears that `v2.4.1` introduces some type errors which causes CI to fail. I've filed a bug report upstream: https://github.com/philcockfield/file-system-cache/issues/32

We could do `skipLibCheck: true`, but I'd rather not, as that makes our types less strict.

**Comment by seriouz** [comment]
@JReinhold Thanks for bringing this up in https://github.com/philcockfield/file-system-cache/issues/32.
Lets wait and see what @philcockfield has to say about this.

**Comment by JReinhold** [comment]
@seriouz could you try with `v2.4.2` here and see if that fixes the issue?

https://github.com/philcockfield/file-system-cache/issues/32#issuecomment-1626665745

**Comment by seriouz** [comment]
ramda has ts-toolbelt as dependency.

**Comment by seriouz** [comment]
Now the pipeline fails saying [fs-extra is missing](https://app.circleci.com/pipelines/github/storybookjs/storybook/54659/workflows/b1907d3b-f0c8-4539-9f94-804d56c8e46e/jobs/555993?invite=true#step-104-25). But its in the dependencies https://github.com/storybookjs/storybook/pull/23253/files#diff-ff04a2a55069519839f556f58b6c56d782b05f607ce3c34221b29763590a78ecR16020

**Comment by JReinhold** [comment]
> Now the pipeline fails saying [fs-extra is missing](https://app.circleci.com/pipelines/github/storybookjs/storybook/54659/workflows/b1907d3b-f0c8-4539-9f94-804d56c8e46e/jobs/555993?invite=true#step-104-25). But its in the dependencies [#23253 (files)](https://github.com/storybookjs/storybook/pull/23253/files#diff-ff04a2a55069519839f556f58b6c56d782b05f607ce3c34221b29763590a78ecR16020)

I see, looks to be the same problem as with `@types/rambda`. Installing it as a dependency won't help because it will land in `node_modules/@types/fs-extra` while TypeScript is looking in `node_modules/file-system-cache/node_modules/@types/fs-extra` (I believe) - so `file-system-cache` needs to install it.

https://github.com/philcockfield/file-system-cache/issues/32#issuecomment-1628386979

**Comment by JReinhold** [comment]
@seriouz seems like this has now been fixed in `2.4.3` of `file-system-cache`. Could you upgrade to that here, I think that should make this mergable.

**Comment by yannbf** [comment]
Hey @seriouz I could not push updates to your branch, could you please update your branch and fix the merge conflicts? Thanks!

**Comment by ndelangen** [comment]
@yannbf It's hard to update branches when they are named `next` because git will say the ref is ambiguous.

It's possible though, if you rename the branch name locally, and point it to track the branch of the PR.

**Comment by seriouz** [comment]
I created a new PR with the latest "next" branch: https://github.com/storybookjs/storybook/pull/24232
I think this PR can be closed.

**Pull request closed without merging**
