### PR TITLE
Add mocking of all decorators in storyshots

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: -unittest for storyshots is failing-

## What I did
I added code to mock storybook addons during storyshots.

## How to test
run `npm test`

### CODE REVIEW

**Comment by tmeasday** [comment]
Which decorators were causing errors? I don't know if mocking them is what we want to do. As per the trichotomy [here](https://gist.github.com/tmeasday/775c5572271121bb2a71153ac5f2cd7a):

1. "modifiers" need to run for the test.
2. "inspectors" tend to just post to the channel, which is mocked out for storybook.
3. "wrappers" are needed for the story to execute. (None of these are wrappers). Ideally they wouldn't be used in the snapshot, but it's not critical that they currently are.

Is it addon-info that's the problem? That's an "inspector" that actually modifies things, but we should fix that

**Comment by shilman** [comment]
@ndelangen I see @tmeasday 's point. I think this is a really clever pattern but we shouldn't use it until we need it, and it sounds like once we fix addon-info (per #1147) then we probably don't need this pattern. I propose we keep this in our back pocket for now. What do you think?

**Comment by ndelangen** [comment]
Hey @tmeasday If you want to reject this, that's fine. If you want to suggest some other way of fixing the unit tests in the branch this PR was targeting?

**Comment by tmeasday** [comment]
@ndelangen - AFAICT, the errors on that branch are the same as the ones on https://github.com/storybooks/storybook/pull/1259, is that correct? The last failing build was https://travis-ci.org/storybooks/storybook/builds/241898626?utm_source=github_status&utm_medium=notification which has the same two errors I posted about here: https://github.com/storybooks/storybook/pull/1259#issuecomment-308322351

I think we need to get to the bottom of whether npm@5 linking / lerna is actually working. My suspicion is that it is not, in general.

**Comment by tmeasday** [comment]
Ok, the larger issue is: https://github.com/storybooks/storybook/issues/1286

I don't think there's much point in mocking out the things we are trying to test. Let's just disable these tests until we resolve the above.

**Pull request closed without merging**
