### PR TITLE
fix(clipboard): try to fix clipboard issue

### PR DESCRIPTION
**Pull request by Nxtivision**
Issue: #16642

## What I did

I just added the property allow clipboard-write (according to the doc) on the iframe responsible to display the Source Code, so the user can copy.

## How to test

I'm not sure how to test it. We need two storybook with composition using chromatic to see if it works or not. However, this small fix should not destroy all Storybook :)

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by kylegach — APPROVED** [review]
Looks good, @Nxtivision! Thanks for taking the time to fix this issue!

**Comment by Nxtivision** [comment]
Hello !

Do you have an idea when this PR will be released ? 🙂

**Comment by ndelangen** [comment]
Should be good to merge as-is!

Sorry for the late merge @Nxtivision , thanks again for contributing!

**Comment by Nxtivision** [comment]
Hello,

Is it possible to cherry-pick this PR to the next patch version of 6.5 ? 😄 Because my team is not ready for v7 and we use a lot of referenced Storybook with Chromatic and Nx. Or a possible workaround until v7 is stable ?

have a nice day !

**Pull request merged**
