### PR TITLE
Addon/docs Fix first story docs not showing.

### PR DESCRIPTION
**Pull request by patelvp**
Issue: https://github.com/storybookjs/storybook/issues/8093

## What I did
- `expanded` prop was set to false for Primary component which displays the first story. Hence the docs were not showing information as expected.
- Setting `expanded` prop to true solves the issue.
## How to test

- Docs now appear for the first story.

### CODE REVIEW

**Comment by patelvp** [comment]
@shilman Thanks for updating my branch!

**Comment by ndelangen** [comment]
@patelvp could you resolve the merge conflicts?

@shilman is this good to merge?

**Comment by patelvp** [comment]
@ndelangen Done!

**Comment by patelvp** [comment]
Thoughts on this or should we close this?

**Comment by ndelangen** [comment]
@shilman are you interested in merging this?

**Comment by shilman** [comment]
TBH I'm not sure. @domyen WDYT? It kind of breaks the design of the "primary" story, and users can always override this by hand using https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#remixing-docspage-using-doc-blocks

**Comment by domyen** [comment]
I think we should leave the default behavior as is. Folks can further customize behavior by passing their own custom docspages as @shilman mentioned.

**Comment by shilman** [comment]
OK, closing this then. Thanks for your patience @patelvp & see the workaround described above.

**Comment by sebastienbarre** [comment]
Love Storybook, but this is really a strange decision. As a new user, it took me a long time to figure out why my first story description was not showing, and find the corresponding workaround...

**Pull request closed without merging**
