### PR TITLE
CLI: Add webpack4/5 detection

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

The CLI can now detect which version of webpack you are using. If it detects you have webpack version 4 installed anywhere, it will use builder-webpack4, if you do not, and you have webpack v5 installed instead, it will use builder-webpack5.

It will still default to use builder-webpack4 if it can't detect anything.

I also added the builder-webpack4 and manager-webpack4 in the case the builder is indeed webpack4. Seems like the right thing to do, if we don't want core-server to depend on any builder in particular.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Great job @ndelangen 💯

**Comment by ndelangen** [comment]
😎

**Comment by daniel-stoian-lgp** [comment]
How can I set which webpack version I want storybook to use after this update?

**Comment by shilman** [comment]
@daniel-stoian-lgp you can set the `core.builder` property in `main.js`:

https://storybook.js.org/docs/6.5/react/configure/webpack#webpack-5

cc @jonniebigodes

**Pull request merged**
