### PR TITLE
update peerDependency

### PR DESCRIPTION
**Pull request by sixmen**
Issue:

## What I did

remove npm WARNs

```
$ npm install    
npm WARN @storybook/addon-actions@4.0.0-alpha.1 requires a peer of @storybook/addons@^3.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/addon-notes@4.0.0-alpha.1 requires a peer of @storybook/addons@^3.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/addon-options@4.0.0-alpha.1 requires a peer of @storybook/addons@^3.3.0 but none is installed. You must install peer dependencies yourself.
```

## How to test

Is this testable with Jest or Chromatic screenshots? NO

Does this need a new example in the kitchen sink apps? NO

Does this need an update to the documentation? NO

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by sixmen** [comment]
I found https://github.com/storybooks/storybook/pull/3183/commits/9f3abbad21ec4436625217bafbb503d4cbf254aa after make this PR.

Please close this PR if not appropriate.

**Comment by Hypnosphi** [comment]
I think we can put `*` there

**Comment by sixmen** [comment]
How about `"^3.3 || ^3.4 || ^4.0`?

**Comment by sixmen** [comment]
I read https://github.com/lerna/lerna/issues/1018 again.
It says `lerna publish` update peerDependencies too.
I think it is better to install same versions for Storybook, so it is not a problem to update peerDependencies.

But if you think it is a problem, how about `"^4.0"` or `"^3.4 || ^4.0"` or `"^3.3 || ^3.4 || ^4.0"` instead of `"*"`

**Comment by Hypnosphi** [comment]
`>= 3.3.0 || ^4.0.0-alpha` should work after publishing stable `3.4.0` which should happen today or tomorrow

**Comment by ndelangen** [comment]
@sixmen You should now have access to the main repo, you do not have to work from your fork anymore, you can create branches and commit directly on this repo ;) 👍

**Comment by sixmen** [comment]
I think this is not needed anymore. I'll close this.

**Pull request closed without merging**
