### PR TITLE
Addon-docs: Fix table dark mode

### PR DESCRIPTION
**Pull request by TheMightyPenguin**
Issue: https://github.com/storybookjs/storybook/issues/14029

## What I did

* Change the styles for the [Table](https://github.com/storybookjs/storybook/blob/df27d3adf36bf484e1c37b2525893e54dd3b3f22/lib/components/src/typography/DocumentFormatting.tsx#L162) component used in Docs pages. The main issue was the table background, which was using styles from the `light` theme before.
* Uses `color.darkest` as the value for `appContentBg` in the dark theme, as it was using the same value.
* Adds an example of a table with icons.

This is how the tables look now in Dark mode:
image

And in Light mode there were no visual changes:
image

### Manual Test

1. Change the official-storybook example theme from `theme.light` to `theme.dark`: https://github.com/storybookjs/storybook/blob/df27d3adf36bf484e1c37b2525893e54dd3b3f22/examples/official-storybook/preview.js#L161
2. Run the official-storybook example `cd examples/official-storybook` and `yarn storybook`. (Also run `yarn build core components addon-docs theming` in the root folder to update the build with the theme changes).
3. Go to Docs > markdown-page document: http://localhost:9011/?path=/docs/addons-docs-markdown-docs--page
4. Assert that the table looks like the image attached above of the dark theme table.

## Questions

For setting the alternative rows background color (pair rows in this case), I did the following:

```
'& tr:nth-of-type(2n)': {
    backgroundColor: theme.base === 'dark' ? theme.color.darker : theme.color.lighter,
},
```

I'm not sure if this was the way to go, I also thought of adding a new theme variable, something like `theme.appAlternativeContentBg`, but not sure if this would be used that often.

### CODE REVIEW

**Comment by TheMightyPenguin** [comment]
@shilman I think this could be tested using Chromatic, but not sure how to proceed, I'm guessing it'll run automatically as part of CI, the issue here is that the official-storybook example is using light mode for the docs, should I replicate that example with a new one using dark-mode or what would be the way to go?

**Comment by shilman** [comment]
@domyen @ghengeveld can one of you please review?

**Review by ndelangen — APPROVED** [review]

**Comment by TheMightyPenguin** [comment]
@shilman @ndelangen in this case I didn't add unit tests as I think visual regression is a better fit for these changes. These docs that include the MDX table are already in a story but it's using light mode in that example project, should I add anything extra for this or is it ok the way it is? (Also I'm not sure if this example project is getting tested in Chromatic)

**Comment by TheMightyPenguin** [comment]
Oh I just saw the story in the chromatic link in CI 😄 https://www.chromatic.com/test?appId=5a375b97f4b14f0020b0cda3&id=60517a9dfa63c80021059690, but there are no tests for dark mode, should those be added?

**Comment by ndelangen** [comment]
I don't see it as required to merge this PR, but if we could add a story like https://www.chromatic.com/test?appId=5a375b97f4b14f0020b0cda3&id=60517a9dfa63c80021059690 but in dark mode, that would be :hearts:

**Comment by TheMightyPenguin** [comment]
@ndelangen Added dark mode story! 😄 so this is ready for merging I think, the only issue is that `ci/circleci: chromatic` is failing with this error:
```
HTTPClient failed to fetch https://index.chromatic.com/graphql, got 503/Service Unavailable
```

**Review by shilman — APPROVED** [review]
Looking good!!! 🙏

**Pull request merged**
