### PR TITLE
Angular: Prioritize template over source

### PR DESCRIPTION
**Pull request by dexster**
Issue: #14268

## What I did

Moved the template check above the source check. If a template exists then use it in the "Show code" block. Also prevents the computesTemplateSourceFromComponent from running unnecessarily. 

## How to test

Create a story with a template that differs from generated source. View "Show code" in docs and the template should display.

### CODE REVIEW

**Comment by shilman** [comment]
cc @yngvebn

**Comment by yngvebn** [comment]
@dexster Thanks for the PR! This works fine if you use templates, but it will completely sidestep the autogeneration, because of this little snippet in StorybookModule:

```
if (hasNoTemplate(template) && component) {
    template = computesTemplateFromComponent(component, props, '');
}
```

So basically the template (for rendering the component) is always generated and used as the source-code if you switch the order in sourceDecorator.ts. I discussed this briefly with @ThibaudAV, and I think we need to either:

1. introduce a flag that indicates that the template is automatically generated
2. Introduce a separate "sourceCodeTemplate" or something that can be used for rendering the source code. This could be populated with the contents of `template` if it's set, otherwise it will fall back to autogenerating the source based on the component and args.

I also think @ThibaudAV had some thoughts on changes here.

**Comment by dexster** [comment]
No problem. I was not aware of the bigger picture. Let me re-examine the template generation flow

**Comment by dexster** [comment]
After speaking to @yngvebn and spending more time understanding the required changes, this requires a lot more work to integrate correctly with Controls. For now it will simply be easier to manually add the code for the View code

**Pull request closed without merging**
