### PR TITLE
refactor(angular): drop support for angular < 13

### PR DESCRIPTION
**Pull request by kroeder**
## What I did

According to the [Angular LTS plan](https://angular.io/guide/releases#actively-supported-versions), Angular 12
support ends in Nov 2022. A lot of code exists
to support Angular < 13 which increases the
maintenance effort and decreases the
contribution DX of framework/angular.

This PR removes all code related to Angular < 13 in preparation for Storybook 7.0

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by kroeder** [comment]
Example app is running perfectly fine and I think I found every code related to Angular < 13 
There are a few more places tagged with "drop before storybook 7.0 release" but they are not related to the support of Angular < 13

@ThibaudAV any second thoughts? @ndelangen already agreed to this

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I think a migration note in `MIGRATION.md` is warranted about this @kroeder 👍

**Comment by ThibaudAV** [comment]
🚀
Only thing to add is : 
What about now always support only same supported version than Angular ? 😁
https://angular.io/guide/releases

Is more easy for many reason and try to support the last one as fast as possible

**Comment by kroeder** [comment]
> 🚀
> Only thing to add is : 
> What about now always support only same supported version than Angular ? 😁
> https://angular.io/guide/releases
> 
> Is more easy for many reason and try to support the last one as fast as possible 

Since dropping support is a breaking change, storybook can only do this between major releases. Angular has 2 majors a year and supports the last 3, storybook has about 1 a year, right? So, most likely storybook would need support the last 4

But officially, I totally agree with you! We should only support all lts versions

@ndelangen @shilman I don't know with whom I already have discussed this on discord but anyway, should we do this? Only support angular lts? (basically 1 1/2 year of angular code)

**Comment by kroeder** [comment]
> I think a migration note in `MIGRATION.md` is warranted about this @kroeder 👍

I added a note to the MIGRATION.md - is this good enough?

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
