### PR TITLE
Check for react-scripts in devDependencies before usage

### PR DESCRIPTION
**Pull request by binomialstew**
Fix for https://github.com/storybookjs/storybook/issues/6973

### CODE REVIEW

**Comment by shilman** [comment]
LGTM, thanks for the fix!!

However, tests need to be updated:

```
 FAIL  app/react/src/server/cra-config.test.js
  ● cra-config › when used with react-scripts >= 2.1.0 › should apply Babel, styling rules and merge plugins

    expect(received).toMatchSnapshot()
```

@mrmckeb Wonder what you think about this?

**Comment by ndelangen** [comment]
👏👏👏

**Comment by binomialstew** [comment]
Do we need to mock `package.json` with `react-scripts` in `devDependencies` for the failing test? I could update the snapshot, but I don't think that will actually test what we are looking for.

**Comment by mrmckeb** [comment]
Hi @binomialstew, this won't work unfortunately.

There can be many forms of `react-scripts`, and we support forks of `react-scripts` (to a basic level) in the same way that CRA does. This PR would break support for a lot of users.

We actually check for `react-scripts` in `bin`, which is a constant with these forked packages. So perhaps looking to their for your solution will help?

**Review by mrmckeb — CHANGES_REQUESTED** [review]
See above comment.

**Comment by ndelangen** [comment]
👏 @mrmckeb thanks for chiming in!

Sounds reasonable to be checking for the existance of the `.bin/react-scripts` right?

**Comment by ndelangen** [comment]
@binomialstew if this is turning into a bit more work then you anticipated and are able to handle, please call out for help!

**Comment by binomialstew** [comment]
@mrmckeb, unfortunately, checking in `.bin` would effectively be the same as checking in `node_modules` and wouldn't fix [this issue](https://github.com/storybookjs/storybook/issues/6973).

I'm starting to think we should have a way to prevent load of react-scripts through env/command line or config. I'd actually even prefer having the user opt-in to using it for the storybook config. For me, it is a bit unexpected that it would be used just by being present in the `n_m`. It caused some confusion for me because I am using full-control mode and saw these new rules loaded that were nowhere in my config. Since I hadn't imported or referenced `react-scripts` anywhere, it seemed very strange until I realized it was being loaded just because it was in `node_modules`.

**Comment by mrmckeb** [comment]
@binomialstew As @shilman said, we are checking .bin now, and this is the solution that works for forked `react-scripts` packages.

For your use-case, perhaps you could prevent hoisting? https://github.com/lerna/lerna/issues/926

If that doesn't help, let us know.

**Comment by binomialstew** [comment]
@mrmckeb, the issue I am trying to solve is more of a general issue I see with the storybook DX—I don't think checking for `react-scripts` installation is enough to decide for the user that it should be used for storybook config. There are other cases in addition to a lerna hoist that could cause `react-scripts` to be used for storybook config unintentionally, and I know others have raised issues with this in the past.

I have workarounds for this, but I also would like to improve what I see as a DX issue--I think it's best not to assume, just because react-scripts is present with no other reference in the config, that it should be used for the storybook config. I've left [a comment in the original issue thread](https://github.com/storybookjs/storybook/issues/6973#issuecomment-504847517)--perhaps we can come to a consensus for this. I'd be happy to open up a new PR with a solution that works for everyone.

I'm closing this one since I think we will find a better solution elsewhere.

**Pull request closed without merging**
