### PR TITLE
FIX react-scripts-latest-fixture by installing expo globally

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: master build is broken

## What I did

I edited the `cli-latest-cra`-test so they use npx directly and the CRNA one uses expo-cli directly

### CODE REVIEW

**Comment by ndelangen** [comment]
Still asks to install expo-cli even when already installed globally... 😠

**Comment by Hypnosphi** [comment]
Do they have a `-y` option?

**Comment by ndelangen** [comment]
I do not know, I have asked on their slack for support..

**Comment by Hypnosphi** [comment]
https://github.com/react-community/create-react-native-app#create-react-native-app

> You can now use `expo init` to create your project. See Quick Start in the Expo documentation for instructions on getting started using Expo CLI.
>
> The `create-react-native-app` command is provided for backwards compatibility.

Looks like we should just use `expo init` instead

**Comment by Hypnosphi** [comment]
> `function create_fixture`

By the way this one isn't actually needed, we never run our tests in old node

**Comment by ndelangen** [comment]
I just wanted to do a quick fix while I was waiting for something else.

Since I was hoping to be the quick hero who fixed master.

Anyhow, it sounds like you have a waay better picture of what's going on and should happen then I do about this @Hypnosphi 😄 

Do you want to take over this PR?

**Comment by Hypnosphi** [comment]
No, please just do the changes I mentioned

**Comment by ndelangen** [comment]
Opened a forum post here:
https://forums.expo.io/t/cl-initi-in-ci-times-out-because-waiting-for-input-this-command-requires-expo-cli/14255

I do not know how to fix this 😭

**Review by Hypnosphi — APPROVED** [review]

**Comment by Hypnosphi** [comment]
Looks like `expo` just [proxies](https://github.com/expo/expo/blob/41458d1de91544c41097818db21e44e9aa84688c/packages/expo/bin/cli.js#L8) to `expo-cli`

This works without prompts:
```
npx expo-cli init -t blank my-project
```

**Comment by Hypnosphi** [comment]
But the problem is, the project that you get doesn't have `react-native-scripts` dependency

**Comment by Hypnosphi** [comment]
We should probably detect `expo` dependency instead

**Comment by Gongreg** [comment]
Even if we manage to pass 
```
Do you want to install it globally [Y/n]? Too long with no output (exceeded 10m0s)
```
We get another issue:

```
[16:32:15] Input is required, but expo is in non-interactive mode.
Required input:
> Choose a template:
```

**Comment by Hypnosphi** [comment]
@Gongreg that's why I added `-t blank`

> But the problem is, the project that you get doesn't have `react-native-scripts` dependency

**Comment by Hypnosphi** [comment]
@ndelangen let's do the following:

Change this to detect `expo` instead of `react-native-scripts` (and probably rename the constant to `types.EXPO`):
https://github.com/storybooks/storybook/blob/master/lib/cli/lib/detect.js#L46-L51

Use `../../node_modules/.bin/npx expo-cli init -t blank react-native-scripts-latest-fixture` in `test_latest_cra.sh`

**Pull request closed without merging**
