### PR TITLE
Core - Extract client-api pkg from core

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: related to #4942

## What I did
Extracted `ClientApi, StoryStore, ConfigApi, toId` to the client-api pkg

### CODE REVIEW

**Comment by ndelangen** [comment]
This is step 1 of N to overhaul Storybook for RN

**Review by ndelangen — APPROVED** [review]

**Comment by Gongreg** [comment]
@igor-dv @ndelangen, keep it up!

**Comment by igor-dv** [comment]
💪

**Comment by Gongreg** [comment]
✋.

**Pull request merged**
