### PR TITLE
Migrate ember to TS

### PR DESCRIPTION
**Pull request by aromanarguello**
Issue: [#5030](https://github.com/storybookjs/storybook/issues/5030)

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
now deploy is incomplete because of some error, but locally it seems to work fine (so far)

**Comment by ndelangen** [comment]
Verified this works, @aromanarguello Is this PR ready?

**Comment by aromanarguello** [comment]
@ndelangen  Do you want me to rebase and re-push? I see some there are failures with the CI that's why I didn't want to make it `ready for review`, I think I've converted every file. What are your thoughts?

**Comment by ndelangen** [comment]
I don't think there's a need to do that @aromanarguello, unless you want to change any code, but if not, I think it's merge-able.

Will you do the honours?

**Pull request merged**
