### PR TITLE
transform for of in dlls

### PR DESCRIPTION
**Pull request by tooppaaa**
Issue: #10427

## What I did

Add plugin-transform-for-of for dlls 

## How to test
 
Launch WITH DLLs in IE 11

### CODE REVIEW

**Comment by tooppaaa** [comment]
@ndelangen I still have issues with vendors~main regarding `class OverlayScrollbarsComponent`. Did I miss anything ?

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I'm getting in IE11:

```
SCRIPT1002: Syntax error
File: vendors~main.7dc0c5d29dca32352212.bundle.js, Line: 2, Column: 4223883
```

```
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
File: main.7dc0c5d29dca32352212.bundle.js, Line: 1, Column: 266065
```

The manager seems to work, preview seems broken..

I'm testing this URL:
https://deploy-preview-10471--storybookjs.netlify.app/angular-cli/?path=/story/addon-background--background-component

**Comment by ndelangen** [comment]
@tooppaaa is this the same you were getting?

**Comment by ndelangen** [comment]
It's `semver` again. It's n the main bundle and it's using destucturing..

Screenshot 2020-04-20 at 17 34 00

**Comment by tooppaaa** [comment]
Yep, manager is fine after adding the plugin for the dlls.
I don't see issues with semver, while debugging, It's stuck on `class OverlayScrollbarsComponent extends react__WEBPACK_IMPORTED_MODULE_0__["Component"] {`

**Comment by ndelangen** [comment]
not fixed yet

**Comment by tooppaaa** [comment]
DLL was not referenced in the preview bundle. 
It was first fine when @ndelangen introduced it, but was removed by [this commit](https://github.com/storybookjs/storybook/commit/26ab72e5695caacbb5010be1e2fec88947ee8878#diff-3f9960d4367e0d7176bea0f6d79a54e7L7) from @shilman 

Added it back, can you confirm it's fine for you ?

**Review by ndelangen — APPROVED** [review]

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
