### PR TITLE
dont display outline when interacting with links

### PR DESCRIPTION
**Pull request by moimikey**
Issue:

## What I did

This simply adds a line of css to react (and not native since it's not through a browser) to get rid of the visually disturbing outline that shows when you click on hyperlinks.

## How to test

You'll simply not see the box shadow anymore.

screen shot 2017-06-15 at 4 50 09 pm

Where previously you could:

screen shot 2017-06-15 at 5 01 29 pm

### CODE REVIEW

**Review by ndelangen — CHANGES_REQUESTED** [review]
Hey thanks for the PR!

I get it's ugly, but it's vital for keyboard usage.

Removing it without any other feedback is not really an option.

Can you find a solution so keyboard users do get feedback what they have focussed?

**Comment by shilman** [comment]
@moimikey thanks for the fix! i'm wondering whether the style should be scoped somehow? right now it's a global change and that feels a little dirty to me?

**Comment by danielduan** [comment]
+1 on accessibility. it's nice to have it highlighted for kb usage.

**Comment by UsulPro** [comment]
I wonder whether the use case of keyboard navigation includes stories switching (if it's about `Tab` / `Shift-Tab`)? Asking because `Ctrl-Shift-Arrow` looks more comfortable for that. So maybe we can add special keyboard shortcuts for switching through the add-ons tabs as well? In this case, we can leave the outline only in the preview area?

**Comment by ndelangen** [comment]
I'm interested in a quick-win fix for this that does not entail completely remove the focus styling.

In the long run I'll be moving our UI components and change the way styling works using glamorous.
And at that point I'll address this myself.

Please re-open if you can find a good style for focussed items 👍

**Pull request closed without merging**
