### PR TITLE
Clean up Svelte snippets + Create Svelte/Typescript snippets

### PR DESCRIPTION
**Pull request by jack-weilage**
## What I did

1. Removed `.native-format.mdx` (**Re-added**) and `.mdx.mdx` snippets for Svelte
2. Removed unreferenced snippets
3. Updated Svelte/JS snippets and created new Svelte/Typescript snippets, staying close to React/Typescript snippets

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by jonniebigodes — CHANGES_REQUESTED** [review]
@jack-weilage, thanks for taking the time to put together this pull request and help us improve our documentation by introducing the TypeScript variations of the Svelte scripts and fixing the other ones. However, there are a couple of things before this can move forward. If you're ok with it, can you re-introduce the `.native-format.mdx` examples but don't link them? The reasoning behind this is that there's some work being done on that front with the Svelte native addon, and we want to introduce them at some point. Also, it seems that there are some issues in the examples, and once again, if you're ok with it, could you run `yarn pretty-docs` to fix them?

With that in mind @JReinhold, if memory serves me right, you've been doing some work on that addon, correct? If so, could you take a pass at this one and follow up with me so that we have a sense of the status of the addon and see when we're ready to start re-introducing them?

Let me know once you've addressed the issues so that we can follow up with you on it.


Hope you have a great day.

Stay safe

**Comment by jonniebigodes** [comment]
@jack-weilage, thanks for following up with me. That's a great question, and sorry for not being clear. And to answer it, the `.mdx.mdx` files not be added, only the ones I've mentioned.

**Comment by jack-weilage** [comment]
That should be everything done now. Funnily enough, I had already run prettier locally, but just hadn't pushed it!

**Review by jonniebigodes — CHANGES_REQUESTED** [review]
@jack-weilage, just one item from you, a small typo, and this should be ready. Also, when you're able, can you solve the conflicts and let me know so that we're able to get this merged?

Hope you have a fantastic weekend.

Stay safe

**Comment by jonniebigodes** [comment]
@jack-weilage just a friendly reminder to see if you have a moment to address the feedback I've mentioned and vet the conflicts so that we can get this one in.

Let me know and we'll take it from there.

Hope you have a fantastic week.

Stay safe

**Comment by jonniebigodes** [comment]
@jack-weilage it goes without saying that we really appreciate you taking the time to put this pull request together and helping us improve the documentation 🙇 . But and I hope you don't mind, I'm going to close as I've got a pull request for the TypeScript variants for Svelte including TypeScript 4.9 and some items that required some additional attention regarding how they're shown.


Looking forward to seeing your next contribution.

Hope you have a fantastic day.

Stay safe

**Pull request closed without merging**
