### PR TITLE
Expose style for customisation

### PR DESCRIPTION
**Pull request by baktiaditya**
Issue:

## What I did
Cannot modify `button.topRight` style from storybook config.js

example:
```jsx
import { setDefaults } from '@storybook/addon-info';
import deepmerge from 'deepmerge';

setDefaults({
  styles: (defaultStyles) => {
    return deepmerge(defaultStyles, {
      button: {
        topRight: {
          right: 'auto',
          borderRadius: '0 0 5px 0',
          left: 0,
        },
      },
    });
  },
});
```

## How to test

Is this testable with jest or storyshots?

Does this need a new example in the kitchen sink apps?

Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Thanks, totally makes sense. Can you please do the same in rest of the places in this component?
https://github.com/baktiaditya/storybook/blob/961e1b91439bb42d4c2ccc5a4dd108660a683cd9/addons/info/src/components/Story.js#L159
https://github.com/baktiaditya/storybook/blob/961e1b91439bb42d4c2ccc5a4dd108660a683cd9/addons/info/src/components/Story.js#L218

**Comment by baktiaditya** [comment]
@Hypnosphi ok, I'll inform you again when it's done

**Comment by baktiaditya** [comment]
@Hypnosphi 👍 done

**Review by Hypnosphi — APPROVED** [review]
LGTM, thanks again

**Pull request merged**
