### PR TITLE
WIP:  implement  JSON story file format as indexer

### LINKED ISSUE #20627: [Bug]: Storybook server needs an indexer for `.stories.json` files
### Describe the bug

Storybook adds a new "indexer" system for the sidebar. Because there is no indexer for `.stories.json` files, Storybook crashes on a new server project.

### To Reproduce

```shell
2174  mkdir server-test
 2175  cd server-test
 2176  yarn init -y
 2177  npx sb@next init -t server
```

Results in:

```
WARN 🚨 Extraction error on stories/button.stories.json: Error: No matching story indexer found for /Users/shilman/projects/testing/server-test/stories/button.stories.json
WARN 🚨 Extraction error on stories/header.stories.json: Error: No matching story indexer found for /Users/shilman/projects/testing/server-test/stories/header.stories.json
WARN 🚨 Extraction error on stories/page.stories.json: Error: No matching story indexer found for /Users/shilman/projects/testing/server-test/stories/page.stories.json
Error: No matching story indexer found for /Users/shilman/projects/testing/server-test/stories/button.stories.json
    at StoryIndexGenerator.extractStories (/Users/shilman/projects/testing/server-test/node_modules/@storybook/core-server/dist/index.js:10:10133)
```
```


### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by floodfx**
Closes #20627

## What I did

* added `loadCsfFromJson` function in `CsfFile.ts` 
* added an indexer for `.json` files in `preset.ts` using above
* removed warning for `.json` files in `codegen-importfn-script.ts`

## How to test

Haven't added a test yet.  Would like some feedback on above approach / code and answers to some of the TODOs particularly in `loadCsfFromJson`.  

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by chakAs3** [comment]
> ## How to test
> Haven't added a test yet. Would like some feedback on above approach / code and answers to some of the TODOs particularly in `loadCsfFromJson`.

How to test is not about the unit-tests, it is how we can see your code working, like 
1 - run yarn start,
2 - open specific story or  create file.json then do ..

how did you see the result of your code ?

**Comment by floodfx** [comment]
Yeah fair point.  I have a local story in json format which I put into a test.  It passes obviously but not sure what the snapshot should actually be.  For example, where do the `parameters` go?  Where should the story `args` end up?

**Review by shilman — COMMENTED** [review]
Thanks for doing this @floodfx !! I'm on vacation for the next few days but will take a closer look next week & do my best to give guidance.

**Comment by chakAs3** [comment]
Hi @floodfx.  I really like your intent, cause I have the same idea as basic with more capabilities like import-export stories, and generate default stories from a specific component library, it will be great, I can pair with you on this if you would like

**Comment by floodfx** [comment]
@chakAs3 that would be great.  As I mentioned in #20627, we use json stories in storybook 6 to test our server rendered templates for a golang project and it has worked well.  I'd like to get that working with SB 7.

**Comment by chakAs3** [comment]
> @chakAs3 that would be great. As I mentioned in #20627, we use json stories in storybook 6 to test our server rendered templates for a golang project and it has worked well. I'd like to get that working with SB 7.

Yes sure @floodfx  can you just add some test stories so I can start from there with you?

**Comment by floodfx** [comment]
I added https://github.com/storybookjs/storybook/pull/22296/commits/dc5a9b824814a498125e3d2f89022a77bac5f0ab which is generally the format we use. I think the problem I have is I don’t know the extent of what the json story format should support and where these json story attributes should end up in the output?

**Comment by shilman** [comment]
@floodfx @chakAs3 thanks so much for putting this together and for your patience on this. The code looks good! I'm going to give a shot at restructuring it today to get this ready to merge.

**Comment by floodfx** [comment]
thanks @shilman.  lmk if I can be helpful.

**Comment by shilman** [comment]
Hi @floodfx, I merged https://github.com/storybookjs/storybook/pull/22460 which restructures this a little bit, and will release on the next 7.0.x patch release. Thanks so much for making this happen! 🙏

**Comment by jonniebigodes** [comment]
@floodfx, thank you so much for taking the time and effort into this pull request. We appreciate it 🙏 ! I want to follow up on one thing that was left out of this pull request. If you're ok with it, can you message me on our [Discord Server](https://discord.gg/storybook) (same username) so that we can go over it? 

Looking forward to hearing from you.

Have a great day.

Stay safe.

**Pull request closed without merging**
