### PR TITLE
Fix link to addons intro from guide-react-native/index.md

### PR DESCRIPTION
**Pull request by gianpaj**
Issue:

## What I did
doc link fix

### CODE REVIEW

**Comment by igor-dv** [comment]
Can you please merge from `master` ?

**Comment by gianpaj** [comment]
@igor-dv you mean from the latest storybooks' master? or my fork master?

**Comment by igor-dv** [comment]
From the latest storybook master

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
done it for you :)

**Comment by igor-dv** [comment]
@ndelangen the test issue is still happening on master.

**Pull request merged**
