### PR TITLE
Fix: (Vue3 cli ts templates) add missing css import on button.vue 

### PR DESCRIPTION
**Pull request by chakAs3**
Issue:

## What I did 
fix a bug by adding the missing  ./buttons.css import on  button.vue .

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by ndelangen** [comment]
@storybookjs/vue is this good to merge?

**Comment by ndelangen** [comment]
@jonniebigodes would you invite @chakAs3 to order a swag-box please?

**Review by ndelangen — APPROVED** [review]

**Comment by jonniebigodes** [comment]
@ndelangen, by all means, yes, I've been keeping track of the great contributions, and I was just about to message @chakAs3 for it. With that @chakAs3 can you do me a favour and message me on Discord (same username) so that I can follow up with you on it?

Looking forward to hearing from you.

Hope you have a fantastic weekend

**Comment by Aaron-Pool** [comment]
> @storybookjs/vue is this good to merge?

I'm not totally in the loop on some of the recent changes in storybook, but I'm not seeing the `./button.css` file it's trying to import.  Is it generated somehow?

**Comment by ndelangen** [comment]
@chakAs3 can you check

**Comment by chakAs3** [comment]
i have already open PR a 7 days ago

**Comment by chakAs3** [comment]
@Aaron-Pool  the css assets are bundled with the cli.  there are used in  2 places I think, in the  templates after reading the user project  `npx sb init`( vite js/ts / ts legacy)  ,and in the sandbox template for contributors vue3-vite/default-ts

**Comment by Aaron-Pool** [comment]
> @Aaron-Pool the css assets are bundled with the cli. there are used in 2 places I think, in the templates after reading the user project `npx sb init`( vite js/ts / ts legacy) ,and in the sandbox template for contributors vue3-vite/default-ts

Cool, just checking. Looks fine to me then.

**Pull request merged**
