### PR TITLE
UI: Fix addon URL escaping in manager

### PR DESCRIPTION
**Pull request by ndelangen**
The URL injected into the manager for addons were not escaped properly causing them to 404 on some hosting platforms.

I added escaping for these URLs.

### CODE REVIEW

**Comment by ndelangen** [comment]
Hmm having second thoughts on this remapping to different files thing...
If there are split bundles that might break the references..

**Comment by ndelangen** [comment]
OK, I think if found a much better solution!

**Review by tmeasday — APPROVED** [review]
LGTM apart from typo in function name

**Comment by IanVS** [comment]
@ndelangen I think this change might have broken Windows support.  See https://github.com/storybookjs/storybook/issues/19534.

**Comment by mjcarsjens** [comment]
`slash()` is definitely not built to handle encoded backslash characters. Would there be any possible issues with just splitting on both `/` and `\\` and then joining with `/` in `sanitizePath()`? This could theoretically break usage of `\` in UNIX file paths, but I don't really see a use-case for this (even disregarding the fact that this would be a terrible idea wrt cross-platform usage) .

**Pull request merged**
