### PR TITLE
Angular: Add multi-project setup for ng workspaces

### LINKED ISSUE #14026: [6.2.0-beta.1] Angular example stories throw "Unhandled Promise rejection: Type ButtonComponent is part of the declarations of 2 modules: StorybookModule and StorybookModule!"
**Describe the bug**
Switching the examples stories (like the ButtonComponent) throws an error in the console and the component is not rendered at all. Works the first time, but as soon as you go to the same component stories is gonna throw this

```
Unhandled Promise rejection: Type ButtonComponent is part of the declarations of 2 modules: StorybookModule and StorybookModule! Please consider moving ButtonComponent to a higher module that imports StorybookModule and StorybookModule. You can also create a new NgModule that exports and includes ButtonComponent then import that NgModule in StorybookModule and StorybookModule. ; Zone: <root> ; Task: Promise.then ; Value: Error: Type ButtonComponent is part of the declarations of 2 modules: StorybookModule and StorybookModule! Please consider moving ButtonComponent to a higher module that imports StorybookModule and StorybookModule. You can also create a new NgModule that exports and includes ButtonComponent then import that NgModule in StorybookModule and StorybookModule.
    at verifySemanticsOfNgModuleDef (core.umd.js:27446)
    at Function.get (core.umd.js:27384)
    at getInjectorDef (core.umd.js:365)
    at R3Injector.push../node_modules/@angular/core/bundles/core.umd.js.R3Injector.processInjectorType (core.umd.js:11537)
    at core.umd.js:11401
    at core.umd.js:4380
    at Array.forEach (<anonymous>)
    at deepForEach (core.umd.js:4380)
    at new R3Injector (core.umd.js:11401)
    at createInjectorWithoutInjectorInstances (core.umd.js:11373) 
```
**To Reproduce**

1. install 6.2.0-beta.1 (currently just `npx sb upgrade --prerelease`)
2. Open the console
3. Click on the button primary story
4. Click on the button secondary story
5. See error in console and component does not show

**Expected behavior**
No errors are thrown and component can render in every story

**Screenshots**
image

**System**

```
Environment Info:

  System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 81.0.2
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.2.0-beta.1 => 6.2.0-beta.1 
    @storybook/addon-essentials: ^6.2.0-beta.1 => 6.2.0-beta.1 
    @storybook/addon-links: ^6.2.0-beta.1 => 6.2.0-beta.1 
    @storybook/angular: ^6.2.0-beta.1 => 6.2.0-beta.1 
```

**Additional context**
My main goal was to get this change in https://github.com/storybookjs/storybook/issues/10272#issuecomment-759355272 so I could manage the component ng-content. Also tried to install 6.2.0-alpha.13 directly but can see this issue there as well (plus the UI is flickering, but that seems fixed in later versions)

### LINKED ISSUE #19289: Type ...Component is part of the declarations of 2 modules: AppModule and StorybookModule
**Describe the bug**

I'm trying to create story with combined component, but got this error: 

`"Type H1HeadingComponent is part of the declarations of 2 modules: AppModule and StorybookModule! Please consider moving H1HeadingComponent to a higher module that imports AppModule and StorybookModule. You can also create a new NgModule that exports and includes H1HeadingComponent then import that NgModule in AppModule and StorybookModule."`

I do not have any other modules, except AppModule.

**To Reproduce**

I'm using Angular14 and get this error, trying with any angular version choice: 

`npx -p @angular/cli@13.1.x ng new angular14 --routing=true --minimal=true --style=scss --skipInstall=true --strict
Error: This command is not available when running the Angular CLI inside a workspace.
An error occurred while executing: `npx -p @angular/cli@13.1.x ng new angular14 --routing=true --minimal=true --style=scss --skipInstall=true --strict`
🚨 Bootstrapping angular13 failed
🚨 Failed to create repro
Error: Error: command exited with code: 1: 
    at repro (/Users/jurijsbelozjorovs/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/cjs/repro.js:172:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**System**

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: ^6.5.12 => 6.5.12 
    @storybook/addon-essentials: ^6.5.12 => 6.5.12 
    @storybook/addon-interactions: ^6.5.12 => 6.5.12 
    @storybook/addon-links: ^6.5.12 => 6.5.12 
    @storybook/angular: ^6.5.12 => 6.5.12 
    @storybook/builder-webpack5: ^6.5.12 => 6.5.12 
    @storybook/manager-webpack5: ^6.5.12 => 6.5.12 
    @storybook/testing-library: ^0.0.13 => 0.0.13 

**Additional context**

...story.ts

```
import { Meta, moduleMetadata, Story } from "@storybook/angular";
import { AppModule } from "src/app/app.module";
import { DelimiterComponent } from "src/app/components/common-parts/delimiter/delimiter.component";
import { H1HeadingComponent } from "src/app/components/common-parts/headings/h1-heading/h1-heading.component";
import { H2HeadingComponent } from "src/app/components/common-parts/headings/h2-heading/h2-heading.component";
import { TitleSubtitleComponent } from "src/app/components/complex-parts/title-subtitle/title-subtitle.component";

export default {
  title: "Delimiter",
  component: TitleSubtitleComponent,
  decorators: [
    moduleMetadata({
      declarations: [
        H1HeadingComponent,
        H2HeadingComponent,
        DelimiterComponent,
      ],
      imports: [AppModule],
    }),
  ],
} as Meta;

const Template: Story<TitleSubtitleComponent> = (
  args: TitleSubtitleComponent
) => ({
  props: args,
});

export const HelloWorld = Template.bind({});
HelloWorld.args = {
  title: "Hello",
  subtitle: "World",
};
```

app.module.ts 

```
import { NgModule, Injector, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";
import { createCustomElement } from "@angular/elements";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { H1HeadingComponent } from "./components/common-parts/headings/h1-heading/h1-heading.component";
import { H2HeadingComponent } from "./components/common-parts/headings/h2-heading/h2-heading.component";
import { H3HeadingComponent } from "./components/common-parts/headings/h3-heading/h3-heading.component";
import { SectionContentComponent } from "./components/common-parts/section-content/section-content.component";
import { TitleSubtitleComponent } from "./components/complex-parts/title-subtitle/title-subtitle.component";
import { DelimiterComponent } from "./components/common-parts/delimiter/delimiter.component";

const customComponents = {
  "h1-heading": H1HeadingComponent,
  "h2-heading": H2HeadingComponent,
  "h3-heading": H3HeadingComponent,
  "section-content": SectionContentComponent,
  "title-subtitle": TitleSubtitleComponent,
  "delimiter-svg": DelimiterComponent,
};

@NgModule({
  declarations: [
    AppComponent,
    H1HeadingComponent,
    H2HeadingComponent,
    H3HeadingComponent,
    SectionContentComponent,
    TitleSubtitleComponent,
    DelimiterComponent,
  ],
  imports: [BrowserModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  entryComponents: [AppComponent],
  bootstrap: [],
  providers: [],
})
export class AppModule {
  constructor(injector: Injector) {
    for (const [tagName, component] of Object.entries(customComponents)) {
      customElements.define(
        tagName,
        createCustomElement(component, { injector })
      );
    }
  }
  ngDoBootstrap() {}
}
```

### LINKED ISSUE #20213: [Bug]: Support for nrwl/workspace 15.3+ for Angular 15
### Describe the bug

When installing Storybook within an Nx 15+ workspace, we receive a peer dependency conflict for the `@nrwl/workspace` package which requires v14.6.1:

https://github.com/storybookjs/storybook/blob/v7.0.0-beta.3/code/frameworks/angular/package.json#L103

### To Reproduce

_No response_

### System

_No response_

### Additional context

Note, here is where the `@nrwl/workspace` package is referenced within Storybook:

https://github.com/storybookjs/storybook/blob/fd2ce3f18f26372cc082bfded019921d793e282a/code/frameworks/angular/src/server/angular-read-workspace.ts#L23

https://github.com/storybookjs/storybook/blob/fd2ce3f18f26372cc082bfded019921d793e282a/code/frameworks/angular/src/server/angular-read-workspace.ts#L25

Also note that `readNxJson` on line 23 is not exported from `@nrwl/workspace` so this line will always throw. It is found within `@nrwl/devkit`:

https://github.com/nrwl/nx/blob/15.3.3/packages/devkit/index.ts#L63

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Resolves https://github.com/storybookjs/storybook/issues/20213 
Resolves https://github.com/storybookjs/storybook/issues/14026 
Resolves https://github.com/storybookjs/storybook/issues/19289

### Remove NX dependency

Previously, we tried to read the NX configuration during initialization to figure out which tsconfig we have to adjust for Storybook to work with Angular. We remove this kind of check. Instead, as soon as we recognize nx being part of the project, we exit the initialization and point to the excellent [@nrwl/storybook](https://nx.dev/packages/storybook) plugin instead.

### Removed support for Angular < 14

We do not support Angular below v14 anymore (https://github.com/storybookjs/storybook/pull/20559/commits/18b76181efb69d76ce7acf2c9c4aef275ff87e18)

### Remove the legacy way of using Storybook for Angular

In the past, it was possible to start Storybook independently of any [Angular builder](https://angular.io/guide/cli-builder). Running `yarn storybook` did the job. Now Storybook is bound to an Angular project, which is set up in the `angular.json` file. During initialization, new entries are added to a particular project's `architect` section to set up Storybook. You have to run `ng run <project>:storybook` and `ng run <project>:build-storybook` now instead. (https://github.com/storybookjs/storybook/pull/20559/commits/4b68d7558679099c1d5e37f4c883f1f34fbb6d65)

### Multi-project setup in Angular workspace

Before, one Storybook was set up for the entire Angular workspace. Since Storybook is now bound to a particular project, this is not the case anymore. If you have set up multiple applications/libraries within an Angular workspace, you will be asked for which particular project you would like to set up Storybook. (https://github.com/storybookjs/storybook/pull/20559/commits/542c5357c60ad63ce5b1c4d910a52a737a6ed410)

### Optional Compodoc generation

Previously, [compodoc](https://compodoc.app/) was set up automatically for you. You'll be asked if you'd like to set it up for a particular project.

### Fixes some Typescript-related issues related to Template Stories

The stricter set of Typescript rules was causing issues with the Template Stories, which are copied/linked over to a sandbox (https://github.com/storybookjs/storybook/pull/20559/commits/4f4b4e4501658d04db4768cb8eeb5365727b1c93)

### Removed legacy renderer

The `parameters.angularLegacyRendering` option is removed. You cannot use the old legacy renderer anymore.

## Flowchart

F3A2D8DC-A76C-4B9D-A7DD-91869632F034_1_201_a

## How to test

1. Create an angular sandbox (`yarn task --task sandbox --template angular-cli/default-ts --no-link`) (Script sometimes stops at `Publishing packages`. Rerun the command and start from `Run the internal npm server (run-registry)`.
2. `cd ./sandbox/angular-cli-default-ts`
3. `yarn storybook` -> Check whether Storybook runs smoothly. Check whether compodoc documentation is available in the addon section. Button inputs for example has some descriptions.
4. `npx ng generate application new-application` -> Creates a new application in the angular workspace
5. `<path-to-storybook>/code/lib/cli/bin/index.js init` -> Initialize Storybook for new-application. Answer compodoc prompt with `N`.
6. Go to angular.json and check whether `projects.angular-latest.architect.storybook` is configured with compodoc args and `projects.new-application.architect.storybook` is configured without compodoc args.
7. Go to `./projects/new-application/.storybook/main.js` and replace the content with:

```js
const mainRoot = require('../../../.storybook/main.js');
module.exports = {
  ...mainRoot,
  previewAnnotations: [],
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"]
};
```

You must do this for testing because the sub-project does not have defined `template stories`. This adjustment, therefore, is only necessary due to how we set up sandboxes.

8. `npx ng run new-application:storybook`
9. `yarn build-storybook` -> Builds root project. Outputs Storybook dist to `storybook-static`
10. `npx ng run new-application:build-storybook` -> Builds new-application project. Outputs Storybook dist to `dist/storybook/new-application`

### CODE REVIEW

**Comment by mandarini** [comment]
That's great!!! :D Thank you very much @valentinpalkovic for pointing to the Nx plugin! I'm sure it will help with setting up Storybook for Nx. I also like the new Compodoc docs and the opt-in. I need to add this to the `@nrwl/storybook` generator, too. I went through the PR, mainly the parts that are either concerned with Nx or with generators. Looks good to me! :)

Also, how great is this flowchart.

**Review by ThibaudAV — APPROVED** [review]
I read quickly I don't know the context of each change 😁 
But on the whole I think it's great.
And the choice for nx is good

Nice to see people working on this part 😊

**Comment by Marklb** [comment]
Now that the Builder is required, should we still leave a small check to for invalid configuration. In my PR to fix tests, I also removed the deprecated so I could drop the deprecated code's tests. I added a check for the `angularBrowserTarget` property and logged an error message that directs them to the docs for migrating to the builder. Maybe the code just throwing an error when it happens to fail is enough, but maybe this small check could make it more obvious to people that haven't migrated.
The change I am referring to in my PR is: https://github.com/Marklb/storybook/blob/marklb/update-angular-tests/code/frameworks/angular/src/server/framework-preset-angular-cli.ts#L36

**Comment by valentinpalkovic** [comment]
> Now that the Builder is required, should we still leave a small check to for invalid configuration. In my PR to fix tests, I also removed the deprecated so I could drop the deprecated code's tests. I added a check for the `angularBrowserTarget` property and logged an error message that directs them to the docs for migrating to the builder. Maybe the code just throwing an error when it happens to fail is enough, but maybe this small check could make it more obvious to people that haven't migrated. The change I am referring to in my PR is: https://github.com/Marklb/storybook/blob/marklb/update-angular-tests/code/frameworks/angular/src/server/framework-preset-angular-cli.ts#L36

It makes totally sense! Added (https://github.com/storybookjs/storybook/pull/20559/commits/e737b3e50ef011d5247b2bd536ddf6d2a320647e)

**Review by shilman — APPROVED** [review]
Amazing work @valentinpalkovic ❤️ 

A few questions from my testing. In your test instructions:

```
const mainRoot = require('../../../.storybook/main.js');
module.exports = {
  ...mainRoot,
  previewAnnotations: [],
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"]
};
```

What's the purpose of `previewAnnotations`? Is that a typo?

Also, the sandbox generated the following in `angular.json`:

```
        "storybook": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            "configDir": ".storybook",
            "browserTarget": "angular-latest:build",
            "compodoc": false,
            "compodocArgs": [
              "-e",
              "json",
              "-d",
              "."
            ],
            "port": 6006
          }
        },
```

But it seems like `compodoc` is still running/working. Any idea what's going on there?

**Pull request merged**
