### PR TITLE
API to get storybook stories

### PR DESCRIPTION
**Pull request by thani-sh**
This can be used to integrate additional tools with storybook. Example:
- BackstopJS https://github.com/kadirahq/react-storybook/issues/294

### CODE REVIEW

**Comment by arunoda** [comment]
This looks good to me.

**Comment by arunoda** [comment]
May be add some tests. (We don't have tests for other APIs as well)

**Comment by mnmtanish** [comment]
Added tests for `clearDecorators`, `action`, `linkTo` and `getStorybook`

**Comment by mnmtanish** [comment]
@arunoda 
Should this be `getStoryBook` or getStorybook` ?

**Comment by arunoda** [comment]
I think `getStorybook` is great. `Storybook` is usually a single word.
I'm good with others. Take this.

**Pull request merged**
