### PR TITLE
Preact: Fix Preact 8 compatibility

### PR DESCRIPTION
**Pull request by fjorgemota**
Follow-up to #10978 

## What I did

Added support to Preact 8 again.

## How to test

- Is this testable with Jest or Chromatic screenshots? no
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? no

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by fjorgemota** [comment]
Just sent this PR to fix Preact 8 compatibility, as requested in #11145... ping @shilman 

@marvinhagemeister  Could you take a look here too? I needed to force the `render` return type to unknown so I could get Typescript to compile the file correctly...your solution unfortunately didn't work correct :( 

Tomorrow I'll send the next PR to fix the Jest serialization..About that...I have a question: If I understood correctly, it's just a question of updating the dependency? If it is, how we can handle the Preact 8 compatibility there? 

Thanks! :)

**Comment by shilman** [comment]
You're awesome @fjorgemota! Will give it a test later today.

**Comment by shilman** [comment]
@fjorgemota still seeing blank screens in the preact-kitchen-sink. repro:

```
yarn bootstrap --core
cd examples/preact-kitchen-sink
yarn storybook
```

can you take a look?

**Comment by fjorgemota** [comment]
Hey @shilman. Thanks for the fast review!

I looked into the issue and I found two problems:
- One, which I was able to fix in https://github.com/storybookjs/storybook/pull/11225/commits/57effc26d3616c5c2562d92f4713786b1e3dc760, caused Preact 8 to fail with an exception when you changed stories;
- The second one, which you reported, I was not able to fix and I honestly don't have a **good** idea to fix it...BUT I know what it's causing it (so I think that's a good thing...right?). Basically, the `preact-kitchen-sink` is using Preact 8...and that's fine. But, when you run `yarn bootstrap --core`, Yarn is installing Preact 10 in `app/preact/node_modules` folder (probably because preact is a devDependency in that package..)...Which means that, while the vnode is created using Preact 8, the `render` method called actually is from the Preact 10..and, well, one thing isn't compatible with the other. 

To "fix" the second issue, I basically deleted the `node_modules` folder in the `app/preact` folder and everything worked fine.

With that said...should I remove `preact` from `devDependencies` in `app/preact`? Or do you have another good idea about how to fix this issue?

By the way, I didn't found time to try to fix the Jest issue today...I'll try to look into it this weekend, ok? :)

**Comment by marvinhagemeister** [comment]
@fjorgemota I'm afraid to say that the TS types where a bit of a mess during the 8.x release line 😬  

Mixing different major Preact versions is not supported. Preact 10 can't render nodes created by Preact 8 due to a few key breaking changes in the internals.

**Comment by shilman** [comment]
@fjorgemota thanks for double checking. my other PR upgrades the kitchen sink to 10, so as long as you've hand-verified that this works for 8 that addresses my concern. LMK if it's good to go and i'll merge this. will check both of these in my other PR once the jest change is ready. thanks for your patience on this!

**Comment by fjorgemota** [comment]
@marvinhagemeister Yeah...and I personally don't  have any problems with that..I just needed to "force" Typescript to accept that `preact.render` return a `Element` in some cases, but honestly I don't think that's a big problem if you consider we'll have compatibility with both Preact versions. About this:

> Preact 10 can't render nodes created by Preact 8 due to a few key breaking changes in the internals.

I know this. I was just debugging the issue, which AFAIK was caused by the fact that we have preact as a devDependency of the storybook's preact support. I don't think this could be caused by a release build.

@shilman as I commented on the latest comment...I just deleted `node_modules` inside `app/preact` folder (which only contained Preact 10) and everything worked fine with Preact 8. Considering that Preact will not be installed together with storybook (as it's referred only in peerDependencies), everything should work fine for the final user too, so unless I'm wrong about this we will be fine. :)

**Review by shilman — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
