### PR TITLE
FIX: Links in Docs' iframe now pointing to `?path=...` instead of `iframe.html?path=...`

### PR DESCRIPTION
**Pull request by optimista**
Nanochange in the way links are opened from an iframe in docs. Before link with href `/story/comps-comp--def` would lead to `iframe.html?path=/story/comps-comp--def`. Now the same link in markdown leads to `?path=/story/comps-comp--def` which (at least in my case) is desired as having only the canvas with the component without the sidebar, controls and header etc. isn't very informative and useful.

## What I did

The problem was resolved by adding `href="/"` to `<base target="_parent" />` tag in `lib/core-common/src/templates/base-preview-head.html`.

PS: My first PR ever. Thank you for your patience and feedback.

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @optimista thanks a lot for your contribution! This might be a tricky change, let me try and do some QA to assess it. 

for myself:
[ ] - Running Storybook in a local directory like `localhost:4000/storybook`
[ ] - Running in dev mode
[ ] - Running in served static from storybook-build

**Comment by yannbf** [comment]
Hey @optimista thanks once again for your contribution! And for your patience.

I tested out your solution and although it does fix some annoying problems, it introduces another problem in the following scenario:

> Running Storybook in a local directory like localhost:4000/storybook

When Storybooks are hosted under a path like `/storybook`, the `base` property has to be set to that said path, otherwise Storybook will fail fetching its resources and be stuck in a loading state:

image

## Reproduction steps

1. Change the build command to output the statics under a second level folder `build-storybook -o build/storybook`
2. Serve the first level folder with something like `npx http-server ./build --port 6009` (you might need to change the port or clear cache when re-running this command)
3. Load the Storybook URL like http://127.0.0.1:8080/storybook
4. See the error

In that scenario, if you make changes the following change:

```html
<base href="/storybook" target="_parent">
```

it should then work

**Comment by yannbf** [comment]
To anyone that stumbles upon this PR, an easy way to compare/test the solution is to serve `official-storybook` and access the following path to the Links section of the **markdown-docs** story:
http://localhost:9011/?path=/docs/addons-docs-markdown-docs--page#links

Then compare with the `next` version of Storybook without the fix:
https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-docs-markdown-docs--page#links

And play around with the bottom links at that page

image

**Comment by yannbf** [comment]
Hey @optimista do you happen to have any updates? Thank you!

**Comment by ndelangen** [comment]
@yannbf what update are you expecting? I don't think this could ever work, could it?

**Comment by yannbf** [comment]
> @yannbf what update are you expecting? I don't think this could ever work, could it?

Good question. I'm not sure, but if we do find a scenario that accomodates this too, I'm good!

- [ ] Running Storybook in a local directory like localhost:4000/storybook

**Pull request closed without merging**
