### PR TITLE
Bug: disable cache in dev-mode

### LINKED ISSUE #21443: [Bug]: Manager.js caching prevents changes in theming
### Describe the bug

Reported by @yannbf 

Changing themes is slightly frustrating, as the manager.js file is cached by the browser, e.g. http://localhost:6006/sb-addons/storybook-11/manager-bundle.mjs

And as a result, if you change your theme to something else (e.g. from light to dark mode), it seems like Storybook didn't do anything. Busting the cache in the browser does the job, but it doesn't feel great. In this gif, you can see that I can refresh many times and Storybook still uses the previous theme. After hard refreshing, it works.

image

### To Reproduce

- Create a sandbox
- Startup the sandbox
- Change the theme in `manager.js`
- Go back to the browser. Theme only updates after a hard refresh

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #21443

## What I did

I just added a no-cache control header on every request coming from the storybook dev-server

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Open Storybook in your browser
3. check the request in the network tab, they should all show no-cache headers

### CODE REVIEW

**Comment by ndelangen** [comment]
@shilman let's discuss after storybook day?

**Comment by chakAs3** [comment]
i was really waiting for this. i was manually do it disabling the cache or opening incognito, but still in incognito i don't have vue extension.

so thanks @ndelangen

**Review by chakAs3 — APPROVED** [review]

**Review by chakAs3 — APPROVED** [review]
i will go ahead i merge this PR, these simple lines of code could saved 2 days of my life i was burning

**Comment by DarthVitalus** [comment]
Hi, guys! Could you please help me out here. Is there a way to change this header by config? Maybe `webpackFinal`? i've tried to make 
```js
/* .storybook/main.js */
module.exports = {
  webpackFinal: (config) => ({
    ...config, 
    devServer: { 
      proxy: { 
        '/static': { 
          headers: { 
            'Cache-Control': 'no-cache' 
          }
        }
      }
    }
  })
};
``` 
and still got `no-store`. So my fonts are loading again and again on every story i visit (and keep, you know, swapping). In develop build, production is good. I'm trying to understand, either i'm doing something wrong, or this behavior should be somewhat more configurable?

**Pull request merged**
