### PR TITLE
Vue: Update events binding in Vue render

### PR DESCRIPTION
**Pull request by gitstart**
Issue: https://github.com/storybookjs/storybook/issues/19318

## What I did

- Vue2 renderer renders only `v-bind="$props"` in component template which missed the right way of binding custom events in Vue 2 with `v-on` or `@...`, in this PR, we base on `argType.table.category` `events` to add events binding into template.

## How to test

```bash
cd code
yarn task --task dev --template vue-cli/vue2-default-js 
open http://localhost:6006/?path=/story/lib-store-hooks--use-state
```

Open `Interactions` panel and verify all tests are passed

image

### CODE REVIEW

**Comment by ndelangen** [comment]
@storybookjs/vue is this good to merge?

**Comment by Aaron-Pool** [comment]
> @storybookjs/vue is this good to merge?

Looks fine to me, though the cleanest approach would be to also pull the properties that correspond to events off the `$props` object that's getting passed to `v-bind` so that duplicate, unintended attributes don't get passed along, potentially gumming up the works in lower down components.

**Comment by ndelangen** [comment]
@gitstart or @Aaron-Pool could either of you make that suggested change? 🙏

**Comment by ndelangen** [comment]
@storybookjs/vue can someone give this the 👍 in a code-review? Then I'll merge it.

**Pull request merged**
