### PR TITLE
Add Knip with initial config

### PR DESCRIPTION
**Pull request by webpro**
[Knip](https://github.com/webpro/knip) is a tool to find unused files, dependencies and exports. There are multiple ways to use it, and in the Storybook repo, for starters, it could be a great companion for clean ups and refactorings.

This PR contains Knip with some initial configuration to get started. Analysis can be done for the project as a whole, or per workspace. Also, output can be filtered for specific issue types. A few example commands to get an idea:

```
yarn knip
yarn knip --workspace ui/manager --include dependencies,unlisted
yarn knip --workspace ui/manager --include files
```

Please refer to the Knip docs for more details.

The Storybook project would benefit from a programmatic API and/or dynamic configuration (e.g. `knip.ts` instead of `knip.json`). For instance, to read the entry files from the `package.json#bundler.entries` in many workspaces and merge into the Knip config. Both are on Knip's roadmap.

Please let me know if you have any questions or feedback regarding Knip or this PR specifically.

Let's get this collaboration started and find out how we can help each other while improving DX for everyone :)

### CODE REVIEW

**Comment by ndelangen** [comment]
@webpro thanks for bringing this my my attention, and thank you for the detailed explanation of knip in the meeting.

I don't see knip being used anywhere? no CI config change, and also no documentation on how to run things manually.

We chatted about integrating it into the check script that each of our packages have.

How do you propose we move this PR forwards?
I'm trying to lower the PR count on storybook, so it be nice if we have some plan for eventually getting this PR moving towards a goal.

**Comment by webpro** [comment]
Oh I forgot to mention: when running `knip` from the `ui/manager` package directory, the last line of the root `code/knip.ts` needs to be commented out:

```
// export default addBundlerEntries(baseConfig);
```

Quickly got into TS config issues when separating this and didn't want to introduce more changes into this PR at this point.

**Comment by ndelangen** [comment]
@webpro I'll keep knip in mind, and will come back to it later.

Thank you for your time, energy and expertise working on this PR.
Sadly I'll close it for now.

**Comment by webpro** [comment]
Of course, Norbert. Let me know if/when I can help. Best of luck!

**Pull request closed without merging**
