### PR TITLE
Fix loader concatentation bug

### PR DESCRIPTION
**Pull request by stefvhuynh**
This has to do with using custom `webpack.config.js` files. The code tries to add `customConfig.module.loaders`. And if `customConfig.module` is not defined, there is an error.

### CODE REVIEW

**Comment by arunoda** [comment]
I need more information. I can't see what this solves anything. This change seems to have no effect on anything.

Am I wrong?

**Comment by stefvhuynh** [comment]
If I have a custom webpack config that looks like this, it'll break:
```
module.exports = {
  resolves: { extensions: [".jsx"] }
}
```
I can fix it, by changing it to this:
```
module.exports = {
  resolves: { extensions: [".jsx"] },
  module: {}
}
```
Take a look at these lines: https://github.com/kadirahq/react-storybook/blob/master/src/server/config.js#L90-L93

If `customConfig.module` does not exist, it uses `{}`. However, on line 93, it expects `customConfig.module` to be defined (to access `customConfig.module.loaders`).

**Comment by arunoda** [comment]
Okay. I got it.
Then the PR should be something like this:

```js
return {
    ...customConfig,
    // We'll always load our configurations after the custom config.
    // So, we'll always load the stuff we need.
    ...config,
    // We need to use our and custom plugins.
    plugins: [
      ...config.plugins,
      ...customConfig.plugins || [],
    ],
    module: {
      ...config.module,
      // We need to use our and custom loaders.
      ...customConfig.module || {},
      loaders: [
        ...config.module.loaders,
        ...customConfig.module? customConfig.module.loaders || [] : {},
      ],
    },
  };
```

Isn't it?

**Comment by stefvhuynh** [comment]
I think instead of `{}`, you want `[]` for the second part of the ternary. But whichever way you prefer is how I'll do it (with the ternary or by defining `module` like I did).

**Comment by arunoda** [comment]
@stefvhuynh Your PR sounds great. I'll do a release within today.

**Pull request merged**
