### PR TITLE
React: Update `react-docgen` to `6.0.1`

### PR DESCRIPTION
**Pull request by danez**
## What I did

I updated `react-docgen` to its latests version `6.0.1`.

Feel free to tell me if there is more work I need to do, or feel free to take over this PR and make it ready for merge. My initial goal is to see if an update is possible and if there are exports from `react-docgen` missing (which there were).

## How to test

Honestly I have no idea how to test. I tried `yarn start` but that fails with an error from yarn 

```
Cannot link @storybook/react-vite into before-storybook@workspace:. dependency @vitejs/plugin-react@npm:3.1.0 [7f3e5] conflicts with parent dependency @vitejs/plugin-react@npm:4.0.0
```

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Thanks so much @danez !! Will discuss with the team and figure out a path forward here. Congratulations on your upcoming release 🚀

**Comment by danez** [comment]
I already fixed some of the typescript issues, but haven't released yet because I found more TypeScript issues. Will push here once the next version is out.

**Comment by danez** [comment]
I fixed the Typescript issues on my side, the remaining ones I am not sure what to do about. It seems you are validating external types with your own tsconfig. So not sure what I can do about this.

**Comment by shilman** [comment]
@danez I have tested this out in another branch and it's working great. You can see my instructions for "how to test" on this PR https://github.com/storybookjs/storybook/pull/23825. Please kick the tires and let me know what you think!

Unfortunately, the logic that converts `react-docgen` output to `ArgTypes` (Storybook's representation of the same) is pretty dicey, so we'll need to update that to fully support `react-docgen`. But now that you have resolver support, I think we'll dedicate some time to improving that and will make `react-docgen` the default in Storybook 8.0.

Amazing job on the release and huge shout out to you and to @phated for his work on resolvers -- so exciting to see this finally in action.

**Comment by valentinpalkovic** [comment]
@shilman Does https://github.com/storybookjs/storybook/pull/23825 replace this PR? And if so, can we close it?

**Pull request merged**
