### PR TITLE
Publish package sources along with transpiled files

### PR DESCRIPTION
**Pull request by Hypnosphi**
Issue: #2602 

In #2589, I introduced `jsnext:main` fields so that eslint can resolve named and default exports when importing one package from another. They point to files in `src` directories that aren't published currently.

### CODE REVIEW

**Comment by igor-dv** [comment]
I think we don't want to publish `src` files...

**Comment by marcin-mazurek** [comment]
@igor-dv If you don't publish the `src` folder, then it doesn't make sense to set the `esnext:main` to `src` (which is needed for tree shaking and so on).

**Comment by Hypnosphi** [comment]
> I think we don't want to publish src files

What's exactly the problem with it? I find it very convenient to be able to view external packages' sources directly in `node_modules` directory

**Comment by tmeasday** [comment]
I don't feel very expert on this but I've seen it done before and it feels OK to me.

**Review by tmeasday — APPROVED** [review]
Happy to approve this

**Review by ndelangen — APPROVED** [review]
This would allow smart bundlers to tree-shake, correct?

LGTM

**Comment by Hypnosphi** [comment]
> This would allow smart bundlers to tree-shake

Well we can actually to that ourselves, by tweaking our default webpack config =)

**Pull request merged**
