### PR TITLE
use @storybook published deprecated dependencies

### PR DESCRIPTION
**Pull request by danielduan**
Issue: temporarily relieves #2303 

## What I did

forked all the komposer/mantra deprecated packages and published version without peer dependency warning

## How to test

Is this testable with jest or storyshots?
n
Does this need a new example in the kitchen sink apps?
n
Does this need an update to the documentation?
n
If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
Nice! LGTM! Do I need to test before we merge?

**Review by shilman — APPROVED** [review]
@danielduan see comment above

**Comment by danielduan** [comment]
@shilman I tested on vue, cra, and crna. We'll see if this netlify thing works too.

**Comment by danielduan** [comment]
I'm really confused about the `build` yarn failure. I just ran that same command and it didn't change anything.

**Pull request merged**
