### PR TITLE
Switch to UglifyJS that supports ES6 and up

### PR DESCRIPTION
**Pull request by ggarek**
Issue:

## What I did
Use `uglify-es` through `uglifyjs-webpack-plugin` to be able to minify es6+ code.

I stumbled upon same issue, then found [this PR](https://github.com/storybooks/storybook/pull/1733), which was not very active recently. So i submit this PR in continuation to original one.

## How to test

I tested as proposed in the original PR. Here are some screenshots.

Build time (is ~28s)
screen shot 2017-12-22 at 16 04 26

Bundle size 
```
1.8M	storybook-static/static/manager.84cf3a1cca5073d55149.bundle.js
1.2M	storybook-static/static/preview.09c4e2758e41ca532a7c.bundle.js
```

screen shot 2017-12-22 at 16 14 57

**Note**
I have no opportunity to check IE 😭

### CODE REVIEW

**Comment by Hypnosphi** [comment]
I changed base to `release/3.3`. Would you mind resolving the conflicts?

**Comment by ndelangen** [comment]
@ggarek Amazing you want to pick this up, thank you so much!

I would love to merge this as soon as possible.

I do think we need to adjust this not just for react and react-native, but also for Vue and Angular.
Would you be able to do that too? Please ask for help if you need it 👍

**Comment by ndelangen** [comment]
merged in master after the 3.3 merge (saved you the plain of the merge conflicts) and added the code to angular & vue

**Comment by ndelangen** [comment]
[CRA](https://deploy-preview-2530--storybooks-cra.netlify.com/?selectedKind=Welcome&selectedStory=to%20Storybook&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel)
[Vue](https://deploy-preview-2530--storybooks-vue.netlify.com/?selectedKind=Welcome&selectedStory=Welcome&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel)
[Angular](https://deploy-preview-2530--storybooks-angular.netlify.com/?selectedKind=Welcome&selectedStory=to%20Storybook&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel)

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Anyone from @storybooks/team want to review and possibly merge?

**Review by igor-dv — APPROVED** [review]

**Pull request merged**
