### PR TITLE
Vue properties test WIP

### PR DESCRIPTION
**Pull request by shilman**
Issue: #9838 

## What I did (w/ @pocka)

1) Adapted the test setup from https://github.com/pocka/vue-docgen-loader/blob/master/test/compiler.js

Error: `warn: Unhandled rejection TypeError: setTimeout(...).unref is not a function`

2) Based on  https://github.com/facebook/jest/issues/1909 , tried creating a `addons/docs/jest.config.js` with:

```js
module.exports = {
  testEnvironment: 'node',
};
```

But got the error:

```
    Could not locate module babel-runtime/core-js/get-iterator mapped as:
    core-js/es/get-iterator.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/babel-runtime\/core-js\/(.*)/": "core-js/es/$1"
      },
      "resolver": undefined
    }
```

3) Based on https://github.com/miaolz123/vue-markdown/issues/18 , tried adding `babel-runtime` as a devDependency. But the error persists.

## How to test

Doesn't currently work:

```
yarn jest --testPathPattern=vue-properties.test.ts --watch
```

### CODE REVIEW

**Comment by Aaron-Pool** [comment]
Still hoping to look at this, but I'm wrapping up a sprint at work and then I'm out of town till Saturday, so it could be a few days 😕

**Comment by Aaron-Pool** [comment]
@shilman I finally got around to trying to dig in to this, but I'm having some troubles bootstrapping the repo in general. Does this need to be merged to master or anything? I'm definitely running latest of both node and yarn (which has been my problem in the past).

**Comment by shilman** [comment]
@Aaron-Pool I updated the branch from `next` and resolved conflicts. `yarn bootstrap --core` is working for me. Try again?

**Comment by Aaron-Pool** [comment]
Apologies for the meaningless commit messages. It's late, and I'm tired. I think I fixed it, possibly? The test is still failing, but only because of a timeout, and not any runtime or compilation issues. I believe the real issue was actually that the `yarn jest --testPathPattern=vue-properties.test.ts --watch` command being run was actually running the jest config from the root of the package, rather than the `jest.config.js` in the `addon/docs` folder. But maybe I'm getting this all wrong 🤷‍♂

**Comment by Aaron-Pool** [comment]
Oh, I just woke up and in my more rested state I realized that I forgot to mention that I specifically got it working by the changes I made _in addition to_ using the `--config="./add-ons/docs/jest.config.js"`

**Comment by shilman** [comment]
Thanks so much @Aaron-Pool !!! 🙏 I'll try to get it merged in the next few days 🚀

**Pull request closed without merging**
