### PR TITLE
Forked CRA support on Windows

### PR DESCRIPTION
**Pull request by sergeyzwezdin**
Issue: Support for CRA fork packages on Windows (#5801)

## What I did

I've added parsing of `.bin/react-scripts` file to find out actual `react-scripts` package path.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Any chance you can add a unit test for this in `cra-config.test.js`? This is hard to test without a windows machine and inside our monorepo which doesn't have any CRA-fork apps. But I'd feel a lot better about merging if I knew what the data looked like.

**Comment by sergeyzwezdin** [comment]
@shilman Hm, I would happy to add that, but I do not understand how to emulate `.bin` and `node_modules` folder in the test. If you advise me, I will add it for sure.

**Comment by shilman** [comment]
@sergeyzwezdin if you look at the existing tests, the `fs` module is already mocked, so you can make it return whatever you want in your test. Make it return something that looks like what you'd get on the windows machine, and verify that the result of your new code is what you'd expect. Does that make sense?

**Comment by sergeyzwezdin** [comment]
@shilman Sounds good. I'll try it tomorrow morning.

**Comment by shilman** [comment]
Great @sergeyzwezdin. Thanks for your patience on this and I'll get it merged and released on alpha as soon as I'm comfortable with the change.

**Comment by sergeyzwezdin** [comment]
@shilman Ok, I managed to add the test. It seems everything is 👌now.

**Review by shilman — APPROVED** [review]
Looks super, great job @sergeyzwezdin! 🚀 I'll release this on alpha today (and post on the issue) and then will patch it back into master once you test it out on the alpha. Sound ok?

**Comment by sergeyzwezdin** [comment]
@shilman yep, sounds cool! 👍🏼

**Comment by shilman** [comment]
@sergeyzwezdin ready for testing 🔍

**Comment by sergeyzwezdin** [comment]
@shilman Works like a charm. When do you plan to release it?

image

**Comment by shilman** [comment]
Super. I've been doing alpha releases every other day (ish) and stable releases once or twice a week (ish) so probably tomorrow. I'll post on the issue when it's live

**Comment by sergeyzwezdin** [comment]
Cool! Waiting for that then. Thank you for you help.

**Pull request merged**
