### PR TITLE
Angular: Add "assets" build option

### PR DESCRIPTION
**Pull request by Marklb**
Closes #

## What I did

Added "assets" option to builder options, so assets can be configured in `angular.json` with Angular's format.

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template angular-cli/default-ts`
2. Add an asset. e.g. `assets/example_img.png`
3. Add "assets" to builder options in `angular.json`. e.g. `"storybook": { ..., "options": { ..., "assets": [ "src/assets" ] } }`
4. Use an asset in a story
5. Open Storybook in your browser
6. Check if a story can access the asset

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
Hey @Marklb,

Thank you for your contribution!

Does it mean that https://storybook.js.org/docs/7.0/angular/configure/images-and-assets#serving-static-files-via-storybook-configuration still works and you want to introduce a way of configuring assets the "Angular way"?

**Comment by Marklb** [comment]
@valentinpalkovic As far as I know, this should have no effect on Storybook's current static directory option. I use Angular's object format for defining assets, which lets me alias the paths, and I would rather not maintain a second assets configuration.

**Comment by valentinpalkovic** [comment]
@Marklb The pipeline is still red. Merging `next` into your branch may fix the issue.

**Comment by valentinpalkovic** [comment]
@Marklb Have you figured out why the pipeline is failing? Should I step in and help you with debugging?

**Comment by Marklb** [comment]
@valentinpalkovic Thanks for taking care of the pipeline error. I have been meaning to look at that, but have been busy with something for work. There isn't any other known problems with this PR is there?

**Comment by valentinpalkovic** [comment]
No, seems to be fine. Currently, we have a merge freeze. After the Storybook Day took place, I will merge it :)

**Review by valentinpalkovic — APPROVED** [review]

**Pull request merged**
