### PR TITLE
Fix custom themes breaking the welcome demo.

### PR DESCRIPTION
**Pull request by Qazzian**
Having applied a dark theme to storybook I noticed that the react demo sets the background white but does not set the text color. This resulted in white text (from my custom theme) rendered on a white background. This change will make the text readable

Issue:

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Makes sense, thanks for the fix!!!

**Comment by shilman** [comment]
@Qazzian mind updating the snapshots?

```
yarn test --core --update
```

**Comment by Qazzian** [comment]
I've run the tests locally and I'm not getting any errors with the snapshots.
running `yarn test --core --update` doesn't  change the snapshots.

I've followed the contribution guide for setting up my dev environment, and tried a second time after running a reset.

This is the summary I get after running `yarn test`
```
Test Suites: 109 passed, 109 total
Tests:       901 passed, 901 total
Snapshots:   277 passed, 277 total
Time:        247.199s
Ran all test suites in 8 projects.
```

**Comment by Qazzian** [comment]
So I've fixed the snapshots. 
The only thing that's blocking the merge now is automention. 
Is there anything I need to do to help this?

**Comment by shilman** [comment]
Thanks for taking care of that @Qazzian!!

**Pull request merged**
