### PR TITLE
Fix webpack cache invalidation

### PR DESCRIPTION
**Pull request by 7rulnik**
Issue: see https://github.com/webpack/webpack/issues/15214 for more info

## What I did

Added `noop` function so https://unpkg.com/browse/@storybook/addon-docs@6.4.13/dist/esm/lib/convert/typescript/types.js and others will not be empty.

I'm not sure that it's the best solution, to be honest.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by tmeasday** [comment]
Looks like maybe we should wait to see what happens on the WP end here?

**Comment by 7rulnik** [comment]
@tmeasday yeah, I think we can wait and it could be workarounded via [usedExports](https://webpack.js.org/configuration/optimization/#optimizationusedexports)

**Comment by 7rulnik** [comment]
This bug was fixed in webpack https://github.com/webpack/webpack/pull/15367
Let's close it

**Comment by tmeasday** [comment]
Thanks @7rulnik!

**Pull request closed without merging**
