### PR TITLE
Presets - add babelDefault extension

### PR DESCRIPTION
**Pull request by igor-dv**
Issue: https://github.com/storybooks/storybook/pull/4107#discussion_r216251083

## What I did 
Added an option to extend "babelDefault" method in presets

### CODE REVIEW

**Review by Hypnosphi — APPROVED** [review]

**Comment by pksunkara** [comment]
IMO, we should move `babelDefault` to `babel`.

**Comment by igor-dv** [comment]
That was my initial thought. But I can see why it may break... maybe when we will remove the support of babel 6 we will be able to remove `babelDefault` as well 🤷‍♂️

**Comment by Hypnosphi** [comment]
IMO, we should remove `babelDefault` to `babel`, and move `babel` to `webpack` =)

**Comment by igor-dv** [comment]
can you please share an example ?

**Comment by Hypnosphi** [comment]
```
export function webpack(config) {
  return {
    ...config,
    // find babel-loader here and add docgen plugin
  };
}
```

But maybe it's not worth it

**Comment by igor-dv** [comment]
Yeah, I don't like it much. It is less API friendly and more error-prone. I have another idea about what to do with `babelDefault`. Will PR asap

**Pull request merged**
