### PR TITLE
Allow collapsing active story and use separate expansion for filtered

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: #5594 and #5419 

## What I did

Refactored the expanded set to be more stateful.

Note that the keyboard events don't seem to actually ever get triggered, so I can't really test them properly: https://github.com/storybooks/storybook/issues/5623

### CODE REVIEW

**Comment by tmeasday** [comment]
Note that there is a noticeable hang when you type the first two characters into the search field. According to the profiler it is mostly in re-rendering the treeview.

We have this behaviour where basically every node in the tree is rendered as you enter two characters into the search field as it is expanding all the matches. Previously (4.x) this performed OK--was this because the previous version simply changed visible state on leaves of the tree rather than redrawing itself @ndelangen?

**Review by shilman — APPROVED** [review]
LGTM, will test before release

**Comment by shilman** [comment]
@tmeasday please update snapshots

**Review by shilman — CHANGES_REQUESTED** [review]
@tmeasday please update snapshots

**Comment by tmeasday** [comment]
@shilman rebased onto latest `next`. Again didn't need to update any snapshots

**Pull request merged**
