### PR TITLE
feat: Added vue docgen options for vite builds

### LINKED ISSUE #22909: [Bug]: Ability to pass vueDocgenOptions into vue3-vite framework options
### Bug
Can't compile some `vue3` stories without `jsx`.

### Fix
Please add the ability to pass `vueDocgenOptions` into `vue3-vite`  framework options.

### Details
By default `jsx` transform is enabled in `docgen`, and the compilation of some of my stories without `jsx` fails with `parse error`. 
Docgen's `parse` method is being used here:
https://github.com/storybookjs/storybook/blob/3415baef7dce037708c3473526c7750ee127ac5a/code/frameworks/vue3-vite/src/plugins/vue-docgen.ts#L16
As it [states](https://vue-styleguidist.github.io/docs/Docgen.html#parse-filepath-string-options-docgenoptions-componentdoc) in the `docgen` docs - `parse` method accepts options as a second argument. 

I need the abilty to pass `{ jsx: false }` as an option into this method, so it will look something like this:
```typescript
// vue-docgen.ts#L16
const metaData = await parse(id, vueDocgenOptions); 
```

```typescript
// my main.ts
const config: StorybookConfig = {
  framework: {
    name: '@storybook/vue3-vite',
    options: { vueDocgenOptions: { jsx: false }}
  }
}
```

Note that `vueDocgenOptions` is similar to the same option in `addon-docs`: https://github.com/storybookjs/storybook/blob/3415baef7dce037708c3473526c7750ee127ac5a/code/addons/docs/vue3/README.md?plain=1#L60

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by OssamaSijbesma**
Closes #22909 

## What I did

I added the possibility to configure the  vue docgen options for advanced usage in Vite. For example for monorepo file aliases for docs.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Added logging to the `preset.ts` and `vue-docgen.ts`.
2. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template vue3-vite/default-ts`.
3. Change the main.ts options (repeatedly based on those options: https://vue-styleguidist.github.io/docs/Docgen.html#api)
4. Checked if the variables are passed correctly and output.

### Documentation

- [x] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by JReinhold** [comment]
Thanks for this! We're thinking about migration Vue docgen to Volar, how does this relate to that? Is this related/compatible with that, or is this different?

**Comment by kasperpeulen** [comment]
cc @chakAs3

**Comment by chakAs3** [comment]
Yes there is already a PR opened addressing docgen, as @JReinhold said we moving to the official Vue language tools.
@kasperpeulen i will be checking the performance issue on the code transform, so we can merge it next week.

**Review by chakAs3 — COMMENTED** [review]
Hi @OssamaSijbesma I'm suggestion to open an other PR  after merging #22285, please check it out and see if you think the PR still relevant, so we can workout the merge

**Comment by ndelangen** [comment]
Please re-open if indeed relevant.

**Pull request closed without merging**
