### PR TITLE
Allow injecting preview-body.html

### PR DESCRIPTION
**Pull request by ewgenius**
Issue:

In my project I have some components which require specified div element `<div id="portal-id"></div>`. So the only way to make it working with Storybook is to allow extending preview body.

## What I did

I extended `getPreviewBodyHtml` function to look for `preview-body.html` (same as `preview-head.html`) and inject its contents to the body of story previewer

### CODE REVIEW

**Comment by shilman** [comment]
@ewgenius Thanks for putting this together. I've marked this for 5.3 (we're just getting 5.2 shipped atm) but if it's urgent let me know and we might be able to expedite it.

**Comment by ewgenius** [comment]
@shilman awesome, thank you. It is not urgent, I can wait for 5.3 release.

**Comment by ewgenius** [comment]
Hmm, @shilman how long it might take to have first 5.3 release? 5.2 is 67% complete, so if possible I'd like to have this feature in one of next 5.2.0-alpha releases
image

Please let me know If I'll need to switch base branch of my pull request for this

**Review by shilman — APPROVED** [review]
LGTM. Clean change.

**Comment by shilman** [comment]
@ewgenius Hope to ship 5.2 in the next 3 weeks. 🤞 I've approved the PR and will let it sit for a couple days in case other people have opinions on this. I'll make the call on 5.2 vs 5.3 then.

**Comment by shilman** [comment]
@ewgenius Sorry for the radio silence. It's been a busy few weeks. Merging now and will release a beta today.

**Comment by ewgenius** [comment]
@shilman thank you!

**Pull request merged**
