### PR TITLE
Fix #4217, exit build when successful

### LINKED ISSUE #4217: build-storybook not exiting after build completes
### Bug or support request summary
- Running build-storybook works but does not exit the process making it impossible to proceed to in a CI process or script.

### Steps to reproduce

- Run 
`npx build-storybook`

screen shot 2018-09-22 at 9 21 32 am

### Please specify which version of Storybook and optionally any affected addons that you're running
- Current alpha version
- master branch

### Affected platforms 
All

### Acceptance criteria

When the build-storybook script completes it should exit

### PR DESCRIPTION
**Pull request by nelsonomuto**
Issue:
#4217 
## What I did
Added the `process.exit()` line so that the process will exit after a build

## How to test

Is this testable with Jest or Chromatic screenshots? no
Does this need a new example in the kitchen sink apps? no
Does this need an update to the documentation? no

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by nelsonomuto** [comment]
how do I label this, I don't have the ability to add the label

**Comment by ndelangen** [comment]
Just a note that using process.exit([number]) is not recommended practice.

The reason this is problematic is because writes to process.stdout in Node.js are non-blocking and may occur over multiple ticks of the Node.js event loop. Calling process.exit(), however, forces the process to exit before those additional writes to stdout can be performed.

Rather than calling process.exit() directly, the code should set the process.exitCode and allow the process to exit naturally by avoiding scheduling any additional work for the event loop:

If you can you should set the exit code and allow Node to exit gracefully:

process.exitCode = 1;

This is what we're doing.

What's holding the process open is the question.

**Comment by ndelangen** [comment]
Pasting this here as info for later debugging session:

> You can call process._getActiveRequests() to get a list of active I/O requests and process._getActiveHandles() to get a list of open handles/file descriptors.

**Comment by contra** [comment]
@ndelangen Was this addressed anywhere? Possible to reopen this?

**Pull request closed without merging**
