### PR TITLE
Draft: Update doc examples with new 6.3.x React types

### PR DESCRIPTION
**Pull request by jacobarriola**
Issue:
n/a

## What I did
According to https://github.com/storybookjs/storybook/pull/15292, the types were updated; however, the docs still reflect the legacy 6.x types.

I'm opening a draft PR to see if this is something worth pursing. Happy to keep going (just did one button).

Thanks!

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by jacobarriola** [comment]
👋🏽 Hi @shilman - not sure if you're the right person to ping here, but I thew up this draft PR based on #15292 - let me know if I'm the right path and should keep going. Thanks!

**Comment by MichaelArestad** [comment]
Let's schedule a meeting to discuss the type systems. @shilman can you set up a meeting in the next week or two with @ndelangen and @yannbf?

**Comment by jonniebigodes** [comment]
@MichaelArestad and @jacobarriola the TypeScript examples are already using the new types. If you check the documentation for [6.4 rc](https://storybook.js.org/docs/6.4/react/get-started/introduction) you'll see them already added. My idea for this is the following, once 6.4 is launched and the 6.3 documentation is placed on its own branch, I wouldn't mind and would appreciate the help on getting the examples documented for consistency. Let me know what you think and we'll go from there.

Have a great week.

Stay safe

**Comment by jonniebigodes** [comment]
@jacobarriola a friendly reminder to ask you if you still have the time to address this? Let me know and we'll go from there. Hope you have a fantastic weekend.

Stay safe

**Comment by jacobarriola** [comment]
Hi @jonniebigodes !

So sorry, I saw this and never circled back.

Yes, I have time and would ❤️ to contribute. How do we move forward?

**Comment by jacobarriola** [comment]
Hey @jonniebigodes ! Checking in again so this PR comments surfaces. Let me know how we should proceed.

Thanks!

**Comment by jonniebigodes** [comment]
@jacobarriola Sorry for the delayed response was busy with other documentation updates. I think that we're good on closing this pr for now! As the documentation is updated to reflect the correct types. 

Thanks for taking the time and effort into this pull request. Looking forward to your next contribution.

Hope you have a great week!

Stay safe

**Pull request closed without merging**
