### PR TITLE
Maintenance: Disable minification in build scripts

### PR DESCRIPTION
**Pull request by tobiasdiez**
Closes https://github.com/storybookjs/storybook/discussions/23970

## What I did

Remove minification in build scripts so that the distributed files are human-readable. This makes debugging of storybook issues 1000 times easier. Since the storybook packages are passed through a bundler anyway, minimifaction doesn't provide any real benefit for production.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

Run the `scripts/prepare/bundle.ts` script on some packages and look at the output produced in `dist`.

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createSize |  0 B | 0 B | 0 B | - | - |
| generateSize |  76.3 MB | 76.3 MB | 0 B | **1.36** | 0% |
| initSize |  167 MB | 183 MB | 15.5 MB | **664.67** | 🔺8.5% |
| diffSize |  91.1 MB | 107 MB | 15.5 MB | **1924.12** | 🔺14.5% |
| buildSize |  7.42 MB | 8.78 MB | 1.36 MB | **423766.56** | 🔺15.5% |
| buildSbAddonsSize |  1.61 MB | 1.63 MB | 19.3 kB | **4925** | 1.2% |
| buildSbCommonSize |  195 kB | 195 kB | 0 B | - | 0% |
| buildSbManagerSize |  2.29 MB | 3.46 MB | 1.18 MB | **88946.97** | 🔺33.9% |
| buildSbPreviewSize |  351 kB | 507 kB | 156 kB | **54485.88** | 🔺30.7% |
| buildStaticSize |  0 B | 0 B | 0 B | - | - |
| buildPrebuildSize |  4.45 MB | 5.8 MB | 1.35 MB | **210061.1** | 🔺23.3% |
| buildPreviewSize |  2.97 MB | 2.98 MB | 11.7 kB | **3644.35** | 0.4% |
| testBuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbAddonsSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbCommonSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbManagerSize |  0 B | 0 B | 0 B | - | - |
| testBuildSbPreviewSize |  0 B | 0 B | 0 B | - | - |
| testBuildStaticSize |  0 B | 0 B | 0 B | - | - |
| testBuildPrebuildSize |  0 B | 0 B | 0 B | - | - |
| testBuildPreviewSize |  0 B | 0 B | 0 B | - | - |

| name | before | after | diff | z | % |
| ---- | ------ | ----- | ---- | - | - |
| createTime |  25.8s | 6.6s | -19s -186ms | -1.21 | -287.6% |
| generateTime |  20.8s | 19.5s | -1s -378ms | -0.21 | -7.1% |
| initTime |  19s | 16.4s | -2s -579ms | -0.41 | -15.7% |
| buildTime |  10.6s | 13.4s | 2.7s | **1.32** | 🔺20.6% |
| testBuildTime |  0ms | 0ms | 0ms | - | - |
| devPreviewResponsive |  7.2s | 7.6s | 390ms | -0.65 | 5.1% |
| devManagerResponsive |  4.7s | 5.1s | 382ms | 0.07 | 7.5% |
| devManagerHeaderVisible |  841ms | 1s | 250ms | **2.85** | 🔺22.9% |
| devManagerIndexVisible |  885ms | 1.1s | 241ms | **2.7** | 🔺21.4% |
| devStoryVisibleUncached |  1.3s | 1.3s | -15ms | 0.3 | -1.1% |
| devStoryVisible |  886ms | 1.1s | 242ms | **2.59** | 🔺21.5% |
| devAutodocsVisible |  773ms | 977ms | 204ms | **2.33** | 🔺20.9% |
| devMDXVisible |  658ms | 846ms | 188ms | 1.1 | 22.2% |
| buildManagerHeaderVisible |  705ms | 913ms | 208ms | **1.93** | 🔺22.8% |
| buildManagerIndexVisible |  713ms | 915ms | 202ms | **1.89** | 🔺22.1% |
| buildStoryVisible |  755ms | 990ms | 235ms | **2.31** | 🔺23.7% |
| buildAutodocsVisible |  607ms | 959ms | 352ms | **2.95** | 🔺36.7% |
| buildMDXVisible |  576ms | 893ms | 317ms | **3.44** | 🔺35.5% |

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
@ndelangen Your opinion is requested here.

**Comment by ndelangen** [comment]
It seems to be increasing the size of build storybook substantially @valentinpalkovic
Screenshot 2024-07-15 at 13 56 28

**Comment by tobiasdiez** [comment]
I had accidentally also disabled the minification for the manager build. The numbers should be better now. Could you please trigger a new benchmark?

**Comment by ndelangen** [comment]
It auto triggers, the number do not look too great, they are increasing pretty significantly upwards.

**Comment by tobiasdiez** [comment]
I tried to reproduce this locally by running `task.ts build --template react-vite/default-ts`. However, there doesn't seem to be any different in the manager output between this branch and `next`. In both cases, the `sb-manager` folder contains mostly un-minimized code.

I would also argue that the distributed size is not super important, depending on the use case. If it's just used as an internal dev tool, then I would gladly have a slightly larger storybook dist then having to uncrypt errors such as

```
De66xnrA.js:5 [nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'cdnURL')
    at e (BGOWv8qc.js:1:209)
    at b (BGOWv8qc.js:1:174)
    at mt (D8wL0etK.js:7:6272)
    at A (D8wL0etK.js:7:6458)
    at K (D8wL0etK.js:7:6492)
    at D8wL0etK.js:7:19552
    at r (De66xnrA.js:5:25148)
    at Object.runWithContext (CR8tLLMx.js:13:22037)
    at ze (De66xnrA.js:5:25187)
    at De66xnrA.js:5:23338
```

If the storybook is intended for a larger audience and has many views, one can activate code minimization of the bundler. The important point is that the end-user can decide which scenario he prefers.

**Comment by ndelangen** [comment]
@storybookjs/core what do we think?

Should we proceed with this, trade some perf for debug-ability?

**Comment by JReinhold** [comment]
Personally I'm very much in favor of this trade-off, and I know @IanVS has requested the same thing before.
After having worked with Svelte and SvelteKit which doesn't have any build step at all, I now see the light in how easy unminified code makes it to debug dependencies in `node_modules`, etc.

I don't know about you all, but _multiple times a week_ I dive into a package in `node_modules` to understand and temporarily modify the behavior - this would make that a lot easier.

I don't understand why the build sizes are different though, I'd expect a built Storybook to maintain it's current size.

**Comment by JReinhold** [comment]
Thanks for the investigation @tobiasdiez. We've discussed this in the team and we don't think the timing of this is great. We're currently putting a lot of effort into making Storybook smaller and faster across the board, including minimising dependencies, ESM-only experiments, etc.

Not minifying the package would counter-act that, and we don't think that's the right trade-off right now. I think we should look into this again when we're happy with our size-reduction efforts in a few month, to see how much the difference is by then.

**Comment by JReinhold** [comment]
> I honestly don't agree here. Your efforts in using esm treeshaking and minimizing dependencies would still have a huge impact, regardless of minimizing the code or not.

That's fair, and I can somewhat agree with that. But right now the priority is to get the size down, because it has continuously been a top complaint for years, that Storybook is "bloated". There are many ways to interpret and solve that, one of them being the package download size, that we want to focus on _first_.

Making it easier to debug Storybook is also a big win, but it only helps a tiny minority (including me) compared to the countless size complaints.

> If it would pass through the normal build pipeline, then it would also be minified before deploying.

Yeah if we did end up not shipping minified code, we'd definitely need to minify everything during build, and there's a performance penalty to doing that we'd need to investigate as well. Could be very little though.

**Pull request closed without merging**
