### PR TITLE
FIX the addon-background tool not appearing, or appearing only after a few navigations

### LINKED ISSUE #5416: @storybook/addon-backgrounds@next does not work
**Describe the bug**
I'm trying to use storybook@next. After I installed & set `@storybook/addon-background`, I faced two problems.

1. Background tool is not displayed occasionally.
2. When I tried to set a background (by clicking a color button), it emits the following error.
    ```
    TypeError: _this.tooltipRef.current.scheduleHide is not a function
    ```

**To Reproduce**
1. `git clone https://github.com/Ailrun/storybook-issue5416`
1. `npm i`
1. `npm start`
1. Check that there is no background tool just like the screenshot.
  image
1. (While running `npm start`) uncomment line 5-21 of `index.js`.
   (FYI, I already set the global parameters in `.storybook/config.js`)
1. Check that there is a background tool.
   (Weirdly...)
1. Open the web dev tool.
1. Click the background tool button.
1. Select `grey` (or any other colors).
1. See the error.

**Expected behavior**
Always display the tool, and do not emit any errors.

**Screenshots**
image

**System:**
 - OS: Manjaro (Kernel 4.18)
 - Device: Desktop
 - Browser: Firefox 64
 - Framework: React
 - Addons: Backgrounds
 - Version: 5.0.0-alpha.10

### PR DESCRIPTION
**Pull request by ndelangen**
fixes: https://github.com/storybooks/storybook/issues/5416

### CODE REVIEW

**Review by Ailrun — COMMENTED** [review]
Could you also fix Popout issue? Actually my issue includes two problems.

**Review by Ailrun — COMMENTED** [review]
FYI, addon-options (and maybe addon-notes) also have similar problem.

**Review by tmeasday — APPROVED** [review]
LGTM

Is `SET_STORIES` the only event we need to listen to?

**Comment by tmeasday** [comment]
@Ailrun I think the popout thing doesn't actually stop anything from happening and can be addressed separately

**Comment by Ailrun** [comment]
@tmeasday I meant, this PR closed my original issue so I thought it should fix all problems in the issue.
However, it's already merged and the issue is already closed, I opened another issue.
#5446.

**Comment by tmeasday** [comment]
Hey, yeah the issue was automatically closed due to the commit message. We'll close it when we release a new alpha and you can test it out.

**Comment by ndelangen** [comment]
@Ailrun I fixed it up better, Would love to have your help, fixing up the other 2 addons too?

**Pull request merged**
