### PR TITLE
React: Update babel dependencies to fix sandbox creation

### PR DESCRIPTION
**Pull request by ndelangen**

### CODE REVIEW

**Review by chakAs3 — APPROVED** [review]

**Comment by chakAs3** [comment]
thanks @ndelangen ❤️  i will merge it

**Comment by ndelangen** [comment]
Running into svelte check issues.

I have no idea how to resolve that.

**Comment by chakAs3** [comment]
i checking out your PR, i will give a shot with svelte

**Comment by ndelangen** [comment]
Thank you @chakAs3 that would be appreciated!

We can try to work out what got updated that makes it break, perhaps there's now multiple versions of a package that we had only 1 of before?

Or we can try to work out what's wrong and fix it.

**Comment by ndelangen** [comment]
Thank you for helping getting this over the line on your weekend @kasperpeulen @chakAs3  🙏

**Review by shilman — COMMENTED** [review]
@ndelangen this updates a bunch of user-facing code, so it should NOT be labeled as `build`, which is for internal build-only changes.

**Comment by ndelangen** [comment]
OK that's fair @shilman

**Pull request merged**
