### PR TITLE
Deps: upgrade ts-dedent to 2.0

### PR DESCRIPTION
**Pull request by tooppaaa**
Issue: none

## What I did
upgrade ts-dedent

## How to test
ci

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
LGTM

**Review by shilman — APPROVED** [review]
LGTM

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
When I upgraded this in chromatic-cli it seemed to have a bug, it didn't surface here?

**Comment by ndelangen** [comment]
Do we have a story somewhere that uses this?

**Comment by shilman** [comment]
Nope, didn't see anything here. I don't think `ts-dedent` is used in any stories, just in Storybook itself.

**Pull request merged**
