### PR TITLE
Args: Fix issues with string default values

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: #12071, #12635, #12767

Workaround/fix two issues that led to string default values being summarized as `'string'` rather than `"'string'"`, which lead to them being eval-ed as global objects.

Also remove fallback to using the string-ified value of defaults (if in doubt, fallback to `undefined` and let the true default come through!), and ensure we allow falsey default values.

Add some stories to highlight how we handle various possibilities

### CODE REVIEW

**Comment by tmeasday** [comment]
@shilman -- I'm not sure if these files are the best place to put these examples? WDYT? (the issue numbers make them a little hard to find, I wonder if a more explicitly named set of "kitchen-sink" examples would help -- maybe they exist already?)

Also do you think I should add one for a class-based component?

```js
React.createClass({

  getDefaultProps() {
    return { ... }
  }
}
```

**Review by shilman — CHANGES_REQUESTED** [review]
@tmeasday approved all of the `null` => `undefined` snapshots. i've left two snapshots unreviewed. can you take a look?

Also there are some broken tests based on your changes.

**Comment by shilman** [comment]
@tmeasday restructuring the stories as normal stories makes sense. maybe with a decorator that shows the actual arg values in the preview as well for debugging purposes?

it's been awhile but i think i structured things this way for two reasons:
1) incorporating examples from issues that don't actually need to be executable in our storybook
2) providing stories for them AND snapshot tests for them that show both the final output and the intermediate output of docgen, for debugging purposes

**Review by shilman — APPROVED** [review]
💯

**Comment by anicholls** [comment]
Cross posting for visibility. This PR does not fix https://github.com/storybookjs/storybook/issues/13608 and this issue needs to be reopened. See my [latest comment](https://github.com/storybookjs/storybook/issues/13608#issuecomment-833114607) on that issue for more details.

**Pull request merged**
