### PR TITLE
Better a11y

### PR DESCRIPTION
**Pull request by hipstersmoothie**
Issue: #4274

## What I did

When using info addon in `inline` mode with the a11y addon the page would jump to the bottom. This is because of axe. For it to work properly it needs to scroll to the bottom of the page. You can pass an option to scroll back but that would would look bad too.

* add id to story root in info addon
* in a11y addon check for info wrapper and use that to run axe if present
* just do axe on root element's children cause we don't care about the root's accessibility

if the content is long the page will still scroll to the bottom, but this mostly solves the problem. I have tested this in my own stories and it work for components in the viewport.

## How to test

Is this testable with Jest or Chromatic screenshots? No.
Does this need a new example in the kitchen sink apps? No
Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by igor-dv — COMMENTED** [review]
`story-root` id sounds me too generic to be in info addon. Also having `a11y` know about the inner implementation of `info` addon, makes them coupled... 

🤔 can we think of a more generic solution?

**Comment by hipstersmoothie** [comment]
> story-root id sounds me too generic to be in info addon.

how about `.info-story-root`? That would be more specific to the into addon.

> Also having a11y know about the inner implementation of info addon, makes them coupled...

It inherently has to be coupled. The problem with running axe on the whole page is that is has to scroll no matter what. It creates a pretty bad user experience. If the user is using `inline: true` the whole page is displayed. So the really does mean that the a11y addon needs to know the space in info where the story code actually lies.

> 🤔 can we think of a more generic solution?

The was my attempt at a more generic implementation. The id on the root of the story in the info addon doesn't callout the a11y addon in particular. This id could be the target of other plugins or even the user targeting it to style it. So in my opinion it already is pretty generic. I also believe it to be a nice feature that the info addon exposes where it renders the story code. 

I am open to suggestions but for me this accomplishes:

- few code changes
- low likelyhood for bugs
- generic

what other way would you have the info addon expose the story code div? @igor-dv

**Comment by ndelangen** [comment]
Long term I think this is the wrong approach, but for right now, I don't have strong objections really.

Having a preferred and fallback id selector for addon-a11y doesn't sound terrible, and adding an extra id to the html of addon-info is fine too.

Long term we want to move away from addon-info all together and move the documentation people are doing in addon-info to an addon that renders in the manager.

That way the story can render in isolation.

**Comment by ndelangen** [comment]
If you change the id to `info-story-root` this should be good IMHO. Do you agree @igor-dv ?

Would you like to help with the docs in the manager approach @hipstersmoothie ?

**Comment by igor-dv** [comment]
If it solves currently the problem I would say it's ok. What about other addons that may wrap a story, though?

**Review by ndelangen — APPROVED** [review]

**Comment by hipstersmoothie** [comment]
Nice!

**Pull request merged**
