### PR TITLE
Storyshots: Fix typings of "test"-method

### PR DESCRIPTION
**Pull request by nknapp**
Issue: #12361

## What I did

Adjust the typescript definition of storyshot's "test" method to better reflect reality.
It could be improved, but I am not sure which args are really passed all the time
(or maybe only depending on the framework).

## How to test

- Is this testable with Jest or Chromatic screenshots? no
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? maybe

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Thanks for digging into this! I'm not too familiar with this code, but it seems like more changes are needed, e.g.

https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/test-bodies.ts#L15-L20

Any chance you can do a more thorough audit of the code to tighten things up as part of this change?

**Comment by nknapp** [comment]
Let's see how it works now. I have done the following changes: 

* fix the TestMethodOptions based on the types found in test-bodies (use a union of all arg-types of all methods defined there).
* refactor the test-bodies to use the new StoryshotsTestMethod. I was a bit confused at first, about what the functions are doing, and I hope that my change makes it clear that they are actually returning test-methods.

**Comment by nknapp** [comment]
@shilman I have made some changes and they are ready for review. I am not sure if I have to do anything to change the state of this PR so that it gets your attention again. It is still in "Changes requested" state.

**Comment by shilman** [comment]
@nknapp i'm on it 😄

**Review by shilman — APPROVED** [review]
LGTM!

**Pull request merged**
