### PR TITLE
Args: Store global args in session storage

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: #10240

## What I did

Store globalArgs in session storage in the preview

## How to test

- Is this testable with Jest or Chromatic screenshots?

Yes there are tests, but it should be checked in a real SB too

### CODE REVIEW

**Comment by shilman** [comment]
@tmeasday ran into a strange case in `official-storybook`.

```
cd examples/official-storybook
yarn storybook
open http://localhost:9011/?path=/story/addons-toolbars--locale
```

1. Update the theme to dark & the locale to spanish
2. Refresh the page
3. Theme will be reset to light, locale will be set as spanish

The only difference is that the default value for theme is `null`. Any ideas?

**Comment by tmeasday** [comment]
Hmm interesting. I only checked the language selector! Will investigate.

**Comment by tmeasday** [comment]
> The only difference is that the default value for theme is null. 

Ok, this is the reason. Actually we have the same problem on HMR too!

**Comment by tmeasday** [comment]
Fixed. Can you take another look @shilman? Ta

**Review by shilman — APPROVED** [review]
Works great! ❤️

**Pull request merged**
