### PR TITLE
Angular: Fix handling of docsMode option in angular builder 

### PR DESCRIPTION
**Pull request by ndelangen**
Original PR: https://github.com/storybookjs/storybook/pull/18384

## What I did

The `docsMode` option when using the angular builder had no effect when I tried to build a project using Storybook *v6.5.6*. 
The [schema](https://github.com/storybookjs/storybook/blob/v6.5.6/app/angular/src/builders/build-storybook/schema.json#L37) for the builder documents the option with the name `docsMode` (matching other documentation), however the implementation tries to [forward a property with the name `docs`](https://github.com/storybookjs/storybook/blob/v6.5.6/app/angular/src/builders/build-storybook/index.ts#L61) and ignores the other one.

As the builder [also uses the property name `docsMode`](https://github.com/storybookjs/storybook/blob/v6.5.6/lib/core-common/src/types.ts#L222), no further mapping between the two names other than a simple renaming is done in this PR.
Note that the relevant schema part seems to be last updated in https://github.com/storybookjs/storybook/pull/15194, however the implementation was not updated back then.

### CODE REVIEW

**Comment by ndelangen** [comment]
@ssams would love a review on this. 🙏

**Comment by ndelangen** [comment]
@shilman I'll merge this if it goes green, since you approved the original PR

**Comment by ssams** [comment]
> @ssams would love a review on this. pray

looks good to me

**Review by ssams — APPROVED** [review]

**Comment by tmeasday** [comment]
The CLI flag is called `--docs` this documentation was wrong.

**Comment by ssams** [comment]
> [The CLI flag is called `--docs`](https://github.com/storybookjs/storybook/blob/e0228420db831fddb42d1eb6cd157db62fe0d3c1/docs/api/cli-options.md#L39-L40)-- this documentation was wrong.

well, the CLI flag may be called like this, but the Angular builder option certainly is not, Angular wouldn't event allow to run the build when validating the `angular.json` if using the other name in the current state:

https://github.com/storybookjs/storybook/blob/994a26df8f8e932577b97ce2dd9c8583a73d5eb8/code/frameworks/angular/src/builders/build-storybook/schema.json#L37-L41

I've been also using this patch locally applied to the stable v6 versions for months now, so it for sure works with these (e.g. also with currently latest https://github.com/storybookjs/storybook/releases/tag/v6.5.15). When I created the original PR it also fixed everything as intended for the upcoming v7, if it really doesn't anymore then something more in the Storybook builder internals must have changed.

**Pull request merged**
