### PR TITLE
Angular: Use system path when checking if asset is a directory

### PR DESCRIPTION
**Pull request by Marklb**
Issue: #11152

## What I did
Format path to system path before checking if the asset item is a directory.

On Windows 10, `fs.statSync` was called with a path like `/e/ex-app/src/assets`, which returned **false** by `isDirectory`, because `fs.statSync` could not find the path. `@angular-devkit/core` exports a function `getSystemPath` to convert a path to a system valid path.

### Example:
```json
// angular.json
{
	...,
	assets: [
		"src/favicon.ico",
		"src/assets"
	]
	...
}
```

When calling `normalizeAssetPatterns()` the result would be:
*Before this change*
```json
[
  { glob: 'favicon.ico', input: 'src', output: '' },
  { glob: 'assets', input: 'src', output: '' }
]
```
> The assets directory item gets normalized to the file object format.

*After this change*
```json
[
  { glob: 'favicon.ico', input: 'src', output: '' },
  { glob: '**/*', input: 'src/assets', output: 'assets' }
]
```
> The assets directory item gets normalized to the directory object format.

## How to test

1. On windows, add a file to the `src/assets` directory. Ex: `src/assets/logo.png`.
2. Run `start-storybook -p 6006`.
3. Try and use the file in a story or just try to access it directly with `http://localhost:6006/assets/logo.png`.

- Is this testable with Jest or Chromatic screenshots? *Potentially with a system specific test in Jest. I did not add one, since a lot of other tests fail on windows from paths not matching also. I can look into a place to add one if needed.*
- Does this need a new example in the kitchen sink apps? *No*
- Does this need an update to the documentation? *No*

### CODE REVIEW

**Comment by kroeder** [comment]
Hey, thanks for the PR

I just looked at https://github.com/angular/angular-cli/blob/3d86b18d7e67ff8d203bc7ec4491c8df00b33124/packages/angular_devkit/core/src/virtual-fs/path.ts#L315

Here are test cases for what it does
https://github.com/angular/angular-cli/blob/3d86b18d7e67ff8d203bc7ec4491c8df00b33124/packages/angular_devkit/core/src/virtual-fs/path_spec.ts

LGTM

**Review by kroeder — APPROVED** [review]

**Review by kroeder — CHANGES_REQUESTED** [review]
Ah, tests are failing

```
+ yarn jest --coverage -w 2 --reporters=/mnt/agent/work/storybook/pull/11472/temp-jest-teamcity/node_modules/jest-teamcity
info => Using angular project 'angular-cli' for configuring Storybook.
info => Using angular project 'storybook' for configuring Storybook.
info => Using angular project 'angular-cli' for configuring Storybook.
ERR! architect.build is not defined for project 'angular-cli'.
ERR! Could not find angular.json using /angular.json
ERR! Could not find angular.json using test-path/angular.json
info => Using angular project 'angular-cli' for configuring Storybook.
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
(node:380) DeprecationWarning: `configure()` is deprecated and will be removed in Storybook 7.0.
Please use the `stories` field of `main.js` to load stories.
Read more at https://github.com/storybookjs/storybook/MIGRATE.md#deprecated-configure
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when needed.
  Please remove the direct import of `core-js` or use `useBuiltIns: 'entry'` instead.
error Command failed with exit code 1.
Process exited with code 1
```

Can you try to fix them, please?

**Comment by Marklb** [comment]
@kroeder Do you know what test is failing? The snippet you pasted show 3 **ERR** log messages, but those are expected log messages. I am not sure what caused the command to fail though.

When I run tests on windows I get 29 failed tests throughout 7 test suites. Most of those are from things like expecting `/` instead of `\\` or expecting `\n` instead of `\r\n`.

I tried an Ubuntu vm this afternoon and got an error from a syntax error with `import` in `node_modules/riot/lib/riot.js`. I then took a break for a few hours and tried again by deleting my whole storybook directory and re-cloning this branch to try again, which gave me a different error with a vue story that I saw being fixed in a another PR. I waited another few hours for that fix to get merged into `next`, but went ahead and tried this branch from scratch again first and no error this time, all tests passed. So, I have no idea what is causing me to get different results each time I try, but I have re-cloned this branch multiple times trying to figure out how I made it fail tests earlier and they all pass every time now. My best guess is some newer version of a dependency was published or I somehow updated some global package that made it now pass.

I will take another look tomorrow and maybe setup another vm or another nodejs version, because the tests are all passing for me, other than the ones I mentioned above that are windows specific and not related to this change.

**Comment by shilman** [comment]
@kroeder @Marklb i don't know what's going on with the TeamCity tests. i only look at the CircleCI results typically, and we've marked those as required.

**Review by kroeder — APPROVED** [review]
@shilman if they're optional then I don't want to block this PR

**Pull request merged**
