### PR TITLE
Added `AntDesign` to Preset Gallery

### PR DESCRIPTION
**Pull request by Zaccc123**
Tested the `preset-ant-design` and prove to be working that tackle [this](https://github.com/storybookjs/presets/issues/35). 

Adding into the preset-gallery since is part of the storybook repo. Let me know if it should be moved into community presets if needed.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
This PR should be based on next. @Zaccc123 do you think you could rebase it?

**Comment by Zaccc123** [comment]
> @ndelangen all the docs on our site are based off `master` so we direct people to edit `master`. i can patch them over to `next` myself.

Yes, I actually click on the Edit. Sorry, my bad. Should have read the `Contribution.md`.

**Comment by shilman** [comment]
@Zaccc123 you didn't do anything wrong. i'm saying docs edits to `master` are fine. thanks for your contribution!!!

**Comment by Zaccc123** [comment]
Aww..I see, okay no problem! I loving storybook now ever since I use it haha. Will start to push in my company too. Thanks for the awesome work!

**Review by shilman — APPROVED** [review]
Awesome, great catch!! 💯

**Pull request merged**
