### PR TITLE
Angular: Fix runCompodoc for Windows, local Compodoc, and user specified tsconfig

### PR DESCRIPTION
**Pull request by Marklb**
## What I did

I got an error when the builder tried to call compodoc with `spawn` on Windows. In other apps I have fixed spawning child processes on Windows, by specifying the shell, and that seemed to fix my issue here also.
**Based on the docs https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options, I should be able to just pass `true`, instead of a specific shell. So, I will do some testing with that tonight and maybe be able to remove the OS check.**

I don't install compodoc globally, and wouldn't expect the global version to be used over the local version, so I set the `cwd` of the spawned shell to the workspace root and spawned `npx` instead of `compodoc`.

I have run into situations where a compodoc bug caused it to fail when parsing a file that wasn't even necessary for my stories. So, I started using a separate tsconfig to exclude those files. So, I added a check for "-p" in "compodocArgs" and only add the tsconfig from the angular build config if "-p" isn't provided.

> I don't know enough about the StackBlitz WebContainers to know if a browser being on Windows would affect that environment, but I wouldn't think so. This fix does fix my StackBlitz projects using the builders though. So, If a browser being on Windows has no effect on the WebContainers then this fixes Windows and StackBlitz WebContainers.

## How to test

- [x] Is this testable with Jest or Chromatic screenshots? The code functionality, yes. Testing that it works on a Windows OS, would depend on if the tests are run on a Windows OS. I am going to hopefully get this working without the OS specific code, but I still don't understand why I only get this problem on Windows, so I can't guarantee the test will stay valid without it running on Windows.
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@storybookjs/angular Could one of y'all take a look at this, please?

**Comment by ThibaudAV** [comment]
I will see for test on mac ;) 
but I don't have windows for dev (only for games 😁 )

**Comment by Marklb** [comment]
I switched the implementation to set `shell` to `true`, instead of specifying a specific shell. So, it is less OS specific now, but still seems to work on Windows.

**Comment by Marklb** [comment]
This same error happens on Stackblitz WebContainers, but I haven't tried this fix on there yet. I may be able to use a local Verdaccio repository with this branch published or maybe a script to patch the file in node_modules. I can try to test it on there later.

**Comment by shilman** [comment]
@Marklb can you please update from `next` and resolve the merge conflicts here? thanks! 🙏

**Comment by Marklb** [comment]
Fixed tests. Also, checked that it fixed builders running Compodoc in a StackBlitz WebContainer. I assume those containers are totally sandboxed to where they would not be inheriting this behavior from the OS, but I am not positive.

**Comment by Marklb** [comment]
Anyone able to take a look at this? On Windows and Stackblitz, at least, I have to disable Compodoc being run by the builder and add the script back to run it before the builder.

Should I force push a commit that doesn't have the `app/angular/src/server/framework-preset-angular-cli.ts` and `lib/core-server/src/build-dev.ts` changes? The linter run by the pre-commit hook does those two changes.

**Review by shilman — APPROVED** [review]
LGTM! Thanks @Marklb 🙏

**Comment by Darkmift** [comment]
Hi all,

I came across this issue as well today and yesterday,

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at module.exports (C:\...\node_modules\better-opn\node_modules\open\index.js:175:34) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```

Ill note I tried running the project in several Pc's and only some had this issue.

I would appreciate any help on solving this.

**Comment by sir-captainmorgan21** [comment]
@shilman is there a builder out there that runs compodoc as a part of the storybook build? Any docs on this?

**Pull request merged**
