### PR TITLE
feat: Add setStoriesUsingStoriesHash

### PR DESCRIPTION
**Pull request by ooihuiying**
Issue: #16996

## What I did
Add a new method: setStoriesUsingStoriesHash
## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by kylegach** [comment]
Thanks for your PR, @ooihuiying. This is a highly unique use case, so before making a code change, we'd like to exhaust other possibilities.

Have you tried accessing and calling the `setState` method used by `setStories`? Here: https://github.com/storybookjs/storybook/blob/main/lib/api/src/modules/stories.ts#L255.

**Comment by ooihuiying** [comment]
> Thanks for your PR, @ooihuiying. This is a highly unique use case, so before making a code change, we'd like to exhaust other possibilities.
> 
> Have you tried accessing and calling the `setState` method used by `setStories`? Here: https://github.com/storybookjs/storybook/blob/main/lib/api/src/modules/stories.ts#L255.

Hi @kylegach Thanks for your response.

I was unable to find the method that allows me to call the setState method used by setStories. Can you advise me on how i can do so?

**Comment by ooihuiying** [comment]
### Found workaround
I think i found a possible workaround. Would like to get your opinions on this workaround.

Since the method storybookApi.setStories(stories); takes in stories of `storiesRaw` type, but i only have stories in the form of `storiesHash` type, the workaround is to try to convert `storiesHash` into `Story[]`.

**Previously in my addon:**
var a = storybookState.storiesHash; // of type StoriesHash
// do something to process a. Eg, remove some stories.
storybookApi.setStories(stories); // Result in error because method setStories expects `storiesRaw` type.

**Now in my addon:**
var a = storybookState.storiesHash; // of type StoriesHash
// do something to process a. Eg, remove some stories.
const stories = Object.values(a).filter((hash) => hash.isLeaf).map(story => story as Story); // of type Story[]
 // @ts-ignore need to add this because technically, Story[] is not StoriesRaw type.
storybookApi.setStories(stories);

This now works and there isn't any error thrown. 

Summary of my step:
1. receive stories of type `storiesHash` from storybookState 
2. Convert stories from type `storiesHash` to type `Story[]`
3. Pass (2) in storybookApi.setStories() method provided by storybook api
4. Within storybook api, this method setStories converts the input (which it expects to be `storiesRaw` into `storiesHash`).

### Some thoughts
However, this feels like a weird way of doing things because
1.  i needed to dug around the storybook code to figure it out.
2. There is redundancy work in converting stories from `storiesRaw` into `storiesHash` when the user (me) already have stories in the form of `storiesHash` and could have passed it in as a param to setStories() method.
3. The storybook api does not provide the stories in the type of `storiesRaw` and this renders the method setStories() unusable by third party users (callers of the api) unless one use the workaround i mention above.

Therefore, there is value for the api to provide a setStories() method that expects `storiesHash` as an input type. Of course, i am not very familar with the storybook codebase and the maintainers know it best. Correct me if i misinterpreted something.

**Comment by ndelangen** [comment]
Hello @ooihuiying It's not exactly excited about the prospect of adding this new 'public' api...

When in fact I've wanted to merge the `refs` module and `stories` module in `lib/api` for some time.
For example we have this API: 
https://github.com/storybookjs/storybook/blob/f973c1abff74b5dbc1842965cf672efe1d5f4bc1/lib/api/src/modules/refs.ts#L248-L263
Which pretty much does exactly what you're asking for except it only applies to refs.

FYI refs are composed storybooks: https://storybook.js.org/docs/react/workflows/storybook-composition

I looked at if we're exposing the full setState method, but we're not. And I'm also not really keen on opening that can...

**Comment by ooihuiying** [comment]
Hi @ndelangen Thanks for your responses.

I agree that it might not be a good idea to expose the full setState method. It might give users access to more power than they need.

I will keep my PR open and the team can decide whether they want to merge it or close it?

**Comment by MichaelArestad** [comment]
Hey @shilman, when you get back, let's discuss this with @ndelangen?

**Comment by ndelangen** [comment]
@shilman I've kinda come around to this, and I think this is a work-able solution for the mean time.

We'll merge refs and stories state at some point, I think.

**Review by ndelangen — APPROVED** [review]

**Pull request closed without merging**
