### PR TITLE
TypeScript definitions on DefinitelyTyped

### PR DESCRIPTION
**Pull request by mfal**
I've added type definitions for this package to [DefinitelyTyped](http://definitelytyped.org). Apparently I could not start a PR, because it would conflict with the typings you've already included here.

This one removes the typings as a prerequisite for starting a PR for this branch: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...mfal:kadira-storybook

### CODE REVIEW

**Comment by apexskier** [comment]
Why use DefinitelyTyped over specifying types in the package.json (as is currently done)? I'm not necessarily arguing against this change, but I'm curious about your reasoning. Including types in a package.json makes it so devs don't have to specify an additional dependency to fetch them.

**Comment by jtmthf** [comment]
I agree with @apexskier. Having typings in the repository means that they're versioned alongside with the source, guaranteeing that the typings are consistent with the source. Ideally I would rather not use Definitely Typed and have all typings defined in the package, but I don't see that happening anytime soon.

**Comment by mfal** [comment]
From a technically point of view you both are right: Keeping the typings along with the source itself is the preferred solution. This is usually the case, if the source is written in TypeScript.

But if it is not, you have to ask yourself: **Is it OK for contributors to burden them with typings?** Because when you @apexskier say "typings will be guaranteed to be consistent", they have to!

To not burden contributors with concepts of a different programming language, is the main reason for this approach.

BTW: Typings from DefinitelyTyped are also on NPM (`npm i @types/kadira-storybook`), so you can keep up the deps with your `package.json` very easily.

**Comment by mfal** [comment]
Hey @jtmthf, @apexskier!

What do you think about it now?

**Comment by apexskier** [comment]
I'm still not convinced that there's a benefit to separating typings from the source.

If the interface is changed within the source, typings need to be updated. (Assuming there's "official" typescript support, which I think there is for storybook, considering that typings already exist.)

I consider it a lesser burden to update in a single location than having to commit code in a second place (two PRs, two discussions of implementation, two build processes). Having typings in a second place is less explicit, so contributors are less likely to know they're going to break things. It also makes it more likely that bugs will surface later, which will make tracking the breaking commit more difficult.

I recognize that it's an additional burden to contributors who aren't familiar with typescript. Luckily, since this is an open source community people can always ask for help!

**Comment by mfal** [comment]
When you keep up this strategy, I would at least recommend having a test along with the typings, that does a simple compile check.

> The tests are not runnable in the TDD way but contain code that should compile with no errors, usually taken from the documentation samples of the library. - http://definitelytyped.org/guides/contributing.html

[You can find one for `uuid` here.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4869992bc079b88280b9ff91213528904109e8ae/uuid/uuid-tests.ts)

**Pull request closed without merging**
