### PR TITLE
Core: Add global box-sizing setting. Fixes #10207

### LINKED ISSUE #10207: [components] Preview Toolbar has scrollbar
**Describe the bug**
The DocsPage Preview component Toolbar has a scrollbar when the IconButton's `box-sizing` is not reset to `border-box` somewhere else.

[Toolbar has height 40](https://github.com/storybookjs/storybook/blob/47a932d850a0460f101c69a9c4d09e98bb483a4a/lib/components/src/blocks/Preview.tsx#L132), and [IconButton has height: 40 + 3 border](https://github.com/storybookjs/storybook/blob/next/lib/components/src/bar/button.tsx#L80-L88)

**Screenshots**
preview-header

### PR DESCRIPTION
**Pull request by matheo**
Issue: #10207

@shilman any other way to set this global style? or this is fine?

### CODE REVIEW

**Comment by shilman** [comment]
@matheo i think this is a @ndelangen question :)

**Comment by ndelangen** [comment]
I think this might be a better place for it.

https://github.com/storybookjs/storybook/blob/c5f520814a128eac54ecbe227c5a304f2eeeb783/lib/theming/src/global.ts#L100-L113

I foresee a problem with this though:

We render storybook UI components in 2 places: In the manager and in addon-docs.

This change will be problematic for the latter.

If our UI components start expecting to be rendered with these global styles, (which will potentially not be the case in addon-docs) this could cause problems for us.

Can we fix https://github.com/storybookjs/storybook/issues/10207 in another more specific method?

**Comment by matheo** [comment]
@ndelangen a global reset seems to be better. See #11071

**Comment by shilman** [comment]
@matheo @ndelangen any chance we can push this forward in the next few days?

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
