### PR TITLE
Removed the tabindex of 0 from the tab content container.

### PR DESCRIPTION
**Pull request by patricklafrance**
A tabindex of 0 has been added to the container of the tab content.

Because of this, you get to do an extra tab when navigation through a docs page. I don't see the point of tabbing on the tabs content, there isn't any possible action to do.

Furthermore, we now have an "outline" when we click on an props table expandable value.

tabs_focus

## What I did

- Removed the tabindex from the tab content

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
@patricklafrance So it looks like @Hypnosphi recently added the tabindex to fix an a11y violation. Can you two figure out the best path forward?

**Comment by Hypnosphi** [comment]
We need for case when there are enough content in the tab to make it scrollable, but at the same time there are no focusable elements in the tab. That way we enable scrolling the tab using keyboard only.

Can we somehow detect this case and set tabIndex selectively?

**Comment by patricklafrance** [comment]
Whats going on with this PR? It still feels weird ;)

**Comment by shilman** [comment]
Sorry. @patricklafrance @Hypnosphi can you two work this out?

**Comment by Hypnosphi** [comment]
@ndelangen wanted to take a look

**Comment by ndelangen** [comment]
Sorry for not reporting back, I didn't find an easy way to detect "if things that can be focussed within children". So conditionally adding tabindex=0 seems pretty hard.

I'm don't have a solution in mind, what do you propose @Hypnosphi @patricklafrance ?

**Comment by patricklafrance** [comment]
My proposition remain the same, remove the tabindex from the tabs component.

**Comment by ndelangen** [comment]
So if we really really want to keep the behaviour that the scroll-area should get tabindex when (and only when) there elements within it cannot receive focus we could do something like this:

```js
import React, { useRef, useEffect, useState } from "react";

const selector = `
a[href]:not([tabindex='-1']),
area[href]:not([tabindex='-1']),
input:not([disabled]):not([tabindex='-1']),
select:not([disabled]):not([tabindex='-1']),
textarea:not([disabled]):not([tabindex='-1']),
button:not([disabled]):not([tabindex='-1']),
iframe:not([tabindex='-1']),
[tabindex]:not([tabindex='-1']),
[contentEditable=true]:not([tabindex='-1'])`;

const ScrollArea = () => {
  const ref = useRef(null);
  const [hasFocussableChildren, setFocussableChildren] = useState(true);

  useEffect(() => {
    if (ref && ref.current) {
      const list = [...ref.current.querySelectorAll(selector)];

      if (hasFocussableChildren !== !!list.length) {
        setFocussableChildren(!!list.length);
      }
    }
  });

  const tabIndexProp = hasFocussableChildren ? { tabindex: 0 } : {};

  return (
    <div ref={ref} {...tabIndexProp}>
      <button>Focus-able</button>
    </div>
  );
};
```

**Comment by Hypnosphi** [comment]
@ndelangen you can also use ResizeObserver (with [`react-measure`](https://github.com/souporserious/react-measure) or sirectly) to detect scrollability (`scrollHeight > clientHeight`)

**Comment by ndelangen** [comment]
@Hypnosphi This proposal code would be an extension to the existing ScrollArea component in lib/components.

Is my proposal code good as-is? does it cover all use-cases? I'm not sure.

**Comment by Hypnosphi** [comment]
@ndelangen it adds a focusable even if the area doesn't have enough content to be scrollable. It can be fixed using ResizeObserver, see my comment above

**Comment by ndelangen** [comment]
Right that makes sense, forgot about that.

**Comment by darleendenno** [comment]
@patricklafrance @Hypnosphi @ndelangen sounds like we have consensus? Will this work be part of this PR?

**Comment by ndelangen** [comment]
Hi Deen,

I think we knew what to do, at the time. But it felt like a lot of work and added complexity.
Are you thinking about taking it ok?

**Comment by darleendenno** [comment]
> Hi Deen,
> 
> I think we knew what to do, at the time. But it felt like a lot of work and added complexity.
> Are you thinking about taking it ok?

Not currently -- though I do think this would be a great improvement. Perhaps let's write an issue linking to this discussion, and allow someone to pick it up when they have availability?

**Pull request closed without merging**
