### PR TITLE
docs: reference the decorators in the introduction page

### PR DESCRIPTION
**Pull request by profanis**
Issue: N/A

## What I did
The decorators apart from the actual landing page, have also a reference on the introduction page which should also have an Angular example.

I included the `decorators` example in the [writing-stories/introduction](https://storybook.js.org/docs/angular/writing-stories/introduction) page.

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
LGTM!

**Comment by yannbf** [comment]
Thanks for your contributions @profanis!

Would you be so kind to add a snippet for the [setup section](https://storybook.js.org/docs/angular/get-started/setup)? That'd be equivalent to `react/your-component.ts.mdx`. Could be in another PR of course, if you feel like doing it!

**Comment by jonniebigodes** [comment]
@yannbf the setup snippet is being covered in another pull request see #12682

**Comment by yannbf** [comment]
> @yannbf the setup snippet is being covered in another pull request see #12682

Great! The disregard my previous comment :D

**Comment by jonniebigodes** [comment]
@yannbf no worries. the pull request wasn't merged because i add to shift my attention to other items. If @shilman doesn't merge it by monday i'll do it. 

@profanis i can't thank you enough for the help you've been providing with the angular snippets. We're extremely grateful for the time and effort you've been putting into adding the angular snippets into the documentation.

**Review by shilman — APPROVED** [review]
💯

**Pull request merged**
