### PR TITLE
Automention for project maintainers

### PR DESCRIPTION
**Pull request by shilman**
Issue: #6223 

## What I did

Add `Automention` github action, configure with an initial set of project maintainers

When an issue or PR is labeled with a specific project, the maintainers of that project are "auto-mentioned" in a comment via a github, triggering a notification.

I added this based on discussion in #6223, and this PR is meant to further the discussion. I also wrote the `Automention` github action, and it's easy to modify based on feedback here. I've been mentioning people manually already using `cc @username` as I go through issues/PRs, especially @benoitdion on `app: react-native` and @backbone87 on `app: vue`

Still to do:
- [ ] Fill out the different project areas @shilman @ndelangen etc.
- [ ] Update storybook.js.org to highlight the different project maintainers @domyen @shilman 

## How to test

Edit the labels of this PR. For example, if you add the label of `addon: a11y` it will auto-mention @CodeByAlex @jsomsanith @Armanio, who have been active contributors to that addon. The action takes just a few seconds to run, but the entire process including spinning up a docker instance takes a minute or two.

### CODE REVIEW

**Comment by Armanio** [comment]
I'm here. :smiley:

**Review by ndelangen — APPROVED** [review]

**Comment by kroeder** [comment]
@shilman why did it tag me while having the tags maintenance and a11y? Is the maintenance tag also a trigger for a set of people?

**Comment by shilman** [comment]
@kroeder IMHO maintenance is more like a category like bug or feature.  These are more about project areas. But I suppose we can use them however we want!

It added you to the list when I added the typescript label. It updates its existing comment if there is one, rather than creating a new one. Lmk if you think this is a bad idea

**Comment by Keraito** [comment]
This sounds great, thanks for still including me! I really haven't had the time to manage SB related stuff since starting my first job 😭 This looks super helpful, awesome idea! 💪

**Review by Keraito — APPROVED** [review]

**Review by gaetanmaisse — APPROVED** [review]

**Comment by gaetanmaisse** [comment]
@shilman I'm honored you included me on `typescript` tag 😃!

**Comment by shilman** [comment]
@tmeasday suggested that we use Github's concept of teams for this. Merging this and will implement in a separate PR

**Pull request merged**
