### PR TITLE
Dependency: Remove node-fetch

### LINKED ISSUE #27156: [Bug]: DeprecationWarning: The `punycode` module is deprecated
### Describe the bug

Source: https://github.com/storybookjs/storybook/issues/27027#issuecomment-2094905490

Looks like you should also update your node-fetch version used in @storybook/core-common to load the transitive dep whatwg-url >= [9.0.0](https://github.com/jsdom/whatwg-url/blob/v9.0.0/src/url-state-machine.js) and avoid the punycode deprecation warning.

```
morgan@machine:~/code/tts-react (develop)$ node --trace-deprecation ./node_modules/.bin/storybook info

Storybook Environment Info:
(node:50775) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:104:7)
    at Module._load (node:internal/modules/cjs/loader:1075:17)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/morgan/code/tts-react/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)

  System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1335U
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.1.0 - ~/n/bin/node
    npm: 10.7.0 - ~/n/bin/npm <----- active
  Browsers:
    Chrome: 124.0.6367.118

morgan@machine:~/code/tts-react (develop)$ npm ls node-fetch
tts-react-monorepo@0.0.0 /home/morgan/code/tts-react
└─┬ story@1.0.0 -> ./packages/story
  └─┬ @storybook/react-webpack5@8.0.10
    └─┬ @storybook/builder-webpack5@8.0.10
      └─┬ @storybook/core-common@8.0.10
        └── node-fetch@2.7.0

morgan@machine:~/code/tts-react (develop)$ npm ls whatwg-url
tts-react-monorepo@0.0.0 /home/morgan/code/tts-react
├─┬ jest-environment-jsdom@29.5.0
│ └─┬ jsdom@20.0.3
│   ├─┬ data-urls@3.0.2
│   │ └── whatwg-url@11.0.0 deduped
│   └── whatwg-url@11.0.0
└─┬ story@1.0.0 -> ./packages/story
  └─┬ @storybook/react-webpack5@8.0.10
    └─┬ @storybook/builder-webpack5@8.0.10
      └─┬ @storybook/core-common@8.0.10
        └─┬ node-fetch@2.7.0
          └── whatwg-url@5.0.0
          ```

### To Reproduce

-

### System

```bash
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yk-kd**
Closes #27156

## What I did
Updated node-fetch package from v2 to v3.
node-fetch v3 removes the whatwg-url dependency, so no more issue warnings.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
Good call! Let’s try it!

**Comment by yk-kd** [comment]
@valentinpalkovic 
I finished.
Lock files still appeared to have node-fetch dependencies.
I didn't look at it in detail, but it looked like a dependency on CI, such as octokit or danger.

**Comment by yk-kd** [comment]
@valentinpalkovic 
Node-fetch under code seems to have been removed in #27039
I've changed it so that it is removed from scripts as well, just in case.
Should I close the PR now that the original purpose has been achieved?

**Comment by valentinpalkovic** [comment]
Hi @yk-kd. No, don’t close it. The core package consolidation moved nearly all Storybook packages to code/core. I guess node/fetch is a dependency there.

**Comment by yk-kd** [comment]
Hi @valentinpalkovic,

There is no node-fetch dependency in package.json when grepping under code.
There is one in yarn.lock, but it is a dependency of danger or octokit.

**Comment by valentinpalkovic** [comment]
Interesting! @ndelangen have you removed node-fetch as part of CPC?

**Review by valentinpalkovic — APPROVED** [review]

**Pull request merged**
