### PR TITLE
Fix: vite dev and yarn pnp + vite by unreverting and adding lodash files to optimizeDeps.include

### LINKED ISSUE #21523: [Bug]: Doctrine does not provide an export named 'default' in v7.0.0-rc.0
### Describe the bug

The requested module '/.yarn/cache/doctrine-npm-3.0.0-c6f1615f04-fd7673ca77.zip/node_modules/doctrine/lib/doctrine.js?v=4047beba' does not provide an export named 'default'

### To Reproduce

Run yarn storybook
https://github.com/bryanjtc/storybook-7-vite-test

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
```

### Additional context

The repo uses yarn pnp.

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/21523#issuecomment-1463112834 #21548 

Related: https://github.com/storybookjs/storybook/pull/21528, https://github.com/storybookjs/storybook/pull/20443, https://github.com/storybookjs/storybook/issues/21527

## What I did

I added the wrapForPnP code back and added the extra optimizeDeps.include entries

## How to test

`yarn start` should work

### CODE REVIEW

**Comment by IanVS** [comment]
I think the core issue here is that vite does not consider absolute paths to be dependencies.  So it does not convert them from commonjs to esm.

I worry that the yarn pnp changes here of turning many things into absolute paths will break other dependencies as well.  Ideally I would like to remove most or all of the `optimizeDeps.include`, and not make the array bigger.  

I'll try to look into it more soon, but wanted to say that I'm concerned about this change.

**Comment by ndelangen** [comment]
@IanVS well, absolute paths are needed to have pnp support fully.. What should we do here?

As-is.. we have a regression where the react-vite framework does not support pnp.

This PR fixes that.

**Comment by IanVS** [comment]
>absolute paths are needed to have pnp support fully

Honestly I'm really surprised by that.  It feels like a workaround, and I would have expected that yarn pnp could handle import/require calls from the correct scopes correctly without having to resort to absolute paths so often.  Is this because of the architectural design of Storybook, whereby we pass strings around from one package to another to be imported?  @arcanis have you encountered other similar projects that have added yarn pnp support (particularly complex projects like ours)?  What ways have they approached it?  Is it expected that we should have to resolve node_module imports into absolute paths?  If so, do you know what those projects have done to support vite, which will not treat absolute paths as dependencies?  Any guidance you can give would be much appreciated here.

**Comment by ndelangen** [comment]
Yes that's the reason @IanVS

**Comment by ndelangen** [comment]
I am also not sure how the lodash issues popped up after this change.

**Comment by IanVS** [comment]
I agree, but what confuses me is why Vite isn't handling it automatically like every other dep.  I'll go ahead and approve so we can move forward, but when I have some time I want to figure out what's really going on, and maybe we can talk about ways that we can try to avoid absolute imports in the future.

**Review by IanVS — APPROVED** [review]
I'm confused why `wrapForPnP` needs to be defined locally in each file, but I guess it has something to do with the monkeypatching that pnp.cjs is doing to `require`.  

I do like that this gives us a clear string to grep for if we ever find another way to handle these.

**Comment by ndelangen** [comment]
The `require.resolve` MUST happen in the file from which the require should be relative to.

the wrapForPnP must be in each file, because it calls `require.resolve`, and for convenience, it also adds and removes `/package.json` to the path.

**Pull request merged**
