### PR TITLE
change NPM organisation from kadira to storybook in code

### PR DESCRIPTION
**Pull request by aaronmcadam**
Issue: #773 

## Blocked by

#1004, ~~#1008~~

## What I did

Created the codemod

## How to test

Run unit tests

## TODO

- [x] Confirm new package names
- [x] remove `storybook-` prefixes
- [x] `getstorybook/generators`
- [x] `LICENSE`s
- [x] `CODE_OF_CONDUCT`s
- [x] `README` badge URLs
- [x] `react-storybook/src/server/track_usage.js`

### New Package directories and names

| Current Repo Path               | Suggested Repo Path      | Publish Name                  |
|---------------------------------|--------------------------|-------------------------------|
| packages/getstorybook           | packages/cli             | @storybook/cli                |
| packages/react-storybook        | packages/react       | @storybook/react          |
| packages/react-native-storybook | packages/react-native | @storybook/react-native    |
| packages/storybook-ui           | packages/ui              | @storybook/ui                 |
| packages/channels               |                          | @storybook/channels           |
| packages/channel-websocket      | packages/channels-websocket                         | @storybook/channels-websocket  |
| packages/addons                 |                          | @storybook/addons             |
| packages/addon-actions          | packages/addons-actions                         | @storybook/addons-actions      |
| packages/decorator-centered     | packages/decorators-centered                         | @storybook/decorators-centered |
| packages/storyshots             |                          | @storybook/storyshots         |

### CODE REVIEW

**Comment by aaronmcadam** [comment]
@ndelangen Can we confirm what we want the published name these packages to be? Should we drop all `storybook-` prefixes?

**Review by ndelangen — COMMENTED** [review]
Do we need to add the codemod as a package? I'd think not.

**Comment by ndelangen** [comment]
So I've been trying this, but it would appear that in order to get this to work, all packages must at least have been published once on npm, in order for lerna to be able to bootstrap.

**Comment by aaronmcadam** [comment]
It would be useful for users to migrateOn 8 May 2017 4:22 pm, Norbert de Langen <notifications@github.com> wrote:@ndelangen commented on this pull request.

Do we need to add the codemod as a package? I'd think not.

**Comment by aaronmcadam** [comment]
Lerna doesn't need the packages to be published to bootstrap. Tests will fail though where they reference the new package names.

**Comment by ndelangen** [comment]
> Lerna doesn't need the packages to be published to bootstrap
That's what I'm hearing from lerna maintainers, however check the travis logs, bootstrap does fail...

> It would be useful for users to migrate
Right, I'd move them somewhere else though, maybe `./migrations`. I feel like we should reserve `./packages/` for functional parts of storybook.

**Comment by ndelangen** [comment]
I'd personally like to remove the `storybook-` prefix, what you you think?

**Comment by aaronmcadam** [comment]
@ndelangen I think we should only have `storybook` mentioned in the name for the main package.

So the directory structure would go from this:

```bash
addon-actions
addon-comments
addon-graphql
addon-info
addon-knobs
addon-notes
addon-options
addons
channel
channel-postmessage
channel-websocket
codemod
decorator-centered
getstorybook
react-native-storybook
react-storybook
storybook-ui
storyshots
```

to this:

```bash
addon-actions
addon-comments
addon-graphql
addon-info
addon-knobs
addon-notes
addon-options
addons
channel
channel-postmessage
channel-websocket
codemod
decorator-centered
getstorybook
native-storybook
storybook
ui
storyshots
```

**Comment by aaronmcadam** [comment]
@ndelangen regarding the codemod, I understand where you're coming from regarding keeping `packages` for functionality.

If we move it elsewhere, we'll have to manually manage publishing it.

We might be able to make it work by setting the [`packages` config in `lerna.json](https://github.com/lerna/lerna/#lernajson)`.

**Comment by UsulPro** [comment]
Hi!
Isn't `storybook-ui` more comfortable than `ui` as an important part of the core?

**Comment by ndelangen** [comment]
> @ndelangen regarding the codemod, I understand where you're coming from regarding keeping `packages` for functionality.
> 
> If we move it elsewhere, we'll have to manually manage publishing it.
> 
> We might be able to make it work by setting the [`packages` config in `lerna.json`](https://github.com/lerna/lerna/#lernajson) to take an extra `tools` directory.

Good suggestion! I'm already using the `packages` config. It's real easy to add a `tools` folder.

**Comment by ndelangen** [comment]
> Isn't `storybook-ui` more comfortable than `ui` as an important part of the core?

Do you prefer `@storybook/ui` or `@storybook/storybook-ui`?

**Comment by theinterned** [comment]
I agree that `@storybook/native-storybook` is more confusing then `@storybook/react-native-storybook` ... the name of the project is `react-native` so arbitrarily cutting it in half seems odd.

**Comment by aaronmcadam** [comment]
I was trying to aim for parity between the directory names on disk and the package names on `npm`. So  `@kadira/react-storybook` has gone to `@storybooks/storybook`. I do agree that the name for the native project is awkward.

**Comment by UsulPro** [comment]
don't we need to consider once more the @tmeasday's idea:

> `@storybook/react`
> `@storybook/react-native`

I start to like it. Looks like we open for other frameworks/applications 😄 ?

> Do you prefer @storybook/ui or @storybook/storybook-ui?
I

**Comment by tmeasday** [comment]
I'd vote for `@storybook/ui` over `@storybook/storybook-ui`.

**Comment by aaronmcadam** [comment]
Ok, so the latest consensus is:

```
addon-actions
addon-comments
addon-graphql
addon-info
addon-knobs
addon-notes
addon-options
addons
channel
channel-postmessage
channel-websocket
codemod
decorator-centered
getstorybook
react-native
react
(storybook-ui|ui)
storyshots
```

**Comment by ndelangen** [comment]
Sorry to through my 2ct in the mix again... Here's my suggestion:

| Current Repo Path               | Suggested Repo Path      | Publish Name                  |
|---------------------------------|--------------------------|-------------------------------|
| packages/getstorybook           | packages/cli             | @storybook/cli                |
| packages/react-storybook        | packages/app-react       | @storybook/app-react          |
| packages/react-native-storybook | packages/app-reactnative | @storybook/app-reactnative    |
| packages/storybook-ui           | packages/ui              | @storybook/ui                 |
| packages/channels               |                          | @storybook/channels           |
| packages/channel-websocket      |                          | @storybook/channel-websocket  |
| packages/addons                 |                          | @storybook/addons             |
| packages/addon-actions          |                          | @storybook/addon-actions      |
| packages/decorator-centered     |                          | @storybook/decorator-centered |
| packages/storyshots             |                          | @storybook/storyshots         |

Previously I suggested `core` but here I'm suggesting `app` as an indicator it's the main app. And yes this naming scheme clearly implies that we're open to more UI frameworks.

Main reason why I'd personally **not** vote for a package called `@storybook/react` is because it sounds like a react fork.

**Comment by ndelangen** [comment]
I'm also OK with moving addons into their own folder, just like we keep examples separated (but still bootstrapped with lerna , but I'm not sure that's really adding any benefits.

**Comment by aaronmcadam** [comment]
To all those watching this PR, I've added the name changes to the PR description.

**Comment by UsulPro** [comment]
Okey
but why `@storybook/addons-actions` and `@storybook/decorators-centered` ? (originally it was without `s`)

And wouldn't it better to rename `@storybook/decorators-centered` to `@storybook/addon-centered` since decorator is just a kind of addon?

**Comment by aaronmcadam** [comment]
@UsulPro I think we should have the same prefix for these namespaced packages so that it's easier to see that packages are related visually.

I don't mind moving `decorators-centered` into the `addons` namespace.

**Comment by UsulPro** [comment]
How do you like the idea (if it still possible) to move all addons into a separate folder `storybook/addons` and remove `addon` from folder name:
 `storybook/packages/addon-actions` ->  `storybook/addons/actions`

**Pull request merged**
