### PR TITLE
upgrade yarn

### PR DESCRIPTION
**Pull request by ndelangen**
Issue:
The sandboxes are installing the latest version of yarn, whereas we use something slightly older

## What I did

upgrade to latest version of yarn,
de-duplicate the yarn installation

### CODE REVIEW

**Comment by ndelangen** [comment]
@kasperpeulen this check issue seems like something you might be able to assist with?

Would you be able to have a look at what's wrong?

At a first glance, it looks like vue JSX types get confused with vue JSX types.

**Comment by ndelangen** [comment]
@kasperpeulen 
Screenshot 2022-11-30 at 11 56 36

**Comment by kasperpeulen** [comment]
Checking it out

**Comment by kasperpeulen** [comment]
@ndelangen I fixed the issue by making sure module augmentation is a bit more explicit throughout the monorepo, and only using the global types of jest by default.

**Comment by ndelangen** [comment]
@kasperpeulen Is this new?:

```
ERR! You may need an additional loader to handle the result of these loaders.
ERR! |     layout: 'fullscreen'
ERR! |   }
ERR! > } satisfies Meta<typeof Page>);
ERR! | export default meta;
ERR! | export var LoggedOut = {};
ERR! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by kasperpeulen** [comment]
dkasperpeulen Yes, it is new, investigating, but having a hard time, see discord. Maybe I should just delete the next TS 4.9 templates for now.

**Comment by ndelangen** [comment]
@shilman  @kasperpeulen self merging

**Pull request merged**
