### PR TITLE
Move webpack to peer dependencies

### PR DESCRIPTION
**Pull request by sheerun**
This makes it possible to use react-storybook with webpack 2.

For now storybook will pass configuration from `.storybook/webpack.config.js` to webpack 1 even parent project specified webpack 2 as dependency. This makes storybook to re-use webpack version from parent project instead of introducing its own.

It really works, I've tested it on my own project.

### CODE REVIEW

**Comment by Zalastax** [comment]
The changes work for me as well. I just had to provide my own webpack config: https://github.com/Zalastax/openschedule/blob/master/.storybook/webpack.config.js

**Comment by arunoda** [comment]
We can't make this a peer dep because, webpack doesn't installed by default with CRA.
But after the webpack 2 official release, we should try to do something.

**Comment by Zalastax** [comment]
Can't you just change the installation instructions/getstorybook? I've seen a lot of libraries do that.

**Comment by sheerun** [comment]
If anyone wants these changes right now, you can try `@sheerun/storybook`

@arunoda Then maybe change require call to discover webpack dependency of parent package, if it exists?

**Comment by arunoda** [comment]
@Zalastax that's also a good idea to do that on the `getstorybook` side.
So, we could try to add webpack as an dependency if there's not.

**Comment by jquense** [comment]
can we at least increase the range on the webpack direct dep? at least then deduping would allow this to work

**Comment by arunoda** [comment]
@jquense yep. That's something we could do now.
Could you send me a PR?

**Comment by cogell** [comment]
just a heads up:
- you're gunna need to drop: https://github.com/storybooks/react-storybook/blob/master/src/server/config/webpack.config.js#L58

- and drop the empty quote from this: https://github.com/storybooks/react-storybook/blob/master/src/server/config/webpack.config.js#L55

**Comment by ndelangen** [comment]
Thank you all, I hope we can do this fairly soon. I resolved the merge conflict, but this needs a very thorough review.

**Comment by ndelangen** [comment]
Very similar to this https://github.com/storybooks/react-storybook/pull/637

This is now also under consideration:
https://github.com/storybooks/mono/pull/4

I need to do a great deal of testing on this.

**Comment by ndelangen** [comment]
So don't feel bad or like this isn't going to happen, because it's likely going to happen SOON!

I'm closing these PR because they will not be merged, because I'm doing them all in 1 swoop.

**Pull request closed without merging**
