### PR TITLE
Add angular 8 and 9 cli fixtures

### PR DESCRIPTION
**Pull request by kroeder**
Issue:

## What I did

Add cli fixtures for angular 8 and 9 in preparation for the angular 9 release (currently 9.0.0-rc.2)

### CODE REVIEW

**Comment by kroeder** [comment]
Is not blocked, just have to finish it

**Comment by kroeder** [comment]
I honestly have no idea why `styles.scss` causes errors in CI. It works as expected locally 😞

**Comment by ndelangen** [comment]
Compare node versions?

**Comment by kroeder** [comment]
I tried to switch to `css` from `scss` to see if this works. Now `CLI tests / CLI Fixtures` fails with a JS stack trace. @ndelangen can you take a look at the stack trace?

Node-version seems to be fine btw.

**Comment by ndelangen** [comment]
`JavaScript heap out of memory` 😢

**Comment by ndelangen** [comment]
Are we trying to get this in 5.3 or is this going to be in 6.0.0?

**Comment by kroeder** [comment]
@ndelangen  @shilman updating angular 9 rc and adding one missing file finally fixed the CI issue

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
