### PR TITLE
Ignore nvmrc

### PR DESCRIPTION
**Pull request by Hypnosphi**
Some of the tests fail in node < 8, so I reflected the target node version in `.nvmrc` file.

It would be also nice to reflect this fact in docs, but unfortunately I failed to pick the right place and wording =(

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]
I'd rather not add more dotfiles in the root.

Are there alternative to this that do not add yet another file in the root?

If not and this is really the best way, go ahead and merge!

**Comment by Hypnosphi** [comment]
The alternative is simple: I gitignore the file, so it works only for me =)

**Review by shilman — CHANGES_REQUESTED** [review]
tests are working well on my machine in node v7.10.0

**Comment by Hypnosphi** [comment]
Yeah, it turns out that things work with node starting from 7.0.0 because of `Object.values()` support. Still not LTS though (and never will be)

**Comment by Hypnosphi** [comment]
Oh, and now it enforces 7 =(
I think I'll just leave it .gitignored

**Comment by ndelangen** [comment]
Whoops sorry, I missed the change in the PR and misread your comments.

Can you repush?

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
