### PR TITLE
ci: apply better dispatch

### PR DESCRIPTION
**Pull request by tooppaaa**
Apply @gaetanmaisse logic on other scripts

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I think a .ts file is used by a .js file now?

**Comment by tooppaaa** [comment]
Yes but it's fine in that direction.

**Comment by ndelangen** [comment]
No it's not?

something.js > something-elese.ts
can't work AFAIK

something.ts > something-elese.js
can, but that's not what's happening AFAIKS

**Comment by tooppaaa** [comment]
Yep you're right ! We can wait https://github.com/storybookjs/storybook/pull/10785 to be merged for this one.

**Comment by ndelangen** [comment]
@tooppaaa That PR seems to be not great for performance. The Ts migration of the scripts seems to add a lot of weight. @yannbf reported it was actually slower on his machine then before...

I'm unsure what to do about it...
So for now that PR is on pause, unless we can find some way of making that performant?

**Comment by shilman** [comment]
@tooppaaa what's going on with this one?

**Comment by tooppaaa** [comment]
Unsure. Let's drop it :) changes are minimal

**Pull request closed without merging**
