### PR TITLE
Fix inline story style

### LINKED ISSUE #21831: [Bug]: for the autodocs page parameters.docs.story.height doesn't work if inline is true and works if inline is false
### Describe the bug

Doesn't work:
```javascript
const meta: Meta<typeof Loading> = {
    title: 'Loading',
    component: Loading,
    tags: ['autodocs'],
};

export default meta;

type Story = StoryObj<typeof Loading>;

export const Base: Story = {
    parameters: {
        docs: {
            story: {
                height: '400px',
            },
        },
    },
};
```

Works:

```javascript
const meta: Meta<typeof Loading> = {
    title: 'Loading',
    component: Loading,
    tags: ['autodocs'],
};

export default meta;

type Story = StoryObj<typeof Loading>;

export const Base: Story = {
    parameters: {
        docs: {
            story: {
                inline: false,
                height: '400px',
            },
        },
    },
};
```

### To Reproduce

_No response_

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.112
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
```

### Additional context

sb@7.0.0-rc.10

### PR DESCRIPTION
**Pull request by 0916dhkim**
Closes #21831

## What I did

`<InlineStory>` component has a typo in its inline css where it selects ID for the story block. This PR fixes the typo.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @0916dhkim Thank you so much for your contribution! Great catch 🚀

**Comment by yannbf** [comment]
> @yannbf Happy to contribute! By the way, what would be the best way to find other Storybook issues that are first-time friendly?
> 
> I'm regularly organizing public mob programming sessions at TorontoJS community, and there are many developers who are interested in open-source contribution. In fact, this PR was created during one of those sessions 😄 [meetup.com/torontojs/events/dctzbtyfcfbxb](https://www.meetup.com/torontojs/events/dctzbtyfcfbxb/)
> 
> TorontoJS is a non-profit 100% volunteer-run community, so any advice or support is appreciated. Hope I can contribute more to Storybook!

Ah that is amazing to know! @usrrname @winkerVSbecks you might even know @0916dhkim!
@vanessayuenn maybe you are interested in this collaboration for community contributions!

**Comment by usrrname** [comment]
Yep @0916dhkim runs our mob-programming style JS Code Club, it's awesome!

**Comment by usrrname** [comment]
screaming! two of my favourite things working together! haha

**Review by JReinhold — APPROVED** [review]
This is great, thank you so much! 🥳

**Pull request merged**
