### PR TITLE
Add splitpane repo

### PR DESCRIPTION
**Pull request by ndelangen**
Issue:

## What I did
ADD the split-pane repo to this repo

## How to test
run `npm run test`

### CODE REVIEW

**Comment by ndelangen** [comment]
@aaronmcadam @benediktvaldez Can you review?

**Comment by shilman** [comment]
@ndelangen please provide manual testing instructions in `how to test` section of PR 😸

**Review by shilman — CHANGES_REQUESTED** [review]
@ndelangen please provide manual testing instructions in `how to test` section of PR 😸

**Comment by ndelangen** [comment]
Closing this, as @UsulPro suggested it's better to not maintain this fork, and use the original here: https://github.com/tomkp/react-split-pane

**Pull request closed without merging**
