### PR TITLE
Notifications placement

### PR DESCRIPTION
**Pull request by domyen**
Issue:#5421 Notifications are obfuscated when the sidebar is narrow.

## What I did
- Made a new directory for notifications components
- Shortened update notification phrasing to "Storybook X.X.X is available"

**Todo**
My goal is to style the notifications like "flash" notifications, which appear above all other content. 
- Extract Notifications from `Sidebar` and put them at the top level of the layout. Currently app notifications live in the sidebar. 

## How to test
- Drag the sidebar to be narrow. If you don't see the update notification, ensure you're cache is cleared and that you're on an older version of SB.

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
LGTM

**Comment by domyen** [comment]
@ndelangen see below for reference design on notifications hoisting

[Mobile zeplin](https://app.zeplin.io/project/5b9991d21eef5c64b5703109/screen/5c745b08a424841af6a03106): 
mobile notifications


[Desktop zeplin](https://app.zeplin.io/project/5b9991d21eef5c64b5703109/screen/5b999206ce2dce43c85e945f): 
storybook

**Review by shilman — APPROVED** [review]

**Comment by shilman** [comment]
@domyen is this still WIP?

**Comment by domyen** [comment]
Yea, Norbert is taking this one now.

**Review by shilman — APPROVED** [review]
LGTM!

**Pull request merged**
