### PR TITLE
Improve `brand` API 

### PR DESCRIPTION
**Pull request by domyen**
Issue: #5665, [this comment](https://github.com/storybooks/storybook/commit/387959d67560437f5299a9003b01478c25014e4d?diff=unified#r32184678)

@tmeasday passing to you to allow users to set `title` and `url` via the params API in their .storybook/config. 

Question: do you think we should also allow folks to pass their custom `component` via the params API? This would be new functionality beyond that of the old addon/options API.

## What I did
- Update `brand` API so users can pass `title`, `url`, and custom `component`s.
- Update SidebarHeading to component to support the API
- Update SidebarHeading.stories to document the new states

## How to test

- Is this testable with Jest or Chromatic screenshots?
Yes, look in Chromatic at the new stories.

- Does this need an update to the documentation?
#5671 is an open ticket to do this for the entire deprecated options API.

### CODE REVIEW

**Comment by tmeasday** [comment]
@domyen hooked it up. There's one issue which I would appreciate @ndelangen's input on. 

When you set the deprecated `name` options via story-level parameters (see this story: http://localhost:9011/?path=/story/addons-options--setting-name), it stores `theme.brand.title = 'Custom Storybook'` in the store as you'd expect.

However when you "unset" it by browsing away (i.e. go to a story that doesn't set that option, it does not clear it, because this line only ever additive to whatever's in the store already: https://github.com/storybooks/storybook/blob/7c6cae66ce766e1b28495cffa3b3d3c8e837cdc8/lib/ui/src/core/init-provider-api.js#L36 

So if your options are `{}` the store will remain unchanged. I'm not super concerned about this particular case (it's an edge case of a deprecated usage) but I think in general this problem may rear its head as people set and then unset options. 

Perhaps instead we should make less stateful and not read the existing values from the store? The downside I see in doing that is the default values that are set in the store may get lost: https://github.com/storybooks/storybook/blob/7c6cae66ce766e1b28495cffa3b3d3c8e837cdc8/lib/ui/src/core/initial-state.js#L5-L21

Instead, perhaps those default values should be spread into the generated options? Something like:

```js
// Instead of 
          ui: {
            ...ui, // <- this is the current state in the store
            ...pick(options, Object.keys(ui)),
            ...checkDeprecatedUiOptions(options),
          },

// This:

         ui: {
            ...defaultUiOptions,
            ...pick(options, Object.keys(ui)),
            ...checkDeprecatedUiOptions(options),
          },
```

What do you think @ndelangen?

**Comment by shilman** [comment]
@Hypnosphi Mind looking this over? It addresses your comment from a previous PR. Looks pretty good to me

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by shilman** [comment]
@tmeasday pls update snapshots

**Comment by Hypnosphi** [comment]
@shilman looks Ok, but we still need to mention it as a breaking change in `MIGRATION.md`. In v4, `brand` was an object as well, but it was a style object (which is quite expectable in theme)

**Comment by Hypnosphi** [comment]
Honestly, this API for brand feels more like `options` than `theme` to me

**Review by shilman — APPROVED** [review]

**Review by ndelangen — CHANGES_REQUESTED** [review]
API not ok, will take this PR and refactor

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@Hypnosphi I'd like to make this a custom component someone can just inject, however with the current working on how the theme needs to cross the frame boundary, that's not possible.

I hear you can especially the brandUrl, doesn't feel like a theme variable to me either.
But long term we want to group the whole brand customization into 1 thing, right now, the theme is the most convenient.

**Comment by ndelangen** [comment]
As discussed today:

I changed brandComponent to brandImage. This is a lot more limiting.
Simply put, we can't currently have react component cross the frame-boundary.

Until we can set the theme in the manager directly this is all the customizability we can offer.

**Comment by domyen** [comment]
The stories that track this are broken, they should look [like this](https://www.chromaticqa.com/component?buildNumber=7549&appId=5a375b97f4b14f0020b0cda3&name=UI%7CSidebar%2FSidebarHeading&specNumber=1) (except the `customBrandComponent` story) but they all render the same thing [like this](https://www.chromaticqa.com/component?buildNumber=7587&appId=5a375b97f4b14f0020b0cda3&name=UI%7CSidebar%2FSidebarHeading&specNumber=4).

**Comment by tmeasday** [comment]
Thanks for sorting this @ndelangen

**Comment by shilman** [comment]
@ndelangen @domyen I expect it will confuse a lot of people that the `brandTitle` only affects the alt text. I thought it would replace the text `"Storybook"` unless the user provided a `brandImage` to override the entire area (which is also confusing, I know).

**Pull request merged**
