### PR TITLE
Provide styling hook for Addon Info story body

### PR DESCRIPTION
**Pull request by duncanbeevers**
Issue: While most parts of the info addon ui offer configurable styles, the container in which the story body is rendered is unstylable.

## What I did
I added an empty styling hook for the story body, used in both the inline and standalone views.

## How to test
Configure a test to style the story body and observe its effects.

```
addWithInfo('default', () => <div>Fantastic</div>, {
  styles: (stylesheet) => Object.assign(stylesheet, {
    infoStory: {
      backgroundColor: '#4267B2'
    }
  })
});
```

### CODE REVIEW

**Comment by danielduan** [comment]
I get that the story info is unstylable, but can you give some use cases where this is necessary?

There's another PR open that lets the user customize the UI colors through the use of `addon-options`. Would love to know if that suits your use case instead of duplicating functionality.

**Comment by duncanbeevers** [comment]
Sure. My main goal is to add a little padding and a dashed border around the rendered component.

I use a custom decorator to mix in our apps base styles such as background color; however, due to the way `addon-info` renders the story in `inline` mode, there's no hook to reach the story itself. Instead I can put a border around the combination header+story+info.

I use this styling hook locally to add a little margin and a dashed

**Comment by shilman** [comment]
@duncanbeevers what do you think about #1147 as a solution instead?

**Comment by duncanbeevers** [comment]
@shilman I think it sounds great. I was just looking for something that solved my problem today, and don't see these as mutually exclusive.

Once the info can live as its own panel, a normal story decorator would solve my problem and this setting would presumedly just go away.

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
