### PR TITLE
React-native: Require user-provided async storage

### PR DESCRIPTION
**Pull request by Gongreg**
Issue: #6078

## What I did

Removed async storage usage in storybook, added ability to pass custom storage.

react-native-community/async-storage is a native dependency that requires linking. Some apps might not use it, so that would mean that storybook requires native dependency that the app itself doesn't have. That bring additional barrier to users. To avoid it we can allow to pass asyncStorage as a parameter to getStorybookUI({asyncStorage: require('react-native').AsyncStorage or require('@react-native-community/async-storage') or any other storage that has getItem and setItem}). Overall async storage functionality in storybook itself is not a core feature but a good to have thing, so asking for additional option shouldn't be too bad.

### CODE REVIEW

**Comment by Gongreg** [comment]
@shilman, it is kinda a breaking change, we are making some functionality opt in.
We need to add information in documentation about it.

**Comment by shilman** [comment]
@Gongreg can you give it a default value that does not make it a breaking change?

**Comment by Gongreg** [comment]
Not really, since that is the main reason why I move asybc storage out. I don’t know what is going to be used. If user doesn’t pass anything nothing bad will happen. It will simply skip trying to read/write to asyncStorage.

Thats why it is not really a breaking change, but rather moving out feature as opt in.

**Comment by shilman** [comment]
why can't you just make it default to the previous behavior, then it will not be breaking at all. and users can still overwrite it to use a different storage provider if they wish. in 6.0 you can make it completely opt in?

**Comment by shilman** [comment]
or does simply having the dependency introduce problems?

**Comment by Gongreg** [comment]
Exactly. If we introduce new dependency it brings native dependencies and we cant use old one since it doesnt exist in RN 59+

**Comment by Gongreg** [comment]
@shilman, so what should we do next?

**Comment by benoitdion** [comment]
@Gongreg we could default to `require('react-native').AsyncStorage` in the next version with a deprecation warning and remove the default in the version storybook version after that.

**Comment by Gongreg** [comment]
I guess we can do that for deprecation. But we also cant start to use react native community one.

**Comment by benoitdion** [comment]
Right. After the deprecation, the default implementation will be a noop

**Comment by Gongreg** [comment]
@shilman, @ndelangen I still feel like this is a way to solve the issue.

This will not be a "real" breaking change. If users want to continue to use asyncStorage then they will have to update, but they won't have to do anything if they don't need it.

**Comment by Gongreg** [comment]
There is already React Native version 0.61, so I think we are blocking users from using storybook by not implementing this fix.

**Comment by shilman** [comment]
@Gongreg please document the migration and then we break semver for this

**Comment by Gongreg** [comment]
@shilman, regarding the warning, you mean that in version v5 we display a warning to use new key, or manually set it to false? And in v6 we just remove the warning?

**Comment by Gongreg** [comment]
@shilman, added a warning

**Pull request merged**
