### PR TITLE
Fix #4269 iPhone viewport dimensions

### LINKED ISSUE #4269: Incorrect iPhone viewport dimensions
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Viewport Addon has incorrect viewports for iPhones (possibly other phones too, haven't checked)

### Steps to reproduce

https://github.com/storybooks/storybook/blob/master/addons/viewport/src/shared/index.js

No need to reproduce, reference config file. 

All iPhone **+** models have a viewport of **414x736**
All iPhone's including X and XS have a viewport of **375 x 667**
The iPhone XR and XS Max have a viewport of  **414x896**

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react": "^4.0.0-alpha.23
- @storybook/addon-viewport": "^4.0.0-alpha.23

### Affected platforms 

All platforms using @storybook/addon-viewport": "^4.0.0-alpha.23

### PR DESCRIPTION
**Pull request by J-Kallunki**
Issue: #4269

Fixed config of iPhone viewport dimensions
Reference config file.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@J-Kallunki thank you for the submission! Would you be able to resolve the unit test failures?

**Comment by J-Kallunki** [comment]
> @J-Kallunki thank you for the submission! Would you be able to resolve the unit test failures?

Yeah I fixed Viewport test but circeci: cli:
"could not find a copy of webpack to link in /tmp/storybook/node_modules/react-static-next-fixture/node_modules/uglifyjs-webpack-plugin/node_modules"

**Comment by igor-dv** [comment]
This is not related to your changes.

**Review by igor-dv — APPROVED** [review]

**Comment by gabrielcsapo** [comment]
🙌 awesome!

**Pull request merged**
