### PR TITLE
Add two additional CLI commands to storybook CLI

### PR DESCRIPTION
**Pull request by rmevans9**
Issue: #1804 

## What I did

Added a passthrough for two pretty essential arguments to the react-native packager

## How to test

Add a `--root <ABSOLUTE OR RELATIVE PATH>` and a `--projectRoots <ABSOLUTE OR RELATIVE PATH>` to the storybook start command in a react-native project and ensure the paths show up in the packager window.

### Is this testable with jest or storyshots?

I didn't see any tests around this CLI tool

### Does this need a new example in the kitchen sink apps?

I do not believe so. Probably just some documentation.

### Does this need an update to the documentation?

I couldn't find a good spot in the docs for this to go on first pass. I will be sure to update documentation once I know the best place to put this information

NOTE: A very similar PR was opened #1861. I believe both of these could live happily together as #1861 allows you to specify an entire config and this one specifically lets you append to `--root` and `--projectRoots`

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]
LGTM, would like a second person to review this!

**Comment by ndelangen** [comment]
Can someone else review this as well @storybooks/team ?

**Review by danielduan — APPROVED** [review]
looks good to me, definitely an option needed for react-native's default packager.

@rmevans9 have you tested this with haul to see if there's any side effects?

**Comment by danielduan** [comment]
Also, I would very much prefer one or the other in terms of this or https://github.com/storybooks/storybook/pull/1861. I think the command line is a simpler approach.

**Comment by rmevans9** [comment]
I have not tested haul. I can certainly do that but will likely be in the next few days that I can get that done.

**Comment by ndelangen** [comment]
I feel this would be OK to keep based on master and release as a patch, how do you feel about this @shilman ?

**Comment by k0nserv** [comment]
@danielduan Yeah I mostly agree as long as there isn't a need for `rn-cli.config.js` because some configuration cannot be done using argument passing.

**Comment by ndelangen** [comment]
I'm ok with merging this and releasing as next patch version. Do you agree @danielduan @shilman ?

**Comment by danielduan** [comment]
@ndelangen yeah this feels like a patch version update

**Comment by rmevans9** [comment]
A quick test of haul shows that it works. I don't believe it respects the settings but that would make sense since haul is more configuration based then the react-native packager.

**Comment by k0nserv** [comment]
Any indication when this will be released? It's currently a pretty significant problem for our project and from my tests you cannot do npm git dependnecies with scoped packages

**Comment by danielduan** [comment]
@shilman publish patch release soon? ^

**Comment by shilman** [comment]
@danielduan @k0nserv sorry guys fell behind on my github notifications and only saw this because of @danielduan 's mention on slack. i just published a patch release: https://github.com/storybooks/storybook/releases/tag/v3.2.11

**Pull request merged**
