### PR TITLE
Build: add more sandboxes to CI tests

### PR DESCRIPTION
**Pull request by yannbf**
Issue: #20886 

## What I did

This PR enables sandbox templates which were defined but still under `inDevelopment` treatment:
- html-vite js
- html-vite ts
- internal storyStoreV6 projects

Some tests were disabled for ssv6 given the lack of support for certain features.

Additionally, I changed the STORYBOOK_TEMPLATE_NAME variable to use the template `key` instead, which I believe everyone thought it was the key already, however it was using the readable `name` property.

## How to test

1. CI should test them out and surface any issues (or lack thereof)!

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [x] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by yannbf** [comment]
@tmeasday @shilman it seems that the e2e to test the ordering of stories fails for ssv6. Is that a bug, should the test be changed or should the test be skipped for ssv6?

**Comment by JReinhold** [comment]
> @tmeasday @shilman it seems that the e2e to test the ordering of stories fails for ssv6. Is that a bug, should the test be changed or should the test be skipped for ssv6?

I did some investigation on this, and I think it's a bug, and the failing test has caught that.

The docs pages in:
- [`internal/ssv6-webpack`](https://63dd39d8084587517bfbd4a8-hcameuqozu.chromatic.com/?path=/docs/addons-docs-docspage-basic--docs): Failing because "Another" is before "Basic" (both in the sidebar and in autodocs)
- [`internal/ssv6-vite`](https://63dd39be40aacee2d50c2084-hqiqiqrrzn.chromatic.com/?path=/docs/addons-docs-docspage-basic--docs): Correctly puts "Basic" first
- [`html/webpack5`](https://6343cdaad28795f71cd31c1f-kzhhyypqca.chromatic.com/?path=/docs/addons-docs-docspage-basic--docs): Correct
- [`html/vite`](https://63dd397461b9918f7bdd988e-dijjrzboaa.chromatic.com/?path=/docs/addons-docs-docspage-basic--docs): Correct

I wonder if https://github.com/storybookjs/storybook/issues/18659 is related to this.

**Comment by tmeasday** [comment]
Sounds like a bug @yannbf! Yay for tests :)

**Comment by tmeasday** [comment]
@yannbf if you like disable the test and add an issue to fix+enable it?

**Comment by yannbf** [comment]
> @yannbf if you like disable the test and add an issue to fix+enable it?

Done! Sorry for the poor description: https://github.com/storybookjs/storybook/issues/20941

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
