### PR TITLE
Sort the PropsTable rows alphabetically

### PR DESCRIPTION
**Pull request by Joseph-Whiunui**
Issue: #8539

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes Chromatic screenshots
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by patricklafrance** [comment]
What's you thought about this solution @shilman ?

**Comment by domyen** [comment]
I think the order of the prop table should be determined by the order of the props in the user's code. If users want to alphabetize their props they should do that themselves – Storybook shouldn't do that for them.

That said, I can see how alphabetizing would be useful for documentation consumers. Perhaps we can sort the table when you click on the "Name" table heading.

**Comment by shilman** [comment]
@patricklafrance I agree with @domyen. This solution might be an improvement on the current behavior, but alphabetizing feels like a patch-over for some underlying problem in one of the libraries we're using. Can we figure out what's going on under the hood and fix that instead?

(That said, thank you @Joseph-Whiunui for providing an improvement on what's there right now! 🙏🙏🙏 )

**Comment by ndelangen** [comment]
Some props are more used then others, those should get the most attention.

The alphabetical order could be an OK opt-in option though.

```
<PropsTable sort="alphabetical" />
```
?

**Comment by patricklafrance** [comment]
I like the idea of making the sorting configurable.

Instead of having predefined sorts, the PropsTable could accept a sort function?

Still need to find the actual problem thought.

**Comment by shilman** [comment]
I'd like to focus on "code definition order" as the default and then possibly add an `alpha` sort on top of that. Making it a function is easy, but makes it harder to serialize as we start making docs more embeddable in other contexts, so it would be great if we could start with something more narrow and expand if the use cases come up.

**Comment by Joseph-Whiunui** [comment]
No worries guys it was great to get a look at the OSS process!

**Comment by ndelangen** [comment]
@Joseph-Whiunui if you'd like, I've got a a prototype for something pretty revolutionary that could use some help to get finished..

**Comment by Joseph-Whiunui** [comment]
@ndelangen Sure, I'm happy to take a look.

**Comment by ndelangen** [comment]
Would you be able to attend an online meeting maybe? tomorrow?

I'll show you what I've got and what the concepts & goals are.

Are you on our discord yet? https://discord.gg/sMFvFsG

**Comment by Joseph-Whiunui** [comment]
It will depend on the time. I'm in NZ so I am available after work (5am-8am GMT) and before  (5pm-6pm GMT)

Yes, username is Joseph-Whiunui#7094

**Comment by patricklafrance** [comment]
Closing this since https://github.com/storybookjs/storybook/pull/8857 has been merged

**Pull request closed without merging**
