### PR TITLE
Remove onDeviceUI animation to support Detox screenshots

### PR DESCRIPTION
**Pull request by Gongreg**
Issue:

I am implementing Detox and storybook integration to do screenshot tests on React Native. There is a really funny issue with onDeviceUI. Because it is using animation, every single time animation happens the shadows are redrawn in view below the sidebar. Because of that comparing screenshots fails every time since few pixels of shadow look different. To avoid this problem I've added opt in option for animation onDeviceUIAnimated. By default it is set to true.

## What I did

Added option to disable animation (onDeviceUIAnimated=true/false).

## How to test

Is this testable with jest or storyshots?

Could be.

Does this need a new example in the kitchen sink apps?

Not really.

Does this need an update to the documentation?

I think we need it. Currently I am not sure we have somewhere all the possible options for StorybookUI documented.

### CODE REVIEW

**Comment by danielduan** [comment]
I would actually feel comfortable just removing animations in general. It's something that's nice to have but not necessary.

**Review by danielduan — CHANGES_REQUESTED** [review]
If you do decide to keep the animation, please document this prop somewhere.

**Comment by Gongreg** [comment]
I am all in for removing animations, unnecessary opacity too.

**Comment by Gongreg** [comment]
@danielduan, removed the animation.

**Review by danielduan — APPROVED** [review]

**Pull request merged**
