### PR TITLE
Fix react-native 0.58.5 and add support for 0.59

### LINKED ISSUE #5545: addon-ondevice-knobs does not support React Native >= 0.56 (requires dependency upgrade)
**Describe the bug**

`@storybook/addon-ondevice-knobs` does not support React Native >= 0.56 due to its dependency on `react-native-modal-datetime-picker`. My Storybook in React Native is working great until attempting to introduce knobs. Attempting to use knobs results in this error:

```
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```

https://github.com/storybooks/storybook/blob/d9cd83c2d5e1d160effdc6f51d1dd19a279b5028/addons/ondevice-knobs/package.json#L28

This has been fixed/release in https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v6.0.0 see merged PR https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/171 and original reported issue https://github.com/react-native-community/react-native-modal/issues/178

Upgrading `react-native-modal-datetime-picker` to `6.0.0` should fix the problem.

**To Reproduce**
1. Attempt using addon-knobs with React Native >= 0.56. Follow instructions at:
    1. https://github.com/storybooks/storybook/tree/master/addons/knobs
    2. https://github.com/storybooks/storybook/tree/next/addons/ondevice-knobs

**Expected behavior**
App should build/run. Knobs should work.

**Screenshots:**
image

**System:**
 - Framework: React Native
 - Addons: knobs, ondevice-knobs
 - Version: 4.1.11 (through to 5.x)

### PR DESCRIPTION
**Pull request by benoitdion**
## Issue
Newer versions of react native break with the current production version of storybook.

While the current focus is to restore support in the `next` branch it is still worthwhile to keep production working with the latest versions of react native.

Note that the same fix will likely need to be applied on the branch that adds react native support to Storybook 5.

## What I did
- Bring crna-kitchen-sink in a runnable state.
- Update `react-native-modal-datetime-picker` to `6.0.0`.

This fixes #5545

## How to test
The current crna-kitchen-sink app uses expo, which is great for rapid development but makes it tricky to validate various react native versions. To test these changes, I ejected from expo (
e17f6b9) and tested the changes to the addons with react native 0.58.5 and 0.59.0-rc.2. 

Ejecting from expo for the example app is a larger discussion so I reverted the eject in 
6aeda91.  We can remove e17f6b9 and 6aeda91 from history before merging but thought it could be useful if someone else wanted to pull down the changes.

### CODE REVIEW

**Comment by shilman** [comment]
@benoitdion Thanks for this -- it's a great contribution that's going to make a lot of RN users happy. I hope @Gongreg and other RN users can review and get this into a mergeable state. I marked it as `do not merge` for now because we're in the middle of our v5 release and I don't want to destabilize that. Will try to get that out in the next week or so and get back to business as usual. In the meantime, sorry for the inconvenience thank you for your patience on this!!!

**Comment by benoitdion** [comment]
@shilman this PR is against master instead of next hoping we can get another 4.x release before v5 is ready.

**Comment by shilman** [comment]
@benoitdion Oops sorry I missed that. Ok we can merge and release provided that one of the maintainers can take responsibility for making sure it's ready to go. Looking at you @Gongreg but open to anybody who wants to take it.

**Comment by Gongreg** [comment]
Hey. For the master branch I suggest to only update modal version.
The example project should be updated in the next branch.
The modal fix does work, since it was already done and tested in next branch.

**Comment by benoitdion** [comment]
Unfortunately this is another dependency. `react-native-modal-selector` was updated on both `master` and `next`. This updates `react-native-modal-datetime-picker`. 

If you don't mind I'd like to keep the changes to the example app since otherwise the changes cannot be tested in master within the repo. 

The `react-native-modal-datetime-picker` bump can be applied separately in `next` or in all likelihood in `react-native/use-core-for-server` or `react-native/use-core-for-server2` before making it to `next`.

**Comment by Gongreg** [comment]
Oh, my bad.

Regarding `react-native-modal-datetime-picker` it should be done on both master and next. Since the next branch will be broken for new RN versions too.

The reason I don't want to just throw in the example inside the master because master gets changes from the next branch when the time is right. And the next branch already has the changes fox example project inside the rewrite. Does the react native server part work in the updated example?

**Comment by benoitdion** [comment]
Discussed with @Gongreg offline and decided to merge #4425 instead of this. We'll bring back crna-kitchen-sink to a running state as part of v5.

**Comment by shilman** [comment]
@benoitdion @Gongreg Thanks for working this out together! Expect #4425 to be released on `4.1.x` sometime this weekend.

**Pull request closed without merging**
