### PR TITLE
#2243 optimizing for iphone x

### LINKED ISSUE #2102: Bug : The hamburger goes behind the status bar on Android
Attaching the image.

screen shot 2017-10-20 at 4 31 10 pm

### PR DESCRIPTION
**Pull request by danielduan**
Issue: 

fix - #2243 on iPhone X, menu button and header is partially hidden

## What I did

- Added vertical and horizontal margins on iPhone X for different orientations
- Removed strange story preview container resize behavior when menu is open
- Made menu background semi-transparent so users can see what's behind it
- Made text sizes larger so users with larger device screens can see better
- Changed all UI colors to black or white from different shades of alpha gray
- Disabled status bar on app start: might fix - #2102 

screen shot 2017-11-08 at 11 16 17 pm
screen shot 2017-11-08 at 11 16 21 pm
screen shot 2017-11-08 at 11 16 33 pm

## How to test

Is this testable with jest or storyshots?
yes
Does this need a new example in the kitchen sink apps?
no
Does this need an update to the documentation?
no
If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by danielduan** [comment]
can someone test this on android to make sure it still works?

**Comment by Hypnosphi** [comment]
> can someone test this on android
will do

**Comment by Hypnosphi** [comment]
Here's a screenshot from master: 
photo5195226062701832233

**Comment by danielduan** [comment]
Okay, looks like Android status bar still needs a bit of height to it. Let me add that.

**Comment by Hypnosphi** [comment]
Ideally, the status bar should automatically hide like it does on master — otherwise we have a regression gere, I think

**Comment by danielduan** [comment]
The implementation is a bit more complicated than that. I have no way of reliably detecting whether it's an iPhone X or not. I have to either use Expo's API to support CRNA or something like `react-native-device-info` which requires a native hook into the app.

Instead I just used `react-native` and its `Platform` API to determine when to pad the top. iOS will get 30px when the status bar is realistically only 20px on all other iPhones. Android I can push it and get 10px or 20px as well.

There's a new API `SafeAreaView` from `react-native` that needs to be backported so we don't regress on everything below 0.50.

**Comment by danielduan** [comment]
I'm fairly confident this is okay. We detect iPhone X with that library using platform and screen resolution. We then add a margin top only if it's iPhone X and reverted everything back.

I got some higher resolution menu and close buttons because the old ones were hideous.

screen shot 2017-11-08 at 9 06 40 pm
screen shot 2017-11-08 at 9 06 48 pm

**Comment by danielduan** [comment]
@Hypnosphi can I request another test from you?

I think this should solve all of the problems. There's some minor style improvements in here too.

**Comment by Hypnosphi** [comment]
The status bar is hidden again, thanks! Will also test in emulator to check if #2102 is fixed

**Comment by Hypnosphi** [comment]
I failed to manage to launch an emulator =( Let's just merge this, but not close  #2102 until the author confirms that it works

**Review by Hypnosphi — APPROVED** [review]

**Pull request merged**
