### PR TITLE
feat: use official webpack config for rax

### PR DESCRIPTION
**Pull request by lleohao**
Issue: https://github.com/storybookjs/storybook/issues/16575

## What I did
Use rax official webpack

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by lleohao** [comment]
Because use rax official config, so it support all features of rax.

Such as typescript, less, sass etc.

**Review by shilman — COMMENTED** [review]
Hi @lleohao thanks for your PR -- However, we've moved Storybook for Rax into its own repository: 
https://github.com/storybookjs/rax

Please issue your PR there. If you are interested in maintaining it, let's chat on Discord https://discord.gg/storybook

**Comment by lleohao** [comment]
> Hi @lleohao thanks for your PR -- However, we've moved Storybook for Rax into its own repository: https://github.com/storybookjs/rax
> 
> Please issue your PR there. If you are interested in maintaining it, let's chat on Discord https://discord.gg/storybook

I will PR to storybookjs/rax

**Comment by lleohao** [comment]
@shilman ok, I will PR to storybookjs/rax

**Comment by chencb** [comment]
@shilman I submit new PR to storybookjs/rax. https://github.com/storybookjs/rax/pull/3

**Pull request closed without merging**
