### PR TITLE
dependencies: Move webpack to peerDeps in @sb/react

### PR DESCRIPTION
**Pull request by maeriens**
Issue: Problems resolving Webpack 4 and 5 dependencies on React repositories

After the discussions in #15252, applied the suggestion made by @kherock's research

## What I did
I removed webpack: 4 dependency, and added webpack: ^4.0.0 || ^5.0.0 as a peer dependency. This should enable @storybook/react to infer in an easier way the used webpack version instead of requiring one, offering compatibility with both 4 and 5 versions.

### CODE REVIEW

**Comment by maeriens** [comment]
@shilman I'm unsure what are the failing tests about - I can see it started failing on all PRs after #15850 got merged but don't see why really

**Comment by shilman** [comment]
@maeriens update from `next` -- should be fixed there!

**Review by shilman — COMMENTED** [review]
@merceyz @gaetanmaisse can i get your eyeballs on this please?

**Review by gaetanmaisse — APPROVED** [review]
LGMT

Sidenote: As we are importing types from `webpack` in `@storybook/react` we should have `@types/webpack` either as dep or peerDep. In some investigation

**Comment by merceyz** [comment]
Keep in mind this is a breaking change as users will now be required to install `webpack` themselves. I'm not quite sure why this is needed

**Comment by gaetanmaisse** [comment]
@merceyz I think it's _only_ to satisfy the peerDep on `webpack` of `@pmmmwh/react-refresh-webpack-plugin`

**Comment by merceyz** [comment]
Removing the `webpack` dependency from `@storybook/react` shows that's not the case
```sh
@storybook/react@portal:/storybook/app/react::locator=sb%40workspace%3A. [a434b] doesn't provide webpack (pa2485), requested by @pmmmwh/react-refresh-webpack-plugin
@storybook/react@portal:/storybook/app/react::locator=sb%40workspace%3A. [a434b] doesn't provide webpack (p6b236), requested by @storybook/core
@storybook/react@portal:/storybook/app/react::locator=sb%40workspace%3A. [a434b] doesn't provide webpack (p6dfe7), requested by @storybook/react-docgen-typescript-plugin
```

**Comment by ndelangen** [comment]
Hello @maeriens Thank you for this PR.

I don't think we can fix the issue this PR is trying to fix in `6.5`, storybook dependencies on webpack aren't well organized, but changing that in a minor version would bring certain chaos to a lot of our users.

So in 7.0 we're doing a few things to set it right:
- there's no default builder, thus storybook packages never depend on a builder, the user MUST depend on one, and supply it.
- the manager will stop using webpack all together. This allows for a webpack-less storybook vite users crave (for good reason!)

So this puts us in the position relating this PR... The work to do the above has already been done in the `future/base` branch. The webpack-less manager builder needs some more finer detail work getting all the features in there we want, but that's just a matter of time now.

So I do want to say I really appreciate this PR, and I KNOW it took a big effort to do this. I know because figuring out what should depend on what an where and how is a complex endeavour...

So with some pain I must inform you that I'll be closing this PR.
I'm sorry. We should have acted upon it earlier, let you know. Please know we do sincerely appreciate your contribution.
Thank you.

**Pull request closed without merging**
