### PR TITLE
Ember: Remove global Ember usage

### PR DESCRIPTION
**Pull request by dbendaou**
Issue:

## What I did
Remove Ember global usage in favor of `Component` directly 

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @dbendaou thanks for this contribution! Is there a reason this PR is still a draft? Thanks!

**Comment by dbendaou** [comment]
Updated!

**Comment by dbendaou** [comment]
Could we move forward and have this merged?

**Review by yannbf — APPROVED** [review]
@shilman could you release this? Thanks ♥️

**Comment by krezicoder** [comment]
Hi @shilman when can we expect this to be released ? Our entire dev workflow is blocked as we are not able to use storybook with ember 4.x

**Review by shilman — CHANGES_REQUESTED** [review]
@dbendaou @yannbf @krezicoder This PR breaks CI -- specifically, it looks like there's a missing dependency on `@ember/component`:

Cursor_and_Mouse_Highlight_Overlay

**Comment by dbendaou** [comment]
Hey @shilman, I've updated my PR and updated the ember source dependencies to be able to leverage the module unification introduced in 3.27+ (previously it wasn't using "real" module)
It seems that TS cannot resolve the `@ember/component` dependencies, however, it's correctly implemented in `ember-source` [here](https://github.com/emberjs/ember.js/tree/master/packages/%40ember/component) 

And I'm able to properly run the Ember example 
Screenshot 2022-05-31 at 16 46 22

Do you know if I'm missing something ?

**Comment by gossi** [comment]
You may be able to pull in `@types/ember__component` to calm the CI for typechecks

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
How could this possibly work?
This @ember/component thing doesn't actually exist at all, on npm

**Comment by gossi** [comment]
`@ember/component` (amongst others) is a virtual package. `ember-cli` magic from the dark days makes it available during serving ember apps (it is virtual until this can be published on npm directly). Given this code is ~10yrs old, the virtual package is the required migration step.

What's needed to move this forward?

**Comment by ndelangen** [comment]
@gossi If you think this is good to merge, that's all that's required from me!

Please merge!, I think you have the access-level to do that, don't you?

**Comment by gossi** [comment]
Merging is blocked for me, @shilman requested changes. Can you unblock me or merge directly?

**Comment by ndelangen** [comment]
Merged!! Thank you @dbendaou and @gossi

**Comment by gossi** [comment]
@dbendaou we should backport this to storybook v6 - as it will take more time to make storybook v7 compatible with recent ember developments.

**Comment by SergeAstapov** [comment]
@shilman @dbendaou @gossi @ndelangen I'm open to help cherry-pick these changes to v6 but little confused which branch it should target. should it be `next-release`?

**Comment by shilman** [comment]
This is now available in 6.5.15-alpha.0

**Comment by dbendaou** [comment]
We didn't had any issue and it's currently working ok in the alpha, do you think we could add it in the next 6.x release?

**Comment by SergeAstapov** [comment]
couple minor issues I've noticed with `peerDependencies:

```json
    "@types/ember__component": "4.0.8",
    "ember-source": "~3.28.1"
```

this causes some issues... I believe these have to be changed to

```json
    "@types/ember__component": "^4.0.8",
    "ember-source": "~3.28.1 || ^4.0.0"
```

**Comment by ndelangen** [comment]
@SergeAstapov Would you be open to opening a PR to remedy this? 🙏

**Pull request merged**
