### PR TITLE
chore(deps): #4267 upgrade lodash to latest

### PR DESCRIPTION
**Pull request by StephM-W**
Issue: Fix for #4267 

## What I did
Upgraded lodash to ^4.17.11, updated imports and mocks (from lodash.xxx to lodash/xxx)

## How to test
```yarn test --core```

### CODE REVIEW

**Review by danielduan — APPROVED** [review]

**Review by wuweiweiwu — APPROVED** [review]
LGTM!

**Comment by igor-dv** [comment]
As far as I remember, when we tried the es6 version last time, it broke the users' code in Storyshots, because they needed to configure jest to transpile `lodash` from the `node_modules`.

**Comment by Stephanemw** [comment]
Would the es6 lodash module be more appropriate in that case? https://www.npmjs.com/package/lodash-es

**Comment by Stephanemw** [comment]
> As far as I remember, when we tried the es6 version last time, it broke the users' code in Storyshots, because they needed to configure jest to transpile `lodash` from the `node_modules`.

Do we have a testcase in the examples that exhibits this breakage? Otherwise, I suppose we could always request the various 2-year old lodash.xxxx packages be upgraded to address that CVE...

**Review by igor-dv — APPROVED** [review]

**Pull request merged**
