### PR TITLE
Update WithTooltip to use visible prop instead of defaultVisible

### LINKED ISSUE #21534: [Feature Request]: Close dropdown when clicking/focusing outside
### Is your feature request related to a problem? Please describe

The dropdown remains open when clicking outside. Only clicking again on its corresponding button will close it. 
Screenshot 2023-03-10 at 13 30 48

### Describe the solution you'd like

More user-friendly should be for the dropdown to close when the focus is lost and we move/click on a different area in the preview.

### Describe alternatives you've considered

_No response_

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Closes https://github.com/storybookjs/storybook/issues/21534

## What I did

Changed the way of how the visible property is passed to `WithTooltipPure` component.

## How to test

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Open Storybook in your browser
3. Click ones on the Theme switcher in the Toolbar
4. Now click on the iframe. The theme switcher should close now

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by pratikkarad** [comment]
Hi @valentinpalkovic,
I already had running `yarn start` on the first terminal and `yarn build --watch components` on the second terminal.
When I applied your changes, I could not close the dropdown box even when I refreshed the site. Only when I ran `yarn start` twice could I see the updated implementation.
My question to you is,
1. What am I doing wrong?
2. What commands should I run after updating the code?
3. How do I run the project in 'linked' mode if I'm running on 'unlinked' mode?

Looking forward to your positive response. 😃

**Comment by valentinpalkovic** [comment]
@pratikkarad 

After `yarn build`, you have to restart `yarn start`, otherwise you will not see the changes. Also, sometimes, it is safer to run `yarn task --task compile`, because you do not know, in which particular packages `components` is bundled into and maybe you are missing some further packages, where a compilation would be necessary as well.

I don't quite understand your third question:
> How do I run the project in 'linked' mode if I'm running on 'unlinked' mode?

**Comment by pratikkarad** [comment]
@valentinpalkovic, Thanks for the quick turnaround.
1. Do we need to re-run these two commands (i.e. `yarn build` and `yarn start`) every time for a single line of change?
2. I posted this question on discord but no one answered. But here's one more try - Do we have any facility to debug the code? I checked on the source tab of the browser but their source code becomes modular, so can't debug there. Also, I added console logs just to check if it is possible to log/ debug the code. But this also doesn't work. Any suggestion on debugging the code?

**Review by MichaelArestad — APPROVED** [review]
This is so much nicer to use. Thank you!

**Comment by pratikkarad** [comment]
Okay, understood. 
While we wait for @yannbf to reply, I was just playing with the code and found out that lint is giving the errors in `WithTooltip.tsx`. How can I add/append the code on this PR?

**Comment by valentinpalkovic** [comment]
@pratikkarad Can you share a screenshot? If lint would give an error, then the pipeline shouldn't be green. Strange that it errors for you

**Comment by pratikkarad** [comment]
Here is the screenshot of the lint error
image

Once we apply a null check on this, the error goes away
image
I think it makes sense to add a null check anyway.
@valentinpalkovic, What do you think?

**Comment by valentinpalkovic** [comment]
This doesn't seem to be rather a typescript error than a lint error. In general, I agree that we should enable strict null checks in our codebase, which we haven't done so far. My assumption is that you have enabled strict null checks for all workspaces somehow, but it is definitely not enabled in our repository so far.

**Comment by pratikkarad** [comment]
Got it 😄

**Pull request merged**
