### PR TITLE
Webpack5: Fix lazy compilation/fscache builderOptions when base config is disabled

### PR DESCRIPTION
**Pull request by ndelangen**
replaces: https://github.com/storybookjs/storybook/pull/19376

@shilman you were right, this is an issue on 7.0 as well.

### CODE REVIEW

**Comment by ndelangen** [comment]
@mandarini I labelled this with the `patch` so it should make it's way into the 6.5 release

**Comment by mandarini** [comment]
@ndelangen thank you so much!!!! :D :D

**Review by shilman — APPROVED** [review]
LGTM! ❤️

**Comment by ndelangen** [comment]
@mandarini We decided the risk of back porting this to 6.5 isn't worth it.

So the way for your users to enable this is either by setting the webpack config merge flag to true, migrate to SB7 (alpha version at the moment), or by manually editing the webpack config in `main.js` themselves.

**Comment by mandarini** [comment]
Thank you very much for this @ndelangen ! :)

**Pull request merged**
