### PR TITLE
Fix: peer dependency warning for `vite-react`

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/20179

## What I did

I bundled in "@joshwooding/vite-plugin-react-docgen-typescript", and also have it use this version: https://github.com/joshwooding/vite-plugin-react-docgen-typescript/pull/8

Which makes it a optional peerDependency.

### CODE REVIEW

**Comment by ndelangen** [comment]
Why everything is marked `new` in chromatic, is a mystery to me.. @tmeasday any idea why that might be?

**Review by IanVS — APPROVED** [review]

**Comment by tmeasday** [comment]
@ndelangen - I'm not seeing what you mean?

**Comment by ndelangen** [comment]
Must have been some inconsistent behavior then @tmeasday sorry for not removing the ping.

**Comment by tmeasday** [comment]
Hmm, doesn't sound ideal either way...

**Pull request merged**
