### PR TITLE
Change keyboard shortcuts to platform safe

### PR DESCRIPTION
**Pull request by Hypnosphi**
Issue: #403

See background: https://github.com/storybooks/storybook/issues/403#issuecomment-326461268

It turned out that `⌘ ⇧ Q` is "quit all apps" on macOS, and `⌘ ⇧ E` just doesn't work, so I used `X` for stories panel and `O` (the closest one to previous `P`) for search

### CODE REVIEW

**Comment by ndelangen** [comment]
I kind of feel this is not the best move to make.
If we're going to change the the shortcut, we should come up with a good system. This just moves some shortcuts to other letters that make less sense, and just happen to not collide with native ones (probably because the letters do not make much sense)

https://medium.com/@sashika/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee

**Comment by Hypnosphi** [comment]
>  less sense

What do `P` in search and `J` in addon position stand for?

**Comment by Hypnosphi** [comment]
> Letters only shortcuts

Actually I like this idea! We already block shortcuts when an input or textarea is focused, so it shouldn't interfere with text input. I'd suggest following shortcuts then:

* `Q`(uery) for search
* `A`(ddons) for addons panel
* `S`(tories) for stories panel
* `D`(own) and `R`(ight) for  addons panel position. Both letter should act the same way, i.e. one can press `R` to move the panel to the right, and the second `R` press will move it back down, same thing with `D`
* `F` for fullscreen
* `?` for showing the shortcuts help

Note that all those letters are quite close on keyboard

**Comment by Hypnosphi** [comment]
> not interfere with the story's keydown/keyup events

I think we can introduce some way to mark element so that it blocks shortcuts when focused, like it's done for all the input fields by default

**Review by danielduan — APPROVED** [review]
I'm gonna okay this one because I think it makes sense and fixes some old issues.

**Review by ndelangen — APPROVED** [review]

**Comment by timgivois** [comment]
why did we use cmd + shift + c.... it is inspect element shortcut in chorme, it's REALLY annoying....

**Comment by Hypnosphi** [comment]
Oh I see, my fault. I wish it would be documented here
https://support.google.com/chrome/answer/157179?hl=en

**Comment by benediktvaldez** [comment]
It's also 'Start element selection' in Safari (essentially the same as selecting an element for inspection).

**Comment by Hypnosphi** [comment]
Ok looks like we need to switch to letter only shortcuts
https://github.com/storybooks/storybook/pull/1858#issuecomment-331628044

If anyone wants to open a PR, go for it

**Comment by apertureless** [comment]
Well, why not make it configurable over `addon-options`? 
It is really tough to find a cross os + cross browser all in one solution.

**Pull request merged**
