### PR TITLE
chore(docs): path in the examples seems wrong

### PR DESCRIPTION
**Pull request by frassinier**
Issue: When using CLI to init a new storybook instance, it comes with MDX example and the path seems wrong

## What I did

Fix the path

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @frassinier thanks for your contribution!

This is a bit tricky because the `stories` folder is placed inside of `src` if there is a `src` folder. Otherwise, it will be placed in the root folder. You can see the logic [here](https://github.com/storybookjs/storybook/blob/next/lib/cli/src/helpers.ts#L210).

Still, I'd say it's better to omit `src` so that it's less confusing to most projects 🤔 WDYT @kylegach ?

**Comment by yannbf** [comment]
In case we're going through with this change, I'd love if you could also change this bit in the same file, as it also contains `src` in the path:

```
View their code in the `src/stories` directory to learn how they work.
```

**Comment by frassinier** [comment]
Up to you guys! But I would vote in favor of removing `src` everywhere!

**Comment by kylegach** [comment]
> Still, I'd say it's better to omit `src` so that it's less confusing to most projects 🤔 WDYT @kylegach ?

Agreed. We strongly recommend colocating stories with the component source, anyway. The `stories` directory is just a place for us to inject some examples for reference, so whether it's in `src` or not shouldn't matter much. We'll want to be sure the TypeScript templates still work as expected though, as sometimes TSConfig specifies `include: 'src/**'`.

**Review by yannbf — APPROVED** [review]
Looks good to me!

**Comment by yannbf** [comment]
> 

Hey @frassinier we'll discuss about this in the [Weekly triage meeting](https://discord.gg/ud9M87ET?event=975718836278009966) (happens publicly in discord) in a few hours!

**Comment by yannbf** [comment]
Hey @frassinier thanks for your patience and contribution! I'm merging this now.

**Review by yannbf — APPROVED** [review]

**Pull request merged**
