### PR TITLE
Addon-docs/Angular: fix extractEnumValues undefined error

### PR DESCRIPTION
**Pull request by Nxtivision**
## What I did

This is the same problem as #16523. I took a look to the entire file, and now, that should work as expected with the result 'object' when resolving types 😄  If you want to avoid this kind of problem, I recommend to enable strict mode in your tsconfig file. However, the entire project is really big and it could be a huge refactoring in some places... 🤔 

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by KMathyTech** [comment]
Hi everybody,

Do I have to do something here? Seems CI is broken, however, I just changed one line

Kind regards

**Comment by shilman** [comment]
@KMathyTech yeah, we have some unrelated CI issues. I plan to review soon but am hustling to try to get 6.4 out the door and it's taking all my waking hours (and even some non-waking ones)! Thanks for your patience and for the contribution 🙏

**Comment by KMathyTech** [comment]
> @KMathyTech yeah, we have some unrelated CI issues. I plan to review soon but am hustling to try to get 6.4 out the door and it's taking all my waking hours (and even some non-waking ones)! Thanks for your patience and for the contribution 🙏

Hey,
no worries, I understand the importance of the project and the time you devote to it. Take the time you need 😄

**Review by shilman — APPROVED** [review]
LGTM! Thanks for your patience

**Pull request merged**
