### PR TITLE
fix compatibility with @babel/core v7

### PR DESCRIPTION
**Pull request by maiis**
Issue:
When using babel v7-beta, this happens:
```
Module build failed: TypeError: Cannot read property 'loose' of undefined
    at _default (/Users/maiis/Projects/zip.ch/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:20:23)
    at Function.memoisePluginContainer (/Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/maiis/Projects/zip.ch/node_modules/@storybook/react/node_modules/babel-core/lib/transformation/file/index.js:135:24)
```

## What I did
I moved `babel-core` to peerDependencies. This way `babel-core` is not installed again into `@storybook/react/node_modules/`

## How to test

Use it with @babel7 dependencies and [babel-bridge](https://github.com/babel/babel-bridge)
```
  "devDependencies": {
    "@babel/core": "7.0.0-beta.35",
    "babel-core": "7.0.0-bridge.0",
    "@storybook/react": "3.2.17",
   ...
  }
```

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Please do the same for storyshots addon https://github.com/storybooks/storybook/blob/3b03c7e1b9b39f34b4fe3ac337bedd614eb73a75/addons/storyshots/package.json

**Comment by maiis** [comment]
@Hypnosphi done ✅

**Comment by Hypnosphi** [comment]
Thanks, will test

**Review by ndelangen — APPROVED** [review]

**Comment by AKFourSeven** [comment]
I am still having these issues, how can I make sure that I get these fixes on my story book (and add-ons) ?

**Pull request merged**
