### PR TITLE
Lock yarn version

### PR DESCRIPTION
**Pull request by kevin940726**
Issue: N/A

## What I did

Lock `yarn` version via `yarn-path`.

The file is generated by running `yarn policies set-version` in the project, which will download the latest stable version of yarn and enforce the version for every contributors. The [doc](https://yarnpkg.com/en/docs/cli/policies#toc-policies-set-version) explained it well on why do we want this.

> When working inside a team, you usually end up in the situation where one of your colleagues uses a different version of Yarn than you. While usually inconsequential, it might sometimes cause subtle and hard to debug issues - for example your colleague might be on a version of Yarn that doesn’t support a feature you rely on, such as the workspaces.

> Note that this command also is the preferred way to upgrade Yarn - it will work no matter how you originally installed it, which might sometimes prove difficult to figure out otherwise.

## How to test

N/A

### CODE REVIEW

**Comment by ndelangen** [comment]
We haven't hit the problem described so far.

This PR adds a whopping 147 thousands lines of code to the repo.
I'm unsure how I feel about it.

**Comment by kevin940726** [comment]
@ndelangen Fair enough! IMHO, it helps prevent future problems regarding versions mismatch, additional code is acceptable. But I fully respect your decisions, feel free to close this PR :)

However, we could mark the file as binary via git attribute, so that they won't count as _code_. Would that help?

**Comment by ndelangen** [comment]
@kevin940726 my comment isn't a "no", I really respect your expertise input here.

Perhaps the issues HAVE been occurring, but they never surfaced to my attention, and potential contributors have been unable to work out the problem.

> However, we could mark the file as binary via git attribute, so that they won't count as code. Would that help?

What impact does that make? I'm not familiar with this feature.

Thank you so much for contributing 🙇

**Comment by kevin940726** [comment]
@ndelangen It's a feature of [git](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes) to mark files which doesn't look like a binary file as binary. Basically what it does is to mark the `yarn-1.21.1.js` file as binary format, so it won't show in the diff as +147K lines of code, but just as a binary file like adding an image.

Thank you so much as well 🙇

**Comment by ndelangen** [comment]
I'm ok with merging this, @shilman how do you feel about it?

**Comment by shilman** [comment]
@ndelangen OK but for 6.0

**Review by ndelangen — APPROVED** [review]

**Pull request merged**
