### PR TITLE
Components: reduce size of syntax highlighter

### PR DESCRIPTION
**Pull request by LarsDenBakker**
Issue: https://github.com/storybookjs/storybook/issues/9282

## What I did

It turns out that the solution was pretty simple. We were already importing the "light build" which doesn't include prebundled dependencies, but `react-syntax-highlighter` imports all languages anyway in their main package export. Importing from a specific file makes it work correctly. 

I added a comment in to that effect in the code, so that it can be removed later.

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes in the sense that they should not cause any visual changes.
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
I'm not sure what to do with this error:

```
Failing the build, there is 1 fail.
Request failed [403]: https://api.github.com/repos/storybookjs/storybook/issues/9287/comments
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}
Feedback: undefined
##[error]Docker run failed with exit code 1
```

**Comment by Rikpat** [comment]
I've been working on something related in the same file, I've included updated version of your change in my PR

**Review by shilman — CHANGES_REQUESTED** [review]
@LarsDenBakker Can you take a look at the 3 updated chromatic snapshots and see if you can figure out what's going on?

@Rikpat It looks like this is what's causing the problem in your PR 💡

**Comment by LarsDenBakker** [comment]
The changes seem to be formatting and a hash change, but I don't understand why my change would cause these.

**Comment by LarsDenBakker** [comment]
Ah, two of the three changes are from syntax highlighting. The DOM probably changed because now not all language definitions are loaded. Visually the css numerals have a different color, but it looks fine to me? Perhaps it's good to double check all the areas that show off syntax highlighting, or would chromatic pick up all the visual changes?

**Comment by shilman** [comment]
@LarsDenBakker I think they're all from syntax highlighting. I think we need to support HTML/CSS/JS/TS/MD highlighting out of the box.

**Comment by ndelangen** [comment]
We're currently importing these:
```
import jsx from 'react-syntax-highlighter/dist/esm/languages/prism/jsx';
import bash from 'react-syntax-highlighter/dist/esm/languages/prism/bash';
import css from 'react-syntax-highlighter/dist/esm/languages/prism/css';
import html from 'react-syntax-highlighter/dist/esm/languages/prism/markup';
import tsx from 'react-syntax-highlighter/dist/esm/languages/prism/tsx';
import typescript from 'react-syntax-highlighter/dist/esm/languages/prism/typescript';

ReactSyntaxHighlighter.registerLanguage('jsx', jsx);
ReactSyntaxHighlighter.registerLanguage('bash', bash);
ReactSyntaxHighlighter.registerLanguage('css', css);
ReactSyntaxHighlighter.registerLanguage('html', html);
ReactSyntaxHighlighter.registerLanguage('tsx', tsx);
ReactSyntaxHighlighter.registerLanguage('typescript', typescript);
```

We'd need to add markdown.

But there must be something else getting imported that is causing this:
https://www.chromaticqa.com/snapshot?appId=5a375b97f4b14f0020b0cda3&id=5e0c97b447849f00209d22cc

**Comment by ndelangen** [comment]
```js
import jsx from 'react-syntax-highlighter/dist/esm/languages/prism/jsx';
import bash from 'react-syntax-highlighter/dist/esm/languages/prism/bash';
import css from 'react-syntax-highlighter/dist/esm/languages/prism/css';
import html from 'react-syntax-highlighter/dist/esm/languages/prism/markup';
import md from 'react-syntax-highlighter/dist/esm/languages/prism/markdown';
import tsx from 'react-syntax-highlighter/dist/esm/languages/prism/tsx';
import typescript from 'react-syntax-highlighter/dist/esm/languages/prism/typescript';

import { PrismLight as ReactSyntaxHighlighter } from 'react-syntax-highlighter/dist/esm/prism-light';

import { ActionBar } from '../ActionBar/ActionBar';
import { ScrollArea } from '../ScrollArea/ScrollArea';

import { formatter } from './formatter';

ReactSyntaxHighlighter.registerLanguage('jsx', jsx);
ReactSyntaxHighlighter.registerLanguage('js', jsx);
ReactSyntaxHighlighter.registerLanguage('javascript', jsx);
ReactSyntaxHighlighter.registerLanguage('bash', bash);
ReactSyntaxHighlighter.registerLanguage('sh', bash);
ReactSyntaxHighlighter.registerLanguage('css', css);
ReactSyntaxHighlighter.registerLanguage('html', html);
ReactSyntaxHighlighter.registerLanguage('md', md);
ReactSyntaxHighlighter.registerLanguage('markdown', md);
ReactSyntaxHighlighter.registerLanguage('tsx', tsx);
ReactSyntaxHighlighter.registerLanguage('typescript', typescript);
```

**Comment by ndelangen** [comment]
I'm kinda ok with the regressions, though I'd like to know if we can prevent them.

**Comment by ndelangen** [comment]
See discussion here:
https://github.com/storybookjs/storybook/pull/9292

**Comment by matheo** [comment]
@ndelangen we need a way to customize this
I'm using `pug` and `styl` and I wonder if I can import the Highlighter and register custom ones.

**Comment by ndelangen** [comment]
I have some thoughts on this, but I could use some help.

**Comment by shilman** [comment]
Closed as dupe to 6.1 fix by @ghengeveld

**Pull request closed without merging**
