### PR TITLE
[WIP] new layout-system

### PR DESCRIPTION
**Pull request by ndelangen**
Work In Progress

**New layout system**:
This introduced a new core principle for storybook called 'layout'.
This can be set via a `config.js` or perhaps in the future could be set per story basis.

## goals:
 * [x] a config that describes the layout 
 * [x] implement config => render 
 * [x] support fullscreen switching
 * [x] support switching addonPanel
 * [x] support switching storiesPanel
 * [ ] write fantastic unittests *for great covefe*

## stretch goals
 * [x] allow setting of additional props
 * [ ] expose a list of default layouts importable for users
 * [ ] expose some utilities to help manage layouts
 * [x] get global config from config.js
* [ ] allow local config from story
 * [ ] allow modifying config at runtime

## long stretch goals
 * [ ] persist changes
 * [ ] setting on where to persist (localstorage / config)
 * [ ] deal with discrepancies between local changes and config changes

### CODE REVIEW

**Comment by ndelangen** [comment]
This is what the setup looks like:
screen shot 2017-10-20 at 10 43 40


This is what you do with this currently, although admittedly, having multiple previews is buggy right now.
screen shot 2017-10-20 at 10 37 34

**Comment by ndelangen** [comment]
Progress update:
It's now possible to define "static analysable" uiOptions in a file called `.storybook.js`.

This file will be loaded into the manager directly, the preview does not push the options into the manager on first run. (It still can).
I'm investigating if There's more options here. Like can I use this file as a universal storybook config file, and place all storybook related configuration in a statically analysable way.

Something to discuss on the roadmap meeting 🎉

**Comment by ndelangen** [comment]
UPDATE:

I implemented:
- support switching addonPanel
- support switching storiesPanel

Made a video showcasing some of the functionality:
[Video of the promised feature](https://www.youtube.com/watch?v=jInsVeMYTbU)

**Comment by ndelangen** [comment]
@shilman Can we discuss if this satisfies your idea of what must be done to get this merged into A 3.x release? 

Anyone else on the @storybooks/team want to weigh in on that? @danielduan @Hypnosphi ?

**Comment by danielduan** [comment]
I'm definitely leaning towards having this be 3.4. This does change Storybook's behavior for every possible user we have so it's definitely not a minor refactor.

However, if we can get this completed soon and go through a good amount of alpha testing, I could be convinced that this be included in 3.3.

**Comment by ndelangen** [comment]
Definitely 3.4 or higher, 3.3 is locked for significant changes AFAIK.

**Comment by ndelangen** [comment]
🤣
screen shot 2017-10-29 at 09 42 23

**Comment by renaudtertrais** [comment]
Could be great to be able to achieve those kind of layout:
image
image

**Comment by gauthamchandra** [comment]
Hi, I was wondering if this is still being worked on (maybe in another PR)?

We wanted to customize the layout and styling for the storybook UI itself but as mentioned earlier in this issue, that's not currently possible due to the dynamically generated nature of the CSS classes.

I wouldn't mind helping out in this regard and opening a PR but wanted to make sure noone else is already working on this.

**Pull request closed without merging**
