### PR TITLE
Add option `--story-filter` in cli to filter stories when starting storybook

### PR DESCRIPTION
**Pull request by JoSuzuki**
Issue: https://github.com/storybookjs/storybook/issues/5065

## What I did

Added the option `--story-filter` to CLI. Now when running `storybook dev` and `storybook build` you can specify a regexp to filter the stories that are going to be built. Eg.: `storybook dev --story-filter Button.stories`.

---

During the implementation I was in doubt if it would be better to implement:

1. An option to filter, as suggested by the issue https://github.com/storybookjs/storybook/issues/5065
2. An option to pass the glob of stories, which would override the stories specified in `main.js` as one comment suggested https://github.com/storybookjs/storybook/issues/5065#issuecomment-807295362.

I've ended up following the first option as it was more in line with the suggestion of the original issue.

Another point which I wasn't able to test, is if this will have a performance improvement on repos with many stories. If I understood correctly it should improve, as we are filtering the file paths before actually loading the content.

---

## How to test

In the example sandbox run the command passing the `--story-filter` argument (eg.: `storybook dev --story-filter Button`). It should only show the stories that match `Button`.

chrome_tbeFJBqvpS

I am not 100% sure on how to approach doing an automated test for this, any help would be apprecianted!

- [ ] Is this testable with Jest or Chromatic screenshots?
	- I don't think so.
- [ ] Does this need a new example in the kitchen sink apps?
	- I don't think so
- [x] Does this need an update to the documentation?
    - Yes. I've included in the `docs/api/cli-options.md` file.

### CODE REVIEW

**Comment by JoSuzuki** [comment]
Not sure, but I believe the tests failed because the machine ran out of resources 🤔

image
image

**Comment by ndelangen** [comment]
Hello @JoSuzuki as currently implemented you not actually achieving what you set out to achieve:
> filter the stories that are going to be built

Storybook will still build for all stories defined in the stories globs define in `main.js` even after this change.
But some stories will not show up in the sidebar, because they'll be missing from the storyIndex. (because that is where you filter them out).

I'm not convinced this should be a feature in storybook, let me explain why:
If a user were to run storybook like this:
```
STORYBOOK_FILTER="button" storybook dev 
```

And edit their `main.js` to do:
```
module.exports = {
  stories: async () => process.env.STORYBOOK_FILTER ? process.env.STORYBOOK_FILTER : []
};
```
... then they could already exactly what your intended change is: To tell storybook to build with a subset of the globs defined.

I understand you might be included to feel that adding a CLI flag isn't that much, and I would tend to agree.
But the case is we're trying to have fewer CLI flags rather than more, and push for most if not all config to exist in a single place: `main.js` (and eventually move that to `storybook.config.js`)

We appreciate the time, energy and skill you've put into making this PR.

If you care mostly about being able to filter which stories get built for your storybook, you have a way.

If you are instead strongly opinionated that YES, this needs to be a feature in storybook, this CLI flag should exist.. then I can be convinced. But we'd need to argue about what the exact CLI flag should be called, whether the value should be a regex, a glob or a pure string, and we need to get the implementation right.

Again: thanks for contributing, it's very very much appreciated! I hope to hear from you.

**Comment by dommett** [comment]
The cli use case for this is having a larger project which takes some time to build in storybook. Being able to work locally with a smaller set of components without possibility of checking in a config change, (or undo/redo when commit) would be useful for workflow.

If there’s another way of achieving this, I’d be interested in learning.

**Comment by ndelangen** [comment]
I understand your use-case @JoSuzuki; thank you for explaining it further though, I understand you'd want this.
But I don't think this is a universal feature request. 

So I'd rather have users solve this using the mechanism I described above.
I don't think this requires "checking in a config change, (or undo/redo when commit)".

It would require a permanent change to main.js config file: to make it respond to the environment variable.

**Pull request closed without merging**
