### PR TITLE
chore(a11y): update highlight toggle snapshot

### PR DESCRIPTION
**Pull request by Armanio**
🤷‍♂️

### CODE REVIEW

**Comment by CodeByAlex** [comment]
@Armanio it looks like it failed on that snapshot. Is there a reason why this is being changed?

**Comment by Armanio** [comment]
I just ran tests with --update param. :)

**Comment by Armanio** [comment]
```
  ● HighlightToggle component › should match snapshot

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "HighlightToggle component should match snapshot 1".

    - Snapshot
    + Received

    @@ -137,11 +137,10 @@
                "appBorderRadius": 4,
                "background": Object {
                  "app": "#F6F9FC",
                  "bar": "#FFFFFF",
                  "content": "#FFFFFF",
    -             "gridCellSize": 10,
                  "hoverable": "rgba(0,0,0,.05)",
                  "negative": "#FEDED2",
                  "positive": "#E1FFD4",
                  "warning": "#FFF5CF",
                },

      36 | 
      37 |     // then
    > 38 |     expect(wrapper).toMatchSnapshot();
         |                     ^
      39 |   });
```

Currenct `next` branch failing on tests. 🤔

**Comment by shilman** [comment]
Hmm @Armanio this doesn't need to be updated on my machine, and I don't think it's failing on CI either. Can you double check?

**Comment by Armanio** [comment]
I checked: pulled actual src, ran tests, it failed. 
Ran with 'update' param - update file. 
:thinking:

**Review by ndelangen — APPROVED** [review]

**Review by shilman — CHANGES_REQUESTED** [review]
Test is failing in CI ... ?

**Comment by Armanio** [comment]
Already irrelevant. Closed.

**Pull request closed without merging**
