### PR TITLE
CLI: Do not use modern TS assets in legacy TS projects

### PR DESCRIPTION
**Pull request by IanVS**
Issue:

New TypeScript (4.9+) syntax components could be added to a project using an older version of TS, if the renderer did not include a `ts-legacy` folder.

## What I did

Removed that unsafe fallback, and added some tests.

## How to test

- [X] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM, @kasperpeulen can you please take a look?

**Comment by kasperpeulen** [comment]
@shilman @IanVS I think this will break angular and web components, as they have only a ts directory, as there is no special syntax for TS4.9 for those renderers. I didnt want to duplicate directories there. 

I think we may just have to be careful to always have a ts-legacy directory when there is a ts directory with new ts features.

**Comment by IanVS** [comment]
In that situation wouldn't it be better to name the folder ts-legacy?  Then it would still be used by both, without the danger of breaking if someone creates just a new ts directory like almost just happened for Vue?

**Comment by kasperpeulen** [comment]
> In that situation wouldn't it be better to name the folder ts-legacy? Then it would still be used by both, without the danger of breaking if someone creates just a new ts directory like almost just happened for Vue?

Yeah, I understand that point, but there may never come a ts directory for angular, as I think it might be imposible to ever take adventage of satisfies there. So it would be also a bit weird to only having ts-legacy in the renderer, while we use it also for modern ts. 🤔

**Comment by IanVS** [comment]
Thanks for explaining.  I personally still think it's better to be safe and have an awkward folder name for Angular, or use a different word than `legacy` if that's the issue.  Do we have any tests that will detect if 4.9 syntax is used in a `ts` folder, without a `ts-legacy`?  This will break for users, which IMHO we should be careful to avoid.

**Comment by kasperpeulen** [comment]
@IanVS Hmm, I would say the correct approach would be to never have "only" have a `ts` directory if it contains `TS>=4.9` code. In that scenario, you always want to have also a `ts-legacy` directory, otherwise we will fallback to `js` in a `ts` project.

I guess the approach of this PR is more safe, but not sure if it is more "right" :D 

Say someone makes a PR that would add a `ts` directory to a renderer, but not taking advantage of TS 4.9 features, when we merge such a PR, it would only install use the `ts` directory for TS >= 4.9 projects, and fall back to JS in TS<4.9 projects, which is not what someone would expect I guess.

If we force such the `ts-legacy` directory name for renderers such angular and web-components, it may look weird, and people might think, hey the `ts` directory is missing, while that directory would not make sense.

Anyway, I understand your point as well. What do you think @shilman ?

**Comment by IanVS** [comment]
Yep, I like that approach.

**Comment by IanVS** [comment]
Marking as draft until I make the suggested change.

**Comment by IanVS** [comment]
The minimum TS version for our current examples is 3.8, because we use `import type`.

**Comment by IanVS** [comment]
@kasperpeulen what do you think of this now?

**Review by kasperpeulen — APPROVED** [review]
LGTM!!

**Pull request merged**
