### PR TITLE
CLI: Add storybook-addon-angular-ivy to angular install

### PR DESCRIPTION
**Pull request by shilman**
Issue: N/A

## What I did

Add Ivy support by default to new projects by default (opt-out).

@kroeder @ThibaudAV please LMK when you think the addon is stable enough to enable by default!

## How to test

```
cd angular-project
/path/to/storybook/lib/cli/bin/index.js init
```

### CODE REVIEW

**Comment by ThibaudAV** [comment]
maybe add it here too, no ? 
https://github.com/storybookjs/storybook/blob/fde2c044b67fb8f249b25c9f879b1e8a9313cabe/examples/angular-cli/.storybook/main.js

**Comment by shilman** [comment]
@kroeder @gaetanmaisse can you please take a look at the e2e test failures from this?

**Comment by gaetanmaisse** [comment]
@shilman is `storybook-addon-angular-ivy` published somewhere?

Running `npm info storybook-addon-angular-ivy'` I get 
```sh
npm ERR! code E404
npm ERR! 404 'storybook-addon-angular-ivy' is not in the npm registry.

```

**Comment by shilman** [comment]
D'oh @gaetanmaisse ... published & fixed 🤦‍♂️

**Review by gaetanmaisse — APPROVED** [review]
✅  Working on CI for both Angular 11 and 10. I have checked the projects after the e2e run and the addon is correctly added.

**Review by ndelangen — APPROVED** [review]

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
