### PR TITLE
CSF: Revert `makeDisplayName` & add stable `storyNameFromExport`

### PR DESCRIPTION
**Pull request by shilman**
Issue: #7599 

## What I did

This partially reverts the change made in #7878, keeping the displayName concept, but removing its configurability and adding a new `storyNameFromExport` concept.

## Why I did it

We made `hierarchySeparator` and `hierarchyRootSeparator` configurable, and it has been a maintenance nightmare, adding complexity across our codebase and bringing that nightmare to other tools in the Storybook ecosystem.

`makeDisplayName` is a similar foundational configuration. However since it can contain arbitrary JS code, we expect it will cause an order of magnitude MORE headaches. At the very least we're not ready to sign up for it without a lot more evidence that it's necessary.

This:

- Improves compatibility with legacy tools that don't support `displayName`
- Improves the readability of generated IDs
- Removes the concept of `makeDisplayName` entirely, replacing it with a stable `storyNameFromExport` utility function

Now we transform the CSF named export using `lodash.startCase` as the default. If you want other behavior you can use the `namedExport.story = { name: 'anything goes' }` construct.

```js
    it('should format CSF exports with sensible defaults', () => {
      const testCases = {
        name: 'Name',
        someName: 'Some Name',
        someNAME: 'Some NAME',
        some_custom_NAME: 'Some Custom NAME',
        someName1234: 'Some Name 1234',
        someName1_2_3_4: 'Some Name 1 2 3 4',
      };
      Object.entries(testCases).forEach(([key, val]) => expect(storyNameFromExport(key)).toBe(val));
    });
```

Consider the following CSF:

```js
export default { title: 'comp' };
export const fooBar = () => <>hello</>
```

**Before this change:**

```js
storiesOf('comp', module).add('fooBar', () => <>hello</>, { displayName: 'Foo Bar' });
```

Story ID in URL: `comp--foobar`

**After this change:**

```js
storiesOf('comp', module).add('Foo Bar', () => <>hello</>);
```

Note that if the user manually specifies a display name, it will still get passed through:

```
fooBar.story = { name: 'whatever' }
```

=> 
```js
storiesOf('comp', module).add('Foo Bar', () => <>hello</>, { displayName: 'whatever' });
```

Story ID in URL: `comp--foo-bar`

## How to test

```
cd examples/official-storybook
yarn storybook
```

### CODE REVIEW

**Comment by tmeasday** [comment]
I think this is good if we commit to the current version of `makeDisplayName` and don't change it in the future.

Otherwise having ids change between versions of storybook is a hot mess I guess ;)

Definitely makes more sense to do this if the user can't change that function.

**Comment by shilman** [comment]
@tmeasday We can make this stable AND potentially configurable in the future:

```js
storiesOf('comp', module).add('Foo Bar', () => <>hello</>, { displayName: userFn('fooBar') });
```

**Comment by tmeasday** [comment]
I guess although that could be pretty confusing too

**Comment by shilman** [comment]
@tmeasday I've updated the code to try to make it less confusing & updated the description up top.

**Pull request merged**
