### PR TITLE
Add support for SourceCode override in Info Addon

### PR DESCRIPTION
**Pull request by jcgertig**
Issue:
Ability to change how the source code is shown.

## What I did
Add a SourceComponent prop so the source code view can be overwritten.

## How to test

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps?
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by ndelangen** [comment]
Interesting! I could see how that's useful!

There seem to be some tests and linting failing, could you resolve that?
Let me know if you need help?

**Comment by ndelangen** [comment]
@jcgertig I'd like to invite you to check out this branch:
https://github.com/storybooks/storybook/pull/4086

And possibly assist in improving the info addon to use the SyntaxHighlighter component introduced there?

**Comment by jcgertig** [comment]
I can look into that sorry for being late to respond I had my filters to crazy for github

**Comment by ndelangen** [comment]
Want to join our discord?
https://discord.gg/sMFvFsG

**Comment by igor-dv** [comment]
Is this PR intended to be finished?

**Pull request closed without merging**
