### PR TITLE
CSF3: Add title prefix support for stories with custom titles

### PR DESCRIPTION
**Pull request by LucaCras**
Issue: #17508 

## What I did
I changed the autoTItle function to userOrAutoTitle, which enables inputting a custom title. If a title is given and the import path matcher, matches the file name, it will add a prefix if available.

If no prefix is available the method will just return the title.

If no title is given, the default autoTitle behaviour is used (returning undefined if no path is matched).

## How to test
Unit tests have been added.

Testing can be done by creating some stories with a custom title, and in main.js specifying a title prefix for files in the directory of the created story. Then check if the prefixes are correctly applied. It's also possible to check if autoTitle still works.

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
This looks like a great start! Love the unit tests ❤️ 

This change handles the "legacy" codepath, but doesn't handle the `storyStoreV7` codepath, which is here: https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/utils/StoryIndexGenerator.ts#L89-L94

You can repro this in `examples/react-ts` which uses `features.storyStoreV7`.

Please add an e2e example in `official-storybook` (which uses legacy mode) and `react-ts` (which uses `storyStoreV7`).

**Comment by LucaCras** [comment]
> This looks like a great start! Love the unit tests ❤️
> 
> This change handles the "legacy" codepath, but doesn't handle the `storyStoreV7` codepath, which is here: https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/utils/StoryIndexGenerator.ts#L89-L94
> 
> You can repro this in `examples/react-ts` which uses `features.storyStoreV7`.
> 
> Please add an e2e example in `official-storybook` (which uses legacy mode) and `react-ts` (which uses `storyStoreV7`).

I have fixed the issues, and I have added both examples :)

**Comment by matthew-dean** [comment]
I would love if this were merged!

**Comment by ljcl** [comment]
We use a plugin to automate adding monorepo package names as a prefix right now. And renaming stories that way isn't compatible with storyStoreV7.

This looks like it would kill two birds with one stone for us

**Review by shilman — APPROVED** [review]
Looking good @LucaCras -- updated with a note in `MIGRATION.md` and merging!

**Pull request merged**
