### PR TITLE
Build: upgrade playwright & re-enable bench

### PR DESCRIPTION
**Pull request by ndelangen**
replaces: https://github.com/storybookjs/storybook/pull/21240 ?

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
@ndelangen this doesn't revert @JReinhold 's changes tho? not sure if it's an issue

**Comment by ndelangen** [comment]
@shilman seems to go green?

**Comment by ndelangen** [comment]
the CRA bench seems to time out

**Comment by ndelangen** [comment]
```
Uncaught (in promise) TypeError: Failed to fetch
    at logEvent (vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-074d72.iframe.bundle.js:2075:3)
    at ./node_modules/@storybook/addon-bench/dist/preview.js (vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-074d72.iframe.bundle.js:2040:23)
    at options.factory (runtime~main.iframe.bundle.js:615:31)
    at __webpack_require__ (runtime~main.iframe.bundle.js:28:33)
    at fn (runtime~main.iframe.bundle.js:298:25)
    at Object.getProjectAnnotations [as nextFn] (main.iframe.bundle.js:234:75)
    at runtime.mjs:4:78491
    at Array.forEach (<anonymous>)
    at SynchronousPromise4._runResolutions (runtime.mjs:4:78432)
    at SynchronousPromise4.then (runtime.mjs:4:75974)
```

**Comment by ndelangen** [comment]
I downloaded the CRA bench, linked it to local verdaccio, and ran it, and it opened fine, except that the bench addon is causing issues.
If I remove the bench addon from main it works fine.

I don't know why the CI is timing out, it would suggest there's some issue happening in the playwright browser, but I can't really reproduce what.

**Review by shilman — APPROVED** [review]

**Pull request merged**
