### PR TITLE
Security: Update x-default-browser and fix issue with package.

### PR DESCRIPTION
**Pull request by The-Code-Monkey**
Issue:

Update x-default-browser to updated version, with fix for mac that will remove the default-browser-id error on mac os.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by The-Code-Monkey** [comment]
@shilman @yannbf this is the updated package with the fix that you had to revert earlier today. I have added a test to catch Mac issues in my package so this shouldn't happen again. My bad for missing a test.

**Comment by ndelangen** [comment]
Can I see the code you changed please?

**Review by ndelangen — CHANGES_REQUESTED** [review]
Hello @The-Code-Monkey 

I'm sorry but this seems a little bit suspicious. I hope you understand. Please show me the security changes you made to the package?

**Comment by The-Code-Monkey** [comment]
Hi there yeah I fully understand, all I have done is updated the project to typescript as well as update the packages contained within so that they do not have any open security issues on GitHub. 

https://github.com/The-Code-Monkey/TechStack/tree/dev/packages/x-default-browser

Here is the link for the code location.

**Comment by The-Code-Monkey** [comment]
Let me know if you want me to make any changes or anything. I have the dependencies automatically updating so if anything new comes out there will be a relevant patch version.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I checked it 🟢 

@The-Code-Monkey thank you for this PR, I really appreciate it. I'll be merging this as soon as the CI goes green 👍

**Comment by The-Code-Monkey** [comment]
@ndelangen No worries, happy to help out when I can, If you do find any issues with the package feel free to add issues to the TechStack Mono Repo and I will get to them as soon as I can. And like I said, its going to auto update with the use of renovate bot and auto publish to npm.

**Comment by kalkin** [comment]
Any chance you will do a release soon containing this change?

**Comment by shilman** [comment]
@kalkin yes after we have a bunch of people on 7.0 alpha to verify that the new version works well

**Comment by tyru** [comment]
@shilman Do you have any plan to release fixed 6.x.x version?

**Comment by shilman** [comment]
@tyru  this fell off my radar. I'll patch it back and release in alpha this week

**Comment by The-Code-Monkey** [comment]
@shilman I have moved this package to a new org name. It's now under @techstack/x-default-browser

This won't be changing again but package will keep getting security updates

**Pull request merged**
