### PR TITLE
Update ADDONS_SUPPORT.md

### PR DESCRIPTION
**Pull request by LazaroOnline**
Issue:
The documentation states that `addon-jest` doesn't work with VueJS, but it does seem to work in my Vue project with no problems, after all, the addon only needs the test results and a matching component name, I don't see why it wouldn't be compatible with all the frameworks, but I only tested it in Vue, so in this change I only added the check mark for Vue.

## What I did
Updated the docs for jest addon to show VueJs as supported since it already works.

## How to test
- In a project with VueCli v3, Vue 2.6.10, add Storybook 5.2.5, and @storybook/addon-jest v5.2.5, follow documentation instructions and voila, it shows the "Tests" tab with the related tests.

### CODE REVIEW

**Comment by shilman** [comment]
@CodeByAlex does this need to be updated across the board?

**Comment by CodeByAlex** [comment]
@shilman it does support all for the reasons stated above and the documentation should be updated.

**Comment by LazaroOnline** [comment]
+Updated for the other frameworks.

**Comment by shilman** [comment]
Thanks guys! 🙏

**Pull request merged**
