### PR TITLE
Source-loader: Disable linting altogether

### PR DESCRIPTION
**Pull request by shilman**
Issue: #9407 #9423 

## What I did

More aggressive than #9410 - just disable linting entirely in these synthetic files. Since this happens at load time, it shouldn't affect users' linting in general.

## How to test

Didn't test

### CODE REVIEW

**Comment by shilman** [comment]
Self-merging @tmeasday @ndelangen @mrmckeb

**Comment by zslabs** [comment]
I'm thinking this may be causing an issue when eslint is integrated into the webpack config and part of the reloading:

```
// main.js

const webpack = require('webpack');

module.exports = {
  stories: ['../src/components/*.stories.(js|mdx)'],
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-knobs',
    '@storybook/addon-actions',
    '@storybook/addon-viewport',
    '@storybook/addon-a11y',
  ],
  webpackFinal: async config => {
    // Provide React by default (since we don't need it with Emotion)
    config.plugins.push(
      new webpack.ProvidePlugin({
        React: 'react',
      })
    );

    config.module.rules[0].use[0].options.presets = [
      require.resolve('@babel/preset-react'),
      require.resolve('@babel/preset-env'),
      // Emotion preset must run BEFORE reacts preset to properly convert css-prop.
      // Babel preset-ordering runs reversed (from last to first). Emotion has to be after React preset.
      require.resolve('@emotion/babel-preset-css-prop'),
    ];

    // Enable eslint
    config.module.rules.push({
      test: /\.jsx?$/,
      exclude: /(node_modules|cache)/,
      use: [
        {
          loader: 'eslint-loader',
        },
      ],
    });

    config.node = {
      module: 'empty',
      dgram: 'empty',
      dns: 'mock',
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      child_process: 'empty',
    };

    // Return the altered config
    return config;
  },
};
```

The initial build works fine, but saves after error out. This worked fine in 5.3.1, but everything after has this issue.

**Comment by shilman** [comment]
@zslabs what do you think is going on? And what is your setup? CRA? Do you have a repro available?

**Comment by shilman** [comment]
@zslabs what do you think is going on? And what is your setup? CRA? Do you have a repro available?

**Comment by zslabs** [comment]
> @zslabs what do you think is going on? And what is your setup? CRA? Do you have a repro available?

Sorry, that was a very vague implementation I had on my end. You can find the complete repo at https://github.com/gremlin/chaoskit/tree/feature/emotion If you download, and run `yarn develop`, saves to `*.stores.js` work properly, but if you upgrade all the Storybook deps to the latest, subsequent saves to those stories will throw the error.

**Comment by zslabs** [comment]
Anymore info I could provide here? Should I open up an issue?

**Pull request merged**
