### PR TITLE
fix(webcomponents): make types play nicely with lit-element

### PR DESCRIPTION
**Pull request by urish**
## What I did

Before this change, returning html`<sometag>...</sometag>` from `storiesOf(...).add` would result in the following error: Type 'TemplateResult' is not assignable to type 'StoryFnHtmlReturnType'

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
I think we need a eslint-ignore rule for:
```
/tmp/*********/app/web-components/src/client/preview/types.ts
  2:1  error  'lit-element' should be listed in the project's dependencies. Run 'npm i -S lit-element' to add it  import/no-extraneous-dependencies
```

**Comment by urish** [comment]
@ndelangen do you want me to amend the pull request and add this?

**Comment by ndelangen** [comment]
done

**Review by ndelangen — APPROVED** [review]

**Comment by urish** [comment]
Even better :-)

p.s. you can see it in action here: https://elements.wokwi.com/
source code: https://github.com/wokwi/wokwi-elements

**Pull request merged**
