### PR TITLE
Added a vanilla React Native example app.

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: We need an example app for RN!  #1012 

## What I did

```
cd examples
react-native init ReactNativeVanilla
cd ReactNativeVanilla
# --> checked it ran normally

getstorybook
# --> checked it ran -- actually there was an issue #1200 I worked around

# --> updated package.json w/ file:// ref to @storybook/react-native
npm install
# --> checked it ran -- I had to revert to RN 0.44.1 because of https://github.com/facebook/react-native/issues/14209]

# --> updated package.json w/ file:// ref to @storybook/addon-storyshots
npm install
# --> added `__tests__/storyshots.js` test file
npm test # <- ensured it worked as expected.

# --> updated package.json w/ file:// ref to @storybook/addon-options
# --> Added code to use options in `storybook/addons.js` and `storybook/index.ios.js` 
#    (note had to work around https://github.com/storybooks/storybook/issues/1192 with a `setTimeout`)
npm run storybook / react-native run-ios # <-- to check the options worked.
```

## How to test

1. Checkout, `npm install`.
2. Run the storybook via (a) `npm run storybook` + `react-native run-ios`. Check the stories are displayed and the `name` option works.
3. Run `npm test`, ensure 3 snapshots are recorded.

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks CodeFactor! I tried to work around https://www.codefactor.io/repository/github/storybooks/storybook/pull/1202 but could not :)

**Review by shilman — CHANGES_REQUESTED** [review]
Please give me a chance to review before merging 😸

**Comment by tmeasday** [comment]
@shilman see in this description why I didn't just import a common file: https://github.com/storybooks/storybook/pull/1201

**Review by shilman — CHANGES_REQUESTED** [review]
@tmeasday you need to add this to `lerna.json` to ignore for both `publish` and `bootstrap`. We don't want to publish it. For bootstrap, it fails if I run a clean `bootstrap` from the root. But if I go to the RN app directory and `npm install` it works.

**Review by ndelangen — COMMENTED** [review]
Should we keep all folder-names lowercase and dash separated ?

**Comment by tmeasday** [comment]
React Native wouldn't let me pass such a name into it. I'm scared to change it after the fact ;)

**Comment by tmeasday** [comment]
Ok, made the changes requested

**Review by shilman — APPROVED** [review]
thanks!!

**Comment by shilman** [comment]
@tmeasday build is failing in minor ways

**Review by shilman — APPROVED** [review]
LGTM!

**Pull request merged**
