### PR TITLE
Improve the Readability UI of Readme.md

### PR DESCRIPTION
**Pull request by kanishbodhwani**
## What I did
Improved the Readability of Readme.md 

## Before  
Previous

## After 
Improved

### CODE REVIEW

**Comment by kanishbodhwani** [comment]
Please review this @jonniebigodes

**Comment by kanishbodhwani** [comment]
@jonniebigodes Please review this so that I can merge or do I have to do something else ?

**Review by ndelangen — CHANGES_REQUESTED** [review]
@kanishbodhwani thank you for contributing.

The `>` block indicates it's a quote of some kind... Though I might look nicer, visually. It's not really up to us how GitHub or NPM format their markdown content?

@jonniebigodes Unless you think otherwise I think we should not proceed with wrapping all text in quote blocks. If we want to ever incorporate this into the docs website this will be a chore to deal with.

**Comment by jonniebigodes** [comment]
@ndelangen, you took the "words right out of my mouth" (pardon the bad pun). I was about to write to @kanishbodhwani with the same response. With that in mind, @kanishbodhwani, if you're interested in learning how Storybook is built and willing to contribute, check the issues marked [good first issue](https://github.com/storybookjs/storybook/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and read the [contributing docs](https://storybook.js.org/docs/react/contribute/how-to-contribute) for more information. Also, if you need help, we have an active [Discord community](https://discord.gg/storybook) that I'm sure is more than willing to help you get unblocked.

I hope you have a great day.

Stay safe

**Pull request closed without merging**
