### PR TITLE
Remark slug and remark external links are deprecated

### LINKED ISSUE #21838: Upgrade `remark-slug` and `remark-external-links` are deprecated
### Describe the bug

We use two remark plugins to support our MDX functionality in `addon-docs` and `builder-vite`:

1. [`remark-slug`](https://github.com/remarkjs/remark-slug)
2. [`remark-external-links`](https://github.com/remarkjs/remark-external-links)

Both of these plugins are marked as deprecated and the maintainer (who also maintains MDX) advices to switch to their rehype equivalent instead, [`rehype-slug`](https://github.com/rehypejs/rehype-slug) and [`rehype-external-links`](https://github.com/rehypejs/rehype-external-links). 

If it doesn't produce any breaking changes, we should switch them over.

### To Reproduce

_No response_

### System

_No response_

### Additional context

`remark-slug` is used to automaticall add `id` to headings, which will create the link functionality to headings. That functionality should be preserved.

`remark-external-links` adds `target="_blank"` to all external links.

### PR DESCRIPTION
**Pull request by MehakFatima24**
Closes #21838

## What I did

I updated the dependencies of the project by replacing the deprecated remark-slug and remark-external-links with rehype-slug and rehype-external-links, respectively. This improves the codebase by using up-to-date and actively maintained packages.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by MehakFatima24** [comment]
@JReinhold @ndelangen  I did something silly 🥲 and accidentally closed my old [MR](https://github.com/storybookjs/storybook/pull/21858) , I have updated this one and tested the sandbox for react-vite and ran the unit tests. Can you please review this?

**Review by JReinhold — CHANGES_REQUESTED** [review]
Great work! A few minor comments, and then we need to upgrade `@storybook/mdx2-csf` when that gets released, which it should be soon.

**Comment by JReinhold** [comment]
@MehakFatima24 your changes to `@storybook/mdx2-csf` have been released at `v1.1.0`, so you should be able to upgrade that dependency in this branch and finally see the changes work :) https://github.com/storybookjs/mdx2-csf/releases/tag/v1.1.0

**Comment by shilman** [comment]
@MehakFatima24 @JReinhold what's going on with this one? Any chance we can get it over the line sometime soon?

**Comment by MehakFatima24** [comment]
> @MehakFatima24 @JReinhold what's going on with this one? Any chance we can get it over the line sometime soon?

Hi, I'd be updating the dependency and testing the changes again today, so we can get this merged.

**Comment by JReinhold** [comment]
This has gone stale, and it's probably easier to redo it from scratch for anyone that wants this feature in. Closing.

**Comment by valentinpalkovic** [comment]
@MehakFatima24

**Pull request closed without merging**
