### PR TITLE
Add storybook-chrome-screenshot to addon gallery

### PR DESCRIPTION
**Pull request by wadackel**
Issue: none

## What I did

Add [storybook-chrome-screenshot](https://github.com/tsuyoshiwada/storybook-chrome-screenshot) addon to [addon gallery](https://storybook.js.org/addons/addon-gallery/).

## How to test

```bash
$ cd docs
$ npm run dev
$ open http://localhost:8000/addons/addon-gallery/
```

### CODE REVIEW

**Comment by danielduan** [comment]
I undid the changes that the automatic linter scripts made to the title. Should be good to go.

**Review by danielduan — APPROVED** [review]

**Comment by tsuyoshiwada** [comment]
Hi @danielduan , Thanks for reviewed.
And sorry. I unexpectedly changed the title ...

**Review by kazupon — APPROVED** [review]

**Comment by kazupon** [comment]
@tsuyoshiwada welcome to storybook 😉

**Comment by tsuyoshiwada** [comment]
Hi @kazupon, Thx :smiley: !

**Pull request merged**
