### PR TITLE
Avoid logging an object on compilation errors

### LINKED ISSUE #1889: Silence error output
When using `start-storybook`, we're seeing the whole compilation object output on error:

```
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./config/storybook/config.js
Stats {
  compilation:
   Compilation {
     _plugins:
      { 'child-compiler': [Object],
        record: [Object],
        'after-hash': [Object],
        'should-generate-chunk-assets': [Object],
        'need-additional-pass': [Object],
        'additional-chunk-assets': [Object],
        'build-module': [Object],
        'failed-module': [Object],
        'succeed-module': [Object],
        seal: [Object],
        optimize: [Object],
        'optimize-modules-basic': [Object],
        'optimize-modules': [Object],
        'optimize-modules-advanced': [Object],
        'optimize-chunks-basic': [Object],
        'optimize-chunks': [Object],
```

The actual output spans hundreds of lines. The compilation error is output correctly before all of this output, and it does not occur when using `build-storybook`. Having a look at the source, I've tracked it down to this line:

https://github.com/storybooks/storybook/blob/master/app/react/src/server/index.js#L162

Where it just logs to the console anything it has caught.

I'm not sure why we're getting the output shown above, but maybe it'd be good to have an option to turn off any caught errors being output to the console? Happy to submit a PR, just unsure what the solution should be.

### PR DESCRIPTION
**Pull request by derekstavis**
## Issue

In certain configurations Storybook might log the whole Webpack
build object when warnings or errors are thrown. This was caused
by a `logger.error` call inside the `index.js` catch.

## What I did

This fixes by logging the error only when it's an instance of an error.

## How to test

This branch was tested on https://github.com/pagarme/pilot. Before
this changes, if an error happens while compiling (e.g. imported file not
found) a big object is logged:

screenshot from 2017-10-24 11-31-24

Resolves
#1889.

Is this testable with jest or storyshots?

Nope.

Does this need a new example in the kitchen sink apps?

Nope.

Does this need an update to the documentation?

Nope.

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by ndelangen — CHANGES_REQUESTED** [review]
Hi @derekstavis, Thank you for this!

Could you apply the same fix for `app/vue` and `app/react-native`?

**Comment by danielduan** [comment]
@derekstavis would you like help putting this into the other 2 apps?

**Comment by derekstavis** [comment]
Yes, will do sometime today! Thanks!

**Comment by danielduan** [comment]
@derekstavis we're looking to get a new release out sometime today. would love to have this in.

**Comment by Hypnosphi** [comment]
Opened #2199 instead

**Pull request closed without merging**
