### PR TITLE
Update index.tsx

### PR DESCRIPTION
**Pull request by JBaczuk**
Turns it into a component so you can use things like {useState} from 'react'.

Issue:

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Where is `StoryFn` defined?

**Review by shilman — APPROVED** [review]
LGTM

**Comment by shilman** [comment]
@ndelangen any idea what's going on with the build here? the logs are a bit cryptic

**Comment by ndelangen** [comment]
This file is now located in: https://github.com/storybookjs/react-native

**Comment by ndelangen** [comment]
@JBaczuk could you open a PR against this new repo?

**Pull request closed without merging**
