### PR TITLE
Devtool change and error handing

### PR DESCRIPTION
**Pull request by arunoda**
With this we are changing the webpack devtool to eval in the development and we no longer use source map.

Source map with babel is always problematic and CRA don't use it.
Also, it takes time longer than other eval.

We also can't use cheap sourcemap devtools because of Chrome has some bugs on it.
## 

We also cleanup some source map based error enhancements we did and how we handle errors.

### CODE REVIEW

**Comment by wmonk** [comment]
@arunoda do you know when this might make it into NPM?

**Comment by arunoda** [comment]
Today. In few hours.

**Comment by wmonk** [comment]
Amazing, thanks so much for sorting this so quickly!

**Comment by nottoseethesun** [comment]
`inline-source-map` is working well for me under Babel; it is not slow and imo it is very much well-worth it despite the identifier renaming (e.g., `this` to `_this2`.   At least, I can see my source code instead of a ton of compiled code/i-code.

Would it be possible to allow this to be configurable with a build switch for the storybook, so that users don't have to change the `node_modules` source?

**Comment by silvenon** [comment]
@nottoseethesun I believe you can override this in [full control mode](https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode).

**Pull request merged**
