### PR TITLE
API: Deprecate isToolshown, rename to showToolbar

### PR DESCRIPTION
**Pull request by JonathanKolnik**
Issue: 
This is a follow up to #18106 where @shilman [mentioned](https://github.com/storybookjs/storybook/pull/18106#issuecomment-1115006516) that we should rename isToolshown to showToolbar and deprecate isToolshown.

## What I did

Renamed isToolshown to showToolbar in most of the code and docs and deprecate isToolshown, left it as an optional config which I believe is the correct way to deprecate this specific config.

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [x] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — APPROVED** [review]
Thanks so much @JonathanKolnik !! 🙏 

@ndelangen can you please review & make sure that `isToolshown` is still supported until 7.0?

**Comment by ndelangen** [comment]
@JonathanKolnik looks like there are CI failures

**Comment by shilman** [comment]
@JonathanKolnik FYI I updated this PR with proper deprecation instructions. Please check it out!

**Comment by JonathanKolnik** [comment]
@shilman thank you, I actually meant to ask you about this after seeing a similar message on Friday but got sidetracked! 🙏

**Pull request merged**
