### PR TITLE
bump react-modal 2.4.1 -> 3.0.4

### PR DESCRIPTION
**Pull request by brucewpaul**
Issue:
react-modal needs to be ^3 as this is one of the dependencies that has a react peerdep. ^3 unlocks react16 as a peerdep

## What I did
bumped react-modal

## How to test

Is this testable with jest or storyshots?

Does this need a new example in the kitchen sink apps?

Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@ndelangen do we really need three dependencies here? Looks like `react-modal` is only imported from `@storybook/ui` code

**Review by Hypnosphi — CHANGES_REQUESTED** [review]
This mostly works, but there is one regression when comparing to `master`: when you open the search box, it isn't focused

Steps to reproduce:
```sh
yarn bootstrap --core
yarn start
```
Open http://localhost:9010/ and hit `⌘ ⇧ P`. Expected: search box is focused. Actual: it isn't focused

**Comment by ndelangen** [comment]
> @ndelangen do we really need all three dependencies here (in `lib/ui`, `app/react`, and `app/vue`)? Looks like `react-modal` is only imported from `lib/ui` code 

Agree, looks like we can remove the dependency on `react-modal` from `app/react` and `app/vue`.

This PR is a good place to remove it in, Will you be able to do that @brucewpaul, or do you need one of use to do it? 👍

**Comment by brucewpaul** [comment]
I'll be able to get to this and I'll take a look at the bug you described as well.

Additionally, has there been discussion on adding react16 to peerDeps and what how you all want to get there?

**Comment by ndelangen** [comment]
I'll put React16 on the issue list for the roadmap meeting. #1724 is on react 16.

**Comment by Hypnosphi** [comment]
@ndelangen master is on React 16 as well

**Comment by ndelangen** [comment]
Any progress on this, Is there anything needed of me? @Hypnosphi

**Comment by Hypnosphi** [comment]
The only critical thing is this: https://github.com/storybooks/storybook/pull/2098#pullrequestreview-71005657

**Comment by Hypnosphi** [comment]
I think I'll pick this one up

**Comment by Hypnosphi** [comment]
Superseded by #2238

**Pull request closed without merging**
