### PR TITLE
UI: Single story hoisting in sidebar

### PR DESCRIPTION
**Pull request by ghengeveld**
Issue: #8255

## What I did

This collapses single-story components in the tree view. Such components must have **exactly one child story** and this one story must have **exactly the same name** as the component itself. If these criteria are met, the component node is removed from the tree, and the story is put in its place.

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes
- Does this need a new example in the kitchen sink apps? Probably
- Does this need an update to the documentation? Yes

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Review by shilman — CHANGES_REQUESTED** [review]
Looks fantastic -- really great addition!

Can you:
- [x] Add an entry to MIGRATION.md
- [x] Add a section here https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy

**Review by shilman — APPROVED** [review]
Beautiful 😘

**Comment by reme3d2y** [comment]
Hi @ghengeveld , @shilman 

How can I use this feature if my stories looks like this:

```mdx
// AmountInput.stories.mdx

import { Meta, Story, Props } from '@storybook/addon-docs/blocks';
import { number } from '@storybook/addon-knobs';
import { AmountInput } from './Component';

<Meta
    title='Components/AmountInput'
    component={AmountInput}
/>

<Story name='AmountInput'>
    <AmountInput value={number('value', 0)} />
</Story>

# Some docs below

<Props of={AmountInput} />
```

I can still see drop-down is sidebar :(

**Comment by shilman** [comment]
@reme3d2y can you make a repro repo for this? i just tried out something similar in MDX in the storybook monorepo and it worked fine.

**Comment by pedroguia** [comment]
Hi @shilman,

I'm implementing storybook for the first time in our toolkit project, loving it btw, but can't make this new feature to work, can you help me? I have this story:

`import React from 'react';

import AutoCompleteFilter from '../components/autoCompleteFilter/AutoCompleteFilter';

export default {
  title: 'Components/Table Filters/AutoCompleteFilter',
  component: AutoCompleteFilter,
  argTypes: {
    onChange: { action: 'changed' },
  },
};

const Template = (args) => <AutoCompleteFilter {...args} />;

export const Default = Template.bind({});
Default.args = {
  id: 'autoComplete',
  options: [{ id: 0, name: 'Rocha' }, { id: 1, name: 'Joel' }],
  placeholder: undefined,
  value: '',
};`

I did install the pre release version. The problem is naming the story, i cannot give it the components name, as it should be, because it already exists.

Thanks.

**Comment by shilman** [comment]
How about this?

```js
import AutoCompleteFilterComponent from '../components/autoCompleteFilter/AutoCompleteFilter';

export default {
  component: AutoCompleteFilterComponent,
  ...
}
```

**Comment by pedroguia** [comment]
@shilman Does not seem to work:

- using the first solution i get this:

image

-using the second i get this:

image

**Comment by shilman** [comment]
@pedroguia make the two strings match. so

```js
export const Default = Template.bind({});
Default.storyName = 'AutoCompleteFilter'; // untested
Default.args = { ... }
```

**Comment by pedroguia** [comment]
@shilman I didn't notice lowercased 'C' before. It does work now using Default.storyName. Thanks!

**Comment by cherylcarpenter** [comment]
This is not working for me. 
Something tells me this code example is incomplete lol.
Can anyone please show a bare minimum but working stories.js where the title is the exact same as the component name?

image

**Comment by shilman** [comment]
@cherylcarpenter https://github.com/storybookjs/storybook/pull/13910

**Comment by iambumblehead** [comment]
**BUG** storybook converts exported story file names from camelCase to "camel case" and so if the storybook title and exported name include any camel-casing, the names won't match and the extra entry is rendered. Careful naming is required...

Something like this doesn't work
```javascript
export default {
  title: 'Box/boxCamelCase', // appears as 'Box Camel Case'
  component
}

export { TemplateInstance as boxCamelCase };
```

**Pull request merged**
