### PR TITLE
Merge addon-contexts into the monorepo

### PR DESCRIPTION
**Pull request by leoyli**
Issue: https://github.com/leoyli/addon-contexts

## What I did
- Fix some bugs (storybook tab switches / story-level configs).
- Fix typing, prettier, linting errors, example story snapshots to get a green build.
- Add some WHY comments for people interested in the source code.
- Add 2 stories under `Addon | Contexts` in our [official Storybook (React), clicking here to see it](https://monorepo-1yhwmyevg.now.sh/examples/official-storybook/?path=/story/addons-contexts--languages).

There were many bad git issues so I close and reopen this PR to remove noises. Please let me know if you have any feedback!

### CODE REVIEW

**Comment by leoyli** [comment]
It seems I have a hard time with the `yarn.lock` file 😠.

**Comment by leoyli** [comment]
I finally get a build really really green... `yarn.lock` file is really a black magic to me :'(

@ndelangen, @shilman: any suggestions!? Could we merge it! :smile_cat:

**Review by ndelangen — APPROVED** [review]

**Comment by leoyli** [comment]
I'm going to merge it since @ndelangen reviewed and approved. Meanwhile, I'm going to deprecate my published NPM pkg once it became available in a stable release (perhaps v5.1?!). If possible, I think we can briefly announce this addon in v5.1 releasing press so the community may know about it (What do you think, @shilman).

My next step is to add tests and **url param** feature, then push this addon toward Angular community. 💪

**Comment by shilman** [comment]
@leoyli Def worth an announcement!

**Pull request merged**
