### PR TITLE
Vendor the "memoizerific" library

### PR DESCRIPTION
**Pull request by eirslett**
Issue:

Storybook depends on a few unmaintained legacy libraries that don't support ESM. That causes issues with some next-generation build tools. These issues can be circumvented, but the best solution is to only use ESM-ready dependencies in the first place.

`memoizerific` is one of these libraries.

## What I did

This commit vendors/moves the unmaintained `memoizerific` library into Storybook, and converts the code to Storybook conventions: ESM modules, TypeScript, tests, code style etc.
It adds a `thirdparty` folder to the Storybook repository, to separate libraries that are a core part of Storybook from vendored dependencies.

## How to test

Running the unit/integration tests should suffice.

### CODE REVIEW

**Comment by eirslett** [comment]
Looks like there is a problem with the tests, could there be an issue with yarn/nx and the configuration for adding a new module?

**Comment by shilman** [comment]
@yannbf @eirslett so far our approach for vendoring packages has been to fork the repo into the `storybookjs` github org and release under the `@storybook` namespace.

Example: https://github.com/storybookjs/react-docgen-typescript-plugin

I propose that we do something similar for this package (if we do it at all!). This way:
- It's easier to update from the base repo if there are changes
- We can release easily on our own version schedule (e.g. using `auto` potentially)
- Consistency across vendored packages

**Comment by eirslett** [comment]
> so far our approach for vendoring packages has been to fork the repo into the storybookjs github org and release under the @storybook namespace. (...) I propose that we do something similar for this package (if we do it at all!). This way:

Yes, it makes a lot of sense to fork it and have a separate Git repository for each vendored library.

I think it would be wise to go in the direction of ESM-only dependencies, so that one day it's possible to run Storybook in the browser without any prebundling or build step at all (maybe except for transpiling JSX and removing TypeScript types). The speed gains we're seeing from Vite are largely because Vite is doing less work than Webpack, and letting the browser deal with the heavy lifting.

What do you think are the best alternatives to forking the libraries into separate repositories?

1. not do anything it at all - keep using the CJS version. This works today with both Webpack and Vite, but it requires preoptimizing/compatibility layers. The advantage of this approach is that it requires no work to be done (today).
2. leave the code like this PR, in the monolith repo. We can reuse the tooling, release cycle, config etc. But it also inflates the monorepo size and increases build times a little bit.
3. Rewrite parts of Storybook so that it's no longer depending on unmaintained dependencies. This takes more upfront work, but is probably better in the long term.
4. ...or any other solutions?

**Comment by ndelangen** [comment]
Ok, let's move forwards with this idea, but I propose not adding this package to the monorepo, instead creating a new repository in the storybook org.

**Comment by eirslett** [comment]
> Ok, let's move forwards with this idea, but I propose not adding this package to the monorepo, instead creating a new repository in the storybook org.

Yup. Here we go!
https://github.com/storybookjs/memoizerific

**Pull request closed without merging**
