### PR TITLE
Use haul/bin/cli.js for cross-platform support

### PR DESCRIPTION
**Pull request by danielkcz**
Issue: #2575 

## What I did

Changed path to Haul CLI instead of using `.bin` folder.

### CODE REVIEW

**Comment by FredyC** [comment]
It's kinda shame that this is not getting more attention as it's a rather annoying bug. Every time I install something with Yarn I have manually change dist files to keep it working. Not sure about failing tests, apparently not related to this change.

**Comment by Hypnosphi** [comment]
Why the old path don't work? I should be a symlink to the new one

**Comment by FredyC** [comment]
Well, Windows and symlinks ... I would say a long story :)

**Review by danielduan — APPROVED** [review]
looks good to me if this is just a change from using the simlinked bin file to the actual one.

@Hypnosphi is the chromatic test on CircleCI broken?

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Merge when ready

**Pull request merged**
