### PR TITLE
fix: Storybook does not respect BROWSER env var

### LINKED ISSUE #21343: [Bug]: Storybook does not respect BROWSER env var if default browser is not chromium based.
### Describe the bug

When using the environment variable BROWSER to configure the browser that storybook opens in, storybook will not respect this configuration if the users default browser is not set to a browser which the `@aw-web-design/x-default-browser` package does not resolve to either `chrome`, `chromium` or `com.brave.browser`.

#### Set the system default browser to something not based on chromium

eg: `safari`

#### Clone the reproduction repo

```bash
mkdir repo-test
cd repo-test
git clone https://github.com/thtliife/storybook-specify-browser-repro
```

#### Install dependencies

```bash
yarn
```

#### Run storybook with the BROWSER environment variable set to something other than the default system browser:

```bash
BROWSER=firefox yarn storybook
```

or create a .env file in the root of the project with the following contents:

```bash
BROWSER=firefox
```

then run storybook
```bash
yarn storybook
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.0 - ~/.tools/n/bin/node
    Yarn: 1.22.19 - ~/.tools/n/bin/yarn
    npm: 8.1.0 - ~/.tools/n/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.2
```

### Additional context

The problem is caused by the `open-in-browser` utility not passing args to `open` when the default browser is not chromium.

If the default browser is a chromium browser, `better-opn` is used which does its own evaluation of environment variables, allowing the BROWSER variable to be evaluated.

### PR DESCRIPTION
**Pull request by quiettide**
Storybook does not respect BROWSER env var if default browser is not chromium based.

Closes #21343

## What I did

This commit adds a check for the environment variable, and passes it to the `open` package as an argument if the specified browser is not chromium based.

Changes are in `code/lib/core-server/src/utils/open-in-browser.ts`

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Comment by thtliife** [comment]
erm, pull bot undid my changes? this no longer fixes anything

**Comment by tmeasday** [comment]
I've no idea what's going on here. I definitely didn't merge anything. And that commit points to an apparently unrelated @shilman commit...

**Comment by shilman** [comment]
What is the "pull" bot? Seems buggy to me

**Comment by thtliife** [comment]
@shilman Haha. It’s a bot that I had forgotten I had installed in my sccount. 
it’s supposed to keep forks up to date with their parent repos…
But it seemed to have been doing a git fetch —hard… 
Needless to say it’s no longer installed in my account 🤪

**Pull request merged**
