### PR TITLE
Addon-controls: Angular support

### PR DESCRIPTION
**Pull request by shilman**
Issue: #10583 #10956

## What I did

angular-controls

Partial support for angular:
- [x] scalar types
- [x] object/array types
- [x] enum types

## How to test

See `angular-cli` stories and added test cases

### CODE REVIEW

**Comment by matheo** [comment]
@shilman I may help with this, I just need to be able to build:watch and link the built package locally to my project without verdaccio, is it possible?

**Comment by shilman** [comment]
Thanks @matheo I'm almost done with this -- making a few last-minute tweaks and will merge/release in the next 1-2h. To try it out, follow the instructions in `CONTRIBUTING.md`, or TLDR is `yarn dev` in one window and `yarn storybook` in `examples/angular-cli`

**Comment by matheo** [comment]
Great news, I will test this out and help to fix any issue that I may find.
I'm checking at the `options` controls, great stuff available!

BTW, can we add `paramKey` to the Controls tab to disable it as any other panel?
I still wonder if it's possible to rename/reorder panels tho
Thanks for this!

**Comment by shilman** [comment]
@matheo i think this should behave just like any other addon. i haven't added any support for `enable` parameter, but otherwise you can play with it and see if it does what you need. gonna do a few touchups on #10953 and then merge/release after both CI pass

**Comment by matheo** [comment]
@shilman sounds good!
just to clarify, I'm talking about the missing `addPanel.paramKey`:
```diff
addons/controls/src/register.tsx

-import { ADDON_ID } from './constants';
+import { ADDON_ID, PARAM_KEY } from './constants';

addons.register(ADDON_ID, (api: API) => {
  addons.addPanel(ADDON_ID, {
    title: 'Controls',
    type: types.PANEL,
+    paramKey: PARAM_KEY,
```
to support `controls: { disable: true }` by default.

**Comment by shilman** [comment]
@matheo Aha, didn't know about `paramKey`--thanks for the heads up. Fixed & will merge/release soon 🤞

**Comment by shilman** [comment]
Self-merging @tmeasday

**Pull request merged**
