### PR TITLE
fix(addon-storysource): use global CLIENT_API instead of injecting .addDecorator

### PR DESCRIPTION
**Pull request by Everettss**
Add `window.__STORYBOOK_CLIENT_API__` at the top of the file instead of adding .addDecorator with estraverse.

Originally this PR is intended to fix issue #4039. But I decided to use global [`__STORYBOOK_CLIENT_API__`](https://github.com/storybooks/storybook/pull/3058) and it fixes also other problems with renaming `storiesOf` function.

### CODE REVIEW

**Comment by ndelangen** [comment]
@igor-dv could you take a look at this?

**Comment by igor-dv** [comment]
Sure. Will check this today. 
Also, there is this #4012 PR that adds some functionality to storysource.

**Comment by igor-dv** [comment]
@Everettss, sadly but `__STORYBOOK_CLIENT_API__`, is not a good solution, because it adds decorators to the `globalDecorators` list. 
That means every new story that is declared, adds its storysource to the list of `globalDecorators`, then this list is copied to the list of the story's decorators:

image

image

image

The first story that is imported, will have `x` decorators, then the story number `100`, will have `x + 100` decorators, and it's definitely not a good thing.

I have tested this with the `@storybook/html`  [preview](https://deploy-preview-4079--storybooks-html.netlify.com) from this PR, and here is the visualization of the problem:

storysource-bug

**Comment by ndelangen** [comment]
@igor-dv how do we proceed with this?

**Comment by Everettss** [comment]
@ndelangen give me 1 or 2 weeks (I'm on vacation now) an I will search for some replacement or simply admit that this is only worth burying.

**Comment by ndelangen** [comment]
@Everettss

I'm absolutely not trying to pressure you, please don't feel as if you're required to do anything. You're not.

I'll leave it open, the bot will come along in a few weeks and remind us, and then close it automatically.

If you need help, please do reach out to us 🙇

**Comment by ndelangen** [comment]
debatable whether it's a bug or feature, doesn't really matter IMHO

**Comment by ndelangen** [comment]
@Everettss Let's have a chat on slack or discord about this, I have some ideas!

**Comment by ndelangen** [comment]
Storysource should add it's data about stories via addParameters, I think this will pretty much solve all problems.

**Comment by igor-dv** [comment]
I am going to close this. We will adjust storysource anyway.

**Pull request closed without merging**
