### PR TITLE
Core: Remove manager redirects on boot

### PR DESCRIPTION
**Pull request by tmeasday**
Issue: Weird `setTimeout(..,1)` navigations in manager url module.

The reason was previously we used the manager URL to drive the story selection.

Now we simply use the storyId, which can be a prefix. We don't need to change the URL until the preview emits the `CURRENT_STORY_WAS_SET` event (at which point the manager sets the path).

## What I did

Dropped the redirects. Fixed up the support for legacy URLs.

## How to test

See tests.

Try the following URLs in official SB:

 - http://localhost:9011/ 
 - http://localhost:9011/?random-stuff=that-should-be-stripped
 - http://localhost:9011/?path=/story/addons-controls--basic
 - http://localhost:9011/?selectedKind=addons-actions&selectedStory=arg-types-example
 - http://localhost:9011/?selectedKind=addons-actions

### CODE REVIEW

**Review by shilman — APPROVED** [review]
AWESOME!!!

**Review by shilman — CHANGES_REQUESTED** [review]
@tmeasday can you check out the chromatic changes? am able to repro locally but not sure why they are caused by this PR

**Review by ndelangen — APPROVED** [review]
👏

**Comment by shilman** [comment]
@tmeasday `examples` failing to build 🙈

**Comment by tmeasday** [comment]
@ndelangen note that the error came from the `extract` script with non-serializable args (see https://github.com/storybookjs/storybook/pull/11390/commits/81e0be17b3a4c8f7f0dee346cbb7ad9ffeecc68d). 

I guess it uses `JSON.stringify`. It doesn't look like `telejson` has this issue as I don't see errors for this story in official-SB.

cc @shilman

**Pull request merged**
