### PR TITLE
UI: Fix panel layout resizing do not apply when done too fast

### LINKED ISSUE #25759: [Bug]: Resizing of Storybook Panel doesn't always apply
### Describe the bug

**Project**: Bitwarden (Angular)
**Version**: 8.0.0-alpha.13
**Bug/feedback**: Resizing of Storybook Panel doesn't always apply
**Tested Browser**: Edge (but also encountered it in Chrome a while ago)

When the panel is resized fast, the changes aren't always applied:

https://github.com/storybookjs/storybook/assets/5889929/73c3edf4-40bd-41a7-abda-887ffbb2c60f

### To Reproduce

1. Go to https://stackblitz.com/edit/github-t8esdj?file=.storybook%2Fmanager.jsx
2. Open the `Primary` Button Story.
3. Try to resize the Storybook Panel fast

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jorge-ji**
Closes #25759

## What I did
Fixed resizing of panel not applying when done too fast.
The fix was done by changing a comparison condition in "useLayoutEffect()". Instead of using a variable ("prevManagerLayoutStateRef") that was also modified by another function ("useEffect()") that could execute at the same time, it now uses a variable that is only modified by the own function, ensuring that the supposed layout values are not changed after they are set.

https://github.com/storybookjs/storybook/assets/133528288/35c4ebcb-2549-4bcd-97e3-471ec30042cd

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

1. Run the default sandbox `yarn start`
2. Try to resize any panel quickly

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by jorge-ji** [comment]
@ndelangen , hello, sorry to bother, but I'm a bit confused with what the check errors are.

**Review by JReinhold — APPROVED** [review]
I can't really reproduce the original issue with or without this patch, but I trust that this fixes it. At least I can confirm that it doesn't break anything based on my testing.

Thanks. ❤️

**Review by JReinhold — CHANGES_REQUESTED** [review]
Maybe I was wrong, it appears that this breaks the keyboard shortcuts for toggling the sidebar/addon panel/fullscreen, as is also evident by the failing e2e tests.

It's not about the keyboard though, using the menu dropdown to toggle doesn't work either.

I think it's because of the added state to the dependency array.
If you toggle the layout via keyboard it will update the manager layout state. This will now trigger this `useLayoutEffect`, which will immediately set the manager layout state back to what it was initially.

**Comment by jorge-ji** [comment]
Sorry for the delay, I believe that fixes the broken toggles, all e2e tests are also passing. I'm not sure why test-portable-stories-svelte is failing, hopefully it's not due to the changes.

**Review by JReinhold — APPROVED** [review]

**Pull request merged**
