### PR TITLE
Addon-docs: Make babel-loader an optional peer dependency

### PR DESCRIPTION
**Pull request by IanVS**
Issue:

## What I did

The webpack `babel-loader` was listed as a dependency of `addon-docs`, and a required peer dependency of `renderers/vue` and `renderers/vue3`.  Since all of these can be used with vite, which does not require `babel-loader`, I've moved them to optional peer dependencies.  

I suggest that if necessary, `babel-loader` could be added as a dependency or peer dependency of the webpack frameworks if we want to ensure that it's available for addons.

## How to test

- CI

### CODE REVIEW

**Comment by yannbf** [comment]
Thanks @IanVS ! Seems like @ndelangen has an interesting idea, can you please discuss with him and possibly @shilman ?

**Comment by ndelangen** [comment]
I think we should not have more peerDependencies, they do not actually fix the issue.

What we should do instead is have the reference to the babel loader come from a preset, probably the builder.

If the builder depends on `babel-loader` it could do something like this:
```ts
// builder/preset.js

export const babelLoaderRef = () => require.resolve('babel-loader');
```

**Comment by IanVS** [comment]
I think that could work for this case, but it would also be great if we could find a more general solution.  I'm hitting the same kind of issue in https://github.com/storybookjs/addon-svelte-csf/pull/72, where `svelte-loader` and `@sveltejs/vite-plugin-svelte` are only needed in one builder or the other.  They can perhaps reasonably be expected to exist in a project already, so peer deps might work, but I agree with you that they're a tire fire and can cause more problems than they solve sometimes.

**Comment by IanVS** [comment]
The CLI has a concept of `extraPackages`.  I wonder if we could get away with using peerDependencies and adding them into that array to be sure that they're installed in the project.

**Comment by ndelangen** [comment]
@IanVS I expanded upon my comment, maybe you hadn't seen it / got no notification, so just doing a ping here, in case.

**Comment by IanVS** [comment]
@ndelangen do you envision we would follow this pattern for any and all dependencies that are specific to one of the builders for all addons, or just for babel-loader?

**Comment by IanVS** [comment]
I suppose the other option is to publish a webpack version and a vite version of such addons.  They could have some common functionality shared between then, but publish separate packages with different dependencies and exports.  It would be a shame, but might be the cleanest way to avoid the extra dependencies.

**Comment by benmccann** [comment]
At least for Svelte, a project won't work without `vite-plugin-svelte` or `svelte-loader`, so I wouldn't worry too much about having them as a peer dependency as the user will already have one installed

**Comment by IanVS** [comment]
We discussed this, and decided to take the approach of adding `babel-loader` as a dependency of `@storybook/builder-webpack`, and exposing its location on disk via `require.resolve()` as Norbert suggested above.  It's not a general solution, but it might be a way to get us out of this particular hurdle, and we can see how well it works and whether it might be an approach we could use for other dependencies as well.

**Comment by IanVS** [comment]
I also removed `@babel/preset-env` and `lodash` from `addon-docs`, since they appear to be unused.

**Review by shilman — APPROVED** [review]
LGTM! thanks for your patience @IanVS and help @ndelangen ❤️

**Pull request merged**
