### PR TITLE
Remove polymer-cli dependency

### PR DESCRIPTION
**Pull request by ndelangen**
It should be used in a full example, but the polymer-cli isn't used by us, and installs gigabytes of dependencies..

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM thanks!

**Review by Hypnosphi — APPROVED** [review]

**Comment by Hypnosphi** [comment]
Not related to the PR, but why don't we have `build-storybook` command for polymer?

**Comment by shilman** [comment]
@Hypnosphi  we do 

```
    "build-storybook": "./bin/build.js",
```

**Comment by Hypnosphi** [comment]
I mean, for the example: https://github.com/storybooks/storybook/blob/dcf287adf7338bbe30e9f38bec3789953801b067/examples/polymer-cli/package.json#L5-L6

**Comment by Hypnosphi** [comment]
@ndelangen can you please remove this dep from CLI fixture as well? It slows down CLI test significantly

**Comment by ndelangen** [comment]
@Hypnosphi I'm not seeing the dependency anywhere else..

**Pull request merged**
