### PR TITLE
Provide a configuration option to limit the number of actions logged

### PR DESCRIPTION
**Pull request by jcharry**
Issue: The actions logger panel accumulates actions for a story endlessly. After a while, this creates quite a bit of lag. You can hit the clear button to clear out the logger and performance improves again, but it'd be nice to have a configuration hook to set a hard upper bound on the number of actions that should be logged.

## What I did
Added a configuration option called `limit` to the `configureActions` call.

### CODE REVIEW

**Comment by rhalff** [comment]
A default limit could probably be added to [configureActions]( https://github.com/jcharry/storybook/blob/fa075796a83efda1f4c1874a0ff3d0aa4d71c5a9/addons/actions/src/preview/configureActions.js#L2), not sure what the default value should be though.

I've added @Hypnosphi as reviewer, does the PR also need to include an example in the `official-storybook`?

**Comment by danielduan** [comment]
I think we should set a sensible default for all users while we're making this change. This seems like an obvious optimization we can make on behalf of users.

does 50 sound like a good number?

**Comment by Hypnosphi** [comment]
> does the PR also need to include an example in the `official-storybook`?

Yeah, that wouldn't hurt

> I think we should set a sensible default for all users while we're making this change. This seems like an obvious optimization we can make on behalf of all users.
>
> does 50 sound like a good number?

Makes sense to me

**Review by danielduan — APPROVED** [review]

**Comment by danielduan** [comment]
@jcharry can you fix the failing test here?

`yarn bootstrap --core` and then `yarn test --core --update`

**Comment by Hypnosphi** [comment]
Please add an example to `example/official-storybooks`

**Comment by jcharry** [comment]
@Hypnosphi Okay, added an example.

**Comment by jcharry** [comment]
Rebased and should be good to go now.

**Pull request merged**
