### PR TITLE
UI: Use Color In Theme

### PR DESCRIPTION
**Pull request by jikwan0327**
## What I did

I have assigned the colors defined in the 'base.ts' theme variable instead of directly specifying colors.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@jikwan0327 appreciate you taking the time to put together this pull request. We appreciate it 🙏 ! @cdedreuille can you follow up with the contributor and provide some context on this situation, why the colors were hardcoded. Thanks in advance.

**Comment by cdedreuille** [comment]
Hi. I'm not sure what you are trying to solve with this PR. Can you describe what was the problem you were trying to solve? We are in the process of building a new theming process so as much as possible I would try not to change anything right now unless there's an explicit problem to solve.

**Comment by jikwan0327** [comment]
At the bottom, color used the value in the color variable. However, the part that corresponds to the code I changed has color in the color variable, but I felt uncomfortable that only that part was hardcoded. I think this could harm maintenance in the future.

**Comment by cdedreuille** [comment]
We are working on a new Theming API so I would not try to push any update to the existing API right now. I'll close this PR for now and share any updates about it on Discord.

**Pull request closed without merging**
