### PR TITLE
UPGRADE telejson

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: telejson was using a package not suited for browsers, that has been removed

### CODE REVIEW

**Comment by shilman** [comment]
@Hypnosphi Mind taking a look at this? If it's correct and straightforward to undo your workarounds for this, let's try to get it done ASAP so we can get it out as part of 5.0! Thanks! 🙇

**Comment by Hypnosphi** [comment]
Everything works after reverting, thanks

**Comment by shilman** [comment]
Thanks @Hypnosphi! Will get this into the next RC 🙇

**Review by shilman — APPROVED** [review]
LGTM

**Pull request merged**
