### PR TITLE
Fix #6077: issue with selectedPanel reset

### LINKED ISSUE #6077: Addon Panel resets on story change
**Describe the bug**
When using actions, knobs and a11y, switching between stories, the selected addon tab is reset to actions tab.

**To Reproduce**

1. Have actions, a11y and knobs installed and configured
1. Click on a story
1. select the a11y tab
1. select another story
1. See that the selected tab is now actions

**Expected behavior**
last selected tab should remain selected and active.

if i had a11y selected, it should remain selected but updated with info about newly selected story.

**Screenshots**
2019-03-14!UNITO-UNDERSCORE!10-29-58

**System:**

* OS: Windows10 (but our storybook runs in docker)
* Device: n/a
* Browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Framework: React
* Addons: Actions, A11y, Knobs
* Version: 5.0.1

**Additional context**

**`package.json`**

```
...
  "dependencies": {
    "@babel/core": "7.2.2",
    "@babel/polyfill": "^7.0.0",
    "@storybook/react": "5.0.1",
    "@storybook/addon-actions": "5.0.1",
    "@storybook/addon-knobs": "5.0.1",
    "@storybook/addon-links": "5.0.1",
    "@storybook/addon-storysource": "5.0.1",
    "@storybook/addon-a11y": "5.0.1",
    "storybook-host": "5.0.3",
    "storybook-addon-jsx": "6.0.0",
    "axios": "^0.18.0",
    "babel-loader": "8.0.5",
    "babel-plugin-require-context-hook": "1.0.0",
    "eslint": "^5.5.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-prettier": "^2.6.2",
    "eslint-plugin-react": "^7.11.1",
    "formstate": "^1.0.2",
    "gatsby": "2.1.14",
    "gatsby-cli": "2.4.11",
    "gatsby-image": "^2.0.29",
    "gatsby-plugin-manifest": "^2.0.18",
    "gatsby-plugin-offline": "^2.0.24",
    "gatsby-plugin-react-helmet": "^3.0.6",
    "gatsby-plugin-sharp": "^2.0.21",
    "gatsby-source-filesystem": "^2.0.21",
    "gatsby-plugin-sass": "2.0.10",
    "gatsby-transformer-sharp": "^2.1.14",
    "gatsby-plugin-alias-imports": "1.0.5",
    "history": "^4.7.2",
    "lodash": "^4.17.11",
    "localstorage-ponyfill": "1.0.2",
    "mobx": "^5.1.0",
    "mobx-react": "^5.2.8",
    "npm-run-all": "4.1.5",
    "node-sass": "4.11.0",
    "onchange": "5.2.0",
    "prettier": "^1.14.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-helmet": "5.2.0",
    "react-error-overlay": "5.1.3",
    "semantic-ui-react": "^0.84.0",
    "require-context.macro": "1.0.4",
    "webpack": "4.29.5",
    "style-loader": "0.23.1",
    "css-loader": "2.1.0",
    "sass-loader": "7.1.0",
    "color": "3.1.0"
}
...
```

### PR DESCRIPTION
**Pull request by malykhinvi**
Issue: #6077 

## What I did
Added check for `options.selectedPanel` presence, so that if it is `undefined` it won't reset the currently selected panel.

## How to test
- Is this testable with Jest or Chromatic screenshots? **Yes, I added unit tests**
- Does this need a new example in the kitchen sink apps? **No**
- Does this need an update to the documentation? **No**

### CODE REVIEW

**Review by shilman — APPROVED** [review]
LGTM and great job on the test cases 👌 Thanks so much for taking care of this!

**Comment by malykhinvi** [comment]
I see a conflict, looks like `layout.js` has been moved to `lib/api/src/modules/layout.ts`, but test is left untouched. Do you want me to move `layout.test.js` to `lib/api/src/modules/tests` to resolve conflict?

**Comment by shilman** [comment]
@malykhinvi yes please! 🙏

**Comment by malykhinvi** [comment]
@shilman done!

**Pull request merged**
