### PR TITLE
Fix: virtual modules excluded for babel-loader

### LINKED ISSUE #22300: [Bug]: Stories glob incorrectly matching test files
### Describe the bug

From Discord https://discord.com/channels/486522875931656193/1090840732945891328/1090840732945891328

I have a single stories.tsx file currently. If I include the story directly, all is well. If however, I switch to a wildcard glob (../src/components/**/*.stories.@(ts|tsx)), SB crashes because it's trying to include my *.test.tsx files, which are not *.stories.tsx.  I tested the babel config and it's ignoring the test files.

Example error:

```
ModuleParseError: Module parse failed: Unexpected token (8:11)
File was processed with these loaders:
 * ../../node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| describe('EzAlert', () => {
|   it('should meet accessibility guidelines for status messages', async () => {
>     render(<EzAlert headline="A11y" use="info" />);
|     expect(await axe(await screen.findByRole('status'))).toHaveNoViolations();
|   });
    at handleParseError (/Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:741:23)
    at /Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:843:9
    at processResult (/Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:597:14)
    at /Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:646:9
    at /Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:368:5
    at iterateNormalLoaders (/Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:213:12)
    at iterateNormalLoaders (/Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:217:12)
    at /Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:229:5
    at context.callback (/Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:116:16)
    at /Users/norandabrown/Projects/recipe/node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js:37:73
```

Version: 7.0.0-rc.10 using react-webpack5
Repo: https://github.com/ezcater/recipe/blob/nb/storybook-7-upgrade/packages/recipe/.storybook/main.ts#L37

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes #22300

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
Seems like the right approach! Do we need to do similar for Vite do you think?

**Comment by ndelangen** [comment]
@tmeasday I don't know if vite suffers from the same problem, I though it didn't..
So I think, doing the same for vite isn't needed.

I was thinking that maybe there would be a need to add some sort of loader for ONLY these entries, possibly an `esbuild-loader` or something.

It seems though that it's not needed, considering the sandboxes are working?!

**Comment by tmeasday** [comment]
> It seems though that it's not needed, considering the sandboxes are working?!

I think that's right. As I said, it's very simple handwritten JS. I guess we just need to be slightly careful we don't use any advanced JS in there, but I think by the nature of being JS (not TS) that's not likely.

> @tmeasday I don't know if vite suffers from the same problem, I though it didn't..
> So I think, doing the same for vite isn't needed.

I guess Vite is not going to suffer from this exact problem (the stripped comment is for webpack after all), so I guess you are right.

**Comment by ndelangen** [comment]
I marked this ready for review then.

**Review by tmeasday — APPROVED** [review]

**Pull request merged**
