### PR TITLE
Add a `shallowSnapshot` option for storyshots `test` functions

### PR DESCRIPTION
**Pull request by heinzmuller**
Issue: #995 StoryShots doesn't have a preset for shallow rendering snapshots

## What I did
Added a test body for shallow rendering snapshots

## How to test
Add this as a storyshot test file 
```
import initStoryshots, { shallowSnapshot } from '@storybook/addon-storyshots'

initStoryshots({
  test: shallowSnapshot
})
```

### CODE REVIEW

**Comment by ndelangen** [comment]
Can you explain why you'd want to shallow render stories? Is this something people want to do?

**Comment by heinzmuller** [comment]
I can only speak for myself, but when you have huge library of smaller react components, if you don't do shallow rendering you will get huge snapshot mismatches when you change those components. Granted that snapshot tests are really easy to update, but when you have large mismatches it is also increases the likelihood that you miss a real error.

And secondly when you shallow render, it makes it that more important to make sure you have tests for all components.

**Comment by ndelangen** [comment]
@tmeasday Can you review this?

**Review by tmeasday — COMMENTED** [review]
Works great, Thanks @heinzmuller !

**Review by tmeasday — APPROVED** [review]

**Pull request merged**
