### PR TITLE
Vue3: Fix SourceDecorator Exception 

### LINKED ISSUE #25523: [Bug]:  decodeEntities option is required in browser builds
### Describe the bug

While stories render fine, the following error is thrown in the dev console:

```plain
error Error: [@vue/compiler-core] decodeEntities option is required in browser builds.
    at baseParse (compiler-core.esm-bundler.js:2586:1)
    at getComponents (entry-preview-docs.mjs:8:1)
    at getTemplateComponents (entry-preview-docs.mjs:8:1)
    at generateSource (entry-preview-docs.mjs:8:1)
    at immediate (entry-preview-docs.mjs:8:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at job (runtime-core.esm-bundler.js:1827:1)
    at doWatch (runtime-core.esm-bundler.js:1858:1)
    at watch (runtime-core.esm-bundler.js:1716:1)#
```

### To Reproduce

not sure I can provide this… :grimacing: 

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.2 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.0 - /tmp/xfs-38cf59af/node
    Yarn: 4.0.2 - /tmp/xfs-38cf59af/yarn <----- active
    npm: 10.2.3 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: 7.6.7 => 7.6.7 
    @storybook/addon-essentials: 7.6.7 => 7.6.7 
    @storybook/addon-links: 7.6.7 => 7.6.7 
    @storybook/vue3: 7.6.7 => 7.6.7 
    @storybook/vue3-webpack5: 7.6.7 => 7.6.7 
    eslint-plugin-storybook: 0.6.15 => 0.6.15 
    storybook: 7.6.7 => 7.6.7
```

### Additional context

Might be related to / duplicate of #25496.

Searching for `decodeEntities` in the Storybook documentation yields no results:

storybook js org_

### PR DESCRIPTION
**Pull request by chakAs3**
Closes #25523

## What I did

i passed a basic decodeEntities to baseParse, it became required in latest versions of Vue 

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
Can we test this? Is the change backwards compatible with older versions of Vue3?

**Comment by chakAs3** [comment]
> Can we test this? Is the change backwards compatible with older versions of Vue3?

we can only test it visually cause it is a source snippet, this worked with the older version, with latest version is throwing an exception in runtime only, the source viewer not showing the expected source.

decodeEntities was optional in older versions so i don't think will break

**Comment by Saurabhmagicsw** [comment]
hello all, please review and merge, I need this fix

**Review by kasperpeulen — APPROVED** [review]
LGTM

**Comment by MisterIsaak** [comment]
@chakAs3 @kasperpeulen , any chance this can get merged? Looks like it's good to go unless there's discussions/concerns elsewhere.

**Comment by kasperpeulen** [comment]
Merged!

**Comment by YUN-RU-TSENG** [comment]
I still have same issue `error Error: [@vue/compiler-core] decodeEntities option is required in browser builds.` , I install storybook today, should i update version? my storybook version is 

    "@storybook/addon-essentials": "^7.6.17",
    "@storybook/addon-interactions": "^7.6.17",
    "@storybook/addon-links": "^7.6.17",
    "@storybook/blocks": "^7.6.17",
    "@storybook/test": "^7.6.17",
    "@storybook/vue3": "^7.6.17",
    "@storybook/vue3-vite": "^7.6.17",

**Comment by kasperpeulen** [comment]
It is only fixed in 8.0 @YUN-RU-TSENG

**Comment by YUN-RU-TSENG** [comment]
thanks, i will update to 8.0 @kasperpeulen

**Pull request merged**
