### PR TITLE
Remove babel-preset-vue

### PR DESCRIPTION
**Pull request by graup**
Issue: #4475

## What I did

- Removed all references to outdated `babel-preset-vue`
  - from app/vue
  - from docs
  - from tests
- Removed jsx stories from cli generator. **Storybook+vue does not support JSX out-of-the-box anymore**
- For kitchen-sink example, include `@vue/babel-preset-jsx` to enable jsx stories
- Added instructions to MIGRATION.md

## Rationale

- `babel-preset-vue` is old. Several people have documented in #4475 why it should be removed. 
- JSX isn't very common in Vue land
- Vue users who care about JSX likely have their own setup (e.g. using `@vue/babel-preset-jsx`) already in place. Since we can just pick up the user's babel config, I think it's fine to drop JSX-out-of-the-box support for Vue.

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
Looks good!

**Review by shilman — APPROVED** [review]
LGTM!

**Comment by shilman** [comment]
@Aaron-Pool @yannbf @tooppaaa can you guys take a quick look? we're removing built-in support for vue JSX with this one... sound ok to you?

**Review by tooppaaa — APPROVED** [review]

**Comment by Aaron-Pool** [comment]
Yeah, I would say anyone who's wanting to use Vue jsx should be comfortable configuring their Babel setup for it themselves 👍

**Pull request merged**
