### PR TITLE
Addon-docs: Vue SFC support in MDX

### PR DESCRIPTION
**Pull request by visualjerk**
Issue: https://github.com/storybookjs/storybook/issues/9768

## What I did

I added a transformer for Vue stories written in SFC syntax:

``````mdx
<Story name="to storybook" height="300px">
  ```vue
  <template>
    <button>click me {{ name }}</button>
  </template>
  <script>
    export default {
      data() {
        return {
          name: 'foo'
        }
      }
    }
  </script>
  ```
</Story>
``````

## How to test

- Is this testable with Jest or Chromatic screenshots?
Yes, I added two snapshot tests for stories written in SFC syntax.

- Does this need a new example in the kitchen sink apps?
Yes, I added an example in the vue kitchen sink (Addon > Docs > SFC Syntax).

- Does this need an update to the documentation?
No / I cannot find the right place to put it.

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
cc @Aaron-Pool

**Comment by graup** [comment]
I'm not very familiar with mdx yet. Is there a standard/precendent for this ` ```vue ... ` string? It looks a bit odd to me. If there isn't, maybe we should coordinate with [@mdx-js/vue-loader](https://github.com/mdx-js/mdx/tree/master/packages/vue-loader) to add that there first.

Does syntax highlighting work with this?

**Comment by visualjerk** [comment]
@shilman Is there any way I can assist with

**Comment by visualjerk** [comment]
Closed by mistake 😄

**Comment by shilman** [comment]
So so incredibly sorry for dropping the ball on this. We're getting close to MDXv2 (currently in RC) that supports Vue natively, and I think we can re-evaluate this feature when we upgrade Storybook. Closing this for now.

**Pull request closed without merging**
