### PR TITLE
Using svg-url-loader for webpack configs that accept svgs

### PR DESCRIPTION
**Pull request by wuweiweiwu**
Issue: #2474 

## What I did
Added `svg-url-loader` to make svg imports smaller

## How to test
build core, docs, examples

Is this testable with jest or storyshots?
No
Does this need a new example in the kitchen sink apps?
No
Does this need an update to the documentation?
No
If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Can someone please check that it works on #3148 branch?

**Comment by wuweiweiwu** [comment]
Sure Ill do that in a bit!

**Comment by wuweiweiwu** [comment]
@Hypnosphi I can just wait until that one is merged!

**Comment by wuweiweiwu** [comment]
@Hypnosphi It worked! :) 

except some stuff with webpack 4 that I had to add:

uglifyjs is its own plugin in webpack 4 `yarn add -D  uglifyjs-webpack-plugin`
`webpack` command is now in its own cli `yarn add -D webpack-cli`

But other than that It works.

**Comment by Hypnosphi** [comment]
uglifyjs is its own plugin in webpack 4 `yarn add -D uglifyjs-webpack-plugin`

Actually, it's used as default `optimization.minimizer` option in webpack 4, so there's no need to depend on it directly

**Comment by wuweiweiwu** [comment]
@Hypnosphi My mistake. I was directly running `yarn build` in the `vue-kitchen-sink` directory. 

Is there anything else to be done on this PR?

**Comment by wuweiweiwu** [comment]
Seems like danger ci has no api token

**Comment by Hypnosphi** [comment]
Looks like it broke image in polymer example: https://deploy-preview-3221--storybooks-polymer.netlify.com/?selectedKind=Welcome&selectedStory=Welcome&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by wuweiweiwu** [comment]
@Hypnosphi seems that `noquotes` breaks polymer svg imports. But for others it doesnt. So I've removed it

**Review by danielduan — APPROVED** [review]

**Pull request merged**
