### PR TITLE
WIP: Add element highlight to addon interactions

### PR DESCRIPTION
**Pull request by yannbf**
Issue: N/A

## What I did

Applied the great work from @mikewoudenberg into the codebase. Thanks a lot for doing this!!

image

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

## TODO
- [ ] Only show the highlight button for valid elements (e.g. hide from `expect(true).toBe(true)` calls)
- [ ] Change highlight logic to be independent from addon-a11y
- [ ] Likely more things, gotta think!

### CODE REVIEW

**Comment by ndelangen** [comment]
@yannbf where is this PR going?

How does this relate to the highlight addon that was added recently by @winkerVSbecks ?

**Comment by yannbf** [comment]
Now that the highlight addon is merged, we can finally proceed with this PR and can use Thad addon instead of the a11y one:

```this.channel.emit('storybook/a11y/highlight', ...)```

And additionally we need to discuss the designs with @MichaelArestad

**Comment by ndelangen** [comment]
Thank you for the update @yannbf

**Comment by yannbf** [comment]
Closing this in favor of #18700!

**Pull request closed without merging**
