### PR TITLE
Chore: Update snippet to address issue #12695

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pull request the issue #12695 is addressed and can be closed.

What was done:
- Adjusted the snippet per @shilman's feedback [here](https://github.com/storybookjs/storybook/issues/12695#issuecomment-712954857) and adjusted accordingly.
- Tested it locally against a Storybook based of React TypeScript and the issue is no longer present.

Feel free to provide feedback

### CODE REVIEW

**Comment by marko-knoebl** [comment]
Nice approach with ComponentProps.

With this exact code I would now get a type error in the last statement of the code example:

```js
FirstStory.args = ...
```

It says "Property 'args' does not exist on ..."

this would get rid of that error for me:

```tsx
import React, { ComponentProps } from "react";
import { Story } from "@storybook/react/types-6-0";
// ...
const Template: Story<ComponentProps<typeof YourComponent>> = (args) => (
    <YourComponent {...args} />
);
```

**Comment by jonniebigodes** [comment]
@marko-knoebl Thank you for taking a look at the pull request. Let me check on my end and move from this. Do you mind waiting a bit?

**Comment by shilman** [comment]
yep @marko-knoebl's suggestion LGTM

**Review by ndelangen — APPROVED** [review]

**Comment by jonniebigodes** [comment]
@marko-knoebl thanks for the suggestion, i'm more than ok and updated the pull request with it. Thank you for the suggestion and the time to take a look at this. Really appreciate it.

Stay safe

**Review by shilman — APPROVED** [review]
💯

**Pull request merged**
