### PR TITLE
Update angular example to v8

### PR DESCRIPTION
**Pull request by kroeder**
Issue:

## What I did

Updating our angular example to the latest version

### CODE REVIEW

**Comment by kroeder** [comment]
Can't proceed with this before we don't upgrade to node 10 in our CI
Angular 8 requires `>= node 10`

**Comment by kroeder** [comment]
Waiting for #8173

**Comment by ndelangen** [comment]
@kroeder Hope this helps 🙏

**Review by shilman — APPROVED** [review]
🎉

**Pull request merged**
