### PR TITLE
Update glob to v10.0.0

### PR DESCRIPTION
**Pull request by NotWoods**
## What I did

Updated the `glob` library to v10, which includes a promise-based API and a min version of Node 16. Also removed the no longer needed glob-promise library.

## How to test

This updates the logic for listing stories in a vite project. To test:

1. Run a sandbox for template, e.g. `yarn task --task sandbox --start-from auto --template react-vite/default-ts`
2. Open Storybook in your browser
3. Check that all expected stories are displayed.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@NotWoods I'll update this branch with the base-branch.

Can you investigate the unit-test failures?

**Comment by NotWoods** [comment]
Which check does the unit test failures appear under?

**Comment by ndelangen** [comment]
ah never mind, might have been inconsistent. I'll get this updated, and merged.

**Comment by blowsie** [comment]
This change [broke some things...](https://github.com/storybookjs/storybook/pull/22327)
Is there an open issue for it or just the PR?

**Comment by zoontek** [comment]
Having `glob@^10.0.0` as dependency broke a lot of CI CLI tools, including `eslint`: https://github.com/eslint/eslint/discussions/17215#discussioncomment-5985393

A solution could be to switch to [`fast-glob`](https://github.com/mrmlnc/fast-glob). I can do the PR if required.

**Comment by ndelangen** [comment]
@JReinhold Didn't your PR address this problem?

**Comment by koni1234** [comment]
> Having `glob@^10.0.0` as dependency broke a lot of CI CLI tools, including `eslint`: [eslint/eslint#17215 (reply in thread)](https://github.com/eslint/eslint/discussions/17215#discussioncomment-5985393)
> 
> The last safe version of `glob` is the `10.1.0` (as `10.2.0` starts to rely on the package `jackspeak`) (from this commit [isaacs/node-glob@94a36ce](https://github.com/isaacs/node-glob/commit/94a36ce995727fcbef8318977832e75e305786ed))
> 
> A solution could be to switch to [`fast-glob`](https://github.com/mrmlnc/fast-glob). I can do the PR if required.
> 
> EDIT: The author of `glob` (and of `npm`) said it's an issue with `yarn` and say the issue is to switch to npm: [isaacs/node-glob@94a36ce#commitcomment-122320956](https://github.com/isaacs/node-glob/commit/94a36ce995727fcbef8318977832e75e305786ed#commitcomment-122320956)
> 
> Not sure that's a realistic solution.

I agree, with storybook 7.3 and 7.4 using yarn i have the same problems ... eslint and webpack scripts are broken

**Comment by shilman** [comment]
@zoontek @koni1234 WDYT about using yarn resolutions to pin the version to 10.1.0? I created a PR to try to pin it in SB but @tmeasday mentioned that we have indirect dependencies on it that we can't control, so I closed it. https://github.com/storybookjs/storybook/pull/24002

@zoontek I'd be up for a `fast-glob` replacement. If you could create a PR for that, we could test it out and see whether it works well.

**Comment by tmeasday** [comment]
Replacing with `fast-glob` doesn't help either due to the indirect dependencies. Unless we also fork all the packages that depend on glob themselves

**Comment by shilman** [comment]
@yannbf is it possible to catch this error & tell users to pin their dependencies?

**Comment by IanVS** [comment]
FWIW, I took a stab at replacing globby with fdir [a while back](https://github.com/storybookjs/storybook/pull/19297#issuecomment-1680621380), for compatibility and performance reasons.  It looks like fdir has been improved further since then, and I plan to take another shot at it, though it sounds like that's insufficient due to transitive deps.

**Comment by koni1234** [comment]
> @zoontek @koni1234 WDYT about using yarn resolutions to pin the version to 10.1.0? I created a PR to try to pin it in SB but @tmeasday mentioned that we have indirect dependencies on it that we can't control, so I closed it. #24002
> 
> @zoontek I'd be up for a `fast-glob` replacement. If you could create a PR for that, we could test it out and see whether it works well.

yes, in order to temporary solve this issue I added these dependencies resolutions in the package.json


  "resolutions": {
    "strip-ansi": "^6.0.1",
    "string-width": "^4.2.2",
    "wrap-ansi": "^7.0.0"
  },

**Comment by tmeasday** [comment]
@koni1234 you only need to pin `jackspeak` as documented: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092

**Pull request merged**
