### PR TITLE
Angular: Fix issue if BrowserAnimationsModule is imported

### PR DESCRIPTION
**Pull request by valentinpalkovic**
Issue: N/A

If `BrowserAnimationModule` was used, the Story was not usable because `BrowserModule` is in place and using both modules in parallel is not allowed. Therefore we have to tell Angular while `boostrapApplication` to spin up an environment, where Animations are enabled.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

### CODE REVIEW

**Review by shilman — COMMENTED** [review]
@valentinpalkovic This looks good, but can you please explain more about how to test it? If I tried your example on a previous SB7 beta, would it fail? Thanks in advance for the clarification!

**Comment by valentinpalkovic** [comment]
If you try to use the `BrowserAnimationModule` in the imports section of moduleMetadata, it will break in previous versions. For example here: https://github.com/storybookjs/storybook/pull/20709/files#diff-eab273740d3db246f7c17bb91c2f9750cb5b9de9fd4da6e8e2e238bc39d1591bR18

**Comment by valentinpalkovic** [comment]
@shilman Just copy over the Stories and the Dummy components and it should fail in previous betas.

**Review by sheriffMoose — APPROVED** [review]
Amazing work @valentinpalkovic , I just verified the changes on my end. Good catch 👍

**Pull request merged**
