### PR TITLE
Add support for custom `react-scripts` packages

### PR DESCRIPTION
**Pull request by mrmckeb**
Issue: #4681

## What I did
Added support for `react-scripts` packages with names other than `react-scripts`. 

## How to test
[Create a fork](https://medium.com/@denis.zhbankov/maintaining-a-fork-of-create-react-app-as-an-alternative-to-ejecting-c555e8eb2b63) of `react-scripts` with a different name (or use an existing), and use that for your `--scripts-version` when running `create-react-app`.

### CODE REVIEW

**Review by chadfawcett — APPROVED** [review]
Looks good to me!

**Review by igor-dv — APPROVED** [review]
We need some CLI test fixture for this IMO

**Review by ndelangen — APPROVED** [review]

**Comment by mrmckeb** [comment]
Certainly @igor-dv and @ndelangen, I'll take a look at doing this over the weekend. Hopefully it'll be fairly straight-forward to test.

And thanks for your review too @chadfawcett.

**Comment by igor-dv** [comment]
I've played a bit with this in #4836 and It doesn't find for me the `react-scripts` pkg in the `cra-kitchen-sink` example. Might It be related either to monorepo or windows?

**Comment by igor-dv** [comment]
When I am debuggin this:

```js
let reactScriptsPath;

function getReactScriptsPath() {
  if (reactScriptsPath) return reactScriptsPath;
  const appDirectory = fs.realpathSync(process.cwd());
  const reactScriptsScriptPath = fs.realpathSync(
    path.join(appDirectory, '/node_modules/.bin/react-scripts')
  );
  reactScriptsPath = path.join(reactScriptsScriptPath, '../..');
  return reactScriptsPath;
}
```

in `cra-kitchen-sink`, I see that
```
reactScriptsScriptPath = 'root\examples\cra-kitchen-sink\node_modules\.bin\react-scripts'
```

Then

```
reactScriptsPath = 'root\examples\cra-kitchen-sink\node_modules'
```

And after when we are tring to use `isReactScriptsInstalled that does 

```
require(path.join(getReactScriptsPath(), 'package.json'));
```
path to `package.json` is wrong and doesn't point to the package.json in the `react-scripts`

**Comment by mrmckeb** [comment]
And does it work for you outside of that environment @igor-dv? And are you using WSL? I'm not home now, but can take a look later.

**Comment by igor-dv** [comment]
Even tests (cra-config) are failing locally for me, but passing in CI. Probably a windows thing =(

**Pull request merged**
